### ISSUE TITLE
[jest] Upgrade to jest 0.5-alpha and update to iojs

### ISSUE THREAD

**Issue by cpojer** [facebook/relay#10]

**Comment by zpao** [comment]
IMO, wait until you ship jest 0.5 stable. I think that's my plan for React.

**Comment by yungsters** [comment]
Just wondering, are there any planned changes between jest 0.5-alpha and stable?

**Comment by cpojer** [comment]
no more big breaking changes but I'd be lying if I said I have made up my mind about what will go in. I'll tag the final 0.5 either this week or next week, so there will probably not be an alpha.

I think the one thing I want to adopt though is that jest releases in the future will only happen if it was successfully deployed on our www codebase at Facebook, which is likely the biggest jest deploy. This makes sure that we don't fall behind on jest updates and also that jest is stable across a large number of test cases.





On Wed, Aug 12, 2015 at 8:10 PM -0700, "Timothy Yung" <notifications@github.com<mailto:notifications@github.com>> wrote:


Just wondering, are there any planned changes between jest 0.5-alpha and stable?
