### ISSUE TITLE
Allow a function to be passed to setVariables

### ISSUE THREAD

**Issue by Aweary** [facebook/relay#1007]
I was wondering if you could currently (or if in the future) pass a function to `setVariables` that takes the current `variables` object as its only argument and returns the next `variables` object.

Kind of like how in React you can do:

```js
this.setState(state => ({
  value: state.value + 1
}))
```

you could do:

```js
this.props.relay.setVariables(variables => ({
  value: variables.value + 1
}));
```

**Comment by josephsavona** [comment]
Thanks for asking about this. Passing a function instead of the variables object isn't currently supported - note also that `setVariables` aren't batched the way that sertState is in React. What's the use case for a function here?

**Comment by josephsavona** [comment]
In general we haven't seen a need for this. Please feel to comment with more information about your use-case and we can reopen to discuss further!

**Comment by Aweary** [comment]
I don't have any really good reasons other than 1) to be consistent with React's `setState` and 2) easier access to the existing `variables` (you don't have to do `this.props.relay.variables`)

If it's not already possible or (very) easily implemented then, yeah, I don't think it's worth the effort. Thanks @josephsavona
