### ISSUE TITLE
Relay creates invalid queries when argument field are identical

### ISSUE THREAD

**Issue by MarioJerkovicDickeys** [facebook/relay#1011]
If we have two connection types defined in GraphQL:

```javascript 
type Store implements Node {
  id: ID!
  number: Int
  label: String
  ....
}
and 

type District implements Node {
  id: ID!
  number: Int
  ...
}
```
Each one of them has its own custom sort argument. For store type is StoreSortType and for District is DistrictSortType.
They are defined like this:
```javascript
const StoreSortType = new GraphQLInputObjectType({
  name: 'StoreSort',
  fields: {
    byNumber: {
      type: SortDirectionType
    }
  }
});
const DistrictSortType = new GraphQLInputObjectType({
  name: 'DistrictSort',
  fields: {
    byNumber: {
      type: SortDirectionType
    }
  }
});

```
On the front end we have imported fragment from DistrictComponent and StoreComponent and each fragment has it's own sort argument, but the values inside it are identical.
 ```javascript 
sort: {byNumber: 'ASC'}
```
What relay does, it sees that those two objects/arguments are identical and crates an query like this:

```javascript
query ViewerQuery($sort_0:StoreSort!) {
  viewer {
    ...F2
  }
}

fragment F0 on Viewer {
  _storeConnection2aYrmE:storeConnection(first:14,sort:$sort_0) {
    edges {
      cursor,
      node {
      ...
      }
  }
}

fragment F1 on Viewer {
  _districtConnection4s1av7:districtConnection(first:14,sort:$sort_0) {
    edges {
      cursor,
      node {
      ...
      }
  }
}
```

As you can see the sort argument/variable is defined as StoreSort, and its reused in district and store, but it shouldn't be, as they are two separate input objects.

The error message: 
`Variable \"$sort_0\" of type \"StoreSort!\" used in position expecting type \"DistrictSort\".`

**Comment by josephsavona** [comment]
Thanks for reporting this. The printer needs to be changed to track variables separately based on their type - see the "create variable" method at the end of `printRelayOSSQuery`. I'll fix this today or on the weekend.

**Comment by mjurinci** [comment]
This is definitely an issue when you have same arguments but on different types, relay confuses them as being same type although they should be scoped based on their type, in application different models can have same attribute names and this makes filtering on them producing errors.
+1 for fixing this

**Comment by josephsavona** [comment]
Thanks again for reporting this, see #1016 for the fix.
