### ISSUE TITLE
If a GraphQL server isn't Relay compliant is using Relay as a client impossible or just harder?

### ISSUE THREAD

**Issue by kaqqao** [facebook/relay#1012]
Many GraphQL server implementations are still not supporting Relay, or at least not fully, but how big of a deal is this really? Can Relay not be used with those at all, or does it just require more work?

**Comment by josephsavona** [comment]
Can you clarify which products you're referring to that are not Relay-compliant? In general any GraphQL [server implementation](https://github.com/chentsulin/awesome-graphql#lib) can be used to create a GraphQL schema for use with Relay. Relay makes a few assumptions about the schema, which documented in the [GraphQL Relay Spec](http://facebook.github.io/relay/docs/graphql-relay-specification.html#content).

**Comment by kaqqao** [comment]
Oh. I now realize it is the schema that needs to be Relay compliant, not the server itself.

What was confusing me is that GraphQl-Java, for example, says "There is a very basic Relay support included", and the Elixir implementation just recently got Relay support, so I was figuring there was something magical needed. But it turns out all this meant is that convenience functions for making a Relay-compliant schema were added.

Cool. Thanks a lot!

**Comment by kaqqao** [comment]
Btw, my original question still sort of stands. If the schema isn't formed to Relay's expectations, is Relay totally unusable or does it mean you must manually implement paging etc?

**Comment by josephsavona** [comment]
The Node and Mutation specifications are required in order for Relay to work, however connections are optional. You can always define a field such as `things(offset: 20, limit: 10)` and Relay will treat it as a normal field and fetch the list of items.

**Comment by kaqqao** [comment]
Exactly the info I was looking for! Thanks a bunch for your kind help!
