### ISSUE TITLE
Generated mutation query is missing some fields

### ISSUE THREAD

**Issue by DanielHuisman** [facebook/relay#1019]
I have set up a basic Relay mutation to add a user, but once executed it returns this error/warning:

> Warning: writeRelayUpdatePayload(): Expected response payload to
> include the newly created edge 'changedUserEdge' and its 'node' field.
> Did you forget to update the 'RANGE_ADD' mutation config?

I noticed Relay leaves out the `changedUserEdge` node on the mutation payload and I have no idea why. I looked at a few Relay examples, but the mutation is constructed exactly the same way.

The mutation, the React component I call it from and the generated query can be found [in this gist](https://gist.github.com/DanielHuisman/198edb1e81bbc3ced596f0224e003022).

I used [graffiti-mongoose](https://github.com/RisingStack/graffiti-mongoose) to generate my GraphQL schema.

**Comment by josephsavona** [comment]
@DanielHuisman Are you using the latest release or master? We've recently added much more informative error messaging and feedback on range add mutations - I'd suggest giving master a try and see if that helps.
