### ISSUE TITLE
fragments on lists

### ISSUE THREAD

**Issue by gilesbradshaw** [facebook/relay#1020]
Given a component whose fragment contains a list such as..

````
fragment on Whatever {
        list: whatevers(first:100) {
          edges {

````

it would be nice to have a subcomponent to display that list however I don't think you can do..
````
fragment on Whatever {
        list: whatevers(first:100) {
          edges {
              ${MyListDisplayer.getFragment('listOfWhatever')}

````

can you?  

If you can what is myListDisplayer's fragment's type (????) ?

````
fragments: {
    listOfWhatever: ()=> Relay.QL`
      fragment on ???? {
          node {

```` 

if you can't do you think it would be a good idea if you could?

**Comment by josephsavona** [comment]
Thanks for asking. Relay supports fragments on the `edges` field - the type would be whatever you have in your schema. For example, you might have a structure like:

```
type User {
  friends(first: Int, after: String, ...): FriendsConnection
}
type FriendsConnection {
  edges: [FriendsConnectionEdge]
  pageInfo: ...
}
type FriendsConnectionEdge {
  cursor: String
  node: User
}
```

Where the inner fragment would be defined as:

```
fragments: {
  edges: () => Relay.QL`
    fragment on FriendsConnectionEdge @relay(plural: true) {
      node { ... }
    }
  `,
}
```

Note the use of `@relay(plural: true)` to tell Relay that the edges prop will receive an array of items, not just one.

**Comment by gilesbradshaw** [comment]
Brilliant!  Thank you very much :)

**Comment by josephsavona** [comment]
Happy to help!
