### ISSUE TITLE
Prepopulating caches

### ISSUE THREAD

**Issue by bigblind** [facebook/relay#1021]
Unless your pages are hosted as a static site, your server can include initial data with the request for the HTML, determined by the URL. It would be cool if there was a way to prepopulate the cache. For example, when I go to /user/123, the client could send a json representation of that graphql node down to the client. That would save a roundtrip. But depending on the data model, even more roundtrips could be saved by something like this.

**Comment by KyleAMathews** [comment]
Check out this issue https://github.com/facebook/relay/issues/136

**Comment by josephsavona** [comment]
Yup, check out #136 as well as [isomorphic-relay](https://github.com/denvned/isomorphic-relay/). That should cover this use-case - please feel free to comment here if you think something's missing and we can reopen.
