### ISSUE TITLE
onReadyStateChange - forceFetch firing 3 times when have data in cache

### ISSUE THREAD

**Issue by mailaneel** [facebook/relay#1023]
using relay@0.7.3

``` js
this.props.relay.forceFetch(variables, (state) => {
  console.log(state);

  // this is where I am changing component state to loading based on state

  this.setState({
    isLoading: !state.ready && !state.error,
    fetchError: state.error
  })
})

```

Expected as per docs:
`{stale: true, ready: true, done: false}`
`{stale: false, ready: true, done: true}`

Current:
`{stale: false, ready: false, done: false}`
`{stale: true, ready: true, done: false}`
`{stale: false, ready: true, done: true}`

This causes page flicker which shows loader for a split second

**Comment by josephsavona** [comment]
cc @yungsters

**Comment by yungsters** [comment]
Hmmm... this sounds like a plain old bug. If we have data on the client that is immediately available for rendering, we should not be firing `{stale: false, ready: false, done: false}`. The bug is probably somewhere in how `RelayContainer` is using `RelayReadyState`.

**Comment by yuzhi** [comment]
I thought we fire the first readyStateCallback with `{stale: false, ready: false, done: false}` to signify that we are fetching data from the server for this `forceFetch`. This code is in `GraphQLQueryRunner`, where we check fired it when we have items `remainingRequiredFetchMap`

**Comment by mailaneel** [comment]
Doesn't ```{stale: true}``` imply relay is going to refresh data from server? calling with stale:false and ready: false is causing extra renders in component

**Comment by wincent** [comment]
This one is getting pretty stale at this point (almost a year old) so I'm closing it due to inactivity. As far as I can tell, this code underwent a significant overhaul in d56cc5f55d5efb9f99f5 and has been touched a few times since then. I suspect that the issue no longer applies. Please feel free to open a new issue if you think there's still a bug in there. Thanks for the report!
