### ISSUE TITLE
When working with react-native, Relay.QL is cached somewhere hidden.

### ISSUE THREAD

**Issue by joonhocho** [facebook/relay#1028]
I am currently using relay together with react-native.
I have found that whenever I make a change to GraphQL schema, there is a hidden cache somewhere that needs to be manually invalidated for the Relay.QL defined for Relay containers.

I have tried these steps:
- rm -rf ios/build
- "Reset contents and settings" on iOS Simulator
- Quit all react-native packager processes
- rm -rf $TMPDIR/react-*

These are not enough and still causes invalid query error.
I would have to make some changes to Relay.QL fragments while running react-native packager to invalidate the hidden caches.

I am not sure if this is relay or react-native problem.

**Comment by joonhocho** [comment]
I believe this is react-native issue. Closing the issue until proven otherwise.

**Comment by sibelius** [comment]
Just commenting here, if someone has the same issue

`react-native start --reset-cache` solves the issue

**Comment by sibelius** [comment]
@joonhocho how did u solve ur problem?

**Comment by joonhocho** [comment]
@sibelius Yes, your answer worked for me!

**Comment by Naoto-Ida** [comment]
@sibelius You're awesome!
