### ISSUE TITLE
Android Network Request Failed on TodoMVC Example

### ISSUE THREAD

**Issue by plraphael** [facebook/relay#1033]
Hello,

After a lot of work, I finally got the TodoMVC example to work on my Ubuntu 15.10. Well, at least, kind of. What's happening now is that I can run the project on my phone (`react-native run-android`), it launches but only displays a white screen with the message "Network request failed" on the bottom. I also ran `npm start` to start the GraphQL server and it says it is running on "http://localhost:8080" before starting the app on my phone.

I'm running the project on Android 6.0.
I can run a normal React Native project (react-native init project). Any help will be appreciated.

Thanks,

Pedro.

![screenshot_20160408-154503](https://cloud.githubusercontent.com/assets/645621/14394214/8311a576-fda1-11e5-89b5-bc61faea7bc2.png)

**Comment by nikhildaga** [comment]
I can confirm. Facing the same issue.

**Comment by sibeliusseraphini** [comment]
You should use `adb reverse` on Android (https://facebook.github.io/react-native/docs/running-on-device-android.html#content)

or FBPortForwarding on iOS (https://github.com/facebook/react-native/tree/master/Tools/FBPortForwarding)

This command will redirect the localhost of the device in that port to the localhost port of your computer

**Comment by ringzhz** [comment]
`adb reverse tcp:8080 tcp:8080` does the trick for me.

**Comment by josephsavona** [comment]
@plraphael do the suggestions to use `adb reverse` help? This looks like a configuration issue.

**Comment by steveluscher** [comment]
Android network connectivity is covered [in the README](https://github.com/facebook/relay/blob/master/examples/TodoMVC/README.md#android).

**Comment by Naoto-Ida** [comment]
This is happening for me on iOS (react-native is `0.29.0`).
I can't really get anymore info on this from the console log.

**Comment by Naoto-Ida** [comment]
Ok, did some console logging in the `fetchWithRetries.js` inside of Relay.
The `init` variable being passed into `fetch` is as below:
```
{"body":{\"query\":\"query Index {\\n viewer\\n}",\"variables\":{}}"
```

Also, response is returning a 400, which is from [express-graphql](https://github.com/graphql/express-graphql#http-usage).

I'm not that familiar with Relay, so help would be much appreciated.

**Comment by Jaikant** [comment]
@Naoto-Ida  did you manage to find the reason for your error? I am facing the same issue.

**Comment by sibelius** [comment]
@Jaikant check if u can access ur graphql server from the browser of your device or emulator

if this is not possible, you should try to use an IP or use `adb reverse`

**Comment by Jaikant** [comment]
@sibelius I am facing this issue intermittently - it's completely random and when I hit the issue the graphql server is not reachable from my device. Something weird is going on in the network (Surprising as it is the private network in my home). Is there a way to catch this error on the react native side so I can display the flaky network error, rather than a blank screen - as this could happen in production too.

**Comment by sibelius** [comment]
you could try to use RelayNetworkDebug to check Relay queries and also use NetInfo (https://facebook.github.io/react-native/docs/netinfo.html) to check if there is network available or not

**Comment by Jaikant** [comment]
@sibelius thx! NetInfo is cool. I think I am tending towards using the render of Relay.Renderer it is kind of more abstracted.
