### ISSUE TITLE
When will we get new release and meeting-notes? 

### ISSUE THREAD

**Issue by zjlovezj** [facebook/relay#1035]
Not sure it is the right place to ask :)

Thanks for the hard work.
It seems there are some major changes after the latest release.
I'm about to start a new project and I want to use relay.
So I wish I could know more latest information about it.

No pressure.

**Comment by wincent** [comment]
@zjlovezj: Thanks for asking!

You can expect a release soon. @steveluscher was talking about preparing one as early as today, but as you know, sometimes things come up so it could end up sliding to next week, so we'll see exactly when it falls.

As for the meeting notes, I believe @josephsavona was going to publish them, but he's been busy with other work so I think I'll just go ahead and do it now.

**Comment by wincent** [comment]
New notes added via 57fb2b1567f.

**Comment by zjlovezj** [comment]
Thank you, I really appreciate it.

**Comment by josephsavona** [comment]
Thanks @wincent!
