### ISSUE TITLE
Is it possible to move meeting notes to separate repository?

### ISSUE THREAD

**Issue by vslinko** [facebook/relay#1039]
I want to subscribe to updates of meeting notes, but I don't want to watch the whole `relay` repository.

**Comment by josephsavona** [comment]
We chose to add notes here so that existing subscribers would see them. If enough people share this concern we'd be happy to reconsider. In the meantime, we also plan to announce new meeting notes on twitter with the #relayjs tag.

**Comment by wincent** [comment]
Going to close this for now. @vslinko, let us know if watching for updates on twitter doesn't work for you.

Generally, [one](https://twitter.com/wincent) [of](https://twitter.com/en_JS) [us](https://twitter.com/steveluscher) will either announce the publication of new notes, and the others will retweet them.

If the signal-to-noise isn't high enough there, we can consider making a Relay-specific Twitter handle that would publish only Relay-specific stuff (as opposed to Relay-stuff plus tweets-about-what-we-just-ate-for-lunch).

**Comment by vslinko** [comment]
It would be awesome to have a Relay-specific twitter account.
