### ISSUE TITLE
Make route queries more like mutations

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#104]
See discussion in #20.

I'll try to get this in the next day or so if nobody beats me to it :smile:

**Comment by devknoll** [comment]
@yungsters Are there any internal users of `buildRQL.Query`? Seems like it's only being used for routes. I'll probably make this change there if not.

**Comment by yungsters** [comment]
@devknoll Nope, `getRelayQueries` is the only caller of `buildRQL.Query`.

**Comment by devknoll** [comment]
#115 with the changes, so I'm going to close this issue out.
