### ISSUE TITLE
Relay Mutation fragment props are not set for fields with arguments.

### ISSUE THREAD

**Issue by joonhocho** [facebook/relay#1040]
For the following mutation, `tag.id` and `tag.name` is set correctly, but `tag.isTagged` is missing from `props.tag`.
I think it has to do with that the field requires an argument.
I have tried to add or remove other fields and every other fields work as expected, except for `isTagged`. 

``` javascript
  static initialVariables = {
    profileId: null,
  }

  static prepareVariables(prevVars) {
    // prevVars.profileId is set correctly.
    return prevVars;
  }

  static fragments = {
    tag: () => Relay.QL`
      fragment on Tag {
        id
        name
        isTagged(profileId: $profileId)
      }
    `,
  }

  getMutation() {
    // id and name are set correctly, but, is missing 'isTagged'.
    console.log(this.props.tag);

    return this.props.tag.isTagged ?
      Relay.QL`mutation { tagRemove }` :
      Relay.QL`mutation { tagAdd }`;
  }

  getVariables() {
    return {
      tagId: this.props.tag.id,
      profileId: this.props.profileId,
    };
  }
```

**Comment by josephsavona** [comment]
Thanks for reporting this. To address problems such as this we've created a new, static mutation API: [`Relay.GraphQLMutation`](https://facebook.github.io/relay/docs/api-reference-relay-graphql-mutation.html) which we recommend. I'm going to close this issue, but please let us know if you have issues with the new mutation API and we'll be happy to work with you to address them!
