### ISSUE TITLE
Component not sent fresh data when using setVariable with an input object.

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#1044]
I have an input object type to set filters on a connection. I can set a string for `size`, `industry`, and `type`. They either have a string value set or they're not set. In my UI when I trigger setting one of these filters, the first time I do this the query to my GraphQL is triggered and the UI updates with the response. But the second time I change the filters, the correct query is sent and received but the UI isn't updated. But then the third time I change the filters, the second query's results are now shown. This pattern of being one query behind continues as long as I bother to keep clicking.

If I console.log `this.props.relay.variables.filters` in my render function, the filters object there is always up-to-date.

I first saw this behavior on Relay 0.6 and updated just now to 0.8 in hopes it was fixed but am still seeing the problem.

**Comment by KyleAMathews** [comment]
Ok, after a bit more debugging the problem seems to be Relay isn't looking at input objects variables closely enough to see if the query changed. I added a `counter` variable that I'm just incrementing with every `setVariable` and now the UI is updating correctly.

**Comment by wincent** [comment]
Sounds like you have a work around (yay!) but also sounds like there is a real bug here. Would you be able to come up with a failing test case?

**Comment by KyleAMathews** [comment]
I don't have a ton of extra time the next couple of weeks but if you could point me to where checking for query changes happens I could take a stab at it.

**Comment by josephsavona** [comment]
@KyleAMathews The logic for checking Relay variables is at https://github.com/facebook/relay/blob/master/src/container/RelayContainerComparators.js#L116-L121

**Comment by wincent** [comment]
Closing this one as we're unlikely to do any further work related to the `setVariables` API, which has been completely replaced in Relay Modern (and which we just officially released).
