### ISSUE TITLE
Mutation contains wrong @include directive argument

### ISSUE THREAD

**Issue by saywhaat** [facebook/relay#1047]
Here is a [sample](https://facebook.github.io/relay/prototyping/playground.html#source=class%20Story%20extends%20React.Component%20%7B%0A%20%20showComments%28%29%20%7B%0A%20%20%20%20let%20%7B%20relay%20%7D%20%3D%20this.props%3B%0A%20%20%20%20relay.setVariables%28%7B%20showComments%3A%20!relay.variables.showComments%20%7D%29%3B%0A%20%20%7D%0A%20%20change%28%29%20%7B%0A%20%20%20%20let%20%7B%20story%20%7D%20%3D%20this.props%3B%0A%20%20%20%20Relay.Store.commitUpdate%28new%20Mutation%28%7B%20story%20%7D%29%29%3B%0A%20%20%7D%0A%20%20render%28%29%20%7B%0A%20%20%20%20let%20%7B%20title%2C%20comments%20%7D%20%3D%20this.props.story%3B%0A%20%20%20%20return%20%28%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Ch1%3E%7Btitle%7D%3C%2Fh1%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7Bthis.change.bind%28this%29%7D%3EChange%20something%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbr%2F%3E%0A%20%20%20%20%20%20%20%20%3Clabel%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cinput%20type%3D'checkbox'%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20checked%3D%7Bthis.props.relay.variables.showComments%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onChange%3D%7Bthis.showComments.bind%28this%29%7D%0A%20%20%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20Show%20comments%0A%20%20%20%20%20%20%20%20%3C%2Flabel%3E%0A%20%20%20%20%20%20%20%20%3Cul%3E%0A%20%20%20%20%20%20%20%20%20%20%7B%28comments%20%7C%7C%20%5B%5D%29.map%28%28%7B%20id%2C%20text%20%7D%29%20%3D%3E%20%28%3Cli%20key%3D%7Bid%7D%3E%7Btext%7D%3C%2Fli%3E%29%29%7D%0A%20%20%20%20%20%20%20%20%3C%2Ful%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%29%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20StoryContainer%20%3D%20Relay.createContainer%28Story%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20showComments%3A%20false%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20story%3A%20%28%29%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Story%20%7B%0A%20%20%20%20%20%20%20%20title%2C%0A%20%20%20%20%20%20%20%20comments%20%40include%28if%3A%20%24showComments%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%24%7BMutation.getFragment%28'story'%29%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D%29%3B%0A%0Aclass%20Mutation%20extends%20Relay.Mutation%20%7B%0A%20%20static%20fragments%20%3D%20%7B%0A%20%20%20%20story%3A%20%28%29%20%3D%3E%20Relay.QL%60fragment%20on%20Story%20%7B%20id%20%7D%60%0A%20%20%7D%0A%20%20getMutation%28%29%20%7B%0A%20%20%20%20return%20Relay.QL%60mutation%20%7B%20change%20%7D%60%3B%0A%20%20%7D%0A%20%20getFatQuery%28%29%20%7B%0A%20%20%20%20return%20Relay.QL%60fragment%20on%20ChangePayload%20%40relay%28pattern%3A%20true%29%20%7B%20story%20%7D%60%0A%20%20%7D%0A%20%20getVariables%28%29%20%7B%20return%20%7B%7D%3B%20%7D%0A%20%20getConfigs%28%29%20%7B%0A%20%20%20%20return%20%5B%7B%0A%20%20%20%20%20%20type%3A%20'FIELDS_CHANGE'%2C%0A%20%20%20%20%20%20fieldIDs%3A%20%7B%0A%20%20%20%20%20%20%20%20story%3A%20this.props.story.id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%5D%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Route%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'Route'%3B%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20story%3A%20Component%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20Query%20%7B%0A%20%20%20%20%20%20%20%20story%20%7B%0A%20%20%20%20%20%20%20%20%20%20%24%7BComponent.getFragment%28'story'%29%7D%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0AReactDOM.render%28%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BStoryContainer%7D%0A%20%20%20%20route%3D%7Bnew%20Route%28%29%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A%29%3B%0A&schema=import%20%7B%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%20%20GraphQLList%0A%7D%20from%20'graphql'%3B%0A%0Aimport%20%7B%0A%20%20globalIdField%2C%0A%20%20mutationWithClientMutationId%2C%0A%20%20nodeDefinitions%2C%0A%7D%20from%20'graphql-relay'%3B%0A%0Aconst%20STORY%20%3D%20%7B%20id%3A%201%2C%20title%3A%20'Story'%20%7D%3B%0A%0Aconst%20%7B%20nodeInterface%2C%20nodeField%20%7D%20%3D%20nodeDefinitions%28%0A%20%20%28%29%20%3D%3E%20STORY%2C%0A%20%20%28%29%20%3D%3E%20StoryType%0A%29%3B%0A%0Aconst%20CommentType%20%3D%20new%20GraphQLObjectType%28%7B%0A%20%20name%3A%20'Comment'%2C%0A%20%20fields%3A%20%7B%0A%20%20%20%20id%3A%20globalIdField%28'Comment'%29%2C%0A%20%20%20%20text%3A%20%7B%0A%20%20%20%20%20%20type%3A%20GraphQLString%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%29%3B%0A%0Aconst%20StoryType%20%3D%20new%20GraphQLObjectType%28%7B%0A%20%20name%3A%20'Story'%2C%0A%20%20fields%3A%20%7B%0A%20%20%20%20id%3A%20globalIdField%28'Story'%29%2C%0A%20%20%20%20title%3A%20%7B%0A%20%20%20%20%20%20type%3A%20GraphQLString%0A%20%20%20%20%7D%2C%0A%20%20%20%20comments%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLList%28CommentType%29%2C%0A%20%20%20%20%20%20resolve%3A%20%28%29%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20console.log%28'GetComments'%29%3B%0A%20%20%20%20%20%20%20%20return%20%5B1%2C2%2C3%2C4%2C5%5D.map%28id%20%3D%3E%20%28%7B%20id%2C%20text%3A%20%60comment%20%24%7Bid%7D%60%20%7D%29%29%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20interfaces%3A%20%5BnodeInterface%5D%0A%7D%29%3B%0A%0Aconst%20changeMutation%20%3D%20mutationWithClientMutationId%28%7B%0A%20%20name%3A%20'Change'%2C%0A%20%20outputFields%3A%20%7B%0A%20%20%20%20story%3A%20%7B%0A%20%20%20%20%20%20type%3A%20StoryType%2C%0A%20%20%20%20%20%20%20%20resolve%3A%20%28%29%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20console.log%28'GetStoryAfterMutation'%29%3B%0A%20%20%20%20%20%20%20%20%20%20return%20STORY%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20mutateAndGetPayload%28%29%7B%0A%20%20%20%20return%20%7B%7D%3B%0A%20%20%7D%0A%7D%29%3B%0A%0Aexport%20default%20new%20GraphQLSchema%28%7B%0A%20%20mutation%3A%20new%20GraphQLObjectType%28%7B%0A%20%20%20%20name%3A%20'Mutation'%2C%0A%20%20%20%20fields%3A%20%28%29%20%3D%3E%20%28%7B%0A%20%20%20%20%20%20change%3A%20changeMutation%0A%20%20%20%20%7D%29%0A%20%20%7D%29%2C%0A%20%20query%3A%20new%20GraphQLObjectType%28%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20%28%29%20%3D%3E%20%28%7B%0A%20%20%20%20%20%20node%3A%20nodeField%2C%0A%20%20%20%20%20%20story%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20StoryType%2C%0A%20%20%20%20%20%20%20%20resolve%3A%20%28%29%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20console.log%28'GetStory'%29%3B%0A%20%20%20%20%20%20%20%20%20%20return%20STORY%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%29%0A%20%20%7D%29%0A%7D%29%3B%0A). I have a story which is fetching immediately and a comment list fetching after checkbox checking. Imagine that the "Change something" button mutates everything we have (the story and the comment list).

I found the result of the next scenario unexpected:
1. check checkbox
2. uncheck
3. click change button

The mutation query is trying to fetch the story aswell as comments. Despite `showComments` variable is `false` query contains part: `comments @include(if:true)`.
Receiving the comment list from database can be a heavy operation so I dont want the mutation perform it if `showComments` is `false.`

Is it bug or I miss something?

Thanks
Dmitry

**Comment by NevilleS** [comment]
I think this is generally just "the way it works" right now. Basically, every query that you make for a given node is tracked by the store, and then when a mutation executes those queries are all refetched (based on intersection with the fat query).

This means that, even if you aren't *currently* rendering the `comments @include(if:true)` fragment, it's still being tracked and therefore will be refetched.

This behaviour is certainly suboptimal, but is done to ensure consistency. If you were to click the checkbox again, Relay would show the correct, modified comments. If you *didn't* update the comments as a result of that mutation, one of two things would happen:

1) Relay would show the wrong, un-mutated comments (oops)
2) Relay would need to refetch the comments then

I think in your case you'd prefer the second option, but there's no way to express that in Relay yet. I think some ways to *explicitly* expire data might work (see #978), but it'd be difficult to do correctly.

...does that make sense?

**Comment by saywhaat** [comment]
Thanks for detailed answer. In my case marking nodes as untracked (explicit expiration functionality) is exactly what I need.

**Comment by wincent** [comment]
Also note that we're in the process of adding a low-level mutations API based on static queries (no tracked/fat query magic by default) which you may be able to use in future to get at least part of what you want (ie. not fetching the `comments`). But as @NevilleS says, if you want consistency (and you probably do), we'll need something more.

**Comment by wincent** [comment]
(Spring cleaning.) This one is pretty stale now, so closing it out. Just to close the loop a little, the low-level mutations API went in quite a while ago (see `RelayGraphQLMutation`) and if you look on the master branch you'll see we've been rolling out pieces of a new API and core, and will continue to do so in the coming weeks or months.

Thanks for bringing this up and contributing to the discussion.
