### ISSUE TITLE
Query with different variables get out of sync (i.e. show inconsistent data)

### ISSUE THREAD

**Issue by Globegitter** [facebook/relay#1052]
We have a component that displays a simple list of tickets as follows:

```js
// TicketsTable
const RELAY_QUERY = {
  initialVariables: {
    assignee: ASSIGNEE_FILTER.value,
    status: 'OPEN'
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Query {
        somethingTickets: tickets(category: SOMETHING, assignee: $assignee, status: $status) {
          ${UpdateTicketMutation.getFragment('ticket')}
          id
          title
          creationTs
          ...
        }
        elseTickets: tickets(category: ELSE, assignee: $assignee, status: $status) {
          id
          title
          creationTs
          ...
        }
      }`
  }
};
```
That page also has filters to change the status between `OPEN/CLOSED/ALL` tickets.

When you click on a specific ticket in the list we use the `node(id:....)` query to fetch for additional ticket data and that page has following fragment defined:

```js
// TicketPage
const RELAY_QUERY = {
  initialVariables: {
    ticketId: ''
  },
  fragments: {
    ticket: () => Relay.QL`
      fragment on Ticket {
        otherFields
        ...
        ${UpdateTicketMutation.getFragment('ticket')}
      }
    `
  }
};
```
The displaying of the list of tickets and the individual ticket all works perfectly.

Then we have a simple mutation to close a ticket, which looks as follows:
```
// mutation
export class UpdateTicketMutation extends Relay.Mutation {
  static fragments = {
    ticket: () => Relay.QL`
      fragment on Ticket {
        id
      }`
  };

  getMutation() {
    return Relay.QL`mutation {updateTicket}`;
  }

  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: {
        ticket: this.props.ticket.id
      }
    }];
  }

  getFatQuery() {
    return Relay.QL`
      fragment on UpdateTicket {
        clientMutationId,
        ticket {
          status
        }
      }
    `;
  }

  getVariables() {
  ...
  }
}
```

The request is made successfully, I can see the right data returned and when I look at the cache (via `console.log(Relay.Store.getStoreData())`) I can see that status of the ticket updated. I also see the list of tickets updated in the `TicketsTable` (e.g. if filter `OPEN` is active, the closed ticket immediately disappears), but when I click around the filters, e.g. the `CLOSE` filter ( `this.props.relay.setVariables({status: 'CLOSED'});`) the ticket does not show up there and seems to have entirely disappeared (at least visually).

I am not sure what exactly is happening and happy to try and provide a more complete example, but it seems to me like only the 'active' query is updated but not the others if they are already in the cache (if the other queries with status `OPEN/ALL` have not been triggered before, i.e. they are not in the cache it loads fine. So the bug only appears once the queries have been loaded in the cache).

I am also happy to do some more debugging/ provide a more complete example/look into it myself with a couple of pointers.

**Comment by josephsavona** [comment]
If I understand correctly, the app fetches a list of tickets which may be have a status of open or closed, and the mutation is toggling the status. With a fields change mutation Relay will update the scalar fields of an object - hence why you are seeing the ticket's `status` change in the store. However Relay does not know anything about range filter calls - in `tickets(status: $status)`, Relay doesn't know what the `status` field means. Put another way, Relay currently can't sort/filter connection items; the server (or your mutation config) has to tell Relay how to update connections.

To make this work, the mutation would have to specify a range add/delete config to tell Relay which variations of connection arguments are affected. Use range add to specify that a now-open ticket goes in the `tickets(status: "OPEN")` connection and a range delete to specify that the same ticket is no longer in the `tickets(status: "CLOSED")` connection.

This is definitely a bit cumbersome and we're open to suggestions about making this simpler.

**Comment by josephsavona** [comment]
@Globegitter Also, thanks for taking the time to provide such a clearly written and well-documented issue.

**Comment by Globegitter** [comment]
@josephsavona Thank you for providing such a clear answer, that does make sense. Intuitively yes, it does feel a bit cumbersome but I am also really just starting to understand how all the different pieces within Relay work under the hood. 

You are saying the server can tell Relay how to update the cache? How is that possible? I haven't seen any docs about that.

**Comment by Globegitter** [comment]
Also I will close this for now as the issue does seem to be resolved (won't get to fix it until monday).

**Comment by nodkz** [comment]
If somebody googled this topic and wants to know how to fetch additional data.
Read this Joseph's answer: http://stackoverflow.com/a/34405708/3340384
Still actual on August'16.
