### ISSUE TITLE
Where to put a more flux-like store variable

### ISSUE THREAD

**Issue by transedward** [facebook/relay#106]
I'm currently working on an example from flux-chat to relay
https://github.com/transedward/relay/tree/master/examples/chat
I tried remove everything from flux, but encounter some problem
For example: How to deal with currentID of ThreadStore in Flux when user clicking thread
Since it's not something you would like to put in database but a necessary state for application
I come up with two solution:

1. put in connectionField like todoApp completeCount, 
https://github.com/facebook/relay/blob/master/examples/todo/data/schema.js#L88
but since resolve function can only get connection back, I don't where I can send thread.id into function and get access to it?

2. like the bottom part of this, http://facebook.github.io/relay/docs/guides-routes.html#content
`addEventListener` for `pushState`, and every time you click thread, then `window.pushState({currentID}, '')`, but stored in a variable in `Relay.createContainer`
like I do it here, https://github.com/transedward/relay/blob/master/examples/chat/js/components/MessageSection.js#L62
But seems like Relay will parse this before any component mounted, you can't access any history state here
I prefer this approach because in the future I can do thing like `/thread/{id}`
then parse the `id` for `currentID` but by default when `/` then display the newest thread

I would to hear some feedback and suggest on this, thanks

**Comment by josephsavona** [comment]
1. Relay currently only supports the caching of server data. To store purely client state, such as the  `currentID` representing the active message thread, we recommend continuing to use a Flux store or similar solution. We're working to support non-server data as a future enhancement.

2. It's a bit unclear what you're trying to do here with routing. Can you provide more specific links to where you have the Route configured with a path of `/thread/{id}`, and how you're managing routing?

**Comment by coodoo** [comment]
@josephsavona speaking of routing, is there more detailed example on how relay works with multiple routings and view-switching? As far as I can see currently all examples are single-routed, thanks.

**Comment by josephsavona** [comment]
cc @steveluscher who was going to work on an example with multiple routes

**Comment by transedward** [comment]
> where you have the Route configured with a path of /thread/{id}

Sorry I need to rephrase: in the future, seems it's a simple app, I just store in `history.state`
But if state works here, it's not difficult to build a simple "relay-router"
But if I didn't figure it wrong, the starting of `Relay.createContainer` is before any lifecycle of `React`, right?
So we can't put any expression like `history.state.currentID` in `initialVariables` property, it has to be `value` like `123`
In this way, we can't let '/' has a default route to '/threads/{threads.egdes[0].node.id}'

**Comment by steveluscher** [comment]
Lots of routing related work coming down the pipe in #118 and relayjs/relay-starter-kit#15!

**Comment by transedward** [comment]
thanks for the nice example, I'm almost done with the example
still stuck on here https://github.com/devknoll/relay-nested-routes/issues/7
if it's working, are u interested in accepting a PR? @steveluscher @josephsavona

**Comment by transedward** [comment]
now the example is working except that AddMessageMutation not optimistically update as expected
Probably not update all the relevant view as I needed
Anyone with interest can see it here: https://github.com/transedward/relay
and one with hot-reloading and source-map to make debug happy here: https://github.com/transedward/relay-chat
I would also try new approach to improve the latter one

**Comment by vladar** [comment]
It would be great if components could declare client-side data requirements in the same container. 

If we could extend server schema on the client with transient data - we could have unified interface for dealing with data, regardless of it being client- or server-based.

Custom network layer could probably handle data splitting on request / merging it back on response.

**Comment by clentfort** [comment]
See #114 for a proposed API on how to access in-memory (or similar) data.

**Comment by vladar** [comment]
@clentfort thanks for sharing - missed that one.

**Comment by josephsavona** [comment]
@transedward this thread has gotten a bit off-topic. Were you able to resolve the issue with optimistic updates for `AddMessageMutation`s?

**Comment by transedward** [comment]
@josephsavona No, as I  reported #135, I would post a more explained-through there
You can close this issue if you guys think the issue about client side data managing is well under tracked.
I have gotten the route working. So I get the answer with my original question

**Comment by josephsavona** [comment]
Yeah, we're tracking the client-side data management enhancement in #114 - thanks for filing this!
