### ISSUE TITLE
how to override a particular item's variables from a parent container

### ISSUE THREAD

**Issue by mjhlybmwq** [facebook/relay#1063]
When `this.props.relay.setVariables` is invoked in `componentWillReceiveProps` or `componentDidUpdate`, no request is sent to the server and my view doesn't update.
Here's some code to explain my problem.

my component:
```javascript
class Widget extends React.Component {
  componentWillReceiveProps(nextProps) {
    this.props.relay.setVariables({
      showInfo : nextProps.showInfo
    });// no request is sent
  }
  componentDidUpdate(prevProps, prevState) {
    // if(prevProps.showInfo !== this.props.showInfo) {
    //   this.props.relay.setVariables({
    //     showInfo : this.props.showInfo
    //   });
    // }
    // no request is sent
  }
  render() {
    var {name, info} = this.props.widget;
    var infoComponent = info ? (<div>{info}</div>) : "";
    return (
      <div>
        <span onClick={()=>{
          this.props.click && this.props.click(); // this will change this.props.showInfo
        }}>{this.props.widget.name}</span>
        {infoComponent}
        <br />
        <br />
      </div>
    );
  }
}
```

my container:
```javascript
const WidgetContainer = Relay.createContainer(Widget, {
  initialVariables : {
    showInfo : false
  },
  fragments : {
    // fetch extra info according to the variables 
    widget : () => Relay.QL`
      fragments on Widget {
        name,
        info @include(if : $showInfo)
      }
    `,
  }
});
```

**Comment by josephsavona** [comment]
It looks like you want the parent component to override the `$showInfo` variable, and fetch the data accordingly. Instead of using willReceiveProps/didUpdate - which would cause a second round trip - you can do this in a single round trip:

```javascript
// Parent of WidgetContainer

render() {
  render <WidgetContainer showInfo={true} /> // <- also pass the same value in props
}

Relay.createContainer(..., {
  fragments: {
    widget: () => Relay.QL`
      fragment on Foo {
        ${WidgetContainer.getFragment('widget', {showInfo: true})} # override the variable in call to `getFragment`
```

More generally, we recommend avoiding data-fetching in willReceiveProps/didUpdate and using [componentDidMount instead](https://github.com/facebook/relay/issues/1048#issuecomment-210189002).

**Comment by mjhlybmwq** [comment]
I don't think that's the solution. 
The parent holds a list of WidgetContainers, and I want each WidgetContainer fetch its own data when its `props.showInfo` is set to true.
I just try to make a simple accordion. Here's the parent of WidgetContainers:
```
class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      selectedWidgetId : ""
    }
  }
  render() {
    return (
      <div>
        <h1>Widget list</h1>
        <ul>
          {this.props.viewer.widgets.edges.map(edge =>
            <WidgetContainer
                widget={edge.node}
                key={edge.node.id}
                showInfo={edge.node.id === this.state.selectedWidgetId}
                click={()=>this.setState({
                  selectedWidgetId : edge.node.id
                })}
            />
          )}
        </ul>
      </div>
    );
  }
}

export default Relay.createContainer(App, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        widgets(first: 10) {
          edges {
            node {
              id,
              ${WidgetContainer.getFragment('widget')},
            },
          },
        },
      }
    `,
  },
});
```

**Comment by mjhlybmwq** [comment]
Still no idea? 😳

**Comment by josephsavona** [comment]
I see, thanks for clarifying. In this case using willReceiveProps definitely makes sense. Calling setVariables at that point should work - if it doesn't that's a bug.

**Comment by mjhlybmwq** [comment]
Finally, I have figured out what goes wrong. The `props` overrides the `variables`, and breaks `setVariables`. I don't know why `getVariablesWithPropOverrides` is called in RelayContainer's `componentWillReceiveProps` and no request is sent.

**Comment by mjhlybmwq** [comment]
same issue to https://github.com/facebook/relay/issues/309

**Comment by josephsavona** [comment]
@mjhlybmwq Thanks for the follow up!

Looking at your use-case more closely, this looks like the same issue as #1048. Regardless of what API we used to pass variables from parent to child (the topic of #309), `componentWillReceiveProps` would need to update the local variables by merging in new variables from the parent. We don't automatically refetch variables there because it could very easily lead to over-fetching. I'll comment more on #1048.
