### ISSUE TITLE
Babel relay plugin doesn't seem to work

### ISSUE THREAD

**Issue by mariusrak** [facebook/relay#1068]
Hello, I'm using gulp with webpack using babel-loader. I have set up babel relay plugin with some difficulties, but now it seems that it's set up fine. However, I get this error:

    Error: RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `Relay.QL`.

Transpiled code looks like this:

    _templateObject2 = _taggedTemplateLiteral(["\n                        fragment on query { ToDo_Lists }\n                "], ["\n                        fragment on query { ToDo_Lists }\n                "]);
    function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
    fragments: {
                hello: function hello() {
                        return Relay.QL(_templateObject2);
                }
        }

Is this transpiled code wrong? And what it should look like? Or where else might be a problem?
Thanks

**Comment by josephsavona** [comment]
This looks like a confirmation issue - a previous plugin is compiling away the template tagged literals before the Relay plugin can see them. 

Take a look at the "react native" section of https://github.com/facebook/relay/blob/master/docs/Guides-BabelPlugin.md - the steps for configuring the plugin on RN should also solve the plugin ordering issue that you're seeing.

**Comment by josephsavona** [comment]
I'm going to close this issue since there isn't anything actionable we can do. See my previous comment for a suggestion about how to resolve. If that doesn't help, we'd need a bit more info about your Babel setup to understand what might be going wrong.

**Comment by mariusrak** [comment]
Hello, Your advice helped and graphql is now transpiling as it should, thank you.
For others, this is what I have in gulpfile now:

```
var webpack = require("webpack-stream"); // not original webpack, because it's not compatible directly with gulp
gulp.task('js', () => {
    gulp.src(paths.js)
        .pipe(webpack({
            module: {
                plugins: [
                    new require('webpack/lib/ProvidePlugin')({
                        React: "React",
                        Relay: 'Relay'
                    })
                ],
                loaders: [
                    {
                        test: /\.jsx?$/,
                        exclude: /(node_modules)/,
                        loader: 'babel',
                        query: {
                            passPerPreset: true,
                            presets: [ // order of all items matter
                                {plugins: ['babel-relay-plugin-loader']}, // smal node module which allows babel-relay-plugin to be leaded inside of webpack inside of gulp
                                'es2015', 'react', 'stage-0'
                            ] 
                        }
                    }
                ]
            },
            output: {
                filename: paths.js_output
            }
        }))
        .pipe(gulp.dest(paths.dist));
});
```
