### ISSUE TITLE
endsWith is not currently supported by IE

### ISSUE THREAD

**Issue by alejandromaka** [facebook/relay#1070]
hey there!
i was recently debugging a fetch triggered by `this.props.relay.setVariables` in IE and saw the use of `endsWith` here https://github.com/facebook/relay/blob/master/src/traversal/printRelayOSSQuery.js#L167 which is currently not supported (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith).
this causes an exception and the fetch never occurs.

**Comment by alejandromaka** [comment]
i've also seen instances of `.find` (https://github.com/facebook/relay/blob/master/src/query/RelayQuery.js#L509) being used which babel doesn't transpile and is also not supported by IE natively (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find). just in case :)

**Comment by edvinerikson** [comment]
Relay relies on ES6 polyfills for older browsers. If you include a polyfill like [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) you will be good. 
You should get a [warning](https://github.com/facebook/relay/blob/master/src/__forks__/Relay.js#L24) about this in older browsers (Relay 0.8+).

**Comment by wincent** [comment]
Thanks for bringing this up @alejandromaka, and thanks @edvinerikson for providing the answer. Goint to mark this one as resolved.
