### ISSUE TITLE
FIELDS_CHANGE mutations do not query connectionType, only objectType

### ISSUE THREAD

**Issue by BarakChamo** [facebook/relay#1079]
I came across an issue when applying mutations that update connection fields. 
The mutation was being executed but the resolvers were never called on GQL's end.

After messing around with the configuration and schema I was able to resolve the issue
by changing the output type of the mutation from a connectionType to the original objectType.
the resolver was then called and the store was updated.

For this example Relay mutation:

``` javascript
import Relay from 'react-relay'

export default class JoinEventMutation extends Relay.Mutation {
  getMutation() {
    return Relay.QL`mutation{ JoinEventMutation }`
  }

  getVariables() {
    return {
      eventId:    this.props.event.id,
      leaveEvent: this.props.leaveEvent
    }
  }

  getFatQuery() {
    return Relay.QL`
      fragment on JoinEventPayload {
        event {
          memberCount
          isMember
        }
      }
    `
  }

  getOptimisticResponse() {
    let event

    if (this.props.leaveEvent) {
      event = Object.assign({}, this.props.event, {
        memberCount: this.props.event.memberCount - 1,
        isMember: false
      })
    } else {
      event = Object.assign({}, this.props.event, {
        memberCount: this.props.event.memberCount + 1,
        isMember: true
      })
    }

    return {
      event
    }
  }

  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: {
        event: this.props.event.id
      }
    }
  ]
  }
}
```

Failing configuration:

``` javascript
...
 outputFields: {
   event: {
     type: eventConnection,
     resolve: EventHandler.join.resolve
   }
 },
...
```

Working schema:

``` javascript
...
 outputFields: {
   event: {
     type: eventType,
     resolve: EventHandler.join.resolve
   }
 },
...
```

This seems to be quite a common use-case when working with graph data and even if this is intended behavior, to get the original object and not the connection and update the cache on Relay's end it is not obvious and not clarified in the documentation.

Note that in the connectionType attempt I did have the fat query configured to access the nested node properly, though it wasn't working either.

**Comment by wincent** [comment]
Thanks for this report, @BarakChamo, and sorry for leaving it without a response for so long.

I'm going to close it as it is likely stale at this point, and you did find a way to get things working. The API you're referring to above is now considered "legacy", so we're unlikely to work on it further in the future (although we'd be happy to entertain PRs that fix bugs). Moving forward we're recommending that people use the newer, static mutation API (`Relay.GraphQLMutaton`) and we'll soon be rolling out a new core and new APIs in any case: pieces of this have already landed on the master branch and will continue to do so, but in the meantime, moving to `Relay.GraphQLMutation` will get you as close as possible to the new modern API which is coming out.

Thanks once again for your input!
