### ISSUE TITLE
babel-relay-plugin does not allow a fragment on a `Relay.Route` queries `queryType`

### ISSUE THREAD

**Issue by albertstill** [facebook/relay#108]
I've been trying to add a fragment to the top level `queryType` in a `Relay.Route` but I get this error `Encountered a GraphQL validation error processing file '/Users/albertstill/github/website-next/js/routes/AppHomeRoute.js'. Check your terminal for details.` and no error in my terminal. Seems the babel-relay-plugin is seeing it as an error and transpiling my JS to throw an error in the browser.

I tested the query I want to happen in Postman and it works. The reason I want to add a fragment to the  `queryType` type is because I have a root level field called `posts` that returns a `PostConnection`. We do not have the concept of a `viewer` root level field.  

```javascript
export default class extends Relay.Route {
  static path = '/';
  static queries = {
    query: Component => Relay.QL`
      query {
        ${Component.getFragment('query')}
      }
    `
  };
  static routeName = 'AppHomeRoute';
}
```

**Comment by devknoll** [comment]
There's currently a very hard assumption being made that all Relay.Routes define a single root query, and include a single fragment.

I can't speak for the Relay team on whether or not this will change (though I think it's unlikely), but probably the easiest thing would be to wrap your posts field in another object type (like a viewer root would have done for you).

**Comment by yungsters** [comment]
As @devknoll explained, the easiest thing would be to have a "viewer"-like object for now. For context, root fields are expected to conform to the Object Identification spec which allows Relay to create a mapping from `root field name + argument => node ID`. For example:

- `node(id: 123)`
 - Response: `{id: 123, ...}`
 - We know that `node` with `id` of `123` maps to the node with ID of 123.
- `user(usernames: [yungsters, en_js])`
 - Response: `[{id: 456, ...}, {id: 789, ...}]`
 - We know that `user` with `username` of `yungsters` maps to the node with ID of 456.
 - We know that `user` with `username` of `en_js` maps to the node with ID of 789.

We want to change some assumptions made to be able to enable querying arbitrary fields from the root (e.g. a connection), but for now it isn't super smooth.

**Comment by yungsters** [comment]
See #112 for a better explanation.

**Comment by yuzhi** [comment]
I am going to close this issue. Please follow along at #112 for discussion and updates on root field support.
