### ISSUE TITLE
RelayMutationTransaction#rollback doesn't update the queued records in RelayStoreData

### ISSUE THREAD

**Issue by kileras** [facebook/relay#1081]
Hi, 

I'm using relay to do partial updates in the local cache followed by commits at some points of a multi step form, literally the situation described in #666. As suggested there I was doing small mutations with apply update and storing them in the cache, something like:

```
const mutation = new this.Mutation({...fragments, individualStepData});
pendingTransactions.push(Relay.Store.applyUpdate(mutation));
```

And then later on when I wanted to save everything in the server with a new mutation and then rollbacking everything so I wont have any uncommitted transactions around:

```
const mutation = new this.Mutation({...fragments, data: allTheDataFromPreviousMutations});
Relay.Store.commitUpdate(mutation, {
      onSuccess: () => { 
          pendingTransactions.forEach(transaction => transaction.rollback());
      },
      ..etc...
});
```
Up until 0.8.0 this was working fine but now we updated relay and we are getting an error:
```
Uncaught Invariant Violation: RelayMutationQueue: `0` is not a valid pending transaction ID.
```
Thats comes from 'RelayStoreReader.prototype._updateMetadataFields' when its doing:
```
var mutationQueue = _this4._storeData.getMutationQueue();
data.__mutationStatus__ = mutationIDs.map(function (mutationID) {
    return mutationQueue.getTransaction(mutationID).getHash();
}).join(',');
```
I spend quite some time looking into the store to see where the problem may be and the transactions are actually rolled back and I see them disappear from '_storeData._mutationQueue' without any errors so that part seems to be fine. What seem to happen is that after that, when Relay gets the mutationIDs in the same '_updateMetadataFields' method using 'this._storeData.getClientMutationIDs(dataID);', is still returning the same ids that were there before rollbacking the mutations. I follow the methods and found that those ids are actually stored into the '_storeData. _queuedRecords' object.

Any ideas on how to do this properly? Sorry for the lack of a better example but its a bit hard to isolate the whole thing :D

**Comment by josephsavona** [comment]
Thanks for reporting this and sorry for the delay, we're looking into this.
