### ISSUE TITLE
Question: v 0.8.1 warns when trying to call Relay.injectNetworkLayer

### ISSUE THREAD

**Issue by mailaneel** [facebook/relay#1099]
I can see some commits related to removing ```Relay.injectDefaultNetworkLayer``` from public api and also adding warning if we try to inject network layer more than once.

Should this line of [code](https://github.com/facebook/relay/blob/00de34d32d51ba9e4d17e45280ad6d7e2734c6ed/src/__forks__/Relay.js#L30)    use ```Relay.injectDefaultNetworkLayer``` instead of ```Relay.injectNetworkLayer```  to allow us to inject our own network layer with out warning?

**Comment by wincent** [comment]
Thanks very much for catching and reporting this @mailaneel. https://github.com/facebook/relay/pull/1100 should fix this.

**Comment by mailaneel** [comment]
@wincent thanks for quick fix
