### ISSUE TITLE
Script to generate testschema.json?

### ISSUE THREAD

**Issue by fson** [facebook/relay#110]
It seems that a script to generate `scripts/jest/testschema.json` is missing from the repository?

I need to add a type to the schema to use in a test case, but it seems that there should be a script to read the schema and dump the results of introspection query to JSON. I could write a script to do this with graphql-js, but maybe there already is one and it was just forgotten from this repo?

**Comment by steveluscher** [comment]
In the meantime, to unblock you, you can adapt [this one](https://github.com/facebook/relay/blob/master/examples/todo/scripts/updateSchema.js) for your purpose!

cc/ @josephsavona

**Comment by yungsters** [comment]
We should add a script to do this at `scripts/jest/update-testschema.js`.

**Comment by josephsavona** [comment]
added `npm run update-schema` in #116

**Comment by fson** [comment]
Great, thanks @josephsavona!
