### ISSUE TITLE
Double call to Relay#injectNetworkLayer

### ISSUE THREAD

**Issue by liorrm** [facebook/relay#1103]
When upgrading from Relay `v0.8.0` to `v0.8.1`, I noticed the following error in the web console:

```
Warning: RelayNetworkLayer: Call received to injectImplementation(), but a layer was already injected.
```

The release notes of `v0.8.1`, specifically the below line, explain the sudden appearance of this warning, despite no code changes:

> `Relay.Environment#injectNetworkLayer` (and, by extension `Relay#injectNetworkLayer`) will now warn if injecting would overwrite a previously injected layer.

I call `Relay#injectNetworkLayer` once throughout the entire app just to customize Relay network preferences (to pass cookies to the GraphQL server), which according to the documentation, is perfectly fine, so what could explain the phantom second call to that function? Does it have to do with where I call it? For reference, here is my `Relay#injectNetworkLayer` call:

```javascript
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer(window.GRAPHQL_URL, {
    credentials: 'include' // need this to pass cookies along with the graphql requests
  })
);
```

...or could it have something to do with an internal call to `Relay.Environment#injectNetworkLayer` perhaps? 

Any help would be greatly appreciated. Thanks in advance! 🙏

**Comment by josephsavona** [comment]
I believe @wincent fixed this in d1abc54d5ab60fc8e0b17353ea3b9b3bf2d4f4a0

**Comment by liorrm** [comment]
Great, thanks @josephsavona. Safe to assume the fix will make it in the next minor release?

**Comment by josephsavona** [comment]
@liorrm yup!

**Comment by josephsavona** [comment]
I'm going to ahead since this has been fixed on master.

**Comment by wincent** [comment]
Yeah, sorry about that! @liorrm 

Will likely cut a release next week, so that this doesn't bother too many people.

**Comment by gauravtiwari** [comment]
@liorrm This works: 

```js
const RelayEnvironment = new Relay.Environment;

RelayEnvironment.injectNetworkLayer(
    new Relay.DefaultNetworkLayer('/graphql', {
      credentials: 'same-origin',
      headers: {
        'X-CSRF-Token': App.csrfToken(),
      },
    })
  );
```
