### ISSUE TITLE
network activity callbacks from DefaultNetworkLayer

### ISSUE THREAD

**Issue by bmcmahen** [facebook/relay#1120]
I'm developing a react-native app using relay and would find network activity callbacks useful from the `DefaultNetworkLayer`. It would allow me to centralize management of the `StatusBarIOS` network activity indicator if I could tell when a) an active request has started, and b) the request has ended (either successfully, or with an error). 

I think I could do a PR for this relatively easily, if there's interest. The alternatives to this approach would be to use the readyState in `Relay.Renderer` or to build my own custom network layer. The problem with the first approach is that, especially in mobile apps, you end up with `Relay.Renderer` calls throughout the app, and sometimes the readyState doesn't indicate whether the data is being fetched from the cache, or over the network layer.

**Comment by josephsavona** [comment]
In general we'd prefer to keep the default network layer as simple as possible. To add custom functionality such as network activity callbacks, you can compose the default implementation in your own object/class with whatever hooks you need. Does this work for your use case?

**Comment by bmcmahen** [comment]
Makes sense. I'll give composing the default implementation a try. Thanks.

**Comment by KyleAMathews** [comment]
@Ben you might be interested in this recent effort
https://github.com/nodkz/react-relay-network-layer

**Comment by bmcmahen** [comment]
For what it's worth, composing the default implementation was super easy and proved perfect for the task.

**Comment by KyleAMathews** [comment]
Cool! Big props to @nodkz for taking this on.
