### ISSUE TITLE
No way to retrieve response headers from RelayDefaultNetworkLayer

### ISSUE THREAD

**Issue by 03eltond** [facebook/relay#1123]
When using relay server side, we can send [request headers via init](https://github.com/facebook/relay/blob/master/src/network-layer/default/RelayDefaultNetworkLayer.js#L128), but since there is no browser to pick up any Set-Cookie headers in the response, a custom network layer is required to proxy them over to the client.  This is OK, but it seems clear to me there is some intention on allowing the RelayDefaultNetworkLayer to send contextual headers, and so it feels reasonable to me that perhaps it should also provide a mechanism for retrieving headers from the back end.

I would be happy to propose a pull request if this seems reasonable, though am unsure what the best route to take would be.  The problem currently is that the internal fetch promise chains resolve with only the body data [here](https://github.com/facebook/relay/blob/master/src/network-layer/default/RelayDefaultNetworkLayer.js#L58) and [here](https://github.com/facebook/relay/blob/master/src/network-layer/default/RelayDefaultNetworkLayer.js#L84), and so the header data is lost.  A solution could be to include the header data in the resolves and make sure it gets made available to the consumer.

Of course, you can just tell me this is beyond the scope of the default network layer and I'll happily write my own, but thought it might be worth discussing as I wonder if it could become a common use case for those of us writing isomorphic apps :)

Thanks!

**Comment by wincent** [comment]
In general I think we want to keep the default layer pretty simple, and the intention is that if you want to do anything "special" you can bring your own.

[Here](https://github.com/facebook/relay/issues/1120) is a similar issue from a day or two ago, which includes an interesting comment from @KyleAMathews to [a user-space network layer project](https://github.com/nodkz/react-relay-network-layer).

**Comment by 03eltond** [comment]
Thanks @wincent for pointing me in that direction.  The idea of using middleware within the network layer is an interesting one that might work out well for us, or at least we can get some good ideas from that implementation.  I'll go ahead and close this since it sounds like a custom layer is the way to go.  Thanks again!
