### ISSUE TITLE
Warn when `getOptimisticUpdate` data shape is wrong

### ISSUE THREAD

**Issue by akre54** [facebook/relay#1145]
I ran into a rather maddening case recently:

> [RelayRecordStore.getLinkedRecordID(): Expected field `child` for record `client:9132455882` to have a linked record.](https://github.com/facebook/relay/blob/v0.8.1/src/store/RelayRecordStore.js#L236-L242)

Turns out it was due to my optimistic update, which took some sleuthing to figure out.

The prop passed to the mutation, `data`, has a `child` key (an ID string of the record's associated `child` prop), while the return value expects `child` as an object with an `id` key. I missed it because I was naiively copying data into the return value. 

```js
getOptimisticUpdate() {
  const { id, data } = this.props
  return {
    id,
    ...data
  }
}
```

The solution was to fix the shape of the data, so that `child` would correctly return an object with a string id key, instead of the string itself:

```js
getOptimisticUpdate() {
  const { id, data: { name, child } } = this.props
  return {
    id,
    name,
    child: {
      id: child
    }
  }
}
```

Totally my fault, but would help if the invariant message were a little less cryptic. Happy to open a pull if that would help. Maybe the invariant can type-check the expected result vs the received?

**Comment by wincent** [comment]
Thanks for this suggestion, @akre54.

With [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable), we'll have a very different (better) way of constructing optimistic updates, so we are unlikely to work on implementing this suggestion against the old API. So I'm going to close this. Thanks once again for you suggestion though!
