### ISSUE TITLE
Current solution for GQL subscriptions?

### ISSUE THREAD

**Issue by saeho** [facebook/relay#1152]
From what I read online, it looks like the Relay/GQL subscriptions API is not ready. What is the current solution for event based query subscriptions?

**Comment by josephsavona** [comment]
Thanks for asking. We're tracking progress of real-time subscriptions in #541. I [recently commented](https://github.com/facebook/relay/issues/541#issuecomment-213093469) there with a brief update and suggestion for a workaround.

**Comment by wincent** [comment]
Going to close this (spring cleaning).
