### ISSUE TITLE
Can't parse Relay.QL`...` in coffeescript

### ISSUE THREAD

**Issue by huan-ji** [facebook/relay#1153]
Currently I am unable to write Relay queries next to React components because there is no way to escape the Relay queries in coffeescript. Is there some way to even implement a local hotfix to allow writing of Relay queries in coffeescript? Thanks.

**Comment by wincent** [comment]
Thanks for the question @huan-ji. We don't use CoffeeScript here at FB, so for now we're focusing on supporting JS. As it is, you need to run the Babel plug-in to transform those template literals into the corresponding runtime representation, so if you could solve the syntax issue on the CoffeeScript side, you'd still need to set things up carefully such that Babel could run over the transformed JS that comes out of your CoffeeScript build pipeline.

I think in the interim your best bet may be to follow the suggestion in https://github.com/jashkenas/coffeescript/issues/1504 (which I can see you commented on), and put the fragments in JS files instead. Not ideal, but it is a workaround.

I'm going to close this, but if anybody has grappled with this issue before and wants to add some insight, please feel free to go ahead.
