### ISSUE TITLE
hooks for Relay status

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#1160]
I am looking for some api that would allow me to monitor if Relay have some async tasks in queue. 

I know that I can track these things individually (`pendingVariables` for `setVariables`, callbacks for mutations, `onReadyStateChange` on route changes), but I did not find hook where I could do that globally for particular Relay instance. 

Use cases are either single UI progress indicator showing that some request is being processed or I think it also could be helpful with selenium tests (thats my intention) as I could avoid many explicit waits if I can wait before every command until Relay says its ready (async tasks are finished) - similar strategy is used in Protractor for Angular.

I could work on PR if you give me good hint where would be good place to create such hook (assuming I did not miss it)

Thanks!

**Comment by wincent** [comment]
A [custom network layer](http://facebook.github.io/relay/docs/guides-network-layer.html) would probably work well for the "some request is being processed" use case, and possibly the Selenium one as well.

**Comment by jardakotesovec** [comment]
@wincent Thanks. I was not sure if that would also cover cases like queued mutations (mutations with same collision key), but I think its correct to assume if such network request resolve - Relay will send next network request in queue within one event loop (assuming I am using default task scheduler), so there should not be gap for race conditions.

Feel free to close it if you don't see this as common use case which would make sense to add to core.

**Comment by wincent** [comment]
Sure thing @jardakotesovec. In general we like to keep the core API as small as possible, so l will close this. Let us know, however, if you run into any roadblocks that prevent you from implementing this "in userland" and we can consider other options.
