### ISSUE TITLE
Noob question: relay setVariables not trigger the query

### ISSUE THREAD

**Issue by rarutu** [facebook/relay#1162]
I am learning React + Graphql + Relay ... and i am fighting for a few hours with this situation: - my component looks like this

```
class Main extends React.Component {
  setLimit = (e) => {
    let newLimit = Number(e.target.value);
    this.props.relay.setVariables({ limit: newLimit });
  };
  render() {
    let content = this.props.store.linkConnection.edges.map(edge => {
      return <Link key={edge.node.id} link={edge.node} /> ;
    });
    return (
      <div>
        <h3>Links</h3>
        <select onChange={this.setLimit}>
          <option value="2" selected>2</option>
          <option value="4">4</option>
          <option value="6">6</option>
        </select>
        <ul>
          {content}
        </ul>
      </div>
    );
  };
}

Main = Relay.createContainer(Main, {
  initialVariables: {
    limit: 2
  },
  fragments: {
    store: () => Relay.QL`
      fragment on Store {
        linkConnection(first: $limit) {
          edges {
            node {
              id,
              ${Link.getFragment('link')}
            }
          }
        }
      }
    `
  }
});
```

as u can see, there is a select in there that is correctly triggering the setLimit handler ... inside setLimit i have this.props.relay.setVariables ... although i do not get any error the query is not being executed upon change

i am surely doing a noob mistake ... just do not know what that is :) ... cause i am noob :))

thanks

**Comment by rarutu** [comment]
maybe it would be useful to say that even if though i am fetching the first 2 items out of 10 ... pageInfo.hasNextPage is false ... maybe that is why it does not trigger the re-fetch

**Comment by josephsavona** [comment]
Thanks for the detailed issue and the follow-up, that's the critical bit. If pageInfo.hasNextPage is false initially, that means the server has indicated there are no more items that can be fetched. In this case, Relay won't bother fetching more. Fixing the the pageInfo response should make this work as you expect.

**Comment by rarutu** [comment]
trying to fix this make me feel like a kardashian in the amazon jungle :(

any way on how to debug this? the part inside schema.js that does the fetching looks like this:

```
let storeType = new GraphQLObjectType({
    name: 'Store',
    fields: () => ({
      linkConnection: {
        type: linkConnection.connectionType,
        args: connectionArgs,
        resolve: (_, args) => connectionFromPromisedArray(
          db.collection("links").find({}).limit(args.first).toArray(),
          args
        )
      }
    })
  });
```

**Comment by rarutu** [comment]
so the only way this worked for me is if i remove **limit(args.first)** but this means i fetch all the items in my db ... and to be honest i find this insane ... what if i have 10 mil recoreds? :/

am i missing something?

**Comment by jardakotesovec** [comment]
@rarutu `connectionFromPromisedArray` is helper that assumes that whole dataset in is in that array, thats reason why it works only if you fetch everything. 

You need to implement (or find) such helper that will work efficiently with MongoDB.  These helpers always gets backend specific.

I don't use MongoDB with graphql, but @nodkz recently referenced some graphql+mongodb [resources](https://github.com/facebook/relay/issues/1150#issuecomment-220283327) which hopefully help you to sort it out.

**Comment by rarutu** [comment]
@jardakotesovec thanks for the answer ... i did not knew that connectionFromPromisedArray assumes u give it all the data ... honestly i do not use mongodb but in the video tutorail i ma following the trainer is using it and for him it worked ... maybe the specs changed since he did the video ... :) ... in any case i will plan to use it with Amazon RDS on MySQL or MariaDB ... do not know which one yet ... probably mysql :)

**Comment by josephsavona** [comment]
@jardakotesovec thanks for answering!

I'm going to close this as it isn't an issue per-se, but please feel free to continue discussing approaches. We'll keep this in mind as it isn't very intuitive why pagination wasn't working in this case.
