### ISSUE TITLE
Allow first and last at the same time

### ISSUE THREAD

**Issue by aihornmac** [facebook/relay#1170]
I understand that `offset` and `skip` arguments can be added to the query to `ConnectionType` manually, but I reckon that the `first` and `last` together can be utilized to express an offset pagination. For example, `{ first: 25, last: 10 }` may be telling `{ offset: 15, limit: 10 }`. In fact I have tried to implement it in GraphQL server. The problem is, relay throws an error, saying this combination of arguments is not allowed. I hope this limitation could be less critical, so that developers can have their choice over implementing specs.
Thank you!

**Comment by steveluscher** [comment]
Thanks for the feedback!

You've probably already seen the [Relay Cursor Connection spec](https://facebook.github.io/relay/graphql/connections.htm) that outlines our approach to pagination. @leebyron evaluated the multitude of approaches to connections in [this excellent Gist](https://gist.github.com/leebyron/ba600d3137aeaba849d0). In short, a _Relay_ connection is going to continue to use the “connection-wrapped, edge-wrapped” model, but there's nothing stopping you from implementing a connection using the model you've described above.

To do so, simply make sure that your type name ends in something other than “Connection.” That's how we recognize a field as one that implements the connection spec. Note, that once you do so, Relay won't offer any connection diffing when you do new fetches, or range add/delete behaviors when performing mutations.

**Comment by aihornmac** [comment]
Thank you for the references!
Actually I was hoping relay could do the differing job even in window pagination, this may be duplicated with [this issue](https://github.com/facebook/relay/issues/540) though. I found relay not fetching new data with same arguments (i.e. skip: 0, take:10), but one thing about window pagination is even with same arguments, that data might have been stale. So instead of `forceFetch`, I hope on one hand relay can still in charge of refetching control, on the other hand it may offer window pagination.

**Comment by josephsavona** [comment]
Thanks for filing an issue. Let's continue discussion of windowed pagination support at #540.
