### ISSUE TITLE
[RFC] default Relay props for progressive rendering

### ISSUE THREAD

**Issue by aweary** [facebook/relay#1175]
### The Current Problem

Relay currently requires the `props` to be resolved before it renders a component with the data, which makes sense in a lot of cases. One situation where we're getting some headaches is progressively rendering our components, i.e., rendering the base structure and then rendering the data within the structure when it's available. This will be an especially useful pattern when `.defer()` support is introduced as well.

Currently we're using the `render` method to conditionally render either the wrapped Relay component or just the base component that we export alongside it.

``` js

render({done, props}) {
  if (!done || !props) {
    return <BaseComponent/>
  }
 return React.cloneElement(WrapperRelayComponent, props)
}

```

This works great for root level components, but we're also using composition to aggregate child container queries so the `render` method of `<BaseComponent/>` returns other Relay containers, which causes errors.

One pattern we've used is to provide a default `viewer` object in `defaultProps` with empty data. This allows us to avoid a bunch of type checks in the `render` methods.

``` js

static defaultProps = {
  viewer:  {
    photos: [],
  }
}
```

We can then either just render an empty version of the component or, if we want, we can just declare `null` values in `defaultProps` and render a `<Loading />`component. We get to declare the empty data structure for each component within the component just like we do with Relay, so each child has its own default `viewer` object with its set of empty values.

Now the issue comes down to this:
- We can conditionally render the base component or the wrapper component at the top level,
  but doing so for children would require a verbose `render` method.
- React requires a prop to be `undefined` to use the value in `defaultProps`
- Relay requires an explicit `null` for viewer

If I try to use `defaultProps` on the child containers themselves I get a bunch of warnings like:

``` js
Warning: RelayContainer: Expected prop `property` to be supplied to `Connect(Gallery)`, but got `undefined`. Pass an explicit `null` if this is intentional.
```

Because I have to pass `undefined` otherwise React will not use the empty data object in `defaultProps`. I could declare one top level default object in the root base component and pass it down but that's contrary to how we declare data dependencies in Relay right now.
### Potential Solution

I think it would be great if there was support for declaring default Relay values just like you can declare default props on React components. This would be consistent with how you declare data dependencies at the point of use currently and it would make it a lot easier to progressively render your React component. A potential API might look like: 

``` js
export default Relay.createContainer(BaseComponent, {
  defaultProps: {
   property: {
     name: ''
   }
  },
fragments: {
  property: () => Relay.QL`
    fragment on Property {
      name
    } 
  `
}
})
```
#### Advantages
- Default data values are colocated with actual data dependencies
- Consistent with current React API, familiar to current users
- Easy to use with composition
- Excellent synergy with `defer()` when it it's supported
#### Disadvantages
-  Not sure how to do default value composition at the root level
#### Alternative Solution

I think another option would be to just have a HOC in userland that wraps your component and manages default props until the `viewer` is available. This is less ideal as I think this is a concept that would fit well within Relay core, but if not maybe we can discuss this.

---

So all in all I think this would make our lives a lot easier, and hopfeully others too! This may be a dumb idea or I'm just missing an obvious alternative, so I'm excited to hear what you guys think.

**Comment by unirey** [comment]
Im also looking for an answer to this question, this is absolutely essential to my project. I love Relay, I would be very, very, very sad if I had to replace Relay with Flux or Redux.. 

Im not an expert (2 weeks into Relay) but I'll try to help, here's an idea that might or might not help..


### Per container flag 
It would render React component ASAP without data and re-render component if data arrives.

```javascript
module.exports = Relay.createContainer(List, {
  initialVariables: {
    // initial vars
  },

  // progressive -> render shell immediately without waiting for data  
  isProgressive: () => true,

  fragments: {
    list: () => Relay.QL
       // query
    ,
  },
});
```

It would be useful to have access to the flag in React component to set `props `and `view` accordingly.

Then we could use it similarly to this:
`(isProgressive && hasdata) ? actual data : shell data / null;`

This boolean check could be transformed into efficient internal Relay checking method.

**I hope it's helpful in any way.**

I've noticed that shell technique is being used by Facebook and Im wondering if any of these views/components have been accomplished with Relay.

Is there currently any way or future plans to make it work without nasty hacks?

**Comment by Aweary** [comment]
You can use the `render` method on a top level `RelayRenderer` to return the component without the `RelayContainer` wrapper, which is sufficient if your component doesn't render other `RelayContainer`s. 

But the heart of the issue, as I see it, is that if you're rendering containers multiple levels deep you can't efficiently handle this scenario as far as I can tell.

**Comment by akre54** [comment]
We're facing this exact issue. It'd be great if future versions of Relay supported this use case instead of the all-or-nothing approach (right now the only two modes are "loading" and "has everything"). Sometimes it's not desirable to show a big loading spinner between all route changes.

**Comment by unirey** [comment]
@Aweary Have you discovered a way to remove mentioned `undefined` warnings?

**Comment by vadimshvetsov** [comment]
I'm not sure that my case is 100% relative to this post but an idea of avoiding warnings the same. Let's say that I have component Posts, which can be rendered as Root component for main page and as sub for TagPage.

```
class Posts extends React.Component {
  static propTypes = {
    viewer: PropTypes.shape({
      posts: PropTypes.shape({
        edges: PropTypes.arrayOf(PropTypes.shape({
          node: PropTypes.shape({
            id: PropTypes.string,
          }),
        })),
      }),
    }),
    tag: PropTypes.shape({
      posts: PropTypes.shape({
        edges: PropTypes.arrayOf(PropTypes.shape({
          node: PropTypes.shape({
            id: PropTypes.string,
          }),
        })),
      }),
    }),
  };

  static defaultProps = {
    viewer: {
      posts: {
        edges: [],
      },
    },
    tag: {
      posts: {
        edges: [],
      },
    },
  };

  render() {
    return (<main className="container">
      {
        this.props.viewer.posts.edges.map(({ node }, index) =>
          <PostPreview key={node.id} post={node} left={index % 2 === 0} />)
      }
      {
        this.props.tag.posts.edges.map(({ node }, index) =>
          <PostPreview key={node.id} post={node} left={index % 2 === 0} />)
      }
    </main>);
  }
}

export default Relay.createContainer(Posts, {
  initialVariables: {
    limit: 5,
  },
  fragments: {
    viewer: () => Relay.QL`
        fragment on Viewer {
            posts(first: $limit) {
                edges {
                    node {
                        id,
                        ${PostPreview.getFragment('post')}
                    }
                }
            }
        }
    `,
    tag: () => Relay.QL`
        fragment on Tag {
            posts(first: $limit) {
                edges {
                    node {
                        id,
                        ${PostPreview.getFragment('post')}
                    }
                }
            }
        }
    `,
  },
});
```

So if I want to render Posts component within TagPage I will get posts from Tag as postConnection. But if I would like to render posts as a Root component it will populated from Viewer.

So like the code is below:

```
class TagPage extends React.Component {
  componentDidMount() {
    document.getElementsByClassName('background')[0].classList.add('tag-page');
  }

  componentWillUnmount() {
    document.getElementsByClassName('background')[0].classList.remove('tag-page');
  }

  render() {
    const { viewer } = this.props;
    const tag = viewer.tag;
    return (<div>
      <TagHeader name={tag.name} />
      <Posts tag={viewer.tag} />
      <Helmet>
        <title>#{tag.name}</title>
        <meta name="description" content={`The freshest horror news on your with #${tag.name} hashtag`} />
      </Helmet>
    </div>);
  }
}

export default Relay.createContainer(TagPage, {
  initialVariables: {
    slug: '',
  },
  fragments: {
    viewer: () => Relay.QL`
        fragment on Viewer {
            tag(slug: $slug) {
                id,
                name,
                ${Posts.getFragment('tag')},
            },
        }`,
  },
});

```

And Root Route: 

```
const ViewerQueries = {
  viewer: () => Relay.QL`query ViewerQuery{ viewer }`,
};

ReactDOM.render(
  <Router history={hashHistory} render={applyRouterMiddleware(useRelay)} environment={Relay.Store}>
    <Route component={App}>
      <Route path="/" component={HomePage} onChange={scrollTop} >
        <IndexRoute component={Posts} queries={ViewerQueries} />
        <Route path="/tag/:slug" component={TagPage} queries={ViewerQueries} />
        <Route path="/post/:slug" component={PostPage} />
        <Route path="/page/:slug" component={Page} />
      </Route>
    </Route>
  </Router>, document.getElementById('app'));
```

It would be great to suppress this warning with using for example defaultProps...

**Comment by amkoehler** [comment]
> You can use the render method on a top level RelayRenderer to return the component without the RelayContainer wrapper, which is sufficient if your component doesn't render other RelayContainers.

We're using this pattern as well, but I have a concern. By first returning the component without the `RelayContainer` wrapper then returning it at a later time with the wrapper, this results in the component getting unmounted and remounted. Has that caused any issues for you?

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

If this is something you'd like to see happen, then we'd be happy to review a pull request.

If this issue is still important to you, please feel free to reopen it with an update.

**Comment by fabiospampinato** [comment]
Random question, but was something like this ever implemented at some point? I'm also looking for a middle ground between "loading, we have no data" and "loaded, we have all the data" 🤔

**Comment by sibelius** [comment]
does partial loading solve this ?

**Comment by fabiospampinato** [comment]
Maybe, I'm not sure we want to render cached data in the the use case I have, but looking at the docs I think this is what I had in mind: https://www.internalfb.com/intern/staticdocs/relay/docs/guides/incremental-data-delivery/

**Comment by sibelius** [comment]
wrap your component in a suspend and it will suspend
