### ISSUE TITLE
Complete TodoMVC example with routing

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#118]
There's still some work to be done to complete the TodoMVC example: add routing [as per the spec](https://github.com/tastejs/todomvc/blob/master/app-spec.md#routing).

**Comment by steveluscher** [comment]
@taion did this in https://github.com/taion/relay-todomvc

…putting a PR on my wishlist. :gift:

**Comment by taion** [comment]
I'm still intending on PR this. Not this weekend though - RC1 of React and React Router took up all my time for open source and then some. Later this week most likely.

**Comment by steveluscher** [comment]
:+1:
