### ISSUE TITLE
[Feature] Combine initialVariables and prepareVariables

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#1190]
`this.props.relay.variables` now has the post-`prepareVariables` values, and `prepareVariables` usually looks something like this:

```js
prepareVariables: (prev) => ({
  ...prev,
  size: prevVariables.size * window.devicePixelRatio,
}),
```

So why don't we pull a Redux, and simplify `initialVariables` + `prepareVariables` to:

```js
variables: (prev = {
  size: 50,
}) => ({
  ...prev,
  size: prev.size * window.devicePixelRatio,
}),
```

Relay can call `variables(undefined)` to get the equivalent of `prepareVariables(initialVariables)` today.

**Comment by josephsavona** [comment]
I like the direction of trying to simplify the API if possible. I'm not sure about this exact proposal though. The reducer approach makes it pretty easy to write a bug; for example, the code above seems right but would always return `{size: NaN}`. This could be fixed by changing the function to return `size: prevVariables ? (prevVariables.size * devicePixelRatio) : DEFAULT_SIZE` or similar, but that seems like a recipe for confusion (and bug reports, issues, etc). For a lot of cases developers don't need `prepareVariables`, either, so this makes the common case harder.

**Comment by devknoll** [comment]
> for example, the code above seems right but would always return {size: NaN}

Was actually just a typo. I agree that the ternary case is much more confusing, but thankfully not necessary ;-)

> For a lot of cases developers don't need prepareVariables, either, so this makes the common case harder.

```js
variables: () => ({
  size: 50,
}),
```

doesn't seem like too much more work ;-) Relay could also allow a signature of `Object | (Object?) => Object` to bring back the simplicity of `initialVariables`.

The main point is that there doesn't seem to be much benefit in having both an `initialVariables` and a `prepareVariables`.

**Comment by nodkz** [comment]
I can add 5 cents:
Allowing to provide vars to relay container without the `initialVariables` declaration save lot of time for newbies. 

In past I spent couple of hours to understand, that passed variable to relay does not work because it was not listed in `initialVariables`.

**Comment by josephsavona** [comment]
After some consideration, I think that this is the wrong API and we aren't going to pursue it. The presence of `prepareVariables` is itself a bit of a hack; it gives product developers a way to adjust variables but substantially complicates the framework. In particular it messes with static analysis of queries - having to run an arbitrary user function is the definition of dynamic. In the future we would like to re-evaluate ways for developers to define even more dynamic queries and improve this API, but for now we'd prefer to keep the more static `initialVariables` style as the default to aid in upgrades.

**Comment by taion** [comment]
@josephsavona FWIW, after you added `prepareParams` to react-router-relay, I've actually never had to use `prepareVariables`. I wonder just how useful `prepareVariables` on containers still is these days.

**Comment by josephsavona** [comment]
@taion Thanks for the feedback. We have a few use-cases internally but I believe that we could find alternative approaches for those.
