### ISSUE TITLE
Error `Cannot query field "node" on type "Query".` after setVariables

### ISSUE THREAD

**Issue by markogresak** [facebook/relay#1195]
Hi!

I'm using this query

``` js
fragments: {
  options: () => Relay.QL`
    fragment on diseaseMedicine @relay(plural: true) {
      value: id,
      label: disease
    }
  `
}
```

included as:

``` js
initialVariables: {
  disease: ''
},
fragments: {
  store: () => Relay.QL `
    fragment on Store {
      DiseaseOptions: diseaseMedicine {
        ${DiseaseSelect.getFragment('options')}
      },
      AllergyOptions: diet {
        ${AllergySelect.getFragment('options')}
      },
      MedicationOptions: diseaseMedicine {
        ${MedicationSelect.getFragment('options')}
      },
      DietOptions: diet {
        ${DietSelect.getFragment('options')}
      }
    }
  `
}
```

Which, after using `.setVariables({disease: ...})`, attempts to send this query:

```
query Index_StoreRelayQL($id_0: ID!) {
  node(id: $id_0) {
    ...F1
  }
}

fragment F0 on diseaseMedicine {
  id
  medicine
}

fragment F1 on Store {
  _diseaseMedicine14kzg6: diseaseMedicine {
    id
    ...F0
  }
  id
}
```

And it fails with error message `Cannot query field "node" on type "Query".`

However, if I were to change the above query (playing in graph*i*QL) to:

```
query Index_StoreRelayQL {
  store {
    ...F1
  }
}

fragment F0 on diseaseMedicine {
  id
  medicine
}

fragment F1 on Store {
  _diseaseMedicine14kzg6: diseaseMedicine {
    id
    ...F0
  }
  id
}
```

It executes correctly, except that it's not using the variable. 

I am using `react-relay` v0.7.3. Also, I'm using [`react-router-relay` v0.10.1](https://github.com/relay-tools/react-router-relay/tree/v0.10.1) for routing and setting [queries](https://github.com/relay-tools/react-router-relay/tree/v0.10.1#routes-and-queries) to:

``` js
{
  queries: {
    store: (component) => Relay.QL`
      query MainQuery {
        store { ${component.getFragment('store')} }
      }
    `
  }
}
```

Any ideas how to fix this?

**Comment by markogresak** [comment]
Apparently moving the `${MedicationSelect.getFragment('options')}` together with `${DiseaseSelect.getFragment('options')}` into same field, as in:

```
options: diseaseMedicine {
  ${DiseaseSelect.getFragment('options')}
  ${MedicationSelect.getFragment('options')}
},
```

solves the problem I was having.
Can someone explain why this was happening?

**Comment by markogresak** [comment]
The last comment didn't solve the problem fully, it was still missing using the variable as argument.

I have noticed that the graphQL schema was missing `nodeDefinitions`, as in there was no `node: nodeField` and no `interfaces: [nodeInterface]`. I should've looked through the tutorial more thoroughly.

**Comment by Maxyss** [comment]
@markogresak on what type did you add nodeDefinitions? On Query type?
