### ISSUE TITLE
Document Relay network debugger

### ISSUE THREAD

**Issue by nodkz** [facebook/relay#1196]
## RelayNetworkDebug

From `Relay@^0.8.0` available relay requests debugger `RelayNetworkDebug`

``` js
import RelayNetworkDebug from 'react-relay/lib/RelayNetworkDebug';  
RelayNetworkDebug.init();
```

 ![screenshot](https://cloud.githubusercontent.com/assets/1946920/15735688/688ccabe-28bc-11e6-82e2-db644eb698b0.png)
## _ _ DEV _ _=true

From `Relay@^0.9.0` became availiable relay's [extended mutation debugger](https://twitter.com/steveluscher/status/738101549591732225). 
<img width="366" alt="screen shot 2016-06-02 at 12 34 35" src="https://cloud.githubusercontent.com/assets/1946920/15735975/6dcbfc6e-28be-11e6-99d7-86812df4b928.png">

For activation via browser's console: type `__DEV__=true`. 
Due webpack build process you may use `webpack.BannerPlugin('__DEV__=true;', {raw: true})` or `webpack.DefinePlugin({__DEV__: true})`.

In [Changelog 0.9.0](https://github.com/facebook/relay/releases) absent underscores for `__DEV__`. Not clean understandable how to turn this debugger.

**Comment by nodkz** [comment]
## And again about Documentation 

May be somebody add a `Debugging` article to documentation. Also will be great if leave article about `scheduling` (thanks to last Joseph talk, I don't know that this cool feature exists).

My english right now is to bad to write articles, and I hate to do it, cause spent a lot of time. I prefer to write some code. 

May be at facebook exists so-so-coders that under dismissal ;), and may be somebody will became a brilliant technical writer ;) Good coder IS NOT good writer and vise versa. So for documentation I think should exist dedicated person.

Also it will be interesting to read about Docker's OSS results: https://blog.docker.com/2016/05/open-source-docker-part-1-people/ I think they can not reach such results without their clean documentation.

**Comment by BlooJeans** [comment]
If you're using a custom relay environment, be sure to do
```
let myEnv = new Relay.Environment();
RelayNetworkDebug.init(myEnv)
```

**Comment by wincent** [comment]
> My english right now is to bad to write articles, and I hate to do it, cause spent a lot of time. I prefer to write some code.

This is a legit stance!

Is anybody else able to whip up a PR? I'm cleaning house trying to prepare the next release this week, so I can't promise getting to it myself, but a "Debugging" page in the docs would be great.

Thanks for bringing this up @nodkz, and thanks @BlooJeans for the PSA.

**Comment by wincent** [comment]
Closing this as we're unlikely to further document the Relay Classic APIs now that Relay Modern is out. PRs improving the Relay Modern docs, however, would be very welcome.
