### ISSUE TITLE
How to update null field to a proper value via mutation? (TrackedFragmentQuery issue?)

### ISSUE THREAD

**Issue by dguillamot** [facebook/relay#1198]
1)
Looking at debug output of my mutation, I can see that my field:  `user { color }`  is not included in the **Mutation Configs --> FIELDS_CHANGE_>Tracked Fragment Query** section. 
I believe this is because prior to the mutation, `user { color }` is null. 

2)
The **Mutation Configs --> FIELDS_CHANGE_>Fat Fragment Query** section does include user { color } 

3) 
Naturally, the **Mutation Configs --> FIELDS_CHANGE_>Intersected Fragment Query** does not include user { color } ..  because it is not included in the tracked section.. because it is null I believe..

4) 
My GraphQL server mutation is returning an object with user { color } defined and non-null. But since it is not included in the Intersected Fragment Query, it is not being updated in the store. If I do a forceFetch, the store gets update correctly, but I would like the store to update naturally, by including the `color` field in the mutation response. I can see in the mutation onSuccess() callback that it is not there. 

How can we track (and intersect) and update fields with null values so that they can be updated by the mutation ?

Thank you,

**Comment by nodkz** [comment]
If we haven't shown the coupons in the UI at the time the
mutation runs, they've never been fetched and the `coupons`
field in the fat query would normally be ignored.
`REQUIRED_CHILDREN` forces it to be retrieved anyway.

https://facebook.github.io/relay/docs/guides-mutations.html#required-children
```
getConfigs() {
    return [{
      type: RelayMutationType.REQUIRED_CHILDREN,
      children: [
        Relay.QL`
          fragment on CouponCreatePayload {
            coupons
          }
        `,
      ],
    }];
  }
```
After that you'll see this `field` in the `onSuccess` callback.

**Comment by dguillamot** [comment]
Thank @nodkz , adding REQUIRED_CHILDREN does indeed add the fields to the mutations onSuccess result, however the store is still not updated correctly, and the Intersected Fragment Query still does not include the `user { color }` field. Hmm

**Comment by nodkz** [comment]
Yep, store will not updated. You should process it onSuccess callback.
3 июня 2016 г. 1:50 PM пользователь "dguillamot" <notifications@github.com>
написал:

**Comment by grydstedt** [comment]
That doesn't seem like a good thing. If fields in a model can't go from `null` to a filled value without having to refresh the store or manually update the date? Is there a way to force the store to track a certain field?

**Comment by josephsavona** [comment]
Hmm. REQUIRED_CHILDREN isn't the right solution here: that's only meant for data that you need access to in the mutation callback (say, the id of a newly created item) and the fields there are ignored by Relay.

Relay should be tracking fields even if they're null. Can you provide a bit more information to help us debug? For example, can you copy the output of the Relay mutation debugger from console?

**Comment by wincent** [comment]
Closing this due to staleness/inactivity. The new Relay core and APIs don't do any tracking anyway, in favor of entirely static mutations, so there is likely no further action to be taken here (the new core/APIs are currently rolling out on the `master` branch in pieces, with more coming in the next few weeks/months.

Thanks to everybody who participated in this thread!
