### ISSUE TITLE
child gets out of sync with parent

### ISSUE THREAD

**Issue by ts-smith** [facebook/relay#120]
https://github.com/ts-smith/relay/commit/0f2f827be08a52de658a38bee701d901cc20eadb

When incrementing the $first variable while there are more unshown todos, the child (TodoList) seems to get a view of the data that is "one behind" the view of the parent (TodoApp).

**Comment by yuzhi** [comment]
Sorry, I'm not sure I understand the problem exactly. What do you mean by "one behind" the view of the parent? Do you have examples of what the parents has, vs what the child has?
Note that `setVariable` is async and the parent will not get one additional edge until it has been fetched from the server and stored in Relay. You can add a [onReadyState callback](http://facebook.github.io/relay/docs/guides-ready-state.htm) for when the additional edge is ready.

**Comment by ts-smith** [comment]
If I do something like 
```          
{hasTodos &&
            <TodoList
              key={Math.random()}
              todos={this.props.viewer.todos}
              viewer={this.props.viewer}
            />
          }
```

to force the todo list to rebuild every time, the list will start to show one more item whenever the parent view gets more data. Without doing that, in order to get one more item to render, I need to increment first twice. Then each additional increment gets one more, but behind where it should be. If I inspect the data the parent has during rendering, it has the desired items, but the child container doesn't get them. Looking at the fragments (that I believe it uses to extract from the data store or something) it has a fragment that looks like the previous query.

**Comment by steveluscher** [comment]
We dug into this, and should have a fix for you soon. Thanks @ts-smith!
