### ISSUE TITLE
Relay creates invalid query with union type where one type implements `Node`

### ISSUE THREAD

**Issue by calebmer** [facebook/relay#1203]
Relay is generating an `id` field on a union type where all types in the union type do not implement `Node`. Here’s a schema (with names obfuscated):

``` graphql
type A implements Node {
  b: B!
}

# Not actually sure if this is the correct syntax, don’t think i’ve ever seen it :blush:
union B = C | D | E

type C {
  c: String!
}

type D implements Node {
  id: ID!
  d: String!
}

type E {
  e: String!
}
```

With a query that looks like:

``` graphql
{
  a {
    b {
      type: __typename
      ... on C {
        c
      }
      ... on D {
        d
      }
      ... on E {
        e
      }
    }
  }
}
```

Relay generates an id field so the query that gets sent looks more like:

``` graphql
{
  a {
    b {
      type: __typename
      # id field generated by Relay
      id
      ... on C {
        c
      }
      ... on D {
        d
      }
      ... on E {
        e
      }
    }
  }
}
```

This of course fails on the server.

**Edit:** In the original post, I omit that `A` implemented `Node`. `A implements Node` was therefore retrospectively added. See [this](https://github.com/facebook/relay/issues/1203#issuecomment-224786705) comment.

**Comment by yuzhi** [comment]
cc @josephsavona

**Comment by josephsavona** [comment]
Weird. We should only be generating an `id` field when the parent type implements `Node`; otherwise we add a `...on Node {id}` instead (which would work here). That logic is in [RelayQLPrinter](https://github.com/facebook/relay/blob/master/scripts/babel-relay-plugin/src/RelayQLPrinter.js#L462-L466). I'll try to think of a short-term workaround. In the meantime, you might try logging in the babel plugin and try to figure out what's going on (why is `hasField('id')` true for that union?)

**Comment by calebmer** [comment]
@josephsavona Turns out in this instance `A` does implement `Node`. Didn’t know that was important. I’ve updated the schema.

**Comment by NevilleS** [comment]
The fact that `A` implements node isn't what Joe means by the "parent type" here - the parent of the faulty `id` field you're describing is the union type `B`. `B` shouldn't have an `id` field, but the RelayQLPrinter is getting fooled into thinking it does.

**Comment by NevilleS** [comment]
You should check your schema.json for the definition of the `B` type. It should look something like this:
```
{
  "kind": "UNION",
  "name": "B",
  "description": null,
  "fields": null,
  "inputFields": null,
  "interfaces": null,
  "enumValues": null,
  "possibleTypes": [
    {
      "kind": "OBJECT",
      "name": "C",
      "ofType": null
    },
    {
      "kind": "OBJECT",
      "name": "D",
      "ofType": null
    },
    {
      "kind": "OBJECT",
      "name": "E",
      "ofType": null
    }
  ]
}
```

I suspect your union type `B` actually has fields, so your schema isn't quite what you are sharing here...

**Comment by josephsavona** [comment]
What @NevilleS said :-)

**Comment by calebmer** [comment]
Here’s what the introspection query result is. Names and descriptions are obfuscated of course.

```json
{
  "kind": "UNION",
  "name": "B",
  "description": null,
  "fields": null,
  "inputFields": null,
  "interfaces": null,
  "enumValues": null,
  "possibleTypes": [
    {
      "kind": "OBJECT",
      "name": "C",
      "ofType": null
    },
    {
      "kind": "OBJECT",
      "name": "D",
      "ofType": null
    },
    {
      "kind": "OBJECT",
      "name": "E",
      "ofType": null
    }
  ]
}
```

**Comment by NevilleS** [comment]
Hm. Alright, I'd recommend you add a snippet like this to `RelayQLPrinter.printField`:
```
      if (fieldType.getName({ modifiers: false }) == "B") {
        console.log("checking B type...")
        console.log("hasField('id')", fieldType.hasField(FIELDS.id))
        console.log("shouldGenerateIdFragment", shouldGenerateIdFragment(field, fieldType))
      }
```

**Comment by kassens** [comment]
Closing this as it refers to classic where we don't expect to do any major updates, please re-open if this still applies to the modern compiler.
