### ISSUE TITLE
Q: Not generating valid gql?

### ISSUE THREAD

**Issue by amccloud** [facebook/relay#121]
I've exhausted my debugging options and can't seem to figure out what is going on here

```
Syntax Error GraphQL request (1:87) Invalid number.\n\n1: query RootRoute{viewer{id,..._0l4ytoy}} fragment _0l4ytoy on User{displayName,_photos-kk19l4:photos(first:10){edges{node{id},cursor},pageInfo{hasNextPage,hasPreviousPage}},id}
```

```javascript
export default Relay.createContainer(RootController, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        displayName,
        photos(first: 10) {
          edges {
            node {
              id
            }
          }
        }
      }
    `
  }
});
```
```javascript
export default class extends Route {
  static routeName = 'RootRoute';
  static path = '/';
  static queries = {
    viewer: (Component) => Relay.QL`
      query {
        viewer {
          ${Component.getFragment('viewer')},
        }
      }
    `
  };
}
```

**Comment by yuzhi** [comment]
Nothing specific jumped out at me. The some of the gibberish characters you see are just auto-generated fragment names and field aliases. One thing I wanted to double check is does your `viewer` root field return a `User` type?

@dschafer does anything look out of place to you?

**Comment by dschafer** [comment]
> Syntax Error GraphQL request (1:87)

Syntax error is at character 87 in

```
query RootRoute{viewer{id,..._0l4ytoy}} fragment _0l4ytoy on User{displayName,_photos-kk19l4:photos(first:10){edges{node{id},cursor},pageInfo{hasNextPage,hasPreviousPage}},id}
```

Which by my math is pointing inside `_photos-kk19l4`. @leebyron, is that not a valid alias?

I can't repro this lex error on graphql-js master, either; I tried adding it as a text case to the lexer and it seems to pass just fine, weirdly.

**Comment by dschafer** [comment]
I think the hyphen might be confusing it.

**Comment by dschafer** [comment]
Yeah, according to the grammar, `-` isn't a valid token in an alias. So it is reading `_photos` as a `NAME`, then it sees `-` which ends the `NAME` and starts a `NUMBER`, then it sees `k` which is invalid in a number and throws.

**Comment by amccloud** [comment]
@yuzhi if I remove the photos field from the query it works just fine at returning my UserType.

**Comment by dschafer** [comment]
> I can't repro this lex error on graphql-js master, either; I tried adding it as a text case to the lexer and it seems to pass just fine, weirdly.

Ah, I had a bug in my code. Just submitted https://github.com/graphql/graphql-js/pull/139 which will slightly improve the error message here (and contains a minimal repro of this as a test case demonstrating the "expected" result).

**Comment by yuzhi** [comment]
I see. I'll update our alias function

**Comment by amccloud** [comment]
@yuzhi That fixed it for me!

**Comment by yuzhi** [comment]
#122 has been merged. Closing issue.
