### ISSUE TITLE
RANGE_DELETE `deletedIDFieldName`, could it be a function too?

### ISSUE THREAD

**Issue by IcanDivideBy0** [facebook/relay#1213]
Hi,
## Problem

I'm implementing a `RANGE_DELETE` mutation on a connection which nodes does not have `id` property.

The way I got it working is to send the node `__dataID__` as a mutation argument, and the server send it back in the mutation payload (which I belive is a strange thing to do).
## Proposal

Allow the `deletedIDFieldName` to be a function (in which I would return `this.props.node.__dataID__` directly). I can provide a PR relatively fast if you think this is the right way to go ?
### My detailed use case

Users playing multiple musical instruments, which you can fetch througt the following query

```
      fragment on User {
        playedInstruments {
          edges {
            node {
              name # this is mostly what looks like an id for an instrument
              label
            }
          }
        }
      }
```

On his probile page, he can add/remove the instruments he plays. here is the Relay mutation

``` js
export class ProfileRemovePlayedInstrumentMutation extends Relay.Mutation {
  getMutation() {
    return Relay.QL`mutation { removePlayedInstrument }`
  }

  getVariables() {
    return {
      // This is the data which will be returned as is from the server,
      // which could be ommited by the use of a function
      __dataID__: this.props.instrument.__dataID__,
      instrument: {
        name: this.props.instrument.name
      }
    }
  }

  getConfigs() {
    return [{
      type: 'RANGE_DELETE',
      parentName: 'user',
      parentID: this.props.user.__dataID__,
      connectionName: 'playedInstruments',
      pathToConnection: ['user', 'playedInstruments'],
      deletedIDFieldName: '__dataID__'
      // Proposal:
      // deletedIDFieldName: () => this.props.instrument.__dataID__
    }]
  }

  getFatQuery() {
    return Relay.QL`
      fragment on ProfileRemovePlayedInstrumentPayload {
        user { playedInstruments }
        instrumentEdge
      }
    `
  }
}
```

This way, the server desn't have to care about an id it never seen.

**Comment by mhahn** [comment]
i have a similar use case where i don't need data from the server to implement the RANGE_DELETE, function would work for me as well.

**Comment by wincent** [comment]
Thanks for the suggestion, @IcanDivideBy0. At the moment this is considered legacy API and we're unlikely to change it: instead, we are suggesting that people move to the newer `Relay.GraphQLMutation` API which is static, and closely aligned with the way Relay is heading in the future (we have a new core and APIs already starting to roll out on the `master` branch and will continue merging in new stuff over the coming weeks and months). As such, I'm going to close this, but thank you for your suggestion. Once the modern API is out, I'd welcome you to open a new issue or PR if you find that the API still isn't meeting your requirements. Thanks once again for your input!
