### ISSUE TITLE
debounce/throttle a mutation

### ISSUE THREAD

**Issue by gre** [facebook/relay#1217]
I was expected a mutation to have a debounce/throttle system, like you could define on it a delay to wait before the mutation will be sent to network but the optimistic update would apply instantly. This is important to not spam the server for all the kind of mutations that are "idempotents" and always replace a state.
For instance, if I am drag-moving an object that is saved with Relay, I don't want to send ALL pending positions but only want to debounce this.
throttling would be interesting too (important subtlety between debounce and throttle)

Is there a way with Relay? a workaround?
I tend to think it should be solved by Relay because the optimistic updates is important to be used for this to work properly (and without repeating the logic).

**Comment by BlooJeans** [comment]
Instead of commitUpdate() you can use applyUpdate(), which does the optimisticUpdate but doesnt send it to the server

```
// untested / wrote it freehand
var debounced = _.debounce((transaction) => transaction.commit(), 500);

function onDrag() {
  var transaction = this.props.relay.applyUpdate(new Mutation()); // optimistically updates immediately 
  debounced(transaction); // sends it to the server when the debounce lets it
}
```

**Comment by wincent** [comment]
Also, if you want to do any kind of custom batching/aggregation, you can use a custom network layer. [This](https://github.com/nodkz/react-relay-network-layer) is a good example of some of the things that can be done.

**Comment by gre** [comment]
sounds good! thanks for your fast answer!

**Comment by gre** [comment]
works great!

**Comment by nightspirit** [comment]
Seems like this only applies to Relay Classic. Any idea how do I make this work on Relay Modern?

**Comment by sibelius** [comment]
you can debounce on fetchQuery

**Comment by Secretmapper** [comment]
^ @sibelius How would the mutation be debounced in this case? (as in applying an update but not committing)?

**Comment by sibelius** [comment]
You can try to use commitLocalUpdate
