### ISSUE TITLE
[Specification compliancy] Access response's `extensions` entry

### ISSUE THREAD

**Issue by ooflorent** [facebook/relay#1219]
According to GraphQL's specification, section [7.2 Response Format](https://facebook.github.io/graphql/#sec-Response-Format), the response map may contain an entry with the key `extensions`.

> The response map may also contain an entry with key `extensions`. This entry, if set, must have a map as its value. This entry is reserved for implementors to extend the protocol however they see fit, and hence there are no additional restrictions on its contents.

In our endpoint, we use this entry the send warnings, mostly ACL related, to the client. Here is a sample query:

``` graphql
query GetUser {
  node(id: "VXNlcjox") {
    id
    email
  }
}
```

And its potential response including a warning:

``` json
{
  "data": {
    "node": {
      "id": "VXNlcjox",
      "email": null
    }
  },
  "extensions": {
    "warning": [
      {
        "message": "Insufficient permissions to read `email` field.",
        "locations": [{
          "column": 5,
          "line": 4
        }]
      }
    ]
  }
}
```

Currently it is not possible to read `extensions` using `RelayDefaultNetworkLayer` or using `RelayEnvironment#addNetworkSubscriber`. It would be really helpful if the complete response payload could be read:

``` js
function logWarnings(request) {
  request.getPromise().then(
    ({response, payload}) => {
      const warnings = _.get(payload, "extensions.warnings")
      if (warnings) {
        warnings.forEach(warning => {
          console.log(formatWarning(request, warning))
        })
      }
    }
  )
}

environment.addNetworkSubscriber(
  logWarnings,
  logWarnings,
)
```

How should we handle this using Relay?
Could such feature be implemented in a future?

Ideally, the subscriber API should allow developers to write such middlewares.

**Comment by josephsavona** [comment]
Thanks for letting us know about this. This is a recent addition to the spec that we have not used yet with Relay, hence the lack of support. Given that it is part of the spec, this is totally reasonable to support. I suspect this will include:
- Changing the default network layer to [resolve the request](https://github.com/facebook/relay/blob/master/src/network-layer/default/RelayDefaultNetworkLayer.js#L75) with all the keys that are listed in the GraphQL spec (something like `const {data, errors, extensions} = payload; resolve({data, errors, extensions});`)
- Changing the [response Flow type](https://github.com/facebook/relay/blob/master/src/tools/RelayTypes.js#L250-L254) to include these new fields with their respective types.
- Then run Flow and see if anything else needs to change :-)

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

If this is something you'd like to see happen, then we'd be happy to review a pull request.

If this issue is still important to you, please feel free to reopen it with an update.
