### ISSUE TITLE
Check the render method of `Relay(props => ReactElement)`.

### ISSUE THREAD

**Issue by ryancole** [facebook/relay#1224]
I'm using a lot of functional stateless components with relay. I'm not sure if this has to do specifically with the fact that I'm using these stateless components or not, but I feel like I only just recently started getting these less informative error messages.

```
Warning: Failed propType: Required prop `links` was not specified in `View`. Check the render method of `Relay(props => ReactElement)`.
```

The component / code that triggers this warning is below ...

```js
import React from "react";
import Relay from "react-relay";
import Navbar from "./Navbar";
import Footer from "./Footer";

View.propTypes = {
  links: React.PropTypes.array.isRequired
};

function View({viewer, children, links=[]}) {
  return (
    <div>
      <Navbar viewer={viewer} />
      {children}
      <Footer />
    </div>
  );
};

export default Relay.createContainer(View, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        ${Navbar.getFragment("viewer")}
      }
    `
  }
});
```

Is this because I'm exporting the container without assigning it to a variable, perhaps? I've used this "pattern" for several months, but don't recall seeing these types of warnings before. I thought I recalled seeing that actual component name in the warning?

**Comment by ryancole** [comment]
Never mind the fact that the prop related code is pointless here, I think, because that default variable is assigned after React checks the incoming props, it appears. This code just illustrates what my code looks like and that this code generates an error where the react component name is not appearing in warning messages.

**Comment by edvinerikson** [comment]
The issue is in the [getComponentName](https://github.com/facebook/relay/blob/master/src/container/RelayContainer.js#L1006-L1016) function and is casued because the `getReactComponent` function doesn't support functional components.

It should probably be changed to something like: `name = ComponentClass.displayName || ComponentClass.name || 'props => ReactElement'`
