### ISSUE TITLE
updateSchema fails on first run (BabelRelayPlugin)

### ISSUE THREAD

**Issue by papigers** [facebook/relay#1225]
When I run `updateSchema` to generate my `schema.json` file for `BabelRelayPlugin` for the first time I get the following error:
`Error: Cannot find module '../schema.json'`
 
Now I realize that it happens because I have my babel relay plugin set on `.babelrc`, so I tried to remove it, run updateSchema, add it back, and run my application, and it worked.

How can I run updateSchema without including the plugin?
I've tried creating another `.babelrc` file in the updateSchema folder, to override my project's .babelrc which includes the plugin, but that didn't work.

**updateSchema.js:**
```
'use strict';
require('babel-register');
let fs = require('fs');
let path = require('path');
let Schema = require('../schema');
let graphql = require('graphql').graphql;
let introspectionQuery = require('graphql/utilities').introspectionQuery,
    printSchema = require('graphql/utilities').printSchema;

(function(){
  graphql(Schema, introspectionQuery).then(function(result){
    if(result.errors){
      console.error('Error inspecting schema: ', JSON.stringify(result.errors, null, 2));  
    }
    else{
      fs.writeFileSync(path.join(__dirname, '../schema.json'), JSON.stringify(result, null, 2));  
    }
  });
})();

fs.writeFileSync(path.join(__dirname, '../schema.graphql'), printSchema(Schema));
```

**BabelRelayPlugin.js:**
```
var getBabelRelayPlugin = require('babel-relay-plugin');
var schema = require('../schema.json').data;

module.exports = getBabelRelayPlugin(schema);
```

**.babelrc:**
```
{
  "presets": [
    "react",
    "es2015",
    "stage-0"
  ],
  "plugins": [
    "./data/plugins/babelRelayPlugin",
    "add-module-exports",
    "transform-class-properties",
    "transform-runtime"
  ],
  "compact": true
}
```

**Comment by HyperSimon** [comment]
How did you solve this problem?

**Comment by nodkz** [comment]
For this case i wrote https://github.com/nodkz/babel-plugin-transform-relay-hot

Which successfully starts without schema.json. And when it somehow generated hot reload babelRelayPlugin without restarting you dev server which runs via babel.
