### ISSUE TITLE
__typename is null when an optimistic update is applied

### ISSUE THREAD

**Issue by calebmer** [facebook/relay#1230]
I have a `Node` that I want to update with an optimistic update, but that `Node` is also returned by a union so I need to get the `__typename` from the union. However, it would appear that after an optimistic update has been applied and before the response comes back, the value of that `__typename` on the union is `null`.

**Comment by josephsavona** [comment]
Just to clarify, are you explicitly setting the `__typename` field in your optimistic response?

**Comment by calebmer** [comment]
No

**Comment by calebmer** [comment]
It does work when `__typename` is set in `getOptimisticResponse` though. Is this expected behavior?

**Comment by josephsavona** [comment]
Yes, this is expected behavior. Relay can't know what type you meant to create within a union, so you have to specify it. It may be possible to infer the type in some cases that we don't today, but a union would always require it to be specified by the user.

**Comment by wincent** [comment]
Going to close this out, but feel free to comment again @calebmer if you'd like to know more. Thanks for bringing this up.
