### ISSUE TITLE
Optimistic Range Update only handles `prepend` or `append` ?

### ISSUE THREAD

**Issue by xuorig** [facebook/relay#1244]
Looking at the `RelayRecordWriter`

https://github.com/facebook/relay/blob/master/src/store/RelayRecordWriter.js#L568-L590

It seems like the optimistic range updater only checks for `PREPEND` and appends to the queue otherwise. `REMOVE` is not handled.

Now this brings another question. Should `REMOVE` really be an accepted rangeBehavior for a `RANGE_ADD` ? In what cases is this useful, and why would you not use `RANGE_DELETE` in these cases ?

I might've missed something here, let me know!

**Comment by johanobergman** [comment]
The reason I can think of is this: in TodoMVC, let's say you have two queries, `todos(completed: true)` and `todos(completed: false)`. When you change the status of the a todo, you'll want to add it to one of the connections and remove it from the other, like this:
```javascript
// ChangeTodoStatusMutation.js
getConfigs() {
  return [{
    type: 'FIELDS_CHANGE',
    fieldIDs: {
      todo: this.props.todo.id,
    },
  }, {
    type: 'RANGE_ADD',
    parentName: 'viewer',
    parentID: this.props.viewer.id,
    connectionName: 'todos',
    edgeName: 'todoEdge',
    rangeBehaviors: ({complete}) => {
      return complete === this.props.complete ? 'append' : 'remove';
    },
  }];
}
```
At least I think it works like this!

**Comment by xuorig** [comment]
Yep that makes sense @johanobergman!

I guess this is due to `RANGE_DELETE` no having access to the calls, unable to make a decision as to removing or node the edge. If it allowed a function similar to `RANGE_ADD` has, this could be rewritten has a `RANGE_ADD` + `RANGE_DELETE`.

The other question remains: It seems like the optimistic range updater only checks for PREPEND and appends to the queue otherwise. REMOVE is not handled. That seems strange.

**Comment by yuzhi** [comment]
You are right! we seem to be missing the remove case for the optimistic updates. We probably didn't notice because it is handled correctly for the server response. We'll fix it soon!

**Comment by xuorig** [comment]
@yuzhi I can submit a fix for it if you'd like!

**Comment by yuzhi** [comment]
@xuorig That would be awesome! Please also add a unit test so we catch this in the future.

**Comment by xuorig** [comment]
👍

**Comment by xuorig** [comment]
So to my surprise, I found tests that expected edges to be removed with the `REMOVE` range operation.

Optimistic range updates work with the `REMOVE` range operation too. It is just a little bit confusing when looking at the function.

Depending on the rangeOperation, `_applyOptimisticUpdate` pushes to a queue located to a certain key. When the `rangeOperation` is `REMOVE`, the key is `__rangeOperationAppend__`.

The `edgeID` is pushed into that queue:
https://github.com/facebook/relay/blob/master/src/store/RelayRecordWriter.js#L585-L588

When retrieving rangeInfo, https://github.com/facebook/relay/blob/master/src/legacy/store/GraphQLRange.js#L957-L960.

That key is fetched, and every edge in the queue is removed.

I think we can close this, feel free to reopen if needed.
