### ISSUE TITLE
toGraphQL gets null type for enum variable

### ISSUE THREAD

**Issue by papigers** [facebook/relay#1256]
I'm using `isomorphic-relay`,  and I'm encountering some problem, which you can read about in more details [here](https://github.com/denvned/isomorphic-relay/issues/42). 

The relevant part for you, is that I saw the server's preloaded data looks like this:
```
...
...
{
          "children": [
            {
              "calls": [
                {
                  "kind": "Call",
                  "name": "orderBy",
                  "metadata": {
                    "type": null
                  },
                  "value": {
                    "kind": "CallValue",
                    "callValue": "TRENDING"
                  }
                },
                {
                  "kind": "Call",
                  "name": "first",
...
...
```

Here you can see that the type of `orderBy` is null, instead of PollSort, an enum type. 

The above snippet is, as mentioned, part of the preloaded data the server passed to the client. This is done in this file: [prepareData.js](https://github.com/denvned/isomorphic-relay/blob/master/src/prepareData.js). The relevant line is:
```
data.push({ query: toGraphQL.Query(request.getQuery()), response });
```

So the root of the problem is actually that `toGraphQL.Query` returns null for my input variable type. 

Any idea how can this be fixed?

**Comment by josephsavona** [comment]
Thanks for filing such a detailed issue. It looks like `callsTooGraphQL` isn't passing the call type to `QueryBuilder.createCall`. Care to send a PR to fix?

**Comment by papigers** [comment]
I'd be happy to, but I'm a bit of a newbie to this repo, and relay in general. How can I get the call type from `callsToGraphQL`?

**Comment by papigers** [comment]
Oh it's simply an attribute of `Call`. I'd try to fix this as soon as I get home.

**Comment by papigers** [comment]
Done. #1257, though there are some build errors...
