### ISSUE TITLE
Documentation includes an invalid example for `RANGE_DELETE` mutation config

### ISSUE THREAD

**Issue by NevilleS** [facebook/relay#1262]
We ran into this today while setting up a `RANGE_DELETE` mutation. As of 71e2350ccb2bd3c8ce145d270788c9042b5fbff5, mutation configs are validated by Relay, which requires the user specify all the fields on the `RANGE_DELETE` config. However, the example in the docs doesn't include it:

```
  getConfigs() {
    return [{
      type: 'RANGE_DELETE',
      parentName: 'todo',
      parentID: this.props.todo.id,
      connectionName: 'tags',
      deletedIDFieldName: 'removedTagIDs',
    }];
  }
```
(from https://facebook.github.io/relay/docs/guides-mutations.html#range-delete-example)

One of two things is wrong here:

1. The docs are wrong, and should be updated to avoid confusing new users
2. The validation is wrong, and `pathToConnection` should not be `REQUIRED` so this example is fine

I found myself a bit bamboozled trying to re-read the docs here, so it might actually be both (1) and (2) 😄

**Comment by NevilleS** [comment]
I'm going to go ahead and cc @wincent here because in his commit message for 71e2350 it looked like he was a little unsure about whether everything should be `REQUIRED` 👍

**Comment by wincent** [comment]
@NevilleS, when I prepared that commit I basically went through and analyzed all the code paths and came to the conclusion that everything was required except for `parentName`. So, I think the examples in the docs are most likely incomplete and should be updated. It's complicated, however, so there is a chance that I got it wrong too.

**Comment by NevilleS** [comment]
Ah OK. For `RANGE_ADD` it seems like specifying both `pathToConnection` and `connectionName` is duplicative but I haven't analyzed the code paths so I'll defer to you here.

It's likely just a docs issue. If I was having a less crazy week I'd submit a PR, sorry 😢

**Comment by josercruz01** [comment]
Hey guys I stumbled into this as well when reading the documentation and using the latest `relay` version. Looking at the code it does seem that the field is required. In any case, the example should reflect the current status and since the validator will fail if you don't send the `pathToConnection` field I put up a PR that adds the field to the example.

Let me know if that sounds good.
