### ISSUE TITLE
What does `Cannot return null for non-nullable field ...clientMutationId` means?

### ISSUE THREAD

**Issue by CoericK** [facebook/relay#1270]
Im about to become crazy with this error, 

I calling a mutation using the Mutator configuration as FIELDS_CHANGE, to update the name of the current viewer, the mutations on the server seems to be updating the data just, but I keep getting this response and I have no idea of what else to do:
```
{
  "data": {
    "updateUser": null
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field UpdateUserPayload.clientMutationId.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

**Comment by CoericK** [comment]
The problem was that `mutateAndGetPayload` was receiving `args`, besides the arguments that you specifies in inputFields, it add one more field`clientMutationId`, i was passing args to my custom function and it was cleaning up the fields that doesnt match with my model, in this case `clientMutationId`, so  the solution was to make a copy from args like this, `let _args = Object.assign({}, args)`, it was passing the args argument by reference and then when `outputFields` was called the field `clientMutationId` didnt exists

@josephsavona maybe u want to consider this for the future.

**Comment by brianyang** [comment]
For me the problem was that the value defined in NEDB was null. Removing the null values resolved this issue.
