### ISSUE TITLE
Website shows mismatched description and Relay playground after back button

### ISSUE THREAD

**Issue by fadils** [facebook/relay#1288]
Tested on:
- Chrome Version 51.0.2704.103 (64-bit)

Worked fine on Firefox, though.

Steps to reproduce:

1. Go to:
https://facebook.github.io/relay/

2. Click to any link such as [Docs](https://facebook.github.io/relay/docs/getting-started.html#content), or [Support](https://facebook.github.io/relay/support.html), or any other link.

3. Click `Back` in your Chrome browser

4. While the description is saying about Tea example, the playground instead is showing a HelloWorld example.

![screen shot 2016-07-16 at 10 45 23 am](https://cloud.githubusercontent.com/assets/6204776/16892605/74e1e79c-4b42-11e6-8aa0-4bbc28dfcf81.png)

Similar thing happens to Simple Parameterization and Simple Mutation sections.
![screen shot 2016-07-16 at 10 48 46 am](https://cloud.githubusercontent.com/assets/6204776/16892612/f236bb82-4b42-11e6-815e-68fc8201acee.png)
![screen shot 2016-07-16 at 10 48 59 am](https://cloud.githubusercontent.com/assets/6204776/16892613/f239a8e2-4b42-11e6-8fcb-da9f97f0b800.png)

**Comment by wincent** [comment]
Going to close this out because we will be rebuilding the website/playground experience for the release of [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable). 

Thanks for the report @fadils, and sorry that we never got to this!
