### ISSUE TITLE
Default network layer seems to be using a relative path?

### ISSUE THREAD

**Issue by rterysen-openroad** [facebook/relay#1291]
I seem to be getting a relative path for my "POST" mutation requests.  

When i create my default network layer I pass it localhost:3000/graphql. 

Please reference console logs before with there values commented next to them. 
```
  function RelayDefaultNetworkLayer(uri, init) {
      console.log("top level uri:" , uri);   //Localhost:3000/graphql  as desired

    _classCallCheck(this, RelayDefaultNetworkLayer);

    this._uri = uri;
    this._init = _extends({}, init);

    // Facilitate reuse when creating custom network layers.
    this.sendMutation = this.sendMutation.bind(this);
    this.sendQueries = this.sendQueries.bind(this);
    this.supports = this.supports.bind(this);
  }

```

 ```
 RelayDefaultNetworkLayer.prototype._sendMutation = function _sendMutation(request) {
    console.log("request in relay: ",request);
    var init = undefined;
    var files = request.getFiles();
    if (files) {
      if (!global.FormData) {
        throw new Error('Uploading files without `FormData` not supported.');
      }
      var formData = new FormData();
      formData.append('query', request.getQueryString());
      formData.append('variables', JSON.stringify(request.getVariables()));
      for (var filename in files) {
        if (files.hasOwnProperty(filename)) {
          formData.append(filename, files[filename]);
        }
      }
      init = _extends({}, this._init, {
        body: formData,
        method: 'POST'
      });
    } else {
      init = _extends({}, this._init, {
        body: JSON.stringify({
          query: request.getQueryString(),
          variables: request.getVariables()
        }),
        headers: _extends({}, this._init.headers, {
          'Accept': '*/*',
          'Content-Type': 'application/json'
        }),
        method: 'POST'
      });
    }

    console.log(this._uri);  // /graphql which is going to localhost:4444/graphql
    return fetch(this._uri, init).then(throwOnServerError);
  };

```

console error in browser. 

RelayDefaultNetworkLayer.js:131 POST http://localhost:4444/graphql 404 (Not Found)

What am I doing wrong? All of my request to get data and display it work great!! 

Only when i send a mutation.

**Comment by josephsavona** [comment]
Thanks for filing an issue. The default network layer uses the same URI for [both queries and mutations](https://github.com/facebook/relay/blob/master/src/network-layer/default/RelayDefaultNetworkLayer.js#L126,L134), so it isn't immediately obvious what could be causing one to work and the other to fail. Could you try adding a breakpoint to the network layer and double check that the URI is what you'd expect? It sounds like there is some local configuration that is causing this to fail.

**Comment by josephsavona** [comment]
@rterysen-openroad Were you able to resolve this? I'm going to close this since it *looks* like a configuration issue. If you're still having trouble, though, feel free to reopen this issue or comment or with more information. Thanks!

**Comment by rterysen-openroad** [comment]
@josephsavona  Sorry i took so long to respond i got sidetracked with other tasks. at work. I am still having this issue.  I ended up putting in a shim that hardcoded the url within relay to make sure the rest of my code was working correctly. 

When i log out my network layer i see below. Below is what prints out in terminal from the backend. 

```
//renderonserver.js 
 const networkLayer = new Relay.DefaultNetworkLayer(process.env.GRAPHQLURL);
       console.log("network: ", networkLayer);

network:  RelayDefaultNetworkLayer {
[1]   _uri: 'http://localhost:3000/graphql',
[1]   _init: {},
[1]   sendMutation: [Function: bound sendMutation],
[1]   sendQueries: [Function: bound sendQueries],
[1]   supports: [Function: bound supports] }
```

below is what prints out in console on the web browser. 

```


// Create Relay environment
const environment = new Relay.Environment( );
environment.injectNetworkLayer( new Relay.DefaultNetworkLayer(
  'http://localhost:3000/graphql',{
  credentials: 'same-origin',
}));
console.log("assigned", environment);
![screen shot 2016-08-01 at 12 04 37 pm](https://cloud.githubusercontent.com/assets/17296866/17300392/37393b02-57e0-11e6-96d7-a1778d6df018.png)

```

I pass this into the router like so 

IsomorphicRelay.injectPreparedData(environment, data);

const rootElement = document.getElementById('root');

console.log("enviroment", environment);

```
match( { routes, history: browserHistory }, ( error, redirectLocation, renderProps ) => {
  IsomorphicRouter.prepareInitialRender( environment, renderProps ).then( props => {
    ReactDOM.render( <Router {...props} />, rootElement );
  } );
} );

```
Thanks for all of your help!! i am sorry for the delayed response.

**Comment by josephsavona** [comment]
Thanks for providing more detail - unfortunately this doesn't help to clarify why mutations are not working correctly. 

I did notice that it seems you are doing server side rendering using `isomorphic-relay`. Could this be related? Are you attempting to issue a  mutation on the server instead of the client or something similar?

**Comment by rterysen-openroad** [comment]
Thank you @josephsavona,  for your help!!  I am still learning this whole environment but I really don't believe it would be related to the server render.  Of course I could be wrong.  After the initial load the mutations would triggered off form submissions. I believe that relay would look directly at the graphql server at that point and not be interactive with the express instances serving it.   

I have Graphql  set up in a separate code source.  Also it doesn't spin up as part of the same project hence the issue with it not being a relative path.  The only thing that blows my mind is that my read queries work fine. No matter where I click or what I do I never have a issue grabbing data.  It is only the mutations.  I already troubleshooted this but my guess was the client.js file that has the routing it in it. All my logs show the correct url. 

I added a shim on line 120 of the default network layer that concats the url to the "/graphql" path to get the app working for the mean time. With that in place it works fine.  It keeps me up at night though :) ! 

I dont see it making any calls to the node instance that is performing the isomorphic render.  I only see the call on the graphql server.  


Thanks for helping me out with this. I know it has got to be really hard to figure out what is wrong over a conversation of comments.  My team and I are really loving relay beside this bug that we cant seem to fix.

**Comment by mbavio** [comment]
I'm experiencing this problem too. Queries get the correct url but mutations are always looking for the relative default url. It only happens with a custom environment created with `new Relay.Environment()`, if I use `Relay.Store` singleton instead, it works fine. Any way I could help with a solution for this issue?

**Comment by mbavio** [comment]
@rterysen-openroad Not sure if you are still having the issue, but I found the solution to the my problem at least: turns out I was still using `Relay.Store.commitUpdate` to run mutations, so the default setup was used as expected, since I updated settings for my custom Environment, not for the Store. 

I solved it by simply doing `enviromment.commitUpdate()` instead!
