### ISSUE TITLE
GraphQLRange is not properly deserialized

### ISSUE THREAD

**Issue by Aweary** [facebook/relay#1293]
`RelayEnvironmentSerializer` just takes the `_storeData` and serializes it. When this happens, instances of `GraphQLRange` are not properly serialized, and `RelayRecordStore` does do any checks before calling `retrieveRangeInfoForQuery` on the range returned from `_getField`.

I understand that `RelayEnvironmentSerializer` is not even documented or released, but I wanted to see if this was being worked on, or if you would be open to accepting PRs fixing/expanding the current serialization behavior.

**Comment by Aweary** [comment]
I see that `GraphQLRange` has a `toJSON` field specifying it's serialized state, so it seems its more an issue of parsing that serialized state.

**Comment by josephsavona** [comment]
I commented on the PR - as you noted, `RelayEnvironmentSerializer` is designed to solve this problem, so let's use that.

**Comment by josephsavona** [comment]
Thanks for starting this discussion. Since you already have a PR open, let's discuss there.
