### ISSUE TITLE
Type checking graphql queries/fragments by flow.

### ISSUE THREAD

**Issue by pvolok** [facebook/relay#1297]
I had a brief discussion with @jeffmo about making flow understand graphql. He suggested to ask Relay team about how you solve the problem of typing relay apps. In the meeting notes it says that @sampepose is working on flow types generation script, but nothing I could find about what that is.

Can you provide any details about your approach for typing relay apps? Would it bring any value if flow supported graphql?

What I mean by graphql-support is parsing queries/fragments like ``Relay.QL`fragment on User {...}` ``, validating them, generating prop types for relay-components, etc.

**Comment by sampepose** [comment]
Hi @pvolok!

I've been working on a script that parses JS and generates Flow types from Relay.QL template strings. We're starting to use this to automatically add typing to mutation arguments and Container fragments for our internal Relay apps. This is especially useful for React Native, where a runtime error crashes the entire app.

Unfortunately, the script relies on a few internal modules that we aren't quite ready to publish. We're hoping to eventually open-source the script, but there's no current timeline I can give.

**Comment by pvolok** [comment]
Thanks @sampepose!
