### ISSUE TITLE
react should be in peerDependencies

### ISSUE THREAD

**Issue by spicyj** [facebook/relay#13]
https://github.com/facebook/relay/blob/0f546869f549bd3939f7fe5744f233f1f7574401/package.json#L35 should be in peerDependencies, or else you'll get multiple copies of React in some cases and it's important that that doesn't happen.

**Comment by zpao** [comment]
I missed that before launch, oops! Looks like the examples are all ok and it should be as simple as removing it from `dependencies` to `peerDependencies` (and then also specifying it in `devDependencies` so tests work)
