### ISSUE TITLE
Invalid mutations with `getFiles` method in the docs

### ISSUE THREAD

**Issue by mhahn** [facebook/relay#1306]
It looks like this example is incomplete:

https://facebook.github.io/relay/docs/api-reference-relay-mutation.html#getfiles-example

I tried using something similar and got errors related to required abstract methods not being implemented.

Something to indicate the mutation is incomplete would be useful.

**Comment by Globegitter** [comment]
What is the exact error message you are getting? It should tell you which abstract methods you need to implement. But they probably are `getMutation`, `getFatQuery`, `getConfigs`, and `getVariables`.

**Comment by sibelius** [comment]
@mhahn could u provide more information?

**Comment by wincent** [comment]
Closing due to staleness.
