### ISSUE TITLE
Race condition when query config params change while setVariables is outstanding

### ISSUE THREAD

**Issue by taion** [facebook/relay#1316]
I'm observing the following in my app:
1. I call `props.relay.forceFetch`
2. I update the top-level query config with new params that eventually get injected down into the container on which I called `forceFetch` in (1)
3. Request from (2) completes and updates `state.rawVariables`
4. On the call in (1) succeeding, `state.rawVariables` is set to the _old_ value from before (2)
5. If I call `forceFetch` again, in `_runVariables`, the stale value of `state.rawVariables` set in (4) gets used; while the request is outstanding, I see the data corresponding to those stale variables

I'm not sure what the right fix here is. Seems like it could be either:
- Abort pending requests in cWRP if `context.route` changes
- In `_runVariables`, check that things haven't changed underneath us before setting `state.rawVariables`

Or maybe something else?

**Comment by chirag04** [comment]
I'm also observing this when child component sets a variable and parent is forceFetching

**Comment by taion** [comment]
@chirag04 I believe this is a different issue from https://github.com/facebook/relay/issues/1138. I don't override any variables at all – they're all coming down from the query config params.

**Comment by chirag04** [comment]
@taion my guess is the two are related since there is a common code path for `setVariables` and `forceFetch`. I don't understand the internals yet so i might be completely wrong.

**Comment by josephsavona** [comment]
Thanks for filing this, it definitely sounds like an edge case that isn't handled yet.

There is a definite similarity to #1138 in that variables are changing at two levels of the tree at the same time, and Relay should either make a decision about which one wins and be consistent in implementing that (i.e. w/o races), or ideally allow the product developer to have some control. The latter is something we are working on in the long-term (by making the work that `setVariables` does more explicit). The former is more practical in the short-term. 

Generally speaking there are a few cases we'd need to handle:
1. The route object changes (!==) but its name, queries, and params are all the same. `RelayRenderer` *should* already detect this and do nothing.
2. The route object changes queries/components in such a way that the original children are unmounted and a different tree is rendered: nothing to do here.
3. The route object changes params, such that the same ancestor component (lets call it `<User user={...} />`) is still rendered. 
  1. If User gets a different user prop - the id has changed - it has to throw away any pending fetches it may be doing and show the new data.
  2. If User gets the same user prop, but the route params have changed, what to do with any pending fetches depends on whether the route params are overriding User's params. If the route says to set `count: 5`, and the component is trying to fetch `count: 10`, then the variables have to be reset and the pending fetch cancelled. If the route isn't overriding any variables, then it's safe to just let the pending fetch finish and use the results of those variables. 

Thoughts?

**Comment by taion** [comment]
It seems like it ought to be possible to simplify (3) to just check for deep equality of the `queries` and `params`. If you don't, I think it's still possible to end up with race conditions. I can't immediately construct a race condition, but it seems like it'd be more predictable to just abort pending requests on any "real" change to the route object.

**Comment by wincent** [comment]
Closing out some old issues involving the Relay Classic APIs because they are not being actively working on any more; all future work is going to go towards Relay modern, which doesn't have a `setVariables` any more.
