### ISSUE TITLE
Relay.DefaultNetworkLayer enhancements

### ISSUE THREAD

**Issue by tberman** [facebook/relay#1323]
I have been playing around with the DefaultNetworkLayer, and I know that the common advice is that it should be replaced with a custom one. However, looking at it, if there was a small middleware layer, you could implement retries, header based auth, handling token expiry/failure all outside of it allowing DefaultNetworkLayer to become much more useful and reusable.

Given the common advice of rip and replace, before I went about putting together a PR for that I wanted to check to see if that PR would be accepted upstream?

**Comment by josephsavona** [comment]
Thanks for asking. We would prefer to keep the default network layer as simple as possible. Advanced functionality can be achieved by injecting a different implementation - either your own or something like nodkz/relay-network-layer (which provides middleware, among other things). 

I believe that your use cases should already be covered by the existing APIs and third party modules. If not, feel free to comment here and we can reopen to discuss more!
