### ISSUE TITLE
[Please help me]Fetch API cannot load https://g.fb.com/graphql. Response for preflight has invalid HTTP status code 405

### ISSUE THREAD

**Issue by tungh** [facebook/relay#1324]
Fetch API cannot load https://g.fb.com/graphql. Response for preflight has invalid HTTP status code 405

```
const graphql = express();
graphql.all('*', (req, res, next) => {
  res.header('Access-Control-Allow-Origin', 'https://c.fb.com');
  next();
});
graphql.use('/graphql', graphQLHTTP({
  graphiql: true,
  pretty: true,
  schema
}));
graphql.listen(config.graphql.port, () => console.log(chalk.green(`GraphQL is listening on port ${config.graphql.port}`)));

```

I use in https://c.fb.com

```
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('https://g.fb.com/graphql', {
    fetchTimeout: 30000,
    retryDelays: [5000, 10000],
  })
);
```

console error 
`Fetch API cannot load https://g.fb.com/graphql. Response for preflight has invalid HTTP status code 405`

**Comment by josephsavona** [comment]
Do you own the domain `fb.com`? I suspect not, and this is why you are getting errors accessing it. 

I would recommend running your server locally and then access it with localhost:<port>
