### ISSUE TITLE
Doesn't optimize single object vs connection?

### ISSUE THREAD

**Issue by unirey** [facebook/relay#1328]
Relay doesn't optimize my queries (I have some data about the object in Store but it will query it anyway).

Take this for example: there's a list of posts and if you click on a list item, you'll go to single post route.

### List:

```
export default Relay.createContainer(PostList, {
    fragments: {
        viewer: () => Relay.QL`
            fragment on Viewer {
                posts(first: 2) {
                    edges {
                        node {
                            id,
                            title,
                            author {
                                id,
                                name
                            }
                        }
                    }
                }
            }`
    }
})
```

### Single post:

```
export default Relay.createContainer(SinglePost, {
    fragments: {
        viewer: () => Relay.QL`
            fragment on Viewer {
                post(id: $postId) { 
                	id,
                	title,
                	content,  // <- shouldn't it be the only one to get queried and returned?
                	author {
                		id,
                		name
                	}
                }
            }`
    }
})
```

- All global ID-s are correct and the single post ID matches the post ID from list / connection.
- Relay does everything correctly in Store: no duplicates and it adds fresh data where appropriate.

## Problem:

It still makes a whole request and gets the whole object back, it doesn't optimize it and remove the fields/data I already have in Store.

Quote from [this article](http://hueypetersen.com/posts/2015/09/30/quick-look-at-the-relay-store/) (cause?):

> One downside to this flexibility is if we query the organization root for id 69631 (e.g. organization(id:69631)) Relay can’t assume the root call argument maps directly to the global id so a full query is sent even if we already have an object with the global id of 69631. Once that mapping is in place though subsequent queries will be able to intelligently diff with the store.

How to make this work appropriately? There **a lot** of wasted resources here. 

Do I need to help or hint Relay somehow? Do I need to use `node` manually in my queries?

**Comment by josephsavona** [comment]
Thanks for the detailed post.

> Do I need to use `node`

Yes! In this example, Relay doesn't know what value will be returned by `query { viewer { post(id: $postID) { ... } } }`. The `post` field could return just about anything - *you* know that it will return an object whose `id` is the same as the `id` argument, but Relay doesn't.

To support efficiently refetching data, Relay has special support for a [`node`](https://facebook.github.io/relay/docs/graphql-object-identification.html#content) root field. If you implement this root field ([`graphql-relay-js`](https://github.com/graphql/graphql-relay-js) provides helpers for this), you can replace `viewer { post(id: $id) }` with `node(id: $id)` and you'll get exactly the behavior you're expecting :-)

**Comment by josephsavona** [comment]
I'm closing this issue since this is a known and documented behavior of the system, but we're open to feedback and happy to answer more questions here.

**Comment by unirey** [comment]
Thank you @josephsavona! 
It's so good to finally get a solid answer, I've been trying to get it for a week or so in stackoverflow.com

I've implemented node definitons but main issue is that `type `is almost always Viewer and `id `is viewer's / user's ID. Im not sure how to approach the viewer issue, any suggestions? What am I doing wrong?  

`const {type, id} = fromGlobalId(globalId)`


## Minimalistic example:

```
const {nodeInterface, nodeField} = nodeDefinitions(
    async (globalId) => {
        const {type, id} = fromGlobalId(globalId)

        console.log(id)  // always viewer's / user's ID
        console.log(type) // always "Viewer" :(

        if (type === 'Viewer') {
            return await getUserById(id)
        } 
        if (type === 'User') {
            return await getUserById(id)
        } 
        if (type === 'Post') {
            return await getPostById(id)
        }
        return null
    },
    (obj) => {
        if (obj instanceof Viewer) {
            return viewerType
        } 
        if (obj instanceof User) {
            return userType
        } 
        if (obj instanceof Post)  {
            return postType
        }
        return null
    }
)
```

```
const viewerType = new GraphQLObjectType({
    name: 'Viewer',
    fields: () => ({
        // fields
    }),
    interfaces: [nodeInterface],
})

const userType = new GraphQLObjectType({
    name: 'User',
    fields: () => ({
        // fields
    }),
    interfaces: [nodeInterface],
})

const postType = new GraphQLObjectType({
    name: 'Post',
    fields: () => ({
        // fields
    }),
    interfaces: [nodeInterface],
})
```

**Comment by unirey** [comment]
Thank you @josephsavona! 
It's so good to finally get an answer, I've been trying to get it for a week or so in stackoverflow.com

I still have one big question about `node`: if I could query all different single items (`post`, `user` _etc_) _via_ `node`, why do I even need `post(args)`, `user(args)` in queries? All the examples I've seen online, have them. 
Only because I can't use other arguments besides `id` in `node` (as far as I know)? That would mean that if I needed to add arguments, I would still not be able to benefit from query optimization?
