### ISSUE TITLE
Filed names cant end with number?

### ISSUE THREAD

**Issue by yangit** [facebook/relay#1330]
I will sound stupid but may this be a bug?
If name of the field ends(contains?) with a number than optimistic updates will not work.
Here is the stripped down repo to reproduce:
[https://github.com/yangit/relayNumberBug](https://github.com/yangit/relayNumberBug)

There are 2 branches which are different by one field name containing one extra symbol!
Here is the link to a [diff](https://github.com/yangit/relayNumberBug/commit/650719096ddbff8539a3a051f2915bad5fedf7e9)

By looking at it could you guess why such a small change could break optimistic updates?

I have no errors in console in any case
I rebuild schema
I refresh my browser using hard refresh
I replace `thisIsUniqueName` using global project search
I knock my head against the wall

Any ideas?

**Comment by josephsavona** [comment]
Tgat is super weird. Relay treats field names as opaque - it doesn't substring them or treat numbers in the field name specially (not on purpose, at least). Are you *sure* there's nothing else different, and that you've updated the schema appropriately with the right field names? Just checking to rule out obvious things.

**Comment by yangit** [comment]
I have no errors in console in any case
I rebuild schema
I refresh my browser using hard refresh
I replace thisIsUniqueName using global project search
I knock my head against the wall

I'm not **sure** but I tried my **best** to eliminate all listed issues.
If you think I can try something else let me know.
BTW I can change name to any other unique name if it does not end with number.
Here is a link to non breaking change  `https://github.com/yangit/relayNumberBug/commit/28f27c28ed181fb4bf275c54f977d455156711c8`

**Comment by yangit** [comment]
Anyone mind doing `npm install` then `npm start` and looking at `localhost:3000` in two different branches?
Detailed instructions are given [here](https://github.com/yangit/relayNumberBug)
I would deeply appreciate that.

**Comment by yangit** [comment]
Here is an example of what I see in debugger
`_conversations3sn0Oo:conversations(first:1000)`
That is for a field called `conversations`
That number `3` there is definitely added by `Relay`
Something to do with params?
Could that be a reason?

**Comment by wincent** [comment]
Relay Modern is now out so I am closing these old issues that pertain to the legacy core, because nobody is actively working on that anymore. Please file any new issues relevant to the new core separately. Thanks!
