### ISSUE TITLE
setVariables() not querying

### ISSUE THREAD

**Issue by unirey** [facebook/relay#1332]
- Im was just testing Relay's abilities of refetching the data but it fails for mysterious reason
- `setVariables()` is updating `this.props.relay.variables.count` as expected
- View is updating correctly if I have enough data from initial load - both increase and decrease
- No errors (unless I decrease `count` to 0 or less)

It just doesn't send the query, I checked with React Developer Tool (Chrome extension) and on server side.

**What could be the reason?** I didn't find any information about possible causes.

```
import React from 'react'
import Relay from 'react-relay'

import PostItem from './post-item'


class PostList extends React.Component {

    render() {
        return (
            <div>

                <button onClick={this.handleIncrease.bind(this)}>Increase</button>
                <button onClick={this.handleDecrease.bind(this)}>Decrease</button>

                <ul>
                    {this.props.viewer.posts.edges.map((edge) =>

                        <li key={edge.node.id}>
                            <PostItem
                                id={edge.node.id}
                                title={edge.node.title} 
                                content={edge.node.content} 
                            />
                        </li>

                    )}
                </ul>

            </div>
        )
    }

    handleIncrease() {
        this.props.relay.setVariables({
            count: this.props.relay.variables.count + 1
        })
    }

    handled() {
        this.props.relay.setVariables({
            count: this.props.relay.variables.count - 1
        })
    }
}


export default Relay.createContainer(PostList, {
    initialVariables: {
        count: 5
    },
    fragments: {
        viewer: () => Relay.QL`
            fragment on Viewer {
                posts(first: $count) {
                    edges {
                        node {
                            id
                            title
                            content
                        }
                    }
                }
            }`
    }
})
```

**Comment by unirey** [comment]
Found the issue: I didn't set up `hasNextPage` code yet and it was `false`. If it's false, Relay thinks that there's no more posts in database and doesn't fetch more.

It's very logical but I still wish it was in docs because it's hard to think of that if you just started with Relay.

**Comment by josephsavona** [comment]
Thanks for asking, and following up! Good point about `hasNextPage`, we'll keep this in mind. Also, feel free to submit a PR to update the docs - if there was a place that you looked and thought it should be mentioned, add it there!
