### ISSUE TITLE
"Using `null` as a rangeBehavior value is deprecated" when using "ignore"

### ISSUE THREAD

**Issue by miracle2k** [facebook/relay#1337]
I implement `rangeBehaviours` as a function and return "ignore". Relay shows me this warning:

`Using `null` as a rangeBehavior value is deprecated. Use `ignore` to avoid refetching a range.
`
Callsite: https://github.com/facebook/relay/blob/712f5926cb67312aac284feef3ab3ed5e147c587/src/traversal/writeRelayUpdatePayload.js#L416

Is the condition there wrong? I'm thinking it might need to be `(!rangeBehavior && rangeBehavior !== IGNORE)`

**Comment by xuorig** [comment]
Oops, good find @miracle2k. The condition was shared because we also want to early return when it's `IGNORE` so `(!rangeBehavior && rangeBehavior !== IGNORE)` would probably not be what we want here.

PR coming for this!
