### ISSUE TITLE
Optimistic Response

### ISSUE THREAD

**Issue by ssbeefeater** [facebook/relay#1339]
Let's consider this relay container

```
class example extends React.Component {...}
example = Relay.createContainer(example, {
  initialVariables: {
    first: 25
  },
  fragments: {
    store: (d)=> {
      return Relay.QL`
     fragment on Store{
     id,
     exampleConnection(first:$first) {    
       edges {
          node {
             id,
             description(language:"en"){
               title
             }
          }
        }
       }
     }
    `
    }
  }
})

```

when try to make a mutation( with RANGE_ADD type) with an optimistic response the description object does not exist but everything else are normally set. 

```
getOptimisticResponse() {
    return {
      exampleEdge: {
        node: {
          id: 'testId',         
          description: {
            title: this.props.title
          }
        }
      },
      store: {
        id: this.props.store.id
      }
    }
  }
```

It seems that when there is an argument in the fragment, prevents the optimistic response to set the specific variable. Is there any solution for that?

**Comment by sibelius** [comment]
@ssbeefeater did u found any solution for this?

**Comment by caiosba** [comment]
It works if you define the `rangeBehaviors` of your `RANGE_ADD` config as a function, like this:

`rangeBehaviors: (calls) => { return 'prepend'; }`

**Comment by wincent** [comment]
(Spring cleaning.) I'm going through older issues looking for things that can be closed in order to reduce clutter. Looks like this one has a workaround noted above, so I'm going to close it. Thank you to everybody who participated!
