### ISSUE TITLE
Setting up a project

### ISSUE THREAD

**Issue by spyalert01** [facebook/relay#134]
Hi All, 
this question is not tech related.
I am trying to understand how the whole react-relay work so that I know how to structure the way I handle project.

Normally my practice is to ounderstand client requirement, then build wire-frame for agreement. After which will get Designer to draft some art work for the system. 
Then we will make Hardcoded in HTML to let customer click and check page by page. Only then finally we insert data and action to the html to make he whole thing work.

After reading the example, I somehow feel relay must come with Database and schema before component. 

My question is, can we make some hardcoded component to build up the look n feel of the system then only insert data?

With the current way, I really confuse, and don't know how to start.

Thanks.

**Comment by josephsavona** [comment]
> After reading the example, I somehow feel relay must come with Database and schema before component.

Relay does require that you implement a GraphQL server to provide data to the application. If you want to use Relay for a prototype, you might consider building a simple server that provides sample data. A good place to start with this approach is the [relay-starter-kit](https://github.com/facebook/relay-starter-kit).

However, it sounds like the easiest option is to start off by just building plain React components first, and only add a GraphQL server and Relay for data-fetching later on.

**Comment by josephsavona** [comment]
Feel free to reopen if you have additional questions.

**Comment by spyalert01** [comment]
@josephsavona  thanks
