### ISSUE TITLE
enum value, as part of a field param, is being wrapped in quotes which causes an error

### ISSUE THREAD

**Issue by ryancole** [facebook/relay#1340]
I've got a field that has a param which accepts an array of enum values. It's just a way to filter the data from that field. Here's the definition of that field, named `teamInvites` ...

```
type Account implements Node {
  id: ID!
  username: String!
  teamInvites(responses: [TeamInviteResponse] = [Pending, Accepted, Rejected]): [TeamInvite]
}
```

I've got a mutation that is using the `FIELDS_CHANGE` config and just doing a blanket change on the entire `Account`,  which is causing Relay to fetch all of this data. The query being sent by Relay has the `TeamInviteResponse` value inlined and wrapped in quotes, though. This is breaking the query because when inlined I believe GraphQL wants just the enum value. Here's that generated query by Relay ...

```
mutation CreateTeamMutation($input_0: CreateTeamInput!) {
  createTeam(input: $input_0) {
    clientMutationId
    ...F1
  }
}

fragment F0 on Account {
  id
  isMyAccount
  _teamInvites3tMcRS: teamInvites(responses: ["Pending"]) {
    id
    team {
      name
      slug
      game {
        name
        slug
        id
      }
      createdBy {
        slug
        username
        id
      }
      id
    }
    account {
      id
    }
  }
  slug
  username
}

fragment F1 on CreateTeamPayload {
  account {
    username
    dateCreated
    teamMemberships {
      id
      dateCreated
      team {
        id
        name
        slug
        game {
          name
          slug
          id
        }
      }
    }
    id
    ...F0
  }
}
```

**Comment by ryancole** [comment]
I'm actually not even sure why it's choosing to use `Pending` as the param there. I don't specify any param in the mutation's `getFatQuery`. Here's that function ...

```
  getFatQuery() {
    return Relay.QL`
      fragment on CreateTeamPayload {
        account
      }
    `;
  }
```

**Comment by ryancole** [comment]
I just noticed that the console.log debug information shows the tracked query and the intersected result. The `Pending` does indeed come from the tracked query, with the quotes around it.

So, perhaps this issue is that tracked query is storing this enum param with quotes?

**Comment by eugene1g** [comment]
I had a similar situation, and my takeaway was the same - if you inline `enum` values directly in the query Relay will always treat them as string literals (instead of enums). The only solution is to reference the value as a variable. So this does not work -
```
const Container = Relay.createContainer(SomeView, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Account {
          responseType(responses: "Pending") {
              id
              team {name slug }
          }
      }
  `
  }
})
```

And using it as a variable does work -
```
const Container = Relay.createContainer(SomeView, {
  initialVariables: {
    responseType: 'Pending'
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Account {
          responseType(responses: $responseType) {
              id
              team {name slug }
          }
      }
  `
  }
})
```

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

I believe this issue is fixed in Relay Modern.
