### ISSUE TITLE
Relay isn't loading properties from a fragment included for a list field.

### ISSUE THREAD

**Issue by jcampbell05** [facebook/relay#1341]
The example below fails to load the `name` property the `Application` component clearly defines in it's fragment which is pulled in by the `ApplicationList`. However if I directly declare it in the `ApplicationList` property it works fine.

Any ideas? 

```
import React from 'react';
import ReactDOM from 'react-dom';
import Relay from 'react-relay';

class Application extends React.Component {
  render() {
    console.log(JSON.stringify(this.props))
    var application = this.props.application
    return <li>{application.name}</li>
  }
}

Application = Relay.createContainer(Application, {
  fragments: {
    application: () => Relay.QL`
      fragment on Application {
        id,
        name
      }
    `,
  },
});

class ApplicationList extends React.Component {
  render() {
    console.log(JSON.stringify(this.props))
    var user = this.props.user
    var applications = user.applications
    return <ul>
    {applications.map(application => (
      <Application key={application.id} application={application} />
    ))}
    </ul>
  }
}

ApplicationList = Relay.createContainer(ApplicationList, {
  fragments: {
    user: () => Relay.QL`
      fragment on User {
        applications {
          id,
          ${Application.getFragment('application')}
        }
      }
    `,
  },
});

module.exports = ApplicationList;

```

**Comment by jardakotesovec** [comment]
Hi @jcampbell05 ,
code seems to be correct, could you try to make repro in [relay playground](https://facebook.github.io/relay/prototyping/playground.html#/) so its possible debug?

**Comment by jcampbell05** [comment]
@jardakotesovec 

It's really strange when running it on the [playground](https://facebook.github.io/relay/prototyping/playground.html#schema=%2F**%0A%20*%20Copyright%20(c)%202013-present%2C%20Facebook%2C%20Inc.%0A%20*%20All%20rights%20reserved.%0A%20*%0A%20*%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%20*%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%20*%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%20*%2F%0Avar%20graphql%20%3D%20require('graphql')%3B%0Avar%20relayql%20%3D%20require('graphql-relay')%3B%0A%0Aconst%20data%20%3D%20%7B%0A%20%20users%3A%20%7B%0A%20%20%20%201%3A%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22id%22%3A%20%221%22%2C%0A%20%20%20%20%20%20%22name%22%3A%20%22James%22%2C%0A%20%20%20%20%20%20%22applications%22%3A%20%5B%0A%20%20%20%20%20%20%20%201%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20%22applications%22%3A%20%7B%0A%20%20%20%201%3A%20%7B%0A%20%20%20%20%20%20%22id%22%3A%20%221%22%2C%0A%20%20%20%20%20%20%22name%22%3A%20%22EchoBot%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0Afunction%20getApplication(id)%20%7B%0A%20%20return%20data.applications%5Bid%5D%3B%0A%7D%0A%0A%2F%2F%20Define%20the%20Application%20type%20with%20two%20string%20fields%3A%20%60id%60%20and%20%60name%60.%0A%2F%2F%20The%20type%20of%20User%20is%20GraphQLObjectType%2C%20which%20has%20child%20fields%0A%2F%2F%20with%20their%20own%20types%20(in%20this%20case%2C%20GraphQLString).%0Avar%20Application%20%3D%20new%20graphql.GraphQLObjectType(%7B%0A%20%20name%3A%20'Application'%2C%0A%20%20fields%3A%20%7B%0A%20%20%20%20id%3A%20relayql.globalIdField('Application')%2C%0A%20%20%20%20name%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%2C%0A%20%20%7D%0A%7D)%3B%0A%0A%2F%2F%20Define%20the%20User%20type%20with%20two%20string%20fields%3A%20%60id%60%20and%20%60name%60.%0A%2F%2F%20The%20type%20of%20User%20is%20GraphQLObjectType%2C%20which%20has%20child%20fields%0A%2F%2F%20with%20their%20own%20types%20(in%20this%20case%2C%20GraphQLString).%0Avar%20User%20%3D%20new%20graphql.GraphQLObjectType(%7B%0A%20%20name%3A%20'User'%2C%0A%20%20fields%3A%20%7B%0A%20%20%20%20id%3A%20relayql.globalIdField('User')%2C%0A%20%20%20%20name%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%2C%0A%20%20%20%20applications%3A%20%7B%20type%3A%20new%20graphql.GraphQLList(Application)%2C%20resolve%3A%20function(user)%20%7B%0A%20%20%20%20%20%20return%20user.applications.map(function(id)%20%7B%0A%20%20%20%20%20%20%20%20return%20getApplication(id)%0A%20%20%20%20%20%20%7D)%0A%20%20%20%20%7D%7D%0A%20%20%7D%0A%7D)%3B%0A%0A%2F%2F%20Define%20the%20schema%20with%20one%20top-level%20field%2C%20%60user%60%2C%20that%0A%2F%2F%20takes%20an%20%60id%60%20argument%20and%20returns%20the%20User%20with%20that%20ID.%0A%2F%2F%20Note%20that%20the%20%60query%60%20is%20a%20GraphQLObjectType%2C%20just%20like%20User.%0A%2F%2F%20The%20%60user%60%20field%2C%20however%2C%20is%20a%20userType%2C%20which%20we%20defined%20above.%0Aconst%20Schema%20%3D%20new%20graphql.GraphQLSchema(%7B%0A%20%20query%3A%20new%20graphql.GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20%7B%0A%20%20%20%20%20%20user%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20User%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20%60args%60%20describes%20the%20arguments%20that%20the%20%60user%60%20query%20accepts%0A%20%20%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20The%20resolve%20function%20describes%20how%20to%20%22resolve%22%20or%20fulfill%0A%20%20%20%20%20%20%20%20%2F%2F%20the%20incoming%20query.%0A%20%20%20%20%20%20%20%20%2F%2F%20In%20this%20case%20we%20use%20the%20%60id%60%20argument%20from%20above%20as%20a%20key%0A%20%20%20%20%20%20%20%20%2F%2F%20to%20get%20the%20User%20from%20%60data%60%0A%20%20%20%20%20%20%20%20resolve%3A%20function%20(_%2C%20args)%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20data.users%5Bargs.id%5D%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20application%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20Application%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20%60args%60%20describes%20the%20arguments%20that%20the%20%60application%60%20query%20accepts%0A%20%20%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20The%20resolve%20function%20describes%20how%20to%20%22resolve%22%20or%20fulfill%0A%20%20%20%20%20%20%20%20%2F%2F%20the%20incoming%20query.%0A%20%20%20%20%20%20%20%20%2F%2F%20In%20this%20case%20we%20use%20the%20%60id%60%20argument%20from%20above%20as%20a%20key%0A%20%20%20%20%20%20%20%20%2F%2F%20to%20get%20the%20Application%20from%20%60data%60%0A%20%20%20%20%20%20%20%20resolve%3A%20function%20(_%2C%20args)%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20getApplication(args.id)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D)%0A%7D)%3B%0A%0Amodule.exports%20%3D%20Schema%0A%0A&source=%2F**%0A%20*%20Copyright%20(c)%202013-present%2C%20Facebook%2C%20Inc.%0A%20*%20All%20rights%20reserved.%0A%20*%0A%20*%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%20*%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%20*%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%20*%2F%0A%0Aclass%20Application%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20application%20%3D%20this.props.application%0A%20%20%20%20return%20%3Cli%3E%7Bapplication.name%7D%3C%2Fli%3E%0A%20%20%7D%0A%7D%0A%0AApplication%20%3D%20Relay.createContainer(Application%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20application%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Application%20%7B%0A%20%20%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0Aclass%20ApplicationList%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20user%20%3D%20this.props.user%0A%20%20%20%20var%20applications%20%3D%20user.applications%0A%20%20%20%20return%20%3Cul%3E%0A%20%20%20%20%7Bapplications.map(application%20%3D%3E%20(%0A%20%20%20%20%20%20%3CApplication%20key%3D%7Bapplication.id%7D%20application%3D%7Bapplication%7D%20%2F%3E%0A%20%20%20%20))%7D%0A%20%20%20%20%3C%2Ful%3E%0A%20%20%7D%0A%7D%0A%0AApplicationList%20%3D%20Relay.createContainer(ApplicationList%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20user%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20User%20%7B%0A%20%20%20%20%20%20%20%20applications%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20%20%20%20%20%24%7BApplication.getFragment('application')%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0Aclass%20Applications%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20user%20%3D%20this.props.user%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ch1%3EApplications%3C%2Fh1%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ca%20onClick%3D%7Bthis.handleClick.bind(this)%7D%3ENew%20%2B%3C%2Fa%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CApplicationList%20user%3D%7Buser%7D%2F%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%0A%20%20handleClick()%20%7B%0A%0A%20%20%7D%0A%7D%0A%0AApplications%20%3D%20Relay.createContainer(Applications%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20user%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20User%20%7B%0A%20%20%20%20%20%20%20%20%24%7BApplicationList.getFragment('user')%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0Aclass%20App%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20user%20%3D%20this.props.user%0A%20%20%20%20return%20%3CApplications%20user%3D%7Buser%7D%2F%3E%0A%20%20%7D%0A%7D%0A%0AApp%20%3D%20Relay.createContainer(App%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20user%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20User%20%7B%0A%20%20%20%20%20%20%20%20%24%7BApplications.getFragment('user')%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%20%20%0Aclass%20AppRoute%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'AppRoute'%3B%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20user%3A%20(Component)%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20Relay.QL%60query%20%7B%20user(id%3A%20%221%22)%20%7B%0A%20%20%20%20%20%20%20%20%24%7BComponent.getFragment('user')%7D%0A%20%20%20%20%20%20%7D%7D%60%0A%20%20%20%20%7D%2C%0A%20%20%7D%3B%0A%7D%0A%0A%0A%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20%20%20%20%20%20%20%20Component%3D%7BApp%7D%0A%20%20%20%20%20%20%20%20%20%20%20route%3D%7Bnew%20AppRoute()%7D%20%2F%3E%2C%0A%20%20mountBode%0A)%3B%0A%0A)

However if I don't use global IDs it throws an [error](https://facebook.github.io/relay/prototyping/playground.html#schema=%2F**%0A%20*%20Copyright%20(c)%202013-present%2C%20Facebook%2C%20Inc.%0A%20*%20All%20rights%20reserved.%0A%20*%0A%20*%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%20*%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%20*%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%20*%2F%0Avar%20graphql%20%3D%20require('graphql')%3B%0Avar%20relayql%20%3D%20require('graphql-relay')%3B%0A%0Aconst%20data%20%3D%20%7B%0A%20%20users%3A%20%7B%0A%20%20%20%201%3A%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22id%22%3A%20%221%22%2C%0A%20%20%20%20%20%20%22name%22%3A%20%22James%22%2C%0A%20%20%20%20%20%20%22applications%22%3A%20%5B%0A%20%20%20%20%20%20%20%201%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20%22applications%22%3A%20%7B%0A%20%20%20%201%3A%20%7B%0A%20%20%20%20%20%20%22id%22%3A%20%221%22%2C%0A%20%20%20%20%20%20%22name%22%3A%20%22EchoBot%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0Afunction%20getApplication(id)%20%7B%0A%20%20return%20data.applications%5Bid%5D%3B%0A%7D%0A%0A%2F%2F%20Define%20the%20Application%20type%20with%20two%20string%20fields%3A%20%60id%60%20and%20%60name%60.%0A%2F%2F%20The%20type%20of%20User%20is%20GraphQLObjectType%2C%20which%20has%20child%20fields%0A%2F%2F%20with%20their%20own%20types%20(in%20this%20case%2C%20GraphQLString).%0Avar%20Application%20%3D%20new%20graphql.GraphQLObjectType(%7B%0A%20%20name%3A%20'Application'%2C%0A%20%20fields%3A%20%7B%0A%20%20%20%20id%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%2C%0A%20%20%20%20name%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%2C%0A%20%20%7D%0A%7D)%3B%0A%0A%2F%2F%20Define%20the%20User%20type%20with%20two%20string%20fields%3A%20%60id%60%20and%20%60name%60.%0A%2F%2F%20The%20type%20of%20User%20is%20GraphQLObjectType%2C%20which%20has%20child%20fields%0A%2F%2F%20with%20their%20own%20types%20(in%20this%20case%2C%20GraphQLString).%0Avar%20User%20%3D%20new%20graphql.GraphQLObjectType(%7B%0A%20%20name%3A%20'User'%2C%0A%20%20fields%3A%20%7B%0A%20%20%20%20id%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%2C%0A%20%20%20%20name%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%2C%0A%20%20%20%20applications%3A%20%7B%20type%3A%20new%20graphql.GraphQLList(Application)%2C%20resolve%3A%20function(user)%20%7B%0A%20%20%20%20%20%20return%20user.applications.map(function(id)%20%7B%0A%20%20%20%20%20%20%20%20return%20getApplication(id)%0A%20%20%20%20%20%20%7D)%0A%20%20%20%20%7D%7D%0A%20%20%7D%0A%7D)%3B%0A%0A%2F%2F%20Define%20the%20schema%20with%20one%20top-level%20field%2C%20%60user%60%2C%20that%0A%2F%2F%20takes%20an%20%60id%60%20argument%20and%20returns%20the%20User%20with%20that%20ID.%0A%2F%2F%20Note%20that%20the%20%60query%60%20is%20a%20GraphQLObjectType%2C%20just%20like%20User.%0A%2F%2F%20The%20%60user%60%20field%2C%20however%2C%20is%20a%20userType%2C%20which%20we%20defined%20above.%0Aconst%20Schema%20%3D%20new%20graphql.GraphQLSchema(%7B%0A%20%20query%3A%20new%20graphql.GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20%7B%0A%20%20%20%20%20%20user%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20User%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20%60args%60%20describes%20the%20arguments%20that%20the%20%60user%60%20query%20accepts%0A%20%20%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20The%20resolve%20function%20describes%20how%20to%20%22resolve%22%20or%20fulfill%0A%20%20%20%20%20%20%20%20%2F%2F%20the%20incoming%20query.%0A%20%20%20%20%20%20%20%20%2F%2F%20In%20this%20case%20we%20use%20the%20%60id%60%20argument%20from%20above%20as%20a%20key%0A%20%20%20%20%20%20%20%20%2F%2F%20to%20get%20the%20User%20from%20%60data%60%0A%20%20%20%20%20%20%20%20resolve%3A%20function%20(_%2C%20args)%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20data.users%5Bargs.id%5D%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20application%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20Application%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20%60args%60%20describes%20the%20arguments%20that%20the%20%60application%60%20query%20accepts%0A%20%20%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%3A%20%7B%20type%3A%20graphql.GraphQLString%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20The%20resolve%20function%20describes%20how%20to%20%22resolve%22%20or%20fulfill%0A%20%20%20%20%20%20%20%20%2F%2F%20the%20incoming%20query.%0A%20%20%20%20%20%20%20%20%2F%2F%20In%20this%20case%20we%20use%20the%20%60id%60%20argument%20from%20above%20as%20a%20key%0A%20%20%20%20%20%20%20%20%2F%2F%20to%20get%20the%20Application%20from%20%60data%60%0A%20%20%20%20%20%20%20%20resolve%3A%20function%20(_%2C%20args)%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20getApplication(args.id)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D)%0A%7D)%3B%0A%0Amodule.exports%20%3D%20Schema%0A%0A&source=%2F**%0A%20*%20Copyright%20(c)%202013-present%2C%20Facebook%2C%20Inc.%0A%20*%20All%20rights%20reserved.%0A%20*%0A%20*%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%20*%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%20*%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%20*%2F%0A%0Aclass%20Application%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20application%20%3D%20this.props.application%0A%20%20%20%20return%20%3Cli%3E%7Bapplication.name%7D%3C%2Fli%3E%0A%20%20%7D%0A%7D%0A%0AApplication%20%3D%20Relay.createContainer(Application%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20application%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Application%20%7B%0A%20%20%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0Aclass%20ApplicationList%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20user%20%3D%20this.props.user%0A%20%20%20%20var%20applications%20%3D%20user.applications%0A%20%20%20%20return%20%3Cul%3E%0A%20%20%20%20%7Bapplications.map(application%20%3D%3E%20(%0A%20%20%20%20%20%20%3CApplication%20key%3D%7Bapplication.id%7D%20application%3D%7Bapplication%7D%20%2F%3E%0A%20%20%20%20))%7D%0A%20%20%20%20%3C%2Ful%3E%0A%20%20%7D%0A%7D%0A%0AApplicationList%20%3D%20Relay.createContainer(ApplicationList%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20user%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20User%20%7B%0A%20%20%20%20%20%20%20%20applications%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20%20%20%20%20%24%7BApplication.getFragment('application')%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0Aclass%20Applications%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20user%20%3D%20this.props.user%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ch1%3EApplications%3C%2Fh1%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ca%20onClick%3D%7Bthis.handleClick.bind(this)%7D%3ENew%20%2B%3C%2Fa%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CApplicationList%20user%3D%7Buser%7D%2F%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%0A%20%20handleClick()%20%7B%0A%0A%20%20%7D%0A%7D%0A%0AApplications%20%3D%20Relay.createContainer(Applications%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20user%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20User%20%7B%0A%20%20%20%20%20%20%20%20%24%7BApplicationList.getFragment('user')%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0Aclass%20App%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20user%20%3D%20this.props.user%0A%20%20%20%20return%20%3CApplications%20user%3D%7Buser%7D%2F%3E%0A%20%20%7D%0A%7D%0A%0AApp%20%3D%20Relay.createContainer(App%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20user%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20User%20%7B%0A%20%20%20%20%20%20%20%20%24%7BApplications.getFragment('user')%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%20%20%0Aclass%20AppRoute%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'AppRoute'%3B%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20user%3A%20(Component)%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20Relay.QL%60query%20%7B%20user(id%3A%20%221%22)%20%7B%0A%20%20%20%20%20%20%20%20%24%7BComponent.getFragment('user')%7D%0A%20%20%20%20%20%20%7D%7D%60%0A%20%20%20%20%7D%2C%0A%20%20%7D%3B%0A%7D%0A%0A%0A%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20%20%20%20%20%20%20%20Component%3D%7BApp%7D%0A%20%20%20%20%20%20%20%20%20%20%20route%3D%7Bnew%20AppRoute()%7D%20%2F%3E%2C%0A%20%20mountBode%0A)%3B%0A%0A)

I guess I need to adopt the Global IDs for Relay to work? I've discovered your blog about converting a REST API to GraphQL which was super helpful (please make this the introduction tutorial, it was the moment where GraphQL and Relay clicked for me)

**Comment by jardakotesovec** [comment]
@jcampbell05 I have not blogged about relay/graphql.... had to be someone else :-).

Yes, global ids are key [requirement](https://facebook.github.io/relay/docs/graphql-object-identification.html#content) from relay.

**Comment by jcampbell05** [comment]
@jardakotesovec Cool, the error on the playground was super helpful !
