### ISSUE TITLE
Can't clear cache for logout

### ISSUE THREAD

**Issue by andrewfader** [facebook/relay#1342]
I have a Relay app and I want to clear cache for a component that displays after logging in. I tried passing a currentRelay.store into my Relay.Router and implementing a currentRelay.reset() which sets that store to a new Relay.Environment, then calling that after logout. The cache is still stored for some reason. I also tried calling this.props.relay.forceFetch({}) and this.forceUpdate() in componentDidMount(). The only way I can get the cache to clear is by manually refreshing the page. I wonder if there's a bug in Relay.Environment or I'm doing it wrong.

**Comment by wincent** [comment]
Rendering with a brand new `Relay.Environment` should clear all internal state. We're not aware of any bugs (hidden state) that wouldn't get cleared; for example, the isomorphic-relay project is [using a new environment](https://github.com/denvned/isomorphic-relay/blob/b7fb72a15d750eed00b261b94f8730e05393a3f7/src/prepareData.js#L6) to perform clean-slate rendering for every request.

I'm going to close this as I don't think there is a bug here (happy to re-open if that is not the case), but I would suggest that you look at [`RelayRenderer`](https://github.com/facebook/relay/blob/b0d115dbd1b90d62a9aa9b20d0c8934d7328dd34/src/container/RelayRenderer.js) and how you can pass an `environment` prop to it. If you can't get to the bottom of your issue, would need to see some code to know more: I'd suggest posting a question on
