### ISSUE TITLE
Make REST to GraphQL with Relay the default tutorial

### ISSUE THREAD

**Issue by jcampbell05** [facebook/relay#1343]
It was this Blog post that finally got Relay and GraphQL into my head (along with some other docs)

Please make it the first tutorial http://graphql.org/blog/rest-api-graphql-wrapper/

If not I will be happy to contribute one :)

**Comment by wincent** [comment]
Thanks for the feedback, @jcampbell05, and sorry for taking so long to respond. We'd welcome PRs to improve out documentation, including improvements to the existing tutorial, or adding links to others such as the one that you mentioned. One thing to bear in mind: we're in the process of rolling out some new APIs and a new core (see ongoing activity on the `master` branch), so there may be some churn involved if you undertake documentation updates at this time; we're expecting to be publishing a fair bit of updated documentation over the coming weeks/months.

In the meantime, closing this to clean out the issue tracker a little bit.

**Comment by jcampbell05** [comment]
No worries 😀
