### ISSUE TITLE
Source code for the babel plugin

### ISSUE THREAD

**Issue by edvinerikson** [facebook/relay#1348]
It seems like the `scripts/babel-relay-plugin/src/` directory doesn't exist anymore and only a compiled version is available.
Is this intended? https://github.com/facebook/relay/tree/master/scripts/babel-relay-plugin

**Comment by kassens** [comment]
No, thanks for catching this. This was an oversight by re-organizing the internal code that got synced to github: 1976109901487189407c86b7c2fdf68e85523ad7

**Comment by kassens** [comment]
Restored with 6c72285a50bb8224359bb34add655fce19ea0666
