### ISSUE TITLE
Getting the corresponding query string for a class-defined Relay Mutation

### ISSUE THREAD

**Issue by elonybear** [facebook/relay#1349]
I'm finding myself in the situation where I would like to create a Relay Mutation as a class but then call the graphql function, passing in the corresponding query string of the Relay Mutation.  
For example, say I have this simple mutation: 

```
class TodoAddMutation extends Relay.Mutation {
  static fragments = {
    viewer: () => Relay.QL`
      fragment on Viewer {
        id,
      }
    `
  }

  getMutation () {
    return Relay.QL`{TodoAdd}`
  }

  getFatQuery () {
    return Relay.QL`
      fragment on TodoAddPayload {
        todoEdge,
        viewer {
          todos
        }
      }
    `
  }

  getConfigs () {
    return [{
      type: 'RANGE_ADD',
      parentName: 'viewer',
      parentID: this.props.viewer.id
      connectionName: 'todos',
      edgeName: 'writeboardEdge,
      rangeBehaviors: (calls) => {
        return 'append';
      } 
    }]
  }

  getVariables () {
    return {} //These could potentially be the actual new values or the filters of the Todo App.
  }
}
```

At the moment, I can't seem to find a way to get the associated printed query string for this mutation. Normally, by calling commitUpdate, passing in a new instance of this mutation, a query string would be sent in the request. I've explored the relay source code but there does not seem to be a publicly accessible function to manually get the printed query of the mutation.

I'm thinking the functionality would look similar to this:

```
let TodoAddMutation = new TodoAddMutation();

graphql(
  Schema,
  TodoAddMutation.getPrintedString(),
  publication_data, //Potentially the data from a publication and this client is a subscriber
  TodoAddMutation.getVariables()
)
```

I think this would be a nice feature because one can define a generic mutation and then use the graphql function to actually send the request. One example in particular where this would be useful is with publications and subscriptions. The client creates an instance of a 'subscription' mutation, which will be dispatched through the graphql function when it is needed.
Is this functionality a possible future addition to Relay?

**Comment by josephsavona** [comment]
I'm not sure I understand the use case. Is this a mutation or a (real-time) subscription? Wouldn't both of these use cases require calling the graphql function on the server? If you're running the schema on the client, perhaps you could use relay-local-schema? (Npm module)

**Comment by elonybear** [comment]
I apologize for the confusion. This would be a real-time subscription, implemented as a mutation to the subscriber's Relay Store. 

Each client connecting to the server would have a set of subscriptions, based on their circumstances (user or administrator, datasets they're looking at, etc.). Drawing from the todo example, let's say all clients subscribe to any additions to the list of todos. When each client connects to the server, they would emit (a potential use of sockets) this AddTodo subscription to the server, which would be stored by the server, perhaps associated with a unique ID so as to pick and choose which clients to update. In my mind, this subscription would be implemented as the Mutation class already defined by Relay. 

Then, if a particular client adds a todo, the desired behavior is that one could invoke a getPrintedQuery function (or the like) and getVariables function for each AddTodo subscription. With this printed query and variables, one can then call the graphql function for each client, updating their Stores as necessary. The 'rootValue' would be the data of the new todo. The variables could be things like permission access level or filters on the list of todos. However, as of now, it doesn't seem like a getPrintedQuery function exists publicly for any Relay Mutation instance.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

If this issue is still important to you, please feel free to reopen it with an update.
