### ISSUE TITLE
How can I pass props into class Mutation static prepareVariables method

### ISSUE THREAD

**Issue by transedward** [facebook/relay#135]
As mentioned in title, If I wanna do pagination like here
https://github.com/transedward/relay-chat/blob/add-pagination/js/components/MessageSection.js#L60
I use `this.props.relay.setVariables` to add number by 1 when I click Load More
But I also have a AddMessageMutation, if I didn't change `fragments` and `getFatQuery` then 
the new added message won't be counted in `last: $number`, which caused the loaded message disappeared by one.
What I wanna is pass a number here https://github.com/transedward/relay-chat/blob/add-pagination/js/components/MessageComposer.js#L49
So AddMessageMutation would how much messages currently there is, then I wanna add it by one
when adding new message
But since `prepareVariables` is a static method for AddMessageMutation, I can't pass props into it.
Is there any way I can fix that?

**Comment by josephsavona** [comment]
#146 seems related - cc @steveluscher

**Comment by transedward** [comment]
to be more specific, 
I don't think it's related with #146
I have done with the [Load more](https://github.com/transedward/relay-chat/blob/add-pagination/js/components/MessageSection.js#L37) and it works as expected as like in fb messenger
it would load more when you hit load more(or scroll position in reality) as long as you didn't type new message
You can easily using `this.props.relay.setVariable` in component [as show here](https://github.com/transedward/relay-chat/blob/add-pagination/js/components/MessageSection.js#L60)

But you can't do that with `Relay.Mutation` Because `initialVariables` and `prepareVariables ` is at `static` level, you can't pass anything to that, so you can't influence `variables` in [`fragments`](https://github.com/transedward/relay-chat/blob/add-pagination/js/mutations/AddMessageMutation.js#L6)
I am not sure if that is a purpose design. If so, how do you solve the issue about `mutation cause a variable in fragments changed`
If I don't handle that, `AddMessageMutation` would cause new message attached in `MessageSection` but the total number to be shown is the same, so the top message would disappear accordingly.

**Comment by steveluscher** [comment]
I think I understand what you're trying to do here. Perhaps the right thing to do is to delegate back to the parent when you know that a message has been created. By then, your optimistic mutation will have been applied, so the parent can increment the counter to accommodate it.

```javascript
// MessageComposer
_onKeyDown = (event) => {
  /* ... */
  Relay.Store.update(new AddMessageMutation(
    {/*... */},
    {onFailure: () => this.props.onMessageCreationRollback()}
  );
  this.props.onMessageCreated();
  /* ... */
}
```

```javascript
// MessageSection
_handleMessageCreated() {
  this.props.relay.setVariables({
    number: this.props.relay.variables.number + 1,
  });
}
_handleMessageCreationRollback() {
 this.props.relay.setVariables({
    number: this.props.relay.variables.number - 1,
  });
}
render() {
  return (
    <MessageComposer 
      onMessageCreated={this._handleMessageCreated} 
      onMessageCreationRollback={this._handleMessageCreationRollback} 
    />
  );
}

```

**Comment by transedward** [comment]
Thanks @steveluscher 
But in my opinion, I'm sure this is "good enough" for an ideal API
In Relay doc, it's encouraged to put all relevant and influenced field in `Mutation getConfig` 
And in this case, it's the `AddMessageMutation` cause the field the variable change,
but the handler in on upper component, which I think it's a little bit suboptimal
Why not let `variables` in `Mutation` being a instance method and let `Mutation input` named something else like `getInputs`
If you think this is worth discussion, I will close this one and open another issue.
If not, you can close this issue since my original question is solved

**Comment by steveluscher** [comment]
I think we need to consider ‘variables’ and ‘fields’ separately.

It's true that you should declare any required fields in a mutation to guarantee that they get rolled up into the root query. This way, you can be sure that whatever data you need to perform the mutation and generate the optimistic response will have been fetched when you need it.

Variables on the other hand, I'm not sure. I'm going to stick with the recommendation above for now. If you end up coming up with something that you think works better, and in general, feel free to bring it up, or send us a PR.

Thanks!
