### ISSUE TITLE
BabelRelayPlugin: metadata.isConnection strange behavior

### ISSUE THREAD

**Issue by dherault** [facebook/relay#1350]
Hi,

in `RelayQLPrinter.js` on the `printField` method you have this code:
```javascript
if (fieldType.isConnection()) {
  if (field.hasDeclaredArgument('first') || field.hasDeclaredArgument('last')) {
    if (!isGeneratedQuery) {
      validateConnectionField(field);
    }
    metadata.isConnection = true;
    if (field.hasDeclaredArgument('find')) {
      metadata.isFindable = true;
    }
  }
}
```

Concretely, this means that for a RelayQueryNode instance to have  `metadata.isConnection === true`, being a connection is not enough, it must have a connection arg too. What about connections without connectionArgs? They exist too, but can't harvest to power off `RANGE_ADD` or whatever because they are not recognized by Relay as connections.

What about this fix?

```javascript
if (fieldType.isConnection()) {
  metadata.isConnection = true;
  if (field.hasDeclaredArgument('first') || field.hasDeclaredArgument('last')) {
    if (!isGeneratedQuery) {
      validateConnectionField(field);
    }
    if (field.hasDeclaredArgument('find')) {
      metadata.isFindable = true;
    }
  }
}
```

Best,

**Comment by dherault** [comment]
I'm closing this because I thought connection args where mandatory (where they at some point?) on a query. Adding them to the field and not using them does the trick. 
Best,

**Comment by josephsavona** [comment]
Thanks for asking about this. The intention of the code (overall, not just the snippet you mentioned) is that if you are fetching `edges` that you must specify a first/last filter call to limit the number of items fetched. If you aren't fetching edges, then you don't need a first/last argument.
