### ISSUE TITLE
printRelayOSSQuery inlining the values of scalar variables

### ISSUE THREAD

**Issue by samn** [facebook/relay#1353]
We recently ran into an problem where Relay was generating invalid GraphQL queries. A query variable had a value with a character (`"\u0013"`) that's [invalid](https://github.com/graphql/graphql-js/pull/186/files#diff-6908a1174c4e9de36b7e8998c5db713aR360) in the GraphQL spec. We expected that this would be fine, since this character (and other similar characters) are valid in JSON, and variables are encoded in JSON and sent separately from the query.

However, even though this value was in a variable it still ended up as part of the printed query. Only variables with Object and Enum types, and the identifying arg got sent as variables, the rest (variables with scalar types) were substituted directly into the printed query.

e.g. a query:

```
query Example($name: String!) {
  Account(name: $name) {
    id
  }
}
```

With variables: `{"name": "user input \u0013"}`
Got transformed into

```
query Example {
  Account(name: "user input \u0013") {
    id
  }
}
```

Which is an invalid query.

Digging through `printRelayOSSQuery` I found that `Relay.QL` doesn't doesn't add type metadata for scalar arguments (see [printArgumentTypeForMetadata](https://github.com/facebook/relay/blob/master/scripts/babel-relay-plugin/src/RelayQLPrinter.js#L687-L701)), which causes [printArgument](https://github.com/facebook/relay/blob/master/src/traversal/printRelayOSSQuery.js#L306-L323) (in printRelayOSSQuery.js) to substitute the value of the variable in directly, instead of treating it as a variable.

Can you explain why the values of scalar variables (and wrapped scalars, e.g. `String!` or `[String]`) are substituted into queries, instead of getting sent separately as variables?
Would you be interested in a PR changing this behavior, or making it configurable?

Thanks!

**Comment by josephsavona** [comment]
Hmm. It seems like that query should be valid, and that GraphQL should accept common syntax for representing Unicode values. 

In Relay 2 - #1396 - this problem will go away, though: only values that you inline in the GraphQL text will be printed inline. Variables will always be sent as variables (simple, predictable). 

For current Relay it all boils down to perf - if we can generate more variables and it doesn't affect performance then we can make that change. If it affects perf, we may need to use a workaround until Relay 2. I'd suggest sending a PR with just the minimal changes to print strings as variables instead of inlining. Don't worry about tests or Flow - just get it working and send a PR, and we can benchmark it and go from there.

**Comment by samn** [comment]
Thanks for the context @josephsavona! I'll put together a PR to facilitate benchmarking.

**Comment by jsdnxx** [comment]
@josephsavona I'm interested in this also: I want to be able to cache validated queries on the server side, which we can do easily if all of the variables are properly extracted.

I am able to get the non-inlined behavior by changing the https://github.com/facebook/relay/blob/master/scripts/babel-relay-plugin/src/RelayQLPrinter.js#L687-L701 method that @samn pointed out.

Are there benchmarks in the open source repo that I could run during development? Or is the best workflow just to open a PR and wait for a response from the team?

**Comment by josephsavona** [comment]
We don't have benchmarks in the repo for this, we are currently testing in a device lab. If you send a PR we can try to benchmark as time permits. That said, we're primarily focused on developing the next version of Relay, where this will hopefully be a non-issue.

**Comment by wincent** [comment]
As the new Relay core and APIs are currently being rolled out (see activity on the `master` branch, and watch it for more pieces landing in the coming weeks/months), I don't think we're going to take any further action on this one. We're aggressively prioritizing rolling out the new core/APIs over working on the legacy ones.

Thanks for bringing this up, however. We appreciate your input!
