### ISSUE TITLE
Relay 0.9.3 Release

### ISSUE THREAD

**Issue by cancan101** [facebook/relay#1355]
What is the timeline for a 0.9.3 release with: https://github.com/facebook/relay/commit/dcc97a431af719b71b62506ce8fe29b85158ef3e included?

**Comment by wincent** [comment]
@cancan101, I am planning on cutting a release this week. I'll update this issue if anything unexpected comes up that would delay it.

**Comment by nikgraf** [comment]
awesome, just noticed you published the latest version of relay, but `babel-relay-plugin` is still on 0.9.2

**Comment by wincent** [comment]
I think there is something fishy with NPM. I can't see it on [the releases page](https://www.npmjs.com/package/babel-relay-plugin), but I definitely ran `npm publish`. If I try to run it again, in fact, I get this:

```
npm ERR! "You cannot publish over the previously published version 0.9.3." : babel-relay-plugin
```

I might have to bump the version number and republish.

ಠ_ಠ

**Comment by kassens** [comment]
`npm install babel-relay-plugin` in an empty directory installs 0.9.3 for me and `npm view babel-relay-plugin` also shows 0.9.3 as the latest release. Looks like the npmjs website just has a caching issue?

**Comment by wincent** [comment]
Ok, I think I might have overreacted here because the listing on npmjs.com is busted. The package actually *is* published. The reason you are seeing that message @nikgraf is because babel-relay-plugin is a peer-dependency. Under NPM 3, you have to supply it yourself.

```
/tmp$ mkdir demo                                                                                           0.02s /tmp
/tmp$ cd demo                                                                                              0.01s /tmp
.  ..
demo$ npm init                                                                                        0.01s /tmp/demo
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (demo)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to /private/tmp/demo/package.json:

{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes)
demo$ npm install --save react-relay babel-relay-plugin react                                         3.63s /tmp/demo
demo@1.0.0 /private/tmp/demo
├─┬ babel-relay-plugin@0.9.3
│ └─┬ graphql@0.6.2
│   └── iterall@1.0.2
├─┬ react@15.3.1
│ ├─┬ fbjs@0.8.4
│ │ ├── core-js@1.2.7
│ │ ├── immutable@3.8.1
│ │ ├─┬ isomorphic-fetch@2.2.1
│ │ │ ├─┬ node-fetch@1.6.0
│ │ │ │ ├─┬ encoding@0.1.12
│ │ │ │ │ └── iconv-lite@0.4.13
│ │ │ │ └── is-stream@1.1.0
│ │ │ └── whatwg-fetch@1.0.0
│ │ ├─┬ promise@7.1.1
│ │ │ └── asap@2.0.4
│ │ └── ua-parser-js@0.7.10
│ ├─┬ loose-envify@1.2.0
│ │ └── js-tokens@1.0.3
│ └── object-assign@4.1.0
└─┬ react-relay@0.9.3
  ├─┬ babel-runtime@6.11.6
  │ ├── core-js@2.4.1
  │ └── regenerator-runtime@0.9.5
  └── react-static-container@1.0.1

npm WARN demo@1.0.0 No description
npm WARN demo@1.0.0 No repository field.
demo$ cat package.json                                                                                5.82s /tmp/demo
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-relay-plugin": "0.9.3",
    "react": "15.3.1",
    "react-relay": "0.9.3"
  }
}
```

The fact that the listing on the webside has failed to update after over 12 hours is a separate issue that threw me off, and which I unfortunately don't think is likely to resolve itself until we publish a new version, but I don't think it is worth it.

**Comment by nikgraf** [comment]
Thanks for taking care of it!

Quite interesting. The website still shows me that 0.9.2 is the last uploaded version while `npm view babel-relay-plugin versions` shows the right results. Might be a caching issues …

```
npm view babel-relay-plugin versions 
 
[ '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.2.0',
  '0.2.1',
  '0.2.2',
  '0.2.3',
  '0.2.4',
  '0.2.5',
  '0.2.6',
  '0.3.0',
  '0.4.0',
  '0.4.1',
  '0.6.0',
  '0.6.1',
  '0.6.3',
  '0.7.0-rc.2',
  '0.7.0',
  '0.7.1',
  '0.7.2',
  '0.7.3',
  '0.8.0',
  '0.8.1',
  '0.9.0',
  '0.9.1',
  '0.9.2',
  '0.9.3' ]
```

![screen shot 2016-09-05 at 11 10 13](https://cloud.githubusercontent.com/assets/223045/18243055/892e8c66-7359-11e6-8f0e-bea1414bfb8f.png)
