### ISSUE TITLE
RelayContainer.prototype.shouldComponentUpdate returning false incorrectly when using 'getFragment' in the query

### ISSUE THREAD

**Issue by mpretty-homepass** [facebook/relay#1356]
The easiest way to explain the issue is with our use case. We have matchMedia breakpoints in our site which are stored in context, when the screen site changes enough to swap between breakpoints the change isn't getting to all children correctly.

I seem to be able to reproduce the issue using the web todo example here https://github.com/relayjs/relay-examples with the following changes:

Add to the top of TodoApp.js
```
  static childContextTypes = {
    breakpoint: React.PropTypes.string
  };
  state = {
    breakpoint: 'desktop'
  };
  getChildContext() {
    return {
      breakpoint: this.state.breakpoint
    }
  }
  componentDidMount() {
    const breakpoints = {
      phone: 'only screen and (min-width: 320px) and (max-width: 480px)',
      tablet: 'only screen and (min-width: 768px) and (max-width: 1024px)',
      desktop: 'only screen and (min-width: 1224px)'
    };
    Object.keys(breakpoints).map(key => {
      matchMedia(breakpoints[key]).addListener((mql) => {
        if (mql.matches) {
          this.setState({ breakpoint: key });
        }
      });
    });
  }
  shouldComponentUpdate() {
    console.log('TodoApp - shouldComponentUpdate:', this.state.breakpoint);
    return true;
  }
```

Add to the top of TodoListFooter.js
```
  static contextTypes = {
    breakpoint: React.PropTypes.string
  }
  shouldComponentUpdate() {
    console.log('TodoListFooter - shouldComponentUpdate:', this.context.breakpoint);
    return true;
  }
```

If you change the screen size to be small enough you should see the log 'TodoApp - shouldComponentUpdate: desktop' in the console. but the TodoListFooter's 'shouldComponentUpdate' method won't be called.

Now, if you remove the query from TodoListFooter.js (swap the 'createContainer' block with the following):
```
export default Relay.createContainer(TodoListFooter, {
  fragments: {
  },
});
```

And update the query in TodoApp.js to be:
```
export default Relay.createContainer(TodoApp, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        totalCount,
        ${AddTodoMutation.getFragment('viewer')},
      }
    `,
  },
});
```

Then reload the page; changing the size of the website should now log 'TodoApp - shouldComponentUpdate: desktop' and 'TodoListFooter - shouldComponentUpdate: desktop' in the console.

I took a look around and it seems like RelayContainer.prototype.shouldComponentUpdate is returning false (it makes it to the final return statement). Not sure how to go about solving the issue in Relay though.

**Comment by josephsavona** [comment]
Thanks for filing an issue. The culprit here is the use of React context. Relay tries to avoid updates to components whose props and fragment data have not changed by implementing a conservative shouldComponentUpdate. Relay can't check every possible contest key, though. If you have no other way to do something than React context, there is an escape hatch: set `shouldComponentUpdate: () => true` In your container definition. 

See also the API docs: https://facebook.github.io/relay/docs/api-reference-relay-container.html#shouldcomponentupdate

**Comment by mpretty-homepass** [comment]
Yea, we figured that's what it was. We didn't actually work though a proper solution before I raised the issue. But yes, unfortunately we would probably need to somehow generate a 'context tree' based on all of the contextTypes of the children. Which seems complex and painful. Thanks for the response though, will have to keep that in mind in the future.

**Comment by mpretty-homepass** [comment]
And didn't see that it was in the docs, will close the issue.
