### ISSUE TITLE
[Renderer] render gets passed null props

### ISSUE THREAD

**Issue by ssomnoremac** [facebook/relay#1358]
I'm getting strange behavior for Renderer. I have another view where this is working. But if I do this

    <Relay.Renderer
                Container={ myContainer }
                queryConfig={ new ViewerRoute() }
                environment={Relay.Store}
                render={({props}) => {
                    return (
                        <CreateProfile_2_Container {...props} passedProps={this.props} />
                    );
                }}

The relay props are `null`. But if I leave off the `render` completely, the relay props are passed fine.

**Comment by nodkz** [comment]
```js
render={({props}) => {
// Change to
render={(props) => {
```

**Comment by ssomnoremac** [comment]
{props} destructures props from this:
    Object {done: false, error: null, events: Array[0], props: null, stale: false…}

**Comment by nodkz** [comment]
Think that was simple typo.
Read this comments https://github.com/facebook/relay/blob/master/src/container/RelayRenderer.js#L88 may be help to find solution.

PS. I'm never use Relay.Renderer directly. Always via https://github.com/relay-tools/react-router-relay

**Comment by ssomnoremac** [comment]
I will leave the answer here in case anyone needs it after I close. Relay will pass `null` for props until it receives the data so If your view is expecting it you have to provide a default.

**Comment by wincent** [comment]
Thanks for following up, @ssomnoremac!
