### ISSUE TITLE
debugging errors 

### ISSUE THREAD

**Issue by andyfenelon** [facebook/relay#1371]
i have the scenario where i have an error somewhere 
- schema valid
- app loads working fine (no problems)
- running on 8080/graphql
- **Problem:** when i call either this.props.relay.forceFetch( .. or this.props.relay.setVariables({...
i get the errors

> app.js:50387 POST http://localhost:3000/graphql 400 (Bad Request)
> app.js:9379 Warning: fetchWithRetries: HTTP error, retrying.

i did a bit of refactoring and i've somehow introduced a bug somewhere, is there any way to debug further ? as this seems very little to work with? 
i've tried setting up server error handling not getting any output as the error seems to be at the top level of the server request.
```
  graphQLApp.use('/', graphQLHTTP({
    graphiql: true,
    pretty: true,
    schema: Schema,
    context: {
      id: '10153554395631920',
    },
    formatError: error => ({
      message: error.message,
      locations: error.locations,
      stack: error.stack
    })
  })); 
```

**Comment by josephsavona** [comment]
@andyfenelon were you able to resolve this? what was the issue, and what helped resolve it?

**Comment by andyfenelon** [comment]
yes and no. i basically had to rebuild it bit by bit until i could isolate what it was breaking it. i think it was sharing a Type across fragments whilst trying to refresh the data on one of them.

the main problem i find i'm coming up against is when there's an error on the server the client just spits back a 400 (Bad Request), in particular with mutations, and there's very little to establish what the error actually is ? i've tried the express formatError but it doesn't seem to help with bad requests just more server internals. 

would welcome more support with debugging. 
Thanks.
