### ISSUE TITLE
Variable modification in getFragment interpolation?

### ISSUE THREAD

**Issue by LukePammant** [facebook/relay#1373]
I'm trying to accomplish a similar recursive data problem as [246](https://github.com/facebook/relay/issues/246). I have a `CommentList` component that has a list of `Comment` components. Each `Comment` has a `CommentList` thus forming the recursion. I am trying to have the comments automatically expand to a depth of 5 but I'm getting the following error: 

`RelayContainer: component 'Comment' was rendered with variables that differ from the variables used to fetch fragment 'comment'. The fragment was fetched with variables '{"expand":false}', but rendered with variables '{"expand":true}'.`

Is this because the it doesn't support performing operations like `currentDepth + 1` on the variables in the string interpolation?

Comment Component
----------------------
I have something like this in my `Comment` container:
`${CommentList.getFragment('comment', { currentDepth: currentDepth + 1 }).if(expand)}`

and render the `CommentList` component like:
`<CommentList
                    comment={comment}
                    currentDepth={this.props.relay.fragments.currentDepth + 1}
                    />`

CommentList Component
-------------------------
And in my `CommentList` component I have:
`${Comment.getFragment('comment', {expand: currentDepth < limit, currentDepth})}`

and render the `Comment` component like so: 
`<Comment key={comment.id}
                comment={comment}
                expand={this.props.relay.variables.currentDepth < this.props.relay.variables.limit}
                currentDepth={this.props.relay.variables.currentDepth} />`

**Comment by josephsavona** [comment]
> Is this because the it doesn't support performing operations like currentDepth + 1 on the variables in the string interpolation?

Quite possibly. Relay only evaluates each fragment once, so doing `${depth + 1}` inside a query probably won't do what you expect. If you need to dynamically modify variables, take a look at [`prepareVariables`](https://facebook.github.io/relay/docs/api-reference-relay-container.html#preparevariables)

**Comment by LukePammant** [comment]
Ah thank you, that did indeed fix my problem.
