### ISSUE TITLE
Invariant: "Relay only supports directives with scalar values"

### ISSUE THREAD

**Issue by jimkyndemeyer** [facebook/relay#1374]
One of the most frequent query patterns we're seeing in our Relay components is as follows:

``` graphql
fragment on Foo {
  someField(input: $myInputObject) @include(if: $myInputObject) {
    # sub selections
  }
}
```

In most of our components `$myInputObject` is an input object and not a scalar, which then causes an invariant to throw in [printDirective](https://github.com/facebook/relay/blob/081b4a3f17dcf37419155317ed97ca5e5ac97522/src/traversal/printRelayOSSQuery.js#L298)

This limitation looks very deliberate (there's even a test case that enforces it), so I'm guessing there might be a very good reason for it.

The behaviour we were hoping for was that the query printer would coerce the `if` directive argument into a boolean based on its knowledge of the schema.

Without this boolean coercion, the above example only works with the introduction of an additional query variable, e.g.:

``` graphql
fragment on Foo {
  someField(input: $myInputObject) @include(if: $myInputObjectCoercedToBoolean) {
    # sub selections
  }
}
```

This extra variable means that we need additional boilerplate. First, we need to include the new variable in `initialVariables`, and secondly, we have to do a manual coercion with the introduction of a `prepareVariables`method, which we could otherwise do without.

What do you guys think about loosening this restriction and adding boolean coercion?

**Comment by josephsavona** [comment]
Thanks for your question. There are actually two aspects to this issue:
- Allowing non-booleans values for `@include`/ `@skip`
- The restriction to scalar values on directives

For the former, I understand that coercion would be convenient. However, the [GraphQL specification](http://facebook.github.io/graphql/#sec-Boolean) specifically does not allow non-booleans to be coerced when a boolean is expected (I double checked this in graphiql too). So even if we changed `printDirective` to support complex values, the `@include(if: $myInputObject)` example above would be rejected by a spec-compliant server. This is definitely something to keep in mind, as this certainly is a common pattern. In the short-term the simplest solution is to use the additional boolean variable, but we're open to suggestions about how to make this work while conforming to the spec (or, alternately, proposing a spec change). 

Re printing non-scalar directive values - this will be supported in Relay 2 (#1369), and we're happy to explore adding support in current Relay if necessary. It doesn't seem like it would help in this case though.

Again, we're open to suggestions about how to make the boolean coercion more ergonomic!

**Comment by jimkyndemeyer** [comment]
Thanks for the quick response and this project as a whole. Really looking forward to Relay 2 :)

Regarding the first point of spec compliance, the initial idea that came into my mind was to let the relay query printer do the coercion, such that the value is sent over the wire as `true` or `false`. That takes care of compliance, and isn't unexpected given that Relay already supports processing of the variables with `prepareVariables`.

There is no contextual information about the schema in the current [printDirective implementation](https://github.com/facebook/relay/blob/081b4a3f17dcf37419155317ed97ca5e5ac97522/src/traversal/printRelayOSSQuery.js#L293), but the genereal idea is along the lines of:

```javascript
function printDirective({name, value}, schemaType/* TODO: get from the client schema */) {
  // coerce value to boolean if the schema expects a boolean
  if(schemaType === 'Boolean' && typeof value !== 'boolean') {    
    value = new Boolean(value).valueOf();
  }
  // rest of impl is unchanged
  invariant(
    typeof value === 'boolean' ||
    typeof value === 'number' ||
    typeof value === 'string',
    'printRelayOSSQuery(): Relay only supports directives with scalar values ' +
    '(boolean, number, or string), got `%s: %s`.',
    name,
    value
  );
  return name + ':' + JSON.stringify(value);
}
```

Any thoughts on the viability of this approach? I'm only slightly familiar with parts of the code at this point :)

**Comment by kassens** [comment]
Closing this as it refers to classic where we don't expect to do any major updates, please re-open if this still applies to the modern compiler.
