### ISSUE TITLE
Optimistic response and server response different?

### ISSUE THREAD

**Issue by Globegitter** [facebook/relay#1378]
In our app we have a list of payments and when you click into one you can cancel it (with a specific `CancelPaymentMutation`). So we want to do two things, update the status to cancelled but also `RANGE_DELETE` it from one of the lists.

Ideally I would have the optimistic response do the `FIELDS_CHANGE` as well as the `RANGE_DELETE` and to have some way to not respond anything from the server, because we know that the mutation was succesful if the server does not respond any errors so we do not have to send anything back. If it does respond with errors the optimistic response should just be rolled back as normal.

Even if this is not possible with Relay 1, would that use case be possible with Relay 2? Or is that also something that goes against a mutation convention? Should it always return what it modifies?

**Comment by josephsavona** [comment]
Hmm. This isn't supported out of the box today, you'd have to do some hacking using semi-public APIs to achieve it. 

With Relay2 it would be simple - you could use the same updater function as both the optimistic and server callback.

**Comment by Globegitter** [comment]
@josephsavona Thank you for the quick response. If it is possible with Relay2 than I am happy to wait and just work around it for now :).
