### ISSUE TITLE
Field aliases coming up with NaN

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#138]
On master, I'm seeing field aliases that look like `_0NaN`. Seems to be due to https://github.com/facebook/relay/blob/master/package.json#L31 being used over the one in fbjs.

Not quite sure which one we _want_ to be using, but the crc32 on npm returns a base16 string :smile: 

@yungsters @yuzhi

**Comment by yuzhi** [comment]
Thanks for bringing this up. I thought I removed those lines in https://github.com/facebook/relay/pull/122/

Will investigate!

**Comment by devknoll** [comment]
Oops, you're right. Looks like it may have just been a botched merge then :smile:

**Comment by yuzhi** [comment]
merged it again here https://github.com/facebook/relay/pull/142

**Comment by devknoll** [comment]
Thanks :)
