### ISSUE TITLE
Allow DefaultNetworkLayer to use simple CORS?

### ISSUE THREAD

**Issue by jakepusateri** [facebook/relay#1385]
It would be nice to allow DefaultNetworkLayer to use simple CORS so no pre-flight OPTIONS request is required when the GraphQL server is not on the same domain. (graphql.example.com vs www.example.com/graphql). However, the use of 

    content-type:application/json

make the request unable to use simple cors.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
```
The only allowed values for the Content-Type header are:
    application/x-www-form-urlencoded
    multipart/form-data
    text/plain
```

'text/plain' is arguably the least wrong of the options. 
I tried to set the content-type header myself 

    const networkLayer = new Relay.DefaultNetworkLayer(server, { headers: { 'Content-Type': 'text/plain' }});

but that appears to be explicitly blocked: https://github.com/facebook/relay/blob/dcc97a431af719b71b62506ce8fe29b85158ef3e/src/network-layer/default/__tests__/RelayDefaultNetworkLayer-test.js#L58

Why can that header not be set? Is there another way to make sure the request is simple CORS?

**Comment by nikolal** [comment]
I have the same issue. Is there any solution to this?

**Comment by josephsavona** [comment]
As a workaround, I would recommend implementing your own network layer.

**Comment by yutin1987** [comment]
I can not setting `'content-type': 'application/graphql'`.
but need it on `express-graphql`
https://github.com/graphql/express-graphql/blob/master/src/__tests__/http-test.js#L780

**Comment by josephsavona** [comment]
I'm going to close this; we recommend crating your own network layer, the default one is a good point to start from.
