### ISSUE TITLE
Send metadata in every query and mutation

### ISSUE THREAD

**Issue by sibelius** [facebook/relay#1387]
I would like to send some metadata in every query and mutation to my graphql server

is there any Relay/GraphQL way of handling this? or should I just add this info on http headers?

**Comment by unirey** [comment]
```jsx

const data = /* Get data from storage, store etc */

environment.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://example.com/graphql', {
    headers: {
      meta: data
    }
  })
)
```

This is how I do it. Every other possible way I could think of requires heavy schema, query and mutation modifications. You could do that and pass metadata as an argument but it's not worth it in my opinion. 

Especially if it's something global and/or you add it to `context` like locale or JWT token for example.

**Comment by unirey** [comment]
```jsx

const data = /* Get data from storage, store etc */

environment.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://example.com/graphql', {
    headers: {
      meta: data
    }
  })
)
```

This is how I do it. Every other way would require too many schema, query, mutation modifications IMO. This way you can be sure that metadata is included with every request and is ready to be used on server-side.

This is especially useful if it's something "global" and/or you add it to `context`, _e.g_ locale or JWT token.

**Comment by sibelius** [comment]
Tks this works
