### ISSUE TITLE
Container API : add mutations field

### ISSUE THREAD

**Issue by yachaka** [facebook/relay#1388]
Hi everyone,

I'm still rather new to Relay so mind me if this has been already discussed.
Regarding `Relay.createContainer`, wouldn't it be more convenient to include a `mutations` field ?
Something along theses lines :

``` js
const MyContainer = Relay.createContainer(MyComponent, {
    fragments: {
        post: () => /* ... */
    },

    mutations: (props) => ({
        likeSelf: new LikePostMutation({ postID: props.post.id }),
    }),
})
```

Mutations would then be accessible directly on `this.props` and wrapped by `commitUpdate`, Redux-style.
This would allow wrapped components to stay pure.

I understand this is easily achievable by supplying a middle component making the link, though it would make sense to include it by default.

**Comment by josephsavona** [comment]
What is the use case? Note that mutations can already be dispatched with `this.props.relay.{applyUpdate,commitUpdate}`, which makes the invocation of the mutation more explicit. Under your proposal, there is an extra level of indirection (ie developers would call e.g. `props.relay.mutations.likeSelf(props)` which would cause Relay to invoke the mutation... just seems like an extra indirection? Happy to discuss more if there's a use-case we're missing though!

**Comment by yachaka** [comment]
I was more thinking about binding the mutations directly on `this.props`, e.g. `this.props.likeSelf()`.
This would allow wrapped components to have no external dependency except from the props, which is great for modularity/testing.

For example, if I have a component <Button> with an `onClick` prop, I'd like somewhere it to commit a `LikePostMutation` and somewhere else a `CommentMutation`.

I could either create 2 additional components, i.e. `LikePostButton` and `CommentButton`, or if I'm lazy (which I am), I'd like a way to bind directly the mutation I want it to execute to the corresponding prop, like this (with an updated method name for clarity) :
```js
const LikePostButton = Relay.createContainer(Button, {
    ...
    createMutationsProps: (props, { applyUpdate, commitUpdate }) => ({
        onClick: () => new LikePostMutation({ postID: props.post.id }),
        // ^ If method returns an instance of Relay.Mutation, it is wrapped in a call to commitUpdate
    }),
})
```
But you're right ; it adds a small level of indirection.
And this is easily achievable with external code.
Me and my laziness !

**Comment by josephsavona** [comment]
Thanks for filing an issue and for the suggestion. It looks like the current API addresses this use-case, so I'll go ahead and close.
