### ISSUE TITLE
"this.props.commitUpdate" doesn't work if a new environment is created (login/logout)

### ISSUE THREAD

**Issue by AndrewIngram** [facebook/relay#1395]
Okay, this is a bit convoluted, so let me try and explain...
1. As recommended, I'm not implementing login using a mutation, instead what I'm doing is creating a new Relay environment after you login/logout, and re-rendering the entire app using the new environment instead.
2. After the re-render, the app correctly reflects the what that user should see. In my case, I'm seeing what products I've liked and what users i've followed.
3. I've added a simple counter that increments each time I create a new environment, this value is attached as a version attribute on the environment itself.
4. If I log in, the environment in React's context, correctly has the new version number. But when I trigger my like mutation using `this.props.relay.commitUpdate`, in `RelayMutation._resolveProps`, the `_environment` variable is still referencing the previous environment.
5. The end result is that the mutation doesn't work unless I allow the Like Button component to unmount (i.e. navigate to a different page and then come back) before attempting to click it.

**Summary**: I log in, create a new environment, as far as my components are concerned i'm using the new environment, but the internals of RelayMutation seems to be pointing at the previous one, even though i'm using `this.props.relay.commitUpdate`.

**Functioning workaround**: It I can use the relay environment in context to trigger the mutation instead and it works fine:

DOESN'T WORK

```
class FollowButton extends React.Component {
  handleClick = () => {
    const mutationProps = /* stuff */
    this.props.relay.commitUpdate(new FollowUserMutation(mutationProps));
  }
  // render
}
```

WORKS

```
class FollowButton extends React.Component {
  static contextTypes = {
    relay: Relay.PropTypes.Environment,
  };

  handleClick = () => {
    const mutationProps = /* stuff */
    this.context.relay.commitUpdate(new FollowUserMutation(mutationProps));
  }
  // render
}
```

Now obviously, i'd prefer to avoid using context directly in my components, but it seems like there's a bug in how commitUpdate and applyUpdate are being provided to containers.

**Comment by AndrewIngram** [comment]
So I think the issue might be in `createContainerComponent` (`RelayContainer.js`), it copies applyUpdate and commitUpdate into state in its constructor (https://github.com/facebook/relay/blob/master/src/container/RelayContainer.js#L158-L159), but doesn't have any mechanism for handling the fact that the context can change. It feels like a classic context gotcha.

**Comment by josephsavona** [comment]
@AndrewIngram Thanks for reporting this. It sounds like we need to update the `relay` prop in `componentWillReceiveProps` to re-copy the `applyUpdate` and `commitUpdate` functions if the context changes

**Comment by wincent** [comment]
I'm not sure if this is still an issue, but if it is, would you care to submit a PR for it? I don't think this is something we're going to address internally because we're aggressively prioritizing working on the roll-out of the new core and APIs (some work already landing on `master`, with more to come in the coming weeks/months), and aren't really working on the legacy core and API, unless we run into a specific bug that bites us internally (regardless, happy to entertain PRs). So I am going to close this for now, but in the meantime, thanks very much for the report.

**Comment by robrichard** [comment]
Looks like there's a PR for this issue here: https://github.com/facebook/relay/pull/1503
