### ISSUE TITLE
babel-relay-plugin reference to graphql too tight

### ISSUE THREAD

**Issue by sedubois** [facebook/relay#1400]
As this [GraphQL issue](https://github.com/graphql/graphiql/issues/58) mentions, there should be a single graphql dependency within `node_modules`. However, because `babel-relay-plugin`'s dependency on `graphql` is so tight (currently `graphql@^0.6.0`), tools such as [babel-plugin-react-relay](https://github.com/graphcool/babel-plugin-react-relay) are unable to meet this requirement, which makes use of [graphql-js configuration style](https://github.com/graphcool/graphql-config#use-local-schema-file-graphqljs) quite difficult ([discussion](https://github.com/graphcool/babel-plugin-react-relay/issues/10#issuecomment-250550062)). 

Would it be possible to loosen the required graphql version, or if not possible for some reason to ensure that it remains up to date with the latest available graphql? It might also help to make graphql a peer dependency? For example in monorepo projects with both frontend and backend, anyway it makes sense to explicitly reference `graphql` in `package.json`.

**Comment by sedubois** [comment]
Here is some documentation on the currently necessary workarounds: https://github.com/graphcool/babel-plugin-react-relay/pull/11/files

**Comment by josephsavona** [comment]
The right answer here is for babel-relay-plugin to be more easily configurable. There are some related issues for this and we're iterating on the plugin at the moment, we'll definitely keep this in mind. Thanks for the feedback!
