### ISSUE TITLE
Using first/after and last/before together (but not simultaneously)?

### ISSUE THREAD

**Issue by GrigoryPtashko** [facebook/relay#1403]
I can't understand if my use case is possible. Say a page loads and a connection is fetched with `first = 10`. Then when I scroll down I fetch another 10 by issuing `relay.setVariables({ first: first + 10 })`. And the newly fetched edges are appended to the connection.

Here's how it looks like:

``` text

------------   <= moment in time of page load

cursor 1
edge 1

cursor 2
edge 2

...

cursor n
edge n

```

Then say I've got a network disconnect and after reconnect I want to fetch everything that is above `cursor 1` and it must be prepended to the connection. In my mind I have to issue `relay.setVariables({ last: 10, before: 'cursor 1' })`.

So that the page would look like:

``` text

cursor -k
edge -k

...

cursor -2
edge -2

cursor -1
edge -1

------------   <= moment in time of page load

cursor 1
edge 1

cursor 2
edge 2

...

cursor n
edge n

```

But I do not understand how to write a proper fragment for such a connection. It seems like I can only specify `connection(first: $first)` but not `connection(first: $first, last: $last, before: $before)`.

Thanks.

**Comment by GrigoryPtashko** [comment]
I've prepared the playground for this. Here's the [link to the playground](https://facebook.github.io/relay/prototyping/playground.html#source=class%20Route%20extends%20Relay.Route%20%7B%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20viewer%3A%20(Component)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20%20%20query%20%7B%0A%20%20%20%20%20%20%20%20%20%20viewer%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%24%7BComponent.getFragment('viewer')%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%0A%20%20static%20routeName%20%3D%20'Route'%3B%0A%7D%0A%0Aclass%20MsgsComponent%20extends%20React.Component%20%7B%0A%20%20static%20propTypes%20%3D%20%7B%0A%20%20%20%20viewer%3A%20React.PropTypes.object%2C%0A%20%20%7D%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20console.log('render'%2C%20this.props.viewer.msgs)%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20this.loadMoreBefore()%7D%3ELoad%20more%20before%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%7Bthis.props.viewer.msgs.edges.map((%7B%20node%2C%20cursor%20%7D)%20%3D%3E%20(%0A%20%20%20%20%20%20%20%20%20%20%3Cdiv%3E%7Bnode.id%7D%26nbsp%3B%7Bnode.text%7D%26nbsp%3B%7Bcursor%7D%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20))%7D%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20this.loadMoreAfter()%7D%3ELoad%20more%20after%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%20%20%0A%20%20loadMoreBefore()%20%7B%0A%20%20%20%20this.props.relay.setVariables(%7B%0A%20%20%20%20%20%20last%3A%201%2C%0A%20%20%20%20%20%20before%3A%20'500'%2C%0A%20%20%20%20%20%20first%3A%20null%2C%0A%20%20%20%20%7D)%3B%0A%20%20%7D%0A%0A%20%20loadMoreAfter()%20%7B%0A%20%20%20%20this.props.relay.setVariables(%7B%0A%20%20%20%20%20%20first%3A%20this.props.relay.variables.first%20%2B%201%2C%0A%20%20%20%20%7D)%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20MsgsContainer%20%3D%20Relay.createContainer(MsgsComponent%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20first%3A%2010%2C%0A%20%20%20%20after%3A%20null%2C%0A%20%20%20%20last%3A%20null%2C%0A%20%20%20%20before%3A%20null%2C%0A%20%20%7D%2C%0A%0A%20%20fragments%3A%20%7B%0A%20%20%20%20viewer%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20%20%20fragment%20on%20Viewer%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20msgs(first%3A%20%24first%2C%20after%3A%20%24after%2C%20last%3A%20%24last%2C%20before%3A%20%24before)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20cursor%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hasPreviousPage%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%20%20%0AReactDOM.render(%3CRelay.RootContainer%20Component%3D%7BMsgsContainer%7D%20route%3D%7Bnew%20Route()%7D%20%2F%3E%2C%20mountNode)%3B%0A&schema=import%20%7B%0A%20%20GraphQLNonNull%2C%0A%20%20GraphQLID%2C%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%7D%20from%20'graphql'%3B%0A%0Aimport%20%7B%0A%20%20connectionArgs%2C%0A%20%20connectionDefinitions%2C%0A%20%20nodeDefinitions%2C%0A%20%20cursorForObjectInConnection%2C%0A%20%20fromGlobalId%2C%0A%7D%20from%20'graphql-relay'%3B%0A%0Afunction%20getMsgs()%20%7B%0A%20%20const%20msgs%20%3D%20%5B%5D%3B%0A%20%20for%20(let%20idx%20%3D%200%3B%20idx%20%3C%201000%3B%20idx%2B%2B)%20%7B%0A%20%20%20%20msgs.push(%7B%0A%20%20%20%20%20%20id%3A%20idx%2C%0A%20%20%20%20%20%20text%3A%20%60msg%24%7Bidx%7D%60%2C%0A%20%20%20%20%20%20publishDate%3A%20idx%2C%0A%20%20%20%20%7D)%3B%0A%20%20%7D%0A%0A%20%20return%20msgs%3B%0A%7D%0A%0Avar%20msgs%20%3D%20getMsgs()%3B%0Avar%20PAGE_LOAD_TIMESTAMP%20%3D%20500%3B%0A%0Avar%20%7BnodeInterface%2C%20nodeField%7D%20%3D%20nodeDefinitions(%0A%20%20(globalId)%20%3D%3E%20%7B%0A%20%20%20%20const%20%7Btype%2C%20id%7D%20%3D%20fromGlobalId(globalId)%3B%0A%20%20%20%20if%20(globalId%20%3D%3D%200)%20%7B%0A%20%20%20%20%20%20return%20%7B%20id%3A%200%20%7D%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20return%20msgs(id)%3B%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20(obj)%20%3D%3E%20%7B%0A%20%20%20%20console.log('nodeDefinitions%20obj'%2C%20obj)%3B%0A%20%20%20%20%0A%20%20%20%20if%20(obj.id%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20return%20viewerType%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20return%20msgType%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A)%3B%0A%0Avar%20msgType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Msg'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLID)%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20text%3A%20%7B%0A%20%20%20%20%20%20type%3A%20GraphQLString%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%0A%20%20interfaces%3A%20%5BnodeInterface%5D%2C%0A%7D)%3B%0A%0Avar%20%7BconnectionType%3A%20msgConnection%2C%20edgeType%3A%20msgEdge%7D%20%3D%0A%20%20connectionDefinitions(%7Bname%3A%20'Msg'%2C%20nodeType%3A%20msgType%7D)%3B%0A%0Avar%20viewerType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Viewer'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLID)%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20name%3A%20%7B%0A%20%20%20%20%20%20type%3A%20GraphQLString%0A%20%20%20%20%7D%2C%0A%20%20%20%20msgs%3A%20%7B%0A%20%20%20%20%20%20type%3A%20msgConnection%2C%0A%20%20%20%20%20%20args%3A%20connectionArgs%2C%0A%20%20%20%20%20%20resolve%3A%20(_%2C%20args)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20console.log('args'%2C%20args)%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20if%20(args.first)%20%7B%0A%20%20%20%20%20%20%20%20%20%20if%20(!args.after)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20conn%20%3D%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20edges%3A%20%5B%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pageInfo%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hasNextPage%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hasPreviousPage%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20startCursor%3A%20PAGE_LOAD_TIMESTAMP%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20endCursor%3A%20PAGE_LOAD_TIMESTAMP%20%2B%20args.first%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20(let%20idx%20%3D%200%3B%20idx%20%3C%20args.first%3B%20idx%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20conn.edges.push(%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20cursor%3A%20PAGE_LOAD_TIMESTAMP%20%2B%20idx%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%3A%20msgs%5BPAGE_LOAD_TIMESTAMP%20%2B%20idx%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20conn%3B%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20afterIdx%20%3D%200%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20(%3B%20afterIdx%20%3C%20msgs.length%3B%20afterIdx%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(msgs%5BafterIdx%5D.publishDate%20%3D%3D%20parseInt(args.after))%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('afterIdx'%2C%20afterIdx)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20conn%20%3D%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20edges%3A%20%5B%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pageInfo%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hasNextPage%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hasPreviousPage%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20startCursor%3A%20PAGE_LOAD_TIMESTAMP%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20endCursor%3A%20PAGE_LOAD_TIMESTAMP%20%2B%20args.first%20-%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20(let%20idx%20%3D%20afterIdx%20%2B%201%3B%20idx%20%3C%3D%20afterIdx%20%2B%20args.first%3B%20idx%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20conn.edges.push(%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20cursor%3A%20msgs%5Bidx%5D.publishDate%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%3A%20msgs%5Bidx%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20conn%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%20else%20if%20(args.last)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%0A%20%20interfaces%3A%20%5BnodeInterface%5D%2C%0A%7D)%3B%0A%0Avar%20queryType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Query'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20node%3A%20nodeField%2C%0A%20%20%20%20viewer%3A%20%7B%0A%20%20%20%20%20%20type%3A%20viewerType%2C%0A%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20%7B%20id%3A%200%20%7D%3B%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%20%20%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20queryType%2C%0A%7D)%3Bl).

The idea is that I can load `first + N` but cannot load `last + K` **before** the first `cursor`.

I'll duplicate the code (without the schema) here (I'm taking it from the playground I've just mentioned).

```javascript
class Route extends Relay.Route {
  static queries = {
    viewer: (Component) => Relay.QL`
        query {
          viewer {
            ${Component.getFragment('viewer')}
          }
        }
    `,
  };

  static routeName = 'Route';
}

class MsgsComponent extends React.Component {
  static propTypes = {
    viewer: React.PropTypes.object,
  };

  render() {
    console.log('render', this.props.viewer.msgs);
    return (
      <div>
        <button onClick={() => this.loadMoreBefore()}>Load more before</button>
        {this.props.viewer.msgs.edges.map(({ node, cursor }) => (
          <div>{node.id}&nbsp;{node.text}&nbsp;{cursor}</div>
        ))}
        <button onClick={() => this.loadMoreAfter()}>Load more after</button>
      </div>
    );
  }
  
  loadMoreBefore() {
    this.props.relay.setVariables({
      last: 1,
      before: '500',
      first: null,
    });
  }

  loadMoreAfter() {
    this.props.relay.setVariables({
      first: this.props.relay.variables.first + 1,
    });
  }
}

const MsgsContainer = Relay.createContainer(MsgsComponent, {
  initialVariables: {
    first: 10,
    after: null,
    last: null,
    before: null,
  },

  fragments: {
    viewer: () => Relay.QL`
        fragment on Viewer {
            msgs(first: $first, after: $after, last: $last, before: $before) {
                edges {
                    node {
                        id
                        text
                    }
                    cursor
                }
                pageInfo {
                    hasNextPage
                    hasPreviousPage
                }
            }
        }
    `,
  },
});
  
ReactDOM.render(<Relay.RootContainer Component={MsgsContainer} route={new Route()} />, mountNode);
```

**Comment by gre** [comment]
I have same usecase.
But it looks like it's not possible to use both last and first on the same container? see related https://github.com/facebook/relay/issues/1170 & https://github.com/facebook/relay/issues/540

**Comment by sibelius** [comment]
can't we use to different connections as a workaround for now?

like:

```
firstMsgs: msgs(first: $first) {}
lastMsgs: msgs(last: $last) {}
```

and then concatenate them?

**Comment by GrigoryPtashko** [comment]
@sibelius I did not try it this way.. But the idea looks promising. I've solved my problem with graphql subscriptions that prepend a bunch of new edges after the network reconnect.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

I believe this issue is much improved with Relay Modern.

If this issue is still important to you, please feel free to reopen it with an update.
