### ISSUE TITLE
Invariant Violation: callsFromGraphQL(): Expected a declared value for variable

### ISSUE THREAD

**Issue by vladar** [facebook/relay#141]
Trying to imlement a workaround for root query with two arguments, mentioned in #112.

And receive error:
```
"Invariant Violation: callsFromGraphQL(): Expected a declared value for variable, `<entityType>`"
```

Am I missing something? Here is route query:
```
viewer: (Component) => Relay.QL`
  query {
    viewer {
      ${Component.getFragment('viewer')}
    }
  }
`
```

Component fragment:
```
viewer:() => Relay.QL`
  fragment on Viewer {
    entity(entityType: $entityType, slug: $slug) {
       ... on SomeEntityType {
         id,
         name
      }
    }
  }
`,
```

Then root container initialization:
```
React.render(
  <Relay.RootContainer
      Component={CompanyPage}
      route={new EntityPageRoute({entityType: "SOMETYPE", slug: 'some-slug'})}
      />,
  document.getElementById('react-app')
);

```

No request is made. Just fails with this error.

Can you please shed some lights on what this error actually means?

**Comment by josephsavona** [comment]
The component fragment references two variables, `$entityType` and `$slug`, and the error message indicates that no values are defined for these. When the values of parameters come from the route, they need to be passed down in the call to `getFragment`:

```javascript
// Route
viewer: (Component, params) => Relay.QL`
  query {
    viewer {
      # note second argument to `getFragment()`:
      ${Component.getFragment('viewer', {entityType: params.entityType, slug: params.slug})}
    }
  }
`
```

**Comment by vladar** [comment]
Ah missed that. Thanks!

**Comment by vladar** [comment]
Another note if someone faces with this problem. Make sure to define `initialVariables` on your container (even if they are nulls). Otherwise Relay will fail to merge them back after update and throw:

```javascript
export default Relay.createContainer(CompanyPage, {
  // This is required:
  initialVariables: {
    slug: null,
    entityType: null
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        entity(entityType: $entityType, slug: $slug) {
          ... on SomeEntityType {
          id,
          name
        }
      }
    }`
  }
});
```

**Comment by davide-ganito** [comment]
Hi, i'm using this pattern with `react-relay-router` and the `entity` field is not available as `viewer` prop on render.
I have implemented `prepareVariables` in the `CompanyPage` Container and I have noticed that it is called 3 times. 
The first and the second with the correct params injected, the last one with the `initialVariable` values.

By the way, why `prepareVariables` is called 3 times?

**Comment by lvarayut** [comment]
@josephsavona, the answer is very helpful. Is there any documentation about those arguments?

**Comment by josephsavona** [comment]
@lvarayut check out http://facebook.github.io/relay/docs/api-reference-relay-container.html#getfragment-overriding-fragment-variables

**Comment by josephsavona** [comment]
Also, the [`initialVariables`](http://facebook.github.io/relay/docs/api-reference-relay-container.html#getfragment-overriding-fragment-variables) docs mention that a default value must be provided for any variables that you reference within the fragment.

**Comment by lvarayut** [comment]
The documentation doesn't say anything about arguments in the `viewer: (Component, variables)`; both Component and variables. Especially, the `variables` is the second argument in the Route, however, it's  the first argument in the Container. I think that they are very important and worth to be mentioned.

**Comment by josephsavona** [comment]
@lvarayut I see what you mean. Feel free to send a PR to expand on the docs!
