### ISSUE TITLE
Uncaught Invariant Violation: RelayMutationQuery : Invalid field name on fat query, `data`.

### ISSUE THREAD

**Issue by amgadserry** [facebook/relay#1410]
I'm trying to create a simple mutation that creates a node of type Restaurant 
here is the scheme for the mutation 

```
type Restaurant implements Node {
  id: ID!
  data: RestaurantData
}

input UpdateRestaurantInput {
  data: String!
  clientMutationId: String
}

type UpdateRestaurantPayload {
  restaurant: Restaurant
  clientMutationId: String
}

type Mutation {
  UpdateRestaurant(input: UpdateRestaurantInput!): UpdateRestaurantPayload
}
```
here is the relay mutation 
```
import Relay from 'react-relay';

export default class UpdateRestaurant extends Relay.Mutation {

  getMutation() {
    return Relay.QL`mutation {UpdateRestaurant}`;
  }

  getVariables() {
    return {data: JSON.stringify(this.props.value)};
  }

  getFatQuery() {
    return Relay.QL`fragment on UpdateRestaurantPayload {
       restaurant{ 
          data
          } 
        }`;
  }

  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: {
        data: this.props.value.id,
      },
    }];
  }
  
}
```
when ever i try to commit the mutation using 
```
this.props.relay.commitUpdate(new UpdateRestaurant({value: this.state.value},
			{onSuccess: (response) => {
				debugger;
				var value = this.state.value; 
				value._id = response.restaurant.data.id; 
				this.setState({value: value});
			}}))
```
i get this error Uncaught Invariant Violation: RelayMutationQuery : Invalid field name on fat query, `data`. 
although data is on the payload and mentioned in the fatQuery

**Comment by josephsavona** [comment]
At a quick glance, I suspect this is because the `data` fiekd is not a top level field of the mutation response. Try changing the fields change config to restaurant (parent of data).

**Comment by amgadserry** [comment]
@josephsavona  i have tried that but then the mutation query generated doesn't include data at all and still the onSuccess doesn't fire so the only data returned from the server is clientMutationId the mutation does happen but nothing happens on the client side

**Comment by nikolal** [comment]
@amgadserry 

How did you solve this issue?

**Comment by josephsavona** [comment]
@nikolal We'd recommend using the new static mutation API instead: https://facebook.github.io/relay/docs/api-reference-relay-graphql-mutation.html#content
