### ISSUE TITLE
Mutation doesn't include variables i specified in getFatQery function in the response 

### ISSUE THREAD

**Issue by amgadserry** [facebook/relay#1412]
here is my mutation

```

import Relay from 'react-relay';

export default class UpdateRestaurant extends Relay.Mutation {

  static fragments = {
    restaurant: () => Relay.QL`
        fragment on RestaurantData {
            id
          }`,
  };

  getMutation() {
    return Relay.QL`mutation {UpdateRestaurant}`;
  }

  getVariables() {
    return {data: JSON.stringify(this.props.value)};
  }

  getFatQuery() {
    return Relay.QL`fragment on UpdateRestaurantPayload {
          restaurant{
              id
          }
        }`;
  }

  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: {restaurant: this.props.value._id}, //this is not retrieved by relay it was just created
    }];
  }
}
```

so from what i know relay intersects fatQuery with configs to generate its schema for response data in this case this is a just created node and _id is a fake id 
what happens is that relay doesn't include the restaurant at all in the response data although the mutation finishes i cant retrieve the id with the mutation what should i do

**Comment by Gregoor** [comment]
Hi @amgadserry,

The fatQuery specifies all the things that can change. Are you sure that the ID of a restaurant would change (not sure whether Relay can handle that).
There are two other requirements to get the required response:
- the graphql server has to actually return the fields in the payload (that has to be done explicity)
- relay intersects the fat query with what is already tracked about that object (e.g. restaurant), afaik that would lead to nothing being returned when no field of that object is tracked

If you've already solved it for yourself, consider closing the issue (and leaving your solution for others to find).
