### ISSUE TITLE
Using prepareVariables causing (invalid) warnings

### ISSUE THREAD

**Issue by gucki** [facebook/relay#1414]
I'm using latest relay 0.9.3.  I have a relay container like this (beware, some coffeescript ahead):

```
Relay.createContainer Component,
  initialVariables:
    brandId: null

  prepareVariables: (variables) ->
    brandId: variables.brandId
    loadModels: variables.brandId?

  fragments:
    root: -> Relay.QL`
      fragment on RootLevel {
        id

        models: modelsList(brandId: $brandId) @include(if: $loadModels) {
          id
          name
        }
      }
    `
```

In my react component I'm having a select which fires `@props.relay.setVariables(brandId: id)` when it's changed.

Everything works as expected, but a few warnings are logged:
1. When the component is rendered: "Warning: RelayContainer: Expected query variable `loadModels` to be initialized in `initialVariables`.".
2. When `setVariables` is called: "Warning: RelayContainer: component `Constructor` was rendered with variables that differ from the variables used to fetch fragment `root`. The fragment was fetched with variables `{"brandId":null,"loadModels":false}`, but rendered with variables `{"brandId":"QnJhbmQtMjA1","loadModels":true}`. This can indicate one of two possibilities: 
   - The parent set the correct variables in the query - `Constructor.getFragment('root', {...})` - but did not pass the same variables when rendering the component. Be sure to tell the component what variables to use by passing them as props: `<Constructor ... brandId={...} loadModels={...} />`.
   - You are intentionally passing fake data to this component, in which case ignore this warning."

When I remove the `prepareVariables` method, add `loadModels: false` to `initialVariables` and add `loadModels`to the `@props.relay.setVariables(brandId: id, loadModels: id?)` it works as before but this time without any warnings.

Bug of relay or my fault?

**Comment by josephsavona** [comment]
The first warning is legit: you must specify a default value for all variables. Use null for variables that you will actually initialize in prepareVariables. 

The second warning about mismatched fetched/rendered variables looks like a false positive.

**Comment by wincent** [comment]
I believe there's nothing further actionable here so I am going to close it out. (Also worth noting, `prepareVariables` is now considered "legacy" API, and is being replaced by a new core and set of APIs that are currently landing on the `master` branch in stages, and will continue to roll out over the coming weeks/months.)

Thanks for posting the issue!
