### ISSUE TITLE
[babel] How to use react-native-stage-0/decorator-support with Relay.

### ISSUE THREAD

**Issue by joonhocho** [facebook/relay#1416]
I am trying to use react-native + relay + [ex-navigation](https://github.com/exponentjs/ex-navigation), and having a problem with babel compilation.

ex-navigation uses (babel-preset-react-native-stage-0)[https://github.com/skevy/babel-preset-react-native-stage-0] so I have to add it to my .babelrc

Here's how my .babelrc looks like with ex-navigation:

    {
      "passPerPreset": true,
      "presets": [
        {"plugins": ["./plugins/babelRelayPlugin"]},
        "react-native-stage-0/decorator-support"
      ]
    }

It was working well when I was using the following config before using ex-navigation:

    {
      "passPerPreset": true,
      "presets": [
        {"plugins": ["./plugins/babelRelayPlugin"]},
        "react-native"
      ]
    }

Now that it uses `react-native-stage-0/decorator-support` instead of `react-native`, it errors with the following error message:

SyntaxError app/node_modules/@exponent/ex-navigation/src/ExNavigationStack.js: Method has decorators, put the decorator plugin before the classes one.

Any thoughts on what this is about?

**Comment by chirag04** [comment]
```
{
  "presets": [
    "react-native-stage-0/decorator-support"
  ],
  "plugins": [
    [ "./src/relay/babelRelayPlugin" ]
  ]
}
```

drop passPerPreset.

**Comment by joonhocho** [comment]
Thanks! It worked for me.
I removed extra parenthesis for relay plugin, too.
Here's my final babelrc that works:

```
{
      "presets": [
        "react-native-stage-0/decorator-support"
      ],
      "plugins": [
        "./plugins/babelRelayPlugin"
      ]
    }
```
