### ISSUE TITLE
Unable to Typecheck Passed Props

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/relay#1418]
Is there a way for Flow to typecheck props directly passed to a Relay wrapped component?

``` javascript

// No Flow error is shown when rendering <Component /> without providing the width prop

// ...Render method of some other component
    render() {
        return (
            <Component />
        )
    }
// ...

type Props = {
    width: number,
    foo: {
        bar: string
    }
}
class Component extends React.Component {
    props: Props
    constructor(props: Props) {
        super()
        this.props = props
    }
}
export default Relay.createContainer(Component, {
    fragments: {
        foo: () => Relay.QL`
            fragment on Foo { bar }
        `
    }
})
```

**Comment by mwalkerwells** [comment]
It's obvious to me now, but the type definitions are not included in the build. Are there plans for this?

**Comment by Gasparila** [comment]
@mwalkerwells did you see this issue: https://github.com/facebook/relay/issues/1064? It appears to be an open issue that has gathered some support but I don't believe it is being actively worked on

**Comment by wincent** [comment]
Sorry for the slow response here.

We're currently in the process of rolling out a new core and set of APIs that we built last year and have been testing in production in FB apps. Part of this is the ability to generate Flow type declarations for mutation inputs and also for component props. As such, there is nothing to actually implement here; we just need to finish shipping the new core. If you look on the `master` branch, you'll see this is already underway, and will continue to ship the remaining pieces over the coming weeks/months. As there's nothing directly actionable here, I am going to close this for now, but I want to thank you for raising the issue. We appreciate your contribution!

**Comment by dmnd** [comment]
This was mentioned in the [recent team sync](https://github.com/facebook/relay/blob/master/meta/meeting-notes/2017-01-17-team-sync.md#updates) too: 

> Getting automated Flow type generation working in www.
