### ISSUE TITLE
Login Mutation

### ISSUE THREAD

**Issue by yachaka** [facebook/relay#1420]
Hello everyone,

I'm having a hard time trying to implement a login mutation.
I don't understand what I should put in the `getConfigs()` method in order for Relay to update my `viewer` prop ?

My Root Query has a `viewer` field of type `User` that returns the current logged user.
My `LoginMutation` returns a `User` type.
Here is my `LoginMutation` :

```js
import Relay, {
  Mutation
} from 'react-relay'

module.exports = class LoginMutation extends Mutation {

  getMutation() {
    return Relay.QL`mutation { login }`
  }

  getVariables() {
    return {
      email: this.props.email,
      password: this.props.password,
    }
  }

  getFatQuery() {
    return Relay.QL`
      fragment on LoginPayload {
        viewer
        errors
      }
    `
  }

  getConfigs() {
    return [] // What should I put here to update the current viewer ?
  }
}
```

Thank you for your help

**Comment by chungwong** [comment]
This is to me is not an issue/bug.
If you have questions/need helps, please refer to [here](https://facebook.github.io/relay/support.html)
[Here](http://stackoverflow.com/questions/32535141/relayjs-authentication-using-relay-which-mutation-to-use) is a simliar question

**Comment by yachaka** [comment]
You're right. I did some research but I didn't find a clear answer, which wasn't a hack.
Thanks for the links, I'm closing this.

**Comment by Naoto-Ida** [comment]
@yachaka Have you found a solution to this? I think this is a legitimate use case for mutations, yet when I come across supposed solutions nothing happens on the app side.

**Comment by yachaka** [comment]
@Naoto-Ida The best solution I found is to reset the environment. Don't use `Relay.RootContainer` but `Relay.Renderer`, pass it in the `environment` prop, and reset it along logout.

**Comment by Naoto-Ida** [comment]
@yachaka I see, so we might have different issues and I may have been confused.

My issue might have more to do with the fact that there is nothing being received on the app side after the mutation. I've seen people doing implementations like [this](https://github.com/yongjz/relay-graphql-example/blob/04a77ce1a148626102b6f292dc51524b5d02712a/js/mutations/LoginMutation.js#L40), but shouldn't the `id` field in `user` not be able to be requested at this point? All I want to do is pass an `email` and `password` through the mutation and return a user.

**Comment by yachaka** [comment]
If it doesn't mutate the client, why do you want to use a mutation ?

**Comment by Naoto-Ida** [comment]
Sorry I was lacking information.
We assign a token to the user when they login to any of our apps.
If they've already logged in before, the existing one is returned.
If not, a new one is created. This is why I have it as a mutation and not a query.
