### ISSUE TITLE
Mongo + database.js  to graphQL (schema.js)

### ISSUE THREAD

**Issue by spyalert01** [facebook/relay#143]
If we have data stored in Mongo, are we suppose to link the database.js with Mongo to deal with retrieving data for GraphQL?

I found that schema.js somehow specify the datatype, which is redundant? since we have data in mongo with its related type.

Is there a simple example on this?

is there any prefered database engine that is perfered by graphhQL?

**Comment by josephsavona** [comment]
GraphQL is agnostic of data storage and programming languages. As for how to integrate with MongoDB, this is a really great question to ask at [the graphql repo](https://github.com/graphql/graphql-js)
