### ISSUE TITLE
Data fetched by REQUIRED_CHILDREN not written into client store

### ISSUE THREAD

**Issue by sedubois** [facebook/relay#1430]
The [documentation](https://facebook.github.io/relay/docs/guides-mutations.html#required-children) says: `Data fetched as a result of a REQUIRED_CHILDREN config is not written into the client store`. Why is that, and would there be any way to enable it at Relay level?

I am experimenting with [Graphcool](https://graph.cool/) authentication, and when calling the `signinUser` mutation, it creates a new field `user` onto `viewer`. My understanding is that the only way to get the rest of the app consume this new data (e.g displaying a user badge in my page header with `viewer.user.givenName` and `viewer.user.picture`) is to add a `REQUIRED_CHILDREN` config.

However I am currently calling the `signinUser` mutation from a Redux saga, so from outside a React component (the Relay API allows this without problem). (Code is [here](https://github.com/sedubois/belong/blob/gql-auth/app/containers/LoginCallback/lib.js#L41))

But in this configuration, I therefore have no React component to update as suggested in the docs:
```
this.props.relay.commitUpdate(
  new CreateCouponMutation(),
  {
    onSuccess: response => this.setState({
      couponCount: response.coupons.length,
    }),
  }
);
```

I suppose I could pass this result into the Redux store and update the component data through those means, but it seems quite cumbersome and would defeat the purpose of using Relay in the first place. The other option I see is to make sure the mutation is called from within a component, but it means I couldn't use sagas any more. I have a feeling Relay and sagas are just not made to be combined, but then I wonder how async state management (e.g doing an authentication flow with Auth0 in my case) is supposed to be done in a Relay app.

I suppose the Relay store is not updated for valid reason (it's not yet aware of any code that will need this) but I could make sure that the components which need the new data will re-render (e.g by making sure that they also consume pre-existing store data that gets changed, although that's a bit hacky). Could e.g a flag be added to Relay to force it to store the result of `REQUIRED_CHILDREN`?

**Comment by Gregoor** [comment]
I tried my best answering your question [on StackOverflow](http://stackoverflow.com/questions/40244124/updating-relay-store-after-graphcool-sign-in/40261075#40261075). Imo that's the best place to ask and answer it, as it isn't an issue with relay. So, you might want to consider closing this ;)

**Comment by sedubois** [comment]
Thanks a lot, I'll follow up there and with the graphcool team directly. Currently wondering why the mutations return a `viewer.user` with value `null`.
