### ISSUE TITLE
DefaultNetworkLayer Losing values assigned in Constructor

### ISSUE THREAD

**Issue by rterysen-openroad** [facebook/relay#1432]
Our Client Side default network layer seems to be losing values assigned in its constructor.  We are using a simple implementation provided in the docs. 

```
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://example.com/graphql', {
    credentials: 'same-origin',
  })
);
```

We found that we are not getting our httpOnly cookie in our mutation calls.  After alot of debugging we do not have the init variable in the sendMutation function.  When we manually add   `credentials: 'same-origin',` to the sendMutation call it works great.  We have /graphql behind NGINX as reverse proxy.  This scenario is executing a mutation that you need to be authenticated to perform. 

We log out the init object in the DefaultNetworkLayer constructor and also in the sendMutation function. We see it get defined initially but then we see it as a empty object when in sendMutation. 

Any advice on how we can make this persist?

**Comment by wincent** [comment]
Thanks for filing the issue! Relay Modern is now out and it uses a completely different network layer implementation. Closing this one because no other work is going to take place on the old API, in order to keep the issue tracker focused on current work.
