### ISSUE TITLE
Relay generating invalid query after using `setVariables`

### ISSUE THREAD

**Issue by rohit-ravikoti** [facebook/relay#1435]
Similar issue to #861.

**versions:**
```
"react-relay": "^0.9.3",
"react-router-relay": "^0.13.5"
```

# Original query:
```
query MyProductionDetailsQuery($id_0:ID!,$where_1:ProductionRoleWhereArgs!) {
  getProduction(id:$id_0) {
    id,
    ...F0
  }
}
fragment F0 on Production {
  id,
  title,
  company,
  city,
  expDate,
  archived,
  start,
  end,
  paymentType,
  paymentDetails,
  description,
  hasFee,
  feeDetails,
  type,
  _roles4oPiwv:roles(first:10,where:$where_1) {
    edges {
      node {
        id,
        title,
        type,
        archived,
        description
      },
      cursor
    },
    pageInfo {
      hasNextPage,
      hasPreviousPage
    }
  }
}
```
## variables:
`{id_0: "UHJvZHVjdGlvbjoxNg==", where_1: {archived: {eq: true}}}`

# Query after `setVariables`:
```
query My_production_details_page_ProductionRelayQL($id_0:ID!,$where_1:ProductionRoleWhereArgs!) {
  node(id:$id_0) {
    ...F0
  }
}
fragment F0 on Production {
  id,
  _roles6J5gK:roles(first:10,where:$where_1) {
    edges {
      node {
        id,
        title,
        type,
        archived,
        description
      },
      cursor
    },
    pageInfo {
      hasNextPage,
      hasPreviousPage
    }
  }
}
```
## variables:
`{id_0: "UHJvZHVjdGlvbjoxNg==", where_1: {archived: {eq: false}}}`

I'm using react-router to render the component with react-router-relay.
I'm not sure if i'm doing something wrong with the configuration or if it's just a bug on Relay's end.

Please help!

**Comment by d-winter** [comment]
@rohit-ravikoti did you figured out how to solve this issue? Got the same error using react-relay 0.10.0

**Comment by rohit-ravikoti** [comment]
Hey @d-winter,
Yes I did! It was a problem with the server side implementation. Basically relay requires a `node` root field to be supplied on the graphql server:
http://stackoverflow.com/questions/33399901/in-relay-what-role-do-the-node-interface-and-the-global-id-spec-play

Hope this helps!
