### ISSUE TITLE
Relay doesnt read from cache

### ISSUE THREAD

**Issue by proProbe** [facebook/relay#1438]
Hello Everyone,

I have two different Relay.Renderer components that displays data about `posts`. The problem Im stumbeling upon is that the cache isnt used properly in one of the relay.renderer components. I have `list_posts` that looks something like:
```
viewer: () => Relay.QL`
            fragment on Viewer {
                list_posts(
                ) {
                    edges {
                        node {
                            id
                            title
                            }
                        }
                    }
                }
            }
        `
```
I have then a `post` component that looks something like with its queryconfig in relay.renderer:
```
post: () => Relay.QL`
            fragment on post {
                id
                title
            }
        `
...
queryConfig={{
    queries: {
         post: () => Relay.QL`query { post(id: $postId) }`,
    },
    params: {
         postId: this.props.previewPost.id,
    },
    name: "PreviewRoute"
}}
```
the `post`s data already exist in `list_posts` but the `post`-component still fetches the data from the server instead of just using the cache. Anyone who knows why?

**Comment by josephsavona** [comment]
Great question. Relay can't infer how the `post` root call behaves - it doesn't know that it will return an object whose ID matches the argument id. Instead, use the `node(id: $id)` root call defined in the object identification spec.

**Comment by proProbe** [comment]
@josephsavona thanks! it solved my situation. is this how you usually do it with `node(id: $id)`? Is this because Im using two different calls?

**Comment by josephsavona** [comment]
Yes, `node` is the recommended and supported way to refetch items by id. GraphQL does not impose any meaning to particular fields, so clients require either configuration or convention (node) to understand how root field may map to previously fetched data.

**Comment by josephsavona** [comment]
I'm going to close since there is a documented way to handle this case, but we're open to PRs that make it more obvious. What did you look at it where would you expect this to be documented?

**Comment by proProbe** [comment]
@josephsavona Im not sure where to read about this. I totally missed the section in https://facebook.github.io/relay/docs/graphql-object-identification.html#content which would probably help most people with this problem. If anything, maybe some more documentation about using multiple relay.renderers in the same app.
