### ISSUE TITLE
query doesnt retry. react-native

### ISSUE THREAD

**Issue by proProbe** [facebook/relay#1439]
Hello Everyone!

Im currently using relay in a react-native app and am having some problem with `retries`. The problem is namely that the app doesnt seem to retry att all after a query timeouts. The error I get is `fetchWithRetries(): Failed to get response from server, tried 1 times.` where the networklayer config is
```
                this.props.environment.injectNetworkLayer(
                    new DefaultNetworkLayer(config.graphqlURL, {
                        headers: {
                            Authorization: `Bearer ${jwt}`,
                        },
                        fetchTimeout: 10,
                        retryDelays: [1000, 2000, 3000, 4000, 5000],
                    })
                );
```
I expect that it should retry atleast 5 times and the error should be `fetchWithRetries(): Failed to get response from server, tried 6 times.`

**UPDATE**
To include some more errorstacks:
the readyState:
```
Warning: RelayReadyState: Invalid state change from `{"aborted":false,"done":false,"error":{},"events":[{"type":"NETWORK_QUERY_START"},{"type":"CACHE_RESTORE_START"},{"type":"CACHE_RESTORE_FAILED"},{"type":"NETWORK_QUERY_ERROR","error":{}}],"ready":false,"stale":false}` to `{"error":{}}`.
```
```
error:Error: fetchWithRetries(): Failed to get response from server, tried 1 times. at ...
message:"fetchWithRetries(): Failed to get response from server, tried 1 times."
stack:"Error: fetchWithRetries(): Failed to get response from server, tried 1 times
```
![screenshot from 2016-11-09 14-32-06](https://cloud.githubusercontent.com/assets/3802899/20140118/c12d1b24-a689-11e6-892b-2c56c46a04c0.png)

**Comment by proProbe** [comment]
Solved this by using https://github.com/nodkz/react-relay-network-layer instead

**Comment by nodkz** [comment]
Related discussion https://github.com/nodkz/react-relay-network-layer/issues/22
