### ISSUE TITLE
Polyfill issues w/ relay and babel-polyfill

### ISSUE THREAD

**Issue by griffinmichl** [facebook/relay#1443]
I am using babel-polyfill.

`warning.js:36 Warning: Relay relies on polyfills for ES6 features in older browsers. Babel provides a good one: https://babeljs.io/docs/usage/polyfill/`

I keep getting this warning followed by:

`RelayTaskQueue.js:97 Uncaught TypeError: _promise2.default is not a constructor`

Not sure if it's related, but I also get the following warning:

```
client?cd17:41 ./~/fbjs/lib/Promise.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/griffin.michl/ads/ads-tools/ui/node_modules/fbjs/lib/Promise.js
    Used by 8 module(s), i. e.
    /Users/griffin.michl/ads/ads-tools/ui/node_modules/react-relay/lib/Relay.js
* /Users/griffin.michl/ads/ads-tools/ui/node_modules/fbjs/lib/promise.js
    Used by 2 module(s), i. e.
    /Users/griffin.michl/ads/ads-tools/ui/node_modules/fbjs/lib/Promise.js
```

**Comment by griffinmichl** [comment]
Someone else on stackoverflow is having the same issue: http://stackoverflow.com/questions/40552072/how-do-i-get-polyfills-to-work-with-relay

**Comment by aizatto** [comment]
@griffinmichl did you find a solution? What was it?

**Comment by griffinmichl** [comment]
It was a build issue. I had webpack resolving modules as `'.'`, which interfered with relay's internal imports.

**Comment by aizatto** [comment]
I managed to fix the problem myself. The problem was that I was running on Mac OS X with a case **insensitive** file system.

I tried creating a disk image with case sensitivity, and it worked.  Followed instructions here. https://gist.github.com/dixson3/8360571 #
