### ISSUE TITLE
Object doesn't support property or method 'getFragment' with <= IE10

### ISSUE THREAD

**Issue by jaden-chen** [facebook/relay#1444]
Similar to #394 
I'm running into this error with <= IE10 and caused my site to break,
`Object doesn't support property or method 'getFragment'`

I tried using the 2 babel plugins that were mentioned in the original ticket, https://babeljs.io/docs/plugins/transform-class-properties/ and https://www.npmjs.com/package/babel-plugin-transform-es2015-classes
However, this error still occurs.

Could someone please help?

**Comment by eugene1g** [comment]
I encountered the same error while using mutations. The solution outlined in #394 worked for me, so I had to replace the call to getFragment for all mutations like this - 
```
export default Relay.createContainer( MyWidget, {
  fragments: {
    widgetInfo: () => Relay.QL`        
        fragment on WidgetInfo {
            label
            # For inner containers, use the default getFragment syntax
            ${WidgetChild.getFragment('widgetInfo')}
            # For mutation classes, use a different syntax to accomplish the same end result
            ${Relay.Mutation.getFragment.call(UpdateWidgetColorMutation, 'widgetInfo')}
        }
    `
  }
})
```

**Comment by jaden-chen** [comment]
@eugene1g, thanks for your help.

Looking at your example, does IE<=10 not complain about this line that you have in your code: `${WidgetChild.getFragment('widgetInfo')}`

If so, it's likely that your Babel config is working in addressing this IE issue. If you could share what Babel plugins you've included, that'll be greatly appreciated!

**Comment by eugene1g** [comment]
My full .babelrc file -
```
{
  "passPerPreset": true,
  "presets": [
    "react",
    "es2015"
  ],
  "plugins": [
    "transform-react-jsx-source",
    "transform-flow-strip-types",
    "jsx-control-statements",
    "transform-object-rest-spread",
    "transform-class-properties",
    "syntax-async-functions",
    [
      "transform-async-to-module-method",
      {
        "module": "bluebird",
        "method": "coroutine"
      }
    ],
    "./_dev/babelRelayPlugin"
  ],
  "env": {
    "development": {
      "plugins": [
        "flow-react-proptypes",
        [
          "babel-plugin-react-transform",
          {
            "transforms": [
              {
                "transform": "react-transform-hmr",
                "imports": [
                  "react"
                ],
                "locals": [
                  "module"
                ]
              }
            ]
          }
        ]
      ]
    }
  }
}
```

babelRelayPlugin.js
```
var getbabelRelayPlugin = require('babel-relay-plugin')
var schema = require('../../backend/data/schema.json')
module.exports = getbabelRelayPlugin(schema.data)
```

**Comment by edvinerikson** [comment]
most likely due to https://babeljs.io/docs/usage/caveats/#classes-10-and-below-

**Comment by jaden-chen** [comment]
Thank you all for the help. I followed @eugene1g 's suggestions to "replace the call to getFragment for all mutations" and it's working for me now.

**Comment by svrcekmichal** [comment]
I fixed it myself with following code on Mutation class
```
  // IE <= 10 workaround URL: https://github.com/facebook/relay/issues/1444
  static getFragment(name) {
    return Relay.Mutation.getFragment.call(MeetingVoteMutation, name);
  }
```
I found it better, because I don't need to handle it outside of Mutation and I need to write it only once for every mutation :)
