### ISSUE TITLE
setvariables child relay.renderer

### ISSUE THREAD

**Issue by proProbe** [facebook/relay#1445]
Hello everyone!

Im currently having some troubles with `setVariables` on a child from the parent via a `ref`. The problem is that the child doesnt fetch new data at all even though `relay.variables` and `props.variables` is set to the new values. My current code:

Parent:
```
<Relay.Renderer
      Container={Feed}
      queryConfig={new FeedRoute({first: this.state.notifications})}
      environment={this.props.environment}
      render={({done, error, props, retry, stale}) => {
                if (error) {
                    ...
                } else if (props) {
                   return (
                     <Feed
                          {...props}
                          onPressUser={this._onPressUser}
                          setRefInParent={(c) => this._feedRef = c}
                          first={this.state.notifications}
                    />
                   );
                } else {
                    return <View style={{paddingTop: 20}}><LoadingIndicator></LoadingIndicator></View>;
                }
      }}
/>
...
onClick = () => {
    this._feedRef.relay.setVariables({first: this.state.notifications + 40})
}
```
Child:
```
const RelayFeed = Relay.createContainer(Feed, {
    initialVariables: {
        first: 1,
    },
    fragments: {
        user: () => Relay.QL`
            fragment on user {
                id
                own_feed {
                  id
                  notifications(first: $first){
                     ....
                  }
                }
            }
        `,
    },
});
```
FeedRoute:
```
import Relay from "react-relay";
import Feed from "./Feed";

class FeedRoute extends Relay.Route {
    static routeName = 'NotificationFeedRoute';
    static paramDefinitions = {
        first: {required: true},
    };
    static queries = {
        user: (Component, variables) => Relay.QL`
            query {
                user {
                    ${Feed.getFragment('user', {first: variables.first})},
                }
            }
        `,
    };
}

export default FeedRoute;
```
I expect this to fetch another `40` notifications to put into the feed. The query doesnt go at all and I get `"STORE_FOUND_ALL"` in `ReadyState`

**Comment by gre** [comment]
```
    this._feedRef.relay.setVariables({first: this.state.notifications + 40})
```

I'm not sure what `state.notifications` is, but it looks like you shouldn't maintain this state yourself as it should just be accessible via `relay.variables.first` right?

**Comment by proProbe** [comment]
@gre I actually had that approach first. It still doesnt work :S

**Comment by josephsavona** [comment]
It isn't immediately obvious what's going on here. It looks like there is some missing code in your example, such as how state.notifications is populated. I would suggest trying to remove any extraneous code and get as simple a repro case as possible. There is likely some detail that needs t be adjusted and which will probably be more obvious with a minimal repro setup.

**Comment by proProbe** [comment]
@josephsavona after sitting with it today, I actually realised that it was a bad implementation on the backend. It basically went like this:
1. user sends a query with `first: 10`
2. backend receives it and start the db-query
3. the db-query had a `limit( args("first") )` (for avoiding fetching the whole db)
4. the cursor and node resolvers interpreted this as `the db only has 10 entries`
5. user tries to fetch more and does a setvariables with `first: relay.variables.first + 10`
6. relay is smart and puts `after: id_of_entry_10`
7. but after only receiving `10 entries` from the db, relay knows that there is no more data to fetch
8. relay skips the fetch as there is no more data to fetch.

I realised that this was actually the problem. Im trying to go around it right now but Im not actually sure what "the way to go" is

**Comment by josephsavona** [comment]
Hmm, it sounds like the issue is in your resolve function. I would double check the implementation (maybe use a unit test to isolate and quickly iterate on that function) and make sure it returns the correct page info.

**Comment by proProbe** [comment]
@josephsavona you are certainly correct. Im trying to read more about this to get a better grasp of it. Im currently looking through https://facebook.github.io/relay/graphql/connections.htm#sec-Reserved-Types. Are there other good sources for this?
