### ISSUE TITLE
Your schema defines a mutation filed 'sportunity'  that takes 0 arguments  

### ISSUE THREAD

**Issue by Kottidev** [facebook/relay#1447]
I need create class Relay.Mutation  to excute this query  graphQL  
`mutation Mutatiton {
  newSportunity(
    input: {
      sportunity:{
        title: "aaa",
        description: "aaa",
        address: {
          country: "France",
          city: "Besançon",
          zip: "25000"
        }
      }
    }
  ){
  	title,
  	description
	}
}`

**in our query we have input argument for mutations.
how can i added input param with Relay.Mutation ?**

schema grapQL mutation : newSportunity(input: newSportunityInput): Sportunity

this is my class Relay.Mutation

`import Relay from 'react-relay';

export default class newActivityMutation extends Relay.Mutation {
    static fragments = {
        activity: () => Relay.QL`
            fragment on Sportunity {
                title
            }
        `,
    };

    getMutation() {
        return Relay.QL`
        mutation {
            sportunity
        }`;
    }
    getVariables() {
        return {
            title: "test"
        };
    }
    getFatQuery() {
        return Relay.QL`
        fragment on Sportunity {
            title,
            id
        }
        `;
    }
    getConfigs() {
        return [{
            type: 'REQUIRED_CHILDREN',
            children: [Relay.QL`
            fragment on Sportunity {
                title,
                id
            }
            `]
        }];
    }
}`

how can i resolve this probleme ?

![mutation](https://cloud.githubusercontent.com/assets/12915009/20345647/6dc2ea08-abf8-11e6-8687-2225538b4697.png)

I just can’t make query graphQL work using Relay

**Comment by nodkz** [comment]
Your mutation code looks correct.

First of all check via GraphiQL your mutation that it has `input` arg. And check that it works.

After that check that you provide the fresh schema file to your `babel-relay-plugin`. Regenerate schema.json and restart/rebuild your app.
