### ISSUE TITLE
Calling setVariables is forcing a refetch from the server instead of using the cached results?

### ISSUE THREAD

**Issue by husterk** [facebook/relay#1448]
I am attempting to render a component multiple times in a table (i.e. one instance of the component per table row). The component requires a Relay variable to be set to determine how to render the contents of the component.

I am setting this variable via a call to `this.props.relay.setVariables` in the component's `componentWillMount` lifecycle event. In my particular case, each of the components end up needing the same set of data from the server so I would expect that the first component to call `this.props.relay.setVariables` would result in a new fetch from the server but each subsequent component in the table would simply use the results of the fetch from the first component since the generated query is exactly the same for each component in the table.

However, what actually happens is that a new fetch is made for each component in the table which is terrible for performance. Is there some way to tell Relay to reuse the original fetch? I thought it was supposed to do this automatically by caching the queries.

FYI... the query is going through the `node` interface and the fragment type is an interface graph type.

This question was also asked on StackOverflow: http://stackoverflow.com/questions/40680185/calling-setvariables-is-forcing-a-refetch-from-the-server-instead-of-using-the-c

**Comment by josephsavona** [comment]
Relay does not currently coalesce identical queries into a single request, which would explain why you're seeing one request per component. One option is to implement such coalescing yourself in the network layer (e.g. keeping a map of query text + variables => request). However, this sounds like an anti-pattern. Why do the components not know their variables until mount?

**Comment by husterk** [comment]
In our current schema, the components rendered in the table (e.g. checklist items) must first query for the set of link types associated with each component and then based on the set of link types we make a determination as to whether or not we plan to load specific child components. Based on this determination we also want to dynamically control the data being queried by Relay / GraphQL since we are conditionally loading the child components.

Each of the child components has a common fragment based on an interface graph type and the data being loaded for this interface graph type is intended to be shared with all of the components in the table (so it should only be loaded once regardless of the number of rows in the table). However, each of the child components only needs a subset of the data available from the interface so we only want to load the appropriate amount of fields from the interface based on the overall set of child components expected to be rendered.

So, for example... if all of our components in the table are found to only need field1 and field2 from the interface type (based on the link types retrieved from the server) we don't want Relay to query for the additional fields on the interface type. However, if even just one of the components in the table also needs field3 then we would want Relay to also get the data for that field as well. Hopefully this makes sense.

I have put together a simplified code example of our fragment structures below for reference. Let me know if you need further details / explanation.

**COMPONENT: Table**
```javascript
// Note: The "Task" type implements the "DataInterface" interface.
fragments: {
  taskInfo: variables => Relay.QL`
    fragment on Task {
      checklistItems {
        ${TableRow.getFragment('checklistItem', variables)}
      }
      ${TableRow.getFragment('dataInterface', variables)}
    }
}
```

**COMPONENT: TableRow**
```javascript
// Note: I am using the lifecycle events of this component to call "setVariables" to update
// the variables once the link types have been loaded and provided to this component via the props.
initialVariables: {
     shouldLoadChildComponent1Fragment: false,
     shouldLoadChildComponent2Fragment: false
   },
fragments: {
     checklistItem: variables => Relay.QL`
        fragment on ChecklistItem{
          linkTypes {
            name
          }
        }
     }`,
     dataInterface: variables => Relay.QL`
       fragment on DataInterface {
         ${ChildComponent1.getFragment('dataInterface', variables).if(variables.shouldLoadChildComponent1Fragment)}
         ${ChildComponent2.getFragment('dataInterface', variables).if(variables.shouldLoadChildComponent2Fragment)}
       }
     }
```

**COMPONENT: ChildComponent1**
```javascript
fragments: {
  dataInterface: variables => Relay.QL`
    fragment on DataInterface {
      field1
      field2
    }
}
```

**COMPONENT: ChildComponent2**
```javascript
fragments: {
  dataInterface: variables => Relay.QL`
    fragment on DataInterface {
      field2
      field3
    }
}
```

**Comment by husterk** [comment]
I was able to work around this issue by moving the logic required to create the "shouldLoadChildComponent1Fragment" and "shouldLoadChildComponent1Fragment" Relay variables up to the Table component which is only rendered once on the page. I then forwarded the variables through the child components as required. This resulted in the data requests that I was expecting but unfortunately adds some data dependencies to the intermediary components that don't actually intend to use either the Relay variables or associated props.

**Comment by voxmatt** [comment]
@josephsavona I'm trying to figure out something in the same vein here. `setVariables` forces a refetch if the specific combination of variables hasn't been fetched before.

Curious if you have any thoughts; I tried to fully articulate my question here:
http://stackoverflow.com/questions/41051401/graphql-relay-filtering-ui

**Comment by josephsavona** [comment]
@voxmatt answered on SO!

**Comment by josephsavona** [comment]
@husterk Thanks again for filing this. I'm not immediately sure what the best approach is here, but the solution you described seems reasonable.

**Comment by voxmatt** [comment]
@josephsavona thanks!

**Comment by wincent** [comment]
Closing this one as it refers to the old `setVariables` API which does not exist in Relay Modern. Now that Relay Modern is out, no development work is being prioritized against the old APIs, so we're better off clearing out the issue tracker of old stuff and focusing on current work. Thanks for the discussion though!
