### ISSUE TITLE
Values being swapped

### ISSUE THREAD

**Issue by aizatto** [facebook/relay#1449]
I have this Relay.QL:

```
      fragment on Viewer {
        topics(locale: $locale) {
          id
          locale
          slug
          topic
          questions { 
            id
            slug
            question
          }
        }
      }
```

When querying GraphQL using GraphiQL, I get the correct results.

When using relay. My `topics.slug` value is over written by the `question.slug`. Is this expected?

**Comment by josephsavona** [comment]
Double check the `id`s of each object: the behavior you're describing is almost always the result of colliding IDs.

**Comment by aizatto** [comment]
I'll check it out. Does this mean object's id in a relay application need to be unique?

**Comment by josephsavona** [comment]
Yup, per the [objeft identification specification](https://facebook.github.io/relay/docs/graphql-object-identification.html).
