### ISSUE TITLE
Publish babel-relay-plugin that depends on graphql 0.8.2

### ISSUE THREAD

**Issue by janicduplessis** [facebook/relay#1451]
The plugin currently depends on graphql 0.6 which can't properly parse schemas generated using graphql 0.8. It would be nice if releases stay somewhat aligned to avoid this.

**Comment by josephsavona** [comment]
@janicduplessis We just updated the plugin to use 0.8.2. We'll try to cut a release sometime soon, but if you're blocked on this check out the version of the plugin on master.

**Comment by gauravtiwari** [comment]
@janicduplessis Fixed in v0.10.0 https://github.com/facebook/relay/commit/cb23da262cc03118281c7fde12bc905e955ef321
