### ISSUE TITLE
Directive \"include\" may not be used on FRAGMENT_DEFINITION.

### ISSUE THREAD

**Issue by jeongsd** [facebook/relay#1453]
i'm use react-relay v0.9.3, graphql v0.7.2 and graphql-relay v0.4.3

components has this fragment:
```js
export default Relay.createContainer(ExampleComponent, {
  initialVariables: {
    show: true,
  },

  fragments: {
    user: () => Relay.QL`
      fragment on User {
        __typename
        ...(if: $show) {
          id
          username
          firstName
        }
      }
    `,
  },
});
```

request payload in chrome dev tool
```graphql
query Queries($id_0:ID!) {
  user(id:$id_0) {
    id,
    __typename,
    ...F1
  }
}
fragment F0 on User @include(if:true) {
  id,
  username,
  firstName
}
fragment F1 on User {
  id,
  ...F0
}
```

Response from server
```json
{
  "errors": [
    {
      "message": "Directive \"include\" may not be used on FRAGMENT_DEFINITION.",
      "locations": [
        {
          "line": 8,
          "column": 21
        }
      ]
    }
  ]
}
```

**Comment by josephsavona** [comment]
Yup! Per the [specification for `@include`](http://facebook.github.io/graphql/#sec--include), this directive is not supported on fragment definitions. If this was allowed then you could have nonsensical GraphQL where the fragment definition had `@include(if: $cond)` and a reference to it had `@skip(if: $cond)`. Instead, put the condition on the fragment spreads.

**Comment by jeongsd** [comment]
thanks response @josephsavona,
so how can i use fragment spreads with `@include`directive in relay createContainer fragment?

i'm use fragment spreads with `@include`like this
```js
Relay.QL`
  fragment on Todo {
    ...@include(if: true){
      complete,
      id,
      text,
    }
  }
`
```

then relay change fragment spreads to fragment definitions
```graphql
fragment F0 on Todo @include(if:true) {
  complete,
  id,
  text
}
fragment F3 on Todo {
  id,
  ...F0,
  ...F1,
  ...F2
}
```

then `FRAGMENT_DEFINITION ` error occur


and fragment spreads with `@include`directive work in 
[relay playground](https://facebook.github.io/relay/prototyping/playground.html#source=%2F**%0A%20*%20Copyright%20(c)%202013-present%2C%20Facebook%2C%20Inc.%0A%20*%20All%20rights%20reserved.%0A%20*%0A%20*%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%20*%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%20*%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%20*%2F%0A%0A%2F%2F%20Welcome%20to%20Relay.%0A%2F%2F%20Allow%20us%20to%20introduce%20you%20to%20the%20four%20elements.%0A%0Aclass%20Hello%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20%2F%2F%20Relay%20will%20materialize%20this%20prop%20based%20on%20the%0A%20%20%20%20%2F%2F%20result%20of%20the%20query%20in%20the%20next%20component.%0A%20%20%20%20const%20%7B%20hello%2C%20world%20%7D%20%3D%20this.props.greetings%3B%0A%20%20%20%20if(!hello)%20return%20%3Ch1%3Ehellow%20undefined%3C%2Fh1%3E%0A%20%20%20%20return%20%3Ch1%3E%7Bhello%20%2B'%20'%20%2B%20world%7D%3C%2Fh1%3E%3B%0A%20%20%7D%0A%7D%0AHello%20%3D%20Relay.createContainer(Hello%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20%2F%2F%0A%20%20%20%20%2F%2F%20This%20GraphQL%20query%20executes%20against%0A%20%20%20%20%2F%2F%20the%20schema%20in%20the%20'schema'%20tab%20above.%0A%20%20%20%20%2F%2F%0A%20%20%20%20%2F%2F%20To%20learn%20more%20about%20Relay.QL%2C%20visit%3A%0A%20%20%20%20%2F%2F%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fapi-reference-relay-ql.html%0A%20%20%20%20greetings%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20...%40include(if%3A%20true)%7B%0A%20%20%20%20%20%20%20%20%20%20hello%0A%20%20%20%20%20%20%20%20%20%20world%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0A%2F**%0A%20*%20%231%20-%20Your%20React%20components%0A%20*%20This%20will%20look%20familiar%20to%20React%20developers.%0A%20*%0A%20*%20To%20learn%20more%20about%20React%2C%20visit%3A%0A%20*%20%20https%3A%2F%2Ffacebook.github.io%2Freact%0A%20*%2F%0Aclass%20HelloApp%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20%2F%2F%20Relay%20will%20materialize%20this%20prop%20based%20on%20the%0A%20%20%20%20%2F%2F%20result%20of%20the%20query%20in%20the%20next%20component.%0A%20%20%20%20return%20%3CHello%20greetings%3D%7Bthis.props.greetings%7D%2F%3E%0A%20%20%7D%0A%7D%0A%0A%2F**%0A%20*%20%232%20-%20Relay%20containers%0A%20*%20Compose%20your%20React%20components%20with%20a%20declaration%20of%0A%20*%20the%20GraphQL%20query%20fragments%20that%20fetch%20their%20data.%0A%20*%0A%20*%20To%20learn%20more%20about%20Relay%20containers%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fguides-containers.html%0A%20*%2F%0AHelloApp%20%3D%20Relay.createContainer(HelloApp%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20show%3A%20true%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20%2F%2F%0A%20%20%20%20%2F%2F%20This%20GraphQL%20query%20executes%20against%0A%20%20%20%20%2F%2F%20the%20schema%20in%20the%20'schema'%20tab%20above.%0A%20%20%20%20%2F%2F%0A%20%20%20%20%2F%2F%20To%20learn%20more%20about%20Relay.QL%2C%20visit%3A%0A%20%20%20%20%2F%2F%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fapi-reference-relay-ql.html%0A%20%20%20%20greetings%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20__typename%0A%20%20%20%20%20%20%20%20...%40include(if%3A%20%24show)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%24%7BHello.getFragment('greetings')%7D%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0A%2F**%0A%20*%20%233%20-%20Relay%20routes%0A%20*%20Define%20a%20root%20GraphQL%20query%20into%20which%20your%0A%20*%20containers'%20query%20fragments%20will%20be%20composed.%0A%20*%0A%20*%20To%20learn%20more%20about%20Relay%20routes%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fguides-routes.html%0A%20*%2F%0Aclass%20HelloRoute%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'Hello'%3B%20%20%2F%2F%20A%20unique%20name%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20%2F%2F%20Here%2C%20we%20compose%20your%20Relay%20container's%0A%20%20%20%20%2F%2F%20'greetings'%20fragment%20into%20the%20'greetings'%0A%20%20%20%20%2F%2F%20field%20at%20the%20root%20of%20the%20GraphQL%20schema.%0A%20%20%20%20greetings%3A%20(Component)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20GreetingsQuery%20%7B%0A%20%20%20%20%20%20%20%20greetings%20%7B%0A%20%20%20%20%20%20%20%20%20%20%24%7BComponent.getFragment('greetings')%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0A%2F**%0A%20*%20%234%20-%20Relay%20root%20containers%0A%20*%20Compose%20a%20Relay%20container%20with%20a%20Relay%20route.%0A%20*%20This%20enables%20Relay%20to%20synthesize%20a%20complete%20query%0A%20*%20to%20fetch%20the%20data%20necessary%20to%20render%20your%20app.%0A%20*%0A%20*%20To%20learn%20more%20about%20Relay%20root%20containers%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fguides-root-container.html%0A%20*%2F%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BHelloApp%7D%0A%20%20%20%20route%3D%7Bnew%20HelloRoute()%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B%0A&schema=%2F**%0A%20*%20Copyright%20(c)%202013-present%2C%20Facebook%2C%20Inc.%0A%20*%20All%20rights%20reserved.%0A%20*%0A%20*%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%20*%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%20*%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%20*%2F%0A%0Aimport%20%7B%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%7D%20from%20'graphql'%3B%0A%0Aconst%20GREETINGS%20%3D%20%7B%0A%20%20hello%3A%20'Hello'%2C%0A%20%20world%3A%20'world'%2C%0A%7D%3B%0A%0A%2F**%0A%20*%20Objects.%0A%20*%20Build%20up%20a%20portrait%20of%20your%20data%20universe%0A%20*%20using%20the%20object%20type.%20Here%2C%20we%20define%20a%0A%20*%20type%20of%20object%20that%20has%20a%20'hello'%20field%0A%20*%20that%20is%20of%20the%20string%20type.%0A%20*%2F%0Aconst%20GreetingsType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Greetings'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20hello%3A%20%7Btype%3A%20GraphQLString%7D%2C%0A%20%20%20%20world%3A%20%7Btype%3A%20GraphQLString%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0A%2F**%0A%20*%20The%20schema.%0A%20*%20Here%20we%20export%20a%20schema%20that%20offers%20one%20root%0A%20*%20field%20named%20'greetings'%2C%20and%20a%20method%20to%0A%20*%20resolve%20its%20data.%0A%20*%0A%20*%20To%20learn%20more%20about%20writing%20GraphQL%20schemas%20for%20Relay%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Fgithub.com%2Fgraphql%2Fgraphql-relay-js%0A%20*%2F%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20greetings%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20GreetingsType%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20Here%20we%20define%20a%20resolver%20that%20returns%0A%20%20%20%20%20%20%20%20%2F%2F%20the%20data%20defined%20above.%20Were%20this%20schema%0A%20%20%20%20%20%20%20%20%2F%2F%20executing%20on%20the%20server%20side%2C%20you%20could%0A%20%20%20%20%20%20%20%20%2F%2F%20write%20a%20resolve%20method%20that%20fetches%0A%20%20%20%20%20%20%20%20%2F%2F%20live%20data%20from%20a%20database.%0A%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20GREETINGS%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A)

**Comment by josephsavona** [comment]
I see. What's happening here is that Relay is converting the anonymous fragment to a fragment definition, on which the directive is not allowed. Instead of moving the directive into an anonymous fragment, I would recommend moving it to where the fragment is referenced: have the parent component conditionally fetch the fragment if it isn't required.

**Comment by awitherow** [comment]
@jeongsd did you get something working for such an approach?

**Comment by josephsavona** [comment]
@awitherow The code snippet you posted unfortunately won't work:

```
fragments: {
    viewer: variables => variables.one ? ... : ... ; // <-- not supported
}
```

The `variables` object is a placeholder for the values, not the actual values. So `variables.one` will always be truthy so the first branch should always be taken (also, the function will be executed only once and its result memoized). The right approach here is probably for Relay not to print `@include` or `@skip` when the value is a constant. This can be fixed in `printRelayOSSQuery()` if you'd like to send a PR!

**Comment by awitherow** [comment]
Right that is what I noticed, that the variables objects only have some type information. Was just a theoretical 'what I would like' implementation ;) Good to know about the intracencies of how the fragment function call works though 👍 

I will look into the `printRelayOSSQuery()` and shoot you any questions I have on how to implement it.

**Comment by awitherow** [comment]
It seems that this code is within the 'classic' implementation of relay though... will it be even worth implementing it if Relay is attempting to switch to this modern version?

Or will functions within classic be used within the modern approach at all?

**Comment by josephsavona** [comment]
@awitherow This use-case is supported in Relay Modern (including in compat mode - details on all this coming soon). But in the meantime, it seems reasonable to fix this in Relay Classic, the module I mentioned.
