### ISSUE TITLE
Fragment "F1" cannot be spread here as objects of type "Node" can never be of type "Viewer".

### ISSUE THREAD

**Issue by maxpolski** [facebook/relay#1454]
I got this error when I tried to make container wit fragment in which one field depends on another.

I have container like this 

```
export default createContainer(Component, {
  initialVariables: {
    prop1: '',
    prop2: '',
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        filed1(first: 10) {
          edges {
            node {
              id
              name
            }
          }
        }
        field2(prop1: $prop1, prop2: $prop2) {
          ${AnotherContainer.getFragment('fragmentFromAnotherContainer')}
        }
      }
    `,
  },
});
```

The case is that I'm trying to refetch the second field('field2'), after I got some data in my Container from user. To make this I call 'this.props.relay.setVariables({ prop1: 'foo', prop2: 'bar' })', but request fails with aforementioned error.

**Comment by maxpolski** [comment]
That is my false, because of some kind of missunderstanding.

**Comment by josephsavona** [comment]
Thanks for asking and following up.

> fragment in which one field depends on another.

This is generally an indication that the schema does not reflect the needs of the client and should be changed. If field B depends on the output of field A then it should be a subfield. So instead of ` { fieldA, fieldB }` the schema should probably be `fieldA { fieldB }`.

**Comment by maxpolski** [comment]
@josephsavona, thanks for clarification
