### ISSUE TITLE
When will we have `Persisted Query` support in js version of Relay?

### ISSUE THREAD

**Issue by luckydrq** [facebook/relay#1455]
Hi, i have recently refactor our back-end service using GraphQL which is a really awsome alternative against REST. And as i dive into it deeper, i find life can be easier if we use relay in the web front end. So i start to search more staff about relay and finally found this [awsome talk](https://www.youtube.com/watch?v=1Fg_QtzI7SU&index=4&list=PLpi1lPB6opQzSSOQU8JQLExuP1JUXPtmA&t=1199s) published recently which mentioned `Persisted Query` that help save query size. It is definitely a great feature for mobile app. But our product is mainly for PC users, so when can we use this awsome feature in web front-end and is there any example code to show a best practice? Thank you!

**Comment by wincent** [comment]
We don't have a specific release date as such, but we are making progress towards having persisted query support available in Relay. The new Relay core and APIs are functional and complete enough that we've been able to run tests in production, and we've been starting to ship pieces to the `master` branch with more to come over the coming weeks/months. As such, your best bet at this point is to watch `master` and keep an eye on [our meeting notes](https://github.com/facebook/relay/tree/master/meta/meeting-notes) where we publish updates from our team syncs.

In the meantime, there is no example code, but there will be (and documentation) by time this gets fully merged and rolled out.

Before I close this, let me point out [this RFC PR](https://github.com/graphql/express-graphql/pull/109) to `express-graphql`, which shows how one might implement persisted query support on the server side.

**Comment by wincent** [comment]
And I forgot to add: thanks for asking the question, and for your patience in waiting for a response.

**Comment by luckydrq** [comment]
Thanks!

**Comment by yusinto** [comment]
I've written a [custom relay compiler](https://github.com/yusinto/relay-compiler-plus) which does this. It also compiles graphql-js schema directly into relay query files with persisted queries. Let me know if it's useful!
