### ISSUE TITLE
Single query error fails whole system

### ISSUE THREAD

**Issue by unirey** [facebook/relay#1456]
Im trying to use GraphQL and Relay `errors` to let Relay do all the heavy lifting and to spare myself from writing duplication error handling code. Everything was beautiful until I had to use two separate queries.

This issue occurs when cache is cold (page refresh, navigation from other site _etc_).

**Situation:** two components, parent `App` and child `Posts`. Both have their own Relay Components and make two separate queries. `App` has it's own query to get current user data in order to make sure that every single page in app gets the user data (even if anonymous) if navigated to with cold cache.

`App` query is successful, `Posts` query return an error (has `errors` array, for example: `post doesn't exist`).

**Expected result:** there are two different queries, Im expecting the successful `App` query to resolve as expected, so that I could  show `post with that ID doesn't exist` or something similar for child component.

**What really happens:** Relay Component that wraps `App` makes a successful query and even adds the record to store but if any of the children queries return error, it never injects the record to `App` component `props`.

Is this supposed to happen? If one query gets an error, Relay halts the whole process or something?

---

This is using [react-router](https://github.com/ReactTraining/react-router) and [react-router-relay](https://github.com/relay-tools/react-router-relay) but I think these shouldn't be related to this issue.

### Code:

```jsx
// Routes

<Route
    path="/"
    component={App}
    queries={ViewerQuery} // This query returns successful response

    render={appRender}   {/* <- Im using render callback to render <App /> component */}
>                        {/* with it's data, even if any of the children gets an error */}

    <Route
        path="/posts"
        component={Posts}
        queries={ViewerQuery}  // This query returns an error
    />

</Route>
```

```jsx
// Relay Renderer render callback

const appRender = ({ done, error, retry, stale, props, element }) => {

    console.log(done)  // never true if any of the children has an error
    console.log(props) // ALWAYS null if any of the children has an error

    if (error) {
        return React.cloneElement(element, { ...props, error: error.source })
    }

    return undefined
}
```

```jsx
// ViewerQuery

const ViewerQuery = {
    viewer: () => Relay.QL`query { viewer }`,
}
```

```jsx
// ReadyStateEvents

type: "NETWORK_QUERY_START"
type: "CACHE_RESTORE_START"
type: "CACHE_RESTORE_FAILED"
type: "NETWORK_QUERY_ERROR"
```

**Comment by phillipj** [comment]
@unirey I'm also trying to wrap my head around handling errors in a good way. Since you closed this issue, did you find any tricks you want to share?

**Comment by mvgijssel** [comment]
I'm also interesting in your findings!
