### ISSUE TITLE
Add support for partial "idFetcher()" inside queries 

### ISSUE THREAD

**Issue by shakaIsReal** [facebook/relay#1457]
I think it'd be cool to only get the minimum data to resolve a global id to an object. Use case: getting new `ships` using cursor. 

```
const { nodeInterface, nodeField } = nodeDefinitions(
  (globalId) => { 
    const {type, id} = fromGlobalId(globalId);
    if (type === 'Faction') {
      return getFaction(id);
    } else if (type === 'Ship') {
      return getShip(id);
    } else {
      return null;
    }
  },
  (obj) => { 
    return obj.ships ? factionType : shipType;
  }
);
```
`getFaction()` could return many object (id, name, ships).. But we don't need all of them when we're interested in `obj.ships` and `obj.id`. There's no need to load the data we already have on the client or don't need. 

Therefore relay could send a partial argument. `partial: true` 

```
"query StarWarsApp_FactionsRelayQL($id_0:ID!) {
  node(id:$id_0, partial: true) {    //// ----> here 
    ...F1
  }
}
fragment F0 on Ship {
  id,
  name
}
fragment F1 on Faction {
  id,
  _shipsd0pxV:ships(after:"YXJyYXljb25uZWN0aW9uOjI=",first:2) {
    edges {
      node {
        id,
        ...F0
      },
      cursor
    },
    pageInfo {
      hasNextPage,
      hasPreviousPage
    }
  }
}"

```
 
And in `idFetcher` we could do this, 

```
 if (type === 'Faction' && partial) {
      return getShipsInFaction(id);   // returns id and [ ships ]
    }  else if (type === 'Faction') {
      return getFaction(id);
    } 

```

Sure people can encode this inside `globalIdField`. But adding this change and documenting it to people can prevent data over fetching

 What do you think, is this change worth it? Or it just adds complexity? 

@leebyron  @wincent

**Comment by josephsavona** [comment]
I don't understand the use case, could you clarify what behavior you're currently seeing and what you'd like to achieve? Note that Relay/GraphQL will only fetch the fields you ask for, so it isn't clear what over/fetching you're referring to. The fragment in your example contains the `ships` and id field on Faction, so only those fields will be fetched. Your `getFaction` method shouldn't load fields preemptively; instead load them when each field is specifically requested (i.e. let the executor call your resolve function for each field and load it only then).

**Comment by shakaIsReal** [comment]
Thanks, lets say I want to get users `id, name, age, gender, posts`. 
`posts` will be fetched using a cursor i.e. `posts(first:10)`

 My query type would look like this: 

```
const queryType = new GraphQLObjectType({
  name: 'Query',
  fields: () => ({
   profile: {
      type: new GraphQLList(UserType),
      args: {
        username: {
          type: new GraphQLList(GraphQLString),
        },
      },
      resolve: (root, {username}) =>  getUser(username),
    },
    node: nodeField,
  }),
});
```
And nodeDefenitions: 

```
const {nodeInterface, nodeField} = nodeDefinitions(
  (globalId) => {
    const { type, id } = fromGlobalId(globalId);
    if (type === 'User') {
      return getUser(id);  
    }  
  },
  (obj) => {
     if(obj instanceof User) { return UserType; }  
  }
);
```
 And `UserType` will get the posts. 

```
... fields for: age, gender, name that return root object 

posts: { 
type: postConnection, 
args: connectionArgs, 
resolve: (_, args) => sql.query('select text from posts where id > $1 limit $2', [args.after, args.first])
}

```
The problem is that `getUser()` will fetch `name`, `gender` and `age`. So if I want to get more posts from a specific user, I will have to ask for unnecessary information inside `idFetcher()`. When really all I need is user's `id`. 

  
> (i.e. let the executor call your resolve function for each field and load it only then 

Are you saying to query the database inside each field's resolver function. Like this? 

```
age: { 
type: GraphQLInt, 
resolve: (root, args) => sql.query('select age from users where id = $1', [root.id])
}

... other fields

```

But this would be inefficient for the server.  Sorry if I misunderstand something, I am used to REST...
I feel like I need to create two separate function one for the query `getUser()` and one for idFetcher: `getUserId()` where a new constructor (User) with id will be created.

**Comment by josephsavona** [comment]
> Are you saying to query the database inside each field's resolver function. 

Yup! Not doing this - loading field pre-emptively implies overfetching in some cases (as you've seen). SQL queries to load individual properties are typically quite fast, and the overhead of making more queries can be offset by avoiding overfetching. I would recommend trying this approach and seeing how it performs (don't just assume it will be slow). 

Check out the `dataloader` npm module to cache data during query execution (to avoid making the same SQL query twice). You may also find https://github.com/stems/join-monster helpful. 

I'm going to close this issue since it's an answered question, but feel free to continue the discussion here or ask for more info at facebook/graphql-js

**Comment by shakaIsReal** [comment]
@josephsavona thank you

**Comment by shakaIsReal** [comment]
@josephsavona What's the motivation of fetching the `id` from the database in `nodeDefenitions`? We already know the `id` from the global object.. Here's an example from join-monster https://github.com/stems/join-monster/blob/master/example/schema-relay-paginate-2/Node.js#L18 

Thanks.

**Comment by josephsavona** [comment]
@shakaIsReal I'm not sure, `join-monster` is a third-party GraphQL library. I'd suggest asking via Join Monster's GitHub page, it's definitely a good question.
