### ISSUE TITLE
Invalid Graphql query when using a Json GraphQLType

### ISSUE THREAD

**Issue by legomind** [facebook/relay#1463]
This GraphQL fragment:

```js
const InventoryItemsContainer = Relay.createContainer(InventoryItems, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on viewer {
        inventoryItems(first: 50, where: { retailer: "TestRetailer"  } ) {
          edges {
            node {
              id,
              description,
              retailer,
              price,
            }
          }
        }
      }
    `,
  },
})
```

results in the following query:

```graphql
query Index {
  ammobot {
    ...F0
  }
}
fragment F0 on Ammobot {
  _inventoryItems1OGGBo:inventoryItems(first:50,where:{"retailer": "TestRetailer"}) {
    edges {
      node {
        id,
        description,
        retailer,
        price,
      },
      cursor
    },
    pageInfo {
      hasNextPage,
      hasPreviousPage
    }
  }
}
```

and that results in the following error:

```
Syntax Error GraphQL request Expected Name, found String "retailer"
```

the following query works just fine (notice the missing quotes from the `retailer` key)
```graphql
query Index {
  ammobot {
    ...F0
  }
}
fragment F0 on Ammobot {
  _inventoryItems1OGGBo:inventoryItems(first:50,where:{retailer: "TestRetailer"}) {
    edges {
      node {
        id,
        description,
        retailer,
        price,
      },
      cursor
    },
    pageInfo {
      hasNextPage,
      hasPreviousPage
    }
  }
}
```

**Comment by josephsavona** [comment]
Thanks for reporting this. What version are you on? The latest release should handle input objects such as this. One possible workaround is to use a variable for the value: `where: $query`, and `initialVaribles: {query: {retailer: "..."}}`

**Comment by josephsavona** [comment]
Related: what is the type of the `where` argument? Is it an input object or a custom scalar type? Sounds like the latter and we need to handle custom scalers better.

**Comment by legomind** [comment]
Version:
```
>>npm ls react-relay                                                                                                            
ammobot@1.0.0 /Users/coryt/projects/ammobot
└── react-relay@0.9.3
```
 I am using a custom scalar type from [graphql-sequelize](https://github.com/mickhansen/graphql-sequelize/blob/master/src/types/jsonType.js)

**Comment by josephsavona** [comment]
Got it. The plugin checks if an argument's type is an instanceof GraphQLScalar type, but should probably check for the specific built-in scalers instead. I'll put up a fix later today.

**Comment by legomind** [comment]
Thanks. If you can't get to it, I can submit a PR with a little guidance.

**Comment by legomind** [comment]
@josephsavona Thanks for the suggested workaround, but unfortunately using variables results in exactly the same query.

**Comment by josephsavona** [comment]
@legomind Yeah, the workaround was worth a try. Thanks for your patience, I just pushed a PR that fixes this.

**Comment by josephsavona** [comment]
@facebook-github-bot import

**Comment by xyy94813** [comment]
I got same problem in relay v10.0.1

```graphql
fragment MyCard_data on MyModel {
      id
      disablements(before: null, first: 30, q: { effecting: true }) {
        nodes {
          id
        }
   }
}
```
