### ISSUE TITLE
invalid value when entities with the same ID 

### ISSUE THREAD

**Issue by chungwong** [facebook/relay#1465]
Considering this response from Graphql
A **Viewer** has many **Products** and each **Products** has many **Batches**.

When two **Products** have to same **Batch**(with the same ID), but the **status** **value** in each node is different. 
The problem is that when **Relay** parses this response, it treats the two Batch nodes the same, the **status** value will become True for the first Batch node(don't know why it is not False)

Is this an expected behaviour? 

```json
{
  "data": {
    "viewer": {
      "_products4xK7qU": {
        "edges": [
          {
            "node": {
              "id": "U2hlZDoy",
              "_batches2P5Ekw": {
                "edges": [
                  {
                    "node": {
                      "id": "QmF0Y2g6MQ==",
                      "status": false
                    }
                  }
                ]
              }
            }
          },
          {
            "node": {
              "id": "U2hlZDox",
              "_batches2P5Ekw": {
                "edges": [
                  {
                    "node": {
                      "id": "QmF0Y2g6MQ==",
                      "status": true
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by nodkz** [comment]
Yes, this is expected behavior.
Internally Relay construct a flat cache by global ids.  So when it gets first batch it save it to cache  with status false. When he reads second record, it found existed batch by id and update value to true. As result both of your components will receive status true.

So you should provide different global ids for your batches.

**Comment by chungwong** [comment]
Thank you for the confirmation, I ended up making globalIdField() to return an alternative ID conditionally.

**Comment by kassens** [comment]
One of the fundamental assumptions of Relay is that objects with the same ID are the same object, therefore all fields should be the same no matter what way the object was fetched. Additionally, it should be possible to refetch the object using `node(id: $id)` and retrieve the same values unless the object was modified in the meantime. If you have additional information that depends on the connection from parent to the nodes of a connection (like the status here), you might want to put that data on the `edge` of the connection.
