### ISSUE TITLE
RANGE_DELETE on a specific fragment

### ISSUE THREAD

**Issue by proProbe** [facebook/relay#1466]
Hello!

Im currently stumbling on a problem where I have multiple `same named` connections that is used in the application. During a mutation, Im trying to `RANGE_DELETE` an `object` only from a specific connection and have currently no idea how that should be done. Right now, its deleting the `object` in all connections which is not ideal. My schema kinda looks like this for reference:

```
fragment on Viewer {
                id
                events(first: $first) {
                    edges {
                        node {
                           ...
                            }
                        }
                    }
               ${EventsList1.getFragment("viewer")
               ${EventsList2.getFragment("viewer")
}
```
where `EventsList1` and `EventsList2` both have similar fragments as the one above with an `events`-connection.

Is it possible to example only `RANGE_DELETE` from EventsList1? My current config looks like this:
```
            {
                type: 'RANGE_DELETE',
                parentName: 'viewer',
                parentID: 1,
                connectionName: 'events',
                deletedIDFieldName: 'event_id',
                pathToConnection: ['viewer', 'events'],
            },
```
with a fatquery:
```
    getFatQuery() {
        return Relay.QL`
            fragment on PopEventPayload @relay(pattern: true){
                event_id
                viewer {
                    events
                }
            }`;
    }
```

Thanks in advance!

**Comment by josephsavona** [comment]
Do both events fields have the same arguments? If not you can probably target which range to delete from via the exact arguments. If yes (same args) then it isn't as straightforward: my first thought is to use local state for now (longer-term we're working on an updated mutation API that addresses this use case).

**Comment by yachaka** [comment]
@josephsavona This is exactly what I'm trying to achieve in an issue I opened earlier (delete from a connection with specifics arguments). It might be dead simple but I can't seem to find the syntax ; [related issue](https://github.com/facebook/relay/issues/1462), for when you have some time.

**Comment by proProbe** [comment]
@josephsavona So if the arguments are correctly inserted, it should update the correct `fragment`? I'll try this out! The other method with local state sounds unfamiliar for me. How would that actually look like?

**Comment by proProbe** [comment]
how would you actually send in params to the mutation for it to update the correct fragment? Something like this doesnt seem to work:
```
getVariables() {
        return {
            event_id: this.props.event_id,
            first: 15,
        };
}

getFatQuery() {
        return Relay.QL`
            fragment on PopEventPayload @relay(pattern: true){
                event_id
                viewer {
                    events(first: $first)
                }
            }`;
    }
```

**Comment by proProbe** [comment]
@josephsavona any information on the question I have above? Sorry for bothering you :) just not sure on how to do the proposed solution

**Comment by wincent** [comment]
The old mutations API is no longer being actively worked on or supported, and Relay Modern is now out, so I'm going to close this one in order to keep the issue tracker focused on the stuff that is currently being worked on. Thanks!
