### ISSUE TITLE
onSuccess / onFailure callbacks are never called

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/relay#1467]
The `onSuccess` nor `onFailure` callbacks seem to never be called in my React Native app when I do mutations.

I have the following component:

```js
export default class Login extends Component {
  login() {
    const payload = {
      email: '<YOUR_EMAIL_HERE>',
      password: '<YOUR_PASSWORD_HERE>'
    }
    Relay.Store.commitUpdate(new LoginMutation(payload, {
      onFailure: (transaction) => {
        console.log(`Error`)
      },
      onSuccess: (response) => {
	console.log(`Success`)
      },
    }))
  }
  render() {
    // a login button
  }
}
```

The LoginMutation is like this:

```js
import Relay, { Mutation } from 'react-relay'
export default class extends Mutation {
  getMutation() {
    return Relay.QL`
      mutation {
        login
      }
    `
  }

  getVariables() {
    return {
      email: this.props.email,
      password: this.props.password,
    }
  }

  getFatQuery() {
    return Relay.QL`
      fragment on LoginPayload {
        token
      }
    `
  }

  getConfigs() {
    return []
  }
}
```

I use [graphql-relay](https://github.com/graphql/graphql-relay-js) for the server implementation.

When I do the same mutation through GraphiQL, it totally works and returns a token.
```js
mutation Login($input_0:LoginInput!) {
  login(input:$input_0) {
    clientMutationId
    token
  }
}

// variables
{
  "input_0": {
    "clientMutationId": "0",
    "email": "<YOUR_EMAIL_HERE>",
    "password": "<YOUR_PASSWORD_HERE>"
  }
}
```

Is this an issue with my implementation or am I missing something regarding compatibility with React Native, as I haven't seen many mutations for React Native apps.

**Comment by josephsavona** [comment]
Ah! Your code is *so* close - the callbacks are the second argument to `applyUpdate`, not to the mutation constructor ([docs](https://facebook.github.io/relay/docs/api-reference-relay-store.html#commitupdate-static-method)). So:

```
Relay.Store.commitUpdate(
  new LoginMutation(payload), 
  {onSuccess, onFailure}
);
```
