### ISSUE TITLE
Question: how to handle layouts (or dynamic components)?

### ISSUE THREAD

**Issue by vladar** [facebook/relay#147]
I have following tree of React components:

```
Layout
    -> Content
```

And `Content` is resolved at runtime (say page component depending on URI). I could potentially put Relay RootContainer in `Layout.render() ` method, but `Layout` has data requirements on itself.

Is it possible to have several nested `RootContainers`? Or how would you approach this?

**Comment by josephsavona** [comment]
It is possible to have nested `<RelayRootContainer>`s, but this would incur multiple round trips. However, the case that you're describing is similar to the problem of nested routes - have you looked at react-router? That in combination with https://github.com/devknoll/relay-nested-routes would allow fetching all the data for the Layout and Conent. 

See also @cpojer's [great blog post about this topic](https://medium.com/@cpojer/relay-and-routing-36b5439bad9).

**Comment by vladar** [comment]
Very helpful, thanks!

I realized that `renderFetched` method of RootContainer is probably all I need for my scenario. In my case Content knows about it's layout, so it may include Layout's data requirements.

Then I can have one RootContainer:
```javascript
<Relay.RootContainer
  Component={Component}
  renderFetched={(data) => Component.renderLayout(data) />}
  route={route}
/>
```
Where `Component.renderLayout(data)` will just do:
```javascript
<Layout ...data><Content ...data></Layout>
```

**Comment by vladar** [comment]
Actually it seems to be impossible to do yet because of #154
