### ISSUE TITLE
Relay query builder losing field aliases in fragments?

### ISSUE THREAD

**Issue by jaredmcdonald** [facebook/relay#1472]
Hey,

I've got a use case where my schema has a union type whose subtypes have fields of the same name. These fields have different types, though--in one type in the union, the field is a non-nullable string, in the other, it's a nullable string. The way to get around this in GraphQL is to alias one of the fields to another name, which works:

```graphql
{
  home {
    content {
      ... on URLRequired {
        url
      }
      ... on URLNotRequired {
        somethingElse: url
      }
    }
  }
}
```

When I do the same thing inside Relay fragments, however, the compiled query that is sent doesn't have the alias (which ends up as a GraphQL error, because we're querying for fields with the same name but a differing type).

I've got a (fairly) minimal case to reproduce it [here](https://github.com/jaredmcdonald/relay-alias-bug-example)... all of the client code is in [`src/client/index.js`](https://github.com/jaredmcdonald/relay-alias-bug-example/blob/master/src/client/index.js), and the GraphQL schema is in [`src/server/schema.js`](https://github.com/jaredmcdonald/relay-alias-bug-example/blob/master/src/server/schema.js). Essentially [this line](https://github.com/jaredmcdonald/relay-alias-bug-example/blob/master/src/client/index.js#L27) ends up without an alias when the query is sent.

Let me know if I can clarify anything...  I've poked around and can't find anything about this being intentional, though if it is we can probably just modify our schema to fix it.

Thanks!

**Comment by nodkz** [comment]
@josephsavona I can confirm this. On the latest version 0.10.0 of react-relay I got the same problem.

Babel-relay-plugin converts correctly fragment fields with alias option, but query sended without alias.

**Comment by itajaja** [comment]
Same problem here

**Comment by wincent** [comment]
Closing out issues pertaining to the Relay Classic API, as Relay Modern is now out with an entirely different query construction process based on a new compiler. No further work is being done on the old APIs, plug-in, or runtime, so we're better off clearing out the issue tracker to keep it focused on current work. Thanks!
