### ISSUE TITLE
Loading more data from root query 

### ISSUE THREAD

**Issue by shakaIsReal** [facebook/relay#1476]
@josephsavona  I have a case where I want to search data and load more afterwards (when user scrolls)
My first thought was to call a query `search(query:"something", first:10)`, before component renders. But since I want to  be able to load more data, I'll need to use `setVariables()`. This would cause relay to create a `node(id:...)` query. Since I don't have `id` in my case, here are some ideas: 

1. Use a mutation, but how would you load more data using a mutation? 
2. Implement custom logic, and modify relay store 
3. Use `viewer` field, so graphql understands `node` queries by using user's id. 

How should I solve this?

**Comment by josephsavona** [comment]
You don't strictly need a `node` field in order to load more data in Relay. Relay tracks how records without an `id` were fetched (the nearest ancestor with an id, and the path from that record to the id-less record). It uses this to construct queries when you call `setVariables`. I would expect that your use-case would "just work".

**Comment by shakaIsReal** [comment]
@josephsavona Sorry for not being clear the first time ( but that was helpful too :D )
What I meant was: 

Here's my Route query 

```
query SearchQuery {
  search(query: "something", first: 10)
} 
```
And some component would require data 

```
fragment SearchFragment on SearchQuery {
  
...on User { id, name }

}
```

How can fetch more data (invoke `search()` query) in this case ?

**Comment by shakaIsReal** [comment]
@josephsavona I also looked at https://gist.github.com/vslinko/3f877c2415464ecc7af6. 
Should pagination logic live in the Route? The example cited, uses `viewer` field as the stating point and has fragments such as `search` linked to it. Yet, I hope there's a better way to do it.

**Comment by josephsavona** [comment]
You should be able to load more data from the component with `setVariables`. Note, however, that Relay doesn't currently support root fields that take multiple arguments - so you would just have to wrap the `search` field under a viewer field.

**Comment by shakaIsReal** [comment]
So for this kind of cases, you suggest making a `viewer` field that links to `SearchType`, and `SearchType` would have a `search` field? But what if the number of these cases increases, then there must be a union type of some kind that resolves to a specific type, right?

**Comment by josephsavona** [comment]
The `viewer` field would have be an ObjectType (named for example "Viewer"), then put root fields there. Check out the [Learn Relay guide](https://learnrelay.org/queries/what-is-a-query#the-node-and-viewer-fields) for more context.

**Comment by shakaIsReal** [comment]
Are you going to support "root fields"? `viewer` field seems like a remnant (http://stackoverflow.com/questions/39938560/graphql-viewer-for-mutations/39939747#39939747)
I already got authorisation (using `context`), and I'll only need `viewer` field for executing queries (such as `search`). Is this the recommended approach anyway?

**Comment by wincent** [comment]
Closing this one now that Relay Modern is out (and yes, it does support arbitrary root fields, unlike the old Relay). Thanks for the discussion!
