### ISSUE TITLE
Relay.commitUpdate Callbacks not being called

### ISSUE THREAD

**Issue by Jtmaca9** [facebook/relay#1478]
```js
const onSuccess = () => {
      console.log('Success');
    };
Relay.Store.commitUpdate(new CreateAccountMutation({ user: this.state.input }, { onSuccess }));
```

The onSuccess callback used to work on our system. Has recently stopped being called across the whole site. We are using a custom network layer, but has not been changed since it was originally working.

**Comment by josephsavona** [comment]
@Jtmaca9 Thanks for filing an issue, someone else just made the same mistake. See my answer at https://github.com/facebook/relay/issues/1467#issuecomment-265067137
