### ISSUE TITLE
getPendingTransactions only works on records with optimistic updates

### ISSUE THREAD

**Issue by acruis** [facebook/relay#1481]
From the [method comments](https://github.com/facebook/relay/blob/17096c3f22fbd98d0b4ace26762917e6c6a54832/src/store/RelayStoreData.js#L215) for `RelayStoreData.getClientMutationIDs`, it seems like `getPendingTransactions` only retrieves transactions for records which have explicit optimistic updates, and from actual mutation usage, this does seem to be the behaviour.

I'm wondering if this is actually intended, because the [Relay docs](https://facebook.github.io/relay/docs/guides-mutations.html#optimistic-updates) on optimistic responses don't seem to suggest this. If this was intended behaviour, then maybe we should update the docs to include this in?

**Comment by yuzhi** [comment]
I don't think I completely understood what you are suggestion. Only optimistic records can have pending transactions, which are waiting on a server response. Once the server response comes back, it is update in the store and the record is no longer pending. We don't really know what nodes might change soon in the server response besides what was included in the optimistic responses.

**Comment by acruis** [comment]
I think if the user is not familiar with how Relay transactions work, they would expect you to also mark a record whose ID is specified under `FIELDS_CHANGE` as "pending".

**Comment by yuzhi** [comment]
I see. Feel free to put up a PR where you think this will be helpful.

**Comment by wincent** [comment]
The old mutations API is no longer being actively worked on or supported, and Relay Modern is now out, so I'm going to close this one in order to keep the issue tracker focused on the stuff that is currently being worked on. Thanks!
