### ISSUE TITLE
Variables not accessible in nested component

### ISSUE THREAD

**Issue by andricicezar** [facebook/relay#1483]
I have the following situation:
- generated query is correct
- response is correct and includes the data requested by the nested component
- nested component does not get the requested data on via props

The problem appeared after I created a connection between `Team` and `childs`. Maybe this is not how I am supposed to do it..

**Versions:**
React 15.4.1
Relay v0.10.0

**My code**:
```JavaScript
  let Child = ({
    child
  }) => {
    console.log(child);      // Object {__dataID__: "24"}
    console.log(child.id);   // undefined 

    return (<div></div>);
  };

  Child = Relay.createContainer(Child, {
    fragments: {
      child: () => Relay.QL`
        fragment on Child {
          id
        }
      `,
    }
  });

  let Container = ({
    team
  }) => {
    console.log(team);        // Object {__dataID__: "2362", id: "2362", childs: Object}
    console.log(team.childs.edges[0].node.id);      // 24
    const childs = team.childs.edges.map(edge => edge.node);
    const childsHtml = childs.map((child) => (
      <Child child={child} key={child.id} />
    ));

    return (<div>{childsHtml}</div>);
  }

  return Relay.createContainer(Container, {
    fragments: {
      team: () => Relay.QL`
        fragment on Team {
          id,

          childs(first: 20) {
            edges {
              node {
                id,
                ${Child.getFragment('child')}
              }
            }
          }
        }
      `,
    }
  });
```

**Comment by andricicezar** [comment]
Can you tell me how can I solve this problem? Can I provide more information? Thank you

**Comment by andricicezar** [comment]
I don't know how, but this problem fixed itself. Maybe it was webpack's cache involved or browser's cache?

**Comment by josephsavona** [comment]
@andricicezar thanks for following up here. Everything looked right, so a configuration or caching issue seems likely. Enjoy using Relay!
