### ISSUE TITLE
Auto-expanding console groups containing errors

### ISSUE THREAD

**Issue by MatthewHerbst** [facebook/relay#1484]
Would you be open to a PR that caused the Mutation console groups to default to expanded instead of collapsed if they contain an error? Often there are errors/warnings hiding with them, but only by manually expanding all the groups/sub-groups are they found.

**Comment by josephsavona** [comment]
Hmm. In general we try to avoid spamming the console as much as possible. Failed requests already display in red, so I think we'd prefer continuing to default to the content collapsed.

**Comment by MatthewHerbst** [comment]
I think my argument though is that showing it as red is useless if the user doesn't see it, and sometimes to see it requires expending multiple levels of groups without actually knowing what half of it means. Maybe a compromise could be a warning under the root group saying it contains an error and to expand them for more info (if there is an error).

**Comment by josephsavona** [comment]
I see. It might help if you could post a screenshot (text version of what it would look like on console is fine too) of what you'd like it to look like to help ground the discussion.

**Comment by MatthewHerbst** [comment]
Sure. So, right now, a successful `FIELDS_CHANGE` update mutation looks something like:

<img width="373" alt="screen shot 2016-12-21 at 1 59 40 pm" src="https://cloud.githubusercontent.com/assets/1287375/21407714/c8c6d628-c785-11e6-9afc-28b0efd0d53b.png">

(Further expansion of groups just gives the actual data.) Let's say there's an error in the `FIELDS_CHANGE`:

<img width="288" alt="screen shot 2016-12-21 at 2 02 12 pm" src="https://cloud.githubusercontent.com/assets/1287375/21407782/1a517bba-c786-11e6-8fc4-47c7410b66c7.png">

Wait, where is it? ...

<img width="613" alt="screen shot 2016-12-21 at 2 01 54 pm" src="https://cloud.githubusercontent.com/assets/1287375/21407788/248e632c-c786-11e6-9e94-f738c162b0cd.png">

Found you! In more complicated mutations, that could be a lot of manual expansion (if you even realize there is an error in there in the first place)! Let's help the user out:

Maybe a message along the lines of:

<img width="662" alt="screen shot 2016-12-21 at 2 05 51 pm" src="https://cloud.githubusercontent.com/assets/1287375/21407886/9ec0e728-c786-11e6-940b-0ec9194d5f23.png">

Though personally I would just prefer the groups to be auto-expanded to the error, and I think most developers would agree with that sentiment.

(Also, you'll note with my calls of `console.groupEnd()` that there is bug in that Relay doesn't close its console groups when an error occurs deeply. This could really screw with further console calls by the developer or other applications.)

**Comment by wincent** [comment]
This looks reasonable to me. As nobody is actively working on this internally I am going to close it, but if you want to submit a PR like you said then we'd be happy to review it. Thanks for thinking about this and explaining the rationale so well!
