### ISSUE TITLE
getFragment data is not among component props

### ISSUE THREAD

**Issue by alerd** [facebook/relay#1485]
Hello, I face an issue with container composition in Relay

In  a parent container I use a fragment from a second container

```
import Relay from 'react-relay';
import Trip from '../components/Trip';
import Country from '../containers/Country';

export default Relay.createContainer(Trip,  {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
              name
              country {
                ${Country.getFragment('country')}
              }
        }`
  }
});
```

Afterwards, I try to get "this.props.viwer" in render method of Trip component

```
import React, { Component } from 'react';

export default class Trip extends Component {
  render() {
    console.log(this.props.viewer);
    debugger;
  }
}
```

But data which is stored in this.props.viewer.trip.country is not the country object I required. Instead, this.props.viewer  contains this
```
{
  "__dataID__": "client:-13922152401",
  "trip": {
    "__dataID__": "client:-13922152407",
    "name": "A trip",
    "country": [
      {
        "__dataID__": "Q291bnRyeUJvb2tpbmc6NzQzNjEzNw==",
        "__fragments__": {
          "2::client": [
            {}
          ]
        }
      }
    ]
  }
}
```

I checked GraphQL response from the server - server does returned me valid data
```
{
  "data": {
    "viewer": {
      "_trip1bq5a": {
        "name": "A trip",
        "country": {
            "id": "Q291bnRyeUJvb2tpbmc6NzQzNjEzNw==",
            "_key": "7436137",
            "countryCode": "USA"
        }
       }
    }
  }
}
```

If I don't use getFragment and specify country fields directly in Trip container
```
import Relay from 'react-relay';
import Trip from '../components/Trip';

export default Relay.createContainer(Trip,  {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
              name
              country {
                id
                _key
                name
              }
        }`
  }
});
```
this.props.viewer in render() method of Trip component contains needed data
```
{
  "__dataID__": "client:-12732119151",
  "trip": {
    "__dataID__": "client:-12732119152",
   "name": "A trip",
    "country": {
        "__dataID__": "Q291bnRyeUJvb2tpbmc6NzQzNjEzNw==",
        "id": "Q291bnRyeUJvb2tpbmc6NzQzNjEzNw==",
        "_key": "7436137",
        "countryCode": "USA"
     }
  }
}
```

Please help me whoever already met  such issue.
Or tell me if I do something wrong

**Comment by unirey** [comment]
I don't know all the exact reasonings behind Relay design but as far as I know, that's not an issue: `getFragment()` returns a reference to that fragment and parent is not aware of the data that gets passed down to children fragments. Think of this way:

If you need to pass down the fragment, I imagine you want to declare the data dependency next to React component for easier reasoning and future maintenance. If parent needs that data, just declare it in parent container and if children also need that data: pass it down as `props` or use fragment as you do (don't know how "Relay 2" will excatly work but current version of Relay should make a smart diff and not over-fetch). 

Secondly, if fragment data was available, you used it in parent component and if you ever deleted some of the used fields from that fragment, you would need to change several files/components and introduce unnecessary complexity. It might not be an issue with just two levels or for single developer but UIs are usually a lot more complex and maintained by group of people with different tech knowledge.

**Comment by unirey** [comment]
I don't know all the exact reasonings behind Relay design but as far as I know, that's not an issue: `getFragment()` returns a reference to that fragment and parent is not aware of the data that gets passed down to children fragments. Think of this way:

If you need to pass down the fragment, you probably want to declare the data dependency next to React component for easier reasoning and future maintenance, otherwise you could just pass it _via_ `props`. 

If parent needs that data, just declare it in parent container and if children also need that data: pass it down as `props` or use fragment as you currently do (I don't know how "Relay 2" will excatly work but current version of Relay should make a smart diff and not over-fetch/fetch same fields twice). 

If fragment data was available, you used it in parent component and if you ever deleted some of the used fields from that fragment, you would need to change several (sometimes tens) files/components and introduce unnecessary complexity. It might not be an issue with just two levels or for single developer but UIs are usually a lot more complex and maintained by group of people with different tech knowledge.

**Comment by alerd** [comment]
If a cannot access fragment data of child container, why I have to explicitly invoke getFragment method in parent container? 
Also I want to use and get Country.getFragment('country') data in many parent containers (not only Trip container) for the sake of DRY principle (not to repeat the nested hierarchical fields of Country inside each parent container).

**Comment by josephsavona** [comment]
Thanks for filing an issue - what you're seeing is **data masking**, wherein Relay only provides each component exactly the fields it asked for and no more. We discuss the reasoning for this (and much of Relay's design in general) in [Thinking in Relay](https://facebook.github.io/relay/docs/thinking-in-relay.html#data-masking), which might be helpful background context.

In this case, the parent `Trip` component can only access fields it asked. The data for the `Country` component is only accessible to that component, so you would typically do something like the following:

```
class Trip extends React.Component {
  render() {
    return (
      <View>
        <Text>{this.props.viewer.name}</Text> // access only fields directly fetched in fragment
        <Country country={this.props.viewer.country} /> // pass fragment data to the corresponding component
     </View>
   ):
  }
}
```

See also [Container Composition](https://facebook.github.io/relay/docs/guides-containers.html#container-composition).
