### ISSUE TITLE
Relay commitUpdate callbacks OnSuccess and OnFailed not firing

### ISSUE THREAD

**Issue by sjzamora86** [facebook/relay#1488]
I have a simple mutation and I would like to show a pop up after mutation success and error message if it fails but my problem is onSuccess and onFailure callbacks are not firing. This is my code:
Is there anyone having same issue. Any help will be much appreciated! 

const onMutationSuccess = (response: any) => {
      console.log('Show success pop up');
    };

    const onMutationFailed = (transaction: any) => {
      console.log('Show error message');
    };

    const mutation = new SampleMutation({input: input});

    this.props.relay.commitUpdate(mutation, {onMutationFailed, onMutationSuccess});

**Comment by ngthorg** [comment]
```js
this.props.relay.commitUpdate(mutation, {onMutationFailed, onMutationSuccess});
```

**Comment by ngthorg** [comment]
```js
const onSuccess = response => {
  console.log('onSuccess', response);
};
const onFailure = err => {
  console.log('onFailure', err);
};
const mutation = new SampleMutation({ input: input });
this.props.relay.commitUpdate(mutation, { onSuccess, onFailure });
```

**Comment by josephsavona** [comment]
Thanks for asking. As @ngthorg noted, the names of the callbacks are `onSuccess` and `onFailure`. Feel free to reopen if that doesn't work!

**Comment by sjzamora86** [comment]
Thank you for the response. It is now working after changing the name of the callbacks. Thank you!
