### ISSUE TITLE
Q: Queries supplied at the root should contain exactly one fragment and no fields...

### ISSUE THREAD

**Issue by keithpitt** [facebook/relay#149]
I have a route that looks like this:

```js
export default class BuildRoute extends Relay.Route {
  static queries = {
    build: Component => Relay.QL`
      query {
        viewer {
          build(organizationSlug: $organizationSlug, pipelineSlug: $pipelineSlug, buildNumber: $buildNumber) {
            ${Component.getFragment('build')}
          }
        }
      }
    `,
  }

  static paramDefinitions = {
    organizationSlug: { required: true },
    pipelineSlug: { required: true },
    buildNumber: { required: true },
  }

  static routeName = 'BuildRoute'
}
```

```
    ReactDOM.render(
      <Relay.RootContainer Component={BuildShow} route={new BuildRoute(...)} />
    , document.getElementById('app'));
```

It used query directly to the `bulld` (`query { build()... }`), but because it has multiple arguments, I had to wrap it in a `viewer` as described here: https://github.com/facebook/relay/issues/112

When I try and fetch the data, I get the following error:

> Uncaught Error: Invariant Violation: Queries supplied at the root should contain exactly one fragment and no fields. Query `BuildRoute` contains a field, `build`. If you need to fetch fields, declare them in a Relay container.

I'm probably doing something silly.

**Comment by josephsavona** [comment]
Route queries should contain only the root field - in this case `viewer`. Try moving the `build` field into the fragment of the root container.

**Comment by josephsavona** [comment]
@keithpitt I'm going to close this issue, but feel free to reopen if the solution above doesn't work for you - see also #112 which will make Root queries more flexible.

**Comment by CDRO** [comment]
This might sound silly, but I got across the same problem.

I followed the steps in #112 where it is told to wrap it. But I cannot add the fragment that I need in this case.

Any ideas on how to really fix this?
