### ISSUE TITLE
Difference between Relay.Store.commitUpdate and this.props.relay.commitUpdate

### ISSUE THREAD

**Issue by nikhildaga** [facebook/relay#1490]
Hi, 

Is there any difference between Relay.Store.commitUpdate and this.props.relay.commitUpdate ? Which one should be preffered and why? 
What when environment={Relay.Store} ? 

Thanks.

**Comment by josephsavona** [comment]
The version on props.relay is a convenience that uses whatever environment the container was rendered in, and should generally be preferred in case you decide t create different environment instances at some point. Note that Relay.Store is just a default instance of RelayEnvironment.
