### ISSUE TITLE
Mutations after rendering with a new environment

### ISSUE THREAD

**Issue by joaquimds** [facebook/relay#1494]
After reading #233, I implemented "resetting the store" in my app like this:

    export const initApp = (token = '') => {
      const environment = new Relay.Environment()
      environment.injectNetworkLayer(new Relay.DefaultNetworkLayer('/graphql'))

      const queryConfig = new AppQueryConfig({ token })

      ReactDOM.render(
        <Relay.Renderer Container={AppContainer} queryConfig={queryConfig} environment={environment} />,
        document.getElementById('root')
      )
    }

But I've been having a problem with mutations after the store is reset.

My theory is that for containers that have been rendered at least once already, `this.props.relay.commitUpdate` doesn't get updated to reference the new environment's `commitUpdate` function. It seems that `this.state.relayProp.commitUpdate` in RelayContainer is set when the container is first rendered, and isn't updated when the environment changes. I think this could be causing issues in my `RANGE_ADD` mutations.

I've found 3 ways to make my issues disappear:
1. Forcing react to render the entire app again, using e.g. `ReactDOM.unmountComponentAtNode(document.getElementById('root'))`,
2. Creating a new `AppContainer` (i.e. calling `Relay.createContainer()` again) when updating the environment, and
3. Modifying the `Relay.Container` code

This change to `RelayContainer.prototype._initialize` fixes the issue for me, but I definitely don't understand the library enough to have any idea on whether it is a good or appropriate change:

	relayProp: this.state.relayProp.route === context.route && require('fbjs/lib/shallowEqual')(this.state.relayProp.variables, nextVariables) ? this.state.relayProp : (0, _extends3['default'])({}, this.state.relayProp, {
      route: context.route,
      variables: nextVariables,
      commitUpdate: context.relay.commitUpdate,
      applyUpdate: context.relay.applyUpdate
    })

(Please let me know if I shouldn't even be using the library in this way.)

**Comment by colllin** [comment]
It looks like you might have found a bug.

I believe `this.props.relay.commitUpdate` and `this.props.relay.applyUpdate` are actually just references to those functions from your `Relay.Environment`.  If I'm reading this right, it looks like `RelayContainer` only sets those references in the constructor, and nowhere else, which means that if its `this.context.relay.environment` is updated, your `this.props.relay.commitUpdate` reference will be outdated.

Looking here: https://github.com/facebook/relay/blob/46a2f876c24dc1a9534d25ab1ef70e5a76ea3c78/src/container/RelayContainer.js#L158

If this is the problem, I would probably fix it by implementing `RelayContainer`'s `componentWillReceiveProps(nextProps, nextContext)` to update the `this.state.relayProp.commitUpdate` and `this.state.relayProp.applyUpdate` references with `nextContext.relay.environment`.

**Comment by josephsavona** [comment]
Yeah this sounds like a bug. @colllin your proposed fix sounds right, other than adding a conditional check to only reset `state.relayProp` if the store actually changed. We'd be happy to accept a PR along those lines! :-)

**Comment by colllin** [comment]
The componentWillReceiveProps solution felt a little messy, but this is where I ended up:
https://github.com/facebook/relay/compare/master...colllin:relay-container-environment-sync

Or... here's an alternative approach, which defines applyUpdate and commitUpdate functions on RelayContainer, which always delegate to the current underlying RelayEnvironment:
https://github.com/facebook/relay/compare/master...colllin:relay-container-environment-passthrough

The second approach feels a little cleaner to me, but has the disadvantage of re-specifying the applyUpdate and commitUpdate interface — I would have used `Function.prototype.apply` to avoid re-specifying the function interface, but didn't see any uses of `Function.prototype.apply` or the `arguments` keyword in this repo, so I didn't want to break that trend.

**Comment by colllin** [comment]
^^^ Do you have a preference about which PR I submit?

**Comment by joaquimds** [comment]
Thanks for checking out my issue guys :-)

Updating `componentWillReceiveProps` makes sense to me – just a thought that `_initialize` seems to be the only place where `relayProp` is modified (outside of the constructor) so it might be good to keep all the modifications in this one place. That said, it doesn't get the right parameters to check if the environment has changed. I'll leave it to you!

**Comment by colllin** [comment]
I considered updating `_initialize` instead of `componentWillReceiveProps` (as you show in your original message), but as you mention, it doesn't get the right parameters, and its logic seems to be focused on "variables", so it didn't feel "right" to add it there. But I'm doing a lot of interpretation here.  If `_initialize` is the right place for it, I can move it.

**Comment by wincent** [comment]
Closing issues relating to the old Relay core, seeing as Relay Modern is now out and that is where we will be targeting all future development efforts, and we want to keep the issue tracker clean and focused on those. Thanks for report and the discussion!
