### ISSUE TITLE
connection query for PageInfo without edges drops PageInfo

### ISSUE THREAD

**Issue by jaredmcdonald** [facebook/relay#1495]
Hey,

I have a use case where I need to see if there's an additional page in a connection without actually following any edges. When I ask for `edges` in addition to `pageInfo`, I get `pageInfo` back as expected, but when I drop `edges`, `pageInfo` comes back undefined in the component's props, without any errors or warnings.

This works as expected:

```js
const WhateverComponent = Relay.createContainer(({ foo }) => {
  console.log(foo.myConnection.pageInfo) // { hasNextPage: true }
  return <h1>test</h1>
}, {
  fragments: {
    foo: () => Relay.QL`
      fragment on WhateverType {
        myConnection(first: 1) {
          edges { ... }
          pageInfo {
            hasNextPage
          }
        }
      }
    `
  }
})
```

But this doesn't (all I do is drop `edges` from the connection):

```js
const WhateverComponent = Relay.createContainer(({ foo }) => {
  console.log(foo.myConnection.pageInfo) // undefined
  return <h1>test</h1>
}, {
  fragments: {
    foo: () => Relay.QL`
      fragment on WhateverType {
        myConnection(first: 1) {
          pageInfo {
            hasNextPage
          }
        }
      }
    `
  }
})
```

Let me know if anything needs clarification--thanks!

**Comment by josephsavona** [comment]
This sounds like a bug in the dynamic core. The simplest workaround for now is to fetch `edges.cursor`.

**Comment by wincent** [comment]
Given that there is a workaround and this bug explicitly applies to the legacy API, I am going to mark this as "wontfix". We want to aggressively prioritize work on the new core and help people move to it as soon as possible. We do appreciate the bug report, however. Thankyou @jaredmcdonald!

**Comment by wincent** [comment]
Having said that, we wouldn't reject a PR with a fix; it's merely that we are unlikely to work on one ourselves.
