### ISSUE TITLE
DefaultNetworkLayer isn't exported

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#15]
`Relay.DefaultNetworkLayer` isn't being exported, presumably because package.json has main set to lib/RelayPublic.js instead of index.js

**Comment by yungsters** [comment]
Will be fixed by eb7cb350f69da52813809935a69d11fac810fcb8.

**Comment by devknoll** [comment]
Thanks @yungsters - does index.js need to be added to `files` in package.json too?

**Comment by yungsters** [comment]
@devknoll Good catch. :)

**Comment by yungsters** [comment]
@devknoll Actualy, it looks like npm automatically includes `index.js` (maybe because it's set to `main`). But being explicit never hurts.

**Comment by devknoll** [comment]
Nice! :+1:

**Comment by devknoll** [comment]
@yungsters Looks like index.js needs to be included in the gulp file too! :smile:
