### ISSUE TITLE
Relay.GraphQLMutation doesn't output log

### ISSUE THREAD

**Issue by chollier** [facebook/relay#1501]
I was using the new Relay.GraphQLMutation and came to notice that it doesn't output any log.
Hence errors such as an invalid config would get swallowed.

Example :
```js
const configs = [
    {
      type: "RANGE_ADD",
      parentName: "forumTopic",
      parentId: this.props.forumTopic.id, <--- it should be parentID
      connectionName: "responses",
      edgeName: "forumResponse",
      rangeBehaviors: (args) => {
        return "refetch";
      },
    },
]
```
fails silently with `Relay.GraphQLMutation` while with the old API we could see the error by expanding :
<img width="284" alt="screen shot 2017-01-13 at 10 42 28 am" src="https://cloud.githubusercontent.com/assets/1869/21941339/2c70fdbc-d97d-11e6-85bb-e440090bc0ea.png">

**Comment by josephsavona** [comment]
hmm interesting. cc @yuzhi

**Comment by yuzhi** [comment]
mhm It might just not be hooked up with Relay.GraphQLMutation. I can take a look when I have free cycles.

**Comment by wincent** [comment]
With the release of Relay Modern, `GraphQLMutation` is no longer being worked on, so I'm going to close this issue. Please file any new issues that you might find in the new API, however. Thanks for reporting!
