### ISSUE TITLE
'Converting circular structure to JSON' error

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/relay#1504]
Hi, I've recently updated my React Native app to the newest RN version(0.40.0) as well as Relay to the newest(0.10.0),
and Relay seems to be giving me the following error since updating.

```
Converting circular structure to JSON

stringify
    stringify.js:5
printRelayOSSQuery
    printRelayOSSQuery.js:56
instrumentedCallback
    RelayProfiler.js:129
RelayQueryRequest._getPrintedQuery
    RelayQueryRequest.js:69
RelayQueryRequest.getQueryString
    RelayQueryRequest.js:94
RelayDefaultNetworkLayer._sendQuery
    RelayDefaultNetworkLayer.js:131
<unknown>
    RelayDefaultNetworkLayer.js:61
RelayDefaultNetworkLayer.sendQueries
    RelayDefaultNetworkLayer.js:60

```

The directories, babel-relay-plugin script, GraphQL implementation, etc. are exactly the same as before.

Relay version is: `v0.10.0`.
Now I do need to point out that I am using a [fork of Relay](https://github.com/alloy/relay) which simply replaces `id` with `__id`.

I can recreate with the code below:

```js
import React, { Component } from 'react'
import { View } from 'react-native'
import Relay from 'react-relay'

class TodoList extends Component {
  render() {
    return <View></View>
  }
}

export default Relay.createContainer(TodoList, {
  initialVariables: {
    first: 10
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        todos(first: $first) {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    `
  }
})

```

My BabelRelayPlugin.js looks like this:
```js
'use strict'
const config = require('../config')
const getBabelRelayPlugin = require('babel-relay-plugin')
const introspectionQuery = require('graphql/utilities').introspectionQuery
const request = require('sync-request')

const url = 'http://localhost:3000'

const response = request('POST', url, {
	authorization: `Bearer ${config.get(`graphql.token`)}`,
  qs: {
    query: introspectionQuery
  }
})

const schema = JSON.parse(response.body.toString('utf-8'))

module.exports = {
	plugins: [
		getBabelRelayPlugin(
			schema.data,
			{
				abortOnError: true
			}
		)
  ]
}
```

I have confirmed that the schema is fetched properly.

**Comment by Naoto-Ida** [comment]
So I did a bit of digging, but not sure where to go from here.
I understand that code like [this](http://stackoverflow.com/q/11616630/4776002) can trigger the 'Converting circular structure to JSON' error.
So the contents of `node` that is being passed to `printRelayOSSQuery.js:33`.

I reverted back to `v0.9.2` of the forked one, and now it's back to normal.
I'm starting to think this might be an issue with the fork, closing now.
Will probably consult @alloy on this.

**Comment by alloy** [comment]
@Naoto-Ida Oh, I have not actually updated to 0.10 in our app yet, so haven’t verified this yet. In the meantime, is there any way for you to confirm if everything works ok if you switch to the canonical version?

**Comment by Naoto-Ida** [comment]
@alloy Do you mean canonical as in the main project?

**Comment by alloy** [comment]
@Naoto-Ida Yeah that’s what I meant, but for some reason I thought the error was occurring in the babel plugin, but now I see I misremembered and it occurs at runtime, which is probably going to be hard to try out as you’d have to change the actual responses coming from your server.

I’ll first take some time to update our main app and see if I can reproduce it there and report back to you.

**Comment by Naoto-Ida** [comment]
@alloy Thank you so much! I wish I could help out a bit more, as I've only been playing with Relay for the past month or so...
