### ISSUE TITLE
Sort out Flow errors in plug-in

### ISSUE THREAD

**Issue by wincent** [facebook/relay#1508]
For some, reason `npm run typecheck` in [scripts/babel-relay-plugin/](https://github.com/facebook/relay/tree/master/scripts/babel-relay-plugin) is bombing out, failing to recognize that `require('util')` refers to a built-in Node.js library and we are running in Node.js. The errors look like this:

```
src/getBabelRelayPlugin.js:21
 21: const util = require('util');
                  ^^^^^^^^^^^^^^^ This modules resolves to "<<PROJECT_ROOT>>/../../node_modules/util/package.json", which is outside both your root directory and all of the entries in the [include] section of your .flowconfig. You should either add this directory to the [include] section of your .flowconfig, move your .flowconfig file higher in the project directory tree, or move this package under your Flow root directory.
```

and it seems I can't force Flow into grokking the type of the `util` module with a declarations file with contents taken [from Flow](https://github.com/facebook/flow/blob/master/lib/node.js) (perhaps I am doing it wrong):

```diff
diff --git a/scripts/babel-relay-plugin/.flowconfig b/scripts/babel-relay-plugin/.flowconfig
index 51ccac9a..df4d1945 100644
--- a/scripts/babel-relay-plugin/.flowconfig
+++ b/scripts/babel-relay-plugin/.flowconfig
@@ -3,6 +3,7 @@
 [include]

 [libs]
+./decl

 [options]

diff --git a/scripts/babel-relay-plugin/decl/flow b/scripts/babel-relay-plugin/decl/flow
new file mode 100644
index 00000000..8f561f45
--- /dev/null
+++ b/scripts/babel-relay-plugin/decl/flow
@@ -0,0 +1,17 @@
+declare module "util" {
+  declare function debuglog(section: string): (data: any, ...args: any) => void;
+  declare function format(format: string, ...placeholders: any): string;
+  declare function log(string: string): void;
+  declare function inspect(object: any, options?: {
+    showHidden?: boolean;
+    depth?: ?number;
+    colors?: boolean;
+    customInspect?: boolean;
+  }): string;
+  declare function isArray(object: any): boolean;
+  declare function isRegExp(object: any): boolean;
+  declare function isDate(object: any): boolean;
+  declare function isError(object: any): boolean;
+  declare function inherits(constructor: Function, superConstructor: Function): void;
+  declare function deprecate(f: Function, string: string): Function;
+}
```

Not sure when this started, but I went back to the previous version of Flow that we were using (v0.36.0) and got the same result.

In the absence of a config option to tell Flow that we're running in Node.js, I tried this in the `package.json`, but that doesn't fix the error either:

```diff
diff --git a/scripts/babel-relay-plugin/package.json b/scripts/babel-relay-plugin/package.json
index 410ecc14..6025e67e 100644
--- a/scripts/babel-relay-plugin/package.json
+++ b/scripts/babel-relay-plugin/package.json
@@ -14,6 +14,9 @@
     "update-fixtures": "babel-node ./src/tools/regenerateFixtures.js",
     "update-schema": "babel-node ./src/tools/generateSchemaJson.js"
   },
+  "engines" : {
+    "node" : "*"
+  },
   "files": [
     "LICENSE",
     "PATENTS",
```

For now the only workaround I've found is liberal use of `$FlowFixMe`:

```diff
diff --git a/scripts/babel-relay-plugin/src/invariant.js b/scripts/babel-relay-plugin/src/invariant.js
index 295451d6..36e0adc7 100644
--- a/scripts/babel-relay-plugin/src/invariant.js
+++ b/scripts/babel-relay-plugin/src/invariant.js
@@ -12,6 +12,7 @@

 'use strict';

+// $FlowFixMe
 const util = require('util');

 function invariant(
```

Going to ask somebody who knows about Flow about this, so sticking this up in an issue to have something to reference.

**Comment by nodkz** [comment]
Try to hack it in `.flowconfig` via [`[options]`](https://flowtype.org/docs/advanced-configuration.html#options):
```js
module.name_mapper='^util$' -> 'path to declaration'
```
Some time ago in such way I connected to `graphql` for providing type definitions with regular import/require in my code. Now graphql package contains `.flow` files, and  I removed this linking, but in past it help me very well.

**Comment by wincent** [comment]
Alas @nodkz, that doesn't work, but I have an alternative workaround that does. The Flow team at FB is aware of the bug in the module resolution so it will be fixed, but for now we have a workaround (see my PR).

**Comment by wincent** [comment]
I believe this is all good now. Closing.
