### ISSUE TITLE
GraphQLMutation & updating local state

### ISSUE THREAD

**Issue by brandonmp** [facebook/relay#1512]
I'm about 3 weeks into Relay & trying to learn the `GraphQLMutation` API (in lieu of the 'legacy' API). I'm hitting some inconsistencies that I can't quite figure out.

I'm using a graphql-aaS (so my gql server should be up-to-spec). The relevant parts of my schema are roughly something roughly like this:

````
# all of these implement the Node interface
type Listing  {
  listingTags: [ListingTag]
  ratings: [ListingRating]
}

type ListingRating {
  user: User
  listing: Listing
}

type ListingTag {
  listing: Listing
  user: User
  tagName: string
}

type User {
  listingTags: [ListingTag]
  listings: [Listing]
}

# this type does NOT implement Node
type UserListingTagsConnection {
  user: User
  listingTag: ListingTag
}
````

In my app, I render each `Listing` with its `ListingTags` and `ListingRatings`, and I render several `User` and each of their `ListingTags`.

The first mutation I wrote added a separate type, `ListingRating`, a `Listing`.  This mutation works fine, and local data updates right away:

````
import Relay from 'react-relay'
import ListingRating from 'components/ListingRating'

const createListingRating = (variables, relayStore) => {
  const query = Relay.QL`mutation {
    createListingRating(input:$input) {
      changedListingRating {
        rating
        id
        listing {
          ratings (first: 100) {
            edges {
              node {
                ${ListingRating.getFragment('ratings')}
              }
            }
          }
        }
      }
    }
  }
  `
  const input = { input: variables }
  const mutation = new Relay.GraphQLMutation(
    query,
    input,
    null,
    relayStore,
    {
      onFailure: err => console.warn(err),
      onSuccess: () => console.log('Success!'),
    },
  )
  mutation.commit()
}


export default createListingRating
````

where `ListingRating.getFragment('ratings')` returns:

````
 fragment on ListingRating @relay(plural: true) {
           rating
           id
            user {
                id
                firstName
            }
            listing {
              id
            }
        }
````

This appears to work perfectly fine, despite not setting `configs` (which I like, as I've found `configs` pretty difficult to grok).

However, the second mutation I wrote, which connects a `ListingTag` to a `User` (via a `many:many` connection `Type`), fails to update local data:

````
// @flow
import Relay from 'react-relay'
import type { Environment } from 'react-relay'
import TagPreview from 'components/ListingCard/TagPreview.js'

type Input = { listingId: string, listingTagId: string };

const connectListingListingTag =
  (variables: Input, relayStore: Environment) => {
    const query = Relay.QL`mutation {
      addToListingsListingTagsConnection(input:$input) {
        changedListingsListingTags {
          listing {
            listingTags (first: 1000){
              edges {
                node {
                  ${TagPreview.getFragment('currentTags')}
              }
            }
          }
        }
      }
    }
  }
  `

    const input = { input: variables }
      const mutation = new Relay.GraphQLMutation(
        query,
        input,
        null,
        relayStore,
        {
          onFailure: err => { console.error(err) },
          onSuccess: () => { console.log("success!")},
        },
      )
      mutation.commit()
  }


export default connectListingListingTag
````
where `TagPreview.getFragment('currentTags')` returns:

````
fragment on ListingTag @relay(plural: true) {
        tagName
        }
````

This mutation successfully updates my database, and according to `relay dev tools` panel, the response contains all the data I want. 

**The part I'm not fully understanding is**:  in what way are these mutations different such that one works and the other doesn't?  

Is it because the `type` of the returned `payload` doesn't implement the `Node` interface? My assumption was that when `Relay` saw `node`s nested in the response `payload`, it'd update the local state as it did with the first mutation.  

Ultimately though, this is the only difference I can reason out, & I'm uncertain how to address it.

**Comment by wincent** [comment]
Closing out some old issues against the old APIs. Relay Modern is now out, so please file any issues you might run into with the new API as new issues. Thanks!
