### ISSUE TITLE
"Using `null` as a rangeBehavior" when not returning `null`

### ISSUE THREAD

**Issue by kalley** [facebook/relay#1520]
I have a `GraphQLMutation` that I'm passing `configs` to. The commit looks like:

```js
mutation.commit([{
    type: 'RANGE_ADD',
    parentID: props.employeeId,
    parentName: 'employee',
    connectionName: 'enrollmentSets',
    edgeName: 'createdEnrollmentSetEdge',
    rangeBehaviors: calls => 'refetch',
  }])
```

I tracked the problem down to this line of code: 

https://github.com/facebook/relay/blob/7110c68f437391ad1ee54ab2c84fd8896a8662fb/src/traversal/writeRelayUpdatePayload.js#L418

where `null` is being intentionally set, and then telling me I'm wrong. It seems like it should be setting to `IGNORE` unless I'm missing something else.

**Comment by wincent** [comment]
The old mutations API is no longer being actively worked on or supported, and Relay Modern is now out, so I'm going to close this one in order to keep the issue tracker focused on the stuff that is currently being worked on. Thanks!
