### ISSUE TITLE
GraphQLMutation.createWithFiles not Posting the file

### ISSUE THREAD

**Issue by AWDGroup** [facebook/relay#1528]
I'm working on a React Native application and I have the following mutation that should create a record and upload a picture.
I'm using GraphQLMutation.createWithFiles and passing a file as an argument, but unfortunately Relay does not post the file. As a result, my record gets created on the server but there is no file submitted to be stored.

```
        let file = {
            uri: this.state.avatarSource.uri,
            type: 'image/jpeg',
            name: 'photo.jpg',
        };
        const environment = new Relay.Environment();
        environment.injectNetworkLayer(this.props.navigator.props.networkLayer);
        const query = Relay.QL`mutation AddEmployeeMutation {
            addEmployee(input: $input) {
                clientMutationId
                employeeEdge {
                    node{
                        id
                    }
                }
            }
        }`;
        const variables = {
            input: {
                firstName: this.state.firstName,
                lastName: this.state.lastName,
                employeePosition: this.state.employeePosition,
            },
        };
        const mutation = Relay.GraphQLMutation.createWithFiles(
            query,
            variables,
            file,
            environment,
        );

        const configs = [{
            type: 'RANGE_ADD',
            parentName: 'viewer',
            parentID: this.props.viewer.id,
            connectionName: 'employeeConnection',
            edgeName: 'employeeEdge',
            rangeBehaviors: (calls) => {
                    return GraphQLMutatorConstants.APPEND;
            }
        }];
        const transaction = mutation.commit(configs);
        console.log(transaction);
```

**Comment by apalm** [comment]
@AWDGroup This was [fixed](https://github.com/facebook/relay/commit/81f8cf92d240cb1cd6fd7cc2263a51c58b2b5a19) but hasn't been released yet.

**Comment by AWDGroup** [comment]
Thanks @apalm, I think GraphQLMutation.createWithFiles is not covered by the test cases and it should be added as well

**Comment by wincent** [comment]
@AWDGroup: Thanks for the report.

> I think GraphQLMutation.createWithFiles is not covered by the test cases and it should be added as well

Some tests were added in https://github.com/facebook/relay/commit/6b87e2692fc6c74021b4aa7fbc3a712aaaedd141 — You're welcome to add more for that specific method, but I think the likelihood of somebody ever breaking the implementation is so vanishingly close to zero that I personally wouldn't bother with it:

```
static createWithFiles(
  mutation: RelayConcreteNode,
  variables: Variables,
  files: FileMap,
  environment: RelayEnvironmentInterface
): RelayGraphQLMutation {
  return new RelayGraphQLMutation(mutation, variables, files, environment);
}
```

On the subject of a release, I was trying to work towards that last week, but currently blocked on getting our open source CI suite green again (our internal CI is passing just fine). At the moment we have quite a few large changes in progress, and the sync set-up we have between GitHub, or native code and our www code, imposes some restrictions that we have to figure out how to work within before we can get everything green again. But we will release as soon as we can, although I can't provide a concrete date for it (too many unknowns).

**Comment by AWDGroup** [comment]
Thanks @wincent for the complete & clear explanation.

**Comment by wincent** [comment]
@AWDGroup: You're welcome. Going to close this out in the meantime so as to unclutter the issue tracker.
