### ISSUE TITLE
Getting error for `new Relay.Environment()` while using GraphQLMutation

### ISSUE THREAD

**Issue by nikhilag** [facebook/relay#1529]
Here's the error I am getting on following the example in the GraphQLMutation documentation at https://facebook.github.io/relay/docs/api-reference-relay-graphql-mutation.html :-

`const environment = new Relay.Environment();`

> Uncaught TypeError: _relay2.default.Environment is not a constructor

My import statement in my react component for Relay is:-
`import Relay, {RelayGraphQLMutation, GraphQLMutatorConstants} from 'relay';`

What am I doing wrong?

**Comment by nikhilag** [comment]
Please ignore this issue. My import statement had errors.

**Comment by wincent** [comment]
Glad to hear you got it sorted out.
