### ISSUE TITLE
Naming queries from setVariables

### ISSUE THREAD

**Issue by mjtamlyn** [facebook/relay#1535]
Hi! I've been running in production for some time now and it's been slowly taking over larger parts of my site. Generally speaking I'm very pleased with it, although I'm looking forwards to some of the changes I've heard planned for Relay 2.

My application has certain regular access patterns to the API, and I'd like to be able to easily identify them so I can track metrics of different common access patterns independently. When changing Route, this is quite easy - you can name the query in the Route using `query MyQueryName {...}`, and the server can identify it. Mutations can be named in the same way. I'd really like to be able to set the query name for the query generated when I call a `setVariables`. A single page will have an initial load state, and maybe 5-10 different additional pieces of data loaded on demand by the user, changing variables and enabling different conditional parts of the query. At the moment I can't find an easy way to distinguish between those different cases.

I believe that an additional parameter could be added to `setVariables` to set the name, and the passed down to the environment/store layer and put into the resulting query, but I don't know enough about the internals of the store to know if this is feasible.

Feel free to tell me I've got the wrong approach here and I'm using relay wrong!

**Comment by wincent** [comment]
Thanks for the post, @mjtamlyn.

The new core uses totally static, vanilla GraphQL syntax, and `setVariables` use cases now require you to specify an explicit "refetch" query, which can be named:

```
query MyArbitraryQueryName($count: Int) {
  viewer {
    ...SomeFragment
  }
}
```

So, this problem effectively goes away with no modifications to the code. I'm going to close this for now because we're entirely focused on shipping the new core and API rather than working on the old one.

**Comment by mjtamlyn** [comment]
Great, glad to know this case is covered in the new API, that was my main concern.
