### ISSUE TITLE
Undocumented GraphQLMutation commit using credentials same-origin

### ISSUE THREAD

**Issue by mattferrin** [facebook/relay#1540]
`GraphQLMutation` method `commit` does not use the result of `injectNetworkLayer` for requests to allow setting the same credentials as origin. To the best of my knowledge, credentials cannot be set to same-origin at all. Can we confirm this is an issue, or to I have a gap in understanding?

**Comment by mattferrin** [comment]
Debugged and saw that I needed to set the mutation queues network layer. Using Ramda, it looked like this.

```js
R.assocPath(['_storeData','_mutationQueue','_storeData','_networkLayer'], new DefaultNetworkLayer(`${host}/graphql`, {
   credentials: 'same-origin',
}), Relay.Store)
```

**Comment by wincent** [comment]
Glad to hear you got it sorted out.
