### ISSUE TITLE
How to update / refetch a single Edge of a connection?

### ISSUE THREAD

**Issue by mvgijssel** [facebook/relay#1544]
Say I want to update some information about the edge of a connection, like `isCoolFriend: true`.  
```
query {
  me {
    friends(first: 100) {
      edges {
        isCoolFriend
        node {
          name
        }
      }
    }
  }
}
```

How would the `getConfigs() {}` of a mutation class look? My experience is as follows:
- `FIELDS_CHANGE` which will refetch the entire collection
- `RANGE_ADD`
  - append/prepend moves the Edge (unwanted)
  - ignore actually only fetches the data for that Edge, but doesn't update the actual Edge (at least the change isn't reflected in the DOM)
  - refetch fetches the entire connection (feels a bit the same as FIELDS_CHANGE)

I have the feeling I'm missing something trivial here, as I just want one field on one edge to update, not refetch the entire thing.

**Comment by mvgijssel** [comment]
After sleeping on it, I'd expect a config like `RANGE_UPDATE` or `RANGE_CHANGE` which would just update the edge. Or am I approaching the problem wrong? Shouldn't it be possible to update a single edge? Could also change the schema to something like:
```
query {
  me {
    friends(first: 100) {
      edges {
        node {
          name
          friendEdge {
            isCoolFriend
          }
        }
      }
    }
  }
}
```
But that feels hacking around the issue.

**Comment by proProbe** [comment]
How does your fatQuery look?
I believe that you need to have something like
```
            {
                type: 'FIELDS_CHANGE',
                fieldIDs: {
                    friend: this.props.friend_id,
                },
            },
```
You need to put in the `edge_type` to the fields_change and input the correct id to the edge you want to update

**Comment by wincent** [comment]
Closing this as Relay Modern is now out with a completely new implementation and API that is based on explicit refetch queries.
