### ISSUE TITLE
Relay uses a promise polyfill with non-standard extensions

### ISSUE THREAD

**Issue by guncha** [facebook/relay#1551]
Please consider using native promises or allow developers the option to choose what polyfill they want to use. Native promises have superior debugging experience to this `throwNext(error)` stuff that `fbjs/lib/Promise` does.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

Note that Relay Modern now relies on the global native Promise
