### ISSUE TITLE
SetVariables for Query on Viewer

### ISSUE THREAD

**Issue by d-winter** [facebook/relay#1558]
Hey all,

I have a problem with a query which should be loaded when an event occurs. My relay container looks like this:

```
export default Relay.createContainer(SearchResults, {
  initialVariables: {
    userFilter: null,
    fetchUsers: false,
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        allUsers(first: 50 filter: $userFilter) @include(if: $fetchUsers) {
          edges {
            node {
              id
              name
            }
          }
        }
      }
    `,
  },
});
```

Here is the the React class:
```
class SearchResults extends Component {
  static propTypes = {
    emailAddress: PropTypes.string.isRequired,
    relay: PropTypes.object.isRequired,
  }

  constructor(props) {
    super(props);
    this._handleClick = this._handleClick.bind(this);
  }

  _handleClick() {
    this.props.relay.setVariables({
      userFilter: { emailAddress: this.props.emailAddress },
      fetchUsers: true,
    });
  }

  render() {
    return (
      <div>
        <button onClick={this._handleClick}>Load!</button>
      </div>
    );
  }
}
```

The query in GraphiQL looks like this:
```
{
  viewer {
    allUsers {
      edges {
        node {
          id
        }
      }
    }
  }
}
```
When I remove the @include condition the query is fetched perfectly the first time, but when I click the Load button, I get this error:
```
Server request for query `SearchResults_ViewerRelayQL` failed for the following reasons:

1. Fragment 'F0' cannot be spread here as objects of type 'Node' can never be of type 'Viewer'. (line 3, column 5):
    ...F0
    ^
       ...F0
       ^^^
```

The query which was send is the following:
```
query SearchResults_ViewerRelayQL($id_0:ID!,$filter_1:UserFilter!) {
  node(id:$id_0) {
    ...F0
  }
}
fragment F0 on Viewer {
  _allUsers1IGgdz:allUsers(first:50,filter:$filter_1) @include(if:true) {
    edges {
      node {
        id,
        name
      },
      cursor
    },
    pageInfo {
      hasNextPage,
      hasPreviousPage
    }
  },
  id
}
```

I googled now for hours and found out, that this is the correct behaviour.
See [here](http://stackoverflow.com/questions/37594134/relay-graphql-querying-field-node-instead-of-viewer-when-using-this-props-re) and [here](http://stackoverflow.com/questions/33399901/in-relay-what-role-do-the-node-interface-and-the-global-id-spec-play/33411416#33411416)
So now I have no idea how I can solve this issue. I definitely have to load the data on an event, since I have to filter the users by the entered emailAdress.

Does anybody can help me on how to do this?
Thanks a lot for any help!

**Comment by amkoehler** [comment]
See #1409 for a possible solution (exact comment [here](https://github.com/facebook/relay/issues/1409#issuecomment-252064786)). Based on that, it looks like your GraphQL API needs to be set up to handle a `nodeInterface` for the type defined within your `allUsers` query.

**Comment by d-winter** [comment]
Hey @amkoehler,
yes, I saw this ticket. Unfortunately the `User` model implements the node interface (I am using Graphcool as the backend).
![screen shot 2017-03-02 at 04 34 46](https://cloud.githubusercontent.com/assets/11208517/23491918/a7db91de-ff01-11e6-9f45-eeeb0f8156f0.png)
What I forgot to mention is, that I am using react-router-relay with this queries object:
```
export const ViewerQuery = {
  viewer: (Component, variables) => Relay.QL`
    query {
      viewer {
        ${Component.getFragment('viewer', variables)}
      },
    }
  `,
};
```
Any further ideas?
Thanks again for you help:)

**Comment by sibelius** [comment]
@d-winter `Viewer` should also implement `node` interface

**Comment by macolsson** [comment]
@sibelius I have the same issue as the OP, and I've tried implementing the viewer as a nodeInterface (using [Graphene (python)](https://github.com/graphql-python/graphene/). When executed, the request no longer throws a 400, but succeeds, however the response is now:
`{"data":{"node":null}}`

Not quite sure I understand why the viewer should be a nodeInterface, since node is _within_ the Viewer:
```
class Root(user_schema.Query, graphene.ObjectType):
    id = graphene.ID(required=True)
    node = relay.Node.Field()
    viewer = graphene.Field(lambda: Root)

    def resolve_viewer(self, args, context, info):
        return info.parent_type

    def resolve_id(self, args, context, info):
        return 1

    class Meta:
        interfaces = (relay.Node, )
```

Why should a query built from root, resolve the entire query within a node interface?

```
/* Main.js */
...
export default Relay.createContainer(Main, {
  initialVariables: {
    toolId: '',
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Root {
        ...
        ${OtherComponent.getFragment('root')}
        userTool(id: $toolId) {
          ${ToolDetail.getFragment('tool')}
        }
      }
    `,
  },
});
```
```
/* ToolDetail.js */
export default Relay.createContainer(ToolDetail, {
  fragments: {
    tool: () => Relay.QL`
      fragment on UserToolNode {
        id
        macAddress
        name
      }
    `,
  },
});
```

Any ideas, or should I be asking elsewhere?

**Comment by wincent** [comment]
No further work is expected to take place on the `setVariables` API now that Relay Modern and a new set of APIs is out, so closing this one for now. Please file any subsequent issues against the new core.
