### ISSUE TITLE
 Fragment "F1" cannot be spread here as objects of type "Node" can never be of type "Store".

### ISSUE THREAD

**Issue by nikhilmahesh** [facebook/relay#1559]
I have written below code

```

On Certain User Action below method is called :

  handleFolderClicked = (topic, parent) => {
    console.log('Main : handleFolderClicked called : ', parent);
    this.props.relay.setVariables({
      parentFolder: parent,
      email: loginEmail
    });
  }

Main = Relay.createContainer(Main, {
  initialVariables: {
    pageSize: pageSize,
    email: loginEmail,
    parentFolder: parentFolder,
  },
  fragments: {
    store: () => Relay.QL`
      fragment on Store {
        id,
        fileConnection(first:999, email:$email, parentFolder:$parentFolder) {
          ${DirectoryListing.getFragment('files')},
        }
        users {
          email,
        }
      }
    `,
  }
});
```

export default Main;

On the time of page load its working fine and fetching results but when value of parentFolder is changed using setVariables, it throws above error.

An insight might be useful and appreciated. Thanks

**Comment by sibelius** [comment]
your `Store` should implement `Node` interface

like this: https://github.com/entria/graphql-dataloader-boilerplate/blob/master/src/type/UserType.js#L37

**Comment by wincent** [comment]
Closing out old questions involving the old Relay APIs as Relay Modern is now out and we want to keep the issue tracker focused on the stuff that is currently being worked on. Thanks for asking your question @nikhilmahesh, and I hope you were able to get to a solution based on the tip from @sibelius.
