### ISSUE TITLE
Uncaught TypeError: queryBuilder is not a function

### ISSUE THREAD

**Issue by Moezalez** [facebook/relay#156]
Hi!

I am very new to all this. And I have trouble with getting Relay in my little client rendering app up and running. 

For some reason I end up with this error:
```
relayDepricated.js:4042 Uncaught TypeError: queryBuilder is not a function
```

I seem to end up with queryBuilder being a GraphQLQuery object and not a function. 
Also I am not really sure why it is using the "relayDepricated.js" instead of the relay.js.
I am really puzzled with this. Any idea how this could happen?

Best regards!

**Comment by josephsavona** [comment]
The most likely cause of the error is that either your route defined a query like this:

```
foo: Relay.QL`query...`
```

Instead of

```
foo: () => Relay.QL`query...` // note the function call
```

I'm not sure why you're seeing `relayDeprecated.js` - are you basing your app off of the starter kit, or did you configure it manually? (and if so, how?)

**Comment by Moezalez** [comment]
Thanks for your answer.

I used a function. My route looks like this:
```
var fragment = Relay.QL`
      fragment on Thread {
        id
        messages {
          content
        }
      }
    `

export default class extends Relay.Route {
  static path = '/';
  static queries = {
    thread: () => Relay.QL`
      query {
        thread {
         ...fragment,
        },
      }
    `,
  };
  static routeName = 'AppHomeRoute';
}
```


This is how I created the container: and how I am rendering
```
var container = Relay.createContainer(MessageBox, {
  queries: {
    thread: Relay.QL`
      query thread {
		    thread {
			    id
			    messages {
			      content
			    }
			  }
		  }
    `
  }
});

React.render(
    <Relay.RootContainer
      Component={container}
      route={route}
      renderLoading={function() {
		    return <div>Loading...</div>;
		  }}
    />,
    document.getElementById('example')
  );
```


I did not use the starter kit. 
I am using babel+webpack:
```
var babelRelayLoader = require('babel-relay-plugin');
var schema = require('./schema');

module.exports = {
  entry: "./index.js",
  output: {
      path: __dirname,
      filename: "bundle.js"
  },
  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: "babel-loader"},
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel', query: {stage: 0, plugins: ['./test']}
      }
    ]
  }
};
```

**Comment by josephsavona** [comment]
Aha! Thanks for pasting the code, it's very close but there are few minor issues.

1) The route query definition should follow the example in the [Relay.Route guide](https://facebook.github.io/relay/docs/guides-routes.html#routes-and-queries).

```javascript
static queries = {
    thread: Component => Relay.QL`
      query {
        thread {
          ${Component.getFragment('thread')} // include the fragment *from the root container*
        },
      }
    `,
  };
```

2) The container code should be updated as follows:

```javascript
var container = Relay.createContainer(MessageBox, {
  fragments: {    // use `fragments` not `queries`
    thread: () => Relay.QL`  // use a function
```

**Comment by josephsavona** [comment]
Also, it appears that the babel configuration isn't using the `babel-relay-plugin` at all (your code `require()`s it but doesn't reference it). Can you paste your full configuration?

The `relay-starter-kit` is definitely the best and easiest way to get started.

**Comment by Moezalez** [comment]
It seems to have resolved that issue! Now I am running in some React Issues it seems, probably not related. 
Thanks a lot Joseph!

Regarding babel-relay-plugin. AFAIK it runs just fine. It also validates agains my schema. I just forgot to remove the require statements when I moved part of the logic.
Full webkit config:

```javascript
//test.js
var getbabelRelayPlugin = require('babel-relay-plugin');
var schema = require('./schema.json');

module.exports = getbabelRelayPlugin(schema.data);
```

```javascript
//webpack.config.js
module.exports = {
  entry: "./index.js",
  output: {
      path: __dirname,
      filename: "bundle.js"
  },
  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: "babel-loader"},
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel', query: {stage: 0, plugins: ['./test']}
      }
    ]
  }
};
```



You are probably right about the starter-kit.
But I'd really love to use my own GraphQL Server (which is already ready).
Also the starter-kit + tutorial both looked really intimidating for a newby like me.

**Comment by josephsavona** [comment]
Cool, sounds like the config is not a problem. 

>  the starter-kit + tutorial both looked really intimidating for a newby like me

Thanks for this feedback! We'll keep on improving these areas - if there are specific items that were unclear, please open a new issue - or submit a PR!
