### ISSUE TITLE
How to update the optimistic response from a RANGE_ADD mutation?

### ISSUE THREAD

**Issue by goras** [facebook/relay#1567]
I haven't found any info about this and I might have missed something obvious, but is this even possible?

Here's a snippet of my current approach of how to update an edge.

```
fragments: {
  author: () => Relay.QL`
    fragment on Author {
      id,
      books (first: $limit) {
        edges {
          node {
            id,
            title,
            ${BookUpdateMutation.getFragment('book')},
          },
        },
      },
      ${BookAddMutation.getFragment('author')},
    }
  `,
}
```

```
class BookAddMutation extends Relay.Mutation {
  ...
  getOptimisticResponse() {
    return {
      bookEdge: {
        node: {
          title: this.props.title,
        },
      }
    }
  }
  ...
}
```

This works if I wait for the server response before updating, but any attempt of updating the optimistic response gives the following error:
```
Uncaught Error: RelayQueryPath.createForID: Expected dataID to be a server id, got `client:-9349566615`.
```

**Comment by rtymchyk** [comment]
What does your config look like for the mutation?

**Comment by goras** [comment]
Thanks for your response!

Here's the config for the two mutations:

```
class BookAddMutation extends Relay.Mutation {
	...
	getConfigs() {
		return [{
			type: 'RANGE_ADD',
			parentName: 'author',
			parentID: this.props.author.id,
			connectionName: 'books',
			edgeName: 'bookEdge',
			rangeBehaviors: {
				'': 'append',
			},
		}]
	}
}
```

```
classBookUpdateMutation extends Relay.Mutation {
	...
	getConfigs() {
		return [{
			type: 'FIELDS_CHANGE',
			fieldIDs: {
				book: this.props.book.id,
			},
		}]
	}
}
```

**Comment by rtymchyk** [comment]
Is there anything preventing you from waiting on the add mutation to complete? If the server has not yet responded with the created edge, then it's probably impossible to know what node to update. You can use relay.hasOptimisticUpdate to check if a node is still pending and prevent updated.

Will let you know though this is speculation, I haven't run into this scenario yet.

**Comment by goras** [comment]
Sure i can find a workaround and wait for the add-mutation to complete, but i guess i'm just asking for the sake of curiosity.

I don't really know relay and graphql that well yet, but i figured that when i receive an optimistic response from the add-mutation it uses an "client-id".
My interpretation was that i could mutate this response (only on the client-side), and when the initial request (the add-mutation) is done on the server,
the data from the newly created edge will be used by the update-mutation which will be able to update the edge on the server with the correct id.
On the client-side though, the optimistic response would be instantly created and updated.

Definitely risky in case the first mutation fails, but is it possible or am i just not understanding this correctly?

**Comment by rtymchyk** [comment]
I see what you mean. I think that a somewhat reasonable assumption to make, so I'll probably let someone else pitch in here in regards to whether or not that's built into relay.

**Comment by dwwoelfel** [comment]
Is this still a problem with Relay Modern? If you still have the problem with `optimisticResponse`, you should be able to handle it with the more imperative `optimisticUpdater`: https://facebook.github.io/relay/docs/mutations.html

**Comment by raymond-ji** [comment]
^Did anyone find out if this is now possible in Relay Modern? I'm just getting familiar with the framework and am wondering if this functionality exists.
