### ISSUE TITLE
Getting pure GraphQLErrors.

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/relay#1569]
When I throw a `GraphQLError` such as `throw new GraphQLError('test')`, the error value in the `render()` callback looks something like this and is difficult to handle:

```js
Error: Server request for query `Index` failed for the following reasons:

1. test
    at RelayDefaultNetworkLayer.js:66
    at tryCallOne (core.js:35)
    at core.js:121
    at JSTimers.js:116
    at Object.callTimer (JSTimersExecution.js:82)
    at Object.callImmediatesPass (JSTimersExecution.js:188)
    at Object.callImmediates (JSTimersExecution.js:204)
    at MessageQueue.js:195
    at guard (MessageQueue.js:39)
    at MessageQueue.__callImmediates (MessageQueue.js:194)
```

Is there a way to extract the pure error thrown by GraphQL? This formatting is neat and all,
but what if I return a JSON-stringified error like `{errorCode: 101, message: 'Permission to query field denied'}` and want to render a component based on the `errorCode`?

**Comment by dwwoelfel** [comment]
I believe this is fixed now in graphql/graphql-js. You can access an `orginalError` field in the error.
