### ISSUE TITLE
Future of mutation configs & documentation

### ISSUE THREAD

**Issue by dminkovsky** [facebook/relay#1570]
Looking at the code for [`writeRelayUpdatePayload`](https://github.com/facebook/relay/blob/7110c68f437391ad1ee54ab2c84fd8896a8662fb/src/traversal/writeRelayUpdatePayload.js#L79), one sees that only `NODE_DELETE`, `RANGE_ADD` and `RANGE_DELETE` mutation config settings are actually examined. Furthermore, for each of those config types, only a subset of the config params are actually used compared to the options presented in the documentation. 

For example: `NODE_DELETE` docs list `parentName`, `parentID`, `connectionName`, `deletedIDFieldName` config params, but if you look at the code, only `deletedIDFieldName` is actually used by the implementation. Same goes for `RANGE_ADD` and `RANGE_DELETE`. Each of these has a bunch of params but only a subset of those params appear to be used when writing update payloads.

Further, `FIELDS_CHANGE` appears to be [totally ignored](https://github.com/facebook/relay/blob/7110c68f437391ad1ee54ab2c84fd8896a8662fb/src/traversal/writeRelayUpdatePayload.js#L95-L106) with the update happening automatically.

Is my understanding correct? I don't know the history of this codebase too well, so I am wondering: are these configs going away or being simplified given the migration from tracked to static? 

Thank you,
Dmitry

PS. I know questions are supposed to be posted to SO, but I am posting here because this seems to be internals-specific enough that SO didn't seem appropriate. My apologies if that is incorrect. Please let me know and I will migrate my question to SO.

**Comment by josephsavona** [comment]
Note that only some of the config options affect the way mutation *payloads* are handled (what you see in `writeRelayUpdatePayload`). The other config options affect the way the mutation *query* is constructed.

**Comment by dminkovsky** [comment]
Ah hah. Thank you. So since mutation query construction is going away--
those params won't be used.

So if you're using `RelayGraphQLMutation`, which doesn't construct queries,
you can skip those params?

**Comment by josephsavona** [comment]
Yup!

**Comment by dminkovsky** [comment]
Cool! Thank you. I guess it makes sense to just close this, then.
