### ISSUE TITLE
Relay.GraphQLMutation mutation with arguments - transformed field name?

### ISSUE THREAD

**Issue by Rodeoclash** [facebook/relay#1573]
Given a mutation using the new `Relay.GraphQLMutation` that uses arguments (in this case year) Example:

```
const query = Relay.QL`mutation CourseToAnnualUpdateDeleteMutation {
  courseToAnnualUpdateDelete(input: $input) {
    clientMutationId
    viewer {
      courseToAnnualUpdates(year: $year) {
        ...
      }
    }
  }
}`
```

Relay returns an auto generated field name, as follows:

![screenshot - 200317 - 12 55 40](https://cloud.githubusercontent.com/assets/63807/24086958/9038b31c-0d6c-11e7-8611-9fae99034d7e.png)

What algorithm is used to auto generate the field name with arguments? (Assume it's a combination of arguments + values, In this case: `_courseToAnnualUpdates2RJpOA`).

It's impossible to craft an optimistic update without being able to perform the same transform to get the generated fieldname. Just the line in the codebase would be fine!

**Comment by anttimo** [comment]
@Rodeoclash in the optimistic update you should be able to just use the `courseToAnnualUpdates`, you don't need to know the generated field. Did you try that yet?

**Comment by josephsavona** [comment]
What @anttimo said - the optimistic update uses the plain field name.

**Comment by Rodeoclash** [comment]
@anttimo That was the first thing I tried, however the optimistic update didn't apply. After I inspected the generated field name and experimented with using that in the optimistic response I got it working correctly.

My assumption is that the field argument: `$year` is combined with the field name: `courseToAnnualUpdates` to automatically name the response field. Knowing how that is generated gives you enough information to construct the optimistic response yourself.

**Comment by anttimo** [comment]
It really should work with just the `courseToAnnualUpdates` and that's how we have been using it. Can you also post the `getOptimisticResponse` you have?

I'm probably best one to explain this but Relay names fields like `courseToAnnualUpdates` with params like that because you might have multiple containers depending on `courseToAnnualUpdates` with different params so it internally creates multiple lists for it. When you use the data in container context it will understand which one is the correct data to expose to that container. You shouldn't use or have a need use mutation data as it is. It has been bit hard for me to grasp how everything actually works and I did mistake of using the mutation response data as it is.

**Comment by Rodeoclash** [comment]
@anttimo I haven't been working on this feature recently, but have returned to it and rested.

Unless I craft the optimistic response to include the transformed field name, I simply don't get the optimistic response being applied.

Can you confirm you're using the new `Relay.GraphQLMutation` API with your version?

I'm going to close this for now as the next step is to create an example of this not functioning in the Relay playground. Once that's done I'll reopen.

**Comment by Rodeoclash** [comment]
I've almost finished constructing an example of this, however it appears the new Relay Mutation syntax is not yet supported in the Playground?

Apologies for the wall of text URL. I can't seem to use a URL shortener on it and see no easy way in the Relay Playground to link this.

I can't progress showing this bug until the playground supports the new `Relay.GraphQLMutation.create` API.

https://facebook.github.io/relay/prototyping/playground.html#source='use%20strict'%3B%0A%0A%2F%2F%20This%20should%20not%20be%20undefined%0Aconsole.log(Relay.GraphQLMutation)%0A%0Afunction%20Course(props)%20%7B%0A%20%20const%20%7B%0A%20%20%20%20course%2C%0A%20%20%20%20inUpdate%2C%0A%20%20%7D%20%3D%20props%0A%20%20%0A%20%20const%20handleClick%20%3D%20(kind)%20%3D%3E%20%7B%0A%20%20%20%20return%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20props%5Bkind%5D(course)%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%20%20%0A%20%20return%20(%0A%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%20%3Ctd%3E%7Bcourse.name%7D%3C%2Ftd%3E%0A%20%20%20%20%20%20%3Ctd%3E%7BinUpdate.toString()%7D%3C%2Ftd%3E%0A%20%20%20%20%20%20%3Ctd%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7BhandleClick('onClickWorking')%7D%3EAdd%20(working)%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7BhandleClick('onClickNotWorking')%7D%3EAdd%20(not%20working)%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Ftd%3E%0A%20%20%20%20%3C%2Ftr%3E%0A%20%20)%0A%7D%0A%0Aclass%20HelloApp%20extends%20React.Component%20%7B%0A%20%20%20%20%0A%20%20annualUpdate()%20%7B%0A%20%20%20%20const%20%7B%0A%20%20%20%20%20%20props%3A%20%7B%0A%20%20%20%20%20%20%20%20relay%2C%0A%20%20%20%20%20%20%20%20viewer%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20annualUpdates%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%20%3D%20this%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20return%20annualUpdates.find((annualUpdate)%20%3D%3E%20annualUpdate.year%20%3D%3D%3D%20relay.variables.year)%0A%20%20%7D%0A%20%20%20%20%0A%20%20handleClickWorking%20%3D%20(course)%20%3D%3E%20%7B%0A%20%20%20%20this.doCreate(%7B%7D%2C%20course)%0A%20%20%7D%0A%20%20%20%20%0A%20%20handleClickNotWorking%20%3D%20(course)%20%3D%3E%20%7B%0A%20%20%20%20this.doCreate(%7B%7D%2C%20course)%0A%20%20%7D%0A%20%20%20%20%0A%20%20doCreate(optimisticResponse%2C%20course)%20%7B%0A%20%20%20%20const%20mutation%20%3D%20Relay.GraphQLMutation.create(%0A%20%20%20%20%20%20Relay.QL%60mutation%20courseToAnnualUpdateCreate%20%7B%0A%20%20%20%20%20%20%20%20courseToAnnualUpdateCreate(input%3A%20%24input)%20%7B%0A%20%20%20%20%20%20%20%20%20%20clientMutationId%0A%20%20%20%20%20%20%20%20%20%20viewer%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20courseToAnnualUpdates(year%3A%20%24year)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20course%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%60%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20input%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20courseId%3A%20course.id%2C%0A%20%20%20%20%20%20%20%20%20%20annualUpdateId%3A%20this.annualUpdate().id%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20year%3A%20this.props.relay.variables.year%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20Relay.Store%2C%0A%20%20%20%20)%0A%20%20%20%20%0A%20%20%20%20mutation.applyOptimistic(%0A%20%20%20%20%20%20optimisticQuery%2C%0A%20%20%20%20%20%20optimisticResponse%2C%0A%20%20%20%20)%0A%20%20%7D%0A%20%20%20%20%0A%20%20render()%20%7B%0A%20%20%20%20const%20%7B%0A%20%20%20%20%20%20props%3A%20%7B%0A%20%20%20%20%20%20%20%20relay%2C%0A%20%20%20%20%20%20%20%20viewer%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20courses%2C%0A%20%20%20%20%20%20%20%20%20%20courseToAnnualUpdates%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%20%3D%20this%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20const%20renderedCourses%20%3D%20courses.map((course)%20%3D%3E%20%7B%0A%20%20%20%20%20%20const%20inUpdate%20%3D%20courseToAnnualUpdates.find((courseToAnnualUpdate)%20%3D%3E%20courseToAnnualUpdate.course.id%20%3D%3D%3D%20course.id)%0A%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3CCourse%0A%20%20%20%20%20%20%20%20%20%20course%3D%7Bcourse%7D%0A%20%20%20%20%20%20%20%20%20%20inUpdate%3D%7B!!inUpdate%20%7C%7C%20false%7D%0A%20%20%20%20%20%20%20%20%20%20onClickWorking%3D%7Bthis.handleClickWorking%7D%0A%20%20%20%20%20%20%20%20%20%20onClickNotWorking%3D%7Bthis.handleClickNotWorking%7D%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20)%0A%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Cp%3EAnnual%20update%20year%3A%20%7Bthis.annualUpdate().year%7D%3C%2Fp%3E%0A%20%20%20%20%20%20%20%20%3Ctable%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cthead%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3EName%3C%2Fth%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3EIn%20update%3F%3C%2Fth%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%3E%3C%2Fth%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%0A%20%20%20%20%20%20%20%20%20%20%3C%2Fthead%3E%0A%20%20%20%20%20%20%20%20%20%20%3Ctbody%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%7BrenderedCourses%7D%0A%20%20%20%20%20%20%20%20%20%20%3C%2Ftbody%3E%0A%20%20%20%20%20%20%20%20%3C%2Ftable%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%0A%20%20%7D%0A%7D%0A%0AHelloApp%20%3D%20Relay.createContainer(HelloApp%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20year%3A%20'2005'%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20viewer%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Viewer%20%7B%0A%20%20%20%20%20%20%20%20annualUpdates%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20year%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20courses%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20courseToAnnualUpdates(year%3A%20%24year)%20%7B%0A%20%20%20%20%20%20%20%20%20%20course%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0Aclass%20HelloRoute%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'Hello'%3B%20%20%2F%2F%20A%20unique%20name%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20viewer%3A%20(Component)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20Query%20%7B%0A%20%20%20%20%20%20%20%20viewer%20%7B%0A%20%20%20%20%20%20%20%20%20%20%24%7BComponent.getFragment('viewer')%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0A%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BHelloApp%7D%0A%20%20%20%20route%3D%7Bnew%20HelloRoute()%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B&schema='use%20strict'%3B%0A%0Aimport%20%7B%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLList%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%20%20GraphQLInt%2C%0A%20%20GraphQLNonNull%2C%0A%7D%20from%20'graphql'%3B%0A%20%20%0Aimport%20%7B%0A%20%20mutationWithClientMutationId%2C%0A%7D%20from%20'graphql-relay'%0A%20%20%0Aconst%20COURSES%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20id%3A%20'1'%2C%0A%20%20%20%20name%3A%20'Bachelor%20of%20Agriculture'%2C%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20id%3A%20'2'%2C%0A%20%20%20%20name%3A%20'Bachelor%20of%20Commerce'%2C%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20id%3A%20'3'%2C%0A%20%20%20%20name%3A%20'Bachelor%20of%20Design'%2C%0A%20%20%7D%2C%0A%5D%0A%20%20%0Aconst%20ANNUAL_UPDATES%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20id%3A%20'1'%2C%0A%20%20%20%20year%3A%20'2005'%2C%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20id%3A%20'2'%2C%0A%20%20%20%20year%3A%20'2006'%2C%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20id%3A%20'3'%2C%0A%20%20%20%20year%3A%20'2007'%2C%0A%20%20%7D%2C%0A%5D%0A%0Aconst%20COURSE_TO_ANNUAL_UPDATES%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20id%3A%20'1'%2C%0A%20%20%20%20courseId%3A%20'1'%2C%0A%20%20%20%20annualUpdateId%3A%20'1'%2C%0A%20%20%7D%0A%5D%0A%0Aconst%20CourseType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Course'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20name%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0Aconst%20AnnualUpdateType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'AnnualUpdate'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20year%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0Aconst%20CourseToAnnualUpdateType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'CourseToAnnualUpdate'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20course%3A%20%7B%20%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(CourseType)%2C%0A%20%20%20%20%20%20resolve%3A%20(parent)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20COURSES.find((course)%20%3D%3E%20course.id%20%3D%3D%3D%20parent.courseId)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20annualUpdate%3A%20%7B%20%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(AnnualUpdateType)%2C%0A%20%20%20%20%20%20resolve%3A%20(parent)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20ANNUAL_UPDATES.find((annualUpdate)%20%3D%3E%20annualUpdate.id%20%3D%3D%3D%20parent.annualUpdateId)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%20%20%0Aconst%20ViewerType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Viewer'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20courses%3A%20%7B%20%0A%20%20%20%20%20%20type%3A%20new%20GraphQLList(CourseType)%2C%0A%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20COURSES%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20annualUpdates%3A%20%7B%20%0A%20%20%20%20%20%20type%3A%20new%20GraphQLList(AnnualUpdateType)%2C%0A%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20ANNUAL_UPDATES%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20courseToAnnualUpdates%3A%20%7B%0A%20%20%20%20%20%20type%3A%20new%20GraphQLList(CourseToAnnualUpdateType)%2C%0A%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20year%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20resolve%3A%20(parent%2C%20args)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20const%20annualUpdate%20%3D%20ANNUAL_UPDATES.find((annualUpdate)%20%3D%3E%20annualUpdate.year%20%3D%3D%3D%20args.year)%0A%20%20%20%20%20%20%20%20return%20COURSE_TO_ANNUAL_UPDATES.filter((courseToAnnualUpdate)%20%3D%3E%20courseToAnnualUpdate.annualUpdateId%20%3D%3D%3D%20annualUpdate.id)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20mutation%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Mutation'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20courseToAnnualUpdateCreate%3A%20mutationWithClientMutationId(%7B%0A%20%20%20%20%20%20%20%20name%3A%20'courseToAnnualUpdateCreate'%2C%0A%20%20%20%20%20%20%20%20inputFields%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20courseId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20annualUpdateId%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(GraphQLString)%2C%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20outputFields%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20viewer%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(ViewerType)%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20resolve%3A%20(viewer)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20id%3A%20'viewer'%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20mutateAndGetPayload%3A%20(params)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20new%20Promise((resolve)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20COURSE_TO_ANNUAL_UPDATES.push(%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%3A%20COURSE_TO_ANNUAL_UPDATES%5BCOURSE_TO_ANNUAL_UPDATES.length%20-%201%5D%20%2B%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20courseId%3A%20params.courseId%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20annualUpdateId%3A%20params.annualUpdateId%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20setTimeout(resolve%2C%201000)%0A%20%20%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D)%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%20%20query%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20viewer%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20new%20GraphQLNonNull(ViewerType)%2C%0A%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20%7B%20id%3A%20'viewer'%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A

**Comment by wincent** [comment]
No future work is planned against the old APIs now that Relay Modern is out; all future development work is going to take place there. So, thanks for the discussion, but going to close this one so that we can keep the issue tracker focused on current issues and work.
