### ISSUE TITLE
Weird behavior of `RANGE_ADD` and `FIELDS_CHANGE` configs combined

### ISSUE THREAD

**Issue by kastermester** [facebook/relay#1577]
Hi!

I'm observing some strange behaviour with mutation configs. I have a mutation configured like this:

```js
export function replyToPulse(input, env, callbacks) {
    const query = Relay.QL`mutation replyToPulse {
        replyToPulse(input: $input) {
            clientMutationId
            pulseEdge {
                __typename
                cursor
                node {
                    ${Container.getFragment('pulse')}
                }
            }
            replyToPulse {
                id
                conversationCount
            }
        }
    }`;
    const variables = {
        input: {
            content: input.content,
            replyToPulseId: input.replyToPulseId
        },
    };
    return new Relay.GraphQLMutation(query, variables, null, env, callbacks, 'reply-to-pulse-' + input.replyToPulseId).commit([
        {
            type: 'FIELDS_CHANGE',
            fieldIDs: {
                replyToPulse: input.replyToPulseId,
            },
        },
        {
            type: 'RANGE_ADD',
            parentName: 'replyToPulse',
            parentID: input.replyToPulseId,
            connectionName: 'conversation',
            edgeName: 'pulseEdge',
            rangeBehaviors: () => 'append',
        },
    ]);
}
```

Configured like this the property `conversationCount` gets updated, however the newly added `pulseEdge` does not get added to the connection. However if I remove the `FIELDS_CHANGE` config, then everything works like I wanted it to work in the first place (`conversationCount` gets updated and the edge is added to the connection).

Having read through the documentation and some of the code I can't seem to find this behaviour documented, so I'm expecting something odd is going on?

I would have expected the posted config to work.

**Comment by sibelius** [comment]
@kastermester I think this is fixed on relay modern

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues. Also, while this issue applies to Relay Classic, our team is trying to focus on Relay Modern going forward.

If this is something you'd like to see happen, then we'd be happy to review a pull request.

If this issue is still important to you, please feel free to reopen it with an update.
