### ISSUE TITLE
How to modify query variables on the root query

### ISSUE THREAD

**Issue by blevine** [facebook/relay#1578]
Additional details for this issue can be found at http://stackoverflow.com/questions/43002555/strategy-for-modifying-a-route-parameter-dynamically-within-the-app (on which I haven't gotten much transaction as of yet).

My query looks something like this:

Original query: 
```
query {
  lunchForWeek(date: nn-nn-nn) {
    fields, fragments, etc.
  }
}
```
Since the variable is on the root query, it seems like the only way to modify that variable is on the Route. This means that the new value for that variable needs to communicated "outside" of Relay by a mechanism such as adding an event listener to the page and modifying window.location (there are others of course). But for my app, the date picker is in a child component in which case that child component's `handleDateChange()` would have to set window.location to cause the change.  This seems very wrong.

What I'd really like to do is move the root lunchForWeek query out of the Route and into the fragment of one of my top-level components so that that component can change the date via `props.relay.setVariables().`  However, there didn't seem to be a way to do this. I thought that I might define an empty query on the Route and then define the fragment 'on Query', but this doesn't seem to be supported.

I finally gave in and added another level to the query so that I could do:

New query:
```
query {
  lunchApi {
    lunchForWeek(date: nn-nn-nn) {
      fields, fragments, etc.
    }
  }
}
```
This works fine. The Route now has:
```
static queries = {
    lunchApi: () => Relay.QL`
        query {lunchApi}
    `,
  };
```
But since the original schema  is completely valid, it seems like Relay should support this. Furthermore, I was able to design around this because I happen to own the GraphQL schema.  But what if I were building an app around someone else's GraphQL API?

What I was trying to do originally seems like a valid use case so perhaps it is possible, but I just haven't figured out how to implement it.  Or is this a design limitation of Relay?

**Comment by amkoehler** [comment]
I ran into this problem as well. I ended up doing the same thing as you (nesting the field needing variables within the root). But, I think you can solve this by using React patterns for communication between components, and `Relay.Renderer`'s `render` method:

```
class ViewerList extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      date: new Date(),
    };
  }

  onDateChange = (newDate) => {
    this.setState({
      date: newDate,
    });
  }

  render() {
    return (
      <Relay.Renderer
        Container={Container}
        queryConfig={new AgilityViewersRoute({ date: this.state.date })}
        render={({ props }) => {
          return <Container {...props} onDateChange={this.onDateChange} />;
        }}
      />
    );
  }
}
```

I don't have an environment where I can test this, but I think it would work. The container component receives a prop called onDateChange, which when triggered will update the date in this parent component's state. This triggers the render method here and should with the new `queryConfig`, where `this.state.date` is the updated value.

**Comment by blevine** [comment]
Thank you @amkoehler. Yes, it seems like this should work although I wonder whether this use case is common enough to warrant an enhancement  at the Relay.Route level.  Even the ability to define an empty query and then a fragment on the query might be enough. But I'll definitely try out your suggestion. Leaving this issue open in case others want to comment on the enhancement idea or additional solutions.

**Comment by amkoehler** [comment]
Sounds good. I think a fragment on an empty query would violate some GraphQL standards, so I don't think that will ever be possible.

**Comment by blevine** [comment]
Not sure what the spec says on this (although I'll check).  I tried this out using graphiql against my graphql-ruby -based backend and it worked, e.g:

```
query {
  ...Base
}

fragment Base on Query {
  lunchApi {
    ...Lunch
  }  
}
  
fragment Lunch on Lunch_Api {
  lunchForWeek(date: "2017-03-28") {
    forWeekOf
    name
    menus {
      edges {
        node {
          description
          name
          image_url
        }
      }
    }
  }
}
```

**Comment by amkoehler** [comment]
Oh I see what you mean. Your fragment is on type `Query`. I thought you meant you wanted to do a query from the root directly on type `Lunch_Api`. Very cool!

**Comment by leebyron** [comment]
Sounds like this question was resolved. Great!
