### ISSUE TITLE
[RN] Locale isn't passed through fetch headers on Android

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/relay#1580]
I'd like to bring up some inconsistencies when using with React Native.

When doing Relay queries on iOS,
the request headers received on GraphQL's side contains a `locale` value like `en-US`.
On the other hand, Android does not send this value in the request.

My workaround for this is to obviously provide a custom header as addressed [here](https://facebook.github.io/relay/docs/guides-network-layer.html#content).
```
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://example.com/graphql', {
    headers: {
      Authorization: 'Basic *****',
      'Accept-Language': 'en-US',
    },
  })
);
```

Is there any way of adding locale on Android in the future?

**Comment by dwwoelfel** [comment]
The API was updated with Relay Modern. See https://facebook.github.io/relay/docs/network-layer.html
