### ISSUE TITLE
Relay.RootContainer: renderFailure() - error.source is undefined after server error

### ISSUE THREAD

**Issue by blevine** [facebook/relay#1582]
I'm testing out my error handling by forcing an authentication error.  The server correctly returns a 401 and in my renderFailure callback I can see that the error.response.statusText is "Unauthorized". The server also returns a JSON response with additional information.  However error.source is undefined.  Shouldn't error.source contain the response from the server?

**Comment by dwwoelfel** [comment]
Will close since this is referencing the Relay Classic API. Please reopen if this is still important to you!
