### ISSUE TITLE
(classic) RelayContainer#shouldComponentUpdate does not pass arguments to specShouldComponentUpdate

### ISSUE THREAD

**Issue by dminkovsky** [facebook/relay#1584]
Would be helpful if it [passed its params](https://github.com/facebook/relay/blob/fcfe1b8496702ff29116445ee2c7b8453377159e/packages/react-relay/classic/container/RelayContainer.js#L765). Not sure how this is useful with the next arguments.

**Comment by kassens** [comment]
Yeah, this seems like an oversight. Feel free to send a PR :)

**Comment by dminkovsky** [comment]
Thanks I will!

вс, 2 апр. 2017 г. в 15:09, Jan Kassens <notifications@github.com>:

**Comment by josephsavona** [comment]
The original intended use-case was basically for forcing updates when you know that something on context could have changed that affects sub-components. But agree that it's reasonable to pass args.

**Comment by scottwarren** [comment]
I'd love to pick this up, but I'm a little unclear about which arguments should be passed. In my eyes it should either be the [arguments Object](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/arguments) or `nextProps` but I might misunderstand.

**Comment by scottwarren** [comment]
I guess another alternative is to put `nextState` and `nextProps` into an object, then apply `nextContext` - what do you guys think?

**Comment by dminkovsky** [comment]
Scott, that would be great! I think just passing the arguments straight
through with .`apply()`.

I haven't done this because

1) I don't need to anymore
2) I didn't know what tests to write/didn't feel like looking at existing
tests
3) Perhaps most importantly, the flurry of activity around Relay Modern

**Comment by scottwarren** [comment]
Hmm, good point about Relay Modern, I'm going to leave this alone.

**Comment by yuzhi** [comment]
Sorry for the late update. We've fixed this a while back. Currently the containers will reevaluate props when any of the passed in arguments has changed.
