### ISSUE TITLE
(classic) Incorrect error message

### ISSUE THREAD

**Issue by dminkovsky** [facebook/relay#1587]
Suppose I have a component like

```
export default React.createClass({

    displayName: 'RendererContainer',

    getInitialState() {
        return {
            id: null
        };
    },

    contextTypes: {
        relayEnvironment: PropTypes.instanceOf(Relay.Environment).isRequired,
    },

    handleShowDetails(id) {
        this.setState({id});
    },

    render() {
        const {id} = this.state;
        const {relayEnvironment} = this.context;
        return (
            <Relay.Renderer
                environment={relayEnvironment}
                queryConfig={{
                    name: 'route',
                    queries: {
                        session: () => Relay.QL`query { session }`,
                        node: () => Relay.QL`query { node(id: $id) }`
                    },
                    params: {
                        id,
                    },
                }}
                Container={Container}
                render={({props}) => {
                    if (!props) {
                        return null;
                    }
                    return (
                        <Container
                            {...props}
                            onShowDetails={this.handleShowDetails}
                        />
                    );
                }}
            />
        );
    },
});
```

Attempting to render this component yields the following error:

> RelayRecordStore.getDataID(): Argument to `node()` cannot be null or undefined.

This is incorrect because the argument __can__ be `undefined`. If `getInitialState()` is changed to return `undefined` for `id`, then the component renders fine, and the `node` query is simply not executed until `id` is set.

I've been using this as an alternative to the `@include` directive but noticed that, contrary to the above error message, it only works when `id` is `undefined`.

**Comment by wincent** [comment]
Further development work against the classic APIs is unlikely to occur now that Relay Modern is out, so I am going to close this in order to help keep the issue tracker clean and focused on the stuff that is currently being worked on. Thanks for posting though!

**Comment by dminkovsky** [comment]
Excellent. Main motivation really was to have this searchable in the issue
tracker in case anyone else encountered it. Thank you.

сб, 27 мая 2017 г. в 2:58, Greg Hurrell <notifications@github.com>:
