### ISSUE TITLE
Error: Introspection must provide input type for arguments.

### ISSUE THREAD

**Issue by davide-ganito** [facebook/relay#159]
My introspection query works fine, but when i try to transpile my code i get this error: "Introspection must provide input type for arguments.".
Somebody knows what's his meaning?

Thx!

**Comment by josephsavona** [comment]
This error originates from `graphql` - it appears that your schema file is missing a definition for an input argument. Can you share a link to your schema?

**Comment by davide-ganito** [comment]
There was a GraphQLList in the inputFields of a mutation causing the issue.
Aren't the List allowed in input fileds?

**Comment by dschafer** [comment]
> Aren't the List allowed in input fileds?

Lists should be allowed in input fields; can you post a gist on https://github.com/graphql/graphql-js/issues/151 of your schema? Sounds like this may be a bug in `buildClientSchema` where it doesn't allow that.

**Comment by davide-ganito** [comment]
Ok, I think it's my fault.
I was using a `GraphQLObjectType` rather than a `GraphQLInputObjectType` as type for the `GraphQLList`. Sorry...

**Comment by josephsavona** [comment]
No worries! Glad you got it sorted out.
