### ISSUE TITLE
Q: Testing Relay Containers

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#161]
```
Error: Invariant Violation: RelayContainer: `Relay(Dashboard)` was rendered
without a valid route. Make sure the route is valid, and make sure that it is
correctly set on the parent component's context (e.g. using <RelayRootContainer>).
```

What's the preferred way to unit test Relay container components?

**Comment by devknoll** [comment]
Relay has a `RelayTestUtils` helper that's used internally. Would it make sense to expose some of this for Relay clients to use?

**Comment by devknoll** [comment]
Just in case it helps anyone else: My current workflow with Jest is to define `__mocks__/react-relay` with:
```js
var Relay = require.requireActual('react-relay');

module.exports = {
  QL: Relay.QL,
  Mutation: Relay.Mutation,
  Route: Relay.Route,
  createContainer: (component) => component,
};
```
Then a component can be tested with:
```js
/* ... */

TestUtils.renderIntoDocument(
  <Dashboard {...fixtures} />
);

/* ... */
```

where `fixtures` is an object matching the expected shape of the GraphQL response/fragments. As a side note, it'd be awesome if fixtures like this could be automatically generated, given that we have a schema :smile:

**Comment by josephsavona** [comment]
@devknoll: That's a pretty solid solution. Relay will pass through any props whose name matches a `fragments` key as-is. You'll get a warning about fake data but this is safe to ignore in tests. 

Most of `RelayTestUtils` is intended for internal tests but we would definitely accept PRs to build a public `TestUtils`-esque API for Relay. `RelayTestUtils.createRenderer()` is a good place to start ;-)

**Comment by rterysen-openroad** [comment]
@devknoll Does __mocks__ live within Jest's __tests__ directory. 

Is there anywhere I can read about this or see a example in a little more detail?

**Comment by sibelius** [comment]
you can create a directory __mocks__

and create a react-relay.js file in it

**Comment by wbyoung** [comment]
If anyone else comes across this who is looking for a non-jest solution, replacing `Relay.createContainer` with a custom version that doesn't actually create the container may be helpful.

```js
Relay.createContainer = ((create) => {
  let disabled = 0;

  const replacement = (Component, ...args) => {
    const Container = create(Component, ...args);
    const Wrapper = (...args) => {
      if (disabled) { return new Component(...args); }
      else { return new Container(...args); }
    };

    Object.assign(Wrapper, Container);

    // allow context population when possible, but don't validate any props
    Wrapper.contextTypes = _.mapValues(
      Container.contextTypes || {}, _.constant(React.PropTypes.any)
    );

    return Wrapper;
  };

  replacement._real = create;
  replacement.disable = () => { disabled++; };
  replacement.enable = () => { disabled--; };

  return replacement;
})(Relay.createContainer._real || Relay.createContainer);
```

A more complete `mocha`/`enzyme` [example can be found here](https://github.com/airbnb/enzyme/issues/398#issuecomment-280167713).

**Comment by emwalker** [comment]
What is a recommended approach to testing client-side mutation and subscription code in an external project?

**Comment by emwalker** [comment]
Using Relay Modern, Jest and Enzyme together with the [approach above](https://github.com/facebook/relay/issues/161#issuecomment-134324986), I was running into global side effects arising from redefining `react-relay.js` in the `__mocks__` subdirectory of a component directory.  I was able to get around this by using a different approach:

```javascript
jest.mock('react-relay', () => ({createFragmentContainer: component => component}))
```
