### ISSUE TITLE
Relay Modern expects query type to be named Query

### ISSUE THREAD

**Issue by kassens** [facebook/relay#1624]
We should also support other names such as `Root`.

**Comment by leebyron** [comment]
Might blame to https://github.com/facebook/relay/blob/master/packages/react-relay/classic/store/RelayStoreConstants.js#L25

**Comment by robrichard** [comment]
I opened a PR to address this issue: https://github.com/facebook/relay/pull/1962

**Comment by leebyron** [comment]
Glad to see this fixed!
