### ISSUE TITLE
[Modern] compiler Watchman error

### ISSUE THREAD

**Issue by unirey** [facebook/relay#1626]
I get the following log:

```
> relay-compiler --src ./js --schema ./schema.json

HINT: pass --watch to keep watching for changes.
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

System: `Windows 10 x64`
Version: `"relay-compiler": "^1.0.0-rc.1"`

Can't find any mentions of Watchman in docs. 
Is this a Windows specific error, bug or is this just an "install step" left out from docs?

**PS!** I get the error with and without the `--watch` flag.

**Comment by mjmahone** [comment]
I believe you'll need to install and enable Watchman's alpha Windows release to get this to work: https://github.com/facebook/watchman/issues/19

**Comment by unirey** [comment]
Yes, I'll install it. I just found if weird that it's not mentioned anywhere.

**Comment by unirey** [comment]
Yes, I'll install it. I just found it weird that it's not mentioned anywhere.

**Comment by unirey** [comment]
@mjmahone As I suspected. I installed Watchman and added it to PATH. Compiler is working now.

**Comment by JCMais** [comment]
@mjmahone why is watchman needed without the `--watch` flag?

**Comment by seemple** [comment]
@mjmahone Hi! Could you please explain me how did add Watchman to PATH ? Thanks in advanced!

**Comment by unirey** [comment]
@seemple I don't remember, Im not too familiar with OS's mechanics & this is one of those things you don't do very often. But it's a general Windows question, search online for "how to add to windows path".
