### ISSUE TITLE
Release notes say "react-compiler" instead of "relay-compiler" [quickfix!]

### ISSUE THREAD

**Issue by eugene1g** [facebook/relay#1630]
Awesome work, everyone. The last few alphas made it possible use relay-modern with far fewer quirks.

One admin cleanup - the release notes at https://github.com/facebook/relay/releases/tag/v1.0.0-rc.1
say
`yarn add --dev babel-plugin-relay@dev react-compiler@dev`
should really be
`...relay-compiler@dev`

**Comment by kassens** [comment]
Thanks, just updated!
