### ISSUE TITLE
TODO note: Docs for the Relay "Environment"

### ISSUE THREAD

**Issue by yantonsoup** [facebook/relay#1632]
Docs show the following: 

`const network = Network.create(fetch); // TODO: still need to provide a non-FB fetch
`

Can we get a clearer description of what fetch is supposed to be here? A uri? A whole network setup?

**Comment by eugene1g** [comment]
Maybe this is helpful https://github.com/facebook/relay/blob/master/docs/modern/NetworkLayer.md

**Comment by josephsavona** [comment]
Yup, just added docs on the network layer! Looks like there are some broken links to it, though, will use this issue to track that.

**Comment by yantonsoup** [comment]
Wonderful! Thanks for help.

**Comment by eugene1g** [comment]
For my setup (Apollo server on the backend), I had to add the right headers like so - 
```js
headers: {
      authorization: "Bearer " + USERTOKEN,
      "content-type": "application/json"
    },
```

**Comment by yuzhi** [comment]
Looks like this has been resolved. Please reopen if you have more questions.
