### ISSUE TITLE
[modern] relay-compiler: `createRefetchContainer` expects a second argument of fragment definitions.

### ISSUE THREAD

**Issue by alex-wilmer** [facebook/relay#1635]
This is the result of running `"relay": "relay-compiler --src . --schema schema.graphql"`

This isn't a "relay" compliant schema, but is that the problem?

```
type Link {
  id: ID
  url: String
  description: String
  tags: [Tag]
}

type Mutation {
  createLink(url: String!, description: String, tags: [TagInput]): Link
  createTag(name: String!): Tag
}

type Query {
  links(id: ID): [Link]
  tags(id: ID): [Tag]
}

type Tag {
  id: ID
  name: String
  links: [Link]
}

input TagInput {
  name: String!
}

```

error:

```
Error: FindGraphQLTags: `createRefetchContainer` expects a second argument of fragment definitions.
    at invariant (/Users/awilmer/Projects/venn/node_modules/relay-compiler/bin/relay-compiler:4401:12)
    at CallExpression (/Users/awilmer/Projects/venn/node_modules/relay-compiler/bin/relay-compiler:4270:82)
    at visit (/Users/awilmer/Projects/venn/node_modules/relay-compiler/bin/relay-compiler:4408:6)
    at traverse (/Users/awilmer/Projects/venn/node_modules/relay-compiler/bin/relay-compiler:4421:8)
    at visit (/Users/awilmer/Projects/venn/node_modules/relay-compiler/bin/relay-compiler:4411:4)
    at /Users/awilmer/Projects/venn/node_modules/relay-compiler/bin/relay-compiler:4425:12
    at Array.forEach (native)
    at traverse (/Users/awilmer/Projects/venn/node_modules/relay-compiler/bin/relay-compiler:4423:13)
    at visit (/Users/awilmer/Projects/venn/node_modules/relay-compiler/bin/relay-compiler:4411:4)
    at /Users/awilmer/Projects/venn/node_modules/relay-compiler/bin/relay-compiler:4425:12
```

repo: https://github.com/alex-wilmer/venn

**Comment by josephsavona** [comment]
I don't see where in the repo you linked you have the createFragmentContainer call, can you provide a specific link? Note that the function signature is `createFragmentContainer(component, fragments)`: the error suggests the second parameter is missing.

**Comment by alex-wilmer** [comment]
I haven't written any front end code yet.. I'm just following the instructions in the "Get Started" section

**Comment by josephsavona** [comment]
Super weird. Does the string `createRefetchContainer` appear anywhere? Can you narrow down which src file is causing this error?

**Comment by alangenfeld** [comment]
I am guessing it is picking up a createRefetchContainer from inside node_modules. We should probably blacklist that directory but in the mean time you can point `--src` at a directory of just your js files.

**Comment by alex-wilmer** [comment]
@alangenfeld indeed it was picking up `node_modules`. Is this something actionable I can make a PR for?

**Comment by alangenfeld** [comment]
here is where we blacklist other directories 
https://github.com/facebook/relay/blob/master/packages/relay-compiler/bin/RelayCompilerBin.js#L40-L42
