### ISSUE TITLE
[Modern] Error: Must provide query string

### ISSUE THREAD

**Issue by jepezi** [facebook/relay#1638]
I'm playing around Relay Modern trying to convert the current relay-starter-kit project into modern one. I got compiler working so far. `npm run build` generates `__generated__/AppQuery.graphql.js`.

So I setup the client with environment and QueryRenderer. But the problem is when I go to http://localhost:3000. I got this error.

```
errors: [{message: "Must provide query string."}] (1)
operation: {fragment: Object, id: null, kind: "Batch", metadata: Object, name: "AppQuery", …}
variables: {count: 10}
```

Set up repo here. [jepezi/relay-starter-kit-modern](https://github.com/jepezi/relay-starter-kit-modern)

**Comment by jepezi** [comment]
Never mind. It appears that I didn't set the appropriate headers in the fetchQuery.

**Comment by brianorwhatever** [comment]
What headers were you missing?
