### ISSUE TITLE
[Modern] Error with .json schema

### ISSUE THREAD

**Issue by unirey** [facebook/relay#1639]
##### Docs: 

> The `relay-compiler` script requires both the directory which holds your source files as well as a path to your GraphQL schema in **either** a .json or .graphql schema file.

##### Log:

```
> relay-compiler --src ./js --schema ./schema.json

HINT: pass --watch to keep watching for changes.
Parsed default in 0.04s

Writing default
Error: Error loading schema. Expected the schema to be a .graphql file using the
GraphQL schema definition language.
```

##### JSON file:

```js
{
  "queryType": {
    "name": "Query"
  },
  "mutationType": {
    "name": "Mutation"
  },
  "subscriptionType": null,
  "types": [
    {
      "kind": "OBJECT",
      "name": "Query",
      "description": null,
      "fields": [

  // etc
```

**Comment by sibelius** [comment]
you should use schema.graphql instead of schema.json

**Comment by unirey** [comment]
@sibelius 
Im trying to find a way to convert it to `.graphql` (I get that particular schema from GraphQL endpoint) but nethertheless, the main question to authors is if `.json` an upcoming feature or are docs misleading?

**Comment by sibelius** [comment]
use this script: https://github.com/entria/graphql-dataloader-boilerplate/blob/master/scripts/updateSchema.js#L40

**Comment by sibelius** [comment]
.json is used on Relay Classic

.graphql is used on Relay Modern

**Comment by unirey** [comment]
Thanks for you suggestion but doesn't this script require `schema` as a `GraphQLSchema` class? 

I need to convert `schema.json` to `schema.graphql` but this is probably not a suitable place for this particular issue and I should ask it somewhere else.


@sibelius:
> .json is used on Relay Classic
> 
> .graphql is used on Relay Modern

Well, if that's true then I got an answer to the issue.

**Comment by leethree** [comment]
@unirey you can parse `schema.json` using `buildClientSchema` from `graphql/utilities`, and then print it using `printSchema`.

**Comment by sibelius** [comment]
@leethree could you provide a code example of it?

**Comment by leethree** [comment]
This should work:

```js
import fs from 'fs';
import {
  buildClientSchema,
  printSchema,
} from 'graphql/utilities';

const schema = buildClientSchema(require('schema.json').data);
fs.writeFileSync(
  `schema.graphql`,
  printSchema(schema),
);
```

**Comment by unirey** [comment]
Like @sibelius mentioned, `schema.graphql` works with Relay Modern and `schema.json` doesn't. This would be an awesome addition to docs, if anyone is great with english and wants to become a Contributor:

[https://github.com/facebook/relay/blame/master/docs/modern/RelayCompiler.md#L48](https://github.com/facebook/relay/blame/master/docs/modern/RelayCompiler.md#L48)

@leethree Thanks for pointing me to `buildClientSchema`.

**Comment by kassens** [comment]
@leebyron: What's your intuition, should we just support `.json` everywhere in addition to `.graphql`?

**Comment by unirey** [comment]
@kassens My personal opinion is that if there are tools available to easily convert `.json` to `.graphql` (and there are as shown by **leethree**) and you have other things to do, it should be a very low priority feature.

**Comment by joho** [comment]
FWIW I'd appreciate if both formats were supported. 

I'm working with a graphql endpoint that currently only spits out the json form of the schema. I (now) understand there are workarounds, but I'm working on a react app that's currently ejected from `create-react-app` but I'd love to have a path back towards un-ejecting when https://github.com/facebookincubator/create-react-app/issues/462 arrives, which gets less and less likely as I add extra build steps into the process.

**Comment by leebyron** [comment]
It's easy for us to support both, so we should @kassens

**Comment by leebyron** [comment]
Fwiw the Babel plugin supports both. This just seems like a small oversight in the compiler
