### ISSUE TITLE
Can't install 'Relay-Runtime'

### ISSUE THREAD

**Issue by yantonsoup** [facebook/relay#1645]
From Docs on relay network layer: 
https://facebook.github.io/relay/docs/network-layer.html

> Currently the easiest way to create a network layer is via a helper from the `relay-runtime` package:

`const {Environment, Network} = require('relay-runtime');`

But when I `npm install --save relay-runtime` I get an empty NPM package at v0.0.1 from here: https://www.npmjs.com/package/relay-runtime

Yet within the facebook relay github repo here: https://github.com/facebook/relay/tree/master/packages
 I can see there's a `relay-runtime` package at v1.0.0-rc.1

What's the right way to import that 'relay-runtime' package? What's going on with that NPM `relay-runtime` package right now?

Thanks!

**Comment by yantonsoup** [comment]
Fixed by uninstalling react-relay `yarn remove react-relay`  
And then reinstalling new release candidate version `yarn add react-relay@dev`

**Comment by Peping** [comment]
Thanks for providing a workaround. It's unfortunate that `relay-runtime` was not included in the current "stable" version of relay, despite being mentioned in the documentation.
