### ISSUE TITLE
dataID.substring is not a function

### ISSUE THREAD

**Issue by boosh** [facebook/relay#165]
Relay is making this request:
```
{"query":"query AppHomeRoute{user(id:1025){..._0c28183ce}} fragment _0c28183ce on User{id,username}","variables":{"userID":1025}}
```
My server replies with:
```
{"data":{"user":{"id":1025,"username":"Leia Skywalker"}}}
```
But then I get an error:
```
Warning: dataID.substring is not a function relay.js (line 1701)
```
Here's my route:
```
export default class extends Relay.Route {

  static queries = {
    user: Component => Relay.QL`
      query {
        user(id: $userID) {
          ${Component.getFragment('user')},
        },
      }
    `,
  };

  static paramDefinitions = {
    userID: {required: true},
  };

  static routeName = 'AppHomeRoute';
}
```
And `App.js`:
```
import 'babel/polyfill';

class App extends React.Component {
  render() {
    return (
      <div>
        <h1>User details</h1>
        <ul>
          <li>{this.props.user.username} (ID: {this.props.user.id})</li>
        </ul>
      </div>
    );
  }
}

export default Relay.createContainer(App, {
  fragments: {
    user: () => Relay.QL`
      fragment on User {
        id,
        username
      }
    `,
  },
});
```
Is the server replying with an unexpected response, or is this a problem in relay itself?

**Comment by josephsavona** [comment]
Are you using the `relay-starter-kit` or configuring things yourself? Be sure to include a polyfill for ES6 features - the examples all use the [`babel/polyfill`](https://github.com/facebook/relay/blob/master/examples/todo/js/app.js#L1).

**Comment by josephsavona** [comment]
Also - thanks for providing so much information! Makes it super easy to debug :+1:

**Comment by boosh** [comment]
Yes, I used relay-starter-kit to begin with. I'm hooking it up to a sangria (sangria-graphql.org) server and I'm trying to work out whether the problem is that sangria isn't returning compatible data, or whether the problem is with relay/relay-starter-kit/what I've done.

**Comment by josephsavona** [comment]
The sample payload you posted looks correct. If you breakpoint at the error, what is the value of `dataID`? What browser are you using?

**Comment by boosh** [comment]
I'm using Chrome Version 44.0.2403.157 (64-bit) on OSX. I get the same issue in Firefox 39.0.3.

It's difficult to see what's going on. It seems to be an issue with resolving a promise. If that's as useful as I imagine I'll create a repo with my client and server in so you can tinker yourself. That'll probably be tomorrow.

**Comment by gabriel-laet** [comment]
Looks like an issue in your schema. How is your schema defined? 
Make sure you're using `graphql-relay` and `globalIdField` to define your object's IDs.

**Comment by josephsavona** [comment]
Ohh got it - `id` should be a string, not an int.

**Comment by boosh** [comment]
Awesome! Thank you! Yes, I thought I was optimising my schema by changing ID to be an int. I've changed it to a string and it works now.

**Comment by josephsavona** [comment]
Awesome, glad you got it sorted. And thanks for following up!
