### ISSUE TITLE
Question : how to use same fragment on multiple node

### ISSUE THREAD

**Issue by matart15** [facebook/relay#1651]
I have following graphql
```
{
  viewer{
    user(id: 1){
      posts(first: 2)
    }
    place(id: 1){
      posts(first: 2)
    }
  }
}
```

I am not sure how to create `PostList` react component. I tried fragment on `PostConnection`

```
class PostList ...

export default Relay.createRenderer(PostList , {
  fragments: {
    posts: () => Relay.QL`
      fragment on PostConnection {
        ...
      }
    }`
  }
}
```
then inside  `User` and `Shop` it is like 
```
{
  viewer{
    user(id: 1){
      posts(first: 2){
        $PostList.getFragment('post')
      }
    }
  }
}
```
```
{
  viewer{
    shop(id: 1){
      posts(first: 2){
        $PostList.getFragment('post')
      }
    }
  }
}
```

But now i have  to write pagination logic twice.

---------
if I try to include pagination logic in `PostList`, I have to include PostConnection in fragment. 
now I have to create `postList` fragment on `User` and `Shop`. That means I have to create it twice.

---------
My guess is that I have to create one more layer of react component outside `PostList` and inside`Shop` and `User` component.
But how?. 
Or is there any other better solution?

**Comment by wincent** [comment]
Thanks for posting! I'm closing issues against the Relay Classic API now that Relay Modern is out. In the concrete case of this question, Relay Modern no longer uses `Relay.QL` strings but rather vanilla, static GraphQL, so fragments can be re-used using standard GraphQL fragment spreads. Please file any questions or bug reports against the new API as separate issues.
