### ISSUE TITLE
[Modern] GraphQL Relay Specification and node root query

### ISSUE THREAD

**Issue by tlvenn** [facebook/relay#1653]
Hi,

I understand that global ids and to that regard the Node interface is a useful concept to help normalize the cache but I wonder if Relay Moderm actually leverage the node root query to refetch any node, it seems to go against the concept of static / persisted queries.

Thanks

**Comment by josephsavona** [comment]
Relay Modern doesn't dynamically construct any queries on behalf of the developer. As such, the use of a `node(id)` root field in the schema is purely optional. However, it can be a useful way to write queries that need to refetch arbitrary objects, for example in the statically defined queries for a RefetchContainer.

**Comment by tlvenn** [comment]
Thanks for the clarification @josephsavona.

Regarding the normalisation of the cache, does Relay Modern leverage the Node interface to do that transparently or that is not a requirement at all and one can give Relay Modern a `dataIdFromObject` function similarly to how Apollo works in that regard ?

**Comment by tlvenn** [comment]
Formulating my question with a little bit more clarity... Does Relay Modern need the `Node` interface to properly normalize its cache or can I tell it how to fetch id out of object ?

**Comment by josephsavona** [comment]
Relay Modern relies on the `Node` interface and `id` field for object normalization. This is a tradeoff for performance reasons: calling a `dataIdFromObject()`-style function to determine the id of every object during normalization can incur overhead that we would prefer to avoid. Along with folks from Apollo and others in the community, we are exploring the idea of a defining the behavior of an `__id` field in the GraphQL specification for this purpose.

**Comment by tlvenn** [comment]
Great, thanks for the feedback, makes sense.
