### ISSUE TITLE
[Modern] Client schema docs and examples

### ISSUE THREAD

**Issue by ivosabev** [facebook/relay#1656]
Any idea when docs and examples would be available?

> Client Schema Extensions 
> The Relay Modern Core adds support for client schema extensions. These allow Relay to conveniently store some extra information with data fetched from the server and be rendered like any other field fetched from the server. This should be able to replace some use cases that previously required a Flux/Redux store on the side.

https://facebook.github.io/relay/docs/new-in-relay-modern.html#client-schema-extensions

**Comment by leethree** [comment]
👍 I was trying to find any reference to how to do "client schema extensions" but failed.

**Comment by mjmahone** [comment]
My suspicion is it'll happen in an example in [RelayExamples](https://github.com/relayjs/relay-examples) before hitting official documentation here. I don't have a timeline, but that's your best bet for taking advantage of this feature. It already works (at least, it works on my machine :)), and you can find references to it via things like the [RelayFilterDirectivesTransform](https://github.com/facebook/relay/blob/master/packages/relay-compiler/transforms/RelayFilterDirectivesTransform.js), but getting this to work outside the FB environment hasn't yet happened.

**Comment by abhishiv** [comment]
I would love to know more about this to as well.

This is what I figured out till now

1) `extendSchema` function to extend schema. Also it's interesting to note that transformers are using this function.

Still missing

1) How do I manually update the Relay store with data.

**Comment by josephsavona** [comment]
I tried documenting this the other day and realized that there is an issue with the OSS compiler that prevents schema extensions from being defined. Once this is fixed we can document this feature. 

Cc @kassens

**Comment by unirey** [comment]
Any news on this? 
Maybe you could show us how it's used? Maybe we could help with PRs or test in different environments.

**Comment by josephsavona** [comment]
@unirey The idea is that you can do something like this:

```
// client-schema.graphql
extend type SomeType {
  client: Foo
}
type Foo {
  name: String
}

// compile script:
relay-compiler --schema schema.graphql --client-schema client-schema.graphql ...

// container fragment
graphql`
  fragment on SomeType {
    client
  }
`

// mutation updater
function updater(store) {
  const someValue = store.get(idOfValueOfSomeType);
  someValue.setValue("Foo", "client");  // value, field name
}
```

The missing part is that the oss compiler binary doesn't expose a way to tell the compiler about the client schema - all the primitives exist in the compiler to support client fields, and the runtime supports them as regular fields.

**Comment by fsenart** [comment]
Hi there 
Please, do you have any news and/or roadmap about this compiler feature?

**Comment by chadfurman** [comment]
FYI anyone new to react / relay looking for a temporary workaround, a "dirty" solution as suggested in https://github.com/facebook/relay/issues/1787 is to use context at the application root

**Comment by chadfurman** [comment]
@josephsavona In terms of changes, we're looking at :

https://github.com/facebook/relay/blob/master/packages/relay-compiler/generic/core/RelayCompiler.js#L52
```
class RelayCompiler {
  _context: RelayCompilerContext;
  _schema: GraphQLSchema;
  _transformedQueryContext: ?RelayCompilerContext;
  _transforms: CompilerTransforms;

  // The context passed in must already have any Relay-specific schema extensions
  constructor(
    schema: GraphQLSchema,
    context: RelayCompilerContext,
    transforms: CompilerTransforms,
  ) {
    this._context = context;
    // some transforms depend on this being the original schema,
    // not the transformed schema/context's schema
    this._schema = schema;
    this._transforms = transforms;
  }
```

We currently only have `schema` and `context` so we'll have to add in `clientSchema` and `clientContext` yes?  Then manage these separately?  Or do we have to have to merge the two schemas?

**Comment by josephsavona** [comment]
@chadfurman The compiler is configured to treat `this._schema` as the canonical server schema, while `this._context` has its own copy of the schema that may include client extensions. So I think what we probably want is to add an optional `clientSchema: string` constructor argument. Each time the context is rebuilt, do a final pass to parse the client schema and extend the `this._context`'s schema. Something like [these lines](https://github.com/facebook/relay/blob/master/packages/relay-compiler/transforms/__tests__/RelaySkipClientFieldTransform-test.js#L38-L39) to parse the client schema text into definitions and add them to context. Maybe do this [here](https://github.com/facebook/relay/blob/df7e236211f27e2d47b6ec58493a6f02da76d9d4/packages/relay-compiler/generic/core/RelayCompiler.js#L90) (or similar), ie constructing a fresh context just before actually running it through all the transforms.

**Comment by unirey** [comment]
@josephsavona Im trying to follow the discussion. Are the steps you mentioned only ones left?

> The missing part is that the oss compiler binary doesn't expose a way to tell the compiler about the client schema [...]

This is still missing? I don't even know what `oss compiler binary` exactly stands for or where do look.

**Comment by chadfurman** [comment]
@adjourn I'd guess this is the OSS compiler: https://github.com/facebook/relay/tree/master/packages/relay-compiler

**Comment by austinamorusotraceme** [comment]
This would be a super helpful feature.

**Comment by ryanpardieck** [comment]
Does the oss compiler support client schema extensions yet?

**Comment by chadfurman** [comment]
Maybe!!! http://graphql.org/graphql-js/utilities/#buildclientschema

**Comment by chadfurman** [comment]
Anyone who didn't notice this thread, also, which looks relevant: https://github.com/facebook/relay/issues/1787

**Comment by sibelius** [comment]
@jstejada any docs about this part?

**Comment by jstejada** [comment]
Hey @sibelius, unfortunately we haven't made any docs about this yet. The limitation mentioned earlier in this thread still stands. We'll keep you posted with any updates :)

**Comment by kassens** [comment]
This is roughly what needs to happen in the compiler: https://github.com/kassens/relay/commit/a51f9f22d83c79b9b08100c866dbb84da210eac1

That would start reading `*.graphql` files from somewhere where one might define schema extensions of the form:

```
extend type User {
  isTyping: boolean
}
```
This extra field can then be queried as usual using fragment containers and updated using `commitLocalUpdate` (permanent change to the store as opposed to optimistic updates that can be rolled back), approximately like this:
```
require('react-relay').commitLocalUpdate(environment, store => {
   store.get('some-user-id').setValue(true, 'isTyping');
});
```

(I'm typing this from memory and haven't actually tested this, but given there's a bunch of interest and this has been too long on the back burner for us, I figured someone might be interested to take a look).

**Comment by adjourn** [comment]
@kassens Thank you for looking into this. Im actually amazed that this and persist (#1846) are still missing while both are listed in Relay Modern features, I personally consider these very necessary features. I hope it commits sooner rather than later - wish I had time to learn Relay insides and help you out but Im working on a big project solo right now.

**Comment by sibelius** [comment]
@kassens @brysgo did this to make client extensions works: https://github.com/brysgo/create-react-app/blob/master/packages/react-scripts/scripts/relay.js#L75

does this look reasonable?

here a sample example of it https://github.com/brysgo/relay-example

**Comment by josephsavona** [comment]
@sibelius just mixing the client schema into the server schema won’t work: the compiler needs to know which fields/types are from which schema in order to strip out client-only portions of queries that it sends to the server. Th compiler binary needs to change to accept a second argument (eg `—client-schema`) and use that appropriately.

**Comment by brysgo** [comment]
Check the network layer in the example, it filters the local stuff. There is probably a better way, but it works.

**Comment by edvinerikson** [comment]
I opened a PR with some slight changes to what @kassens did. https://github.com/facebook/relay/pull/2264. I tested it on the Relay Todo app in the relayjs-examples repo. I can define extensions and see them being added to the concrete fragments but removed for the final query so seems to work.

**Comment by brysgo** [comment]
[My example](https://github.com/brysgo/relay-example) has been updated to use @edvinerikson's changes in #2264 if anyone is here looking for an example.

**Comment by jstejada** [comment]
any PR's to add docs for this would be accepted! The only important thing to note would be that client schema extensions only currently support additions to existing types and not adding entirely new types

**Comment by tslater** [comment]
I'm confused, isn't there still a limitation where the compiler needs to be altered to allow for client schema? Or was that solved in #2264? Is the only step now to get things documented?

**Comment by brysgo** [comment]
notwithstanding the limitation pointed out above, it is solved.

**Comment by alloy** [comment]
@tslater That’s correct, it was solved in #2264 and the only thing needed now is documentation.

**Comment by tslater** [comment]
@alloy Thanks for clarifying. I just noticed this in the release notes: 

> Extensions only work on existing types, and does not currently support adding client-only types to the schema.

Does that mean one needs to put any types they're using client side in their server/other schemas?

**Comment by alloy** [comment]
I believe so, yes. Maybe @edvinerikson can better help you with the details.

**Comment by edvinerikson** [comment]
I haven't tested adding new types, but I don't think there is any limitation. The compiler just takes all the extra documents and merges them into a complete schema (together with server schema). To also check if a type is from the server, they also track the server schema separately as well.

https://github.com/facebook/relay/blob/master/packages/relay-compiler/codegen/RelayFileWriter.js#L120
https://github.com/facebook/relay/blob/master/packages/relay-compiler/graphql-compiler/transforms/SkipClientFieldTransform.js#L115
https://github.com/facebook/relay/blob/master/packages/relay-compiler/graphql-compiler/core/GraphQLCompilerContext.js#L44

**Comment by jstejada** [comment]
@edvinerikson the main limitation right now is that records of those types will always get garbage collected, I /think/

@sibelius yeah I think that's a good idea

**Comment by istarkov** [comment]
So there are no way to prevent records to be collected from store?

i.e.
```
  commitLocalUpdate(environment, s => {
    const err = s.create('4', 'Error');
    err.setValue('4', 'id');
    err.setValue('Error message', 'message');
    root.setLinkedRecords([err], 'errors');
  });
```

'errors' array after `gc` contains `undefined`.

**Comment by lszomoru** [comment]
As I am reading through this issue it is not clear to me whether relay-compiler version 1.5.0 which was updated 2 months ago on npm supports client schema or not. If this version does not support it, is there an ETA for publishing a version that does? Thanks!

**Comment by istarkov** [comment]
It supports client schemas well, we use this feature in development.

**Comment by ivosabev** [comment]
Could anyone provide some meaningful examples, since docs are lacking?

**Comment by istarkov** [comment]
- place anywhere inside src folder your local schema name, give it `.graphql` extension for example `local.graphql`
- add inside local schema your types and extend server types 

```
# local.graphql
type Trace {
  id: ID!
  file: String
  line: Float
  what: String
  addr: String
}

type Error {
  id: ID!
  message: String
  prettyMessage: String
  operationName: String
  path: [String]
  trace: [Trace]
}

extend type Query {
  errors: [Error]
}
```

- run relay compiler as usual `relay-compiler --src ./src --schema {PATH_TO_SERVER_SCHEMA}`

- since now you can use local definitions above in your fragments or query 

```
const query = graphql`
  query AppQuery {
    ...serverStuff_root
    ...otherServerStuff_root
    errors {
      id
      message
      prettyMessage
      operationName
      path
      trace {
        id
        file
        line
        what
        addr
      }
    }
  }
`;
```

- now you need to add data in your relay store

```javascript
import { commitLocalUpdate, ROOT_ID } from 'relay-runtime';

const ROOT_TYPE = '__Root';
const ERR_TYPE = 'Error';
const TRACE_TYPE = 'Trace';

function addErrs(environment, errs) {

    commitLocalUpdate(this.environment, s => {
      let root = s.get(ROOT_ID);
      if (!root) {
        root = s.create(ROOT_ID, ROOT_TYPE);
      }

      const errRecords = errs.map(err => {
        const errRecord = s.create(err.id, ERR_TYPE);
        errRecord.setValue(err.id, 'id');
        errRecord.setValue(err.message, 'message');
        errRecord.setValue(err.prettyMessage, 'prettyMessage');
        errRecord.setValue(err.operationName, 'operationName');
        errRecord.setValue(err.path, 'path');

        /*
        file: String
        line: Float
        what: String
        addr: String
        */
        const traceRecords = err.trace.map(traceLine => {
          const traceLineRecord = s.create(traceLine.id, TRACE_TYPE);
          traceLineRecord.setValue(traceLine.id, 'id');
          traceLineRecord.setValue(traceLine.file, 'file');
          traceLineRecord.setValue(traceLine.line, 'line');
          traceLineRecord.setValue(traceLine.what, 'what');
          traceLineRecord.setValue(traceLine.addr, 'addr');
          return traceLineRecord;
        });

        errRecord.setLinkedRecords(traceRecords, 'trace');
        return errRecord;
      });

      const existingErrRecords = root.getLinkedRecords('errors') || [];

      root.setLinkedRecords([...errRecords, ...existingErrRecords], 'errors');
    });


    // Hack to prevent records being disposed on GC
    // https://github.com/facebook/relay/issues/1656#issuecomment-380519761
    errs.forEach(err => {
      const dErr = this.store.retain({
        dataID: err.id,
        node: { selections: [] },
        variables: {},
      });

      const dTraces = err.trace.map(tLine =>
        this.store.retain({
          dataID: tLine.id,
          node: { selections: [] },
          variables: {},
        }),
      );

      this.disposableMap[err.id] = () => {
        dErr.dispose();
        dTraces.forEach(dT => dT.dispose());
      };
    });
}
```

- don't forget to call dispose i.e `this.disposableMap[err.id]()` on err removal
- You win, you don't need recompose etc ;-) you can use relay for all

**Comment by kikoseijo** [comment]
Wow, thanks @istarkov , you are the ***** Boss!

**Comment by istarkov** [comment]
Also we use local type extensions, to add local properties to existing objects like isNew, then setting isNew in mutation updater, we can show that object just created, (updated) etc so you can use local schemes even without commitLocalUpdate

**Comment by MrSaints** [comment]
@istarkov Thanks for that, though, arguably not as straightforward as say, the way Apollo GraphQL does it. And from the looks of it, you can't do things like mutations?

**Comment by hisapy** [comment]
I found @istarkov findings super useful but didn't know where `this.store` comes from ...  So I did a little research and found that in Relay **1.6.0**  `retain` method is available directly from `environment`.

```javascript
const dErr = environment.retain({
    dataID: err.id,
    node: { selections: [] },
    variables: {},
});
```

I also found that you can access store from environment, useful if you want to test changes like the following

```javascript
describe("handleChange(field, value)", () => {
  test("updates userForm.user in local Relay store", () => {
    const firstName = "Roberto";
    const container = shallow(<UserForm relay={{ environment }} />).instance();
    container.handleChange("firstName", firstName);

    expect(
      environment
        .getStore()
        .getSource()
        .get("userForm:user").firstName
    ).toEqual(firstName);
  });
});
```

Just for the record  [relay-mock-network-layer](https://github.com/1stdibs/relay-mock-network-layer/blob/master/index.js) is really useful for this kind of tests.

**Comment by astenmies** [comment]
I'm trying to extend `type Whatever` in a clientSchema.graphql.

Relay compiler (v 1.5.0) has the flags: `--schema ./schema/schema.graphql --client-schema ./schema/client.graphql`

It gives me the following error:
GraphQLParser: Unknown field `contentText` on type `Whatever`

Any idea what's going on?

**Comment by JCMais** [comment]
This post on medium is really helpful too https://medium.com/@matt.krick/replacing-redux-with-relay-47ed085bfafe

**Comment by mattkrick** [comment]
thanks for the shoutout @JCMais! just a heads up, the client schema is ___not___ safe to use for fields that are mutated by server & optimistic updates. I wrote a fix for it here (https://github.com/facebook/relay/pull/2482) but it's been in PR purgatory for a few months :cry:

**Comment by MartinN3** [comment]
As @mattkrick and @josephsavona are working tough on #2482 - as we might see some improvements soon, it might be good time to start documenting those experimental features on that ### pull request🗡

**Comment by sibelius** [comment]
can we have a `fetchFnClient` in network layer that handle custom resolvers on client schema extensions?

`fetchFnClient` would receive resolvers that are not in server schema

**Comment by sibelius** [comment]
you can use this helper

```jsx
export const setLocal = (query: GraphQLTaggedNode, localData: object) => {
  const request = getRequest(query);
  const operation = createOperationDescriptor(request, {});

  env.commitPayload(operation, localData);
  env.retain(operation.root);  // <== here @en_js magic :wink:
};
```

To make sure relay does not garbage collect same graphql operation

**Comment by sibelius** [comment]
more blog posts here

https://babangsund.com/relay_local_state_management/
https://babangsund.com/relay_local_state_management_2/

anybody want to improve the docs with all this info?

**Comment by mattkrick** [comment]
@sibelius thanks for keeping this alive!

Using hooks for local data is pretty easy, too. That way you don't need a clunky QueryRenderer.

```
const data = useLocalQuery<SnackbarQuery>(query)
```


```
const useLocalQuery = <TQuery extends {response: any; variables: any}>(
  environment: Environment,
  query: any,
  inVariables: TQuery['variables'] = {}
): TQuery['response'] | null => {
  const variables = useDeepEqual(inVariables)
  const [dataRef, setData] = useRefState<SelectorData | null>(null)
  const disposablesRef = useRef<Disposable[]>([])
  useEffect(() => {
    const {getRequest, createOperationDescriptor} = environment.unstable_internal
    const request = getRequest(query)
    const operation = createOperationDescriptor(request, variables)
    const res = environment.lookup(operation.fragment, operation)
    setData(res.data || null)
    disposablesRef.current.push(environment.retain(operation.root))
    disposablesRef.current.push(
      environment.subscribe(res, (newSnapshot) => {
        setData(newSnapshot.data || null)
      })
    )
    const disposables = disposablesRef.current
    return () => {
      disposables.forEach((disposable) => disposable.dispose())
    }
  }, [environment, setData, query, variables])
  return dataRef.current
}
```

**Comment by sibelius** [comment]
we now have official docs about how to use client schema extensions:

https://relay.dev/docs/en/next/local-state-management

thanks to @babangsund for the great work exploring and documenting this
