### ISSUE TITLE
[modern] babel-plugin-relay requires compat=true

### ISSUE THREAD

**Issue by eugene1g** [facebook/relay#1657]
Seems like `createFragmentContainer` basically [proxies](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayFragmentContainer.js#L198) to `ReactRelayCompatContainerBuilder` which [checks the structure of the passed fragment](https://github.com/facebook/relay/blob/master/packages/react-relay/compat/ReactRelayCompatContainerBuilder.js#L162) to make sure it's an object, because that's how Relay Classic defined fragments (I think?).

In Relay Modern, if babel-plugin-relay is configured without compat=true then it will generate fragments as [functions](https://github.com/facebook/relay/blob/master/packages/babel-plugin-relay/createModernNode.js#L27), not as objects. This will fail the check in `ReactRelayCompatContainerBuilder` and break the execution chain. If compat=true is used, then the plugin generates code for each fragment like so -
```
{
  mydataprop: {
    modern: function modern() {
      return require('....graphql);
    },
    classic: function classic() {
      return bigcomplexobject;
   }      
}
```
And this fools the compat container into thinking it's a valid fragment (while it's just a random object).

Am I am missing on how to create modern components without involving `ReactRelayCompatContainerBuilder`, or maybe the fragment check needs to be expanded to accept functions?

**Comment by eugene1g** [comment]
Possibly related https://github.com/facebook/relay/pull/1647

**Comment by leebyron** [comment]
Merging this issue into #1631
