### ISSUE TITLE
[Modern] relay-compiler errors on mutation

### ISSUE THREAD

**Issue by lpalmes** [facebook/relay#1660]
I've cloned this repo `https://github.com/apollographql/relay-modern-hello-world` by @stubailo and everytime i run `yarn run relay` i got this message
```
Writing default
Error writing modules:
TypeError: type.getFields is not a function
Unchanged: 3 files
Written default in 0.29s
✨  Done in 1.72s.
```
which i don't know what `TypeError: type.getFields is not a function` means, i got three other queries and they compile perfectly but i can't get it to work with mutation. I'm not sure if i'm doing something wrong, any help would be greatly appreciated.

This are my files
```javascript
//src/mutations/CreateCuisineMutation.js
import { commitMutation, graphql } from "react-relay";

const mutation = graphql`
mutation CreateCuisineMutation($name: String!) {
  createCuisine(name: $name) {
    id
    name
  }
}
`;

function commit(enviroment, name) {
  return commitMutation(enviroment, {
    mutation,
    variables: { name },
    onCompleted: response => {
      console.log("Success!");
    },
    onError: err => console.error(err)
  });
}

export default { commit };
```
This is my schema for cuisine mutations
```
type Mutation {
  createCuisine(name: String!): Cuisine
}

type Cuisine {
  id: ID!
  name: String!
  created: String
  updated: String
}
```

**Comment by lpalmes** [comment]
I've been doing some testing, i've found out that it works when using an `input` type but not String, neither ID.

```javascript
import { graphql, commitMutation } from "react-relay";

const mutation = graphql`
mutation CreateFoodListMutation($input: FoodListInput!) {
  createFoodList(input: $input) {
    id
    name
  }
}
`;
```

Schema.graphql
```
type FoodList {
  id: ID!
  name: String!
  items: [MenuItem]!
  created: String
  updated: String
}

input FoodListInput {
  name: String!
  items: [String!]!
}

type Mutation {
  createFoodList(input: FoodListInput!): FoodList
}
```

**Comment by tlvenn** [comment]
My guess is that mutations have to follow the GraphQL Relay spec in that regard and this is still a requirement with Modern:

> https://facebook.github.io/relay/docs/graphql-mutations.html

Great article on designing mutations which happen to align with the relay spec and give you some perspective as to why it's a good idea: https://dev-blog.apollodata.com/designing-graphql-mutations-e09de826ed97

**Comment by tlvenn** [comment]
At the same time, I am surprised it worked even though your input does not have a `clientMutationId`. Modern might have relaxed some of the requirements when it comes to mutations..

@josephsavona could you clarify this for us please ? Thanks.

**Comment by lpalmes** [comment]
Thanks @tlvenn, i've used to run my graphql server by a simple POST via fetch, so i see there are some conventions that i have to follow when moving to relay

**Comment by mjmahone** [comment]
This is probably simply a bug that went untested, because that's how most mutations within Facebook are done (with a single InputObject), as most RelayModern mutations have been migrated from classic Relay. Fixing this would make a great PR, if there were tests included with it to make sure new features don't accidentally break it again.

Modern *should* be able to allow at least anything within the GraphQL spec (besides a few quirks, like needing to name your fragments in specific ways to match your modules). We might not be 100% compliant, but in any instance where RelayModern is not, PRs to get closer are highly appreciated.

**Comment by josephsavona** [comment]
Yeah, I think this is just a bug as @mjmahone mentioned. Do you have the full stack trace of the error? 

Note that Relay Modern relaxes all the restrictions from Relay classic for mutations:
- Arbitrary root fields/arguments are supported (can be more than one argument of any  name(s), doesn't have to be an input object)
- No need for a `clientMutationId` field

Please file bugs / send PRs if this isn't working! Stack trace would help in this case.

**Comment by lpalmes** [comment]
Thanks @josephsavona, i do not have a stack trace, that's all the logs i've found, i'm not really familiar with relay codebase neither but i'm trying to get into it. I will try with rc2 today and let you know how it goes, thanks!

**Comment by andyfen** [comment]
finding something similar when theres no $input value used
example (working in graphiQL)
```
mutation IncrementCountMutation {
  incrementCount {
    count
  }
}
```
compiler returns undefined
> Writing default
> Error writing modules:
> TypeError: Cannot read property 'type' of undefined

**Comment by lpalmes** [comment]
It seems that relay-compiler is trying to get each argument from the ast and get it's fields, given that i get `TypeError: type.getFields is not a function` and my String in `mutation CreateCuisineMutation($name: String!)` has no fields

**Comment by dmbrowne** [comment]
I also have an error when running the compiler for a mutation.
```
Writing default
Error writing modules:
RangeError: Maximum call stack size exceeded
```
However this error only occurs when the graphQL *object Type* that I'm mutating (e.g. `User`) has field that is of another *object Type* (e.g. `ProfileImage`)
```
input CreateProfileImageInput {
  userId: ID
  user: CreateUserInput
  blobFieldName: String!
  clientMutationId: ID
}

type CreateProfileImagePayload {
  changedProfileImage: ProfileImage
  changedEdge: ProfileImageEdge
  viewer: Viewer
  clientMutationId: String
}

type ProfileImage implements Node, Timestamped, Blob {
  user: User
  createdAt: DateTime!
  blobMimeType: String
  blobUrl: String
  id: ID!
  modifiedAt: DateTime!
}

type User implements Node, Timestamped {
  # The user's username.
  username: String!
  lastLogin: DateTime!
  description: Text
  id: ID!
  roles(where: RoleWhereArgs, orderBy: [RoleOrderByArgs], first: Int, after: String, last: Int, before: String): UserRolesConnection
  profileImage(where: ProfileImageWhereArgs, orderBy: [ProfileImageOrderByArgs], first: Int, after: String, last: Int, before: String): ProfileImageConnection
  modifiedAt: DateTime!
  createdAt: DateTime!
}
```

When I attempt compile the following graphql mutation, I get the error I stated above
```
const mutation = graphql`
	mutation profileActionsUploadImageMutation($input: CreateProfileImageInput!){
		createProfileImage(input: $input) {
			changedProfileImage { blobUrl }
		}
	}
`
```

Any way I can fix this issue?
I cant even build my code :(

**Comment by dmbrowne** [comment]
I'm still struggling with this error, has anyone experienced it yet and found a way to solve it?

**Comment by lpalmes** [comment]
@dmbrowne i've managed to convert all my mutations to have a single input object, and that solved it, but the compiler does not know how to handle multiple parameters yet, i think it will soon, but right now using a single input object does the job, let me know if you need any help on that

**Comment by henryqdineen** [comment]
@lpalmes I am running into the same error as you. Was the issue that you had multiple arguments or was it because your argument was a `String!` and not a more complex type?

**Comment by lpalmes** [comment]
Hey @henryqdineen, sorry for the delay, it seems that the compiler only works with input type objects, so `String!`, `Int!`, etc will not work for now

**Comment by josephsavona** [comment]
Are you using Relay Modern or classic? The compiler is capable of handling arbitrary mutation inputs, but Relay classic has a limitation that mutations have a single argument that is an input object. See https://facebook.github.io/relay/docs/graphql-mutations.html for more on the limitation in classic.

**Comment by mike-marcacci** [comment]
This is related to #1775 and #1825

**Comment by kassens** [comment]
Closing in favor of the 2 linked issues.
