### ISSUE TITLE
[Modern] babel-plugin-relay not dealing w/ different query-type name

### ISSUE THREAD

**Issue by femesq** [facebook/relay#1667]
I'm using [graphene](https://github.com/graphql-python/graphene) on Django, that can generate `schema.json`. Converting it to `schema.graphql` using [this script](https://github.com/facebook/relay/issues/1639#issuecomment-295314954) works fine.

Results:
```
schema {
  query: AllQueries
  mutation: AllMutations
}

type AllMutations {
  ...
}

type AllQueries {
  ...
}

```

Trying to convert to Relay-Modern rises this error:
```
-- Relay Transform Error -- AppPrivate --

File:  xxx/app/scripts/containers/AppPrivate.js
Error: TypeError: Cannot read property 'toString' of undefined
    at RelayQLType.getName (xxx/node_modules/babel-plugin-relay/lib/RelayQLAST.js:482:86)
    at RelayQLType.mayImplement (xxx/node_modules/babel-plugin-relay/lib/RelayQLAST.js:632:17)
    at shouldGenerateIdFragment (xxx/node_modules/babel-plugin-relay/lib/RelayQLPrinter.js:569:27)
...
```
Line `babel-plugin-relay/lib/RelayQLAST.js:482` corresponds to [this](https://github.com/facebook/relay/blob/master/packages/babel-plugin-relay/RelayQLAST.js#L525).

Changing `schema.graphql` by hand to this:
```
// Removed schema definition

type AllMutations {
  ...
}

type Query {  //  <= HERE
  ...
}

```

Solved the problem...

I'm using `babel-plugin-relay` w/ `compat: true` config.
All Relay packages are on `rc2`. The problem already occurred on `rc1`...

**Comment by tlvenn** [comment]
Looks pretty similar with this https://github.com/facebook/relay/issues/1624

**Comment by eugene1g** [comment]
Had the same issue, but only with `compat: true`

**Comment by skosch** [comment]
To clarify, until this is fixed, you'll have to replace all instances of `AllQueries` in your schema.graphql (or `RootQueryType`, or whatever yours is called) with the `Query` from [here](https://github.com/facebook/relay/blob/master/packages/react-relay/classic/store/RelayStoreConstants.js#L25)

**Comment by robrichard** [comment]
I opened a PR to address this issue: https://github.com/facebook/relay/pull/1962
