### ISSUE TITLE
[Modern] React Native component library use through npm

### ISSUE THREAD

**Issue by trevordmiller** [facebook/relay#1674]
I wired up a GraphQL server to a component library using Relay Modern:
https://github.com/trevordmiller/cortex-components/commit/a98eaf3e0b83636006493c6edde661fb97de599c

Using this component library works in React (using the Create React App setup):
https://github.com/trevordmiller/cortex-clients/blob/master/web/src/index.js#L3

But I get an error that `relay` isn't found in React Native (using the Create React Native App setup):
https://github.com/trevordmiller/cortex-clients/blob/master/native-mobile/App.js#L2

![image](https://cloud.githubusercontent.com/assets/5497885/25288744/f36b1c74-2683-11e7-86af-0ff5ef05149b.png)

Since [the `relay` npm package](https://www.npmjs.com/package/relay) doesn't have anything to do with Facebook's Relay Modern, I assume this error has something to do [with the `babel-plugin-relay`](https://github.com/trevordmiller/cortex-components/blob/master/package.json#L29-Lundefined), but don't know.

The component library was working on both platforms before switching from static data to Relay Modern.

**Comment by trevordmiller** [comment]
@dikaiosune might have some ideas as this could be related to React Native / Create React Native App

**Comment by sibelius** [comment]
@trevordmiller check my PR here: https://github.com/sibelius/ReactNavigationRelay/pull/5

**Comment by trevordmiller** [comment]
@sibelius I looked through the PR and it seems I already have things set up as you for React Native, with the only difference being I'm using an npm package with components that use Relay inside the React Native project, so the React Native project doesn't use Relay directly.

**Comment by trevordmiller** [comment]
fyi, I'm on latest release candidates of all Relay Modern packages https://github.com/trevordmiller/cortex-components/commit/8441a190bd160e38955db5ab7c7cad38a3d30a27

**Comment by sibelius** [comment]
@trevordmiller I think you maybe need to setup a .babelrc on your `cortex-components`

**Comment by trevordmiller** [comment]
@sibelius I have my babel config in the package.json which works with React Native / Create React Native App: https://github.com/trevordmiller/cortex-components/blob/master/package.json#L43-L51

**Comment by trevordmiller** [comment]
So, adding duplicate babel plugins in the consuming react native project resolved the errors:
https://github.com/trevordmiller/cortex-clients/commit/1c39a4651120063674d3449be9aa746f47a3cb7f
I'm confused as to why though, since this project is just importing relay wrapped components from a component library project which has already compiled them:
Source package: https://github.com/trevordmiller/cortex-components/blob/master/package.json#L8
Consuming: https://github.com/trevordmiller/cortex-clients/blob/master/native-mobile/App.js#L2

This also wasn't a problem when I was using hard-coded data and then Apollo client, before switching to Relay Modern - so I feel it must have something to do with the way Relay Modern's internals work, some sort of side effect relying on the babel plugins directly? No idea. Would appreciate if someone on the Relay team could take a look at this.

**Comment by trevordmiller** [comment]
Perhaps has something to do with the `__generated__` folders in the component library being published to npm? 
![image](https://cloud.githubusercontent.com/assets/5497885/25296923/d85cc12a-26a7-11e7-8d3f-dae0ef2cc599.png)
I'm confused 😕

**Comment by trevordmiller** [comment]
Closing since there hasn't been activity in a while. But if the team has bandwidth to look into it feel free to reopen.
