### ISSUE TITLE
[Modern] Relay Containers Documentation syntax error

### ISSUE THREAD

**Issue by rchall-gladly** [facebook/relay#1675]
I think there's a syntax error in the query fragment documentation.

From the official doc you can see this code describing how you define [Relay Containers](https://github.com/facebook/relay/blob/master/docs/modern/FragmentContainer.md#relay-containers):

```
module.exports = createFragmentContainer(TodoItem,  {
  {
    item: graphql`
      fragment TodoItem_item on Todo {
        text
        isComplete
      }
    `,
  },
});
```

Relay compiler fails with a similar code following the same structure. I think the problem is in the {{}}.

I might have some other configuration issue so here I'll share my packages versions and babel-relay-plugin setup:

"babel-plugin-relay": "1.0.0-rc.2",
"relay-compiler": "1.0.0-rc.2",
"react-relay": "1.0.0-rc.2",

.babelrc

["relay", {
      "compat": false, 
      "schema": "my/path/to/schema.graphql"}
]

This is how I'm importing from react-relay package:

import {
  createFragmentContainer,
  graphql,
} from 'react-relay';

**Comment by mjmahone** [comment]
Good catch! There shouldn't be a surrounding `{}` around the inner one: it should look like
```
module.exports = createFragmentContainer(TodoItem,  {
  item: graphql`
    fragment TodoItem_item on Todo {
      text
      isComplete
    }
  `,
});
```

You're right, this is a documentation error: feel free to make a PR to fix the docs once you've verified your fix!

**Comment by mjmahone** [comment]
This is a real-world example for how to do this correctly, from the [todo-modern example](https://github.com/relayjs/relay-examples/blob/master/todo-modern/js/components/TodoList.js#L63):
```
export default createFragmentContainer(TodoList, {
  viewer: graphql`
    fragment TodoList_viewer on User {
      todos(
        status: $status,
        first: 2147483647  # max GraphQLInt
      ) {
        edges {
          node {
            id,
            complete,
            ...Todo_todo,
          },
        },
      },
      id,
      totalCount,
      completedCount,
      ...Todo_viewer,
    }
  `,
});
```

**Comment by rchall-gladly** [comment]
Thanks for the quick response mjmahone. Gonna work on that PR right now.

**Comment by wincent** [comment]
Not sure why this issue didn't auto-close. Thanks for the PR, @rchall-gladly.
