### ISSUE TITLE
Plans for "generic Relay"

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#168]
In the blog post introducing Relay, @josephsavona said, "We're working to extend Relay to provide a unified interface for interacting not only with server data, but also in-memory and native device data (and, even better, a mix of all three)."

I was curious to hear more about what that means exactly :)

Does this mean you'd like Relay to replace Flux at Facebook? Will you be able to create client-side only GraphQL types that you can query/mutate client side?

Any plans to do stuff like time-traveling debugging, user state saving/restoring, etc.?

**Comment by josephsavona** [comment]
Thanks for asking! Note that issue #114 gives overview of this feature and is intended as a place to gather feedback from the community about additional use-cases. I'll address your specific questions here though:
 
> Does this mean you'd like Relay to replace Flux at Facebook? 

Short answer: no. Note that Relay is an implementation of the Flux pattern (can Flux replace itself?). Consider that mutations are effectively asynchronous action creators, payloads from the server are actions, and the cache is a single integrated store. Our goal is to solve product use-cases that require interacting with data from multiple (potentially async) sources. 

> Will you be able to create client-side only GraphQL types that you can query/mutate client side?

Yup, that's the basic idea - see more on #114. 

> Any plans to do stuff like time-traveling debugging, user state saving/restoring, etc.?

Our short-term goals are to provide development tools for Relay and to facilitate offline operation. We're not specifically planning to implement time-traveling debugging, for example, but we absolutely appreciate the value of these kinds of tools. Having an initial version of Relay dev tools could be a great place for the community to get involved on building these features.

**Comment by josephsavona** [comment]
@KyleAMathews We're always interested in feedback and if this plan addresses any use-cases you might have been thinking of. Also, I should clarify that while our goal isn't to "replace Flux", implementing this feature would allow us to replace generic variations of Flux in a lot of places.

**Comment by gyzerok** [comment]
@KyleAMathews you can use GraphQL client-side today.

**Comment by KyleAMathews** [comment]
:+1: Thanks @josephsavona! I'll close this issue in lieu of #114
