### ISSUE TITLE
[Modern] Some way to implement "Save" button

### ISSUE THREAD

**Issue by s-panferov** [facebook/relay#1693]
Hello. I cannot find something in Modern API to make a deferred batched save of a group of mutations (while keeping the ability to update them optimistically).

Could you please provide some examples?

UPD: The only way I see right now is to handle this on the network layer. Is this the right way?

**Comment by leebyron** [comment]
cc @josephsavona

**Comment by jardakotesovec** [comment]
Was this considered in modern architecture? We are using this logic to make input updates in realtime via optimistic updates and committing to the server at the end in relay classic.  Its blocking us to move towards modern. Wondering how much effort it would be to add such functionality...

**Comment by jardakotesovec** [comment]
Thanks to @yuzhi updates https://github.com/facebook/relay/commit/98ec1d5b3de46f94dc601a26caeab674b8a17a4e I managed to make this two step process work with modern. So I would like to share it and also feedback is welcomed if this approach makes sense.

```
import {
    commitMutation,
    graphql,
} from 'react-relay';
import environment from '../environment';

import { applyOptimisticMutation } from 'relay-runtime';

const mutation = graphql`
  mutation UpdatePricesMutation($input: updatePricesInput!) {
    updatePrices(input: $input) {
        price {
            id
            amount
            total
        }
    }
  }
`;

export default ({ pricesObject, amount, total }) => {
    const variables = {
        input: {
            pricesId: pricesObject.id,
            amount,
            total,
            clientMutationId: ''
        }
    };

    const config = {
        mutation,
        variables,
        optimisticResponse: {
            updatePrices: {
                prices: {
                    id: pricesObject.id,
                    amount,
                    total,
                 }
            }
        }
    };

    const disposable = applyOptimisticMutation(
        environment,
        config
    );

    return {
        dispose: () => disposable.dispose(),
        commit: () => {
            disposable.dispose();
            commitMutation(environment, config);
        }
    };
};
```

Which can be use than as:
```
const mutation = updatePrices(pricesObject, amount, total);
mutation.dispose();
or
mutation.commit();
```

**Comment by leebyron** [comment]
Great! glad to see resolution here

**Comment by jardakotesovec** [comment]
@leebyron I would like to make some clear outcome from this issue. This is feature I personally used several times in classic and I am glad to be able to achieve that in Modern. 

I think following questions need to be answered:
- Is this local update with rollback/commit feature relay core team is willing to support? 
- Am I using the right API to do that trick? Maybe exposing this functionality via some higher level api would be more suitable (something we had basically in classic)

Once we settle on these two questions, it can be adjusted and api exposed and also eventually documented and than closed :-). I would like to help to push it forward with some PRs. I was bit [involved](https://github.com/facebook/relay/pull/646) in this functionality for classic as well, but would need some feedback from relay core team to get direction.

**Comment by leebyron** [comment]
I'm not entirely certain. Perhaps @yuzhi could have a better idea of that since she helped add this API.

**Comment by yuzhi** [comment]
> Is this local update with rollback/commit feature relay core team is willing to support?
Yes I think so. This is essentially just standard optimistic mutation without sending the mutation to the server right away. We are also using it for a mutation internally.

> Am I using the right API to do that trick? Maybe exposing this functionality via some higher level api would be more suitable (something we had basically in classic)

I think we just need to expose `applyOptimisticMutation` in `react-relay`. I don't think we have plans for higher level API at the moment.
