### ISSUE TITLE
[Modern] Updated variables in RefetchContainer not passed to child fragments

### ISSUE THREAD

**Issue by robrichard** [facebook/relay#1695]
I have created a container using `createRefetchContainer` which updates variables used by child fragments. In Relay Modern the child components corresponding to those fragments are not re-rendered with the updated variables. I can see that query was executed with the updated variables, the store has been updated to hold these records but the components are still passed the old props. This works as expected with the compat environment.

Reproduction example here: https://github.com/relayjs/relay-examples/compare/master...robrichard:variables-example?expand=1

Running on http://localhost:3000/?useModern (uses modern environment)
Initial view
![image](https://cloud.githubusercontent.com/assets/3814096/25452042/29475454-2a92-11e7-9d1e-09d0b3972fc6.png)

click on "use b"
![image](https://cloud.githubusercontent.com/assets/3814096/25452051/3148c07a-2a92-11e7-9fde-30b60d74493f.png)

Running on http://localhost:3000/ (uses compat environment)
![image](https://cloud.githubusercontent.com/assets/3814096/25452083/5c3491c4-2a92-11e7-97fd-082257423453.png)

**Comment by robrichard** [comment]
I did some more digging and it looks like `RelayModernFragmentSpecResolver` will resolve props for `FragmentContainers` based on the variables in context. `QueryRenderer` will add the variables for it's query to React context but `ReactRelayRefetchContainer` will not. Any fragment containers rendered as children of a refetch container will never be rendered with the data from the refetch query. It seems like the simplest solution is to implement `getChildContext` in `ReactRelayRefetchContainer`.

**Comment by yuzhi** [comment]
Thanks @robrichard  for fixing this!
