### ISSUE TITLE
[Modern] runtime expects object, but babel-plugin-relay generates fn exp

### ISSUE THREAD

**Issue by gusbicalho** [facebook/relay#1696]
relay-runtime `RelayStaticSelector` expects the fragments to be a ConcreteFragment, but `babel-plugin-relay` generates function expressions.

Relevant lines:
https://github.com/facebook/relay/blob/master/packages/babel-plugin-relay/createModernNode.js#L23
https://github.com/facebook/relay/blob/master/packages/relay-runtime/store/RelayModernSelector.js#L59

**Comment by josephsavona** [comment]
Yup! This is the underlying cause of #1665 and fixed on master, should go out in RC3.

I'm going to close since the fix should be out soon, but thanks for reporting!

**Comment by josephsavona** [comment]
Fix was d7c57506f9276175d5684c920a915fbf3de71d83
