### ISSUE TITLE
Fragment templates

### ISSUE THREAD

**Issue by davide-ganito** [facebook/relay#170]
Is it possibile to create some kind of fragment template. For example:
```
$Type = 'TypeConnection1'

Relay.QL`
  fragment on $Type {
    edges { node }
  }
`
```
I was thinking about som generic components for connection pagination...
What do you think?

**Comment by josephsavona** [comment]
This type of polymorphic fragment definition isn't supported. A similar option is to use interfaces - for example, multiple types might have connection fields with the type `UsersConnection` and `node` fields of type `User`. This would allow you to create generic components that could paginate a list of users. 

@dschafer Can you think of any other options?

**Comment by gyzerok** [comment]
@davide-ganito 

```javascript
function createFragment(name) {
  return `
    fragment on ${name} {
      edges { node }
    }
  `;
}

createFragment('Human');
```

**Comment by josephsavona** [comment]
> you can do it yourself:

@gyzerok This type of dynamic templating won't work. The babel plugin has to know the type name at compile time.

**Comment by davide-ganito** [comment]
Renouncing to the compile time schema validation text would be possibile to implement this in the babel plugin? 
Watching the transpiled code i have noticed that the fragment is produced by a self calling lambda.
```
var connectionFragment = (function () {
  var GraphQL = _reactRelay2['default'].QL.__GraphQL;
  return new GraphQL.QueryFragment('GameList', 'GameConnection', [new GraphQL.Field('totalCount', null, null, null, null, null, {
    'parentType': 'GameConnection'
  }), new GraphQL.Field('pageInfo', [new GraphQL.Field('startCursor', null, null, null, null, null, {
    'parentType': 'PageInfo'
  }), new GraphQL.Field('endCursor', null, null, null, null, null, {
    'parentType': 'PageInfo'
  }), new GraphQL.Field('hasNextPage', null, null, null, null, null, {
    'parentType': 'PageInfo',
    'requisite': true
  }), new GraphQL.Field('hasPreviousPage', null, null, null, null, null, {
    'parentType': 'PageInfo',
    'requisite': true
  })], null, null, null, null, {
    'parentType': 'GameConnection'
  })]);
})();
```
Would it be possible to transpile in something like the the following in presence of a @gyzerok like syntax?
```
var connectionFragment = (function (connectionType) {
  var GraphQL = _reactRelay2['default'].QL.__GraphQL;
  return new GraphQL.QueryFragment('GameList',connectionType, [new GraphQL.Field('totalCount', null, null, null, null, null, {
    'parentType': connectionType
  }), new GraphQL.Field('pageInfo', [new GraphQL.Field('startCursor', null, null, null, null, null, {
    'parentType': 'PageInfo'
  }), new GraphQL.Field('endCursor', null, null, null, null, null, {
    'parentType': 'PageInfo'
  }), new GraphQL.Field('hasNextPage', null, null, null, null, null, {
    'parentType': 'PageInfo',
    'requisite': true
  }), new GraphQL.Field('hasPreviousPage', null, null, null, null, null, {
    'parentType': 'PageInfo',
    'requisite': true
  })], null, null, null, null, {
    'parentType': connectionType
  })]);
})();
```

**Comment by josephsavona** [comment]
@davide-ganito The exact type has to be known at compile time in order to properly compile all the subfields. I'll reiterate: templated queries are not supported.

Can you provide an example of how you'd like to use this? There are likely simpler, supported solutions or reasonable alternatives.

**Comment by devknoll** [comment]
If you _really_ need to do this, here are two crazy ideas off the top of my head:
* Easy but unstable: Bypass the babel plugin entirely and just have a `createFragment` function that returns the transpiled code (the format of this might change, but I _think_ the intention is to eventually stabilize it with pure JSON objects, right Joe?)

* Harder but reliable: Make a babel plugin that parses your templates and generates Relay.QL statements that the Relay babel plugin can transform later.

**Comment by davide-ganito** [comment]
Ok @josephsavona, thx!
I have not try it yet, do you think that something like this could work?
```
import React from 'react';
import Relay from 'react-relay';


export default function RelayConnectionContainer( ListContainer, opts ) {

  const {
    displayName,
    collectionName
  } = Object.assign({
    displayName : ListContainer.displayName || ListComponent.name,
  },opts);


  const CollectionContainer = React.createClass({

    displayName : `${displayName}Page`,

    getDefaultProps() {
      return {
        pageSize : 10
      }
    },

    hasPreviousPage() {
      const { pageInfo } = this.props[connectionName];
      return pageInfo.hasPreviousPage;
    },


    hasNextPage() {
      const { pageInfo } = this.props[connectionName];
      return pageInfo.hasNextPage;
    },

    renderPagination() {
      return (
        <div>
          <ul className="pagination">
            <li className={!this.hasPreviousPage()?'disabled':''}>
              <a href="#" onClick={this._handlePreviousClick}>
                <i className="material-icons">chevron_left</i>
              </a>
            </li>

            <li className={!this.hasNextPage()?'disabled':''}>
              <a href="#" onClick={this._handleNextClick}>
                <i className="material-icons">chevron_right</i>
              </a>
            </li>

          </ul>
        </div>
      )
    },

    render() {

      const connection = this.props[connectionName];
      const listProps = {
        [connectionName] : connection.edges.map( edge => edge.node )
      };

      return (
        <div class="row page">
          <ListComponent { ...listProps } />
          { this.renderPagination() }
        </div>
      )
    },

    _handleNextClick() {
      const { pageInfo } = this.props[connectionName];

      if ( this.hasNextPage() ) {
        this.props.relay.setVariables({
          after : pageInfo.endCursor,
          first : this.props.pageSize,
          before : null,
          last : null
        })
      }
    },

    _handlePreviousClick() {

      const { pageInfo } = this.props[connectionName];

      if ( this.hasPreviousPage() ) {
        this.props.relay.setVariables({
          before : pageInfo.startCursor,
          last : this.props.pageSize,
          first : null,
          after : null
        })
      }

    }

  });
  

  return Relay.createContainer( CollectionContainer, {

    initialVariables : {
      after : null,
      first : 10,
      last : null,
      before : null
    },

    fragments : {

      [collectionName] : () => Relay.QL`
        fragment on ConnectionInterface {
          edges {
            node {
              ${Component.getFragment(collectionName)}
            }
          }
          pageInfo {
            startCursor,
            endCursor,
            hasNextPage,
            hasPreviousPage
          },
          totalCount
        }
      ` 
   
    }


};
```

**Comment by davide-ganito** [comment]
And i will use it like this:
```
import React from 'react';
import Relay from 'react-relay';
import RelayConnectionContainer from '../lib/RelayConnectionContainer';

const GameList = React.createClass({

  render() {

    const { games } = this.props;
    return (
      <ul>
        { games.map( (game) => {
          return <li key={game.id}>{game.name}</li>
        }) }
      </ul>
    )

  }

});


const GameListContainer = Relay.createContainer( GameList, {

  fragments : {
    games : () => Relay.QL`
      fragment on Game @relay(plural: true) {
        id,
        name
      }
    ` 
  }

});


export default RelayConnectionContainer( GameListContainer, {
  connectionName : 'games'
});
```

**Comment by josephsavona** [comment]
Yeah, I don't see any read flags. Try it!

**Comment by wincent** [comment]
I'm going to close this out for now, as it looks like you've found a solution. Feel free to re-open or create a new issue if you have any more questions or suggestions.

Thanks for opening the ticket, @davide-ganito.

**Comment by nodkz** [comment]
@davide-ganito did your solution works?

I also want wrap `Connection` to component, which provide infinite scroll with spinner. 
Or may be such component exists already?

**Comment by davide-ganito** [comment]
Yes, with a little adjustment. But in my experience it wasn't so useful.
I'm taking a look to the source, if it seems to work I can post the last version.

**Comment by stevewillard** [comment]
Very curious about your solution, too @davide-ganito I have been trying to hack apart the babel relay plugin to prevent schema validation, but I think it's doing too much with the type information. Mainly, I want to do with @gyzerok put together:
```
function createFragment(name) {
  return Relay.QL`
    fragment on ${name} {
      edges { node }
    }
  `;
}
```

**Comment by josephsavona** [comment]
We absolutely agree that there should be a way to define a generic "connection" interface such that you can create a reusable connection container along the lines of @davide-ganito's [comment](https://github.com/facebook/relay/issues/170#issuecomment-135951324). 

The main challenge in implementing this is that Relay needs to know the fragment type name in order to properly transform the query. Because `Relay.QL` tags are compiled away, runtime `createFragment`-style functions (per @stevewillard's example above) won't work. For example, depending on the fragment type it's either a connection or not - Relay needs to know this at runtime, but the information is only available in the schema at build time (schemas can easily be too large to load at runtime).

I mention this only to encourage that we look for solutions within the GraphQL type system, as opposed to runtime hackery. @leebyron - any ideas?
