### ISSUE TITLE
[Relay Modern] Querying __type

### ISSUE THREAD

**Issue by chollier** [facebook/relay#1715]
With Relay Classic, I used to query some fields from the schema directly, for instance I had:
```js const DiscussionTopicQueries = {
  platformType: () => Relay.QL`query { __type(name: "Platform") } `,
};
```

and in my Relay Classic Container I would have:
```js
export default const Relay.createContainer(Component, {
  fragments: {
    platformType: () => Relay.QL`
      fragment on __Type {
        ${ResponseNew.getFragment("platformType")}
      }
    `
    }
});
```

Platform type being an enum : 
```graphql
enum Platform {
  # iOS
  IOS

  # Android
  ANDROID

  # All of them
  ALL
}
```

Now with Relay Modern / Relay Compiler, when trying to query on Type, I get:

```
Error: You supplied a GraphQL document with validation errors:
Fragment "DiscussionDetail_platformType" cannot be spread here as objects of type "Query" can never be of type "__Type".
```

Is is still possible to query things from the Schema in Relay Modern?

**Comment by chollier** [comment]
figured I could just query `__type(name: "Whatever")` on any query

**Comment by ctsexton** [comment]
Sorry to reopen this years later, but I am getting this error when attempting to query `__type`:
`Unknown field '__type' on type 'Query'.`
This is the query I'm trying to compile:
```
query {
  __type(name: "ISO3166") {
    enumValues {
      name
      description
    }
  }
}
```
Basically I'm trying to get a list of available enum values for the enum "ISO3166" from the schema. Am I doing something wrong here? This is a valid GraphQL query that returns results from my API.

**Comment by sibelius** [comment]
You can’t do this anymore, as relay now only rely on types declared on schema.graphql

Expose this in a different way

**Comment by AlaDouagi** [comment]
@sibelius What's the replacement of GraphQL `__type` retrospection?
I can't find anything that helps with the migration of this deprecated feature.

**Comment by sibelius** [comment]
you need to explicit create `__type` again in your Query Type

**Comment by AlaDouagi** [comment]
Thanks, but I have to mention that the issue was resolved following the definitions found in GraphQL's docs [Introspection](https://github.com/graphql/graphql-spec/blob/02fd71f816139b7e040f969860778d23df288d32/spec/Section%204%20--%20Introspection.md) section.

**Comment by sibelius** [comment]
can you share your solution?

**Comment by AlaDouagi** [comment]
I copied from the [Schema Introspection](https://github.com/graphql/graphql-spec/blob/02fd71f816139b7e040f969860778d23df288d32/spec/Section%204%20--%20Introspection.md#schema-introspection) these couple of lines of code in the query definition:
```graphql
__schema: __Schema!
__type(name: String!): __Type
```
also I copied the whole **Schema of the GraphQL schema introspection system** from the same section (in the link above).

**Comment by sibelius** [comment]
this will make sure to avoid disabling graphiql introspection capabilities

**Comment by holmesal** [comment]
I didn't want to modify `schema.graphql`, as we regularly refetch/overwrite it.

This approach worked fine for us:
1. Add an `introspection.graphql` file alongside the main `schema.graphql` file.
2. Use `extend type Query { ... }` to add the introspection fields @AlaDouagi mentioned above (thanks!).
3. Add the other required types.

https://gist.github.com/holmesal/681ecf5ccccf8a14ab29fa5a0f4a8ff9

This seems to be picked up by the relay compiler just fine.

**Comment by mununki** [comment]
Actually, we don't need to manipulate the schema after introspection, because it is part of [GraphQL spec](https://graphql.org/learn/introspection/#:~:text=__Schema%2C%20__Type%2C%20__TypeKind%2C%20__Field%2C%20__InputValue%2C%20__EnumValue%2C%20__Directive%20%2D%20These%20all%20are%20preceded%20with%20a%20double%20underscore%2C%20indicating%20that%20they%20are%20part%20of%20the%20introspection%20system.).
I'm using [graphql-codegen](https://www.graphql-cli.com/codegen/) to introspect and stitch the schema, there is a [plugin to generate the schema](https://the-guild.dev/graphql/codegen/plugins/other/schema-ast). It supports the feature to introspect the introspection types that generates it for us.
