### ISSUE TITLE
Resources for React Native Integration

### ISSUE THREAD

**Issue by nickmacia** [facebook/relay#1717]
I'm just curious if there exist any good resources that show how to use relay modern with react native. I've found a few snippets here and there with react, but they aren't entirely congruent with react native set ups. Apollo has great docs, but seems to have a very different api.

**Comment by sibelius** [comment]
You can take a look on my boilerplate: https://github.com/sibelius/ReactNavigationRelayModern

**Comment by kassens** [comment]
I've also opened relayjs/relay-examples/issues/53 to create an example for React Native, contributions there are highly welcome!
