### ISSUE TITLE
[Modern] request caching

### ISSUE THREAD

**Issue by bsr203** [facebook/relay#1719]
I am migrating my app to modern and going great so far. One thing I noticed is that, in the older runtime graphql request is not  sent to the server for the same request after the first time. For example, if I navigate between two views (or with browser history back/forward), the network tab indicates no request being sent to the server (except the first time). but, with `modern`, the requests are repeated and feels like no caching. I setup the environment and network layer as in the [docs](https://facebook.github.io/relay/docs/relay-environment.html). Is there anything I need to do to prevent subsequent queries for cached response?

the router I use, re render the components from root on route change (this has been the case with relay classic as well). I think it is efficient in react to [do so](https://navigation4asp.net/).  Not sure how does `QueryRenderer` handles that.

**Comment by JenniferWang** [comment]
You may probably use `RelayQueryResponseCache` in the network request function to have a simple in-memory cache.

**Comment by bsr203** [comment]
@JenniferWang thank you. I will explore RelayQueryResponseCache. I saw it also mentioned on offline cache [here](https://github.com/facebook/relay/issues/1687#issuecomment-296842575). I will follow that discussion as well. thanks again for your help.

**Comment by IkerArb** [comment]
How do I implement the ReqlayQueryResponseCache, should I pass it to Network.create besides my fetchQuery?

**Comment by JenniferWang** [comment]
@IkerArb I think you need to add it in `fetchQuery` function (refactor the function a bit to read from cache first and also write to the cache when receiving the network request)

**Comment by IkerArb** [comment]
@JenniferWang perfect, thanks also I have been looking at the retain() method because I am building on a React Native app with two independent QueryRenderers the issue is that when I pop a view my previous cache is emptied, how can I unmount a QueryRenderer without it's cache being emptied?

**Comment by JenniferWang** [comment]
@IkerArb which cache are you referring to ? I don't think we clean up the request response cache in this case.

**Comment by IkerArb** [comment]
The RelayRecordSourceSelectorProxy, when doing the mutation I use this to delete an edge from my connection object, the thing is that in the other QueryRenderer I enter to the edit of an edge inside this connection and on coming back and doing the delete edge mutation I find that my proxies are empty.
