### ISSUE TITLE
[Modern] renderVariables doesn't work as expected

### ISSUE THREAD

**Issue by chollier** [facebook/relay#1721]
According to the doc https://facebook.github.io/relay/docs/refetch-container.html, with a RefetchContainer when specifying `renderVariables` in the `refetch` calls we should be able to replicate the "load more" behavior:
> renderVariables is an optional param that tells Relay which variables to use at when the component is re-rendered after fetching. Without this, the refetchVariables will be used. You might use this for more advanced usage, for example, to implement pagination, where you would fetch an additional page with variables like `{first: 5, after: '...'}`, but you would then render the full collection with `{first: 10}`.

I have been trying to use it to implement my own pagination. However it doesn't seem to work as expected as as soon as I specify `after` then the result of my query wipes out the previous result. 

I found this in the code, https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayRefetchContainer.js#L215 is it fair to assume it's not been implemented yet or am I misusing it?

**Comment by JenniferWang** [comment]
The task seems not relevant.
Would you please more specific about  'as soon as I specify `after` ...', where did you specify it?

**Comment by chollier** [comment]
The structure is overall like this: 

```js
<QueryRenderer>
  <RefetchContainer>
      <Table>
         <Row />
         <Row />
         <Row />
         <LoadMore />
      </Table>
  </RefetchContainer>
</QueryRenderer>
```

When `<LoadMore />` becomes visible on screen, I call `this.props.relay.refetch` like this:

```
this.props.relay.refetch((fragmentVariables) => ({
  ...fragmentVariables,
  count: 10,
  after: this.props.pageInfo.endCursor
}), {
  count: this.props.collectionSize
})
```

however doing so results on the data only containing the items included in the refetch query and _loosing_ the original query data.

If I'm not clear I can try to come up with an example repo

**Comment by josephsavona** [comment]
It might help if you can share the fragment and refetch query. In general, pagination requires a handle provider in order to merge distinct segments of edges into a single list. Out of the box we provide the `@connection` handler to do this if you're following the Relay Connection spec. 

PaginationContainer is designed for this use-case - is there a blocker to using here?

**Comment by chollier** [comment]
This is the query:
```graphql
      query ApproversPageQuery(
        $count: Int!,
        $after: String,
        $orderDirection: OrderDirection,
        $orderProperty: UserOrderProperty,
        $handle: String,
        $email: String,
        $role: UserRole,
        $name: String
      ) {
        users(
          first: $count,
          after: $after,
          handle: $handle,
          email: $email,
          role: $role,
          name: $name,
          orderDirection: $orderDirection,
          orderProperty: $orderProperty,
        ) {
          edges {
            node {
              id
              ...ApproverRelayRow_item
            }
          }
          pageInfo {
            hasNextPage
            endCursor
          }
        }
      }
```

and the fragment:

```graphql
      fragment ApproversPage_approversRelayPage on UserConnection {
        edges {
          node {
            id
            ...ApproverRelayRow_item
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
```

@josephsavona your explanation makes sense, there's no way I guess for Relay to know that I want to merge data.
When role or name change, I want to "refetch" the connection, this is why I used the Refetch container over the Pagination — I might have misled myself doing that, I'll try with the pagination one

**Comment by chollier** [comment]
That said I'm not sure I understand what would be the `renderVariables` use cases

**Comment by josephsavona** [comment]
It sounds like you're doing both refetching and pagination. For this use-case I would explore a RefetchContainer to handle refetching the connection in full when things like role/name/handle change, and have that that wrap a PaginationContainer that handles loading more for the current role/name/handle/etc. 

For the outer RefetchContainer, I think we need to make it easier to define them but it should be sufficient in that case to leave the second param to `refetch` blank (since the variables you fetch will also be the variables that you render with).

**Comment by chollier** [comment]
As a side-note, it took me a while to debug something with the PaginationContainer: my connection is a root field I couldn't get it to work so I had to wrap it under `viewer`. Because there was no _direct_ selection on the query but a fragment, nothing would get passed down to the components 

I got pretty far but as soon as I wrap the PaginationContainer within the the RefetchContainer, I'm getting some:

warning.js:36 Warning: RelayModernSelector: Expected object to contain data for fragment `ApproversPage_users`, got `{"users":{"edges":[{"cursor":"WzQ4XQ==","node":{"id":"VXNlci00OA==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci00OA=="}},{"cursor":"WzUzXQ==","node":{"id":"VXNlci01Mw==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci01Mw=="}},{"cursor":"WzU0XQ==","node":{"id":"VXNlci01NA==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci01NA=="}},{"cursor":"WzU1XQ==","node":{"id":"VXNlci01NQ==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci01NQ=="}},{"cursor":"WzU2XQ==","node":{"id":"VXNlci01Ng==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci01Ng=="}},{"cursor":"WzU3XQ==","node":{"id":"VXNlci01Nw==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci01Nw=="}},{"cursor":"WzU4XQ==","node":{"id":"VXNlci01OA==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci01OA=="}},{"cursor":"WzU5XQ==","node":{"id":"VXNlci01OQ==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci01OQ=="}},{"cursor":"WzYwXQ==","node":{"id":"VXNlci02MA==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci02MA=="}},{"cursor":"WzYxXQ==","node":{"id":"VXNlci02MQ==","__fragments":{"ApproverRelayRow_item":{}},"__id":"VXNlci02MQ=="}}],"pageInfo":{"hasNextPage":true,"endCursor":"WzYxXQ=="}}}`. Make sure that the parent operation/fragment included fragment `...ApproversPage_users`.

And the PaginationContainer get the original query result but then doesn't fetch new data.

This is probably because fragment data doesn't get passed down, hence I tried to pass it down but it is "sanitized" (aka doesn't have `__id` and `__fragments`)

**Comment by chollier** [comment]
@josephsavona I was actually able to get it to work without the RefetchContainer: as my QueryRenderer variables (role, name, handler, order etc) come from react-router's location, I can just change the url with browserHistory.push(...) and QueryRender refetches the query
