### ISSUE TITLE
[Website] Playground examples duplicate after navigation back in Chrome 

### ISSUE THREAD

**Issue by iurii-kyrylenko** [facebook/relay#1729]
**Preconditions**:
- Google Chrome: Version 58.0.3029.96 (64-bit)
- Mac OSX

**Step to reproduce**:
1. Open [home page](https://facebook.github.io/relay/)
2. Press `Try it Out` button.
3. Navigate back in browser history by clicking browser's `back` button or executing script in browser's console: ` window.history.back()`

**Actual result**:
For all three examples ("A simple list", "A simple parameterization"), "A simple mutation") have duplicated code from previous playground page ("Hello World")

**Expected Result**:
Keep the original code

**Comment by kassens** [comment]
The playground was relay classic which we're in the progress of duplicating. Please re-open if this is still an issue in Relay Modern.
