### ISSUE TITLE
[Modern] Nesting in fragment containers

### ISSUE THREAD

**Issue by dispalt** [facebook/relay#1731]
Hi so I am trying to build some bindings for Relay in Scalajs.  I've gotten the compiler to mostly do what I want but now I am running into a convention issue.

I know this is probably a long shot, but is there any way I could get relay to go one more prop deep.  so, for instance, my props all live under some variable in props, let's say `a`.  So if I pass props from relay for a viewer fragment.  Something like `Todo_viewer`, right now everything lands in `props.viewer`.  But Ideally I could do Todo_a_viewer` and it would land in `props.a.viewer`.  The interop story is a bit finicky, but the boxing (aka `a`) makes it possible to interop with scala much better and that's basically been the way it's been for a while.

I guess the more generic question is can we nest more than one level deep?

**Comment by eugene1g** [comment]
Maybe not directly with Relay, but you could solve this with React by adding a HOC to proxy data props to the right place. For example, on the query level, it could be something like this -
```js
//...
  return (
    <QueryRenderer
      query={query}
      variables={variables}
      environment={getRelayEnvironment()}
      render={({ error, props }) => {
// ...
        if (props) {
          return <MyFancyComponent a={{viewer: relayProps.viewer}}
        }
// ...
return null;
      }}
    />
  );
```
You could wrap the whole thing in a standard function to generate the boilerplate.

**Comment by dispalt** [comment]
That's exactly the conclusion I came to, thanks for helping me confirm it!
