### ISSUE TITLE
I cannot add a todo if it is same text of previous text and get flattenChildren error?

### ISSUE THREAD

**Issue by iamglenbacs** [facebook/relay#1744]
I am new in relay and I can't figure out this error when I add a new text that is same text of previous todo in TodoList. this code is from the relay todo modern sample:

Warning: flattenChildren(...): Encountered two children with the same key, VG9kbzo0. Child keys must be unique; when two children share a key, only the first child will be used
I believe the problem is here since when I reload, the data display is in sync in the database but ofcourse I don't want my frontend not to sync because I have achieved it using getOptimisticResponse on my other mutation that works but this code in relay modern mutation is different

      updater: (store) => {
        const payload = store.getRootField('addTodo');
        const newEdge = payload.getLinkedRecord('todoEdge');
        sharedUpdater(store, user, newEdge);
      },
      optimisticUpdater: (store) => {
        const id = 'client:newTodo:' + tempID++;
        const node = store.create(id, 'Todo');
        node.setValue(text, 'text');
        node.setValue(id, 'id');
        const newEdge = store.create(
          'client:newEdge:' + tempID++,
          'TodoEdge',
        );
        newEdge.setLinkedRecord(node, 'node');
        sharedUpdater(store, user, newEdge);
        const userProxy = store.get(user.id);
        userProxy.setValue(
          userProxy.getValue('totalCount') + 1,
          'totalCount',
        );
      },
what I wanted to do is maybe use an if statement to check if text is already in the database along with window.comfirm or abort adding the todo. help? Also, where do i read about RelayRecordProxy? and these functions docs?

- functions copyFieldsFrom
- function copyFieldsFrom(source)
- function getDataID()
- function getLinkedRecord(name, args)
- function getLinkedRecords(name, args)
- function getOrCreateLinkedRecord(name, typeName, args)
- function getType()
- function getValue(name, args)
- function setLinkedRecord(record, name, args)
- function setLinkedRecords(records, name, args)
- function setValue(value, name, args)
- function RelayRecordProxy(source, mutator, dataID)

**Comment by sibelius** [comment]
I think the problem is here:

`const id = 'client:newTodo:' + tempID++;`

**Comment by iamglenbacs** [comment]
@sibelius I think not because I can add a new todo if it's not the same text of the previous todo added

**Comment by kassens** [comment]
This sounds like a server issue with the playground. Please re-open an issue there if this is still an issue!
