### ISSUE TITLE
[Modern] commitRelayModernMutation -> unstable_internal

### ISSUE THREAD

**Issue by stoffern** [facebook/relay#1745]
Error: `Cannot read property 'unstable_internal' of undefined`

Appears to be when there are multiple commits sendt at the same time.
Trying to figure out more exactly why the error occours.
It happends when items in a ReactNative FlatList are in viewport and Relay will sendt a mutation on seen element.

Would it not be good to check the enviroment variable is present and not undefined before continuing?
https://github.com/facebook/relay/blob/368409ef83b5308e658b40509b0f78f9ddafc02c/packages/relay-runtime/mutations/commitRelayModernMutation.js#L52

**Comment by JenniferWang** [comment]
Since we have Flow type check, there shouldn't be any code checking nullability.

**Comment by stoffern** [comment]
Do i need til add flow into my code to fix it then?

**Comment by leebyron** [comment]
Very interesting! No you are not required to use Flow.

I would have expected https://github.com/facebook/relay/blob/368409ef83b5308e658b40509b0f78f9ddafc02c/packages/relay-runtime/mutations/commitRelayModernMutation.js#L48 to be triggered and a more descriptive error to be thrown if `environment` was undefined.

**Comment by leebyron** [comment]
Ah - it seems that this invariant was added the day after the last RC was released, so the npm version does not check this invariant first. I'm working on releasing RC4 which includes this invariant and will ensure a much more actionable error message.

Typically this means you are using Relay Classic and Relay Modern together in incompatible ways. Make sure you're using `react-relay/compat` when using the new mutation APIs with an existing Relay Classic app

**Comment by stoffern** [comment]
Thanks for clarifying @leebyron. I will wait for next RC.
I have already converted 100% of the code over to react-relay so it uses the full RC3 and not a `classic` or `compat` on the queries or the mutations
