### ISSUE TITLE
babel-plugin-relay: Missing schema option 

### ISSUE THREAD

**Issue by grandmore** [facebook/relay#1747]
I'm getting an error after updating to Modern, but I cannot find any reference to it. Do you know what this is?

```
ERROR in ./client/routes/ViewerQuery.js
Module build failed: Error: /routes/ViewerQuery.js: babel-plugin-relay: Missing schema option
```

This was an old method of passing query to the object. for example from todo..
```
ReactDOM.render(
  <Router
    environment={Relay.Store}
    history={history}
    render={applyRouterMiddleware(useRelay)}>
    <Route path="/"
      component={TodoApp}
      queries={ViewerQueries}>
      <IndexRoute
        component={TodoList}
        queries={ViewerQueries}
        prepareParams={() => ({status: 'any'})}
      />
      <Route path=":status"
        component={TodoList}
        queries={ViewerQueries}
      />
    </Route>
  </Router>,
  mountNode
);
```

**Comment by raffihsieh** [comment]
Are you using Relay Classic ? 
It looks like you may be missing the schema parameter in your babelrc file

https://facebook.github.io/relay/docs/babel-plugin-relay.html#using-with-relay-classic

**Comment by leebyron** [comment]
Thanks for answering, @raffihsieh! Indeed, you need to pass the schema to the options for babel-plugin-relay when using Relay Compat mode or when transforming Relay.QL tags.

**Comment by workteam123** [comment]
Using Relay Modern with react-create-app and setup.js to inject babel-relay this still occurs.  Do I have to eject?
