### ISSUE TITLE
[Modern] QueryRenderer oddity

### ISSUE THREAD

**Issue by dispalt** [facebook/relay#1749]
I'd love to see an example that uses `QueryRenderer` multiple times because I am running into something that looks like a problem, but I am having issues narrowing it down.  The gist is this:

* I have a parent router with two routes `/app/settings` and `/app/home`
* Each route renders its own separate tree
* If I land on `/app/settings` with a full reload then commit a mutation, and use the `updater` to handle the payload, I use it similar to the `todo-modern` example, everything works great.  I have to insert after a connection and all is well.  I use the `@key` param to specify the connection name and everything.
* If I land on `/app/home` then navigate to `/app/settings` then do the same mutation, I can't find my connections hanging off my viewer.  Even though everything looks the exact same.
* Here's the weird part, if I use `ViewerHandler.VIEWER_ID` it all works in both scenarios.  I am using `query { viewer { ... } }` and I have not configured a `handlerProvider`

any tips or explanation? I am happy to browse through the code.  Is it something with the fact that it's instantiating the DefaultHandler provider which handles viewer's specially?

Thanks for the help

**Comment by yuzhi** [comment]
Sorry for taking a while to get back to you. You should be able to use QueryRenderer anywhere you can use a React component regardless of how you do routing.  Relay also has a GC that might have cleaned up some of this data. 
We are trying to clean up some of our older issues. Please reopen a new issue if you would like more eyes on this.
