### ISSUE TITLE
[Modern] SetLinkedRecords doesn't update the UI while last edges is deleted

### ISSUE THREAD

**Issue by luthfielaroeha** [facebook/relay#1750]
I try to create my own custom deleteNode function.

```
function deleteByID(store, rootFieldName, deletedID) {
	const record = store.getRoot()
	const edges = record.getLinkedRecords(rootFieldName);
	if (!edges) {
		return;
	}
	let nextEdges;
	for (let ii = 0; ii < edges.length; ii++) {
		const edge = edges[ii];
		const node = edge;
		if (node != null && node.getDataID() === deletedID) {
			if (nextEdges === undefined) {
				nextEdges = edges.slice(0, ii);
			}
		} else if (nextEdges !== undefined) {
			nextEdges.push(edge);
		}
	}
	if (nextEdges !== undefined) {
		record.setLinkedRecords(nextEdges, rootFieldName);
	}
}
```

It works fine, except while the last edges is deleted, the UI doesn't updated.

**Comment by josephsavona** [comment]
Should this be `const node = edge.getLinkedRecord('node');`?

**Comment by luthfielaroeha** [comment]
yeah, but I tried to create GraphQL server without node and edges. Here is my root schema
```
schema {
	query: Query
	mutation: Mutation
}

type Query {
	actions: [Action]
	action(id: ID!): Action
	rules: [Rule]
}
```
Is that okay or should I create node and edges in my GraphQL server ?

**Comment by cipater** [comment]
I'm seeing the same thing. I have a similar function to delete an item by ID, but not from Connection edges. 

As the title says, calling `record.setLinkedRecords(nextItems, recordsFieldName)` doesn't update the UI when `nextItems` is missing the last record from "`previousItems`".

**Comment by josephsavona** [comment]
Thanks for the update. Care to send a PR to fix? The problem is likely in recycleNodesInto() or in RelayModernRecord's update() function (that takes a previous and next record and returns a new record only if there are changes - it might not be comparing array fields correctly)

**Comment by cipater** [comment]
So the issue actually turns out to be in https://github.com/facebook/relay/blob/master/packages/relay-runtime/store/RelayModernFragmentSpecResolver.js#L276. 

```javascript
const prevData = this._data;
let nextData;
for (let ii = 0; ii < this._resolvers.length; ii++) {
  const prevItem = prevData[ii];
  const nextItem = this._resolvers[ii].resolve();
  if (nextData || nextItem !== prevItem) {
    nextData = nextData || prevData.slice(0, ii);
    nextData.push(nextItem);
  }
}
this._data = nextData || prevData;
this._stale = false;
```

If `this._resolvers.length == 0`, or is less than `prevData.length` and `prevItem == nextItem ` for each index of `this._resolvers`, then `nextData` will remain undefined and `prevData` is always returned.

The below change resolves the issue for me...

```javascript
const prevData = this._data;
let nextData;
for (let ii = 0; ii < this._resolvers.length; ii++) {
  const prevItem = prevData[ii];
  const nextItem = this._resolvers[ii].resolve();
  if (nextData || nextItem !== prevItem) {
    nextData = nextData || prevData.slice(0, ii);
    nextData.push(nextItem);
  }
}
if (!nextData && this._resolvers.length != prevData.length) {
  nextData = prevData.slice(0, this._resolvers.length);
}
this._data = nextData || prevData;
this._stale = false;
```

**Comment by josephsavona** [comment]
@cipater Thanks for investigating! If you have the time it would be great if you could send that as a PR (would need a unit test) :-)

**Comment by casparrolfe** [comment]
@cipater @josephsavona was any progress made on this issue? Looks like its a duplication of #1904
