### ISSUE TITLE
[Modern] babel-plugin-relay not available on npm

### ISSUE THREAD

**Issue by jacobcabantomski-ct** [facebook/relay#1752]
Although `babel-plugin-relay@1.0.0-rc3` is available on yarn, attempting to grab it from https://www.npmjs.com/package/babel-plugin-relay results in an empty project. See Related as to potentially why.

Are there plans to get `babel-plugin-relay` on npm? All other Relay Modern dependencies are available there.

Related:
- https://github.com/facebook/relay/issues/206
- https://github.com/facebook/relay/issues/256

**Comment by kassens** [comment]
Since there was a version 1.0.0 published, we couldn't go back, so unfortunately, it's `npm install 1.0.1-rc.3` for now. We'll get this back in sync once the version is higher than that.

**Comment by jacobcabantomski-ct** [comment]
👍  Didn't see that as an available version, resolved my issue. Thanks @kassens
