### ISSUE TITLE
[modern rc3] RelayModernFragmentSpecResolver refetch sees no difference

### ISSUE THREAD

**Issue by decebal** [facebook/relay#1759]
Although the network request is successful the props are not mapped right, hence the component never gets updated!

Flow: `createRefetchContainer()` -> call `relay->refetch()`

**Comment by chollier** [comment]
Most likely a duplicate of https://github.com/facebook/relay/pull/1702

**Comment by yuzhi** [comment]
@chollier Sounds like it was a dup of  #1702 has been resolved. Please open a new issue if it's still broken for you.
