### ISSUE TITLE
relay-compiler not generating any files on Windows.

### ISSUE THREAD

**Issue by akatebi** [facebook/relay#1763]
Take the relay-examples repository and go to the todo-modern folder and run the compiler.
It works on Linux but not on Windows 7. It thinks that files are already generated.

**Comment by wincent** [comment]
Thanks for reporting this @akatebi. I am suspicious of the Watchman support on Windows, so I think one nice way to handle this would be to implement a fallback mode in the compiler that doesn't rely on Watchman.

**Comment by akatebi** [comment]
Hi Greg,

    I had a work around by touching the source files using the touch
command. However the issue with the Watchman has mysteriously disappeared
now. BTW Relay Modern is fantastic !!!

Thanks,
Alex Katebi

**Comment by wincent** [comment]
Thanks @akatebi. If this comes up again we can re-open.
