### ISSUE TITLE
react-relay: PropTypes deprecation warning

### ISSUE THREAD

**Issue by lumio** [facebook/relay#1769]
We are currently getting a deprecation warning about accessing PropTypes directly from React. And it seems that it is caused by react-relay/lib/**RelayPropTypes.js** (4. at stacktrace below).

We are using **`react-relay v0.10.0`**

```js
'use strict';

var _require = require('react'),
    PropTypes = _require.PropTypes; // Faulty code, line 16
```

**Warning itself:**

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

**Stacktrace:**

```
1. printWarning		@	warning.js:36
2. warning		@	warning.js:60
3. get			@	React.js:95
4. (anonymous)		@	RelayPropTypes.js:16
5. __webpack_require__	@	bootstrap 0ba5a86…:657
6. fn			@	bootstrap 0ba5a86…:85
7. (anonymous)		@	RelayPublic.js:27
8. (anonymous)		@	app.js:126999
9. __webpack_require__	@	bootstrap 0ba5a86…:657
10. fn			@	bootstrap 0ba5a86…:85
11. (anonymous)		@	Relay.js:29
12. __webpack_require__	@	bootstrap 0ba5a86…:657
13. fn			@	bootstrap 0ba5a86…:85
14. (anonymous)		@	emitter.js:2
15. __webpack_require__	@	bootstrap 0ba5a86…:657
16. fn			@	bootstrap 0ba5a86…:85
17. (anonymous)		@	wrappy.js:33
18. __webpack_require__	@	bootstrap 0ba5a86…:657
19. validateFormat	@	bootstrap 0ba5a86…:706
20. (anonymous)		@	bootstrap 0ba5a86…:706
```

**Comment by bdegreve** [comment]
Any chance a patched version will be released on npm? We're facing the same error. Thanks.

**Comment by olegkogan** [comment]
The same thing

**Comment by taion** [comment]
Use v1.0.0 and switch your imports to `react-relay/classic`.

**Comment by amkoehler** [comment]
Thanks, @taion. Upgrading to 1.0.0 and using the [codemod](https://github.com/relayjs/relay-codemod/blob/master/transforms/upgrade-requires-1.0.js) took us <30 minutes and now everything is cleared up.

**Comment by kassens** [comment]
We recommend upgrading and focus our energy on making the developer experience on the top better. Happy to hear that the upgrade to `react-relay/classic` wasn't too bad. Making the migration work is still something we think a lot about.
