### ISSUE TITLE
optimisticResponse function gets called, but UI does not re-render

### ISSUE THREAD

**Issue by lukecwilliams** [facebook/relay#1778]
I have the simple code below; the optimisticResponse is indeed getting called and checked, and as far as I can tell matches the graphql exactly.  However the component calling the mutation never rerenders.  Is something missing here or should this apply?

```
const mutation = graphql`
  mutation UpdateWaistSizeMutation($input: UpdateWaistSizeInput!, $date: String!) {
    UpdateWaistSize(input: $input) {
      userData {
        waistSize(date: $date)
      }
    }
  }
`;

export default function UpdateWaistSizeMutation(newWaistSize: number,
  date: string,
  userDataID: number) {

  const variables = {
    input: {
      waistSize: newWaistSize,
      date: date
    },
    date: date
  };

  const optimisticResponse = () => {
    console.log('optimistic call');
    return ({
    UpdateWaistSize: {
      userData: {
        waistSize: newWaistSize,
      },
    },
  })};

  commitMutation(environment, { mutation, optimisticResponse, variables });
}

```

**Comment by josephsavona** [comment]
Does userData have an id? Without that, Relay doesn't know how to update store automatically. The two options are to specify the userData.id value in the optimistic response or use an optimisticUpdater function that imperatively updates the store.

**Comment by lukecwilliams** [comment]
Thanks @josephsavona, that worked - we needed to return an id on userData equal to the Relay ID.

Why does this need an ID, but the [documented example](https://facebook.github.io/relay/docs/mutations.html) does not?  
```

const optimisticResponse = () => ({
  markReadNotification: {
    notification: {
      seenState: SEEN,
    },
  },
});

commitMutation(
  environment,
  {
    mutation,
    optimisticResponse,
    variables,
  },
);
```

I think a doc update would be helpful to other Relay Modern adopters, as I didn't find the hidden "id" requirement anywhere else.

**Comment by lukecwilliams** [comment]
@josephsavona Related question #2: Is there somewhere with a minimal example of Create/Update/Delete from a list of items with optimistic updates, or can this be provided?

We need to set up those optimistic updates, which I'm sure are a very common case, and we're shooting a bit in the dark because I'm not aware of any examples yet.

**Comment by lukecwilliams** [comment]
Since the original issue is solved, closing in favor of a new thread on the documentation requests.

https://github.com/facebook/relay/issues/1780
