### ISSUE TITLE
[Compat] Inline fragment documentation

### ISSUE THREAD

**Issue by ekosz** [facebook/relay#1779]
Hey there,

I'm going though and converting are code base to use Relay Mordern and I've hit an issue I can't seem to find any documentation / tests around. We have a peice of relay 1 code that looks like:

```js
const UserFrag = Relay.QL`fragment on User {
  name
  stauts
  # bunch of other props
}`;

export default Relay.createContainer(Thing, {
  fragments: {
    user: () => Relay.QL`fragment on User {
      ${UserFrag}
      manager {
        ${UserFrag}
        directReports { ${UserFrag} }
      }
    }`,
  }
});
```

But I can't seem to find how to pull off the same thing in Relay 2. I've tried:

```js
graphql`fragment Thing_user on User {
  id
  name
  ...Person_user
}`;

export default createFragmentContainer(Thing, graphql`
  fragment Thing_viewer on Viewer {
    user {
      ...Thing_user
      manager { ...Thing_user }
    }
  }
}
```

But I get the error 

```
Uncaught TypeError: (Thing.__container__ || Thing).getFragment is not a function
```

Is there a way of doing this with modern/compat modes?

**Comment by lukecwilliams** [comment]
Are you missing "on Viewer"?  I don't even get the Relay Compiler and babel to run if "on Viewer" is not included here.

    fragment Thing_viewer on Viewer {

**Comment by ekosz** [comment]
@lukecwilliams Whoops. Sorry I wrote out a contrived example rather than copy paste code. Just forgot to include that part. I've updated the example to include that part.

**Comment by brysgo** [comment]
Are they two different thing elements you are passing through to?

**Comment by nikhildaga** [comment]
@ekosz : Did you find a solution? We also want to share fragments but don't know if relay modern allows it or not.

**Comment by alloy** [comment]
Sharing just a fragment indeed can’t be done afaik, also because relay-compiler will validate that the fragment has the name of the module it resides in as its name prefix.
