### ISSUE TITLE
[relay-compiler] Issues in generated flow types

### ISSUE THREAD

**Issue by Mayank1791989** [facebook/relay#1783]
Importing flow types from generated files are not recognized by flow I think the issue is due to  mixing module.exports (commonjs) and using "export" for flow types.

**Comment by nirrek** [comment]
See https://github.com/facebook/relay/issues/1689 for a more detailed report of this issue and a decent short-term workaround for getting things working in your project.

Based upon Lee's comment https://github.com/facebook/relay/issues/1758#issuecomment-302685966 I wouldn't expect the ideal fix to ship anytime soon.

**Comment by Mayank1791989** [comment]
Thanks @nirrek. Closing this as duplicate of #1689
