### ISSUE TITLE
Local schema extensions

### ISSUE THREAD

**Issue by unirey** [facebook/relay#1787]
If you search repository for 'extensions', you can find few bits and pieces about it but it's still rather unclear. I can't even get past the compiler, it throws an error if you use fields not defined in schema. Does it have specific syntax?

This feature is advertised in release notes and docs, would love to know if all the pieces are there, to get few pointers and see a basic example of it. Would also love to know its (intended) use cases/limits (if there are any), particularly:

* only intended to extend already available types with **associated** data or is it more flexible?
* possible to store and get **arbitrary** data? _E.g_ language or bg color (think user preferences)

---

Would love to see a simple example for some arbitrary case, for example: 

(if this case is even possible and intended use case for local schema extensions)

* field `backgroundColor` that holds the HEX color code value as string
* write that value to Store (_e.g_ when page loads, get from LocalStorage and write)
* update/overwrite that value in Store (_e.g_ when user changes preference)
* get that value from Store (_e.g_ React component requires the value to set background color)

It seems to me that reading the value is just as quering any other data with `graphql` query which makes it available as a `prop` (at least in React) but how does it look like? Arbitrary data as a subfield for totally unrelated fragment/type? Outside the fragment?

Writing/updating seems to be done _via_ `environment.commitUpdate()`.

---

Can't wait to replace my dirty `context` based local store in application root.

**Comment by erikfrisk** [comment]
I also really want documentation on this. I think this issue is a duplicate of #1656 though.

**Comment by unirey** [comment]
Ah! Closing this issue in favor of #1656.
