### ISSUE TITLE
[Modern] How do you perform pull to get new item / pull to refresh on RN

### ISSUE THREAD

**Issue by bondanherumurti** [facebook/relay#1794]
I have successfully managed to perform pagination on my list, however i got confused on performing pull to get new item

this is my code

```
import Expo from 'expo';
import React, {Component} from 'react';
import {
  View,
  Text,
  FlatList,
  TouchableOpacity
} from 'react-native';

import {
  createPaginationContainer,
  graphql
} from 'react-relay';

class DummyList extends Component {
  renderItem(item) {
    return(
      <View style={{padding: 10}}>
        <Text key={item.node.id}>{item.node.title}</Text>
      </View>
    );
  }

  _loadMore() {

    if(!this.props.relay.hasMore() || this.props.relay.isLoading()){
      return;
    }

    this.props.relay.loadMore(
      10,
      e => {
        console.log('e', e);
      }
    )
  }

  render() {
    return(
      <View>
        <FlatList
          data={this.props.viewer.allDummies.edges}
          renderItem={({item}) => this.renderItem(item)}
          keyExtractor={(item, index) => item.node.id}
          onEndReached={() => this._loadMore()}
        />
        <TouchableOpacity style={{padding: 10}} onPress={() => this._loadMore()}>
          <Text>Load More</Text>
        </TouchableOpacity>
      </View>
    )
  }
}

export default createPaginationContainer(
  DummyList,
  {
    viewer: graphql`
      fragment dummyList_viewer on viewer {
        allDummies(first: $count, after: $cursor) @connection(key: "DummyList_allDummies"){
          edges{
            cursor
            node {
              id
              title
            }
          }
          pageInfo{
            hasNextPage
            endCursor
          }
        }
      }
    `
  },
  {
    getConnectionFromProps(props) {
      // console.log('getConnectionFromProps props', props);
      return props.viewer.allDummies;
      // return props.user && props.user.feed;
    },
    direction: 'forward',
    getFragmentVariables(prevVars, totalCount) {
      return {
        ...prevVars,
        count: totalCount
      }
    },
    getVariables(props, { count, cursor }, fragmentVariables) {
      return {
        count,
        cursor
      }
    },
    query: graphql`
      query dummyListQuery(
        $count: Int!
        $cursor: String
      ){
        viewer{
          ...dummyList_viewer
        }
      }
    `
  }
);
```

assuming the answer would be using refetchContainer then how to perform such thing while the flatList is already wrapped with createPaginationContainer

**Comment by jhalborg** [comment]
I'm interested in somewhat the same thing, but I would just like a simple "pull-to-refresh" feature that simply forces a re-fetch of the specified data, without taking paging or anything into account.

**Comment by sibelius** [comment]
you can use refetchContainer

**Comment by jhalborg** [comment]
@sibelius - Any way to do it without passing new variables? I would like to just call `this.props.relay.refetch(null, null)` or `this.props.relay.refetch({}, null)` or `this.props.relay.refetch()` for pull-to-refresh on views where the user would just want to check for new data, even though no pagination or any other variables has changed?

**Comment by jhalborg** [comment]
As in - right now it's a plain fragmentContainer with a static query (no variables). I want to add pull-to-refresh, so I was expecting to be able to just use a refetch-container instead, add a refresh-handler to my list that would call something like `this.props.relay.refetch()`, but no dice :)

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

If you're still having issues, it would be great to see a failing pull request. Or if you have more to share, please feel free to reopen it with an update.
