### ISSUE TITLE
Is there a way to declare to forceFetch a Relay fragment to avoid N requests?

### ISSUE THREAD

**Issue by joonhocho** [facebook/relay#1795]
I have two different React components that require a list of friends with different fields:

For example,

Screen A:
```
fragments: {
  user: () => Relay.QL`
    fragment on User {
      friends {
        id
        name
        picture
        fieldA // <-- different field
      }
    }
},
```

Screen B:
```
fragments: {
  user: () => Relay.QL`
    fragment on User {
      friends {
        id
        name
        picture
        fieldB // <-- different field
      }
    }
},
```

Since screen A and B share same friends, but require a different field on friends, Relay will try to fetch `fieldB` for each of user's friends and that maybe more than few hundreds of individual calls to the server.

I'd rather have a single call that refetches the entire friend list rather than 300 individual calls.
Is there a way to force this on `Relay.QL` level or React component level?
For example I'd want some components to always refetch its data regardless of cache status.

Thank you in advance.

**Comment by joonhocho** [comment]
Maybe related https://github.com/facebook/relay/issues/1793

**Comment by josephsavona** [comment]
In Relay Classic you can use forceFetch (It's a param on RelayRenderer and an alternative function to setVariables() in containers). Relay Modern doesn't do field diffing and so this behavior wouldn't occur.

**Comment by sibelius** [comment]
maybe you can use `nodes` field for this

**Comment by hkjorgensen** [comment]
Sounds very much like what I'm experiencing in https://github.com/facebook/relay/issues/1793
@josephsavona can you share a couple of more details? is this intended behavior in the classic API?

**Comment by josephsavona** [comment]
Relay Classic diffs lists of items one by one and creates a new query for each item that is missing data, so we'd expect to see N (typically small) queries in this case. These are sent to the network later as an array (the API is sendQueries() - plural), which means it's possible to write a custom network layer to send the queries to the server as a batch if your server supports this (we do this internally at FB). 

Relay Modern doesn't do field-level diffing so this wouldn't occur.

**Comment by hkjorgensen** [comment]
Thanks for sharing @josephsavona, `sendQueries` is also where I ended up. It's not an issue when the batch is in place. Still a big gotcha with the default behavior, suddenly our application spiked with 83 network requests for particular Renderer.

Side note: Have you considered optimizing the individual `node()` queries array and combine it into a `query { nodes() } ` if it's the same type?

**Comment by josephsavona** [comment]
We did consider coalescing the node queries, but the issue is that different fields may be missing for each node based on what you've fetched previously. So we'd have to do a full equality scan of every query before merging which may not be cheap. 

More generally diffing has edge cases like this, which is part of the motivation for not doing diffing in Relay Modern.

**Comment by joonhocho** [comment]
@josephsavona Based on your comments, I think going Modern sounds like the best solution for me. So, Modern Relay does not do any diffings at all? I thought that was one of the main strengths of Relay.

**Comment by josephsavona** [comment]
@joonhocho Diffing was an interesting aspect of Relay Classic, but over time we realized that diffing can have performance implications since it requires runtime query manipulation. We discuss the motivations behind Relay Modern in https://code.facebook.com/posts/1362748677097871/relay-modern-simpler-faster-more-extensible/ which I recommend for understanding the motivations behind the changes. Basically, Relay Modern builds on the core concepts of view/data collocation and declarative data fetching but embraces static queries for performance.

**Comment by joonhocho** [comment]
@josephsavona Thank you so much for your answer! Also feel free to close this issue.

**Comment by bochen2014** [comment]
@josephsavona  if you don't diff fields, what is `node` query for ?

**Comment by josephsavona** [comment]
We use (and suggest) the `node` root field as a convenient way to fetch (more) information about a node by id. Diffing out fields you've already fetched is an option, as used in Relqy Classic, but refetching all fields by default is simpler, more predictable, and allows build-time optimizations.

**Comment by bochen2014** [comment]
I think the other user case of `node`.qiery is `connection` which is still in use..

**Comment by yuzhi** [comment]
Looks like there is a lot of good discussion here already. I don't think there is any actionable items here for now. I'm going to clean up this issue, but please feel free to reopen if you have more questions.
