### ISSUE TITLE
extend documentation: document how to configure a webpack or create-react-app project 

### ISSUE THREAD

**Issue by barbalex** [facebook/relay#1796]
Seeing that relay modern integration in create-react-app is [not about to happen soon](https://github.com/facebookincubator/create-react-app/issues/2335) I tried to:

- create new create-react-app
- eject
- add support for relay modern

The last point turned out to be harder than I thought (well: not _that_ surprising: If this were easy cra would probably not exist). I could not find any instructions explaining how to configure a webpack project to work with an existing graphql endpoint (I am using [postgraphql](https://github.com/postgraphql/postgraphql)) and configure relay modern.

The [official relay tutorial](https://facebook.github.io/relay/docs/getting-started.html) shows how easy it is to work _once a project is configured_! The code examples are so to the point though that you can not even see from what packages the used functions were imported :-(. And it works by forking an already configured project instead of explaining how to configure _your_ project.

Everything I tried based on the [official relay example](https://github.com/relayjs/relay-examples/tree/master/todo-modern) did not work. There are also other examples (for instance [this](https://github.com/graphcool-examples/react-relay-todo-quickstart)) but it seems like there are many ways to do this and every example takes a different route and some may be specific for relay 1. Who knows...

It would be really nice if configuring a webpack project could be added to the docs.

**Comment by barbalex** [comment]
Additionally or alternatively it would be very helpful if in [example app](https://github.com/relayjs/relay-examples/blob/master/todo-modern) all occurrences of relay were commented to explain what is happening and why

**Comment by seanchas** [comment]
After eject

```
yarn add graphql react-relay react-compiler react-runtime
yarn add --dev babel-plugin-relay
mkdir schema
```


`config/paths.js`
```diff
module.exports = {
...
+ appSchema: resolveApp('schema/schema.graphql'),
...
}
```


`.env.local`
```diff
...
+ REACT_APP_GRAPHQL_ENDPOINT=<YOUR_GRAPHQL_ENDPOINT>
...
```


`scripts/schema.js`
https://gist.github.com/seanchas/b0632551d080598ad5b8e12cca762951


`package.json`
```diff
"scripts": {
+ "schema": "node scripts/schema.js",
+ "build-relay": "relay-compiler --src ./src --schema ./schema/schema.graphql",
+ "watch-relay": "yarn run build-relay -- --watch",
- "build": "node scripts/build.js",
+ "build": "yarn run build-relay && node scripts/build.js",
  ...
}

...

"babel": {
...
+ "plugins": {
+   "relay"
+ }
...
}
```

**Comment by barbalex** [comment]
@seanchas thanks a lot

That got me _just_ far enough so I managed to fetch my first data. Wohoo!!

**Comment by josephsavona** [comment]
Care to submit a PR to add these steps to the docs? :-)

**Comment by seanchas** [comment]
@josephsavona I don't speakEnglish **that** well, you know ;)

**Comment by josephsavona** [comment]
@seanchas We welcome contributions from multilingual speakers! (aside: several of us are non-native English speakers and almost everyone on the team speaks 2+ languages). If you have time a PR would be great, we can always help edit grammar :-)
