### ISSUE TITLE
[Question] Using Relay 2 for app state managemnet for the client without server

### ISSUE THREAD

**Issue by BrandoIsNotASword** [facebook/relay#1798]
I'm new to Relay in general, and I'll like to use Relay 2 for my project; currently we don't have a Graphql server. Reading through the docs of React Modern, I found that it is posible, apparently, with client schemas, to use Relay 2 as your state manager for the client side.

I haven't figured it out how to use it for my app. I read the todo-modern in the examples, but haven't had success.

Link to todo-modern: [https://github.com/relayjs/relay-examples/tree/master/todo-modern](url)

I'll like to know if someone have had success using Relay 2 with client schemas for the app state, or should I stick with Redux right now?

**Comment by josephsavona** [comment]
I would stick with Redux for now if all your data is client-side; Relay Modern has support for client fields but this is still experimental.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.
