### ISSUE TITLE
New User/Tutorial Feedback

### ISSUE THREAD

**Issue by BinaryMuse** [facebook/relay#180]
[Per @josephsavona's request](https://twitter.com/en_JS/status/635842439991836673), this is some initial feedback on my experience going through [the tutorial](https://facebook.github.io/relay/docs/tutorial.html). I should mention I had little exposure to and no experience with either GraphQL or Relay before this.

I started getting very lost around [the section on authoring a schema](https://facebook.github.io/relay/docs/tutorial.html#authoring-a-schema). I found myself typing the code listings to follow along, but not really understanding what everything meant or did as I did so (especially at the call to `nodeDefinitions` and when defining types/connections). There's quite a bit of verbose-looking code to it all, and I felt like it might be apparent to me at the end what it did, but that point never really came.

In the end, I got the game to work after some fiddling (I chose a different name for the mutation and thus the fat query's `fragment on CheckHidingSpotForTreasurePayload` didn't work), but I didn't really understand why, and my attempt to add a simple mutation to reset the game state without needing to restart the server took me a surprisingly large amount of time to get right.

In the end, I decided to start over and go as raw and simple as possible. With the help of [this article](https://medium.com/@clayallsopp/your-first-graphql-server-3c766ab4f0a2) I started with a *super minimal* schema, and once I got it working (and realized how little code was actually required), I managed to come up with this simple schema that fetches data from Reddit:

```javascript
import axios from "axios";

import {
  GraphQLSchema,
  GraphQLObjectType,
  GraphQLInt,
  GraphQLString,
  GraphQLNonNull,
  GraphQLList,
} from "graphql";


function dataFieldsWithType(fieldNames, type) {
  return fieldNames.reduce((acc, field) => {
    acc[field] = { type: type, resolve: (post) => post.data[field] };
    return acc;
  }, {});
}


const stringPostFields = dataFieldsWithType([
  "id", "domain", "subreddit", "selftext", "author",
  "thumbnail", "url", "permalink", "title"
], GraphQLString);

const numPostFields = dataFieldsWithType([
  "score", "num_comments", "ups", "downs"
], GraphQLInt);

const postType = new GraphQLObjectType({
  name: "Post",
  fields: Object.assign({}, stringPostFields, numPostFields)
});


const pageType = new GraphQLObjectType({
  name: 'Page',
  fields: {
    id: { type: new GraphQLNonNull(GraphQLString), },
    before: { type: GraphQLString, },
    after: { type: GraphQLString, },
    posts: {
      type: new GraphQLList(postType),
      args: {
        first: { type: GraphQLInt }
      },
      resolve: (post, {first = null}) => {
        if (first) {
          return post.children.slice(0, first);
        } else {
          return post.children;
        }
      }
    }
  }
});


const rootQuery = new GraphQLObjectType({
  name: 'RootQueryType',
  fields: {
    page: {
      type: pageType,
      args: {
        id: { type: new GraphQLNonNull(GraphQLString) },
        after: { type: GraphQLString }
      },
      resolve: (root, {id, after = ''}) => {
        return axios.get(`https://api.reddit.com/${id}?after=${after}`).then(({data}) => {
          return {
            id: id,
            before: data.data.beore,
            after: data.data.after,
            children: data.data.children
          }
        });
      }
    },
  }
});


const schema = new GraphQLSchema({
  query: rootQuery
});


export { schema as Schema };
```

It was then a relatively simple matter of copying patterns from the tutorial to render the data with React and Relay (after dropping the second `after` parameter from the root field). I was [very happy to see it all work](https://twitter.com/BinaryMuse/status/636737593577598976). Now that I understand the basics and have a somewhat-working knowledge, I feel comfortable with learning what's wrong/could be improved with my little schema, and [diving into graphql-relay](https://github.com/graphql/graphql-relay-js) and learning more advanced techniques.

In hindsight, I think my confusion stemmed from two things:

1. I wasn't very familiar with GraphQL. I understood the ideas, but basically none of the implementation. A skim of the spec helped, but at the time I felt there was very little official documentation to point me in the right direction. This is partially my fault for not being quite prepared, though either a pointer to another document or something to that matter would probably be helpful.
2. `graphql-relay`'s abstractions—while I'm sure they're very useful (I'm still digging in), they seemed to be the cause of what seemed like a lot of noise in the code as I was copying it down. The names didn't resonate any kind of meaning with me, and the documentation for them only makes sense if you're already familiar with the basics.

I hope this issue doesn't come off as too critical; the project is of course young, and docs are hard, and I was hardly the best candidate for them. :) Relay (and GraphQL) seems super cool, and I'm looking forward to learning more!

**Comment by josephsavona** [comment]
@BinaryMuse It's really helpful to have this kind of specific, constructive feedback as we improve the documentation. Thanks for this!

**Comment by josephsavona** [comment]
cc @steveluscher

**Comment by steveluscher** [comment]
This is excellent feedback @BinaryMuse; thank you! I hope that I've done it justice here: https://github.com/facebook/relay/issues/6#issuecomment-135514251.

**Comment by BinaryMuse** [comment]
The overview you [posted there](https://github.com/facebook/relay/issues/6#issuecomment-135514251) sounds perfect!

**Comment by wincent** [comment]
This looks closable to me now, thanks to https://github.com/facebook/relay/issues/6#issuecomment-135514251. Feel free to re-open if I am mistaken.

Thanks very much for the great feedback, @BinaryMuse!
