### ISSUE TITLE
[Modern] optimisticResponse not applied on simple mutation

### ISSUE THREAD

**Issue by lukecwilliams** [facebook/relay#1809]
I have two builds running side-by-side, one optimistic response works and one doesn't.  (Server response is applied correctly in both cases).  Have been debugging through Relay code for a few hours and think I need some help.

The sole difference in the code seems to be the name of the fields.  Is there some special functionality in relay-compiler that happens when the top-level object is called "viewer" instead of "userData"?

This code does not work (optimistic update is not applied), but when called `userData` instead of `viewer`, it applies.

```
const mutation = graphql`
  mutation UpdateWaistSizeMutation($input: UpdateWaistSizeInput!, $date: String!) {
    UpdateWaistSize(input: $input) {
      viewer {
        waistSize(date: $date)
      }
    }
  }
`;

  const optimisticResponse = () => ({
    UpdateWaistSize: {
      viewer: {
        // id is necessary for Relay to know which store item to update
        id: viewerId,
        waistSize: newWaistSize,
      }
    }
  });
```

Stepping through the code, the `selectors` created are much different between the two cases.  It looks like this is because the `taggedNode` created by relay-compiler actually creates significantly different `__generated__/*` files  in each case.  E.g. in `UpdateWaistSizePayload`:

**(works):**

```
"kind":"LinkedField",		
"alias":null,		
"args":null,		
"concreteType":"UserData",		
**"name":"userData",**		
```

**vs (doesn't work):**

```
"kind":"LinkedField",
**"alias":"viewer",** // ???
"args":null,
"concreteType":"Viewer",
**"name":"__viewer_viewer",** // ???

...

// (This section doesn't get generated when I call it userData)
{
"kind":"LinkedHandle",
"alias":null,
"args":null,
"handle":"viewer",
"name":"viewer",
"key":"",
"filters":null}],
```

([Full diff here](https://www.diffchecker.com/C870TQ7t).)

This `taggedNode` definition causes much different `selectors` to get created, which I think may be breaking the optimistic update.

Lastly, this._store.publish in RelayPublishQueue::_applyUpdates yields different results in both cases.

In the working (userData) case:
- _store._recordSource._records[userDataID] is properly updated with the new waist size
- there is a store record called `client:root:UpdateWaistSize` that has a `userData` member, which is just a `ref` with the userData ID.
- there is no `client:root:viewer` or `client:root:userData` record (see below)

In the broken (viewer) case:
- the viewerID record is properly updated with the new waist size (but the UI is **not** updated!)
- there is no client:root:UpdateWaistSize record in the store
- there **is** a `client:root:viewer` record, which appears to have duplicate data of everything under the [viewerID] record!  *This record is not updated during the optimistic update.*  So after _store.publish, there are **two differing sources of truth about `viewer`** - each showing a different waist size from the other.

Help?  I feel I understand Relay Modern's structure better after this debugging, but I still feel totally in the dark on why this very simple `optimisticResponse` isn't getting applied to the UI.

**Comment by josephsavona** [comment]
I believe that this in part due to an issue where viewer fields are transformed even when the Viewer type has an id (the transform is meant for the cases when th type is not identifiable by id). I have a pending PR to fix this. Cc @wincent

**Comment by josephsavona** [comment]
PR is #1804

**Comment by lukecwilliams** [comment]
@josephsavona Thanks Joe - it seemed like it had to be something specific to the name "viewer."  I'll keep an eye on the PR and we'll either use a different name or just wait on the PR to finish with optimistic updates.

**Comment by lukecwilliams** [comment]
Closing since #1804 has been imported.
