### ISSUE TITLE
[Modern] react-static-container dependency conflicting with react ^16.0.0

### ISSUE THREAD

**Issue by zunder** [facebook/relay#1811]
Is there a deeper need for the `react-static-container: 1.0.1` dependency right now? The module was not updated since more than a year and has a peerDependency on `react: ^15.0.0` at most. Meaning we can not use `react-native: ^43.0.0` as it is depending on `react: ^16.0.0`.

**Comment by kassens** [comment]
It'd be nice to get a release out for `react-static-container` for our next release. I'll push to get a new version out.

**Comment by vshab** [comment]
@kassens 
This is an issue :)

**Comment by leebyron** [comment]
Perhaps we could just get rid of this dependency altogether?

**Comment by leebyron** [comment]
The impl of it is quite small https://github.com/reactjs/react-static-container/blob/master/src/StaticContainer.react.js

**Comment by leebyron** [comment]
I'll get this included in the next release soon
