### ISSUE TITLE
Need to update to graphql v0.10.0 or later to avoid Flow errors

### ISSUE THREAD

**Issue by wincent** [facebook/relay#1815]
On Flow v0.47.0 we get a bunch of new errors:

https://travis-ci.org/facebook/relay/jobs/236607874

Most of them will be fixed by moving to GraphQL v0.10.0 or later (we actually released v0.10.1 today) plus one or two additional manual fixes by the looks of it.

**Comment by kassens** [comment]
Closed with 665166ab895d061374593195b38680b09fc459cd.
