### ISSUE TITLE
[Modern] commitMutation's onCompleted firing with undefined response on Android only

### ISSUE THREAD

**Issue by thatwillwork** [facebook/relay#1818]
I'm encountering a strange issue where `commitMutation` doesn't seem to be working properly on Android only. On my iOS simulator everything works as expected, but when I test on my Android device `onCompleted` seems to get called with the `response` undefined. 

Here is the `commitMutation` code:
```
    commitMutation(environment, {
      mutation,
      variables,
      updater: store => {
        console.log("this never gets printed");
      },
      onCompleted: (response) => {
        // response is undefined here
      },
      onError: err => {
        // error is also undefined here
      }
    });
```

Here is the `fetchQuery` function I pass to the `Network`:
```
function fetchQuery(operation, variables, cacheConfig, uploadables) {
  return fetch("https://XXXXXXX.com/graphql", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      Accept: "application/json"
    },
    body: JSON.stringify({
      query: operation.text,
      variables
    })
  })
    .then(response => {
        return response.json();
    })
    .then(responseData => {
      console.error(responseData);
      return responseData;
    })
    .catch(error => {
      console.error(error);
    });
}
```

According to the `console.error(responseData)` call in the `fetch` function call above, the `responseData` is correct and consistent across the iOS simulator and my Android device. This leads me to believe that the response is getting lost between the `fetch` call and the callback set up in `commitMutation`.

Another observation is that when remote JS debugging is enabled on Android, the response returned is actually not undefined. Using the inspector the only difference between the network responses is that `responseType` is empty when remote JS debugging is off, and `responseType` is `blob` when remote JS debugging is on.

This is the full package.json used:
```
{
  "name": "foo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "flow": "flow check",
    "test": "jest",
    "relay": "relay-compiler --src ./src --schema schema.graphql",
    "get-schema": "node scripts/getSchema.js"
  },
  "dependencies": {
    "@shoutem/ui": "shoutem/ui#242/head",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-gifted-chat": "^0.1.4",
    "react-native-vector-icons": "^4.0.1",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.2",
    "react-relay": "^1.0.0",
    "redux": "^3.6.0",
    "redux-persist": "^4.7.1"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-plugin-relay": "^1.0.1",
    "babel-preset-react-native": "1.9.1",
    "flow-bin": "0.37.0",
    "jest": "18.1.0",
    "react-test-renderer": "~15.4.0",
    "relay-compiler": "^1.0.0"
  },
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "<rootDir>/jest.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-native-tab-view|react-navigation|fbjs|@shoutem)"
    ]
  }
}
```

Any help would be greatly appreciated!

**Comment by gusbicalho** [comment]
Might be related to https://github.com/facebook/relay/issues/1797 and https://github.com/facebook/relay/issues/1704, please try the polyfill in the latter to see if it works.

**Comment by leebyron** [comment]
This definitely sounds related, @gusbicalho!

Unfortunately a bug in core-js is wrecking havok on Android devices when used alongside React Native. I'm working on a patch to remove reliance on it.

**Comment by thatwillwork** [comment]
Turns out it was related. The monkey patch fixed the issue!

**Comment by leebyron** [comment]
Closing since the problematic Set polyfill will no longer be included in the next release.
