### ISSUE TITLE
[Modern] Payload did not contain a value for field

### ISSUE THREAD

**Issue by Rodeoclash** [facebook/relay#1821]
I'm getting this warning in the console however it does not seem to affect the behaviour of the app. Inspecting the query sent to the server, it seems like my GraphQL server (Absinth) is optimising the query and not returning part of the tree that is duplicated in another area. (In this exact case, products that are on the page are also part of the shopping cart, asking for the product list will omit all matching products in the cart).

While the page behaves correctly, I suspect this is only because the data is available in the graph under the id by coincidence of being returned somewhere else.

Is this warning occurring because of a stricter reliance on valid GraphQL responses (and that Absinth is at fault for omitting / optimising items)?

**Comment by yuzhi** [comment]
Yes. Sounds like the warning you are getting is because the client did not get a valid GraphQL response based on the query it has sent.
