### ISSUE TITLE
relay-compiler throws "unknown field" error on query that runs flawlessly in graphiql

### ISSUE THREAD

**Issue by barbalex** [facebook/relay#1823]
I believe my project is correctly configured.
So far everything has worked nicely - thanks for this _amazing_ project!

When I run relay-compiler like this:

    npm run build-relay

which calls:

    "scripts": {
      "build-relay": "relay-compiler --src ./src --schema ./schema/schema.graphql",
      ...
    },

I get this error:

    PS C:\Users\alex\ae2> npm run build-relay

    > ae2@0.1.0 build-relay C:\Users\alex\ae2
    > relay-compiler --src ./src --schema ./schema/schema.graphql

    HINT: pass --watch to keep watching for changes.
    Parsed default in 0.06s

    Writing default
    Invariant Violation: RelayParser: Unknown field `taxonomyObjectLevel1` on type `Query`. Source: document `TreeTaxonomyObjectLevel1Query` file: `GraphQL`.
        at invariant (C:\Users\alex\ae2\node_modules\fbjs\lib\invariant.js:44:15)
        at RelayParser._transformField (C:\Users\alex\ae2\node_modules\relay-compiler\bin\relay-compiler:2356:28)
        at C:\Users\alex\ae2\node_modules\relay-compiler\bin\relay-compiler:2283:24
        at Array.map (native)
        at RelayParser._transformSelections (C:\Users\alex\ae2\node_modules\relay-compiler\bin\relay-compiler:2280:37)
        at RelayParser._transformOperation (C:\Users\alex\ae2\node_modules\relay-compiler\bin\relay-compiler:2246:28)
        at RelayParser.transform (C:\Users\alex\ae2\node_modules\relay-compiler\bin\relay-compiler:2137:22)
        at Object.transform (C:\Users\alex\ae2\node_modules\relay-compiler\bin\relay-compiler:2106:18)
        at C:\Users\alex\ae2\node_modules\relay-compiler\bin\relay-compiler:1142:37
        at Array.map (native)

Component `TreeTaxonomyObjectLevel1` contains this query:

```JSX
<QueryRenderer
  environment={environment}
  query={graphql`
    query TreeTaxonomyObjectLevel1Query {
      taxonomyObjectLevel1 {
        nodes {
          id
          name
        }
      }
    }
  `}
  render={({ error, props }) => {
    // ...
  }}
/>
```

What baffles me is that the exact same query runs flawlessly in http://localhost:5000/graphiql:

```GraphQL
{
  taxonomyObjectLevel1 {
    nodes {
      id
      name
    }
  }
}
```

When I exchange above query with a different one no error occurs. So I _think_ component `TreeTaxonomyObjectLevel1` is correctly built.

`taxonomyObjectLevel1` is provided by the following function in PostgreSQL via [postgraphql](https://github.com/postgraphql/postgraphql):

```sql
CREATE OR REPLACE FUNCTION ae.taxonomy_object_level1()
  RETURNS setof ae.taxonomy_object AS
  $$
    SELECT *
    FROM ae.taxonomy_object
    WHERE parent_id IS NULL
  $$
  LANGUAGE sql STABLE;
ALTER FUNCTION ae.taxonomy_object_level1()
  OWNER TO postgres;

```

**Comment by josephsavona** [comment]
What does the Query type look like in your schema.graphql file? Does that field exist there?

**Comment by barbalex** [comment]
No, I can't find anything containing the string `level1` in there (case insensitive search)

**Comment by josephsavona** [comment]
Hmm. That seems like the problem, since Relay Compiler uses that file to determine what fields/types exist in your schema - double check that schema.graphql is up to date? Otherwise maybe your server is returning incorrect results for the introspection query (?).

**Comment by barbalex** [comment]
Yep: I ran `node scripts/schema.js` and now it works.

I thought running `npm run build-relay -- --watch` was enough?

**Comment by josephsavona** [comment]
`--watch` watches your JS files for changes to queries, but does not watch the schema as there isn't a standard way to watch for schema changes.

**Comment by unirey** [comment]
Node server uses `GraphQLSchema` (why GraphiQL works), compiler uses `schema.graphql` file. Unless you've automated it - if you change anything about `GraphQLSchema`, you have to manually update `schema.graphql` and by *anything* I mean GraphQL types, names, fields. Take a look at `schema.graphql` file and you'll get the basic idea what updates to `GraphQLSchema`  require `schema.graphql` update.

**Comment by barbalex** [comment]
Thanks a lot guys!
