### ISSUE TITLE
relay-compiler: Add support for mutations without input

### ISSUE THREAD

**Issue by mgtitimoli** [facebook/relay#1825]
Hi there,

Currently, as you can see [here](https://github.com/facebook/relay/blob/296e0b703d5bc8fd556b26dde7094d855367468f/packages/relay-compiler/codegen/flowtype/printFlowTypes.js#L48), there is an assumption that `selection.args[0]` is never empty, or in other words, mutations are expected to always require an input.

![image](https://cloud.githubusercontent.com/assets/4404683/26564042/527c4ba6-44b2-11e7-9c3f-a09122a3ebfe.png)
 
**FTR**: the mutation we have has no input, since the only thing it needs is the accessToken and this is obtained from the headers.

Are we missing something, or this is indeed a bug?

Thanks!

**Comment by josephsavona** [comment]
Yeah, this is a bug in the [Flow type printer](https://github.com/facebook/relay/blob/296e0b703d5bc8fd556b26dde7094d855367468f/packages/relay-compiler/codegen/flowtype/printFlowTypes.js#L48), which only handles the Relay classic style of mutations, whereas the modern *runtime* supports arbitrary mutation arguments. This should probably map over `selection.args` instead of extracting just the first one. cc @kassens

**Comment by mgtitimoli** [comment]
I guess something like this should work, what do you think @josephsavona?

```javascript
        const nodes = selection.args.map(transformInputObjectToIR);

        if (node.name !== RELAY_CLASSIC_MUTATION) {
          selection.name = `${node.name}Response`;
          nodes.push(selection);
        }

        return nodes
          .map(n => generate(normalize(transform(n))).code)
          .join('\n\n');
```

**Comment by josephsavona** [comment]
I think so, though @kassens is much more familiar with the Flow type generation. Try it out, what does the output look like?

**Comment by josephsavona** [comment]
Currently the exported Flow types have something like 

```
export type CreatePostInput = {
  title?: ?string;
  url?: ?string;
  votes?: ?number;
};
```

It would probably be preferable to have an object representing the variables that the mutation expects, something like:

```
export type CreatePostInput = {
  title?: ?string;
  url?: ?string;
  votes?: ?number;
};
export type CreatePostVariables = {
  input: CreatePostInput,
};
```

Exporting a type for each argument would maintain backwards compatibility, while the new merged "<Foo>MutationVariables" type would be useful for typing the total variables expected as input to the mutation. If we did this, it would also be useful for queries/subscriptions too.

**Comment by mgtitimoli** [comment]
Sorry, there was a mistake, normalize(transform(n)) returns an Array, so it has to be flatten before passing it to generate...

I've just tested the following code and it worked:

```javascript
const nodes = selection.args.map(__webpack_require__(72));

if (node.name !== RELAY_CLASSIC_MUTATION) {
  selection.name = node.name + 'Response';
  nodes.push(selection);
}

return nodes.reduce((codes, node) => codes.concat(
  normalize(transform(node)).map(n => generate(n).code)
), []).join('\n\n');
```

**Comment by mgtitimoli** [comment]
@josephsavona this would be great:

> Exporting a type for each argument would maintain backwards compatibility, while the new merged "MutationVariables" type would be useful for typing the total variables expected as input to the mutation. If we did this, it would also be useful for queries/subscriptions too.

should we meanwhile merge that fix I wrote, or do find it better go for this directly?

**Comment by josephsavona** [comment]
@mgtitimoli Yeah we can do this in two stages. Would you mind sending your changes as a PR?

**Comment by mgtitimoli** [comment]
@josephsavona sure, let me prepare it and I'll send it, and regarding with your proposal, I need to have a deep look to the code to understand the required changes to make this possible, I will try to do it this week, don't you mind opening an issue describing it? (this way we might also get some feedback for more people)

**Comment by mgtitimoli** [comment]
done @josephsavona, thanks for your help!

**Comment by alloy** [comment]
The Flow code has seen significant changes since this ticket was filed and unfortunately the linked PR (#1827) no longer applies and has been closed. So I think that it makes sense to close this too and see if this gets reported again and we can address it then.

@mgtitimoli Please do re-open if you are still dealing with this, though!
