### ISSUE TITLE
[Modern] Use fragments that are not related to components.

### ISSUE THREAD

**Issue by miracle2k** [facebook/relay#1831]
I frequently feel the desire to define a standalone fragment. One example is that I render a fragment container that might have this query:

```
fragment List_offers on Viewer {
    offers(first: $count) @connection(key: "List_offers")
    {
      edges {
        node {
          id,
          name
        }
      }
    }
  }
```

I now have a mutation that insert an edge into this connection. For this purpose, I want the connection to query the same fields as the List component, in this case, id and name.

I'd like to make a separate fragment for this:

```
fragment FooBarBaz on Offer {
   id,
   name
}
```

and then use that in both the List query and the mutation.

The reason this doesn't work is that, I think, the system refuses to actually inline these fragments so that List_offers could access them. When a fragment is used in a container it is always assumed that it comes from a child component.

I know that one solution is to factor out the part that needs ``FooBarBaz`` into it's own child-component, but I don't like that I am forced to do so.

**Comment by JenniferWang** [comment]
@kassens @leebyron I remember that we've discussed `@inline` directive at some point to address similar problems.

**Comment by robrichard** [comment]
The app that I converted to Relay Modern had a few of these. I worked around it by using a function like this:

```js
import {getSelector} from 'relay-runtime';

export const viewerFragment = graphql`
    fragment List_viewer on Viewer {
        myField
    }
`;

function getViewerFragmentData(relayContext, viewer) {
    const selector = getSelector(
        relayContext.variables,
        viewerFragment.viewer(),
        viewer
    );
    return relayContext.environment.lookup(selector).data;
}
```

**Comment by nishp1** [comment]
@JenniferWang Where would one start if we wanted to build custom directives into modern like `@inline` and `@defer`(more appealing to me).

**Comment by wincent** [comment]
Thanks for the input here. We're currently going through old issues that appear to have gone stale (ie. not updated in about the last 3 months) because the volume of material in the issue tracker is becoming hard to manage. If this is still important to you please comment and we'll re-open this.

Thanks once again!

**Comment by miracle2k** [comment]
For anyone finding this ticket: It's my understanding that Relay now support this.
