### ISSUE TITLE
relay.refresh resetting store

### ISSUE THREAD

**Issue by reactor81** [facebook/relay#1845]
i am finsing that the second time I call relay.refresh (Relay Modern), my store is being erased. Does anyone have thoughts on what may be causing this? 

Anyone seen similar behaviornof relay.refresh breaking the store?

Also, are there any examples of relay.refresh in use? Im actually just trying to pass a component's prop value into the relay fragment, bit couldn't see an example of that, so I had to move to the refreshContainer which is causing me to queey twice, just to get the prop value into the relay fragment :(

**Comment by yuzhi** [comment]
@reactor81 can you clarify what `relay.refresh` you are referring to is? I don't think I recognize that API.

**Comment by alloy** [comment]
Going to close this due to inactivity. Please re-open if this issue still applies, though!
