### ISSUE TITLE
How do we use RelayNetworkLogger?

### ISSUE THREAD

**Issue by taion** [facebook/relay#1856]
Regarding: https://github.com/facebook/relay/blob/v1.0.0/packages/relay-runtime/network/RelayNetworkLogger.js

There doesn't seem to be any documentation here. Is the idea to call:

```js
const network = Network.create(
  RelayNetworkLogger.wrapFetch(fetchQuery, () => ''),
);
```

Would it make sense to make the `graphiQLPrinter` argument optional?

**Comment by kassens** [comment]
Yes, that's the idea. We do it internally for dev builds and skip the network logger wrapping for production.

We saw people internally really like `graphiQLPrinter` as it prints a link in the console that's clickable to take you straight to the query in GraphiQL, but seems totally reasonable to make this optional and just skip printing the link.

Happy to accept a PR for docs or the small API change!
