### ISSUE TITLE
[Modern] props are not uptodate in the callback of the refetch function of RefetchContainer 

### ISSUE THREAD

**Issue by JacquesBergou** [facebook/relay#1859]
When I call the `refetch` function with a callback argument (3rd arg) on a  `RefetchContainer`, the callback is well called just after the fetch to the server, BUT the props are not yet uptodate with the just fetched data (I'm in the case where there are no errors on the server).
I try to move the calling line in [ReactRelayRefetchContainer.js](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayRefetchContainer.js#L228)

        // TODO t15106389: add helper utility for fetching more data
        this._pendingRefetch = null;
        // callback && callback(); /// move the call after this.setState
        this._resolver.setVariables(fragmentVariables);
        this.setState({data: this._resolver.resolve()});
        callback && callback();

in that case, the props are updated when callback in called, BUT the callback is called **after** the next  `render` which is not good.

Is there a way to have a callback with the updated props and before the next fetch?

**Comment by bondanherumurti** [comment]
referencing https://github.com/facebook/relay/issues/1792

**Comment by mmjd** [comment]
fixed in 1.2.0-rc.1
