### ISSUE TITLE
[Modern] relay-compiler with Typescript?

### ISSUE THREAD

**Issue by voxmatt** [facebook/relay#1863]
The errors coming out of `relay-compiler` are a bit difficult to follow (added some logging to troubleshoot), but I assume it's choking on Typescript syntax somewhere because this:

`relay-compiler --src ./src --schema ./build-util/schema.gql --extensions ts tsx`

Yields this: `SyntaxError: Unexpected token, expected } (66:36)`

I'm happy to dive into this one, but would appreciate any guidance on how I might get the compiler working with Typescript files. Seems like "swapping in your own `FileWriter` and `FileParser`, or by adding on an additional `IRTransform`" is the way to go, but any additional docs/guidance would be much appreciated!

**Comment by sibelius** [comment]
try this one https://github.com/facebook/relay/pull/1710

**Comment by kassens** [comment]
Closing as duplicate. I hope we can make progress on the linked issue very soon.
