### ISSUE TITLE
[relay-modern]  response never gets resolved in latest master branch

### ISSUE THREAD

**Issue by bochen2014** [facebook/relay#1864]
I just compiled and deployed latest `realy` master branch to my application and found that my page never gets rendered. I digged in a bit and find the issue might because of [fetch](https://github.com/facebook/relay/blob/master/packages/relay-runtime/network/RelayNetwork.js#L136)
we might missing `await` there or did I miss something?  

@jewang

**Comment by josephsavona** [comment]
A recent change to the network layer broke compatibility. I have a fix for this in #1862. 

@JenniferWang can we move forward with that PR? The recent network changes completely break OSS.

**Comment by bochen2014** [comment]
what does oss stand for?
