### ISSUE TITLE
[Modern] How do I make use of generated type annotation? 

### ISSUE THREAD

**Issue by bochen2014** [facebook/relay#1865]
I'm not an expert of `flow` but can understand a large part of it;
I noticed `relay-compiler` generated artifacts contain flow type annotations for my `graphql` literals which is great, *but*, type annotations are commented out by default (do we I have to uncomment them ?)

for example:  the generated `__generated__/Todo_todo.graphql.js` contains the flowing:
```
/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Todo_todo.graphql
 * @generated SignedSource<<3bb8d45a6a5c6505ba77db85d6f80567>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Todo_todo = {
  complete?: ?boolean;
  id: string;
  text?: ?string;
};
*/
const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",

..................

```

I made a few attempts to import these types in my container source file
1.  uncomment `  /*::  export type Todo_todo = {  ... */`  in `Todo_todo.graphql.js`
2.  in my `Todo.js`
```
import type{
  Todo_todo
} from 'Todo_todo.graphql';

```

but `flow` complains `TodoList_viewer.graphql. Required module not found`

we already have `@providesModule Todo_todo.graphql` in place to tell `flow` to use current file when resolving the module, so why is `flow` still complaining?
what shell I do to make it work?

**Comment by bochen2014** [comment]
https://github.com/facebook/relay/issues/1689

**Comment by wincent** [comment]
I see you've closed this, but for future reference, the comment syntax `/*:: */` is [understood by Flow](https://flow.org/en/docs/types/comments/#comment-types-syntax-a-classtoc-idtoc-comment-types-syntax-hreftoc-comment-types-syntaxa) and the contents of the comment are parsed as though they were uncommented source code.

**Comment by bochen2014** [comment]
great! thanks @wincent
