### ISSUE TITLE
error on react native 45 and react 16-alpha.12

### ISSUE THREAD

**Issue by sibelius** [facebook/relay#1866]
I'm using react-relay 1.0.0
I've upgraded my react native code to RN 45, and it is throwing the following error:

![image](https://user-images.githubusercontent.com/2005841/26897091-90c3c1ae-4b9d-11e7-907d-a735e0175f2f.png)

in this line: `require('./relayUnstableBatchedUpdates')`

```jsx
var mounted = _this3.mounted;
        if (mounted) {
          var updateProfiler = require('./RelayProfiler').profile('RelayContainer.update');
          require('./relayUnstableBatchedUpdates')(function () {
            _this3.setState(partialState, function () {
              updateProfiler.stop();
              if (isComplete) {
                completeProfiler.stop();
              }
            });
            if (callback) {
              callback.call(
              // eslint-disable-next-line react/no-string-refs
              _this3.refs.component || null, (0, _extends3['default'])({}, readyState, { mounted: mounted }));
            }
          });
        } else {
```

**Comment by joonhocho** [comment]
I am still using react-relay/classic, and I just upgraded react-native to v0.45.1 and I started getting the following error:

this._batchUpdate is not a function.

![simulator screen shot jun 9 2017 8 55 17 pm](https://user-images.githubusercontent.com/930795/26999739-fd3b8588-4d55-11e7-84cd-a5ad7c5db6dc.png)

**Comment by lprhodes** [comment]
Seeing this too - have you found any work-arounds?

**Comment by juhaelee** [comment]
@joonhocho I'm also getting this error, did you resolve it?

**Comment by joonhocho** [comment]
@lprhodes @juhaelee Not yet. For now, I just downgraded my react-native.

**Comment by alloy** [comment]
I have fixes for this in a branch that I’m updating as I go through upgrading our app. I’ll move extract these to a PR later today.

**Comment by alloy** [comment]
Please give #1889 a try (I’m not yet done with the conversion of our app)

**Comment by yungsters** [comment]
@spicyj helped me debug this. So `relayUnstableBatchedUpdates.native.js` does the following:

```
const ReactNative = require('ReactNative');

module.exports = ReactNative.unstable_batchedUpdates;
```

However, `ReactNative` [gets mapped to](https://github.com/alloy/relay/blob/master/gulpfile.js#L39) `react-native` which, according to the [`react-native/package.json`](https://github.com/facebook/react-native/blob/master/package.json#L86), is actually (and confusingly) [`react-native-implementation.js`](https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native-implementation.js).

Notice that `react-native-implementation.js` does not currently export `unstable_batchedUpdates`, which means that `relayUnstableBatchedUpdates` is likely coming up as undefined.

@sibelius Can you try modifying `react-native-implementation.js` to export `unstable_batchedUpdates` and see if this resolves the bug? If so, either you can send a pull request or I can make the change to export it.

Separately, we really need to rename `ReactNative.js` to something else (e.g. `ReactNativeRenderer.js`) and rename `react-native-implementation.js` to `ReactNative.js`. But that's a separate issue.

**Comment by spicyj** [comment]
> and rename `react-native-implementation.js` to `ReactNative.js`. But that's a separate issue.

To be fair, I suggested `ReactNativeEverythingBagel.js`.

**Comment by yungsters** [comment]
@sibelius or @alloy, can either of you see if https://github.com/facebook/react-native/commit/5550a25628fe04899b737597fa06d9bb979b499d helps?

**Comment by joenoon** [comment]
@yungsters https://github.com/facebook/react-native/commit/5550a25628fe04899b737597fa06d9bb979b499d worked for me so far.  I'm in the middle of a big upgrade, so possible I'll run into something else, but so far so good!

**Comment by gre** [comment]
facebook/react-native@5550a25 works great

**Comment by alloy** [comment]
@yungsters Been a while, our migration was on hold. I can confirm that that patch fixes the issue 👍

**Comment by yungsters** [comment]
Perfect.
