### ISSUE TITLE
A bizarre error caused by a bug in the Set class on react native

### ISSUE THREAD

**Issue by mzdunek93** [facebook/relay#1875]
I've been having problems with passing my data using relay to the component - the data was correctly fetched from the server, but the `props` variable passed to the render function on the `QueryRenderer` component was still empty. After a bit of an investigation, I found out that the `_commitPayloads` function on the `RelayPublishQueue` class was not working properly. Namely, this part:

```
    if (!this._pendingPayloads.size) {
      return;
    }
```

Logging revealed that although the `_pendingPayloads` collection contained some elements, `this._pendingPayloads.size` was null. So I changed the code to this:

```
    var size = 0;
    this._pendingPayloads.forEach(function (_ref2) {
      ++size;
    });

    if (!size) {
      return;
    }
```

And it works perfectly. Clearly, the `size` property on the `Set` class is not working properly here. The code initiation the `_pendingPayloads` variable looks like this in my library files:

```
var _set2 = _interopRequireDefault(require('babel-runtime/core-js/set'));
this._pendingPayloads = new _set2['default']();
```

Is there any permanent solution to this problem that's better than manually editing library files? Here are all of my dependencies:

```
  "devDependencies": {
    "babel-plugin-relay": "^1.0.1",
    "flow-bin": "0.47.0",
    "jest-expo": "~1.0.1",
    "react-native-scripts": "0.0.31",
    "react-test-renderer": "16.0.0-alpha.6",
    "relay-compiler": "^1.0.0"
  },
  "dependencies": {
    "expo": "^17.0.0",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0",
    "react-native-swiper": "^1.5.4",
    "react-navigation": "^1.0.0-beta.11",
    "react-relay": "^1.0.0"
  }
```

**Comment by sibelius** [comment]
This will be fixed in next Relay release

**Comment by kassens** [comment]
Yeah, @leebyron removed the bundled Set, Map and Promise polyfills. With the next release you'll have to provide your own polyfill if the environment doesn't come with them. I'm pretty sure RN includes a modern enough js engine.
