### ISSUE TITLE
scripts/schema.js causes UnhandledPromiseRejectionWarning, only on macOS

### ISSUE THREAD

**Issue by barbalex** [facebook/relay#1876]
[This](https://github.com/barbalex/ae2/blob/master/scripts/schema.js) is my schema.js file.

When I run `node scripts/schema.js` this error occurs:

    Alexanders-MBP:ae2 alex$ npm run schema

    > ae2@0.1.0 schema /Users/alex/ae2
    > node scripts/schema.js

    (node:18932) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Parameter "url" must be a string, not undefined
    (node:18932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This only happens on my mac notebook (macOS Sierra 10.12.5). On my Windows 10 PC it works fine.
I am running node v8.1.
[My schema](https://github.com/barbalex/ae2/blob/master/schema/schema.graphql) is created by [postgraphql](https://github.com/postgraphql/postgraphql).

**Comment by barbalex** [comment]
I have deleted and reinstalled `node_modules`, to no avail.

**Comment by barbalex** [comment]
Same error occurs with node v6.11.0 on macOS.

**Comment by kassens** [comment]
Sounds like `process.env.REACT_APP_GRAPHQL_ENDPOINT` is `undefined` here, try replacing that with your server URL: https://github.com/barbalex/ae2/blob/master/scripts/schema.js#L14

**Comment by barbalex** [comment]
Yep, that is true.

It turns out that `.env.local` was included in `.gitignore` and so never made it from my Windows 10 PC (where the project was ejected from create react app) to my macOS notebook :-(

Thanks a lot!
