### ISSUE TITLE
[modern] (compat) undefined props on RefetchContainer

### ISSUE THREAD

**Issue by sibelius** [facebook/relay#1884]
```jsx
const UserRefetchContainer = createRefetchContainer(SendMessage,
  //language=GraphQL
  graphql.experimental`
    fragment User_query on Query
    @argumentDefinitions(
      ids: {type: "[ID!]!", defaultValue: ["UGVyc29uOjg3MjU1MDA2", "UGVyc29uOjExMjMyNjMz"]}
    ) {
        nodes(ids: $ids) {
          id
          ... on User {
            name
          }
        }
      }
  `,
  //language=GraphQL
  graphql.experimental`
    query UserRefetchQuery($ids: [ID!]!) {
      ...SendMessage_query @arguments(ids: $ids)
    }
  `,
);


const UserQueryRenderer = (args) => (
  <QueryRenderer
    environment={environment}
    query={graphql.experimental`
      query UserQuery($ids: [ID!]!) {
      ...User_query @arguments(ids: $ids)
    }
    `}
    variables={{
      ids: ["UGVyc29uOjg3MjU1MDA2", "UGVyc29uOjExMjMyNjMz"],
    }}
    render={({error, props}) => {
      console.log('render: ', error, props, args);
      if (props) {
        return <UserRefetchContainer {...props} />;
      } else {
        return (
          <Text>Loading</Text>
        )
      }
    }}
  />
);
```

QueryRenderer props are returning undefined

the queries works fine on graphql

**Comment by sibelius** [comment]
I've created a field `peopleByIds(ids: $ids)` on `ViewerType` and it worked well

Does we have any tests of usage of `nodes` or `node` with Relay Modern?

**Comment by josephsavona** [comment]
Thanks for filing this. A couple questions: 
- In the QueryRenderer query you have `...User_query @arguments(ids: $ids)` - did you mean `... SendMessage_query @arguments(ids: $ids)`? It looks like you might be referencing the wrong fragment.
- In the description you mention that QueryRenderer props are undefined, but the title says RefetchContainer props are undefined - can you clarify which is the case? What data is returned by the network?

**Comment by josephsavona** [comment]
Note that there *might* be an issue with fragments on the Query type in compat mode. I would try moving the `nodes` field up to the QueryRenderer query instead.

**Comment by sibelius** [comment]
> In the QueryRenderer query you have ...User_query @arguments(ids: $ids) - did you mean ... SendMessage_query @arguments(ids: $ids)? It looks like you might be referencing the wrong fragment.

this was a typo, fixed

I've moved `nodes` to QueryRenderer.
I've added __typename and id on `nodes` it fetches well, but it does not handle well

```graphql
... on User {
            name       
   }
```

neither in RefetchContainer, neither in QueryRenderer inlined

**Comment by sibelius** [comment]
I think QueryType does not work fine on compat mode

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

If you're still having issues, it would be great to see a failing pull request. Or if you have more to share, please feel free to reopen it with an update.
