### ISSUE TITLE
[compat] updater and optimisticUpdater are never called when trying to commit a mutation in react-relay/compat

### ISSUE THREAD

**Issue by codepreneur** [facebook/relay#1890]
```
const {commitMutation} = require('react-relay/compat');

type Variables = {[name: string]: any};

commitMutation(
  environment: Environment,
  config: {
    mutation: GraphQLTaggedNode,
    variables: Variables,
    onCompleted?: ?(response: ?Object) => void,
    onError?: ?(error: Error) => void,
    optimisticResponse?: ?() => Object,
    optimisticUpdater?: ?(store: RecordSourceSelectorProxy) => void,
    updater?: ?(store: RecordSourceSelectorProxy) => void,
  },
);
```

@sibelius @leebyron

**Comment by sibelius** [comment]
Relay compat will use getConfigs instead of updater

**Comment by JenniferWang** [comment]
Yep, the above comment is correct.

**Comment by MaxAggedon** [comment]
Hi, the RANGE_ADD config is has changed between classic and modern: `connectionName` and `rangeBehavior` became `connectionInfo`.

Does this mean that this kind of store update is not possible in compat ?

If it is still possible, would you have an example ?

**Comment by toxsick** [comment]
Hi,

this prevents us to rewrite mutations while migrating to modern with compat mode. I have written a small blogpost about this issue:

https://www.froehlichundfrei.de/blog/2017-11-08-bug-of-the-week-relay-compat-mode/

cheers

**Comment by maxaggedon** [comment]
Thanks for the answer ! I have updated everything to use the modern api now anyway =)

**Comment by sibelius** [comment]
it looks like we could make it work using this helper

https://github.com/facebook/relay/blob/master/packages/react-relay/compat/ReactRelayCompatPublic.js#L52

`applyOptimisticMutation`

**Comment by sibelius** [comment]
or use `optimisticResponse`

https://github.com/facebook/relay/blob/master/packages/react-relay/compat/mutations/RelayCompatMutations.js#L88
