### ISSUE TITLE
[Compat] Filename is expected to use the same case of container variable

### ISSUE THREAD

**Issue by alloy** [facebook/relay#1893]
* `relay-compiler` expects fragments to be named after the filename they are defined in 
* The fragments included in a classic node are expected to exist on variables in scope [named after the prefix](https://github.com/facebook/relay/blob/ed5f4f9d3a575236f503778915dcbbf19c8e2440/packages/babel-plugin-relay/createClassicNode.js#L397) of the fragment name.

----

Our filenames use snake-case, but we name our containers using camel-case. For instance, consider the following pathname `dist/lib/components/artist/articles/article.js`, which would contain code like:

```js
import { createFragmentContainer, graphql } from "react-relay/compat"

export default createFragmentContainer(Article, {
    artist: graphql `
      fragment article_artist on Article {
        title
      }
    `,
})
```

A wrapper component would use the fragment like so:

```js
import { createFragmentContainer, graphql } from "react-relay/compat"
import Article from "./article"

export default createFragmentContainer(Articles, {
   artist: graphql `
      fragment articles_artist on Article @relay(plural: true) {
          __id
          ...article_artist
      }
    `,
})
```

However, if we look at the code generated for the above file, you’ll notice that it wrongly assumes that the ‘article’ container is named `article`, instead of `Article`. This is, as outlined at the top, because the plugin assumes the container uses [the same case as the filename](https://github.com/facebook/relay/blob/ed5f4f9d3a575236f503778915dcbbf19c8e2440/packages/babel-plugin-relay/createClassicNode.js#L397) it’s defined in.

```js
var _compat = require("react-relay/compat");
var _article = require("./article");
var _article2 = _interopRequireDefault(_article);

(0, _compat.createFragmentContainer)(Articles, {
  articles: {
    classic: function classic() {
      var RelayQL_GENERATED = require("react-relay/classic").QL,
          article_artist = article.getFragment("artist");
      return {
        // ...
      };
    }
  }
});
```

This obviously leads to the following runtime exception:

<img src="https://user-images.githubusercontent.com/2320/27199799-9d436878-5217-11e7-8e4a-92a47d48643d.png" width="320" />

When the filename uses camel-case and the fragment is renamed to `Article_artist`, the generated code looks like expected:

```js
var _Article = require("./Article");
var _Article2 = _interopRequireDefault(_Article);

(0, _compat.createFragmentContainer)(Articles, {
    articles: {
        classic: function classic() {
            var RelayQL_GENERATED = require("react-relay/classic").QL,
                Article_artist = _Article2.default.getFragment("artist");
            return {
               // ...
            };
        }
    }
});
```

----

Questions:

* I _think_ this only applies to classic usage, but I haven’t been able to migrate far enough to know for sure. Is that the case?
* While I’m not entirely sure yet _how_ to change this and allow for our case, would you accept a patch for this or am I overlooking something and should we just rename our files to use camel-case?

**Comment by alloy** [comment]
We’ve actually decided to just rename our files to use camel-case, so this isn’t an issue for us anymore. I’ll leave it up to you to decide wether or not to close.

**Comment by leebyron** [comment]
Yeah, unfortunately this is part of the restriction of relay compat to support both environments. Once fully on modern, these restrictions are much much lighter.

**Comment by kassens** [comment]
I was thinking to update the `getModuleName` module to uppercase the first character, but wasn't fully convinced yet.

**Comment by BinaryMuse** [comment]
I would be happy to open a pull request to make the change @kassens suggests, but there is a test that specifically verifies that the first letter of the module name for lowercased filenames is also lowercased. Is this a change that is likely to be accepted?
