### ISSUE TITLE
custom type does not work in @argumentDefinitions

### ISSUE THREAD

**Issue by sibelius** [facebook/relay#1895]
I would like to define an argument of type DateFilter on my refetch container:

```graphql
@argumentDefinitions(
        date: {
          type: "DateFilter",
          defaultValue: {start: "", end: ""}
        }
      )
```

and I'm receiving the following error:

`BabelPluginRelay: Unsupported literal type `ObjectValue`.`

**Comment by sibelius** [comment]
@kassens is this supposed to work?

**Comment by matheuscorreia** [comment]
This was solved by updating to version 1.3.0

**Comment by sibelius** [comment]
Great

**Comment by salhotra** [comment]
@sibelius where and how did you define DateFormat type?

**Comment by josephsavona** [comment]
@salhotra The type has to be defined in your schema, since it's used as a field argument type it would be an InputObject type.

**Comment by sibelius** [comment]
```graphql
input DateFilter {
  """start date"""
  start: String!

  """end date"""
  end: String!
}
```

**Comment by salhotra** [comment]
Thank @sibelius
