### ISSUE TITLE
[relay-compiler] watchman should not be required when not using --watch

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#1900]
I am getting following error which make sense when I use `--watch` parameter, otherwise it should not depend on watchman, right? 

```
HINT: pass --watch to keep watching for changes.
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
```

**Comment by wincent** [comment]
Should not, but currently does. I think there might be an existing issue for this; let me see if I can find it.

**Comment by wincent** [comment]
Let's merge this into #1644. I'm going to retitle that one to make it clear that we prefer to fix the unnecessarily strict dependency rather than just document it.

Thanks for this @jardakotesovec!
