### ISSUE TITLE
[relay-compiler] duplicate fragment names should raise error

### ISSUE THREAD

**Issue by rosskevin** [facebook/relay#1902]
Now that we have converted to modern which forces a specific naming structure for all fragments, we have encountered some incompatibilities.  Namely, we had several complex react `Page` components with internal structures that were nearly identical i.e. `Card`, `View`, `Edit`.  We were able to succeed with relay compilation, all the while knowing we _should_ have fragment conflicts.  e.g. `Foo/Card Card_person` should raise an error upon parsing after `Bar/Card Card_person`.

We are now renaming Components to longer names (not really excited about that, but it's acceptable) and trying to get a clean compile.  Unfortunately, this means we need to manually check every query, because conflicts aren't reported.

**Comment by Rodeoclash** [comment]
Also related to https://github.com/facebook/relay/issues/1883

**Comment by leebyron** [comment]
Agreed.

#2020 introduces a fix for this (pending) and #2093 tracks a task to relax unique filenames.
