### ISSUE TITLE
Recommended way to extract actual ID of an object

### ISSUE THREAD

**Issue by boosh** [facebook/relay#191]
The IDs of some of my objects are significant. I need to make calls to an external calendar service passing the numeric ID of my Entry object as a parameter.

At the moment I'm base64 decoding the IDs from the server, and extracting the second element after splitting on colons to retrieve the actual, server-side ID of the object. I'm then creating a new component using the props for an Entry, but replacing the base64 encoded ID with this actual numeric one. After reading https://facebook.github.io/relay/docs/graphql-object-identification.html#content I guess I shouldn't do that. 

So what's the recommended way of storing the actual server ID on a returned item?

**Comment by fson** [comment]
@boosh The `id` field is required to be globally unique and base64 encoding is a way to signal the client that it should treat it as an opaque string, even if you encode more information in it on the server. Decoding it on the client breaks this encapsulation.

Maybe you could simply add another field in your Entry type (e.g. `entryId`) that returns the numeric ID you can use to make calls to the external service?

**Comment by amccloud** [comment]
@fson anyway to name relay's globally unique id `gid` and leave id as is?

**Comment by boosh** [comment]
There's already a __dataID__ attribute that contains the base64 encoded ID. I was assuming that relay was using that for caching, etc. Does it actually use the `id` field instead?

**Comment by fson** [comment]
@amccloud I don't think so. The `Node` interface has one field `id` and Relay expects it to be the unique ID that it can use to refetch the object using the `node(id)` root field. Do you have some scenario where just using some other field for the non-unique ID wouldn't work? If that's the case maybe you can make a wrapper for your component that renames the props passed to it?

@boosh As far as I know the `dataID` property is used to store the ID in the internal store of Relay. The public API Relay expects from the server is unique ID in the `id` field as defined in the [Object Identification spec](https://facebook.github.io/relay/docs/graphql-object-identification.html).

Also note that base64 encoding the ID is not mandatory. The only requirement for the `id` is that it's globally unique. But if your IDs are only unique within a single type, base64 encoding the type and that ID just happens to be a simple way to make them globally unique.

**Comment by boosh** [comment]
Hmm. I *could* add an extra field on the server, and I guess I'll have to in the short term if my fiddling with the `id` is a Bad Thing. But it introduces a mismatch between the client and server model, and is something that could be easily confused and go wrong. 

I expect this would be quite a common scenario so it'd be nice if the framework handled it natively instead of having to send a duplicate field for each type.

**Comment by boosh** [comment]
I'll just return an extra ID instead of fiddling with the `id` field.

**Comment by josephsavona** [comment]
@fson you're correct that `__dataID__` is for the internal ID of the record and should not be accessed by application code (following the usual convention that anything prefixed with an underscore is "private").

@boosh this issue was brought up and discussed in #75 - see there for why we haven't added support *yet*. For now, the solution of adding an extra field seems best.

Longer term, we would like to support type-specific IDs (that could then be transparent values), but this is not high priority for the core team. We'll file a public issue to document the changes required to make this work - it would be a great area to have some input from the community!

**Comment by josephsavona** [comment]
also, @fson, thanks for answering this!
