### ISSUE TITLE
[Modern] createFragmentContainer unable to detect fragment as variable

### ISSUE THREAD

**Issue by ryancole** [facebook/relay#1910]
I was trying to do something like ...

```
const fragment = graphql`
  fragment Foo on Bar {
    ..some stuff
  }
`;

export default createFragmentContainer(NavbarAuthAuthenticated, fragment);
```

but that seems to fail. The relay compiler doesn't seem to detect that it's a fragment. Everything works when that fragment is passed directly to the function, though.

It'd be nice for cleanliness to be able to put fragments in variables. Although, I understand that this involve the babel plugin and such so perhaps there's some limitation there.

**Comment by maikelrobier** [comment]
I have the same issue. These are related:
https://github.com/facebook/relay/issues/1698
https://github.com/facebook/relay/issues/1790

**Comment by leebyron** [comment]
Unfortunately this is just a tough problem. The relay compiler looks for specific patterns of javascript to understand how to operate, that means using the API in a predictable way.
