### ISSUE TITLE
[Documentation] "Edit This Page"-links are broken

### ISSUE THREAD

**Issue by nikolasburk** [facebook/relay#1916]
The footer of each page in the Relay Modern docs has a button that says `Edit This Page`. This page currently directs to `https://github.com/facebook/relay/blob/master/docs/<page-name>.md` when it should actually point to `https://github.com/facebook/relay/blob/master/docs/modern/<page-name>.md`.

**Comment by Igor-Senshov** [comment]
Links are also broken under Relay Compat.

**Comment by kassens** [comment]
I need to figure out how the website templating works to allow directories. Might not be too hard.
