### ISSUE TITLE
Incorrectly assumes type implements node when it has an ID attribute

### ISSUE THREAD

**Issue by julienp** [facebook/relay#1925]
For a schema as follows
```
type Notification implements Node {
  ...
  object: NotificationObject
  id: ID!
}

type NotificationObject {
  ...
  title: String
  id: ID!
}

type Me implements Node {
  notifications(...): NotificationConnection
}
```

NotificationObject.id is a pointer to some Node, but NotificationObject itself is not a Node.

When loading the `NotificationConnection`, it adds records to the store for each `NotificationObject`. Then when the actual node with the given ID is loaded, things blow up.

Arguably this isn't great schema design and the workaround to use something like is `objectID` or flatten NotificationObject into Notification is easy to implement, but it was somewhat unexpected this didn't work.

**Comment by kassens** [comment]
`id` is a reserved key. Anything that has an `id` will be stored in the flattened store using the `id` key and the `id` key should uniquely identify that object. The best fix would be to rename id on `NotificationObject` to something else.
