### ISSUE TITLE
[relay-compiler] should formatGeneratedModule be publicly exported

### ISSUE THREAD

**Issue by robrichard** [facebook/relay#1927]
I have built my own version of relay-compiler by copying and modifying `RelayCompilerBin` to work around the limitations with using fragments from node_modules (see https://github.com/facebook/relay/pull/1921). 

As of relay-compiler@1.1.0 `formatModule` option is required for `RelayFileWriter` and the default is to pass in `formatGeneratedModule`. If the intention is to allow people to build their own customized `relay-compiler`, should `formatGeneratedModule` be exported in `RelayCompilerPublic`?

**Comment by zth** [comment]
I'm also very interested in this. Due to current limitations of IntelliJ I need to make Relay Compiler output the Flow types without wrapping them in comments. I guess this would help with that too?

**Comment by kassens** [comment]
zth: Yes, you probably want to copy the code from `formatGeneratedModule` and make the change to the output.
