### ISSUE TITLE
[Modern] Getting 'Expected object to contain data for fragment...' error

### ISSUE THREAD

**Issue by blevine** [facebook/relay#1928]
Running react-relay version 1.1.0

My application includes a parent 'App' component and a child 'AllLunchesView' component that includes a PaginationContainer. The App component includes a QueryRenderer with a query defined like so:

```
const query = graphql`
      query AppAllLunchesViewQuery($afterCursor: String, $count: Int!) {
        lunchApi {
          allLunches(after: $afterCursor first: $count) @connection(key: "AllLunchesView_allLunches") {
            edges {
              node {
                forWeekOf
                name
                menus {
                  name
                  description
                }
              }
            }
            pageInfo {
              startCursor
              endCursor
              hasNextPage
              hasPreviousPage
            }
          }
        }
      }
    `;
```

Its render method renders the AllLunchesView like so:

```
return (<AllLunchesView allLunches={props.lunchApi} />);
```

And here is a snippet from AllLunchesView:

```
export default createPaginationContainer(
  AllLunchesView,
  {
    allLunches: graphql`fragment AllLunchesView_allLunches on Lunch_Api {
      allLunches(after: $afterCursor first: $count) @connection(key: "AllLunchesView_allLunches") {
        edges {
          node {
            forWeekOf
            name
            menus {
              name
              description
            }
          }
        }
        pageInfo {
          startCursor
          endCursor
          hasNextPage
          hasPreviousPage
        }
      }
    }`,
  },
...
,
    query: graphql`
      query AllLunchesViewQuery($afterCursor: String, $count: Int!) {
        lunchApi {
          ...AllLunchesView_allLunches
        }
      }
    `
```
This causes the warning:
```
Warning: RelayModernSelector: Expected object to contain data for fragment `AllLunchesView_allLunches`... Make sure that the parent operation/fragment included fragment `...AllLunchesView_allLunches`
```

I tried to rewrite the QueryRenderer query to use the AllLunchesView_allLunches fragment (in fact, this is the way I originally coded it) in which case the query appears to be executed correctly, however this.props.lunchApi.allLunches is not populated. this.props.lunchApi.allLunches is populated only if I write out the fully query replicating the contents of the fragment.

Not sure what I'm doing wrong here.

**Comment by blevine** [comment]
Looks like the problem I referred to in my previous comment (no data when the initial query contains the fragment defined in the PaginationContainer) may be the same problem mentioned in #1920. Although I reverted to react-relay 1.0.0 (maybe not correctly) and it didn't resolve the problem.

**Comment by pranaygp** [comment]
So, from the looks of it, it seems like you're passing down the `lunchApi` object from App to `AllLunchesView`, however, the query within AllLunchesView seems like it's acting on `allLunches`, and not `lunchApi`.
Also, you shouldn't have to rewrite the same query between the 2 components (you should be reusing the child fragment at the App level).

With that in mind, your new App query should be a lot simpler: 

```
query AppAllLunchesViewQuery($afterCursor: String, $count: Int!) {
  lunchApi {
    ...AllLunchesView_lunchApi
  }
}
```

The render method of the App will then probably look like

```
return (<AllLunchesView lunchApi={props.lunchApi} />);
```

And within `AllLunchesView`, you just need to update the prop name to be `lunchApi` instead of `allLunches` (since you're acting on Lunch_Api).

```
export default createPaginationContainer(
  AllLunchesView,
  {
    lunchApi: graphql`
      fragment AllLunchesView_lunchApi on Lunch_Api {
        allLunches(after: $afterCursor first: $count) @connection(key: "AllLunchesView_allLunches") {
          edges {
          ...

  ...
  query: graphql`
    query AllLunchesViewPaginationQuery($afterCursor: String, $count: Int!) {
      lunchApi {
        ...AllLunchesView_lunchApi
      }
    }
  `
  ...
```

Consequently, within `AllLunchesView`, you should be able to access `allLunches` as `props.lunchApi.allLunches`

**Comment by blevine** [comment]
Thank you @pranaygp, that worked.  Although I understand why your solution worked,   I don't understand why mine didn't. I should also point out that my original post had a typo. I was actually passing `props.lunchApi.allLunches` to the AllLunchesView component. This seemed more appropriate to me since the AllLunchesView should only know about a collection of lunches, not the the parent lunchApi. 

Interestingly, one thing that threw me was the fact that props.lunchApi.allLunches is not populated until the constructor of AllLunchesView.  In other words, when I debugged this, I put a breakpoint in the render() method of my App component. At that point, I can see props.lunchApi, but there is no props.lunchApi.allLunches. When I stop at the breakpoint in the AllLunchesView component, props.lunchApi.allLunches appears.

**Comment by pranaygp** [comment]
@blevine we hide data that components didn't request. This gives you a more predicatble structure of the data you receive in props and prevents you from trying to refer to data at a level that didn't require them. It makes it pretty easy to unknowingly break things without this.

In other words, each component only gets what it asked for

You can read more about that here: https://facebook.github.io/relay/docs/thinking-in-relay.html#data-masking :)

**Comment by blevine** [comment]
Thanks again @pranaygp. I guess I forgot to read that ;-)  My confusion stems from the  fact that this didn't seem very object-oriented to me. Why should a component that only knows about lunches be passed a parent (lunchApi) that happens to contain lunches as opposed to simply passing the lunches collection to it?  But having read that article, I now understand the thinking.  Thanks again for your help!  I'm going to close this issue.

**Comment by Khangeldy** [comment]
@pranaygp How about
 `query routesOrdesQuery {
  ...Orders_orders
}` root query fragment ? 
If it hides all data that don't need in this parent component. Soo how i get this data on createPaginationComponent ?

**Comment by steida** [comment]
Just ask them in query { foo, bla, ...SomeFragment }

**Comment by Khangeldy** [comment]
@steida Why then my code not work? 
routes.js
```
const ordersQuery = graphql`query routesOrdersQuery( $count: Int!, $after: String) {
  ...Orders_orders @arguments(count: $count, after: $after)
}`
...
<Route path="/orders" Component={Orders} query={ordersQuery} />
```

Orders.js
```
export default createPaginationContainer(
  Orders,
  {orders: 
    graphql`
      fragment Orders_orders on Query {
        orders(first: 10) @connection(key: "Orders_orders") {
          edges {
            node {
              ...Orders_order
            }
          }
        }
      }
    `},
  {
    direction: 'forward',
    getConnectionFromProps(props) {
      return props.orders && props.orders.orders
    },
    getFragmentVariables(prevVars, totalCount) {
      return {
        prevVars,
        totalCount
      }
    },
    getVariables(props, { count, after }, fragmentVariables) {
      return {
        count,
        after,
      }
    },
    query: graphql`
      query Orders_Query(
        $count: Int!
      ) {
        ...Orders_orders
      }
    `
  }
)
```

package.json
```{
    "found-relay": "^0.3.0-alpha.12",
    "react-relay": "^1.6.0",
}
```
With this i get `this.props.orders` null in `Orders` components . In the network tab i am see all my data that i request. But they lost somewhere in Orders Relay Connected Component.

**Comment by sibelius** [comment]
Try to have a fragment on QueryType instead

And then get this.props.query

**Comment by Khangeldy** [comment]
I Solve it. Just not use Component and use render method like in QueryRender. And it should consider loading, error state like this.
```javascript
render={({error, props}) => {
      if(error) {
         return <div>{error.message}</div>
      } else if(props) {
         return <Orders query={props} />
      } else {
         return <div>Loading...</div>
      }
}}
```
Otherwise not work.
