### ISSUE TITLE
Accessing variables in RelayContainer fragments

### ISSUE THREAD

**Issue by drabinowitz** [facebook/relay#193]
I would like to access variables in my fragments outside of the GraphQL fragments (specifically I would like to use a different fragment depending on the variables).  However, when I took a look at the passed in variables they are GraphQLCallVariables without an immediately apparent way for me to access their values.  I was wondering if Relay exposes a public method to get the values from these variables:

```javascript
game: variables => {
  if (variables.foo /*this is a GraphQLCallVariable*/) {
    return fooQL;
  } else {
    return barQL;
  }
}
```

**Comment by yungsters** [comment]
The `variables` is intentionally opaque. In fact, the function `variables => ...` is only ever executed once and memoized for subsequent access. This allows structural comparison of fragments without having to traverse the entire query tree.

**Comment by drabinowitz** [comment]
yup realized that after opening the ticket sorry about that, thanks for the response!
