### ISSUE TITLE
PageInfo startCursor and endCursor fields missing from documentation

### ISSUE THREAD

**Issue by sj26** [facebook/relay#1930]
Should the [Relay Cursor Connections Specification](https://github.com/facebook/relay/blob/master/website/graphql/Connections.md) include the `startCursor` and `endCursor` fields? They now seem to be required by Relay Modern's `PaginationContainer`.

**Comment by taha** [comment]
Any updates on this?

**Comment by merrywhether** [comment]
I believe the link for this is has been moved to https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo, and this appears to be the same as https://github.com/facebook/relay/issues/2457.

**Comment by jedwards1211** [comment]
I'm guessing that Relay switched to using `startCursor` and `endCursor` to save bandwidth, since most edge cursors would be wasted bits.  So I definitely think it was a wise change and should be added to the spec.
