### ISSUE TITLE
[Modern] Compiler injects ID property even when not requested

### ISSUE THREAD

**Issue by nevir** [facebook/relay#1939]
I have a few types in a schema where: 

* They can be naturally identified from their properties.
* We've attached IDs to them for database purposes, and expose that ID via GraphQL for debugging purposes.
* The IDs are not useful in day to day use of our client application.

We also have some other cases where it's just not useful (to the client application) to select IDs - either the nodes are immutable, or can be identified from their context

For example:

```graphql
type ExperimentAssignment {
  id: ID
  name: String
  treatment: String
  version: Float
}
```

And say I select it via some query

```graphql
query foo {
  experimentAssignments {
  name
  treatment
  version
  }
}
```

Annoyingly, when running `relay-compiler` against it, the compiler inserts an `id` field into the compiled query:

```json
…
{
  "kind": "LinkedField",
  "alias": null,
  "args": null,
  "concreteType": "ExperimentAssignment",
  "name": "experimentAssignments",
  "plural": true,
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "treatment",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "version",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    }
  ],
  "storageKey": null
},
…
```

---

Changing the type of the `id` field from `ID` to `String` works around it

**Comment by nevir** [comment]
At second glance – is this on purpose?  It does enable querying subsets of nodes, while still being able to guarantee that the returned node is the same one that's already cached (or updating the cache to point to a new one)

**Comment by kassens** [comment]
This is on purpose as relay uses the `id` field to normlize objects into it's in memory store. This is useful in case the same object is returned from different queries to update the existing objects.
