### ISSUE TITLE
Q: Passing props through RootContainer?

### ISSUE THREAD

**Issue by amccloud** [facebook/relay#194]
Any reason RootContainer is opaque when it comes to props? I'm trying to configure react-native's Navigator component to work with relay. I've gotten it to successfully work, but any components rendered into RootContainer do not have access to the navigator prop.

#### Navigator.renderScene

```javascript
import {RootContainer} from 'react-relay';

export default function routeMapper(route, navigator) {
  var props = {
    Component: route.component,
    route: route,
    navigator: navigator
  };

  return (
    <RootContainer {...props} />
  );
}
```

#### Example route

```javascript
const route = {
  name: 'root',
  component: RootController,
  params: {},
  queries: {
    viewer: (Component) => Relay.QL`
      query {
        viewer {
          ${Component.getFragment('viewer')},
        }
      }
    `
  }
};
```

**Comment by josephsavona** [comment]
@amccloud This is intentional - `Relay.RootContainer` does not pass through props. However, you can customize the props passed to the component via the [`renderFetched()` prop](https://facebook.github.io/relay/docs/guides-root-container.html#renderfetched). In this example, you might do:

```javascript
<RootContainer
  renderFetched={data => 
    <Component {...props} navigator={navigator} />
  } />
```

**Comment by amccloud** [comment]
I see, thanks!

**Comment by ssomnoremac** [comment]
<RootContainer
      renderFetched={data => 
        <Component {...data} passedProps={this.props} />
    } />

worked for me to pass between scenes using `react-native-router-flux`
