### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by didierfranc** [facebook/relay#1946]
It seems react-realy doesn't support IE11 out of the box

### Issue

<img width="480" alt="screen shot 2017-07-07 at 10 38 21" src="https://user-images.githubusercontent.com/14132464/27950136-73d780e2-6300-11e7-8865-a0f909561937.png">

<img width="385" alt="screen shot 2017-07-07 at 10 43 34" src="https://user-images.githubusercontent.com/14132464/27950349-3c17c06c-6301-11e7-9650-56b73a65794f.png">

### Solution

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Polyfill) suggest this polyfill maybe this should be added to the source code of react-relay
```js
if (!String.prototype.startsWith) {
  String.prototype.startsWith = function (searchString, position) {
      position = position || 0;
      return this.substr(position, searchString.length) === searchString;
  };
}
```

**Comment by sibelius** [comment]
You should polyfill what you need for your environment

**Comment by didierfranc** [comment]
Yes it's easy to solve it 

With some **String** method polyfill or a simple :
```html
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
```

I just wanted to know what was the ootb browser support of relay I can't find it

**Comment by kassens** [comment]
Relay requires polyfills as others mentioned here.
