### ISSUE TITLE
ERROR: invalid field list: unknown field name 'content.sha1hex'

### ISSUE THREAD

**Issue by softronic** [facebook/relay#1947]
I tried cloning relay-repo and build it. No problems in general and tests run o.k. 

But when I try to use with my project the relay-compiler I get:

ERROR: invalid field list: unknown field name 'content.sha1hex'

I have tried to find a reference how to get around this but so far unsuccessfully.

**Comment by kassens** [comment]
Thanks, I'll take a look. This might be a new watchman option we're using.

**Comment by kassens** [comment]
We'll need to find a solution for this. `content.sha1hex` is a fairly new feature and not in an official release yet. We need to somehow detect if it's supported or have 2 implementations of the file finder.

**Comment by kassens** [comment]
Feel free to try this out again. Hope it's fixed now.
