### ISSUE TITLE
Release process similar to React Native

### ISSUE THREAD

**Issue by gyzerok** [facebook/relay#195]
subj

**Comment by yungsters** [comment]
Can you elaborate on what you think we can adopt from the React Native release process?

**Comment by gyzerok** [comment]
@yungsters I'm talking about their every two weeks stable release. It seems like with this in mind they are able to move forward faster than other FB projects. Another good example is iojs.

**Comment by vjeux** [comment]
@gyzerok: React Native is a bit special in a sense that it has a gigantic API surface, so doing feature releases would be very hard as many individuals need to figure out when is a good time to ship their feature. React and Relay are different as they have a very small API surface. So it is manageable to proper releases and for each of them have a much higher quality upgrade path, release notes...

**Comment by kassens** [comment]
We're currently in a pretty early phase and plan on releasing the latest version to npm every Friday. We'll revisit the release schedule when we see this not working out.
