### ISSUE TITLE
[Modern] Expected type `PageInfo!` to have an endCursor field

### ISSUE THREAD

**Issue by macs91** [facebook/relay#1958]
I'm working with Relay Modern to fetch data from Shopify new [Storefront API](https://help.shopify.com/api/storefront-api) that seems to conform to Relay spec as defined here: https://facebook.github.io/relay/graphql/connections.htm

But when I try to use a pagination container I get the following error:

`Invariant Violation: RelayConnectionTransform: Expected type 'PageInfo!' to have an endCursor field`

Relay appears to require and `endCursor` field which I think is not currently in the specs. Of course I don't have control on Shopify servers to change the `PageInfo` schema, so what should I do?

> Note: My goal here is to implement a load more feature

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

If you're still having issues, please feel free to reopen it with an update.

**Comment by merrywhether** [comment]
I've also run into this issue (my company's API doesn't currently have startCursor/endCursor partly because they are not mandatory in the spec). It seems like I should be able to manually provide the cursor of the last node in the getVariables function to get around this.

**Comment by macs91** [comment]
@merrywhether I've switched to Apollo to get around this.. If you found a working solution for this it would be awesome if you could share the details 👍

**Comment by httpsOmkar** [comment]
I was able to work around with this transformer. Once I get data from the server. I call this function and transform the data.

```ts
export function inputJSON(json) {
  return fix(json);
}

const fix = obj => {
  if (typeof obj !== 'object' || obj === null) {
    return obj;
  }
  if (obj.pageInfo && obj.edges.length) {
    obj['pageInfo'].endCursor = obj.edges[obj.edges.length - 1].cursor;
  }

  Object.keys(obj).forEach(key => {
    if (typeof obj[key] === 'object' && Array.isArray(obj[key])) {
      obj[key].forEach(e => fix(e));
    } else if (typeof obj[key] === 'object') {
      fix(obj[key]);
    }
  });

  return obj;
};

```

And modifing query with this `QUERY_TEXT.split('endCursor').join('')`

And modifying the schema manually for now.
