### ISSUE TITLE
Relay website shows documentation for unreleased features

### ISSUE THREAD

**Issue by sgwilym** [facebook/relay#1961]
Was really stumped as to what I was doing wrong here:

```
this.props.relay.refetchConnection(5, null, {orderBy: newOrder});
```

But then I saw issue #1954, written by someone who had a similar problem. After looking in `node_modules/react-relay/lib/ReactRelayPaginationContainer`, I can see that the definition for `this._refetchConnection` doesn't even take a third parameter, which is not what the API or source seems to think at all.

So it looks like there's no way to change variables on paginationContainers with the current distribution.

**Comment by sgwilym** [comment]
Okay, I realise now that this is simply a new feature that hasn't been released yet.

Nonetheless, it is _very_ confusing to see documentation on the official Relay docs site referring to unreleased features.

**Comment by kassens** [comment]
Sorry about this. Typically we update the website after a release, not sure why the documentation was pushed before the NPM release.
