### ISSUE TITLE
[Modern] mutation API: settings an array of scalars

### ISSUE THREAD

**Issue by mattkrick** [facebook/relay#1963]
in a mutator updater, if the server response is: `{foo: {bar: [1,2,3]}}` I can get at it via `store.getRootField('foo').getValue('bar')`.
however, if I try to `foo.setValue([1,2,3], 'bar')` I get an error telling me it's not scalar. Feels a little asymmetric that you can't call `setValue` with the thing that you got from calling `getValue`. Is there another way to do this? Should I make a PR for `setValue` to check if it's scalar or an array of scalars?

**Comment by mattkrick** [comment]
Any thoughts on how to accomplish this?
Alternatively I could add a `setValues` method to the API.

**Comment by juhaelee** [comment]
I would also like to know how to set the value for an array of scalars. Is this currently possible with the existing api?

**Comment by omerzach** [comment]
This seems like a bug

**Comment by kassens** [comment]
7a2b27ea0e93d37857358707f40a2ededef0cfdc released with 1.3.0  should've solved this. Please let me know if that's not the case.

**Comment by saudpunjwani101** [comment]
I'm doing a mutation of array of items, and my response from server is,
   {  
    shopItem: 
   { addedItems:
   [ 
      { node: 
        { id: 'SXRlbToy', 
          name: 'Milk Pack Full Pack', 
          price: 321 
        }
       } 
     ]
   }
  }

I'm doing   const payload = store.getRootField('shopItem').getValue('addedItems');
it gives me error RelayModernRecord.getValue() expected a scalar value but found plural linked records. Need help

**Comment by willyyang** [comment]
the change in `1.3.0` did not fix this issue. I am having the same problem where I call 

`let rec = proxyStore.getRoot().getLinkedRecord('...').getValue('abc')` then set `rec.setValue([1,2,3], 'abc')`

 I get `Uncaught Error: RelayRecordProxy#setValue(): Expected a scalar or array of scalars,`
