### ISSUE TITLE
[Modern] Parent component pass variables to child fragment

### ISSUE THREAD

**Issue by ericsin112** [facebook/relay#1964]
In Relay Classic, I can do something like `${childComponent.getFragment('viewer', {lang: 'en'}}` to pass variables to child fragment. But in Relay Modern, how can I do that?

**Comment by maikelrobier** [comment]
@ericsin112 you can do it using `@arguments` and `@argumentDefinitions` directives, I had the same question in SO: https://stackoverflow.com/questions/44753480/pass-variables-to-fragment-container-in-relay-modern

**Comment by ericsin112** [comment]
@maikelrobier It works. Thanks. But I want to know can I declare the value on parent fragment.

Now:
In Parent Component:
`...childComponent @argument(lang: $lang)`
In Query:
`query xxxQuery ($lang: String!) {
  viewer{
    ...parentComponent
  }
}`
In Router use prepareVariables to declare `$land: 'en'`

Can I do something like this:
In Parent Component:
`...childComponent @argument(lang: 'en')`

**Comment by maikelrobier** [comment]
I haven't tried router integration with Relay Modern yet, but you can do that `...childComponent @argument(lang: "en")`. Note that it can't be single quotes, that would end up with a GraphQL parsing error. You could also try `defaultValue` if that helps. The only path that I have explored so far for passing javascript values as fragment variables is through the `variables` prop in `QueryRenderer`.

**Comment by ericsin112** [comment]
I have tired `...childComponent @argument(lang: "en")`, but it returned an error `RelayParser: All @arguments() args must be variables, got StringValue`. Seems that the only way is passing values through the `variables` prop in QueryRenderer or in router.

**Comment by yo34** [comment]
Hello,

    I have exactly the same probleme. I made a ticket in the todo modern example. 
The documentation of the Refecth Container explains how to code this container but not how to set variable in a parent Fragment Container (exept from the QueryRenderer).

Could someone update this documentation https://facebook.github.io/relay/docs/refetch-container.html to show how setting variable from a parent fragment container for example after a user interaction ? 

Thank you.

**Comment by albertstill** [comment]
@ericsin112 the consuming fragment above can use `@argumentDefinitions` again to stop the `@arguments() args must be variables` error.

```graphql
fragment foobar_foobar on Foo @argumentDefinitions(
  lang: {type: "String", defaultValue: "en"},
) {
  ...childComponent @arguments(lang: $lang)
}
```

This gives you the added ability to override the "en" should you wish.

**Comment by jstejada** [comment]
Right! You can do what @albertstill suggested, or inside parentComponent you should also be able to reference the `$lang` variable defined in the root query.

@ericsin112 @yo34 we've recently updated our docs for fragment and refetch containers and added docs on how to use `@arguments`. Going to close this for now but let us know if you have other questions!
