### ISSUE TITLE
[relay-compiler] --exclude does not work

### ISSUE THREAD

**Issue by steida** [facebook/relay#1977]
Or I am dumb. In https://github.com/zeit/next.js, we have root flat directories and .next dir.

I have to delete .next dir, because --exclude seems not to work.

`"relay": "# Delete .next dir because relay-compiler --exclude does not work.\nrimraf .next && relay-compiler --src ./ --schema data/schema.graphql",`

**Comment by robrichard** [comment]
Which version of `relay-compiler` are you using? `--exclude` was merged to master recently but was not included in a release yet (will be in [1.2.0](https://github.com/facebook/relay/pull/1976))

**Comment by steida** [comment]
npm 😂
