### ISSUE TITLE
[Relay-compiler] non-null and nullable types should not be conflicting

### ISSUE THREAD

**Issue by hannesj** [facebook/relay#1981]
I got the following error ```Invariant Violation: RelayParser: Variable `$route` was used in locations expecting the conflicting types `String` and `String!`. Source: document `RouteMarkerPopup_trip``` from relay-compiler.

The fragment is below, and includes the variable $route in both parameters where null is tolerated,and not tolerated.

```
    fragment RouteMarkerPopup_trip on Query {
      fuzzyTrip(
        route: $route
        direction: $direction
        time: $time
        date: $date
      ) {
        gtfsId
        pattern {
          code
          headsign
          stops {
            name
          }
        }
      }
      route(id: $route) {
        gtfsId
        mode
        shortName
        longName
      }
    }
```

**Comment by mprobus** [comment]
I've run into the same problem, with "ID" and "ID!" types, in a nearly identical use-case in which a record "ID" is used as an optional filter in a subfragment, and the "ID!" is used to get a specific node.  Anyone have a workaround suggestion?

**Comment by sibelius** [comment]
Use ID! and pass a null value

**Comment by mprobus** [comment]
Looking at relay-compiler's _recordVariableReference and graphql/utilities/typeComparators, the order in which the variable types occur is significant.  If the first occurrence of a variable is of type non-null, a following use of it as a nullable will pass.  In short, what seems to work for me is the equivalent of moving the route(id: $route) block above the fuzzyTrip block.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

If you're still having issues, it would be great to see a failing pull request. Or if you have more to share, please feel free to reopen it with an update.
