### ISSUE TITLE
commitMutation should return Promise

### ISSUE THREAD

**Issue by steida** [facebook/relay#1987]
Because onCompleted and onError.

**Comment by sibelius** [comment]
you can't cancel promises yet

**Comment by steida** [comment]
Or observer, whatever is better than callbacks.

**Comment by sibelius** [comment]
it is easy to wrap the current implementation in promises or observers, I don't think they wanna this on core

check this https://github.com/robrichard/relay-commit-mutation-promise

**Comment by steida** [comment]
Thank you!
