### ISSUE TITLE
Warning: commitRelayModernMutatuion: Expected `optimisticResponse` to be an object, received a function.

### ISSUE THREAD

**Issue by moolo** [facebook/relay#1988]
Warning: commitRelayModernMutatuion: Expected `optimisticResponse` to be an object, received a function.

**Comment by jalalat** [comment]
Use it like this:
optimisticResponse: getOptimisticResponse()

rather than:
optimisticResponse: () => getOptimisticResponse()

**Comment by DaveyEdwards** [comment]
@jalalat thank you!  And for everyone else that might might not scroll down all the way and have less js knowledge then they thought they did.

It is in the commitMutation, NOT the  getOptimisticResponse function itself

```js
function commit(
	environment: Environment,
	data: Object,
	viewerId: number,
) {
	commitMutation(
		environment,
		{
			mutation,
			variables: { input: data },
			optimisticResponse: getOptimisticResponse(data, viewerId), // This is the line you change
			configs: getConfigs(viewerId),
		},
	);
}
```
