### ISSUE TITLE
[relay-compiler] [documentation] Consider providing an example on extending/modifying relay-compiler output

### ISSUE THREAD

**Issue by antmdvs** [facebook/relay#1997]
I understand there are extensibility points for modifying the relay-compiler output (https://facebook.github.io/relay/docs/relay-compiler.html#advanced-usage). I'd like to explore creating TypeScript definitions instead of Flow type, but I'm having a hard time finding good (any) resources on how to get started. The link references RelayCompilerPublic.js, but I'm not sure where to go from there.

Any guidance would be appreciated. Thanks.

**Comment by leebyron** [comment]
I'm sorry this issue has sat here for so long. In an attempt to clean up our issue queue we're closing some aging or unclear-action issues.

I hope you'll be able to look at our architecture diagrams and documentation to assist you. If you're willing to share back your learnings in the form of documentation, I'm sure many would appreciate it!
