### ISSUE TITLE
[relay-compiler] watchman is required even if watch option is not passed

### ISSUE THREAD

**Issue by bitriddler** [facebook/relay#2001]
I'm ignoring all relay generated files `components/**/__generated__` in `.gitignore`.
Now when I try to deploy to heroku I need to run `relay-compiler` which requires `watchman` to be installed. Is there a way to ignore it so I dont need to install on heroku?

**Comment by sibelius** [comment]
this https://github.com/facebook/relay/pull/1966 is almost done

**Comment by bitriddler** [comment]
@sibelius great! thanks
