### ISSUE TITLE
[modern] prepareVariables equivalent on createFragmentContainer

### ISSUE THREAD

**Issue by sibelius** [facebook/relay#2003]
in classic I have this:

```jsx
export default Relay.createContainer(CommercialStructureChildrenFilterModal, {
  initialVariables: {
    id: null,
    type: null,
    isValid: false,
  },
  prepareVariables: prevVariables => ({
    ...prevVariables,
    isValid: prevVariables.id !== null && prevVariables.type !== null,
  }),
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
       list(id: $id, typeNumber: $type) @include(if: $isValid) {
          children(first: 100) {
            edges {
              node {
                id
                _id
                name
              }
            }
          }
        }
      }
    `,
  },
});
```

I use `prepareVariables` to transform id and type into a boolean

how can I do the same in relay modern/compat using createFragmentContainer?

**Comment by staylor** [comment]
`$idValid` needs to become a variable on the query itself:

```graphql
query ViewerQuery($isValid: Boolean) {
    ...CommercialStructureChildrenFilterModal_viewer
}
```

`isValid` will have to be set when you are passing your variables into whatever is executing the query. If the query gets refetched over time, you have access to your previous variables when setting up your Refetch Container: https://facebook.github.io/relay/docs/refetch-container.html

**Comment by sibelius** [comment]
that's correct, tks
