### ISSUE TITLE
[relay-compiler] Compiler SyntaxError with Typescript non-null operator

### ISSUE THREAD

**Issue by Razinsky** [facebook/relay#2004]
relay-compiler doesn't seem to like the non-null operator (`!`) in Typescript code even when it is not related to Relay-related variables e.g. `viewer`.

I get `Parse error: SyntaxError: Unexpected token, expected ; (94:32) in "public/components/pages/browse/Results/index.tsx"` everywhere I enforce a  non-null variable.

Right now I must remove all `!` first, then compile Relay, add the `!` back and run my compilation script.

Using version `1.2.0-rc.1`

**Comment by leebyron** [comment]
Unfortunately the relay compiler does not parse typescript files, since it relies on the babel toolchain.
