### ISSUE TITLE
[classic] Error when upgrading to React v16 beta

### ISSUE THREAD

**Issue by AnderssonChristian** [facebook/relay#2009]
#I've been using Relay Classic on my project since last year and haven't gotten around to migrating to Relay Modern yet. Yesterday I tried updating React from version 15.6.1 to 16.0.0-beta.2 by simply doing `yarn add react@next react-dom@next` but this causes the following error to be logged in the console:

    Uncaught TypeError: Cannot read property 'shape' of undefined

Here's the full output:

![skarmavbild 2017-08-02 kl 09 53 46](https://user-images.githubusercontent.com/12988898/28863264-86b22254-7768-11e7-8e1e-4b7321ef1ff7.png)

Am I missing something? How can I fix this? Thank you.

**Comment by sgwilym** [comment]
Looks like react-relay still uses React's built in prop types module (deprecated in React 16) instead of using the new separate `prop-types` package.

**Comment by leebyron** [comment]
Fixed as of the latest release

**Comment by felipellrocha** [comment]
@leebyron Which version is that exactly?

**Comment by AnderssonChristian** [comment]
Can confirm that this has been resolved on my end as well. Thanks.
