### ISSUE TITLE
[modern] RefetchContainer refetch function swallows errors.

### ISSUE THREAD

**Issue by henryqdineen** [facebook/relay#2011]
if a `callback` isn't provided to `refetch` it should re-throw the error.

**Comment by sibelius** [comment]
I don't think so

**Comment by leebyron** [comment]
Please test this out:

```js
const {Observable} = require('relay-runtime');
Observable.onUnhandledError(error => {
  console.error(error);
});
```

In development builds, these uncaught errors will be rethrown. Please make sure you're on the latest version when trying this out!
