### ISSUE TITLE
[Modern] When using RANGE_DELETE and specifying more than one connection key, only the first is matched

### ISSUE THREAD

**Issue by tberman** [facebook/relay#2012]
This looks like a misplaced call to `break` at https://github.com/facebook/relay/blob/master/packages/relay-runtime/mutations/setRelayModernMutationConfigs.js#L292 but I am having a hard time creating a test case that proves it.

I would expect it to look at every connection key I am passing in and removing the node from all of them, not just the first one it finds.

**Comment by ivosabev** [comment]
test

**Comment by kirkbross** [comment]
Comment

**Comment by helios1989** [comment]
test

**Comment by sibelius** [comment]
Use new mutations directives instead
