### ISSUE TITLE
Support for babel-plugin-relay on create-react-app without ejecting

### ISSUE THREAD

**Issue by renatonmendes** [facebook/relay#2018]
In my opinion, does not seen reasonable to eject a `create-react-app` to support `babel-plugin-relay` as they are all interrelated projects. You need to do so if you want to use Relay Modern.

Is there a way to use `babel-plugin-relay` with `create-react-app` without ejecting ? Wouldn´t it make sense to support it ?

**Comment by amkoehler** [comment]
An eject was still needed with relay-classic, right? It was a different babel plugin but the same problem if I remember correctly. This sounds like a create-react-app limitation more than a relay limitation.

**Comment by renatonmendes** [comment]
Yes. This is a create-react-app problem, but they are both facebook, right  ? I think a request from someone from relay project would put this issue on priority. It´s just some lines of coding at create-react-app, but it´s a messy to use relay with create-react-app if not supported.

**Comment by leebyron** [comment]
This is not something our team will be able to get to, however we would be happy to review a pull request for anyone who would like to investigate a fix for this

**Comment by josephsavona** [comment]
This is implemented: https://create-react-app.dev/docs/adding-relay/
