### ISSUE TITLE
graphql: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `graphql`.

### ISSUE THREAD

**Issue by satishrao84** [facebook/relay#2025]
Hello,
I am getting started on Relay Modern and my learner app has run into an issue with an graphql error. 

    import React, { Component } from 'react'
    import {
      createFragmentContainer,
      graphql
    } from 'react-relay'

    class Link extends Component {

     render() {
        return (
         <div>
          <div>{this.props.link.description} ({this.props.link.url})</div>
      </div>
    )
    }
  
     _voteForLink = async () => {
    // ... you'll implement this in chapter 6  
     }

    }

    export default createFragmentContainer(Link, graphql`fragment Link_link on Link {
    id 
    description 
    url
    }
    `)

I run the relay-compile by ./node_modules/relay-compiler/bin/relay-compiler --src ./src --schema ./schema.graphql 
It generates the LinkListPageQuery.graphql.js	LinkList_viewer.graphql.js	Link_link.graphql.js in the __generated__ folder. 
However, when I start the app, I get the graphql: **Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `graphql`.** error on Link.js

I don't have .babelrc file configured. 

Could someone please help me out here? Would it help if I posted my learner app (basically following instructions in howtographql.com) up on GitHub? Thanks !

**Comment by satishrao84** [comment]
This was an error on my part. I did not perform a yarn eject to disassociate the create-react-app from the application and allow the babel configurations to be done. 
Will close it now.

**Comment by idkjs** [comment]
Dont have to eject. See https://hackernoon.com/using-create-react-app-with-relay-modern-989c078fa892.
