### ISSUE TITLE
I cannot create a connection in relay & graphql schema?

### ISSUE THREAD

**Issue by iamglenbacs** [facebook/relay#2026]
I am trying to create a pagination in relay & graphql in my schema. This is my code:

const GraphQLFriendByUser = new GraphQLObjectType({
  name: 'FriendByUser',
  fields: {
    id: globalIdField('FriendByUser'),
    _id: {
      type: GraphQLString,
      resolve: (root) => root._id,
    },
    email: {
      type: GraphQLBoolean,
      resolve: (root) => root.email,
    },
    fullName: {
      type: GraphQLString,
      resolve: (root) => {
        return root.fullName;
      },
    },
  },
  interfaces: [nodeInterface],
});

const {
  connectionType: FriendsByUserConnection,
  edgeType: GraphQLFriendByUserEdge,
} = connectionDefinitions({
  name: 'FriendByUser',
  nodeType: GraphQLFriendByUser,
});
I created this similarly looking at sample in todo-modern, In my TodoListHome component, this is my graphql query:

friendsByUserContext( first: 200 ) @connection(key: "TodoListHome_friendsByUserContext") {
      id
      _id
      fullName
      email
    }  
there's no problem when I update the schema, but when I try to build, this is my error:

Invariant Violation: RelayParser: Unknown field id on type  FriendByUserConnection. Source: document TodoListHome_viewer file:  C:\Users\PE60\Desktop\socialnetworking-todoapp\js\components\TodoListHome.js.

**Comment by Gregoor** [comment]
https://github.com/facebook/relay/blob/master/CONTRIBUTING.md#questions-regarding-how-to-use-relay-andor-graphql
