### ISSUE TITLE
Update schema.json why this error occurred

### ISSUE THREAD

**Issue by TongDaDa** [facebook/relay#2029]
hello !

What is the reason for this error? I just updated the schema.json

![2017-08-11 11 29 41](https://user-images.githubusercontent.com/23241188/29200557-f202c050-7e88-11e7-969b-05dca6a1af2f.png)

**Comment by kassens** [comment]
This seems to be an issue in the schema definition on your server. If this is still an issue please look into your server implementation and then open an issue on https://github.com/graphql/graphql-js
