### ISSUE TITLE
is relay modern, like angular2, a lot of downsides

### ISSUE THREAD

**Issue by webmobiles** [facebook/relay#2031]
I've started reading a book about relay "Learning Graphql and Relay", in the middle of book the code does not work, i've tried to follow blog and stackoverflow, everything changed, so i was trying update, but Relay was updated since book was written, and  a new version called relay modern exist and the imports is very confused for old relay, updated relay and modern relay, and for projects migrated to relay modern: 4 scenarios.
Documentation on site teach you old relay,  very poor documentation, no starters (just for old version ), very few pages about relay modern on the official site:

https://facebook.github.io/relay/docs/relay-modern.html

finally i've get lost with a simple code to show "quotes', all this   remind me work with a product highly unstable and all the mistakes like angular2, with a lot of versions and way to do the things and keep changing.

I'm afraid about the path that relay is taking. any ideas? anyone with this problem?

or must forget relay and learn apollo, it's seems more stable...

**Comment by unirey** [comment]
@webmobiles 

I wouldn't call it unstable. Yes, there was a major rewrite but myself & probably others too who kept up w/ Relay, knew & were waiting for it looong time (> year I think): new awesome features & less magical API.

Keep in mind that FB also uses Relay in production & I don't think they enjoy too many breaking changes.

---

There's a clear documentation section for [RELAY MODERN](https://facebook.github.io/relay/docs/relay-modern.html) & even [RELAY COMPAT](https://facebook.github.io/relay/docs/relay-compat.html) in case your app(s) already use Relay Classic: haven't used it but it seems to provide a simple upgrade path to Modern. 

I personally prefer videos to books, e.g [this playlist](https://www.youtube.com/watch?v=9_pIJAnpJQM&list=PLn2e1F9Rfr6l1OVXPV0QEdrP_5Abt4vI3) seems to be very helpful for beginners.

---

I like Relay, only 2 things that are currently missing for my personal taste: local schema & id generation for persisted queries. [Missing part of oss compiler binary](https://github.com/facebook/relay/issues/1656#issuecomment-304857498) seems to hold back local schema & Im not even sure what's holding back id generation for persisted queries - [not sure how to require user's custom persist code](https://github.com/facebook/relay/pull/1846/files)?

But both are in features list, I hope we'll see them soon.

**Comment by johntran** [comment]
https://hackernoon.com/using-create-react-app-with-relay-modern-989c078fa892

You would probably have more luck following this tutorial :)

**Comment by kassens** [comment]
Thanks for the feedback, we know we have more work we can do on the documentation and welcome any help in form of PRs. Closing this as a bit too broad.
