### ISSUE TITLE
Question on graphQL design

### ISSUE THREAD

**Issue by satishrao84** [facebook/relay#2041]
Hello,
I have a json structure like the below stored in mongo

```
    {
      application_name:"...",
      buckets: [
        ....
        ....
       ] }

```
Every application has multiple buckets.

FOr the nodes - edges pattern, I was planning for the buckets to be the nodes as below

```
let applicationType = new GraphQLObjectType({
    name : 'Application',
    fields : () => ({
        id : globalIdField("Application"),
        app_name:{type:GraphQLString},
        buckets:{
            type : bucketConnection,
            args: connectionArgs,

        },
        resolve:(_,args) => {
                return connectionFromPromisedArray(
                    db.collection("buckets").find({}).toArray(),
                                        args
                );
        
        }
    }),
    interfaces:[nodeInterface]
})


const { connectionType: bucketConnection } = 
    connectionDefinitions({ name: 'Bucket', nodeType: bucketType });


const Query = new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
        node: nodeField,
        application: {
            type: applicationType,
            resolve: () => getApplication(),
        },

    }),
});
const schema = new GraphQLSchema({
    query: Query,
});
```
My questions were 
a) Is this a right approach?
b) getting an error as below 

> Error: Application.resolve field config must be an object
>     at invariant (/Users/sanupin/CouchbaseDashboard/node_modules/graphql/jsutils/invariant.js:19:11)
>     at /Users/sanupin/CouchbaseDashboard/node_modules/graphql/type/definition.js:360:56
>     at Array.forEach (native)
>     at defineFieldMap (/Users/sanupin/CouchbaseDashboard/node_modules/graphql/type/definition.js:357:14)
>     at GraphQLObjectType.getFields (/Users/sanupin/CouchbaseDashboard/node_modules/graphql/type/definition.js:311:44)
>     at typeMapReducer (/Users/sanupin/CouchbaseDashboard/node_modules/graphql/type/schema.js:209:25)
>     at /Users/sanupin/CouchbaseDashboard/node_modules/graphql/type/schema.js:219:20
>     at Array.forEach (native)
>     at typeMapReducer (/Users/sanupin/CouchbaseDashboard/node_modules/graphql/type/schema.js:210:27)
>     at Array.reduce (native)
>

**Comment by w01fgang** [comment]
Your `resolve` is a field name, so your type doesn't contain `resolve` field. You have defined only `name `, `fields ` and `interfaces `.

**Comment by sibelius** [comment]
this is most suited to StackOverflow

**Comment by leebyron** [comment]
Please direct questions like these to StackOverflow, so we can keep this forum high signal for bugs and feature discussion for Relay
