### ISSUE TITLE
Add capability to send multiple mutations in one request

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#205]
GraphQL make possible to post multiple mutation tasks in one request - is possible to do that with Relay?

**Comment by clentfort** [comment]
Looking at [`sendMutation`](https://github.com/facebook/relay/blob/master/src/network-layer/default/RelayDefaultNetworkLayer.js#L49-L67) in the default network layer I would say no, not possible. It only ever sends one mutation at a time.
Maybe if you explain why you want to send multiple mutations at once either a suggestion on how to improve your design can be made, or it can serve as an example for when multiple mutations are useful.

**Comment by jardakotesovec** [comment]
Lets say that I have context menu when I can change many things about the image: its metadata, tags and groups.  I like the idea of having several simple mutations with clear purpose rather than having one `updateImage' mutation which does everything based on args.

I understand that I could trigger several mutations via separate requests, but its not optimal - it causes more data to send/receive and possibly more re-renders. 

GraphQL support that..  I would think that there was some flexibility reason for it.

But also I can imagine that things can get complicated to handle that..  and they are pretty complicated already..  so also depends on complexity that it would bring...

**Comment by yungsters** [comment]
Relay does not currently support sending multiple mutations for a single request, but there isn't any reason we can't add support for it.

**Comment by josephsavona** [comment]
This is definitely a nice to have, but we haven't seen strong demand for this feature. I'm going to close it due to inactivity, but feel free to comment here and we can reopen.

**Comment by jwaldrip** [comment]
We would love to see this too.

**Comment by kareem3d** [comment]
so I cant do a mutation like this ?
```
setViewer
createProduct
```
That really hurts :(

**Comment by wincent** [comment]
@kareem3d: What would `setViewer` do? (And specifically, what would it do that couldn't be achieved by adding another argument to the input to `createProduct`?) Independently of that, overriding the viewer is a delicate issue in Relay/GraphQL due to the pervasive use of caching (where switching viewers may involve large parts or all of the cache to be invalidated).

**Comment by kareem3d** [comment]
@wincent `setViewer` will take a token as an input and save the viewer in the context(request). this is my first try tho with graphql and relay so I'm not sure what's the best approach to handle authentication but I have been working for the last 5 days only on the graphql side and I decided to wrap all my queries with a root type that will take the token as an argument and all other queries are nested. for mutations I had in mind that they execute sequentially so I created a setViewer mutation with a token input that a user must run before any other mutation. it was quite sad after I started working on relay that it doesnt support something like that.

Now I have moved to Authorization header and removed the root query and things actually becoming much easier to manage but it just doesnt feel like a graphql way of authentication I think...

**Comment by wincent** [comment]
@kareem3d: It's conventional to pass auth tokens along at the network layer level, but outside the query itself (see [this guide](https://facebook.github.io/relay/docs/guides-network-layer.html) for an example). You can then pass information about the authorized user through to the field resolvers on the server [via context](https://github.com/graphql/graphql-js/blob/7064b9d27cc677b714098d3851ba1daa2fca1043/src/execution/execute.js#L119).

**Comment by gautam123456** [comment]
@yungsters @jardakotesovec Can you please add this capability, we need it for good reasons. In our project we create custom fields and then we need a way to batch update those fields our backend already supports it but due to relay's incapability we are not able to do batch update.

**Comment by josephsavona** [comment]
I don't think we have anything in Relay Modern that limits the  number of root fields in a mutation. Have you tried this with Relay Modern (it will not work in classic/compat)?

**Comment by gautam123456** [comment]
Thanks @josephsavona for replying, we are still on 0.8.2, will try to upgrade and let you know if find any issue.

**Comment by divyenduz** [comment]
I tried this with relay modern and ran into the error:- 

```
ERROR:
Parse error: Error: FindGraphQLTags: Operation names in graphql tags must be prefixed with the modul
e name and end in "Mutation", "Query", or "Subscription". Got `LoginUserMutation` in module `CreateU
serMutation`. in "mutations/CreateUserMutation.js"
```

I am tried to make register + login user mutation in one go. 
Maybe because there is a specific format that requires us to use the file name in mutation name. 

Any ideas?

**Comment by c-neves** [comment]
I thought I needed this, ended up implementing it with Relay Modern, and it worked.
