### ISSUE TITLE
[Modern] Unable to reset environment

### ISSUE THREAD

**Issue by Togrias** [facebook/relay#2059]
I'm trying to implement a way to reset the store (such as upon log-out). Based on #1134 and other issues, the cleanest/recommended way is apparently to create a new Environment and passing it to a wrapper component around QueryRenderer (or in my case, Found Router), then passing the reset function via context to lower components.

But every time I create a new Environment, it keeps resetting to the old Store/Record Source values. The new Environment would retain all the store values by the time the App gets rendered. I'm not sure if this behaviour is unique to Relay Modern as I've never used Relay Classic.

A quick look at the source code shows that the Relay objects implement Object.freeze extensively. I'm not sure if that's the reason for this behaviour.

Are there any workarounds to instantiate a new Environment object with a blank Store? Are there any side effects?

**Comment by edvinerikson** [comment]
If you keep getting old data it's most likely because of
1: your network layer keeps a cache
2: you are reusing the same Relay Store/Record soiurce passed to the environment
3: you are not properly passing the new environment to the react tree causing it to still use the old environment.

I am doing the same thing (reseting the environment) and it works without issues in Relay Modern.

**Comment by wincent** [comment]
Thanks for posting, @Togrias.

> A quick look at the source code shows that the Relay objects implement Object.freeze extensively. I'm not sure if that's the reason for this behaviour.

To prevent unintended mutation. JS doesn't have real immutable "records", but we've programmed it with immutable semantics in mind. There are a few places where we do an `Object.freeze` in `__DEV__` mode as a way of catching violations of those semantics (while avoiding the runtime overhead in prod).

> Are there any workarounds to instantiate a new Environment object with a blank Store? Are there any side effects?

Nope, no workarounds should be required. Like @edvinerikson said, you should be able to reset by creating a *completely new* environment instance, and that means taking care not to re-use the old store or a network that might have cached previous responses.

I don't think there's an issue in Relay here, so going to close this.

**Comment by Togrias** [comment]
Thank you for the responses, @edvinerikson and @wincent. We still can't fix the issue and are pretty flummoxed by the behaviours. I'm pretty sure we're passing down a completely new network and store. But the moment the environment is passed to React, it reverts to its old value. 

I've pasted our code for the Wrapper below:

    reset = () => {
        const source = new RecordSource();
        const store = new Store(source);
        console.log(store); 
        const network = Network.create(this.props.fetchQuery);
        const environment = new Environment({store, network});
        const resolver = new Resolver(environment);
        this.setState({resolver});   //The moment this function executes, the new store and environment reset to their old values. If I comment out this line, then the new store and environment are created successfully but I have no way of passing them to React. 
    };

    render() {
        const Router = this.router;
        return <Router resolver={this.state.resolver}/>;
    }
