### ISSUE TITLE
Should "eslint-config-fbjs" really be in relay-compiler dependencies?

### ISSUE THREAD

**Issue by vshab** [facebook/relay#2063]
It is said in readme that this is internal facebook linting configuration. Having this package as dependency cause problems with incorrect peer dependencies for projects that use different eslint version.

Introduced by f4d62c0

**Comment by knpwrs** [comment]
It should definitely be moved to development dependencies, it is very annoying when I depend on `gatsby`, which in turn depends on `relay-compiler`, which in turn wants me to install linting dependencies that I don't even want to use.

**Comment by wincent** [comment]
https://github.com/facebook/relay/pull/2066 moves it.

**Comment by kassens** [comment]
Fixed by 7b914f0ec7b49004a9d63107884e501a92020b95
