### ISSUE TITLE
optimisticUpdater set value of an object inside node

### ISSUE THREAD

**Issue by jalalat** [facebook/relay#2065]
This is not working for me. I am getting an error: 

> relayrecordproxy setvalue(): expected a scalar value

    optimisticUpdater: (store) => {
      const id = 'client:newTodo:' + tempID++;
      const node = store.create(id, 'Comment');
      const author = {
        userId: user._id,
        userName: user.userName,
        vote: 0,
      };
      node.setValue(text, 'text');
      node.setValue(id, 'id');
      node.setValue(id, '_id');
      node.setValue(author, 'author'); // Getting an error here
      const newEdge = store.create(
        'client:newEdge:' + tempID++,
        'CommentEdge',
      );
      newEdge.setLinkedRecord(node, 'node');
      sharedUpdater(store, post, newEdge);
    },

**Comment by yuzhi** [comment]
As the error has mentioned, `setValue` is only for scalars. To update a new record, a new record you have to make a new record for `author` and setValue on each of the fields and then do `node.setLinkedRecord()` to reference author object from the new comment.

**Comment by jalalat** [comment]
Thanks; do not why i got sidetracked and started converting author into Scalar. It worked:

```
      const author = store.create(
        'client:newAuthor:' + tempID++,
        'author',
      );
      author.setValue(user._id, 'userId');
      author.setValue(user.userName, 'userName');
      author.setValue(0, 'vote');
      node.setLinkedRecord(author, 'author');
```
