### ISSUE TITLE
Relay prop in renderLoading

### ISSUE THREAD

**Issue by grydstedt** [facebook/relay#207]
How do I access the `relay` prop to pass it as property in `renderLoading`?

```
renderLoading={() => {
  return <Component loading={true} relay={this.props.relay} />;
}}
```

In Component, `this.props.relay` is undefined and `relay` is not defined as a property in `Relay.RootContainer`.

**Comment by devknoll** [comment]
The relay props are provided by RelayContainer. If Component is a container, the props should be there.

**Comment by josephsavona** [comment]
`renderLoading` is intended for showing a placeholder - loading spinner, etc - while the data for a Relay Container is being fetched. `this.props.relay` is only available inside of components wrapped with `Relay.createContainer()`. What are you trying to do?
