### ISSUE TITLE
[modern] 1.3 normalize mutation payload error

### ISSUE THREAD

**Issue by seanchas** [facebook/relay#2070]
`normalizePayload` function throws error if there is no data returned from mutation,
which is pretty normal, when mutation could not be completed.
Is it new design or mistake?

```
Uncaught Error: No data returned for operation `addToWishListMutation`, got error(s):
viewer.not-authorized
```

**Comment by seanchas** [comment]
It seems you have to provide `onError` handler to suppress error throwing.

**Comment by kassens** [comment]
cc @leebyron

**Comment by ajhyndman** [comment]
@kassens @leebyron Is this intended behaviour?

**Comment by ajhyndman** [comment]
This is a separate issue.  I'll follow up here:

https://github.com/facebook/relay/issues/2385

**Comment by jstejada** [comment]
cc @dwwoelfel

**Comment by ajhyndman** [comment]
@ViktorAksionov I'd appreciate if you add a thumb here, so we can highlight that this issue is ongoing, and important!

https://github.com/facebook/relay/issues/2385

**Comment by MM3y3r** [comment]
Any solution?

`Uncaught RelayNetwork: No data returned for operation`

**Comment by sibelius** [comment]
@MM3y3r please open an issue issue with your use case
