### ISSUE TITLE
The router that solves the request waterfall problem

### ISSUE THREAD

**Issue by grahammendick** [facebook/relay#2075]
## The Problem
A `QueryRenderer` per route works fine for flat routes, but causes the request waterfall problem for nested routes.

## The Solution
The problem isn't with nested routes. The problem is with nested configuration. The [Navigation router](http://grahammendick.github.io/navigation/) solves the request waterfall problem by using flat configuration for nested routes. With flat configuration you can have one `QueryRenderer` per configuration item, just like you'd have one `QueryRenderer` per flat route.

I've put together a [master/details example that shows flat configuration for nested routes](https://codepen.io/anon/pen/ayQdZW?editors=0010) in action. The route `/people` displays a list of names. Clicking 'brenda', for example, changes the route to `/people/brenda` and displays her date of birth inline. I capture these nested routes with the following flat configuration item:
```
{ key: 'people', route: 'people+/{name}' }
```
The work is done by the '+' in the route `people+/{name}`. It tells the Navigation router to turn this one route into two: `people` and `people/{name}`. You can then attach a function to this configuration item. The Navigation router calls your function whenever either route is hit and passes in any route data.

In the example, I've added a `getData` function that only fetches the person's date of birth if their name is passed in. You'd replace this with one `QueryRenderer`, pass it the route data and let GraphQL work out what to fetch.

**Comment by sibelius** [comment]
take a look here https://medium.com/@taion/react-routing-and-data-fetching-ec519428135c

awesome post by @taion

**Comment by grahammendick** [comment]
@sibelius The [Relay team are interested in routers that work well with Relay Modern](https://facebook.github.io/relay/docs/routing.html#custom-routing-and-more). They already know about Found

**Comment by kassens** [comment]
Feel free to send a PR to add a link to the new solution to https://facebook.github.io/relay/docs/routing.html#custom-routing-and-more. Since many environments have very different needs for routing and packaging, we're hoping that folks find the independent solutions that work for them.
