### ISSUE TITLE
[help wanted] Export Relay Flow types properly

### ISSUE THREAD

**Issue by yuzhi** [facebook/relay#2076]
Source code of ReactRelayCompatPublic.js and ReactRelayPublic.js exports a set of Flow types like: RelayPaginationProp,	
RelayProp,	
RelayRefetchProp,

However, these gets stripped out by Babel. Looking for volunteers to help us make them accessible so people can use it in their Relay components with Flow.

**Comment by kassens** [comment]
@leebyron Do you know how to do this? I figured you've configured it already for immutable.js?

**Comment by wincent** [comment]
See also #1758.

**Comment by kassens** [comment]
Closing as duplicate
