### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by bucaixiaot** [facebook/relay#2084]
I am reading the framework kernel code.
What is  packages/react-relay/classic and packages/react-relay/compat ？

my relay version is 1.1.0

**Comment by kassens** [comment]
Classic is the "old relay" before 1.0.0 and compat is a way to make the modern API work with the legacy core as a way to incrementally upgrade an application to the 1.0.0 style. Since this is a bigger shift we created this path.
For a new app this should ideally not be used!
