### ISSUE TITLE
How to handle intermittent network with Relay Modern? (docs issue)

### ISSUE THREAD

**Issue by lukecwilliams** [facebook/relay#2085]
I haven't found any examples or documentation on how to handle a network connection that is going in and out (e.g. is out for several minutes or hours while hiking in the woods, then returns).  We're on React Native.

**First problem**: how to pass a status from fetchQuery back to the Component, to display a "network unavailable" notification?  It looks like passing back an object with { error: [Error] } should work, but it doesn't seem to.

For now we've worked around this limitation by having the component subscribe to network updates in an environment.js file, then notifying the subscriber each time the network succeeds or fails.  The subscriber component then calls setState with the network status and message.  This seems clunky, especially when `QueryRender` already has an `error` parameter - it seems I should be able to get fetchQuery to feed something back into that parameter!  If course in Debug mode we get the exception text, but in Release mode the app just crashes.  How can we get fetchQuery to pass an error back to QueryRenderer?

**Second problem**: when the network comes back up, how can we allow the user to try a new query?  Of course if this is an hour later, any retries would be done.  We just need a button that says "ok Relay, now you can try fetching again."  There doesn't appear to be anything in the docs or code that I can find.

We're hacking around this by showing a Retry button that just restarts the app - works for our simple app now but as it gets more complex, that's not going to work.

Thanks!

**Comment by taufik-nl** [comment]
The same problem with me before, and a solution just added catch error on fetchQuery and don't write **errors** on QueryRenderer just write **error**, then every error will be passed to QueryRenderer.

**Comment by leebyron** [comment]
Checkout `<RelayRenderer>`'s renderer that provides `error` as an argument, which you can look for and decide to render a network unavailable screen.

Also, look for "readyState" within the relay prop which explains the state of the underlying requests including errors. These are available for exactly this case.

As far as network reconnection - this is a tricky problem and unfortunately not one that Relay helps you solve. Relay expects you to mostly bring your own network. There's a bunch of resources out there on how to detect network reconnection, and there's also a recent effort to add this to core browser API: http://wicg.github.io/netinfo/

**Comment by adeperio** [comment]
Hi @leebyron 

I'm having a similar issue here. How do I access the readyState prop? `this.props.readyState` doesn't seem to work in my component. In fact the render method of my component is not reached if the network connection is down. Do you know how I can render a state in the component for this particular scenario? Thanks
