### ISSUE TITLE
[compat] Modern-style mutation configs not supported by classic environment

### ISSUE THREAD

**Issue by psalz** [facebook/relay#2086]
While classic environments seem to be supposed to support modern-style mutation configs (i.e. for RANGE_ADD with `connectionInfo` instead of `connectionName` and `rangeBehaviors`), they actually don't support them.

I say *seem* as the [RelayMutationConfig](https://github.com/facebook/relay/blob/b29db7897e6ac5ec923e69465fbed482652d0845/packages/react-relay/classic/tools/RelayTypes.js#L165) flow type accepted by `RelayEnvironment`'s [sendMutation](https://github.com/facebook/relay/blob/b29db7897e6ac5ec923e69465fbed482652d0845/packages/react-relay/classic/store/RelayEnvironment.js#L223) method does include the new fields.

However, the `handleRangeAdd` function dealing with the configs [expects](https://github.com/facebook/relay/blob/b29db7897e6ac5ec923e69465fbed482652d0845/packages/react-relay/classic/traversal/writeRelayUpdatePayload.js#L345) `connectionName` to be set and has no notion of `connectionInfo`.

I'm nowhere near as familiar enough with Relay internals to know whether classic environments could even support modern-style configurations. In the meantime I could however certainly submit a PR so that compat `commitMutation` complains when it encounters a classic environment with new style configurations.

**Comment by leebyron** [comment]
Unfortunately this is one of many areas where Relay Modern has pressed ahead of Relay Classic in feature support.

>  In the meantime I could however certainly submit a PR so that compat commitMutation complains when it encounters a classic environment with new style configurations.

Please! I think this would be a great addition to developer experience.
