### ISSUE TITLE
Relay Chrome Extenstions Freezes 

### ISSUE THREAD

**Issue by akatebi** [facebook/relay#2088]
Hello,

 Once I refresh / reload the page. The Relay Extension pane becomes none responsive.  The Store Explorer page is not clickable. Nothing is clickable. I would have to close the developer tools and open it again for a work around. 

Thanks,
Alex Katebi

**Comment by taufik-hidayat** [comment]
You are right! Any solution everyone?

**Comment by leebyron** [comment]
Can you please provide some more information? Links to the version of the extension you're using,  what version of Relay you're using, the browser and OS version you're on.

**Comment by akatebi** [comment]
Hi Lee,

  It's an honor to have received an email from you. Below are two machines
that show the freeze behavior after a page refresh. Thanks, -Alex

Chrome: Version 61.0.3163.79 (Official Build) (64-bit)
Windows 7 Enterprise, Service pack 1
react-relay: 1.3.0
Relay Dev-Tools: 0.2.0


Chrome: Version 60.0.3112.113 (Official Build) (64-bit)
Windows 10 Enterprise
react-relay: 1.3.0
Relay Dev-Tools: 0.2.0

**Comment by leebyron** [comment]
Thanks for your report.

I'm working on getting a new version of the devtools out soon, which I hope will resolve your problem.

I'll let you know when that's released to look for your confirmation that your issue is fixed.

**Comment by akatebi** [comment]
Hi Lee,

   The Relay store and mutation visuals are invaluable. I look forward to
checkout the new version of the devtools.

   Any outside chance of getting a Firefox add-on for the devtools?

Thanks,
Alex

**Comment by leebyron** [comment]
I'll look into Firefox - I've never made plugins for Firefox before, but understand they're similar to Chrome.

**Comment by leebyron** [comment]
I'm also working on a standalone version of the devtools that you can use with Firefox or any other browser

**Comment by akatebi** [comment]
That would be great.  Thanks Lee!

**Comment by leebyron** [comment]
The standalone version is released (https://www.npmjs.com/package/relay-devtools) and the updated Chrome plugin is now published in the store (https://chrome.google.com/webstore/detail/relay-devtools/oppikflppfjfdpjimpdadhelffjpciba)

Hope this helps!
