### ISSUE TITLE
Have a better official working example than current relay-examples?

### ISSUE THREAD

**Issue by joonhocho** [facebook/relay#2099]
I am currently migrating from `classic` to `modern`, and it seems it's lacking both documentation and examples.

Lacking documentation is somewhat okay as long as there is a thorough example.

However, I looked at https://github.com/relayjs/relay-examples, and the app is too simple that it doesn't even use `PaginationContainer` nor `RefetchContainer` which are probably the harder part of migration with most changes (thus most important to document). It just uses a few simple `FragmentContainer` that is not too difficult to migrate in the first place. 

I want to see how `PaginationContainer` and `RefetchContainer` are used together with `QueryRenderer` and how they should be nested properly within other containers.

**Comment by sibelius** [comment]
check my example here https://github.com/sibelius/ReactNavigationRelayModern

**Comment by sibelius** [comment]
we should have a real world example

**Comment by joonhocho** [comment]
@sibelius Thanks! I see that it uses `PaginationContainer` and that's great! Do you also have an example of how to use `RefetchContainer`? I think your example also should be added to README. It will be very helpful.

**Comment by joonhocho** [comment]
@sibelius Also, in my existing app, I am using graphql directives like `@include` and `@skip` extensively, and I could just pass down variables with `getFragment` compositions.
Since `modern` queries are static, how do I achieve that?

**Comment by sibelius** [comment]
you can use @argumentDefinitions to define local variables on fragments

and use @arguments to pass down variables to components

example:

`...Component @arguments(var1: $var1)`

**Comment by sibelius** [comment]
check some of my issues about @include

like this one: https://github.com/facebook/relay/issues/2071

**Comment by leebyron** [comment]
Our documentation at https://facebook.github.io/relay/ is always improving. The absolute highest value contributions we get from the community are improvements to documentation and links to high quality examples.

As you're learning and encounter gaps in the documentation you wish existed, please consider coming back and writing something and contributing it! The rest of the community will greatly appreciate it.

Could either of you submit a PR to add a link to @sibelius's example to the relevant page in the documentation?
