### ISSUE TITLE
I want to provide custom `getModuleName` for compiler.

### ISSUE THREAD

**Issue by joonhocho** [facebook/relay#2101]
I organize my files into

```
ComponentName/component.ios.js
ComponentName/component.android.js
ComponentName/component.native.js
ComponentName/relay.js
ComponentName/config.js
```

This breaks current `getModuleName`. 
I am sure many people use their own way to organize their modules.
Ability to customize `getModuleName` from filepath would be great.

**Comment by leebyron** [comment]
We're not planning on allowing different module naming schemes, however we do plan to relax the constraint for the Relay Modern compiler that filenames need to match. See #2093.
