### ISSUE TITLE
[Modern] refetching with include(if: false) makes existing field undefined

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#2103]
Using the RefetchContainer I have two different fields I want refetch - but not always both.. depending how variables are changing I need to get update only from one or both. So I figured I can control with `@include(if: @shouldFetch)` expression which one I would refetch.

Request and response to the server works as expected. If include is false the field is completely omitted in response.

It looks like this:

```
export default createRefetchContainer(User, {
    viewer: graphql.experimental`
        fragment User_viewer on Viewer
        @argumentDefinitions(
            foo: {type: "String!", defaultValue: ""},
            bar: {type: "String!", defaultValue: ""},
            fetchFirst: {type: "Boolean!", defaultValue: false},
            fetchSecond: {type: "Boolean!", defaultValue: false},

        ) {
            firstField (foo: $foo) @include(if: $fetchFirst) {
                data
            }
            
            secondField (foo: $foo, bar: $bar ) @include(if: $fetchSecond) {
                data
            }
        }

    `
}, graphql.experimental`
    query UserRefetchQuery(
        $one: String!, 
        $two: String!, 
        $fetchFirst: Boolean!,
        $fetchSecond: Boolean!
        ) {
        
        viewer {
            ...User_viewer @arguments(
                one: $one, 
                two: $two, 
                fetchFirst: $fetchFirst, 
                fetchSecond: $fetchSecond,
            )
        }    
    }
`);
```

But issue is how its interpreted. Because when for example `two` is not present in response at all relay makes `viewer.two` undefined even if there was value before. 

So it seems that its serializing the response to the store also based on the actual query, not just based on the response, which make sense. But I would think if the @include/@skip is used to omit the field - it should be considered not requested at all, therefore not updating the store with undefined?

My intention is just update one of the fields with new value, but not loose value from the second one.

If we you are agreeable on this, some hint where to start to adjust this behavior?

Thanks!

**Comment by sibelius** [comment]
I was thinking in saving some data in state of the component as a workaround for this

**Comment by leebyron** [comment]
This definitely sounds like a bug, thanks for the clear report!

I think the fix is likely to be found in RelayResponseNormalizer, which is responsible for converting a network response into normalized Relay store in the context of a request. Seems like that might not be properly differentiating between `null` and `undefined`

**Comment by maikelrobier** [comment]
@leebyron  Are the `@include`/`@skip` directives going to be fully supported in relay modern? I ask because they are not present in the docs: https://facebook.github.io/relay/docs/relay-directives.html.

**Comment by leebyron** [comment]
They are supported as is, yes. That documentation page explains relay-specific client-side directives used by the relay-compiler, but `@include`/`@skip` are sent on to the server as is (if it supports them)

**Comment by leebyron** [comment]
Added some clarity in #2112 to improve that page

**Comment by jardakotesovec** [comment]
[Realized](https://github.com/facebook/relay/pull/2114#issuecomment-361855638) that this use case can be nicely addressed using renderVariables in refetch function.

So time to close this :-).
