### ISSUE TITLE
[Modern] Is it possible to share fragments without containers?

### ISSUE THREAD

**Issue by nikhildaga** [facebook/relay#2104]
In graphiql, we can write
```
{
  viewer{
    contact{
      ...contact
    }
  }
}

fragment contact on contact{
  firstName
  lastName
  avatar
}
```

In relay classic, we could write
```
import Relay from 'react-relay';

const contact = Relay.QL`fragment on contact {
  id
  firstName
  lastName
  avatar
}`;

export default Relay.createContainer(View, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on viewer {
        contact{
          ${contact}        
        }
      }`,
  },
});

```

In relay modern its necessary for the fragment to provide component name. So, is it even possible to share fragments without containers in relay modern ?  If not, what's the alternative? 

Even after providing component name, relay compiler gives the error : `RelayFlattenTransform: Unknown fragment `contact`.`

```
const contact = graphql`fragment Inbox_contact on contact{
  firstName
  lastName
  avatar
}`


export default createFragmentContainer(View, {
  viewer: graphql`
    fragment Inbox_viewer on viewer {
      contact {
        ...contact @relay(mask: false)
      }
    } `,
});
```

**Comment by nikhildaga** [comment]
I was able to fix this issue by creating fragment in separate folder and using 
`...Contact_contact @relay (mask : false)`


So, its possible to share fragments without containers.

**Comment by mike-marcacci** [comment]
Just to note, this does't appear to be possible [if the fragment requires arguments](https://github.com/facebook/relay/issues/2118).
