### ISSUE TITLE
Compiler does not generate Flow types for query arguments

### ISSUE THREAD

**Issue by steida** [facebook/relay#2105]
`query meQuery($filter: WebFilter) {`

I suppose WebFilter type should be generated.

**Comment by mike-marcacci** [comment]
FWIW these already appear to be generated for mutation arguments, and looking through the code on master, it looks like it *should* be generating... so maybe this has already landed but hasn't been released yet?

**Comment by AugustinLF** [comment]
This can probably be closed, this is fixed with `relay@1.5`.
