### ISSUE TITLE
Hoist non-react statics for HOCs

### ISSUE THREAD

**Issue by janicduplessis** [facebook/relay#2108]
`createFragmentContainer` and friends don't hoist static members of the class they wrap and this causes issues with libraries that use static properties. As a workaround you have to define the statics on the `Container` which is less ideal.

Example:
```js
class Screen extends Component {
  static route = { ... };
  ...
}
// This doesn't work :(
export default createFragmentContainer(Screen, ...);

// Have to do this instead
const FragmentContainer = createFragmentContainer(Screen, ...);
FragmentContainer.route = { ... };
export default FragmentContainer;
```

Static config on class seem to be a common pattern (used in react-natigation for example) so it would be nice to support this. Using https://github.com/mridgway/hoist-non-react-statics might be a good start, looks like it is what react-router uses for its HOCs.

Is this something we would to do and is there any drawback or potential issues?

**Comment by kassens** [comment]
This is certainly useful, but here are some reasons I have against it:

- Extra runtime overhead (iterating over the class statics) to construct containers, but we'd like to keep the overhead minimal to encourage creating smaller containers.
- Some extra magic, why are statics copied, but not instance methods? We had this internally for Classic and it creates even more magic that might break and make debugging harder.
- While we're not there yet to correctly type our containers with flow, this is something I'm working towards and this would make it more difficult.

Hope this makes sense and given that the workaround isn't that bad, maybe something that's not too bad?

**Comment by leebyron** [comment]
Doing this automatically is something I would strongly discourage. We actually tried this in Relay Classic, and it ended up being a significant runtime overhead burden and made flow typing very difficult.

I suggest either doing this manually, as your code examples shows (also, more explicit is better IMHO) or write a simple function or use mridgway's library directly to do so. That way you're opting into this behavior only for the components that need it, and are not paying that runtime cost for all of your Relay containers.

In Relay Classic we also tried pulling React class instance methods up onto the Relay container as well, similar issues, and we ended up adding a first class API to support this by allowing `componentRef` as a prop, leveraging React's "refs" API to get a ref to the contained component instance.

Perhaps it makes sense to have a first class API to get access to the contained React class as well?

**Comment by janicduplessis** [comment]
Makes sense, especially since it was already tried in Classic. If I want a similar behavior I could just wrap `create*Container` in a function that copies only the statics my app cares about.

> Perhaps it makes sense to have a first class API to get access to the contained React class as well?

I'm not sure how useful that would be since you usually already have access to that class. Maybe if some function takes in a potentially wrapped component class.

```js
function(Component) {
  const WrappedComponent = Component.WrappedComponent || Component;
  const value = WrappedComponent.someStatic;
  ...
}
```
