### ISSUE TITLE
[Modern] this.props.relay.environment._network.fetch disappeared in 1.3.0

### ISSUE THREAD

**Issue by nicerr** [facebook/relay#2110]
Doing the howtographql example with the lastest versions (react-relay@1.3.0) the statement:

`const result = await this.props.relay.environment._network.fetch(checkVoteQuery, {userId, linkId})` crashes.

Downgrading to react-relay@1.2.0 solves this problem.

See this issue: #https://github.com/howtographql/howtographql/issues/222

Using react-relay@1.2.0 this shows: 

![screen shot 2017-09-20 at 2 20 34 am](https://user-images.githubusercontent.com/1907478/30621648-90bcb9f2-9dac-11e7-9e5c-6a77b33aea72.png)

and using react-relay@1.3.0 this shows:

![screen shot 2017-09-20 at 2 30 42 am](https://user-images.githubusercontent.com/1907478/30621649-90c4b1a2-9dac-11e7-8b35-678179e88dbf.png)

It appears that the functions fetch, request, and requestStream have disappeared in 1.3.0?

Is this by design or error?

**Comment by sibelius** [comment]
this is not a public api, you should avoid using like this

**Comment by kassens** [comment]
`_` prefix is a convention we use for private properties. I'm not sure what the use case is here, but you should probably use a QueryRenderer or refetch container here.
We've made some changes to the network layer recently to allow more complex network response formats like potential streaming. The Network module is pretty much internal API.

**Comment by nicerr** [comment]
It's used in the recommended [Relay Modern tutorial](https://www.howtographql.com/react-relay/6-more-mutations-and-updating-the-store/) for a validation query. I'm a newbie and am just working through the tutorial. Sorry about that.

**Comment by iamglenbacs** [comment]
@sibelius what do you suggest to use aside from fetch with similar functionality?

**Comment by iamglenbacs** [comment]
@kassens i tried refetch container but there are other filters that I do not use at requests, what do i do with error that variables are not used?
