### ISSUE TITLE
[Modern] RelayNetworkLogger log shows YellowBox on ReactNative

### ISSUE THREAD

**Issue by felippepuhle** [facebook/relay#2111]
Hello folks, how are you?

<img width="444" alt="screen shot 2017-09-20 at 10 38 36 am" src="https://user-images.githubusercontent.com/15961929/30646778-8163bec6-9df0-11e7-88e9-bc6fb7e30625.png">

I think we could verify if `console.groupCollapsed` and `console. groupEnd` exists here: https://github.com/facebook/relay/blob/master/packages/relay-runtime/network/RelayNetworkLoggerTransaction.js#L90

That would solve this problem. I can send a PR if you agree.

Thanks!

**Comment by leebyron** [comment]
I suggest checking in the constructor, that way we can throw an early error if you're attempting to use the network logger on a platform that doesn't support it. A PR would be great

Also, I think these methods become available if you connect to a chrome debugger (Cmd+D from the simulator I believe)

**Comment by felippepuhle** [comment]
Left a message on the PR, thanks @leebyron.
