### ISSUE TITLE
Unknown directive "connection".

### ISSUE THREAD

**Issue by steida** [facebook/relay#2124]
It's probably Nuclide error, still, I am curious if something isn't broken at my side.

![screen shot 2017-09-24 at 16 45 30](https://user-images.githubusercontent.com/66249/30783707-ccfe3348-a147-11e7-9717-a70ec1dd1ca4.png)

**Comment by yuzhi** [comment]
This is a Nuclide issue. They might have an older version og the GraphQL plug in.

**Comment by sibelius** [comment]
I think we can close this

this is related to nuclide, not relay itself
