### ISSUE TITLE
what is relay-debugger-react-native-runtime and how to use it?

### ISSUE THREAD

**Issue by slicejunk** [facebook/relay#2129]
this is referenced from https://www.npmjs.com/package/relay-devtools-core

what is https://www.npmjs.com/package/relay-devtools then ?

what is the recommended solution to set up a relay debugger within a react native app ?

thanks,

**Comment by leebyron** [comment]
`relay-debugger-react-native-runtime` is the older version of the client-side devtools runtime which is specific to react native. That, and `relay-devtools-core` are no longer necessary (if you use Relay v1.4.0 or higher).

`relay-devtools` is the newer version of this which replaces those two packages, which has a simpler installation (see https://www.npmjs.com/package/relay-devtools README)
