### ISSUE TITLE
[Modern] Refetch an item in list of PaginationContainer.

### ISSUE THREAD

**Issue by joonhocho** [facebook/relay#2131]
I have a pagination list of items.
Later in the code, I want to refetch just an item, not the entire list as it will be waste of resource.
How can I do that in Relay modern?
I cannot use `RefetchContainer` for item because AFAIK it requires `QueryRenderer` as a wrapper that needs to receive its argument such as `id` from `PaginationContainer.render()`, but that is not possible at query time.
Is there any way to refetch `FragmentContainer` like `relay.forceRefetch()` in classic?

**Comment by sibelius** [comment]
no need for a queryRenderer, you can use refetchContainer alone

you just need to use @argumentDefinitions

your refetch query should use `node`

check this https://github.com/facebook/relay/issues/1942

**Comment by joonhocho** [comment]
@sibelius Thank you! It worked for me.
I did not know `RefetchContainer` could be used without `QueryRenderer`.
The following setup (simplified code) worked for me.
All I had to do is call `this.props.relay.refetch({id: this.props.item.id})` on ListItem.


```javascript
export default createRefetchContainer(ListItem, {
    item: graphql`
      fragment ListItem_item on Item {
        id
        value
      }
    `
  },
  graphql`
      query ListItemRefetchQuery($id: ID!) {
        node(id: $id) {
            ...ListItem_item
        }
      }
    `,
  );
);

export default createFragmentContainer(List, {
    list: graphql`
      fragment List_list on List {
        items {
          ...ListItem_item
        }
      }
    `
  );
);
