### ISSUE TITLE
[Modern] consider removing `getConnectionFromProps` from ReactRelayPaginationContainer

### ISSUE THREAD

**Issue by nodkz** [facebook/relay#2137]
It very annoying to define `getConnectionFromProps` method for every `ReactRelayPaginationContainer` (`createPaginationContainer`). 
If container will be restricted for fetching/serving only one connection (exactly one `@connection` directive in fragment) it helps to simplify code and reduce errors when creating containers. 

Anyway current pagination container can serve only one connection (loadMore, hasMore, isLoading). And if present other connections - they just present as regular fragments and can be taken out to another component/file.

https://github.com/facebook/relay/blob/17d06cc3410440094569ee7cf261382320b36939/packages/react-relay/modern/ReactRelayPaginationContainer.js#L193-L198

**Comment by yuzhi** [comment]
I think @kassens  had some ideas for this.

**Comment by kassens** [comment]
If you're running in RelayModern mode, you should actually be able to just leave out `getConnectionFromProps` and this code will generate the function from the location of the @connection directive.

https://github.com/facebook/relay/blob/d88ed376fa8ae05c52f21587ff7f2b48e0dad86e/packages/react-relay/modern/ReactRelayPaginationContainer.js#L318

We haven't advertised the broadly yet, as I couldn't find a clean-ish way to obtain the metadata in compat mode which back when I wrote this was the majority of our use cases.

**Comment by nodkz** [comment]
@yuzhi @kassens thanks a lot for the explanation.

One more question:
In `compat` mode for working `loadMore` method now is required explicit definition of `pageInfo { hasNextPage, endCursor }` in paginationContainer's fragment. Do I need to keep it for `modern` or it can be omitted?

---

How I understood `compat` mode contains excessive setups according to `modern`. And better way for migration is just to convert all single `fragments` in `compat` mode. Take a break on accepting new features in a project. And switch right away on `modern` for rewriting rest parts (connections, mutations, queries) of the app.

**Comment by sibelius** [comment]
Classic and compat is removed can we address this now?

**Comment by yuzhi** [comment]
Hang tight! This is all going away with the new Relay Hooks API. Still working with the React Core team to figure how best to deal with pagination + suspense.

**Comment by maxaggedon** [comment]
Hey everyone ! I guess there is some inconsistency between the code and the docs about `getConnectionFromProps `...

[**Docs**](https://relay.dev/docs/en/pagination-container#arguments)
> a container might fetch multiple fragments and connections, but can only paginate one of them

**Code**
https://github.com/facebook/relay/blob/7c45530d4d55b7371ef778d27c0d9dfb9b9fa989/packages/react-relay/ReactRelayPaginationContainer.js#L270-L276

If only one connection is allowed, then I guess `getConnectionFromProps ` is useless, or am I missing something ?

**Comment by sibelius** [comment]
Migrate to relay hooks, if the issue still valid, open another issue
