### ISSUE TITLE
[modern] RefetchContainer refetching same variables every time

### ISSUE THREAD

**Issue by Tismas** [facebook/relay#2143]
I have an autocomplete where I refetch data on change in it and as I understand without force flag it should not refetch data with same variables twice, right? For example if I have fetched data with variable "Hello" and then change it to "Hell" and back to "Hello" it should not fetch data for "Hello" second time, but it does. 

Here is my container:
```
export default createRefetchContainer(ExampleComponent, {
	data: graphql.experimental`
		fragment ExampleComponent_data on Autocomplete 
		@argumentDefinitions(
			a: {type: "String", defaultValue: ""}
			b: {type: "String", defaultValue: ""}
		) {
			someData(first: 10, a: $a) {
				edges {
					node {
						id
					}
				}
			}
			someMoreData(first: 10, b: $b) {
				edges {
					node {
						id
					}
				}
			}
        }
	`
},
graphql.experimental`
	query ExampleComponent_Query($a: String, $b: String) {
		autocomplete {
			...ExampleComponent_data @arguments(a: $a, b: $b)
		}
	}
`);
```

and I refetch it like this:
`
    this.props.relay.refetch(refetchVariables, null, () => {}, {force: false});
`

Requests are flying with same variables mutiple times.
 Did I do something wrong? Is it intended to work this way or it's a bug?

**Comment by amkoehler** [comment]
My understanding is that relay modern is supposed to work this way. In relay classic, any requests made while a component was mounted were cached and could be reused if the request matched a signature from a previous request. Relay modern makes no assumptions about what you want cached and will [garbage collect](https://facebook.github.io/relay/docs/new-in-relay-modern.html#garbage-collection) any data that is no longer referenced. 

If you want to implement your own caching, they reference how to do this in the [network layer docs](https://facebook.github.io/relay/docs/network-layer.html).

**Comment by sibelius** [comment]
check this https://github.com/facebook/relay/pull/2121

of how to add cache to your network layer

**Comment by sibelius** [comment]
Relay Modern has no cache as default option, you should bring your own cache implementation

check this post of how to do it https://medium.com/@sibelius/relay-modern-network-deep-dive-ec187629dfd3
