### ISSUE TITLE
[devtools] DevTools tab not present in inspector window

### ISSUE THREAD

**Issue by dminkovsky** [facebook/relay#2154]
Following up with: https://twitter.com/leeb/status/919954848736358400

I am not seeing the DevTools tab in the inspector. I am running Relay 1.4.1.

I went to `chrome://extensions` and under "Inspect views" clicked "background page" (only option). 

I did see one error in the console:

```
3_generated_background_page.html:1 Error in event handler for runtime.onConnect: TypeError: Cannot read property 'onMessage' of undefined
    at doublePipe (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/backgroundMessageBus.js:131:7)
    at chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/backgroundMessageBus.js:115:7
```

where `backgroundMessageBus.js:131` is this line

```
one.onMessage.addListener(handleOne);
```

**Comment by leebyron** [comment]
Thanks for the report!

**Comment by dminkovsky** [comment]
Also just saw this for the first time:

```
VM17215 extensions::messaging:102 Uncaught Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:140:26)
    at handleMessageFromBackend (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/injectGlobalHook.js:112:10)
PortImpl.postMessage	@	VM17215 extensions::messaging:102
publicClassPrototype.(anonymous function)	@	VM17214 extensions::utils:140
handleMessageFromBackend	@	injectGlobalHook.js:112
postMessage (async)		
send	@	globalHook.js:185
detectedRelayEnvironment	@	globalHook.js:230
(anonymous)	@	globalHook.js:113
registerEnvironment	@	globalHook.js:112
RelayModernEnvironment	@	RelayModernEnvironment.js:72
...
```
Would guess it's not related, but posting just in case.

**Comment by dminkovsky** [comment]
Whoops just noticed in relay examples that you need to `installRelayDevTools` from `relay-devools`. Yikes! That seems to have been the issue.

**Comment by dminkovsky** [comment]
However, now I get a lot of these:

```
index.js:970 WebSocket connection to 'ws://localhost:8734/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ index.js:970
(anonymous) @ index.js:997
```

and limited functionality

**Comment by alloy** [comment]
I’m a little confused, the Relay tab doesn’t show for me when opening the Chrome DevTools either and I’m also on Relay 1.4.1 (actually recent master, but I didn’t spot any related changes). Additionally I’m trying to use this in the context of a [storybook](https://github.com/storybooks/storybook/).

Using `installRelayDevTools` from the `relay-devtools` package makes it so I can use the standalone Electron app and connect successfully, but from what I understand that shouldn’t be necessary to being able to use the Chrome extension.

Looking at [this line of code](https://github.com/facebook/relay/blob/dc1de35386778ff0ca6c7a0898297383664c2334/packages/relay-runtime/store/RelayModernEnvironment.js#L85), I’m not sure I understand _who_ is responsible for defining the `__RELAY_DEVTOOLS_HOOK__` variable. Is it the Chrome extension? If so, got any tips where to look? (I have zero experience with Chrome extensions.)
