### ISSUE TITLE
[Modern] NODE_DELETE does not remove node from connections

### ISSUE THREAD

**Issue by dminkovsky** [facebook/relay#2155]
`NODE_DELETE` deletes a node from the store, but does not delete corresponding edges from connections that contain the node. The result is after a `NODE_DELETE`, pagination containers that render a connection that had this node will receive connections props with the an edge that has a cursor but `null` a node.

The documentation says `NODE_DELETE`:

> Given a deletedIDFieldName, Relay will remove the node(s) from the connection.

[setRelayModernMutationConfigs.js](https://github.com/facebook/relay/blob/v1.4.1/packages/relay-runtime/mutations/setRelayModernMutationConfigs.js#L98) seems to verify this as the intended behavior.

Wouldn't it make sense for `NODE_DELETE` to delete from ranges that contain this node, too? Would that be possible given the new runtime? Is the correct solution to explicitly add a RANGE_DELETE config in addition `NODE_DELETE` to remove from the connection? Should the docs be updated?

**Comment by dminkovsky** [comment]
Reading through `RelayConnectionHandler`, it seems like this would be pretty complicated. You'd have to look through all connections that might possibly have this node?

**Comment by bharathmuraleedharan** [comment]
Basically NODE_DELETE is useless alone, it should be used along with RANGE_DELETE to avoid npes!

**Comment by DavidHe1127** [comment]
@dminkovsky

have you got this issue resolved? I have the same problem and no idea what to do with null node

**Comment by bharathmuraleedharan** [comment]
@DavidHe1127 you could try writing updater: https://github.com/relayjs/relay-examples/blob/a5e1139906197ceeca70c30cd98cef48e952c04c/todo/js/mutations/RemoveTodoMutation.js#L55

**Comment by dminkovsky** [comment]
@DavidHe1127 nope, I never resolved it beyond moving from configs to updaters, which I think is the intended way in Relay Modern. As @bharathmuraleedharan points out, you can write an updater and target the connection you're looking to remove from. 

I haven't look at this in a while, so maybe something changed: but if you're trying to remove a node from all connections after you delete a node, short of knowing a priori which connections it belonged to and removing that node from those connections, it appears there is no easy way to do that.

**Comment by jamesone** [comment]
Confirmed that I see the same issue - An edge remains with the following contents:

```
{
cursor: 'xxx',
node: null,
}
```

This happens using the following config:

```
const configs = [
  {
    type: 'NODE_DELETE',
    deletedIDFieldName: 'id',
  }
];

const optimisticResponse = {
  deleteUser: {
    id: id,
  },
};

commitMutation({
  mutation,
  variables,
  optimisticResponse,
  configs,  
  onCompleted: res => resolve(res),
  onError: err => reject(err),
});
```

**Comment by taion** [comment]
You can add a `RANGE_DELETE` config to clean up edges from any relevant connections.

**Comment by dminkovsky** [comment]
Yeah, that's my thinking on this too now. There's no way to remove from all connections the node might be in unless you know the connections, but given the typical GC/fetch data flows I've experienced in Relay, that's okay.
