### ISSUE TITLE
RefetchContainer alway use QueryRenderer's initial data

### ISSUE THREAD

**Issue by cgx9** [facebook/relay#2160]
first,my initial query renders is return [a,b]，and then in my refetch container i trigger this.props.relay.refetch({id: 4}),my fetchQuery already return [c,d,e,f].but nextProps still [a,b]

i am  in RelayModernFragmentSpecResolver.js debug resolve  method,this._resolvers[key] alway null

**Comment by cgx9** [comment]
fragment.metadata

**Comment by cgx9** [comment]
my fragment code is
```js
fragment refetchindex_viewer on GoodsCategory
@argumentDefinitions(
  id: { type: "Int", defaultValue: 1}
)
@relay(plural:true) {
    goodsCategory(spaceType: $id,code: $code){
      id
      ......
  }
}
```
but fragment.metadata is null

**Comment by cgx9** [comment]
resolved .please close this.

**Comment by sibelius** [comment]
@cgx9 you can close

**Comment by fi11** [comment]
@cgx9 i have a same issue, how did you resolve it?

**Comment by hisapy** [comment]
how is this resolved? ... I'm on 1.3.0 and the component never gets updated props

**Comment by sibelius** [comment]
this https://github.com/facebook/relay/pull/2507 could solve this
