### ISSUE TITLE
environment.execute is not a function after upgrade

### ISSUE THREAD

**Issue by tomas-paronai** [facebook/relay#2167]
After upgrading from `1.2.0-rc.1` to `1.4.1` I get the following error related to Environment:
`TypeError: environment.execute is not a function in ReactRelayQueryRenderer`

**Comment by seripap** [comment]
I get this issue as well, upgrading from v1.3.0 to 1.4.1.

From the dist, this is where it breaks in `ReactRelayQueryRenderer`
```js
var request = environment.execute({ operation: operation, cacheConfig: cacheConfig })['finally']
```

**Comment by maxaggedon** [comment]
I had the same thing for a sec but there was an unmet peer dependency with `relay-compiler`. Have you tried updating it as well ? With both packages updated to `1.4.1` and after recompiling the relay codebase everything worked fine for me.

**Comment by seripap** [comment]
@maxaggedon that fixed it. thanks!

**Comment by tomas-paronai** [comment]
Oh thanks! I was also using `relay-runtime` so upgrading just the `relay-compiler` did not help but after setting all relay modules to `1.4.1` did the job.
