### ISSUE TITLE
Electron DevTools: dead link in the docs

### ISSUE THREAD

**Issue by maxaggedon** [facebook/relay#2169]
Relay DevTools seems really great to track what's happening while developing, unfortunately the link towards the electron standalone is dead...

https://facebook.github.io/relay/docs/relay-debugging.html#debugging-visually

Is it still available somewhere ?

**Comment by sibelius** [comment]
check this https://github.com/facebook/relay/issues/2129#issuecomment-332986659

and this https://www.npmjs.com/package/relay-devtools

**Comment by maxaggedon** [comment]
thanks a lot!
