### ISSUE TITLE
[Modern] UI not updating after subsequent mutations in connection

### ISSUE THREAD

**Issue by hoantran3108** [facebook/relay#2179]
Currently, I stumbled accross a problem with mutations in relay modern. I have a diary which contains a list of entries. Whenever a user add an entry which day of diary doesn't exist, it will create a diary before creating an entry. Everything works as expected without any errors to console.log but the UI doesn't update immediately. When i refresh the page, both new diary and new entry are there.

add a diary if not exist with a callback to provide id for AddEntryMutation
```
import { commitMutation, graphql } from 'react-relay';

const mutation = graphql`
  mutation AddDiaryMutation($input: AddDiaryInput!) {
    createDiary(input: $input) {
      diary {
        id
        ...EntryList_entries
      }
    }
  }
`;

let clientMutationId = 0;

const commit = (environment, { date }, callback) =>
  commitMutation(environment, {
    mutation,
    variables: {
      input: {
        date,
        clientMutationId: clientMutationId++
      }
    },
    onCompleted: response => {
      const id = response.createDiary.diary.id;
      callback(id);
    }
  });

export default { commit };
```

AddEntryMutation will get the id from AddDiaryMutation response to add entry.
```
import { commitMutation, graphql } from 'react-relay';
import { ConnectionHandler } from 'relay-runtime';

const mutation = graphql`
  mutation AddEntryMutation($input: AddEntryInput!) {
    createEntry(input: $input) {
      entryEdge {
        node {
          id
          tasks {
            edges {
              node {
                id
                name
                done
              }
            }
          }
        }
      }
    }
  }
`;

function sharedUpdater(store, diaryId, newEdge) {
  const diaryProxy = store.get(diaryId);
  const conn = ConnectionHandler.getConnection(diaryProxy, 'EntryList_entries');
  ConnectionHandler.insertEdgeAfter(conn, newEdge);
}

let clientMutationId = 0;

const commit = (environment, { diaryId, ...rest }, callback) =>
  commitMutation(environment, {
    mutation,
    variables: {
      input: {
        ...rest,
        clientMutationId: clientMutationId++
      }
    },
    updater: store => {
      const payload = store.getRootField('createEntry');
      const newEdge = payload.getLinkedRecord('entryEdge');
      sharedUpdater(store, diaryId, newEdge);
    },
    onCompleted: () => callback()
  });

export default { commit };
```

EntryList fragment

```fragment EntryList_entries on Diary {
      entries(first: 20) @connection(key: "EntryList_entries", filters: []) {
        edges {
          node {
            ...Entry_entry
          }
        }
      }
    }
```
Entry fragment
```
fragment Entry_entry on Entry {
      id
      tasks {
        edges {
          node {
            id
            name
            done
          }
        }
      }
    }
```

**Comment by maxaggedon** [comment]
Hi, you haven't specified any `updater` nor `configs` in `AddEntryMutation`. Might be a good start ;)

**Comment by baquy96** [comment]
@maxaggedon In this case, Diary is a root node so I don't know how to write in updater. Do you have any idea for it?

**Comment by maxaggedon** [comment]
I have never tried that. But I guess you must have tried to query it in order to know that it did not exist. Something like that:
```
query {
  diary(id: $id) {
    id
    ...EntryList_entries
  }
}
```
and the response must have been:
```
{
  data: {
    diary: null,
  } 
}
```
Then maybe there is a root field in the store with a value set to `null`. In that case you could get it with `store.getRootField("diary")` (I am not sure what the name of the field would be) and update it with `setValue(payload.getLinkedRecord('diary'))`.

That's what I would try, but I cannot guarantee it will work...

**Comment by baquy96** [comment]
@maxaggedon Thanks so much but it's still not working.

**Comment by AndreiCalazans** [comment]
There are few examples around on to update store.
here is one
https://github.com/AndreiCalazans/hackernews-react-relay/blob/master/src/mutations/CreateVoteMutation.js

Relay Modern is a bit smarter than Relay Classic, for example it can update by itself when it is a simple fields change but you need to get back from the mutation the fields that you changed in the payload of your mutation.

if simple fields change does not work you will need to update through the updater like in the example in the repo.

**Comment by alloy** [comment]
@hoantran3108 Is this resolved by now?

**Comment by taion** [comment]
there isn't actually an issue here. to add an item to a list, you either need to pull down the edge and use a `RANGE_ADD` config (if using connections), or write an updater yourself to prepend this to an existing list. if you just get back a new item, relay has no way to know where to insert it

**Comment by alloy** [comment]
Alright, gonna close this then as there doesn’t appear to be anything actionable.
