### ISSUE TITLE
Add callback to RelayMutationTransaction for optimistic mutation

### ISSUE THREAD

**Issue by amccloud** [facebook/relay#218]
This would useful in a scenario where you have a mutation that persist a new record but you have enough information display that record immediately to the user.

```javascript
    Relay.Store.update(new CreatePhotoMutation({
      viewer: this.props.viewer,
      photo: {
        localImageUri,
        remoteImageUri
      }
    }), {
      onOptimistic: (data) => {
        navigator.push(
          new PhotoRoute({createPhotoMutationId: data.createPhoto.clientMutationId})
        );
      }
    });
```

Something like that?

**Comment by josephsavona** [comment]
Knowing when the optimistic record has been created makes sense, and having access to the `clientMutationId` would presumably be used for checking for errors within the view that you're pushing?

This seems like a good use case, and shouldn't be too difficult to support. The main points to consider when implementing this (mostly in `RelayMutationTransaction`) are to avoid firing the callback multiple times ([`_handleOptimisticUpdate()`](https://github.com/facebook/relay/blob/master/src/mutation/RelayMutationTransaction.js#L290-L302) is called again if another mutation has to be rolled back)

**Comment by amccloud** [comment]
@josephsavona I'm not actually sure about the `clientMutationId`. The idea is to have the next view query the store for the optimistic response (and eventually real response) by that client id.

**Comment by josephsavona** [comment]
Yeah, you can't fetch records via a `clientMutationId`. The schema would need some field for identifying the newly created object that wouldn't change between the optimistic payload and the server response.

**Comment by yungsters** [comment]
Adding an `onOptimistic` callback does indeed make sense. As discussed, you probably don't want to ever use `clientMutationId` for anything.

If this is a `RANGE_ADD` mutation, the new node will have an optimistically generated client-side `id` that you can use in the callback. Unfortunately, Relay should but does not currently support generating optimistic client-side IDs for other types of mutations (e.g. creating a new orphaned node).

**Comment by grydstedt** [comment]
+1 on adding `onOptimistic`, seems very useful.

**Comment by josephsavona** [comment]
@amccloud @grydstedt does this still seem useful, or have you found workarounds? I'm going to close this due to inactivity, but feel free to comment or submit a PR to add this callback!
