### ISSUE TITLE
Pagination refetchconnection

### ISSUE THREAD

**Issue by yo34** [facebook/relay#2197]
Using relay 1.4.1, I created a Pagination Container. It works fine. I would like to update a variable when I get new props (like I did with a RefreshContainer) according to the given API from this page : https://facebook.github.io/relay/docs/pagination-container.html

Here is a part of my code :

```
componentWillReceiveProps(nextProps) {
  if(nextProps.myfilter === this.props.myfilter) {return;}
  const refetchVariables = fragmentVariables => ({status: fragmentVariables.status=nextProps.myfilter});
  console.log(refetchVariables)
  //this.props.relay.refetch(refetchVariables, null);
  this.props.relay.refetchConnection(4, null, refetchVariables);
  }
}
```

In my getVariables function, I still get the initial value of my variable 'status'.
```
getVariables(props, {count, cursor}, fragmentVariables) {
      console.log("getVariables " + JSON.stringify(fragmentVariables.status) );
      return {count, cursor, status: fragmentVariables.status}
    },
```
Have I forgotten something ?

**Comment by slaviczavik** [comment]
Did you try `refetchConnection(4, null, { status: nextProps.myfilter })`? This should rewrite init variables in `getVariables` function.

**Comment by slaviczavik** [comment]
Did you try refetchConnection(4, null, { status: nextProps.myfilter })? Third argument is then accessible in `getVariables` function via `fragmentVariables`.

**Comment by rodrigopr** [comment]
Hit the same problem.
Merging the `fragmentVariables` with the `_localVariables` on RelayPaginationContainer seems to fix for me. Still learning some relay-modern concepts, so it might not be the best/correct approach.

https://github.com/facebook/relay/blob/337aed906c69a6a3c63a3d384124a665d1d53d59/packages/react-relay/modern/ReactRelayPaginationContainer.js#L644-L652

what fixed for me:
```
// Pass the variables used to fetch the fragments initially
{...fragmentVariables, ...this._localVariables}
```

**Comment by yo34** [comment]
@slaviczavik, thank you. it's work now.
