### ISSUE TITLE
[Modern] ReactRelayFragmentContainer does not resolve new data from store immediatelly

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#2201]
Having simple schema like
```
{
  viewer {
    user {
      id
    }
  }
}
```
and Studio component rendering `StudioGrid`
```
class Studio extends React.Component {
render() {
 return <StudioGrid viewer={this.props.viewer}>
}
}
```
Both wrapped with createFragmentContainer. If I console.log in render what user.id looks like  after mutation which switches to different user:
```
Studio render: US-2
StudioGrid.jsx:220 StudioGrid render: US-107
StudioGrid.jsx:220 StudioGrid render: US-2
```

I have been looking into `ReactRelayFragmentContainer` and what happens it simply resolves old data in `componentWillReceiveProps` even though the props coming to `componentWillReceiveProps` are correctly with new user:
```
      const data = this._resolver.resolve();
      if (data !== this.state.data) {
        this.setState({data});
      }
```

Second render has correct data (shortly after first render) from:
```
      this._resolver = createFragmentSpecResolver(
        relay,
        containerName,
        fragments,
        props,
        this._handleFragmentDataUpdate,
      );
```

But I think it should already get correct data in componentWillReceiveProps.

If I would modify my scenario and also would pass the user object:
```
render() {
 return <StudioGrid viewer={this.props.viewer} user={this.props.viewer.user}>
}
```
It correctly detects the change immediately and both this.props.viewer.user.id and this.props.user.id are correctly updated already in componentWillReceiveProps (in ReactRelayFragmentContainer for StudioGrid).

This issue can leads (in my case) to some tricky inconsistent state. In my case issue is that Studio will makes some state changes in componentWillReceiveProps and studioGrid than gets this new state as prop from Studio but it has old data from Relay.

**Comment by jardakotesovec** [comment]
Also to point out, apart from this inconsistency for short time (which is fairly rare case that this is causing issue) it also has performance impact to trigger more renders than necessary.

**Comment by sibelius** [comment]
migrate to useFragment, if the issue still valid open another issue
