### ISSUE TITLE
relay-compiler misses like-named queries & mutations in sibling directories

### ISSUE THREAD

**Issue by piotrblasiak** [facebook/relay#2203]
I have the following directory/component structure:

```
Users/
Users/Home.js
Events/
Events/Home.js
```

Both Home.js have queries with the same names:

```
const query = graphql`
  query HomeQuery {
    something {
      id
      name
    }
  }
`;
```

Problem now is that unless I name the query in Events/Home.js something else, it won´t get picked up by the relay-compiler. So the only workaround I´ve found so far is to do this:

```
const query = graphql`
  query Home_Query {
    something {
      id
      name
    }
  }
`;
```

**Comment by sibelius** [comment]
- query names should be unique

this enable persisted queries

**Comment by piotrblasiak** [comment]
Ah, I see.  Makes sense. Thanks.

**Comment by piotrblasiak** [comment]
@sibelius just a thought then - maybe the relay-compiler should not enforce a query naming where the component name has to be the prefix? In my case I have to do something like Home_Users_Query to make it unique.

**Comment by sibelius** [comment]
Unique name for filename is a good thing as well

UsersHome and EventsHome is better than just Home

**Comment by piotrblasiak** [comment]
@sibelius that´s something I´ve been debating with myself quite extensively and it´s not as easy as that - I mean, how far would that go? In this case, they would have to be globally unique - and what if you have 2 EventsHome in the app? Would you then name them MainEventsHome and ManagerEventsHome? This is a reality in my app and I decided to go with namespacing instead.
I might be wrong, and my workaround is not too much of a pain. Anyhow, just my opinion on the matter.

**Comment by hisapy** [comment]
I solved a similar problem by _un-colocating_ the fragment. For example, I have a `PeoplePaginationContainer` which exports a function that calls `createPaginationContainer` with the component passed as arg. Then I use the same fragment with 2 or 3 components that need to paginate people connection.
