### ISSUE TITLE
Strange thing with getVariables in Pagination Container

### ISSUE THREAD

**Issue by slaviczavik** [facebook/relay#2207]
[**According to source code**](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayPaginationContainer.js#L182):

```js
getVariables(props, {count, cursor}, fragmentVariables) {
  return {
    ...RelayFBCompatQueryConstants.get(),
    id: props.user.id,
    afterCursor: cursor,
    count,
  },
 }
```

This doesn't works (request is sent, response is received, but **view is not rendered**).

But if I set value for this prop in `QueryRenderer`:

```js
<QueryRenderer
  environment={environment}
  query={query}
  variables={{
    count: 2,
    id: user.id
  }}
  render={({ error, props }) => {
    // Rendering...
  }}
/>
```
It works, but only if `user.id == props.user.id`.

### Summary
It seems the pagination only works if the `getVariables` function returns object with values from `count`, `cursor`, `fragmentVariables` but not from `props`.

**Comment by slaviczavik** [comment]
Hm, I just added `filters` prop with empty array as value to the `@connection` and it works!

**Comment by MapleYe** [comment]
The getVariables function can grab data from props if the prop is passed from its parent component.  You can check the value of the prop like your props.user.id in its React component.

**Comment by Meshu** [comment]
@slaviczavik thank you so much !
My pagination container was not working properly either without a filters array or with one with my varying parameter in it. putting an empty array is what did it for me !

However I would be interested to understand what was happening here.

**Comment by jstejada** [comment]
hi @slaviczavik , @Meshu, what did your `@connection` annotations look like? Did they have `key`?
Here's a brief explanation of `@connection`: https://facebook.github.io/relay/docs/en/pagination-container.html#connection

**Comment by Meshu** [comment]
Hi @jstejada.

Here is my pagination fragment, pretty standard inifite scroll searchable list :
`fragment ServerList_viewer on Viewer
  @argumentDefinitions(
    count: { type: Int, defaultValue: 20 }
    cursor: { type: String }
    searchTerm: { type: String, defaultValue: "" }
   ) {
  servers(first: $count, after: $cursor, searchTerm: $searchTerm)
    @connection(key: "ServerList_servers", filters: []) {
    totalCount
    edges {
      node {
        id
        ...Server_server
      }
    }
  }
}`

This version works as intended.

Trouble arises if I remove the filters array or if I add `"searchTerm"`.
Then when I call refetchConnection with a new searchTerm, the first query is ok, but subsequent `loadMore` will not reconcile the store properly, though the query will have the right shape.

**Comment by hughevans** [comment]
@Meshu I had/have the same issue. So I added the args into my state (Redux) and plucked them back out for the PaginationContainer:

``` javascript
  getVariables(props, { count, cursor }, fragmentVariables) {
      return {
        count,
        cursor,
        filter: props.filter,
        orderBy: props.orderBy,
        accountID: props.account.id,
      };
    },
```

So yes, I too cannot use the `fragmentVariables` as intended (in combination with `loadMore()`).
