### ISSUE TITLE
Open the slack channel

### ISSUE THREAD

**Issue by boosh** [facebook/relay#221]
The slack channel at https://reactiflux.slack.com/messages/relay/ gives me a message "To start using Slack, you'll need to be invited by your team administrator." How can I get an invitation?

**Comment by sgwilym** [comment]
Slack is a bit weird — it’s not really made for big public channels yet. However, you can be 'invited' in using the signup form on this page: http://www.reactiflux.com (which seems to be down at the moment…)

**Comment by boosh** [comment]
Oh. It'd be helpful to note that in the `CONTRIBUTING.md` file in that case. Thanks.
