### ISSUE TITLE
Add ability to remove a linked record from a RelayRecordProxy

### ISSUE THREAD

**Issue by mike-marcacci** [facebook/relay#2210]
Right now, there appears to be no way to remove a linked record from another record. For example, given the following GraphQL schema:

```graphql
type Something {
  id: ID!
  name: String
}

type Query {
   something: Something
}
```

We might want to remove the link from the root `something` field, while not necessarily deleting the record with ID `abcd` from the store (in case it's referenced elsewhere). Attempting to set the linked record to `null` fails, and using `setValue` does not produce the desired result.

```es6
store.getRoot().getLinkedRecord('something');
// => RelayRecordProxy {_dataID: "abcd"}

store.getRoot().setLinkedRecord(null, 'something');
/*
invariant.js:49 Uncaught Error: RelayRecordProxy#setLinkedRecord(): Expected a record, got `null`.
    at invariant (invariant.js:42)
    at RelayRecordProxy.setLinkedRecord (RelayRecordProxy.js:66)
    at <anonymous>:1:3
*/

store.getRoot().setValue(null, 'something');
store.getRoot().getLinkedRecord('something');
// => RelayRecordProxy {_dataID: "abcd"}
```

I searched around for a solution, and it appears that others have had this issue as well: https://stackoverflow.com/questions/46859833/is-it-possible-to-unlink-a-linked-record-using-the-relay-modern-imperative-mutat

This could be resolved by either:

- Accepting a `null` value in `setLinkedRecord`
- Adding a `removeLinkedRecord` specifically for this case

**Comment by smagch** [comment]
Does the issue still remain a problem? I can't replicate the issue with Relay `1.5.0`, 

I've just pushed an example app, which just demonstrate unlinking records: https://github.com/smagch/relay-example-unlinking-records
https://smagch.github.io/relay-example-unlinking-records/

**Comment by mike-marcacci** [comment]
@smagch thanks for the awesome demo! And yes, I can confirm that this now works in `1.5.0` :-)
