### ISSUE TITLE
Relay website has reverted styling

### ISSUE THREAD

**Issue by mike-marcacci** [facebook/relay#2215]
Hey there! It looks like something happened on the [gh-pages](https://github.com/facebook/relay/commits/gh-pages) branch causing this:

![image](https://user-images.githubusercontent.com/690517/33511101-2045de22-d6e3-11e7-814e-16e0bcc247fc.png)

to look like this again:
![image](https://user-images.githubusercontent.com/690517/33511104-2751bc18-d6e3-11e7-8ca1-ba5109dadcd7.png)

**Comment by mike-marcacci** [comment]
Haha, this was probably intentional on the part of your team; the color scheme had just reminded me of the previous template, so I assumed it was a reversion. But it clearly wasn't:

![image](https://user-images.githubusercontent.com/690517/33511235-cd6a8c82-d6e4-11e7-8806-fa6c72c8daa8.png)

**Comment by kassens** [comment]
@mike-marcacci Thanks for noticing. We switched to [Docusaurus](https://docusaurus.io/) which mroe and more FB OSS projects like Jest or Flow use and provides us less maintenance while also adding new features like API search and a translation framework, and automatic deployment on commits!

The one downside is that we lost the custom styling, but that seemed like a fair trade off.

**Comment by mike-marcacci** [comment]
Sounds great @kassens! One note: It looks like the [Docusaurus repo](https://github.com/facebookexperimental/Docusaurus) is private at the moment. This may be intentional as well, but figured I'd mention it!
