### ISSUE TITLE
How to render nested data : Many Posts with Many Comments.

### ISSUE THREAD

**Issue by bitcoinporn** [facebook/relay#2220]
I'm a bit stuck here, i tried to display Posts data with pagination, then each post will display many comments and with pagination too.

I can't find any example of this on web... is there best practice to do this?

**Comment by MartinDawson** [comment]
Same problem as me https://github.com/facebook/relay/issues/2223

**Comment by ngthorg** [comment]
@bitcoinporn try with this example https://github.com/facebook/relay/issues/2223#issuecomment-350165328

**Comment by sibelius** [comment]
use a refetch container to handle pagination

each connection in each refetchContainer

check this https://github.com/entria/guidelines/blob/master/relay/flatlist-relaymodern.md of how to handle pagination using refetchContainer
