### ISSUE TITLE
[Modern] Nested pagination

### ISSUE THREAD

**Issue by MartinDawson** [facebook/relay#2223]
I have a root query of `songs`, this is in a pagination container.
I then have a nested property on songs called `comments` that I also want to be paginated because I don't want to load 10k comments for each song all at once.

songsContainer.js:

    fragment songsContainer on Query {
        songs(
          first: $count
          after: $cursor
          genre: $genre
          filter: $filter
        ) @connection(key: "songsContainer_songs") {
          edges {
            node {
              audioId
              name
              coverImageUrl
              artist
              likes
              dislikes
              ...commentsContainer
            }
          }
        }
      }

    const connectionConfig = {
      direction: 'forward',
      query: graphql`
        query songsContainerForwardQuery(
          $count: Int!
          $cursor: String
          $genre: String
          $filter: FilterInput
        ) {
          ...songsContainer
        }
      `,
      getVariables: (_, { count, cursor }) => ({
        count,
        cursor,
      }),
    };

    paginationContainer(fragments, connectionConfig);
  
commentsContainer.js

      fragment commentsContainer on Audio {
        comments(
          first: $count
          after: $cursor
          getReplies: $getReplies
        ) @connection(key: "commentsContainer_comments") {
          edges {
            node {
              commentId
              body
              date
              likes
              dislikes
              repliesCount
              originalComment {
                id
              }
              user {
                userName
              }
            }
          }
        }
      }

How do I write the connectionConfig for the comments? I tried this:

    const connectionConfig = {
      direction: 'forward',
      query: graphql`
        query commentsContainerForwardQuery(
          $count: Int!
          $cursor: String
        ) {
          ...commentsContainer
        }
      `,
      getVariables: (_, { count, cursor }) => ({
        count,
        cursor,
      }),
    };

But because the comments are nested on songs then it throws an error saying that the query doesn't exist on the Root.

**Comment by ngthorg** [comment]
SongsContainer.js

```
createPaginationContainer(
  SongsContainer,
  {
    viewer: graphql`
      fragment SongsContainer_viewer on Query {
        id
        songs(first: $count, after: $cursor)
          @connection(key: "SongsContainer_songs", filters: []) {
          edges {
            cursor
            node {
              id
              ...SongItem_song
            }
          }
        }
      }
    `
  },
  {
    direction: 'forward',
    getConnectionFromProps(props) {
      return props.viewer && props.viewer.songs;
    },
    getFragmentVariables(prevVars, totalCount) {
      return {
        ...prevVars,
        count: totalCount
      };
    },
    getVariables(props, { count, cursor }, fragmentVariables) {
      return {
        count,
        cursor
      };
    },
    query: graphql`
      query SongsContainerQuery($count: Int!, $cursor: String) {
        viewer {
          ...SongsContainer_viewer
        }
      }
    `
  }
);
```

SongItem.js

```
createRefetchContainer(
  SongItem,
  {
    song: graphql`
      fragment SongItem_song on Audio
        @argumentDefinitions(
          count: { type: "Int", defaultValue: 20 }
          cursor: { type: "String", defaultValue: null }
        ) {
        id
        ...CommentsContainer_song
      }
    `
  },
  graphql`
    query SongItemQuery($id: ID!, $count: Int!, $cursor: String) {
      song(id: $id) {
        ...SongItem_song @arguments(count: $count, cursor: $cursor)
      }
    }
  `
);
```

CommentsContainer.js

```
createPaginationContainer(
  CommentsContainer,
  {
    song: graphql`
      fragment CommentsContainer_song on Audio {
        id
        comments(first: $count, after: $cursor)
          @connection(key: "CommentsContainer_comments", filters: []) {
          edges {
            id
          }
        }
      }
    `
  },
  {
    direction: 'forward',
    getConnectionFromProps(props) {
      return props.song && props.song.comments;
    },
    getFragmentVariables(prevVars, totalCount) {
      return {
        ...prevVars,
        count: totalCount
      };
    },
    getVariables(props, { count, cursor }, fragmentVariables) {
      return {
        count,
        cursor,
        id: props.song.id
      };
    },
    query: graphql`
      query CommentsContainerQuery($id: ID!, $count: Int!, $cursor: String) {
        song(id: $id) {
          ...CommentsContainer_song
        }
      }
    `
  }
);
```

**Comment by sibelius** [comment]
you can use a refetch container like in this blog post https://medium.com/entria/relay-modern-pagination-using-refetch-container-editing-a07c6b33ae4e

@MartinDawson is this problem solved? can we close this?

**Comment by MartinDawson** [comment]
@sibelius Yes. Thanks.

**Comment by puchm** [comment]
Hi,
I am quite late to the party but I was wondering whether it was possible to somehow query all of the nested objects, in this case the comments. E.g. how could I build a component that searches all comments in all songs that are currently in the Relay cache? I don't want to perform another query, just want to run a function on everything that is already there.

I know the example sounds a bit weird but that is since I adapted to your case.

FYI my case is as follows:
I have a table that uses nested pagination for rows and columns. I want to build a selection component for that where you can drag a box and select the cells inside. The problem is that I don't have all of the data in the root component but just the pagination fragments. 
E.g. my root table component only knows about all of the rows there are and each of the row components only knows about it's cells. How can I find out which cells are inside the box I am drawing?
