### ISSUE TITLE
Relay-classic search not working

### ISSUE THREAD

**Issue by CarlRosell** [facebook/relay#2236]
Hi, I'm in the middle of upgrading some apps to relay-modern and trying to find relay-classic documentation. But all the relay-classic search results have been (re)moved. 

It looks like this part is missing from the results `/en/classic/classic-`

**Comment by varunarora** [comment]
+1

Even search engine links to Relay's documentation are broken. In my case, I was specifically looking to read up on .forceFetch

**Comment by kassens** [comment]
We're no longer supporting relay classic, maybe Google/Duckduckgo are able to search the arhived docs!

**Comment by varunarora** [comment]
@kassens That is made very clear by your team, but as a good practice in open source, and out of respect for your early adopters, it is only right to keep maintaining historical documentation. How do you think people who jumped in immediately after that F8 talk and investing 10s of hours tweaking their apps for Relay Classic would feel now?

**Comment by sibelius** [comment]
@varunarora you can check all docs versions here

https://facebook.github.io/relay/en/versions.html

is this good enough?

**Comment by varunarora** [comment]
My apologies, I spoke too soon. Yes, it works @sibelius. I think originally I was concerned only about the search being broken, but got carried away after seeing @kassens's comment.
