### ISSUE TITLE
A console warniing

### ISSUE THREAD

**Issue by wellorange** [facebook/relay#2239]
This is warning from the console：
webpack-internal:///2:45 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div data-reactid="
 (server) <div data-reactid="

This is code ：
import React from 'react'
import {render} from 'react-dom'
import {QueryRenderer,graphql} from 'react-relay'
import {
  Environment,
  Network,
  RecordSource,
  Store,
} from 'relay-runtime';

import Menu from './components/menu'

function fetchQuery(
  operation,
  variables,
) {
  return fetch('http://localhost:1234', {
    method: 'POST',
    mode:"cors",
    headers: {
     // 'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query: operation.text,
      variables,
    }),
  }).then(response => {
    return response.json();
  });
}

const modernEnvironment = new Environment({
  network: Network.create(fetchQuery),
  store: new Store(new RecordSource()),
});

render(
    <QueryRenderer
    // cacheConfig={force:true, rerunParamExperimenta:{},poll:20,metadata:{a:"a"}}
    // dataFrom={}
    query={graphql`
    query appQuery {
      user {
        name
        age
        number
      }
    }
  `}
    environment={modernEnvironment}
    variables={{a:"a"}}
    render={({error, props}) => {
      if (props) {
        return (<Menu/>)
      } else {
        return <div>Loading</div>
      }
    }}/>,
    document.getElementById('root')
  );

**Comment by sibelius** [comment]
this is not a problem with relay
