### ISSUE TITLE
[relay-compiler] graphql 0.12 schema update

### ISSUE THREAD

**Issue by andrewBalekha** [facebook/relay#2240]
In new version of graphql comment format has been changed
*Before*
```
type Account {
  # The ID of an object
  id: ID!
}
```

*Now*
```
type Account {
  """The ID of an object"""
  id: ID!
}
```

**Comment by andrewBalekha** [comment]
As far as I understood, `relay-compiler` - was updated with graphql v0.12v 9h ago.

Probably after release it will work again.

**Comment by mortezaalizadeh** [comment]
Same happening for me, any chance the fix can be released soon? Cheers

**Comment by emjaksa** [comment]
The graphql v0.12 release notes specifies:

> To read a SDL that uses comments as descriptions, buildASTSchema(document, { commentDescriptions: true }); to write an SDL using comments as descriptions, printSchema(schema, { commentDescriptions: true }).

Try adding the new commentDescriptions option to your printSchema.

**Comment by mortezaalizadeh** [comment]
@emjaksa Thanks for your help. I added the commentDescription to the printSchema and it's still not working. Relay compiler can't recognize the new """ syntax in schema.graphql file.

**Comment by mortezaalizadeh** [comment]
@emjaksa  ignore my last comment mate, it fixed my problem. Thank you.

**Comment by andrewBalekha** [comment]
Works, Thanks @emjaksa

**Comment by Kenam18** [comment]
> The graphql v0.12 release notes specifies:
> 
> This change follows the latest updates to the spec proposal (graphql/graphql-spec#90) after a long discussion between the merits of comments vs. literals as descriptions. To ease the migration to this latest change, existing comment-descriptions can still be used by providing options to the relevant functions. To read a SDL that uses comments as descriptions, buildASTSchema(document, { commentDescriptions: true }); to write an SDL using comments as descriptions, printSchema(schema, { commentDescriptions: true }).
> 
> Try adding the new commentDescriptions option to your printSchema. Just a temp fix till relay-compiler supports literals as descriptions.

Can you please let me know the file where this has to be added?

**Comment by sibelius** [comment]
Add graphql as a dep and this will be fixed

**Comment by Kenam18** [comment]
Thank you! It's fixed.
