### ISSUE TITLE
[relay-compiler] Compiler fails to parse .graphql with new comment syntax

### ISSUE THREAD

**Issue by mike-marcacci** [facebook/relay#2251]
The `relay-compiler` is unable to parse the new multi-line comment syntax used by `printSchema` in the `graphql` package. It's pretty trivial to switch over to a JSON file (instead of .graphql) but this should probably be fixed anyhow.

Given a `schema.graphql` file containing this:

```graphql
# ...

type AreaObject implements Node, Object {
  id: ID!

  """This is the name of the area."""
  name: String

  # ...
}

# ...
```

the command `relay-compiler --src ./src --schema ./data/schema.graphql` produces:

```
ERROR:
Error loading schema. Expected the schema to be a .graphql or a .json
file, describing your GraphQL server's API. Error detail:

GraphQLError: Syntax Error GraphQL request (44:3) Expected Name, found String

43:
44:   """This is the name of the area."""
      ^
45:   name: String
```

**Comment by chadfurman** [comment]
I second this issue.  
```
Writing default
ERROR:
Error loading schema. Expected the schema to be a .graphql or a .json
file, describing your GraphQL server's API. Error detail:

GraphQLError: Syntax Error GraphQL request (5:3) Unexpected String

4: 
5:   """All input for the `acceptInvite` mutation."""
     ^
6: input AcceptInviteInput {


```

**Comment by rytakahashi** [comment]
A temporary solution besides using JSON is passing `commentDescriptions: true` to `printSchema` to revert to the previous functionality.

```javascript
printSchema(schema, {
  commentDescriptions: true,
});
```

**Comment by chadfurman** [comment]
My schema is being generated by a third-party library.  @benjie is that something we can do in postgraphile / graphile-build ?

**Comment by benjie** [comment]
You can generate it yourself using something like this:

https://gist.github.com/benjie/446380c4167edfc532a88f2034514049

**Comment by chadfurman** [comment]
Neat. A bit more complicated than would be ideal, but a solution none the less. Thank you :)

**Comment by pranaygp** [comment]
Now that https://github.com/facebook/graphql/pull/90 has been merged, I think it's all the more important this gets addressed ASAP

**Comment by alloy** [comment]
@jstejada This can be closed.

**Comment by Kenam18** [comment]
> 1.5.0-rc.1
 I have updated my relay-compiler with a version 1.7.0 but still facing the same issue. Any suggestions?
