### ISSUE TITLE
Optimistic Updater setting nested connection

### ISSUE THREAD

**Issue by MartinDawson** [facebook/relay#2266]
I have a fragment like this:

```js
  fragment repliesContainer_comment on Comment
  @argumentDefinitions(
    count: { type: "Int", defaultValue: 0 }
  ) {
    commentId
    id
    replies(
      first: $count
      after: $cursor
    ) @connection(key: "repliesContainer_replies") {
      totalCount
      edges {
        cursor
        node {
          commentId
          ...commentContainer_comment
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
```

I am trying to set the `replies` to a new empty connection in the optimistic updater so that when accessing `replies.edges` further down the tree it doesn't throw an undefined error on `replies`.

Mutation:

```js
  mutation commentMutation(
    $cursor: String
    $input: SaveCommentInput!
  ) {
    comment(input: $input) {
      comment {
        ...commentContainer_comment
        ...repliesContainer_comment
      },
    }
  }
```

Optimstic updater:

```js
    (store) => {
      const root = store.getRoot();
      const comment = store.create(`newComment_${tempID += 1}`, 'comment');
      const replies = store.create(`newReplies_${tempID += 1}`, 'replies');

      replies.setLinkedRecords([], 'edges');

      comment.setValue(tempID * -1, 'commentId');
      comment.setValue(body, 'body');
      comment.setLinkedRecord(replies, 'replies');

      sharedUpdater(store, audio, comment);
    },
```

Replies is always undefined though in my React components, everything else works fine. How do we set the `replies` connection to an empty one?

**Comment by Nutelac** [comment]
Any luck with this?

**Comment by gpbaculio** [comment]
I am also having this problem, can't find solution after hours, anyone help?

**Comment by sibelius** [comment]
Check this https://medium.com/entria/relay-modern-optimistic-update-a09ba22d83c9
and this https://medium.com/entria/wrangling-the-client-store-with-the-relay-modern-updater-function-5c32149a71ac

also check relay store docs https://relay.dev/docs/en/relay-store

try to change to 

`@connection(key: "repliesContainer_replies", filters: [])`

so it won't generate more connections then you need

ConnectionHandler can help https://relay.dev/docs/en/relay-store#connectionhandler

this question is better suited to stackoverflow

**Comment by gpbaculio** [comment]
somehow I am getting undefined on the connection field, hope somebody help [Stackoverflow](https://stackoverflow.com/questions/57006651/how-to-optimisticresponse-a-connection-property-in-relay-modern-mutation)
