### ISSUE TITLE
Changing a nested variable not triggering refetch

### ISSUE THREAD

**Issue by grydstedt** [facebook/relay#227]
When I change the the values of a nested input object, a trigger to refetch doesn't happen?
```
var filter = {sort: 1};
this.props.relay.setVariables({
  first: this.props.relay.variables.first,
  filter: filter,
});
// Refetch happens.

// Later
filter.sort = 2;
this.props.relay.setVariables({
  first: this.props.relay.variables.first,
  filter: filter,
});
// No refetch
```

**Comment by grydstedt** [comment]
Adding a `cache` variable seems to work.

```
this.props.relay.setVariables({
  first: this.props.relay.variables.first,
  filter: filter,
  cache: JSON.stringify(filter)
});
```

**Comment by josephsavona** [comment]
The reason this doesn't work is that `filter.sort = 2` *mutates* the value of a variables. Note that variables should be treated [as if they were immutable](http://facebook.github.io/relay/docs/api-reference-relay-container.html#variables):

> Never mutate this.props.relay.variables directly as it will not trigger data to be fetched properly. Treat this.props.relay.variables as if it were immutable, just like props.

```javascript
// anti-pattern:
filter.sort = 2;
this.props.relay.setVariables({
  first: this.props.relay.variables.first,
  filter: filter,
});

// supported:
filter = {...filter, sort: 2}; // new variable
this.props.relay.setVariables({
  first: this.props.relay.variables.first,
  filter: filter,
});
```

**Comment by grydstedt** [comment]
Thank you for clarifying! I read that but didn't realize that setVariables needed to be passed a new immutable object as well, just directly modifying `relay.variables`
