### ISSUE TITLE
Remove implicit dependencies in favour of explicit imports

### ISSUE THREAD

**Issue by k15a** [facebook/relay#2277]
Hey,

we're currently investigating if we want to use a GraphQL client and if Relay would be a great fit. We found that Relay is a great fit but I am still a bit worried because many GraphQL names and keys are passed implicitly between different files. Let me illustrate what I mean based on the Todo example:

1. Fragment names are not imported and therefore implicitly required. Also, they have to have a specific name because of `relay/compat` and they have to be unique in the whole project.

If we take a look at [TodoList.js#L63](https://github.com/relayjs/relay-examples/blob/master/todo/js/components/TodoList.js#L63) from the todo example we can see that we are using two fragments of the Todo component:

```js
export default createFragmentContainer(TodoList, {
  viewer: graphql`
    fragment TodoList_viewer on User {
      todos {
        edges {
          node {
            ...Todo_todo,
          },
        },
      },
      ...Todo_viewer,
    }
  `,
});
```
I think a better solution would be that fragment containers export the name / reference of their fragments as well so I can import it and use it.

Example:
```js
import Todo from './Todo'

export default createFragmentContainer(TodoList, {
  viewer: graphql`
    fragment TodoList_viewer on User {
      todos {
        edges {
          node {
            ...${Todo.todo}
          },
        },
      },
      ...${Todo.viewer},
    }
  `,
});
```

The keys would match the keys of the object which is passed as the second argument to createFragmentContainer. This would force the user to use the object notation.

This would also solve the problem that the names have to be unique because the relay compiler could create a fragment name based on a hash or the filepath.

2. ConnectionHandler.getConnection is using the connection name from a different file implicitly in [RemoveTodoMutation.js#L35](https://github.com/relayjs/relay-examples/blob/master/todo/js/mutations/RemoveTodoMutation.js#L35)

This could be solved similarly. The only difference is that AFAIK the connection refers to the key in a `@connection` directive. Not sure how a new API could look like but something more explicit would be better.

**Solved Problems with an explicit API:**

I see 2 problems which are solved with an explicit API.
1. Fragments and connection don't have to be unique in the whole project.
2. The code is more maintainable because we don't have any implicit dependencies between different files and you can directly see where something is coming from.

**The reasons I know why the current API is designed in this way are:**

1. `relay/compat` needs a specific fragment name. This could be solved with a flag on the compiler which tells him that I don't want Relay classic compatibility.
2. graphql template strings are not allowed to have interpolations because it makes the compiler easier. I don't know the compiler internals but I think that chasing down the reference to the fragment container should not be impossible.

I would like to start a discussion why the current API is designed in that way and if we could change it to a more explicit API.

**Comment by robrichard** [comment]
@k15a take a look at this PR that I opened some time ago: https://github.com/facebook/relay/pull/2064

It was a similar approach to to solve the issues you described but it was not well received by the Relay team.
