### ISSUE TITLE
connection field with id sets edges to null

### ISSUE THREAD

**Issue by renehauck** [facebook/relay#2278]
Hi,

I have this definition:
`export const PushMessageConnection = connectionDefinitions({ nodeType: PushMessageSchema})`

and this query in a "RefetchContainter"

```
       pushNotificationHistory(input:$input){    
                edges{
                        node{
                        _id
                        id
                        title
                        createdAt
                        message
                    }
                }
        }  
```
with this result:

![screenshot_20180111_122010](https://user-images.githubusercontent.com/3898144/34823202-dbda62ba-f6c9-11e7-86f7-15eccfa49f21.png)

Now I would like to add an id field. For this I have updated the definition:

`connectionDefinitions({ nodeType: PushMessageSchema ,connectionFields:{id:globalIdField(PushMessageListIdField)}})`

and the query

```
       pushNotificationHistory(input:$input){    
                id
                edges{
                        node{
                        _id
                        id
                        title
                        createdAt
                        message
                    }
                }
        }  
```

Now I have an id field, but the edges-field is null.

![screenshot_20180111_121510](https://user-images.githubusercontent.com/3898144/34823397-7e139dee-f6ca-11e7-87fb-90d25f057027.png)

If I'm doing something wrong, is this a relay bug, or is it a graphql-relay bug?

Thank you for your work :grinning:

**Comment by sibelius** [comment]
check this https://github.com/entria/graphql-mongoose-loader

I think this is a bug in your code

**Comment by renehauck** [comment]
Thanks for the link, but we use DynamoDb. :wink: 

> I think this is a bug in your code

I'm not sure, but even GraphQl gives me that result:

Query:
```
      pushNotificationHistory(input: {page: 0}) {
        id
        edges {
          node {
            title
          }
        }
      }
```

Result:
```
        "pushNotificationHistory": {
          "id": "UHVzaE1lc3NhZ2VMaXN0SWRGaWVsZDo=",
          "edges": [
            {
              "node": {
                "title": "Hello"
              }
            },
            {
              "node": {
                "title": "Hello World"
              }
            },
            {
              "node": {
                "title": "Hello World2"
              }
            }
          ]
        }
```

**Comment by sibelius** [comment]
all node needs an unique id

**Comment by renehauck** [comment]
They have, 

Query
```
 pushNotificationHistory(input: {page: 0}) {
        id
        edges {
          node {
            id
          }
        }
      }
```

Result
```
 "pushNotificationHistory": {
          "id": "elwv8mrjcagob5y",
          "edges": [
            {
              "node": {
                "id": "UHVzaG1lc3NhZ2U6UHVzaE1lc3NhZ2VfZWx3dm94eGpjYWNxY3Rs"
              }
            },
            {
              "node": {
                "id": "UHVzaG1lc3NhZ2U6UHVzaE1lc3NhZ2VfZWx3dm94eGpjYWN2aXE1"
              }
            },
            {
              "node": {
                "id": "UHVzaG1lc3NhZ2U6UHVzaE1lc3NhZ2VfZWx3djNkcWpjYWQ1NW1q"
              }
            }
          ]
        }
```
But I think it's a bug of "graphql-relay".
 I changed the line:

`connectionDefinitions({ nodeType: PushMessageSchema ,connectionFields:{id:globalIdField(PushMessageListIdField)}})`

 with the line:

`connectionDefinitions({ nodeType: PushMessageSchema ,connectionFields:{id:{type: GraphQLID,resolve:()=>uniqid()}}})`

 and it works.
I therefore close the problem but would keep it up to date.
