### ISSUE TITLE
Get loading state of refetches

### ISSUE THREAD

**Issue by grydstedt** [facebook/relay#228]
Is there a way to get information regarding refetches when a fetch is triggered using `setVariables`. Neither `renderFetched`, `renderLoading`, or `onReadyStateChange` is called. The use case would be to show some loading spinner or similar when fetching more edges in a connection.

**Comment by josephsavona** [comment]
The props you mentioned are on `<RelayRootContainer>`. In this case, you're changing variables for a Container. The `this.props.relay.setVariables()` function accepts an [`onReadyStateChange` argument](http://facebook.github.io/relay/docs/api-reference-relay-container.html#setvariables) that you can use to determine when changed variables are available:

```javascript
loadMore() {
  this.props.relay.setVariables({
   count: this.props.relay.variables.count + 5,
  }, readyState => {
    if (readyState.done) { /* all data loaded */ }
    else if (readyState.error) { /* error occurred */ }
    else { /* can ignore partial/aborted states */ }
  });
```

**Comment by grydstedt** [comment]
Awesome, thank you!
