### ISSUE TITLE
Include `.flow` file definitions in package

### ISSUE THREAD

**Issue by nodkz** [facebook/relay#2284]
@kassens @leebyron Maybe put `.flow` files to the built package while 1.5.0 in RC phase for better DX (static analysis and autocompletion in IDE)?

Like it did with `graphql-js` - https://unpkg.com/graphql@0.12.3/type/

**Comment by steida** [comment]
cc @calebmer

**Comment by kikoseijo** [comment]
+1

**Comment by zth** [comment]
This would indeed be wonderful! But are the issues around generating these resolved? I think @leebyron mentioned some non-trivial issues with doing that in another issue.

**Comment by jstejada** [comment]
Going to merge this into #1758
