### ISSUE TITLE
QueryRenderer partial caching with STORE_THEN_NETWORK

### ISSUE THREAD

**Issue by graingert** [facebook/relay#2296]
I've got an app that uses:
```
    <App>
       <NavBar data={data}/>
       {children}
      <Footer>
    </App>
```
and I've got two routes:
```
    <App><Foo /></App>
    <App><Bar /></App>
```
with a query renderer foo Foo:
```
    query on RootQuery {
       viewer {
           ...NavBar_data
           ...Foo_data
       }
    }
```
and Bar:
```
    query on RootQuery {
      viewer {
        ...NavBar_data
        ...Bar_data
      }
    }
```

I'm currently using dataFrom="STORE_THEN_NETWORK" but that only works when the full query is available. I want it to work with the partial data already in the store.

is there any way to get Relay QueryRenderer to start rendering with the data already available in the store
when navigating from Foo to Bar
eg the NavBar_data is already in the store
but Bar_data is not
I'd like it to render twice, once with the NavBar_data and once with the Bar_data and the NavBar_data at once
eg the NavBar is safe to be stale

**Comment by jstejada** [comment]
Hey @graingert, unfortunately we don't currently support a way to render partial data, and it is not something we're currently working on, but might consider in the future. If you're interested it might be worth trying to write a PR for it!
Thanks!
