### ISSUE TITLE
Bad RelayNodeInterface Mock

### ISSUE THREAD

**Issue by yungsters** [facebook/relay#230]
The `RelayNodeInterface.js` mock is currently requiring a module that does not exist: https://github.com/facebook/relay/blob/master/src/__forks__/interface/__mocks__/RelayNodeInterface.js#L18

**Comment by yungsters** [comment]
This will be fixed, but no one is awake right now to accept my internal diff. It will be fixed first thing in the morning. (Just wanted to file this task to admit awareness.)

**Comment by wincent** [comment]
Just accepted your internal diff.

**Comment by yungsters** [comment]
Closed by cf8ecd462ef37663d3d6814740552b7d524b63da.
