### ISSUE TITLE
Is variables a required prop in QueryRenderer?

### ISSUE THREAD

**Issue by AugustinLF** [facebook/relay#2300]
Hey folks,
While adding react-relay types to my app (from flow-typed, which mirrors the one from this repo), I discovered that the `variables` prop of `QueryRenderer` is typed as [not optional](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayQueryRenderer.js#L59). However, it does perfectly work if you don't provide it. I do believe that the docs consistently pass it (an empty object when the query doesn't have any variables).

Is the prop required on purpose? I could update my app code and pass empty objects as variables everywhere, to be more in line with the design of `react-relay`, but if it is not necessary, I'd rather make a PR to update the typings here :)

**Comment by alloy** [comment]
The reason this is not optional is because if it were then there's no way to enforce required variables when you do have them. i.e. passing `undefined` as variables object would be considered valid too.
