### ISSUE TITLE
Compiled classic queries still included in bundle with relay-modern

### ISSUE THREAD

**Issue by amkoehler** [facebook/relay#2301]
Hello,

I was running some tests with Chrome's code coverage tool and notice a large amount of code generated by relay was showing up as unused. If you haven't used the tool before, the results look something like this:

![](https://i.imgur.com/Hl477Wu.jpg)

Red is unused and green means used. This specific chunk of code stood out to me, because it looks like the classic queries are still getting included in the bundle even though we're fully on relay modern. In this case the modern query shows up as green because it's actually getting used on the page. Nowhere in our application do we use `react-relay/compat` and our babel-plugin-relay configuration does not have `compat: true`. Are we missing a configuration option somewhere that ensures the classic queries don't get compiled? Or, if those are there intentionally I would be curious why they're still in the bundle if we're not using compatibility mode.

**Comment by alloy** [comment]
Here’s an example from our app where we only use modern, which _only_ includes the artifact `require` that in your example is inside the `modern` object. So what you’re seeing should not be happening if you’re only on modern mode.

```js
exports.default = (0, _reactRelay.createFragmentContainer)(Biography, {
  artist: function artist() {
    return require(978                                       ); // 978 = ./__generated__/Biography_artist.graphql
  }
});
```

_Note that our app is on Relay 1.3.1, so if there has been a regression it might have happened after that version._

**Comment by amkoehler** [comment]
Your comment led me to remember babel with webpack's babel-loader caches things pretty aggressively, and this has caused issues for us in the past when making babel config changes. I very recently removed the `{ compat: true }`, so after clearing out my `node_modules/.cache/babel-loader` it now works as expected. Thanks for the help!

I should have noted that we're on version v1.4.1 of all the relay packages.

**Comment by alloy** [comment]
Glad it helped 👍
