### ISSUE TITLE
[writeRelayUpdatePayload] Show different error depending on whether a required field was subtracted out or simply not returned by the server

### ISSUE THREAD

**Issue by sgwilym** [facebook/relay#231]
I've got a mutation that creates a new Leaf in a schema kind of like this:

```
Trunk {
  Branches {
    Leaves
  },
  Leaves
}
```

The fat query in my mutation looks like this:

```
fragment on CreateLeafPayload {
  trunk { leaves },
  newTreeLeafEdge,
  branch { leaves },
  newBranchLeafEdge
}
```

and the configs look like this: 

```js
{
  type: 'RANGE_ADD',
  parentName: 'branch',
  parentID: this.props.branch.id,
  connectionName: 'leaves',
  edgeName: 'newBranchLeafEdge',
  rangeBehaviors: {
    '': 'append'
  }
},
{
  type: 'RANGE_ADD',
  parentName: 'trunk',
  parentID: this.props.trunk.id,
  connectionName: 'leaves',
  edgeName: 'newTrunkLeafEdge',
  rangeBehaviors: {
    '': 'append'
  }
}
```

Executing this query throws a warning in the console:
```
writeRelayUpdatePayload(): Expected response payload to include the newly created edge `newUserComicEdge` and its `node` field. Did you forget to update the `RANGE_ADD` mutation config?
```

The mutation query received by the server doesn’t have the `trunk { id }` or `newTrunkLeafEdge` fields, so the GraphQL server doesn’t return them. I know Relay intersects the mutation query with a 'tracked query' — maybe something is going wrong there?

**Comment by sgwilym** [comment]
This might not be anything to do with `RANGE_ADD`, as I'm now getting a similar problem in an extremely simply `FIELDS_CHANGE` mutation: Relay never queries for `updatedObject { updatedField }`.

**Comment by yungsters** [comment]
> I found the cause of this (#232), but the problem in my first comment still stands.

Thanks for investigating and reporting. If #232 fixes your problem, which remaining problem are you referring to in the first comment?

**Comment by sgwilym** [comment]
The problem is that the mutation doesn’t include the fragments for `trunk` or `newTrunkLeafEdge`, so the returned payload is missing them to, meaning I get the error: 

```writeRelayUpdatePayload(): Expected response payload to include the newly created edge `newUserComicEdge` and its `node` field. Did you forget to update the `RANGE_ADD` mutation config?```

**Comment by sgwilym** [comment]
Just to take this out of the abstract a bit, I've made a gist with the actual mutation, where I'm calling it from, the resulting query + variables, and the returned payload: https://gist.github.com/sgwilym/77191368cf1885a289e2

**Comment by sgwilym** [comment]
Thanks to the help of @devknoll, I found out this issue is because nowhere else in the app is `user { comics }` being queried, so the query from the mutation is being subtracted. I guess my only remaining confusion then is whether Relay should be throwing errors like the one posted above when it doesn't receive the corresponding fragment for a query that itself subtracted.

**Comment by josephsavona** [comment]
@sgwilym Good point - the error could be more informative and check whether the field was in the query (which means its a server error to not include in the response) or if it isn't in the query (which means it was subtracted and the message could tell you the field isn't being queried anywhere).

**Comment by bmcmahen** [comment]
I spent quite a while debugging the same thing, too. It was the same issue that @sgwilym was having; i.e., the app wasn't querying the relevant fields.  A more helpful warning message might be useful here.

**Comment by xymostech** [comment]
I'm running into this issue as well. In my case, I'm trying to use the returned data in the mutation's `onSuccess` (in particular, I'm routing to a page with the returned node's `id`), so I need the data to be returned, even if the data isn't being queried elsewhere in the app.

Is there a (good) way to force the fields to be put in the query, even if they're not used? I could do something silly like add a dummy `query viewer { books(first: 1) { edges { nodes { id } } } }` to ensure that the fields are used, but that doesn't seem great.

**Comment by steveluscher** [comment]
I wrote about how to use the `REQUIRED_CHILDREN` config to force certain fields to be made available to your `onSuccess` handler, @xymostech: http://stackoverflow.com/questions/32539189/how-to-get-the-id-of-a-new-object-from-a-mutation

See also #237.

**Comment by steveluscher** [comment]
The task. Given a `RANGE_ADD` mutation config:

1) If Relay never queries for the new edge because they were eliminated during the intersection of the tracked and fat queries, explain that there's a client-side problem and how to fix it (namely to make sure the parent/connection is used – ie. tracked – in your app)
2) If the server never responds with the newly created edge despite having been queried for it, explain that the problem is on the server side.

**Comment by xymostech** [comment]
@steveluscher Awesome! Looks like #237 also addresses the fact that `REQUIRED_CHILDREN` is undocumented so far. :+1:

**Comment by josephsavona** [comment]
merging into #542
