### ISSUE TITLE
Relay docs on fragments currently incorrect

### ISSUE THREAD

**Issue by carlosdp** [facebook/relay#2315]
The quick start guide that is currently published on the Relay website has incorrect code which caused me a ton of confusion. Specifically, it passes in `props.user.userTodoData` to the TodoList component in the Rendering Fragments section, when it should be `props.viewer`.

It looks like the docs are fixed in `master`, is it possible to get the updated doc published? Even if the docs in master refer to future features right now, I think it'd be worth pulling the quickstart doc from master with these fixes into the currently published doc to avoid this for new users.

**Comment by jstejada** [comment]
@carlosdp thanks for bringing this up, and sorry for the confusion! we'll update the latest published version of the docs soon (probably along with 1.5.0). Thanks!
