### ISSUE TITLE
support for graphql-js 0.13.0 (SDL breaking changes)

### ISSUE THREAD

**Issue by galki** [facebook/relay#2323]
It appears that relay [has support] for the latest graphql-js version (0.13.0) but it's not released yet, causing problems like https://github.com/graphql/graphql-js/issues/1246.

**Comment by alloy** [comment]
I don’t believe there have been breaking API changes iirc, so, in case you use yarn, you could use the [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) feature to override the dependency and force 0.13.

**Comment by alloy** [comment]
Relay [1.5.0](https://github.com/facebook/relay/releases/tag/v1.5.0) has been published and fixes this.
