### ISSUE TITLE
fetchQuery

### ISSUE THREAD

**Issue by steida** [facebook/relay#2330]
```import { fetchQuery } from 'react-relay';```

It isn't typed because it's unstable API? fetchQuery is super awesome with Next.js for true SSR.

**Comment by jstejada** [comment]
Hi @steida, what is your question specifically? Currently `fetchQuery` is undocumented, and we aren't exporting flow types in our package (#1758), so the flow types aren't available.

In the future. I would suggest opening issues that point to a specific problem and hopefully have an actionable outcome. It would also be useful if the title of the issue had a name that conveyed more meaning into what the problem or question is.

Thanks!

**Comment by alloy** [comment]
I’d add that `fetchQuery` is not an unstable API afaik, we’ve discussed documenting it.
