### ISSUE TITLE
[Doc] fetchQuery missing operationName

### ISSUE THREAD

**Issue by djeeg** [facebook/relay#2335]
I am using express-graphql to handle relay requests, have created an extensions handler to log and respond to the requests with extra tracing metrics, and have noticed that the operationName is null.

Digging into express-graphql
https://github.com/graphql/express-graphql/blob/d28fea332eefa9747fde0fdbe85542f3fef74774/src/index.js#L383

Then back into relay
https://github.com/facebook/relay/blob/master/docs/Modern-NetworkLayer.md

It looks like the fetchQuery function is responsible for passing the operationName:

Should it be like this?
```
body: JSON.stringify({
    query: operation.text, // GraphQL text from input
    variables,
    operationName: operation.name,
}),
```

Recently switched from apollo-server-express and I am sure I remember operationName being populated. Apollo may have been extracting the operationName from the query. Not totally sure.

**Comment by sibelius** [comment]
you can do in your network layer

```jsx
name: request.name,
operationName: request.name,
```

request is the same as operation
