### ISSUE TITLE
[Modern] [RelayCompiler] [Feature Request] Parse <script> in HTML-like formats

### ISSUE THREAD

**Issue by ntkme** [facebook/relay#2339]
Cheers,

I just created [vue-relay](https://github.com/ntkme/vue-relay) for Vue.js, which closely reassemble react-relay's APIs.

[Vue.js single-file components](https://vuejs.org/v2/guide/single-file-components.html) embed JavaScript in `<script>` tags just like HTML does, and apparently `relay-compiler` does not understand any HTML-like formats.

``` sh
relay-compiler --src src --schema schema.graphql --extensions js vue
```

The command above would simply fail. As a workaround, I have to `export` `graphql` template literals from `.js` files, then `import` them into `.vue` files. It works, but also breaks the idea of single-file components.

It would be great if `relay-compiler` can handle HTML-like formats with embedded JavaScript code.

**Comment by ntkme** [comment]
It seems #2293 would solve this.

**Comment by sibelius** [comment]
@ntkme can you do this using a language plugin?

**Comment by ntkme** [comment]
@sibelius The problem is that in .vue file you can possibly have either javascript, or typescript, or any other thing that translates to js. With that, it messes up the idea of language plugin interface.

For .vue files:
1. Extract the <script>.
2. Determine the language of <script> (e.g. can be `<script lang="ts">`, etc.).
3. If it's anything that's not JavaScript, transpile to JavaScript.
4. Now find the `graphql` template literal and do work.

With step 3 being a requirement, I believe a proper solution would be something that sort of works like `babel`, where you can apply a chain of transpilation. This way, the existing typescript language plugin can be used to do the work of step 3 and 4, and we just need to implement something that does step 1 and 2 and pass the rest of work to typescript plugin.

If we don't do that, then the vue language plugin would be really horrible, that to support any nested script language, we have either put a messy wrapper on top of typescript plugin, or we have to duplicate the work that typescript plugin already does. Either way it will be pretty bad.

With the idea that we should allow a chain of plugins to do multiple transpilation, however, it does not need to be as good as babel. Just introducing a pre-language-plugin interface would definitely cover most of the use case.

**Comment by sibelius** [comment]
I think the best approach is to have `vue plugin` to handle part 1 and 2 (preprocessing) and pass the result of it to functions/methods of `typescript plugin`

`typescript plugin` could export some functions to be consumable to other plugins

**Comment by alloy** [comment]
@sibelius I think that @ntkme is referring to that by:

> If we don't do that, then the vue language plugin would be really horrible, […], we have either put a messy wrapper on top of typescript plugin

Nonetheless, @ntkme could we perhaps start with that and see how horrible it really is and then iterate from there?
