### ISSUE TITLE
mutation query doesn't consider interfaces

### ISSUE THREAD

**Issue by davide-ganito** [facebook/relay#234]
Hello,
I have the following schema
```
interface CompanyInterface {
  id: ID!
  name: String
  customers: [CompanyCustomer] 
}

type CompanyCustomer implements Node {
  id: ID!
  company: CompanyInterface
}

type Market implements Node, CompanyInterface {
  id: ID!
  name: String
  customers: [CompanyCustomer]
  balanceProductMarket: Float
}
```

the following fragment on a Component:

```
fragment on CompanyCustomer @relay(plural: true) {
  company{
    ... on Market {
      balanceProductMarket
    },
    id,
    name,
    marketArea,
    paymentTerms
  },
  priority
}
```

and the following fatQuery for the AddCustomerMutation:

```
fragment on AddCustomerPayload {
  firm
}
```

The first fetch query is perfect
```
query Firm{user{..._28fabdeb23}} fragment _2b8337a7c3 on Market{id,balanceProductMarket} fragment _2ababa9b06 on CompanyCustomer{company{name,marketArea,paymentTerms,id,..._2b8337a7c3},priority,id} fragment _2c944cb380 on CompanySupplier{company{name,marketArea,paymentTerms,id},priority,id} fragment _2df02dde49 on Firm{id,game{id}} fragment _2973307868 on Firm{name,marketArea,sourcingStrategy,customers{id,..._2ababa9b06},suppliers{id,..._2c944cb380},game{id,name},availableNewCustomers{id,name},id,..._2df02dde49} fragment _28fabdeb23 on User{_gamece442bd8:game(id:"R2FtZTo1NWU4NjM5NmE5ZWJjZjY4MzYzYWUxNjE="){id,_firm2227d3e8:firm(id:"RmlybTo1NWU4NjM5N2E5ZWJjZjY4MzYzYWUxNzA="){name,id,..._2973307868}},id}
```

but the mutation query doesn't consider that Market implements Company and produce this query:
```
mutation AddCustomer($input:AddCustomerInput!){addCustomer(input:$input){clientMutationId,firm{availableNewCustomers{id,name},customers{company{balanceProductMarket,id,marketArea,name,paymentTerms},id,priority},game{id,name},id,marketArea,name,sourcingStrategy,suppliers{company{id,marketArea,name,paymentTerms},id,priority}}}}
```

Am I doing something wrong?

**Comment by yungsters** [comment]
What does your `AddCustomerMutation` look like? And can you provide some more detail about what is wrong with the mutation query you pasted?

**Comment by davide-ganito** [comment]
The `AddCustomerMutation` add a new `Custumer` to the `Firm` curstomer's list and return the modified Firm.
Every `Custumer` has a `company` field of type `CompanyInterface`.
I have 3 kinds of company: `Marker`, `Supplier`, `Firm`.

In my Component I specify, with an inline fragment, which fields I want to fetch from  the `Market`:
```
company{
          ... on Market {
            balanceProductMarket
          },
          id,
          name,
          marketArea,
          paymentTerms
        }
```
but i have this mutation query:
```
company{
  balanceProductMarket, // this field is not defined on CompanyInterface
  id,
  marketArea,
  name,
   paymentTerms
}
```

**Comment by josephsavona** [comment]
@yungsters This could be caused by tracked queries being flattened. These should be unflattened when the mutation is constructed (via `refragmentRelayQuery`) - not sure why that isn't taking effect here.

**Comment by davide-ganito** [comment]
I have noticed that when calling the `buildMutationFragment` by `buildFragmentForField` the `mutatedFields` param has the node corresponding to `balanceProductMarket` recorded as `RelayQueryField` at the same level of the others `CompanyInterface` fields.

Inside the `refragmentRelayQuery`it is marked as 'RelayQueryFragment` instead.

This could be of any help?
Thx!

**Comment by steveluscher** [comment]
Did b16c384 take care of this, @josephsavona, or is there more to do here?

**Comment by josephsavona** [comment]
@steveluscher yes, this has been resolved.
