### ISSUE TITLE
Should we use  .graphql files everywhere?

### ISSUE THREAD

**Issue by steida** [facebook/relay#2340]
It seems it's a must for client-only schema extensions.

It seems Nuclide provides a nice DX for .graphql files. https://nuclide.io/docs/languages/graphql

**Comment by jstejada** [comment]
Hi @steida, I'm not sure what your specific question is. What do you mean by using them everywhere?
You can use .graphql files to define client-schema extensions. 
Keep in mind that client-schema extensions are currently undocumented.
