### ISSUE TITLE
When developer accidentally forged to add explicit check for connection existence

### ISSUE THREAD

**Issue by steida** [facebook/relay#2344]
... and the third arg is wrongly defined.

![screen shot 2018-02-23 at 02 59 07](https://user-images.githubusercontent.com/66249/36574352-aa820b94-1845-11e8-8a9d-1d63e7208a30.png)

This is DX from hell.

![screen shot 2018-02-23 at 03 00 22](https://user-images.githubusercontent.com/66249/36574373-d01410dc-1845-11e8-8a1b-2d9b9885ef32.png)

Sure I am rude. For a reason. Accept it or do not do OSS at all. Thank you.

**Comment by steida** [comment]
I hope you will appreciate those issues because I care about Relay.

**Comment by sibelius** [comment]
Flow won’t get this ?

**Comment by steida** [comment]
No.

**Comment by jstejada** [comment]
Thanks for bringing this up @steida. We'll see if we can improve that API; hopefully when we export flow types in the npm package (#1758) this can improve.

I'm going to go ahead and close this issue for now given that it isn't actionable. Thanks!
