### ISSUE TITLE
[relay-compiler] After upgrade to 1.5.0, it throws ERROR: Type "Address" already exists in the schema. It cannot also be defined in this type definition.

### ISSUE THREAD

**Issue by nightspirit** [facebook/relay#2346]
In our schema.graphql, we define a type Address for common address 
```graphql
type Address {
  city: String
  latitude: Float
  longitude: Float
  state: String
  staticMap: Image
  street: String
  zip: String
}
```
It works when we are using 1.4.1 without issues. But today when we upgrade to 1.5.0 (along with relay-runtime/react-relay) we no longer able to compile the static queries.

react-compiler keeps throwing ERROR:
Type "Address" already exists in the schema. It cannot also be defined in this type definition.

After we downgrade to 1.4.1, the compiler works again.

**Comment by sibelius** [comment]
is there only one type Address?

**Comment by nightspirit** [comment]
@sibelius  Yes, there is only one type Address in the schema.graphql file.

**Comment by sibelius** [comment]
could u create a repo to reproduce this?

**Comment by obibring** [comment]
@sibelius I'm seeing the same issue. It's not clear what needs to be done to reproduce it, given that the error message is incorrectly stating that the defintion already exists. When I run the compiler with `--verbose`, I get:
```
ERROR:
Type "< MyTypeName >" already exists in the schema. It cannot also be defined in this type definition.
From: CodegenRunner.write
    at extendSchema (.../node_modules/relay-compiler/node_modules/graphql/utilities/extendSchema.js:82:17)
    at .../node_modules/relay-compiler/bin/relay-compiler:4897:13
    at Object.run (.../node_modules/relay-compiler/bin/relay-compiler:481:31)
    at Object.extendASTSchema (.../node_modules/relay-compiler/bin/relay-compiler:4885:34)
    at .../node_modules/relay-compiler/bin/relay-compiler:7613:40
    at Generator.next (<anonymous>)
    at step (.../node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at .../node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (.../node_modules/core-js/library/modules/_export.js:35:28)
```

Upon inspecting the source code, I see that line `4897` of `node_modules/relay-compiler/bin/relay-compiler` has a comment written directly above it: 
```js
// TODO T24511737 figure out if this is dangerous
```

**Comment by alloy** [comment]
Otherwise, in order to make a repro, an empty app with your schema should probably suffice, if you can share that.

**Comment by fllamo** [comment]
I am seeing the same issue with a different type definition, also only have one defined.

**Comment by nightspirit** [comment]
@alloy @sibelius Here is the [repo](https://github.com/nightspirit/relay-compiler-issue-2346) that I extract from our project. I can reproduce the issue with this.

**Comment by steida** [comment]
@nightspirit Because you have wrong args so compiler scans dirs with the schema files. I had the same problem. Check https://github.com/este/este/blob/b60c7a2f8f7c2b78ba4d0a889fee8a78cb2bbd50/package.json#L12

You have to process only dirs without the other schemas. cc @jsteiner Compiler could have a better error message for that.

**Comment by nightspirit** [comment]
@steida After I move the schema.graphql out of src directory as well as changing the command. It seems working.

```
relay-compiler --src ./src --schema schema.graphql
```

1.4.1 accept the schema.graphql in the src folder. I guess the error is somehow related to "client-only schema extensions" feature. Does it scan the src folder for .graphql files and add additional type to schema definition? The main schema should be excluded in my opinion.

**Comment by jstejada** [comment]
> 1.4.1 accept the schema.graphql in the src folder. I guess the error is somehow related to "client-only schema extensions" feature. Does it scan the src folder for .graphql files and add additional type to schema definition? The main schema should be excluded from scanning in my opinion.

@nightspirit I think this is correct! See #2264.
I'm going to update the release note to indicate that this change can break the compiler and see if we can have a better error message for this.

Thanks! And sorry for the trouble!

**Comment by alloy** [comment]
@jstejada I think we should fix this DX by excluding the `--schema` path from the found `.graphql` documents or do you foresee problems with that?

**Comment by renatonmendes** [comment]
I´m sorry, but it´s not clear to me what should be done. I´m facing the same problem:

```
ERROR:
Type "Node" already exists in the schema. It cannot also be defined in this type definition.
From: CodegenRunner.write
    at extendSchema (D:\dev\app\client\node_modules\graphql\utilities\extendSchema.js:82:17)
    at D:\dev\app\client\node_modules\relay-compiler\bin\relay-compiler:4897:13
    at Object.run (D:\dev\app\client\node_modules\relay-compiler\bin\relay-compiler:481:31)
    at Object.extendASTSchema (D:\dev\app\client\node_modules\relay-compiler\bin\relay-compiler:4885:34)
    at D:\dev\app\client\node_modules\relay-compiler\bin\relay-compiler:7613:40
    at next (native)
    at step (D:\dev\app\client\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at D:\dev\app\client\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at Promise.F (D:\dev\app\client\node_modules\core-js\library\modules\_export.js:35:28)
    at D:\dev\app\client\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
```

And my command:

`    "relay": "relay-compiler --src ./src --verbose --schema ./src/data/schema.graphql"
`

My graph ql is generated at tha following folder:

d:\dev\app\client\src\data

Should I change the directory, change parameters or something else ? Please clarify...

**Comment by steida** [comment]
@renatonmendes Check https://github.com/este/este for an inspiration.

**Comment by renatonmendes** [comment]
@steida, hummm... Should I put my `schema.graphql` in a directory other then `src/`, as leaving at src/ it will be reloaded by the compiler ?

**Comment by alloy** [comment]
@renatonmendes Yes, the problem is when your schema file resides inside the source root you specify with `—src`

**Comment by alloy** [comment]
Going to re-open this and make a fix to improve DX.

**Comment by ErnestGrey** [comment]
Maybe I missed something too, but I am having the same issue. I set my project up exactly how @steida has his setup. Put my `schema.graphql` file in a `server` folder. Included my folders that should have generated files in the relay command.

`relay-compiler --src . --include 'components/**' 'client/**' --schema server/schema.graphql`

Still getting the error, here is a snapshot of my `package.json`. Also running Node v8.9.3

![screen shot 2018-03-08 at 2 10 08 pm](https://user-images.githubusercontent.com/1953040/37171065-a7edb0fa-22da-11e8-8a9b-933a522c8db6.png)

**Comment by alloy** [comment]
@ErnestGrey Your server schema exists inside `src`, which is why it’s being used as a client schema extension as well.

**Comment by ErnestGrey** [comment]
@alloy My apologies, but I don't follow, I don't have a `src` folder in my file structure. Do I need one?
![screen shot 2018-03-08 at 4 45 46 pm](https://user-images.githubusercontent.com/1953040/37178367-3b62bc3a-22f0-11e8-9a1a-ee20d8755971.png)

**Comment by alloy** [comment]
I wasn’t clear enough and have updated my comment. I meant the source root that you designate with the `--src` option.

**Comment by renatonmendes** [comment]
Getting the same error, now in my monorepo:

`"relay": "relay-compiler --verbose --src ./src --schema ../graphql/data/schema.graphql"
`
My ` --schema` is outside `./src`

 ```
relay-compiler --verbose --src ./src --schema ../graphql/data/schema.graphql

HINT: pass --watch to keep watching for changes.

Writing js
ERROR:
Type "Company" already exists in the schema. It cannot also be defined in this type definition.
From: CodegenRunner.write
    at extendSchema (D:\monorepo\node_modules\graphql\utilities\extendSchema.js:89:17)
    at D:\monorepo\node_modules\relay-compiler\bin\relay-compiler:4897:13
    at Object.run (D:\monorepo\node_modules\relay-compiler\bin\relay-compiler:481:31)
    at Object.extendASTSchema (D:\monorepo\node_modules\relay-compiler\bin\relay-compiler:4885:34)
    at D:\monorepo\node_modules\relay-compiler\bin\relay-compiler:7613:40
    at next (native)
    at step (D:\monorepo\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at D:\monorepo\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at Promise.F (D:\monorepo\node_modules\core-js\library\modules\_export.js:35:28)
    at D:\monorepo\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! @monorepo/editor@3.0.0 relay: `relay-compiler --verbose --src ./src --schema ../graphql/data/schema.graphql`
npm ERR! Exit status 100

```

**Comment by alloy** [comment]
That seems suspicious indeed. If you grep `./src/**/*.graphql` for `Company`, what occurrences do you find?

**Comment by renatonmendes** [comment]
```
$ grep Company ./src/**/*.graphql
# Company
type Company implements Node {
# Company input type
input CompanyInput {
  createCompany(data: CompanyInput!): Company
  updateCompany(id: ID!, data: CompanyInput!): Company
  deleteCompany(id: ID!): Company
  company: Company
  company: Company
  company(id: ID!): Company
  companies: [Company]

```

**Comment by alloy** [comment]
@mvachhar Yes.

**Comment by alloy** [comment]
@renatonmendes I’m not sure what you mean by suggestion ‘a’ can you elaborate? Suggestion ‘b’ seems like a good one, want to send a PR for that? Suggestion ‘c’ seems to be counter-intuitive, we _want_ `*.graphql` files to be processed, _except_ for the `--schema` one, which is fixed in https://github.com/facebook/relay/pull/2361

**Comment by antimtechnology** [comment]
node_modules/.bin/relay-compiler --src ./src/ --schema ./schema.graphql


Error: Cannot find module 'graphql'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\ReactNative\RelayAndGraphQL\frontend\node_modules\graphql-compiler\lib\GraphQLSchemaUtils.js:153:20)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
