### ISSUE TITLE
Relay DevTools: Connected, but store is empty

### ISSUE THREAD

**Issue by steida** [facebook/relay#2347]
For some reason, it seems to be connected, but store is empty. 
![screen shot 2018-02-24 at 01 22 56](https://user-images.githubusercontent.com/66249/36623026-764df740-1901-11e8-8870-76d05f2847cf.png)

**Comment by steida** [comment]
Which places? I have tried several places without any luck. :-(

**Comment by ssomnoremac** [comment]
Well the second time I set the `Env` I'm passing `params` which are typically tokens, this is what it looks like for me. I'm using Elixir Absinthe on the backend with sockets.
```
    const env = new Environment({
        network: Network.create(
            createFetcher(absintheSocket, errorFun),
            createSubscriber(absintheSocket, errorFun)
        ),
        store: new Store(new RecordSource()),
    })
    if (params) {
        installRelayDevTools()
    }
```

**Comment by steida** [comment]
Thank you! Unfortunately, it still does not work. There must be some prerequisites I am not aware of.

**Comment by alloy** [comment]
@steida I don’t believe the repo is public, but the source is in `./node_modules/relay-devtools`

**Comment by kevinbmccall14** [comment]
Peeking at source code points out that you can pass a port, host and custom prompt message to `installRelayDevtools()`.

```javascript
// ./node_modules/relay-devtools/index.js
/*
* By default, this will look for the Relay DevTools app at localhost:8734,
* however both the port and host can be configured.
*/
function installRelayDevTools(port, host, prompt) {
  // ...source code
}
```

**Comment by kassens** [comment]
The relay devtools are over at https://github.com/relayjs/relay-devtools. Closing this as there's been a new release since this issue was opened. I think this is also referring to the old devtools and not the (somewhat improved) newer version.
