### ISSUE TITLE
prepareVariables + routing

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#235]
If you pass in params from the route using e.g.

```
viewer: () => Relay.QL`query { viewer }`
```

then `prepareVariables` isn't called on the override parameters passed by the route (just `initialVariables`).

It seems like we should probably run the override parameters through too, so that everything going into the fragment query goes through `prepareVariables` first.

**Comment by devknoll** [comment]
Double checked the code and debugged a little harder, and found out that `prepareVariables` is actually being called here, but some other strange thing is happening. I'll open a new issue when I discover it.

**Comment by josephsavona** [comment]
I'm working on a related change that should address this.
2015年9月3日(木) 14:10 Gerald Monaco <notifications@github.com>:

**Comment by taion** [comment]
I do notice an odd thing here where the variables passed in from a wrapper seem to clobber `initialVariables`.
