### ISSUE TITLE
[Relay-Complier]ERROR: Parse error: SyntaxError: A trailing comma is not permitted after the rest element

### ISSUE THREAD

**Issue by xyy94813** [facebook/relay#2350]
Today, i try to upgrade react-relay, babel-plugin-relay and relay-compiler from 1.4.1 to 1.5.0 in my project.

I try to use relay-compiler to regenerate `.graphql` file, then i got another error: 
`Parse error: SyntaxError: A trailing comma is not permitted after the rest element`

Why add this limit?

**Comment by alloy** [comment]
This is a side-effect of Relay updating `babylon` to > v6.11.3 [here](https://github.com/facebook/relay/commit/ea93d0e0af562e80962fdb016b864f4c89fad626), which had [this breaking change](https://github.com/babel/babylon/blob/master/CHANGELOG.md#v6113-2016-10-01) introduced in an apparent ‘spec compliancy’ effort. As such, this isn’t likely to be changed.
