### ISSUE TITLE
[Modern] Does pagination support both directions?

### ISSUE THREAD

**Issue by operate2v** [facebook/relay#2355]
pagination seems to support only one direction.
However, I need a bi-directional pagination.
Is there a way to enable bi-directional pagination in relay-modern?
Or a guide

I've asked the same question on stackoverflow is
https://stackoverflow.com/questions/49048051/does-pagination-support-both-directions

**Comment by alloy** [comment]
As asked by others on your SO question, it’s not entirely clear what your case is. In addition this issue tracker is meant to track work on Relay, so I would suggest you keep your question on SO or maybe join a [community chat](http://graphql.org/community/) such as the #relay channel on [the GraphQL Slack](https://graphql-slack.herokuapp.com/). Having said that, once you figure out how to solve your case and think it can be helpful to others then PRs for more docs are always welcome!

**Comment by jstejada** [comment]
Hey @operate2v, pagination container currently doesn't support pagination in 2 directions simultaneously, but we will likely add something soon to support this
