### ISSUE TITLE
Fetching data in programmatically way

### ISSUE THREAD

**Issue by noone0012** [facebook/relay#2360]
Hi There!

I've got countries/cities select boxes. When user selects country the appropriate city list needs to be fetched from the server (initially no cities are needed). How can I implement this? I've tried to solve with refetchContainer but it's no use.

**Comment by sibelius** [comment]
you can use refetchContainer or use fetchQuery directly

**Comment by robrichard** [comment]
Here are the docs for `fetchQuery`

https://facebook.github.io/relay/docs/en/next/fetch-query.html

**Comment by noone0012** [comment]
I think fetchQuery is the right choice in this case. 
I'd like to know is there a way to implement this with refetchContainer (initally not fetching data)

**Comment by sibelius** [comment]
yes, you can use `@include` directive, so you can be `lazy`

**Comment by noone0012** [comment]
Ok. Thank you!
