### ISSUE TITLE
Implementing instant search feature, failed with both QueryRenderer and RefetchContainer?

### ISSUE THREAD

**Issue by irrigator** [facebook/relay#2363]
The feature is simple: a typical search bar with results coming in as you type. I've tried implementing it use both methods, neither was perfect. There seems be some fundamental problems.

Method One: Use QueryRenderer, pass the search term as a variable. The problem is every time a new search request is started, QueryRenderer will empty the props, thus rendering an empty page.
Also, since the data fetching is handled declaratively be QueryRender, I can't find a way to throttle it.

Method Two: Use RefetchContainer (as a child of QueryRenderer, of course). The search term state lives with the RefetchContainer, and every time it changes it calls ```this.props.relay.refetch``` to resend the search request. The problem is I need to first render the root QueryRenderer to show the search bar to the user, and sending an empty string as a default search term variable, thus sending a wasted request to the network. Also, since QueryRenderer only renders when data is ready, the search bar shows only after the wasted request succeeds.

**Comment by alloy** [comment]
Not sure if you already found a solution and thus closed this, but you could use `fetchQuery` imperatively instead https://facebook.github.io/relay/docs/en/next/fetch-query.html

**Comment by irrigator** [comment]
That's what I need. I searched fetchQuery on the doc site, but nothing came out though.

**Comment by alloy** [comment]
It looks like the docs for that will be available in the next release, I googled for it.
