### ISSUE TITLE
Rename REQUIRED_CHILDREN and document its use cases

### ISSUE THREAD

**Issue by yungsters** [facebook/relay#237]
We should rename `REQUIRED_CHILDREN` to be `EXTRA_FRAGMENT` or something that explains how it is merely supplementary fields that may be needed in order to correctly respond to the success of the mutation.

For example, if you're sending a mutation that creates a new account and you want to navigate immediately to that new account (e.g. using a URL with the new account's ID), the new account may not be part of the response if it is not currently rendered (i.e. it is not the intersection of what can change and what is cached on the client). In this case, you need to use this (tentatively-named) `EXTRA_FRAGMENT` configuration to add additional fields (like the new account's ID).

We should also revise the documentation to explain its use cases instead of simply saying, "Avoid this." Also, it is not currently documented on the website at all.

**Comment by AndrewIngram** [comment]
Incidentally, this is exactly what I needed to know about for this: https://github.com/facebook/relay/issues/447 (http://stackoverflow.com/questions/33001632/patterns-for-transient-user-notifications-with-relay).

**Comment by oguzbilgic** [comment]
@steveluscher 's answer (http://stackoverflow.com/questions/32539189/how-to-get-the-id-of-a-new-object-from-a-mutation/32546415#32546415) explains how to use `REQUIRED_CHILDREN` for adding a new node and getting It's ID to be used in callback. However @wincent (http://stackoverflow.com/a/33367168/96725) states that It could also be used for deleting a node without requiring It's parent (where node doesn't know its parent etc.) Could you please provide an example for this use case too? I'm currently working on a mutation, where deleted node isn't aware of it's parents.

**Comment by wincent** [comment]
I'm going to fold this into #538, which is about overhauling the mutations API. (It will be easier to manage with the various interrelated mutations issues in a single place.)
