### ISSUE TITLE
multiple subscriptions in one component throws error when another subscription fires?

### ISSUE THREAD

**Issue by iamglenbacs** [facebook/relay#2370]
so i have just added another subscription on my component, but when i try to add another subscription, when one of them fires, it throws error like this:
![1](https://user-images.githubusercontent.com/17801912/37479272-379abe00-28b7-11e8-9fa6-bfed6b5e083e.png) help?

**Comment by sibelius** [comment]
can u provide a repo so we can reproduce this?

**Comment by iamglenbacs** [comment]
my repo is this: https://github.com/iamglenbacs/rgr, on home component, I have todoLiked subscription and todoAdded subscription, both trying to update the store

**Comment by sibelius** [comment]
this is not a problem with subscriptions, it is a problem of how do u get nodes from store

**Comment by alloy** [comment]
@sibelius Going to close this then.
