### ISSUE TITLE
Unclear Error

### ISSUE THREAD

**Issue by noone0012** [facebook/relay#2375]
This happens when trying to access to property of the response 
http://prntscr.com/ist0dm

**Comment by noone0012** [comment]
I've got this mutation, that returns a list of photo edges as response.
The error appers in the updater function when I'm trying to access to property of the response,

`store.getRootField('addPhotos').getLinkedRecord('photosEdge');`

```
  mutation AddPhotosMutation($input: AddPhotosInput!) {
    addPhotos(input: $input) {
      photosEdge {
        cursor
        node {
          id
          url
        }
      }
    }
  }
```

**Comment by sibelius** [comment]
can u share the whole mutation code?

**Comment by noone0012** [comment]
Sure.

```
import { graphql } from 'react-relay';
import commitMutation from 'relay-commit-mutation-promise';

const mutation = graphql`
  mutation AddPhotosMutation($input: AddPhotosInput!) {
    addPhotos(input: $input) {
      photosEdge {
        cursor
        node {
          id
          url
        }
      }
    }
  }
`;

function commit(environment, input, userId) {
  return commitMutation(environment, {
    mutation,
    variables: { input },
    updater(store) {
      const payload = store.getRootField('addPhotos');

      // if received an error
      if (!payload) {
        return;
      }

      payload.getLinkedRecord('photosEdge');
    }
  });
}

export default { commit };
```

**Comment by sibelius** [comment]
try to follow this medium https://medium.com/entria/wrangling-the-client-store-with-the-relay-modern-updater-function-5c32149a71ac

or use something for this gist https://twitter.com/sseraphini/status/975678585536241666

**Comment by noone0012** [comment]
Ok. Thank you.

**Comment by alloy** [comment]
@noone0012 Is this solved or is there still a way in which Relay could/should be improved?

**Comment by sibelius** [comment]
@noone0012 have you solved?

**Comment by alloy** [comment]
Let's close for now.
