### ISSUE TITLE
PaginationContainer without initial fetch

### ISSUE THREAD

**Issue by noone0012** [facebook/relay#2378]
I've got `Chat` component which is similiar to modal. Whenever user clicks on friend's photo, that chat appears and loads messages by calling `loadMore`. So I don't want to initially fetch something. 
I've implemented it with `PaginationContainer ` using ` @include ` on ` connection` field.
But there are some issues by doing so. 

1. Whenever  chat is opened, `loadMore` does not work as expected, it doesn't send request.  And also `hasMore ` returns  `false`.
I've solved this by using `refetchConnection`, but I don't think it's a very good solution.

2.  The main problem is here. The parent component does not actually gives required data to child, that is to `Chat ` Component. I think this is because initially Chat didn't include the connection field.

Is there any way to solve this? I really don't want to use `fetchQuery`. It's really boring.

**Comment by alloy** [comment]
Thanks for taking the time to file an issue, but this appears to be a usage question and, as indicated by [the issues template](https://github.com/facebook/relay/blob/master/.github/ISSUE_TEMPLATE.md#questions-regarding-how-to-use-relay-andor-graphql), those types of questions should go to StackOverflow or a chat community such as Discord; although I’d suggest [#relay](https://graphql.slack.com/messages/relay) on [the GraphQL Slack](https://graphql-slack.herokuapp.com) over the Discord one.
