### ISSUE TITLE
getFragmentVariables: prevVars's values is incorrect

### ISSUE THREAD

**Issue by noone0012** [facebook/relay#2381]
I'm using `createPaginationContainer` and `refetchConnection` to restart pagination when `userID` is changed. In `getVariables` I'm returning new userID and it works OK. However in `getFragmentVariables`s `prevVars` argument doesn't take changed ID. After calling `refetchConnection` it takes the default values defined in fragment. How to get new ID ?

**Comment by alloy** [comment]
Thanks for taking the time to file an issue, but this appears to be a usage question and, as indicated by [the issues template](https://github.com/facebook/relay/blob/master/.github/ISSUE_TEMPLATE.md#questions-regarding-how-to-use-relay-andor-graphql), those types of questions should go to StackOverflow or a chat community such as Discord; although I’d suggest [#relay](https://graphql.slack.com/messages/relay) on [the GraphQL Slack](https://graphql-slack.herokuapp.com) over the Discord one.
