### ISSUE TITLE
clientSubscriptionId isn't working

### ISSUE THREAD

**Issue by noone0012** [facebook/relay#2383]
It seems clientSubscriptionId isn't identifiying the records.
I'm using `subscriptions-transport-ws` as a ws-server so it returns response in not standard way as it does graphql.  The response looks like the following. However `onNext ` method is called with `relayData`
May it cause a problem ?

```
id: "1"
payload : { data: relayData }}
type: "data"
```

**Comment by sibelius** [comment]
could u share some code and what error does it cause?

**Comment by noone0012** [comment]
It behaves as if it didn't receive clientSubscriptionId. The received records become the same.

I have one question. What value I should return to client from the server as clientSubscriptionId? 
1. The same as client passed when connected to ws? However in this case the server will always return the same Id in every response.
2. The clientMutationId that was received from mutation ?

In both cases I'm getting the same issue.
`Encountered two children with the same key, `TWVzc2FnZTo1NTA=`.`

**Comment by sibelius** [comment]
make this is the same problem as clientMutationId: https://github.com/facebook/relay/pull/2349

**Comment by noone0012** [comment]
Thank you. However it doesn't say how to use another ID ? The following is subscription's `updater`.

```
      const conn = ConnectionHandler.getConnection(
        store.get('root_connections'),
        'Chat_messages',
        { userId: input.userId }
      );

      ConnectionHandler.insertEdgeAfter(
        conn,
        store.getRootField('newMessage').getLinkedRecord('messageEdge')
      );
```

**Comment by sibelius** [comment]
as a workaround u could make clientSubscriptionId just a random number for now
