### ISSUE TITLE
New React context API and SSR hack

### ISSUE THREAD

**Issue by steida** [facebook/relay#2392]
I am using this Relay provider for the server-side rendering in https://github.com/este/este.
I suppose I will be able to use this hack until React 17 which will remove legacy context API.
Do we have any other option for SSR? Is something planned? How can I help? Thank you.

```js
// @flow
import * as React from 'react';
import PropTypes from 'prop-types';
import type { Environment } from 'react-relay';

// RelayProvider sets Relay context manually for SSR and pending navigations.
// Check App.getInitialProps, note "await fetchQuery". It replaces QueryRenderer.
// https://github.com/robrichard/relay-context-provider

type RelayProviderProps = {
  environment: Environment,
  variables: Object,
  children: React.Node,
};

class RelayProvider extends React.PureComponent<RelayProviderProps> {
  static childContextTypes = {
    relay: PropTypes.object.isRequired,
  };

  getChildContext() {
    return {
      relay: {
        environment: this.props.environment,
        variables: this.props.variables,
      },
    };
  }

  render() {
    return this.props.children;
  }
}

export default RelayProvider;
```

**Comment by kassens** [comment]
I haven't tried server rendering myself, but we have a similar use case when we did prefetching of a query.

Essentially, we have the ability in the network layer to synchronously return data instead of waiting a tick. If you do that, Relay instantly renders the final layout instead of first a loading state. I think that should be enough to server render.

**Comment by steida** [comment]
And here is the usage https://github.com/este/este/blob/master/components/app/index.js#L125

**Comment by maxbeatty** [comment]
I'm using [an almost identical provider in Next.js](https://github.com/zeit/next.js/blob/5.1.0/examples/with-relay-modern/lib/RelayProvider.js) and curious how new context API will be used in relay

**Comment by steida** [comment]
@maxbeatty Next.js example was written by Este.

**Comment by johntran** [comment]
https://medium.com/ansaro-engineering/using-reacts-new-context-api-with-relay-ff61a2c6de37

You can use this as inspiration.

**Comment by steida** [comment]
https://github.com/zeit/next.js/issues/6157#issuecomment-457971721
