### ISSUE TITLE
Flow: property $refType is missing in object

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/relay#2394]
Hello. 👋 We use generated Flow types in our functions like this for example:

```js
export default (room: ?BeddingInfo_room): string => {
  // ...
};
```

Problem is that Relay is generating Flow types with `+$refType`:

```js
import type { ConcreteFragment } from 'relay-runtime';
import type { FragmentReference } from 'relay-runtime';
declare export opaque type BeddingInfo_room$ref: FragmentReference;
export type BeddingInfo_room = {|
  +type: ?string,
  +maxPersons: ?number,
  +bedding: ?$ReadOnlyArray<?{|
    +type: ?string,
    +amount: ?number,
  |}>,
  +$refType: BeddingInfo_room$ref,   // <<<
|};
```

This, unfortunately, complicates our testing because we cannot use simple plain objects (without the `$refType`):

```js
expect(
  // Flow error here (vv) because Relay $refType is missing in the object
  formatBeddingInfo({
    type: 'Single Room',
    maxPersons: 1,
    bedding: [
      {
        type: 'Single Bed(s)',
        amount: 1,
      },
    ],
  }),
).toMatchSnapshot();
```

I don't really understand why is this property necessary but is it possible to make it at least optional? Or how should we test it properly? It was fine before version 1.5... Error message:

```
Cannot call formatBeddingInfo with object literal bound to room because property $refType is missing in object
literal [1] but exists in BeddingInfo_room [2].

     app/hotels/src/singleHotel/roomList/__tests__/formatBeddingInfo.test.js
      4│
      5│ it('formats bedding information', () => {
      6│   expect(
 [1]  7│     formatBeddingInfo({
      8│       type: 'Single Room',
      9│       maxPersons: 1,
     10│       bedding: [
     11│         {
     12│           type: 'Single Bed(s)',
     13│           amount: 1,
     14│         },
     15│       ],
     16│     }),
     17│   ).toMatchSnapshot();
     18│ });
     19│

     app/hotels/src/singleHotel/roomList/formatBeddingInfo.js
 [2]  7│ export default (room: ?BeddingInfo_room): string => {
```

**Comment by sibelius** [comment]
you can use $RelayProps https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayTypes.js#L101

**Comment by mrtnzlml** [comment]
@sibelius Oh, that would probably solve my problem. But is it exported outside of the `react-relay` package? I am not able to find it (or figure out how to use it correctly).

**Comment by juhaelee** [comment]
@mrtnzlml did you find a solution for this?

**Comment by juhaelee** [comment]
@mrmlnc I see, I also seemed to get flow errors on mutations as well ever since the upgrade :/

**Comment by mrmlnc** [comment]
@juhaelee, I think you wanted to mention @mrtnzlml :)

**Comment by kassens** [comment]
Hey, sorry for not responding here earlier.

To unblock your tests for now, you can do something like:

```
// Maybe define this in some utility
const mockRefType: any = null;

expect(
  // Flow error here (vv) because Relay $refType is missing in the object
  formatBeddingInfo({
    $refType: mockRefType,
    type: 'Single Room',
    maxPersons: 1,
    bedding: [
      {
        type: 'Single Bed(s)',
        amount: 1,
      },
    ],
  }),
).toMatchSnapshot();
```

I do think there should be more work done on testability and making the testing more ergonomic.

**Comment by sibelius** [comment]
this PR could have solved this https://github.com/facebook/relay/pull/2293

try on master

**Comment by creatyvtype** [comment]
@sibelius it did not. Just upgraded from 1.4.1 to 2.0.0 and we have hundreds of these flow errors now. the `mockRefType` workaround that @kassens suggested works, but I can't just go through each error and add this one by one. This is a big problem for us.

**Comment by steida** [comment]
Before I switched to TypeScript, I was manually fixing generated types as a workaround.

**Comment by artola** [comment]
@steida By the way, then how did you solved it in TS?

I have a generic (`NoFragmentRefs<T>`) to cleanup recursively the references and I use it for component data and to prepare the fixtures.

**Comment by steida** [comment]
@artola Check here https://github.com/este/este

**Comment by kassens** [comment]
Check out https://github.com/relayjs/relay-examples/tree/master/todo, @Stephen2 has been working with me to figure out the typing in OSS. The types exported from `flow-typed` seem to be a bit off and he's been looking in fixing them.

I'm pretty sure they work *as defined in relay iself*. We use them all over the place internally.
