### ISSUE TITLE
Bug: Broken link from relay docs

### ISSUE THREAD

**Issue by soneymathew** [facebook/relay#2398]
The link to https://facebook.github.io/relay/docs/en/graphql-connections.html from https://facebook.github.io/relay/docs/en/relay-environment.html#adding-a-handlerprovider is broken

![image](https://user-images.githubusercontent.com/1210516/38417280-067f84c4-39db-11e8-8688-8950d6a73873.png)

**Comment by alloy** [comment]
Thanks for the report! Fixed in #2415.
