### ISSUE TITLE
Not including a field causes a createFragmentSpecResolver warning

### ISSUE THREAD

**Issue by maxaggedon** [facebook/relay#2399]
I have a query which can be simplified to that:

```graphql
query UserFormQuery($userId: ID!, $shouldIncludeUser: Boolean!) {
  user(id: $userId) @include(if: $shouldIncludeUser) {
    ...UserForm_user
  }
}
```
with the following fragment:

```graphql
fragment UserForm_user on User {
  name
  email
  ...
}
```

I use this for a form, so when I need to create a new user I set `$shouldIncludeUser` to `false` (and `$userId` to an empty string as it will not be used but will create an error if absent) and when I need an existing one I set it to `true` in order to retrieve the existing data.

My problem is that I get a warning when I don't fetch the data because no `user` prop is passed down to the `FragmentContainer`:
```
Warning: createFragmentSpecResolver: Expected prop user to be supplied to Relay(UserForm), but got undefined. Pass an explicit null if this is intentional.
```

**Comment by sibelius** [comment]
you need `<UserForm user={user} />`

**Comment by sibelius** [comment]
You can fix this doing this:

`return <WrappedComponent query={...props} {...passDownProps} />;`

and then you gonna have a fragment on QueryType instead of `user`

```
query UserFormQuery($userId: ID!, $shouldIncludeUser: Boolean!) {
   ...UserForm_query
}
```

```
fragment UserForm_query on Query {
  user(id: $userId) @include(if: $shouldIncludeUser) {
      name
     email
     ...
  }
}
```

You gonna need a refetchContainer on UserForm to change `$shouldIncludeUser` variable
