### ISSUE TITLE
Compile time support for Relay Spec compliance validation

### ISSUE THREAD

**Issue by soneymathew** [facebook/relay#2404]
Hello relayjs team,

  Is it a viable pursuit to add compile time support to validate the schema against relay spec compliance. This can range from errors to warnings from relay compiler that will guide the schema author to add provisions that will help get the best benefits from relay. I am interested in failing fast on bad type definitions that is not aligned to the needs of relay.
By schema I mean server schema as well as client extensions to the schema.

I am ok if the validations are scoped to the types used by my react components, but I want to detect it at compile time. Please share your thoughts. Also I am very curious how you handle this need internally.

Thanks,
Soney

**Comment by sibelius** [comment]
@soneymathew the only requirements for now is to have a global ID in the schema

**Comment by sibelius** [comment]
https://facebook.github.io/relay/graphql/objectidentification.htm

**Comment by soneymathew** [comment]
@sibelius I was referring to the other parts of the spec 
https://facebook.github.io/relay/docs/en/graphql-server-specification.html

If I am starting fresh on a project, I think this will help me fall into the pit of success, We can also avoid this review overhead between members of the team.

If this is not the task of the compiler when it is running in watch mode, is using eslint or stricter a better strategy?

**Comment by orta** [comment]
I wonder about a schema linter, it could check that all classes ending in Input have a mutationID, that you don’t do array resolvers but use connections

**Comment by soneymathew** [comment]
@orta / @sibelius  we now have linters available that handles this. if relay is not planning to incorporate this into the compiler this issue can be closed.

checkout
https://github.com/cjoudrey/graphql-schema-linter#relay-connection-types-spec

I have tested this in a big schema and found it to be effective.

**Comment by sibelius** [comment]
We can add this link to the docs

**Comment by josephsavona** [comment]
Relay Compiler does check the schema for compliance, but it currently does so lazily based on usage of the schema as opposed to eagerly. The compiler won't throw an error, for example, if you have a connection field that doesn't conform to the spec. However, if you _use_ that with `@connection`, you'll get an error at that call-site saying the schema doesn't conform. Similarly for things like 3D. If we did add an option to check the schema ahead of time, we'd want to find a way to do that validation just once, and reuse it from the various transforms.
