### ISSUE TITLE
Hot reload queries

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#241]
When working with Webpack hot reloading, it'd be great if when you change a query, it gets re-run. Currently I have to reload my browser.

**Comment by yungsters** [comment]
cc @steveluscher :)

**Comment by carlosepp** [comment]
:100: please :)

**Comment by tommyJS** [comment]
+1

I am wondering also if Hot Module Replacement works together with Relay Containers. It does not work on my setup, however, I might do something wrong. I use Relay, React and React Router Relay. Is it possible to get it working? Thanks.

**Comment by nicerr** [comment]
Have you had a look at this: https://github.com/doabit/react-relay-graphql-starter-kit ?

**Comment by tommyJS** [comment]
Thank you for the answer.
`"preset": "react-hmre"` works.
Previously I tried:
```
["react-transform", {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }]
```
and it was not working.

**Comment by josephsavona** [comment]
I can definitely see the value of this, although it's a bit tricky. In the new core, all graphql tagged templates are replaced with references to generated JS modules, which would likely be amenable to hot-reloading. However, the module that includes the query wouldn't necessarily update and know to re-issue the query. Definitely something to keep thinking about in the future once the new core is available.

**Comment by kassens** [comment]
Sorry this has been lingering a lot time. We're open to anyone sending a PR, but we're trying to close some of the very old issues that haven't found traction.
