### ISSUE TITLE
No way to access container data in map / forEach

### ISSUE THREAD

**Issue by vladar** [facebook/relay#242]
The problem I faced with is that when I render a list of items (where item is a container), I can't set `key` value properly because actual data is not available during iteration - it only becomes available inside the container.

```javascript
const ListComponent = React.createClass({
  render() {
    return this.props.items.map((item) => <ItemContainer item={item} key={item.id} />)
  }
})
```

In this example `key={item.id}` doesn't do anything because item data is not resolved yet and `item.id` is `undefined`.

Currently I have to use `item.__dataID__`, but this feels like a hack, because `__dataID__` seems to be an implementation detail and may change some day. 

Can I rely on it or maybe there is a better way to do this? Couldn't find anything relevant in docs.

**Comment by josephsavona** [comment]
Can you paste the GraphQL fragment for the `ListComponent` container? This is likely a matter of having the parent ask for the `id` of each list element.

eg:

```javascript
Relay.createContainer(Parent, {
  fragments: {
    foo: () => Relay.QL`
      fragment on Foo {
        fooConnection(first: $count) {
          edges {
            node {
              id, # get the id for use as a key
              ${Child.getFragment('listItem'),
            ...
```

**Comment by vladar** [comment]
Whole container looks like this:

```javascript
Relay.createContainer(TopLevelComponent, {
  initialVariables: {
    wrapped: true
  },
  fragments: {
    viewer: (variables) => Relay.QL`
      fragment SB on Viewer {
        listWrapper @include(if: $wrapped) {
          items {
            ${ItemContainer.getFragment('item')}
          }
        }
        items @skip(if: $wrapped) {
          ${ItemContainer.getFragment('item')}
        }
     }`
  }
})
```

List is iterated by non-contanier intermediate component that simply receives `items` from parent as a prop.

**Comment by josephsavona** [comment]
Thanks for pasting - as I mentioned, you can add the `id` field so that the parent (thing iterating the list) has a value to use for `key`:

```
        ...
        items ... {
          id, # add this to both `items`
          ${ItemContainer.getFragment('item')}
        }
```

**Comment by josephsavona** [comment]
Also, all `__underscore__` and `_underscore` properties should be considered private (not used by application code) and subject to change at any time.

**Comment by vladar** [comment]
Makes sense. Thanks!

**Comment by josephsavona** [comment]
Happy to help!
