### ISSUE TITLE
Modifying/rolling your own variant of the compiler

### ISSUE THREAD

**Issue by zth** [facebook/relay#2423]
Hi!

I'm looking to change a few things with the compiler that I need for my projects (namely, `formatGeneratedModule` + possibly a few other minor things). What's the recommended way of doing that? Is it maintaining your own copy of https://github.com/facebook/relay/blob/master/packages/relay-compiler/bin/RelayCompilerBin.js + whatever other files I need to modify...?

Thanks!

**Comment by zth** [comment]
@robrichard sorry for tagging you, but didn't you do something similar, or am I misremembering?

**Comment by robrichard** [comment]
@zth yes we maintain a fork of RelayCompilerBin to support persisted queries and setting the search paths to our list of private node_modules that contain relay data.

**Comment by zth** [comment]
Thank you! I'll go ahead and close this and go for that solution too.
