### ISSUE TITLE
refetchContainer clears other fields that other components are subscribed to

### ISSUE THREAD

**Issue by juhaelee** [facebook/relay#2425]
Say I have a component called School that looks like this:

```
school: graphql`
fragment MySchool_school on School {
      id
      name
      location { city }
      ...StudentsRefetchContainer_school
    }
`
```

My refetchContainer's fragment looks like this:
```
graphql`
    fragment StudentsRefetchContainer_school on School
      @argumentDefinitions(show: { type: "Boolean", defaultValue: false }) {
         ...StudentsInfo_school @include(if: $show)
    }
  `
```

My refetchContainer's query for refetching looks like this:
```
  graphql`
    query StudentsRefetchContainer_Query($id: ID!, $show: Boolean!) {
      school(id: $id) {
        ...StudentsRefetchContainer_school @arguments(show: $show)
      }
    }
  `
```

I call refetch on mount of the RefetchContainer component, which triggers a refetch. As soon as the refetch happens, the school record in the store gets updated by setting everything as undefined. However, my app crashes because the parent updates since it's subscribed to that school instance. I assume this is because when the refetch happens, the data in the store gets updated with the data that gets returned from the refetch query. This makes sense. However, shouldn't it not make the other fields undefined? Rather, just update the fields that were returned from the refetch query? (a merge rather than a replace)

**Comment by liweinan0423** [comment]
“Refetch” obviously means to refetch and replace data in the store, which makes sense. I think you might have to implement some sort of a `MergingRefetchContainer` that updates in the store only the fields returned from server.

**Comment by sibelius** [comment]
This could cause some staled data issues as well

**Comment by mike-marcacci** [comment]
@juhaelee I believe this is a duplicate of #2237.

**Comment by juhaelee** [comment]
Closing this in favor of https://github.com/facebook/relay/issues/2237
