### ISSUE TITLE
Refetch Container: Root prop does not update after refetch

### ISSUE THREAD

**Issue by maikelrobier** [facebook/relay#2434]
This might be related to https://github.com/facebook/relay/issues/2244 or https://github.com/facebook/relay/issues/2421, but I couldn't find a solution there.

It seems a root property that was initially null won't update after refetching even when the field comes in the response from the server. This was the code:

```jsx
class CarrierFormsEdit extends React.Component<Props> {
  handleTemplateGroupCreated = (id: string) => {
    this.props.relay.refetch({
      isEditing: true,
      templateGroupId: id,
    })
  }

  //...
}

const fragments = {
  templateGroup: graphql`
    fragment CarrierFormsEdit_templateGroup on CarrierFormTemplateGroup {
      ...CarrierFormsGroupBasicInfo_templateGroup
      ...CarrierFormsGroupTemplates_templateGroup
      ...CarrierFormsGroupEvents_templateGroup
    }
  `,
  viewer: graphql`
    fragment CarrierFormsEdit_viewer on Query {
      ...CarrierFormsGroupBasicInfo_viewer
    }
  `,
}

const query = graphql`
  query CarrierFormsEditQuery($isEditing: Boolean!, $templateGroupId: ID!) {
    templateGroup: node(id: $templateGroupId) @include(if: $isEditing) {
      ...CarrierFormsEdit_templateGroup
    }
    viewer {
      ...CarrierFormsEdit_viewer
    }
  }
`

const enhance = flow(
  withRefetch(fragments, query),
  mapProps(({ templateGroup }) => ({
    templateGroup: templateGroup || null,
  })),
  withQuery({ query }),
)

export default enhance(CarrierFormsEdit)
```

The field `templateGroup` uses the `@include` directive to be fetched conditionally, initially it is null, but after calling refetch I would expect it to get a value, since the value for it comes in the query response, but `RefetchContainer` doesn't update it, it keeps being null after refetch.

I found a workaround, getting rid of the `templateGroup` fragment and moving it inside `viewer` solves the problem for me:

```jsx
const fragments = {
  viewer: graphql`
    fragment CarrierFormsEdit_viewer on Query @argumentDefinitions(
      isEditing: { type: "Boolean!" },
      templateGroupId: { type: "ID!" },
    ) {
      templateGroup: node(id: $templateGroupId) @include(if: $isEditing) {
        ...CarrierFormsGroupBasicInfo_templateGroup
        ...CarrierFormsGroupTemplates_templateGroup
        ...CarrierFormsGroupEvents_templateGroup
      }
      ...CarrierFormsGroupBasicInfo_viewer
    }
  `,
}

const query = graphql`
  query CarrierFormsEditQuery($isEditing: Boolean!, $templateGroupId: ID!) {
    viewer {
      ...CarrierFormsEdit_viewer @arguments(isEditing: $isEditing, templateGroupId: $templateGroupId)
    }
  }
`
```

But I'd like to understand if the problem is a relay issue or simply that I'm using `RefetchContainer` incorrectly. Thanks.

I was using relay `1.5.0`.

**Comment by jstejada** [comment]
Hey @maikelrobier, so I believe the problem here is that Refetch containers are used for refetching the fragment in the container with different variables. Your fragment initially doesn't have any variables, so the subscription to the store wont be set up using the right variables; I believe that's why your second example works, because you're using the variables inside the fragment.

Happy to try to clarify this better in the docs
