### ISSUE TITLE
Relay Fragment doesn't update it's state.

### ISSUE THREAD

**Issue by ErrorPro** [facebook/relay#2436]
Hi, I found strange behaviour of Relay Fragment. I have a container and inside it I render fragments container with passed data prop as current data(depends on router params) and I noticed that after route is changed Relay Fragment returns the old data however in props I see that route params has been changed. I started digging into this problem and found that [getDerivedStateFromProps](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayFragmentContainer.js#L107) never gets called. I was trying to understand why and I found [this](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/buildReactRelayContainer.js#L74). buildReactRelayContainer tries to overwrite static method but it actually never does, because class is returned before `ContainerConstructor` is called.
This is why react doesn't call getDerivedStateFromProps and this is why RelayFragmentContainer returns old data because it doesn't update it's state.

I tried to reproduce what is happening [here](http://jsbin.com/qicaxicopo/edit?js,console).

Can you confirm that whether it is a bug or it's me doing something wrong?

Thanks.

**Comment by sibelius** [comment]
related to https://github.com/facebook/relay/issues/2429#issuecomment-386646387

**Comment by jstejada** [comment]
hey @ErrorPro thanks for reporting this. Not sure what's going on off the top of my head. What do you mean by 
> because class is returned before ContainerConstructor is called.
?
I'm not sure I'm following how that's the case in the code

**Comment by ErrorPro** [comment]
@jstejada Hey, static method `getDerivedStateFromProps` of relay fragment is never called because it's always undefined. It happens because lifecycle method is [attached](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/buildReactRelayContainer.js#L74) to a wrapper component **after** the wrapper component is [returned](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/buildReactRelayContainer.js#L101) from `buildReactRelayContainer`.

**Comment by ErrorPro** [comment]
It's been a month guys, any updates?

**Comment by jstejada** [comment]
merging into #2429
