### ISSUE TITLE
Don't send query to node root

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#244]
Not sure I'm phrasing this question right but I'm building a search interface where Relay keeps sending the query inappropriately to the `node` root instead of the `viewer`.

The relevant parts of my schema look like:
```
type Query {
  node(id: ID!): Node
  viewer: User
}

type SearchConnection {
  pageInfo: PageInfo!
  edges: [SearchEdge]
  total: Int
  took: Int
}

type SearchEdge {
  node: Post
  cursor: String!
}

type User implements Node {
  id: ID!
  name: String
  search(before: String, after: String, first: Int, last: Int, query: String): SearchConnection
  post(post_id: Int): Post
  allPosts(before: String, after: String, first: Int, last: Int, query: String): PostConnection
}
```

The first time I run a search query, the query looks like:

`query Router{viewer{id,..._11k0wzb}} fragment _11k0wzb on User{_search58fc16:search(first:30,query:”the query”){}}}`

But if I change the query  using `setVariables` (or `forceFetch`), instead of going to the viewer root, it now goes to node e.g:

`query Search{node(id:"VXNlcjox"){..._2h807t8}} fragment _2h807t8 on User{_search89ucld:search(first:30,query:”new query”){}}}`

As the node root type doesn't know how to resolve searches, it returns null.

I'm probably missing something obvious but how do I make search queries actually search every time?

**Comment by KyleAMathews** [comment]
And fwiw, I'm using react-router-relay.

**Comment by KyleAMathews** [comment]
The problem was in my `nodeDefinitions`. I wasn't loading the user id correctly or identifying the node object. Once I got those working everything worked properly :)

**Comment by KyleAMathews** [comment]
Clearly still figuring this Relay thing out but loving it so far. https://twitter.com/kylemathews/status/640289107122368513

**Comment by josephsavona** [comment]
@KyleAMathews Really happy to heard that! Thanks for filing issues and helping to make Relay better :-)
