### ISSUE TITLE
Optional Chaining

### ISSUE THREAD

**Issue by steida** [facebook/relay#2452]
```
Parse error: SyntaxError: This experimental syntax requires enabling the parser plugin: 'optionalChaining' (68:33) in "components/CreateWeb.js"
```

Not sure why it happens, but babel-eslint has the same problem https://github.com/babel/babel-eslint/issues/595

**Comment by sibelius** [comment]
fixed here https://github.com/facebook/relay/commit/4691145e7c8d2babcedb1b1eff02819321a32ff8

by @dwwoelfel

**Comment by steida** [comment]
@sibelius Is is possible to use Relay from master somehow easily?

**Comment by JCMais** [comment]
`yarn add relay@facebook/relay#master`

version can be used as `github/repo#commitsh-value`
the commit it was downloaded is added to yarn.lock, so running `yarn upgrade` updates to latest revision from master.

**Comment by JCMais** [comment]
npm in reality, it can resolve to any package on github. But this is probably not going to work with relay, mainly because it's a monorepo, and does not store transpiled sources on GitHub
