### ISSUE TITLE
store.get() returning undefined.

### ISSUE THREAD

**Issue by tyrong** [facebook/relay#2456]
I am trying to update the store inside the updater method in commitMutation how ever when i try use store.get(id) it returns me undefined even though relay-devtools shows that the store does include the value i am trying to get.

My code is as follows:
Mutation: 
```
const mutation = graphql' 
  mutation AcceptTradeMutation($tradeId: ID!) {
    acceptTrade(tradeId: $tradeId) {
      status
    }
 }
';
```

commit Method:
```
const commit = tradeId =>  
    commitMutation(env, {
      mutation,   
      variables: { tradeId },   
      onCompleted: (resp, error) => {...},   
      onError: (err) => {...},    
      updater: (store) => {   
        const x = store.get(tradeId);    
        // tradeId === '5b0916b1cd83ce20e454f315 '
        console.log(x) // LOGS UNDEFINED  
      },   
  }); 
```  

And this is my relay-devtools:
![screen shot 2018-05-26 at 10 00 56 pm](https://user-images.githubusercontent.com/18492891/40575889-d06fe7de-6130-11e8-8743-5d3a81f0998d.png)

Thanks

**Comment by sibelius** [comment]
I think you should use globalId instead of `5b0916b1cd83ce20e454f315`

check here https://facebook.github.io/relay/graphql/objectidentification.htm

and the js implementation https://github.com/graphql/graphql-relay-js/blob/master/src/node/node.js#L115

**Comment by kikoseijo** [comment]
What about this space on your id?
 // tradeId === '5b0916b1cd83ce20e454f315 '

**Comment by babangsund** [comment]
Could this be closed? 🙂

**Comment by sibelius** [comment]
use globalId
