### ISSUE TITLE
Add clarifications/missing specifications about order of edges to the relay cursor connections specification

### ISSUE THREAD

**Issue by jedwards1211** [facebook/relay#2466]
Recently while working on improving `graphql-sequelize`'s implementation of connections, I discovered that, as far as I understand, someone misinterpreted the specification: their implementation returns `edges` in the opposite order when the `last` argument is used.  This also means the `startCursor` and `endCursor` are swapped, and their reverse pagination test fetches the previous page by requesting `last: 3, before: pageInfo.endCursor`.  But as far as I understand `before` should always take the `startCursor` of the current `pageInfo`.

I've submitted a PR to fix their implementation but I'd also like to help prevent this kind of misinterpretation for anyone in the future.

Adding the following clarifications to the Relay Cursor Connections Specification would precisely specify the ordering of `edges`:
* The ordering of `edges` should be the same when using `first/after` as when using `last/before`, all other arguments being equal
* To fetch the next page one should use `after: pageInfo.endCursor`, not `after: pageInfo.startCursor`
* To fetch the previous page one should use `before: pageInfo.startCursor`, not `before: pageInfo.endCursor`
* When `before: cursor` is used, the edge closest to `cursor` should come **last** in the result `edges`.
* When `after: cursor` is used, the edge closest to `cursor` should come **first** in the result `edges`.

**EDIT**: merrywhether pointed out that `startCursor` and `endCursor` are not standard right now, so I've updated my PR to refer to the edge cursors instead.

**Comment by merrywhether** [comment]
It seems like https://github.com/facebook/relay/issues/2457 would have to happen first, since `startCursor` and `endCursor` aren't even listed as required fields on the `pageInfo` object.

**Comment by jedwards1211** [comment]
@merrywhether actually I could rewrite my changes so that they refer to the cursors of the first and last edge instead of `startCursor` and `endCursor`.

**Comment by merrywhether** [comment]
The problem is that Relay doesn't fall back to using the first and last edge cursors.

**Comment by jedwards1211** [comment]
i know, but that doesn't mean that the current spec is flawed, it just means relay isn't respecting it.  It's still worth adding this clarification to the spec as it stands.

**Comment by merrywhether** [comment]
Makes sense. I'm just curious about the official stance on this issue:

>Does Relay officially require a GraphQL spec extension or is its implementation flawed and up for re-engineering?

I can see pros to either direction, so it's difficult to know what to push on. As you pointed out in the other issue, the Relay connections spec starts out implying it works with standard GraphQL, but I suspect that is a holdover from Relay Legacy.
