### ISSUE TITLE
Local gulp error running TodoMVC example from README

### ISSUE THREAD

**Issue by mjw56** [facebook/relay#248]
I tried running the TodoMVC example from the README file but got the below error. 

I'm running node 0.12.3 and npm 3.2.2. I also have gulp CLI 3.9.0 installed globally.

Running npm install from ```relay/``` first solved the issue.

```bash
$ cd relay/examples/todo && npm install                                                                            [1:24:44]

> react-relay@0.2.1 prepublish /Users/mikewilcox/dev/relay
> npm run build


> react-relay@0.2.1 build /Users/mikewilcox/dev/relay
> [ $(ulimit -n) -lt 4096 ] && ulimit -n 4096; gulp

[01:24:59] Local gulp not found in ~/dev/relay
[01:24:59] Try running: npm install gulp
```

**Comment by steveluscher** [comment]
Thanks for bringing this up!

The examples used to depend on the npm `react-relay` module, but they've since been changed to depend on `"../../"` to allow local development.

We either need to:

1. Document this.
2. Automate the building of `react-relay` when you try to install/run the examples.
