### ISSUE TITLE
__clientField directive sets field to undefined

### ISSUE THREAD

**Issue by steida** [facebook/relay#2488]
Client schema is super awesome. I recommend this article https://medium.com/@matt.krick/replacing-redux-with-relay-47ed085bfafe.

However, there is a little bug or a feature, not sure. Note I have to use alias to get original text value, because `@__clientField(handle: "draftText")` sets the text to undefined, for some reason.

Am I doing something wrong or not?

![screen shot 2018-07-15 at 16 16 00](https://user-images.githubusercontent.com/66249/42734820-62deb330-884a-11e8-8328-a9d5f5077b8b.png)

**Comment by sibelius** [comment]
Do u have a handler for draftText?

**Comment by steida** [comment]
Sure I have. It works as expected. Except text is undefined for some reason.

https://github.com/este/este/blob/master/components/app/createRelayEnvironment.js#L58

**Comment by renatobenks** [comment]
@steida you have tried debugging right here https://github.com/este/este/blob/master/components/app/handlerProvider.js#L25, in the `value`? You shouldn't be using the `JSON.parse` to parse the `value`, for then, uses it on `record.setValue`?

**Comment by steida** [comment]
Sorry, but I don't see where I am using JSON.parse. Or I don't understand your comment.

**Comment by BorisTB** [comment]
I don't think this is a bug, you just have to set value to payload.handleKey in handler

`record.setValue(record.getValue(payload.fieldKey), payload.handleKey)`

**Comment by steida** [comment]
@BorisTB Thank you.
