### ISSUE TITLE
react-dom missing in the peerDependencies

### ISSUE THREAD

**Issue by samuelbriole** [facebook/relay#2491]
I just upgraded relay from `1.4.1` to `1.6.0` and encounter the same bug as #2447

I tried to understand why yarn didn't automatically upgraded `react-dom`, and I found out that `react-dom` is missing in the peerDependencies.

Here is an extract of the output when I type `yarn info react-relay`:

```js
{
  dependencies: {
    'babel-runtime': '^6.23.0',
     fbjs: '^0.8.14',
     'prop-types': '^15.5.8',
     'relay-runtime': '1.6.0'
  },
  peerDependencies: {
    react: '^16.3.0'
  },
}
```

**Comment by sibelius** [comment]
Check release notes https://github.com/facebook/relay/releases/tag/v1.6.0

```
Breaking:

The minimum React dependency was raised to ^16.3.0
```

Relay does not depend on react-dom as it work on react-native as well

so react-dom should have the correct peerDeep on react instead

**Comment by Vernie2** [comment]
Ext.mem. catagory API17 for accelerator on video.vid-sys.com

**Comment by Vernie2** [comment]
Ext.mem. catagory API17 for accelerator on video.vid-sys.com
