### ISSUE TITLE
Optimistic response for updated connections field?

### ISSUE THREAD

**Issue by sgwilym** [facebook/relay#250]
I have a mutation that changes a field on every node in a connection — like a `Book` object with a `pages` connection, where you change the `pageNumber` of each `page`.

At the moment I'm doing this as a `FIELDS_CHANGE` mutation, the field that’s changing being the `pages` of the `book`. This works great — the only problem is that I'd like to have this update optimistically.

I've tried returning an optimistic response that looks like this:

```js
getOptimisticResponse() {
  return {
    updatedBook: {
      id: this.props.book.id,
      pages: reorderPages(this.props.book.pages)
    }
  }
}
```

Where `reorderPages` is an imagined function that returns an object conforming to the structure of a connection field, with the `node`s containing their updated `pageNumber` values. But this doesn’t seem to do anything.

How should I be doing this?

**Comment by sgwilym** [comment]
Dang, I was caught out by #119.

**Comment by wincent** [comment]
Thanks for the report, @sgwilym, and glad that you where able to get to the bottom of things.
