### ISSUE TITLE
RefetchContainer refetchVariables do not get updated

### ISSUE THREAD

**Issue by kenips** [facebook/relay#2506]
Hello Relay team,

I'm trying to build something similar to https://facebook.github.io/relay/docs/en/refetch-container.html#loading-more-data but using page and pageSize on my connection instead. I managed to get everything working only for the first page. The page variable would not increase after the first page and it seems to be a bug. Here's my createRefetchContainer:

```
export default createRefetchContainer(
  OrganizationsTable,
  graphql`
    fragment OrganizationsTable on Query
      @argumentDefinitions(page: { type: "Int", defaultValue: 1 }, pageSize: { type: "Int", defaultValue: 3 }) {
      organizations(page: $page, pageSize: $pageSize) {
        edges {
          node {
            ... on Organization {
              id
              name
            }
          }
        }
      }
    }
  `,
  graphql`
    query OrganizationsTable_RefetchQuery(
      $page: Int
      $pageSize: Int
    ) {
      ...OrganizationsTable
        @arguments(
          page: $page
          pageSize: $pageSize
        )
    }
  `,
);
```

and here's my `_fetch`:

```
_refetch = () => {
    this.props.relay.refetch(
      // TODO: relay is broken?
      ({ page, pageSize }) => {
        return { page: page + 1, pageSize };
      }
    );
  }
```
When `refetch` is first called I'm getting `{ page: 1, pageSize: 3 }` and returned `{ page: 2, pageSize: 3 }` so everything is great. I see the next page fetched. When I refetch again, I see that i'm getting the `{ page: 1. ... }` again instead of `{ page: 2, ... }`.

Further digging I see that right before my `refetchVariables` callback is called, at [ReaactRelayRefetchConatiner.js:L334](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayRefetchContainer.js#L334), I see the following probing in console:
<img width="227" alt="image" src="https://user-images.githubusercontent.com/794915/44053245-10b32d0a-9f0d-11e8-9ada-b087a555592e.png">

So, my question is, is this a bug? I'm expecting to receive `this.state.localVariables` in this case, but Relay is calling `this._getFragmentVariables()` which are outdated. Or should [the line setting localVariables](https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayRefetchContainer.js#L363) be updated? I see a TODO there. Thanks for your time, guys!

**Comment by sibelius** [comment]
Check our relay guideline to paginate using refetch containers

https://github.com/entria/guidelines/blob/master/relay/flatlist-relaymodern.md#onendreached-relay-modern-createrefetchcontainer

.refetch is tricky

it contains only the first fragmentVariables passed to the fragment, you should keep this in your component state

**Comment by kenips** [comment]
@sibelius thanks. Yeah I can keep track of state in my component. But I'm wondering why refetch can't just do:

from this:
```
let fetchVariables =
        typeof refetchVariables === 'function'
          ? refetchVariables(this._getFragmentVariables())
: refetchVariables;
```
 to:
```
let fetchVariables =
        typeof refetchVariables === 'function'
          ? refetchVariables(this.state.localVariables || this._getFragmentVariables())
: refetchVariables;
```

which seems to be more of what's it's advertising? (and would fix my issue here...)

**Comment by sibelius** [comment]
Try to send Relay code and see if it solves your use case, then send a pr

**Comment by kenips** [comment]
Thanks @sibelius. It does, and will do!
