### ISSUE TITLE
updateSchema error

### ISSUE THREAD

**Issue by mfirry** [facebook/relay#251]
Can't seem to be able to write simple query with my [schema](https://gist.github.com/mfirry/10aeeb8fdf2352d8fb96).

When running `upadateSchema` I always get `Error: Ticket.id field type must be Output Type but got: [object Object].`

I tried mimicking the one on the tutorial but to no avail
```
var queryType = new GraphQLObjectType({
  name: 'Query',
  fields: () => ({
    node: nodeField,
    ticket: {
      type: ticketType,
      resolve: () => getTicket(),
    }
  })
});
```
I must be missing something.

Thanks

**Comment by l-urence** [comment]
Try to change the id definition in your schema. 

```js
fields: () => ({
    id: {
      type: globalIdField('Ticket'),
      description: 'The id of the flight.'
    },
...
```

to 

```js
fields: () => ({
    id:  globalIdField('Ticket'),
...
```

**Comment by steveluscher** [comment]
:+1: That should do it. Thanks @l-urence!

**Comment by mfirry** [comment]
Great, I'll try this out first thing tomorrow.
Should the [tutorial](https://github.com/facebook/relay/blob/master/docs/QuickStart-Tutorial.md) be updated accordingly or is my case somehow different?

**Comment by steveluscher** [comment]
It looks like the tutorial follows the pattern mentioned by @l-urence above:

```
id: globalIdField('Game'),
/* ... */
id: globalIdField('HidingSpot'),
```

**Comment by mfirry** [comment]
You're totally right. My bad. Thank you so much.
