### ISSUE TITLE
Allow Connection Type to end in something other than "Connection"

### ISSUE THREAD

**Issue by adrice727** [facebook/relay#2513]
As as I understand it, based on the [Relay Spec](https://facebook.github.io/relay/graphql/connections.htm#sec-Connection-Types), Connection Types must end in "Connection".  This is likely going to create confusion for consumers of our API as [connections](https://tokbox.com/developer/sdks/js/reference/Connection.html) are one of the primary abstractions in our platform, and in turn, one of the most important objects exposed through the TokBox API.  

For example, part of our schema looks like:

```graphql
connections {
  edges {
    node {
      publishers {
        edges {
          node {
            subscribers { 
              . . .
            }
          }
        }
      }
    }
  }
}
```

  With this requirement, we would be introducing:

- `ConnectionsConnection`
- `PublishersConnection`
- `SubscribersConnection`

These are all things that _seem_ like they could exist as part of our platform, but do not.  It's important enough of that we're at the point of dropping Relay support.  So . . . is it possible to allow for an alternative to "Connection"?

**Comment by hbaqai** [comment]
I think others could run into the same issue. Connection is a relatively overloaded term even outside of the TokBox platform. LinkedIn, for example, uses the word Connections for people in their social graph.

**Comment by sibelius** [comment]
you only need `Connection` for your fragments on `Connection` not in the connections itself

check this: https://github.com/entria/entria-fullstack/blob/master/packages/app/src/UserList.tsx#L112
