### ISSUE TITLE
[RFC] Allow for more complex configuration of relay-compiler / babel plugin

### ISSUE THREAD

**Issue by alloy** [facebook/relay#2518]
While I’m not a fan of lots of configuration –and thus think that where possible we should have generally applicable defaults, such as with persisted queries– I’m starting to feel like relay-compiler + the babel plugin could do with a more advanced way of configuration, in the form of an evaluated JS config module:

* Being able to specify custom scalar mappings (#2162)
* Specifying custom persisted query logic (
https://github.com/facebook/relay/pull/2354#issuecomment-36927167, 0https://github.com/facebook/relay/pull/2354#issuecomment-395483449, and #1846)
* Currently the path to the single artefact directory needs to be passed to _both_ the CLI and the babel plugin. It would be great if this could be specified in one place instead. (https://github.com/relay-tools/relay-compiler-language-typescript#configuration)

```js
export default {
  schema: "./data/schema.json",
  language: "typescript",
  artifactDirectory: "./src/__relay_artifacts__",
  customScalars: { URL: "String" },
  persistedQueries: (…) => { … },
}
```

**Comment by alloy** [comment]
cc @jstejada @kassens

**Comment by jstejada** [comment]
cc @alunyov

**Comment by sibelius** [comment]
consuming a user babel config in js is pretty easy

you can just import like a normal `.js` file

**Comment by bencallaway** [comment]
@alloy Is the "language" option already supported? If not how would that work? Should it compile on the fly?

**Comment by alloy** [comment]
@bencallaway It is. See https://github.com/relay-tools/relay-compiler-language-typescript#relay-compiler-language-typescript

**Comment by bencallaway** [comment]
@alloy I have been using the `relay-compiler-language-typesecript` plugin, and very thankful for your work there btw. I was curious about the `babel-plugin-relay` config itself. As of `1.7.0-rc.1` it appears "language" is not a plugin option (yet? <- Partly my previous question). However, after looking back at the code I now see there's a `buildCommand` option that I had failed to notice before (https://github.com/facebook/relay/blob/v1.7.0-rc.1/packages/babel-plugin-relay/BabelPluginRelay.js). It would seem I can pass in my own `relay-compiler --language typescript` and the compilation will occur on the fly. (I am currently doing this with a separate `--watch` process while developing.

**Comment by bencallaway** [comment]
Ok, retracting some of that last comment. It appears that `buildCommand` does not handle compilation on the fly, it's just used for error reporting. I'll need to spend some more time looking through the plugin's source.

**Comment by alloy** [comment]
Oh I see. No currently it remains a two-step process. `relay-compiler` should be used to generate the artefact files, the babel plugin to switch out the `graphql` tags with the corresponding artefacts.

**Comment by alloy** [comment]
> Re implementation, it would be great to have this as a standalone package.

Do you mean in the same way how `relay-compiler` and `react-relay` are separate packages but part of this monorepo?

**Comment by josephsavona** [comment]
Yeah, in this repo as a sibling package to relay-compiler/

**Comment by alloy** [comment]
> …allow command-line arg versions for all arguments.

I'm going to start with PRs to make all features available through the CLI first, as that needs to get done anyways.

**Comment by AugustinLF** [comment]
Regarding config coming from different places, I know that jest use a `jest-config` package that centralise this logic. You can find it [here](https://github.com/facebook/jest/tree/master/packages/jest-config). It was explained by @cpojer in a [video](https://www.youtube.com/watch?v=3YDiloj8_d0) where they explained the overall architecture of jest.

**Comment by ivosabev** [comment]
I believe this is related: https://github.com/facebook/relay/issues/2702

**Comment by alloy** [comment]
> Be consistent about naming of configuration keys and the corresponding command-line overrides

@josephsavona I noticed that we have camelCase _and_ kebab-case options currently. camelCase would make consistency between CLI and JS configuration easier and probably more natural, but kebab-case is ofc more natural to CLIs. Should we choose one case and, if so, which one?
