### ISSUE TITLE
Should `@relay(mask: false)` apply recursively to nested fragments?

### ISSUE THREAD

**Issue by alloy** [facebook/relay#2524]
The [docs on the directive](https://github.com/facebook/relay/blob/d3cfd58501d011690f3a7305c728ff5d90abd10b/website/versioned_docs/version-1.6.0/Modern-GraphQLInRelay.md#relaymask-boolean) mentions:

> recursively including the data from the fields of the referenced fragment

Is the “recursively” part here meant to indicate that it should unmask _all_ nested fragments, even when their parents don’t include the directive themselves?

I’m asking this because we often need to manually craft data in our tests/stories and currently have no good way to get complete typings for that data. As such, it would be great if we could use this directive to emit artefacts with typings that covers the response for the entire tree of fragments.

----

For example, consider the following fragments:

```gql
fragment SharedInternUser on InternUser {
  id
  name
}

fragment Component_internUser on InternUser {
  manager {
    ... SharedInternUser
  }
}

fragment Component_user on User {
  internUser {
    ...Component_internUser @relay(mask: false)
  }
}
```

…would we expect that to result in unmasked data (and typings) like the following?

```js
{
  internUser: {
    manager: {
      id
      name
    }
  }
}
```

**Comment by alloy** [comment]
If this is not how it should already behave, then would it be possible to add a new parameter that makes this possible? e.g. `@relay(maskRecursively: false)`

(Something like the following might read nicer, but I assume the ship has set sail on that? `@relayMasking(enabled: false, recursive: true)`)

**Comment by cvle** [comment]
I'd love this. I was evaluating if it makes sense to use the same fragment in a query and in a mutation, making sure the data requested is always the same. However the types generated were not usable e.g. for the optimisticResponse when nested fragments were present.

**Comment by dminkovsky** [comment]
This doesn't make sense to me because it would break the clean compositional functionality that's currently in place. The way it works now guides you develop components that compose correctly. That's been huge for me.

**Comment by alloy** [comment]
@dminkovsky This proposal in no way does away with that, I think most of us that like to use Relay do so for features like that.

This is for those cases where you really do want to inject all required data manually, of which there are legit cases in tests/stories, but also in codebases that are transitioning to Relay and conditionally need to have data injected from other sources.

Specifically, this proposal does not change the way in which the composed components work. For normal operations you would continue to work on them in isolation as normally intended.

**Comment by dminkovsky** [comment]
@alloy If `mask=false` resulted in unmasking all nested `mask=false` variables, it leads to broken composition because a `FragmentContainer`'s fragment should declare the fields needed by the component that it directly wraps. That's the abstraction it is meant to provide. If you need to unmask further—meaning you need those fields there in that component—why don't you include those fields in the fragment for that component? That's what the whole thing is about, declaring data where it is needed. 

Unmasked fragments are most useful for fragments that are shared locally by multiple fragments within a module.

**Comment by alloy** [comment]
You’re missing the point raised in the OP. In special cases we want to manually inject data for a container and all nested container children. We would like to get types emitted for this full payload so that we get type checking on all data required.

We do not need access to child data in any of the nested containers, we want access to all the data in the root container, or more specific to our case, we need the side-effect of that which is to get types emitted for all that data.

**Comment by alloy** [comment]
Superseded by https://github.com/facebook/relay/issues/2597.

@cvle I'd love to hear your thoughts there.
