### ISSUE TITLE
Subscriptions: Push vs. Pull

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#253]
I was curious on what the Relay team is thinking re: subscriptions on the question of whether data is pushed to Relay or if Relay controls when it pulls data.

I've been researching Kafka recently and thought [their discussion of the design for their consumer API was relevant](https://kafka.apache.org/08/design.html).

>Another advantage of a pull-based system is that it lends itself to aggressive batching of data sent to the consumer. A push-based system must choose to either send a request immediately or accumulate more data and then send it later without knowledge of whether the downstream consumer will be able to immediately process it. If tuned for low latency this will result in sending a single message at a time only for the transfer to end up being buffered anyway, which is wasteful. A pull-based design fixes this as the consumer always pulls all available messages after its current position in the log (or up to some configurable max size). So one gets optimal batching without introducing unnecessary latency.

This matches well I think with many of the goals of Relay e.g. working well on low-bandwidth devices that often go off line. Relay could dynamically change how often it polls for new updates depending on network quality, battery level, etc. On very poor connections/low-battery, Relay could wait minutes even between polls. On good connections, Relay could use long-polling or WebSockets. While waiting for a new pull request, the server could queue updates as well as squash objects with multiple updates.

Pull instead of push also solves the out-of-order problem that affects naive push messaging. The server can track the read position of each consumer and ensure that new messages are sent in the correct order when pushed.

**Comment by josephsavona** [comment]
> the question of whether data is pushed to Relay or if Relay controls when it pulls data

Subscriptions are still an active area of work so details are likely to change (check the GraphQL slack channel for discussion). Specifically for Relay, the basic idea is that the application can declare that it wants to receive updates for some subset of events (perhaps "likes on story xyz") and be notified when such an event occurs (via push, with updated data). Similar to queries and mutations, this isolates the "what" from the "how" - and could allow for the network layer to use a variety of different strategies (polling, websockets, etc.).

**Comment by wincent** [comment]
I'd also note that this doesn't necessarily be a dichotomy of either push or pull, it could actually be a mix of both (ie. periodic, eager push notification of the availability of updates, but with the client making the call about when to actually pull them). Regardless, separating the "what" from the "how" is the right idea (both on the Relay side on the client, but also on the server side where there are a bunch of ways that subscriptions *could* be implemented, but GraphQL won't want to be overly opinionated about the details.

**Comment by KyleAMathews** [comment]
>periodic, eager push notification of the availability of updates, but with the client making the call about when to actually pull them

Agree a mix could be better depending on tradeoffs you're making. My main point is naive push leads to out-of-order/missing updates. But to your what vs. how point, this is probably not a GraphQL/Relay concern but something I'd need to build into my own application. For many applications, naive push would be fine (e.g. stock ticker) so missing an update or two wouldn't matter.
