### ISSUE TITLE
Concern about unstable_read and SSR

### ISSUE THREAD

**Issue by johntran** [facebook/relay#2544]
Hi there,

@TrySound brought up a good point [in this comment](https://github.com/facebook/relay/commit/98e866f5e0fc3548f0577bf081df0507832b15f9#commitcomment-30685974) about how SSR wouldn't work for components where `unstable_read` is being used. 

It seems to be best to revert the change back to use `<ReactRelayContext.Consumer>` and use `unstable_read` in the `relay-experimental` package.

@TrySound provided a codesandbox repo to show how `unstable_read` breaks SSR: https://codesandbox.io/s/l5j35928xl

Thoughts?

**Comment by josephsavona** [comment]
cc @jstejada

**Comment by jstejada** [comment]
Thanks for bringing this up @johntran, @TrySound. React is actually going to [remove unstable_read](https://github.com/facebook/react/pull/13861), so  we will end updating this in a way that is also SSR compatible

**Comment by TrySound** [comment]
Well, it's not quite removed. It's hidden in react internals. Libraries still can use it for own purpose. For example in relay it would be nice to have an api without render props and HOCs like this
```js
const fragment = createFragment(
  graphql``
)

const Component = props => {
  const user = fragment.read(props.user)
  return null
}
```
