### ISSUE TITLE
Container is not rerendered when calling refetch

### ISSUE THREAD

**Issue by ntelkedzhiev** [facebook/relay#2553]
I'm using RelayCache to load the initial data and then calling `refetch` in `componentDidMount()`:
```
 this.props.relay.refetch(refetchVariables, null, () => console.log('Refetch Done!'), {force: true})
```

However, the QueryRenderer does not render when the refetch is executed, nor the callback of the refetch function is called. What is more interesting is that if I wrap the refetch call into a setTimeout everything works fine:

```
  setTimeout(() => {
      this.props.relay.refetch(refetchVariables, null, error => console.log('Refetch done'), {force: true});
  });
```

Any suggestions why this is happening?

**Comment by sibelius** [comment]
QueryRenderer should be used only for the first query (on root component, like the first react component in a route)

Only your refetchContainer should rerender, check the docs https://facebook.github.io/relay/docs/en/refetch-container.html

QueryRenderer won't rerender if you won't change variables

**Comment by ntelkedzhiev** [comment]
@sibelius Issue persists even if the variables are different. The RefetchContainer does not rerender.

**Comment by jgcmarins** [comment]
@ntelkedzhiev I've made a comment here: https://github.com/ntelkedzhiev/relay-refetch/commit/2b1084f4c934caa89261bb8d9ca071e8187fface#r31043442

**Comment by ntelkedzhiev** [comment]
@jgcmarins Thanks but this is unrelated (and false according to the docs).

**Comment by ntelkedzhiev** [comment]
Any ideas?

**Comment by josephsavona** [comment]
The most likely explanation for a RefetchContainer not updating is that the data being refetched doesn't overlap with the data that the fragment is selecting - usually because the variables don't line up. I would double check the query and variables.

**Comment by jgcmarins** [comment]
relay-dev-tools can help you with RelayNetworkLogger
You can also check network tab

**Comment by ntelkedzhiev** [comment]
I did check the query and the variables. None of the usual solutions for this type of problems make sense here. 

As I said above, wrapping the relay refetch call in a simple `setTimeout()` solves the issue which is what makes this issue "interesting". Please see the demo I referenced.

**Comment by ntelkedzhiev** [comment]
The problem is here: 

https://github.com/facebook/relay/blob/d7964972c86ed8b292bc379c4d85cd04f6dbd442/packages/react-relay/modern/ReactRelayRefetchContainer.js#L113-L124

For some reason the first refetch request passes the if. Maybe because it was initiated before the initial request (from the QueryRenderer), and in the meantime the initial payload rendered the props so they point to new records (compared to where they pointed to at the time of the first refetch).

**Comment by xyy94813** [comment]
pass render-variables can resolve this issue in my project.

```js
const q = { effecting_true: 1 };
const vars = {
  id: data?.id,
  disablementQ: q,
};
refetchData(vars, {
  q,
});
```

```js
 export default createRefetchContainer(
  DriverDisablementCard,
  {
    data: graphql`
      fragment DriverDisablementCard_data on Driver
        @argumentDefinitions(q: { type: "JsonObject" }) {
        id
        disablements(before: null, first: 30, q: $q) {
          nodes {
            ...DriverDisablementTable_data
          }
        }
      }
    `,
  },
  graphql`
    query DriverDisablementCardQuery($id: ID!, $disablementQ: JsonObject) {
      data: node(id: $id) {
        ...DriverDisablementCard_data @arguments(q: $disablementQ)
      }
    }
  `
);
```

**Comment by sibelius** [comment]
Migrate to relay hooks, if the issue still valid, open another issue
