### ISSUE TITLE
babel-relay-plugin => babel-plugin-relay

### ISSUE THREAD

**Issue by thejameskyle** [facebook/relay#256]
The babel plugin in `scripts/babel-relay-plugin` should be named according to the `babel-plugin-*` naming scheme. However, the name is currently taken by an empty project.

I've contacted the package owner on npm and CC'd npm support according to https://docs.npmjs.com/misc/disputes. Hopefully the owner releases the name without any issue.

**Comment by thejameskyle** [comment]
The module name has been released by the owner https://www.npmjs.com/package/babel-plugin-relay

**Comment by thejameskyle** [comment]
I've reseved the name for now and added all the owners of the `babel-relay-plugin` module on npm to it. Feel free to remove me and replace it, if you have any issues just ping me.

**Comment by devknoll** [comment]
p.s. the intention was to publish #206 separately under this package name, but since there's interest in having this functionality in the current `babel-relay-plugin` / I haven't had time to actually work on the project yet, I went ahead and released the name.

**Comment by josephsavona** [comment]
@devknoll thanks!

**Comment by josephsavona** [comment]
also thanks @thejameskyle!

**Comment by devknoll** [comment]
@josephsavona this happening? :wink:

**Comment by josephsavona** [comment]
@devknoll Yeah, we should eventually move to the recommended naming scheme. This might take a few rounds of PRs:
- change the package name in the code (and then publish it)
- update everything to depend on it
- also update the docs

Community help appreciated! ;-)

**Comment by devknoll** [comment]
Thanks for the list and the tag, that's what I wanted to see :+1:

**Comment by thejameskyle** [comment]
ping

**Comment by BerndWessels** [comment]
@devknoll steveluscher @josephsavona Will this replace the `babel-relay-plugin` on NPM ?
If so it should still be in sync with the version number of `react-relay` to avoid confusion ?!
But it looks like there is a `1.0.0` published to NPM - but `react-relay` is only `0.6.1`.
Can you please fix this or am I mistaken here?

**Comment by frodosamoa** [comment]
:+1:

**Comment by schickling** [comment]
Until this is happening we've built [babel-plugin-react-relay](https://github.com/graphcool/babel-plugin-react-relay) supporting different source types such as JSON files, JS schema definitions and even URL schema endpoints.

This is meant to provide a more convenient and powerful solution without the need for scripts like `build/babelRelayPlugin.js`.

**Comment by josephsavona** [comment]
See my [comment on the PR](https://github.com/facebook/relay/pull/732#issuecomment-210023522) - we're happy to change the name, but the change has to be done incrementally in order to not break things for us. If someone wants to work on this, send a PR!

**Comment by nodkz** [comment]
BabelRelayPlugin with hot reload 🔥
Reflect GraphQL Schema changes in json file without completely restarting dev server.
https://github.com/nodkz/babel-plugin-transform-relay-hot
