### ISSUE TITLE
Refetch from one container doesn't refresh props in another

### ISSUE THREAD

**Issue by earksiinni** [facebook/relay#2561]
I have a refetch container (A) and a paginate container (B). They are siblings in the React hierarchy.

The refetch query on A references the fragment on B. When I call refetch on A, I can see the correct query being sent on the wire via the network tab in my dev tools along with all the correct variables, and I receive the correct response. Therefore, I expect that the fragment props on B will update because the refetch should update the underlying data store with the correct and work its magic. Instead, the props on B don't get updated, they remain the same.

Any idea why this is? Am I missing some underlying assumption (i.e., that refetches will only refresh the props of the container on which they're called)?

**Comment by earksiinni** [comment]
Side note, I've looked through the issues and seen core team members casually referring to "subscriptions" in the context of refetching and updating variables. I'm not sure that it's relevant to my issue (my variables are changing when I do the refetch), but I want to say that it's very confusing to newcomers. Are the "subscriptions" referring to GraphQL subscriptions or is that term being used to refer to some kind of internal mechanism by which fragments are notified of changes to store state?

**Comment by robrichard** [comment]
I wouldn't expect a refetch or pagination container to update a sibling container.

Data is resolved from all Relay containers using variables that are set in React context. QueryRenderers, PaginationContainers, and RefetchContainers all set React context when they make a GraphQL request. Children components read context set by the closest parent component.

In your case, the component that did not initiate the query would still read the original context set by the parent of both siblings.

**Comment by earksiinni** [comment]
Fair point, sounds like my expectations were off. It would be helpful if the docs explicitly stated when the React context gets set.

I went ahead and refactored:

1. Container A sets shared state between A and B (e.g., Redux, parent container's React state) that updates B's props when state changes
2. Container B now has a call to `refetchConnection` inside of its `componentWillReceiveProps`. It doesn't pass the props using `refetchConenction`'s argument, but rather the props are set using the paginate container's `getVariables` function.
3. I can see the correct network request and response on the wire when A changes the shared state.
4. Container B still doesn't update props.

Any ideas?

**Comment by earksiinni** [comment]
I've done a little more debugging. It looks like my update is correctly appearing inside of the payload passed to the `onNext` function in the pagination container, as shown here: https://github.com/facebook/relay/blob/master/packages/react-relay/modern/ReactRelayPaginationContainer.js#L731

If I'm reading the code correctly, however, it looks like nothing happens with the payload argument. It just gets discarded. What is `onNext` inside the pagination container used for?

**Comment by earksiinni** [comment]
Oy, this is my fault. I was passing the new refetch variables in the first argument rather than in the third argument to `refetchConnection`. I was doing this because I saw someone else do that in some issue here and assumed that it was correct. Everything works fine when I pass the variables in an object as the third argument, as per the documentation.
