### ISSUE TITLE
Wasteful rerender during Pagination

### ISSUE THREAD

**Issue by cvle** [facebook/relay#2562]
*Update: Regression since version `5.0.0`.*

I have done some performance analysis and just realised that during a pagination using the `createPaginationContainer` there is a lot of wasteful rerender that impacts the performance the larger the list gets. 

I have created a minimal example here: https://github.com/cvle/relay-wasted-render

![image](https://user-images.githubusercontent.com/14221600/47859490-bd23e000-ddee-11e8-824c-d1d61b3789bc.png)

You can see on the screenshot that whenever I load more, the whole list gets rerendered and I haven't found a way yet to optimise rendering using the `shouldComponentUpdate` approach. It seems like all fragment data has changed even though e.g. the `me` fragment has not been mutated / changed.

We are currently transitioning from Apollo to Relay and we occasionally render a comment list with more than 100 comments. The rendering during a pagination slows down by several seconds. We found a way to optimise this in Apollo, but not in Relay. I think Relay should be able to tell if a given fragment has changed or not and only change the data if needed (preserving immutability).

Not sure if this is considered a bug report or a feature request :-)

**Comment by sibelius** [comment]
in which version? can you check latest 2.0.0-rc.1 as well?

can you do this check using refetch container (check this guide https://github.com/entria/guidelines/blob/master/relay/flatlist-relaymodern.md of how to do pagination using refetch container)?

**Comment by cvle** [comment]
Thanks @sibelius, verified that this has been fixed in `2.0.0-rc.1`! Omg this is awesome :-D

**Comment by cvle** [comment]
There is a regression since `v5.0.0`, the pagination container always render every single item even when it is not necessary. I've upgraded the example at https://github.com/cvle/relay-wasted-render to the latest relay version `10.1.2`
