### ISSUE TITLE
Docs don't explain data ID's

### ISSUE THREAD

**Issue by earksiinni** [facebook/relay#2572]
I'm still relatively new to Relay, but today I discovered something fundamental by accident via debugging that suddenly made the entire library click for me. The following is going to seem obvious to probably everyone else, but that's the point; bear with me.

When you execute a query, every object returned is expected to have an id field. The value of that id field becomes what's known as the "data id," mentioned sporadically throughout the docs but never actually explained. If the server doesn't provide an id, then the data id gets autogenerated (also happens regardless in some cases, e.g., pagination containers). The data id, whether provided or generated, is a key for each record in the Relay store.

When you render the query to props, Relay maps the values passed to the props to the records in its store, and it uses the data id as a primary key. If you execute a new query that updates information in the store, it will also update props *if and only if* the data id's for the updated records in the store match the data id's of the records that were being rendered in the props.

Understanding the ramifications of the above behavior are critical to understanding Relay. Otherwise, Relay becomes a glorified version of `fetch` that renders props once and then never updates them again (or updates them very unreliably). I've been using Relay for over a month, banging my head against the wall trying to understand what the purpose of the store is and how props get updated after queries. **It took me over a month to understand why Relay has a store and how props get updated.** Think that one through.

The docs don't explain anything about how important the data ID is, why/how it's set and how updating records with the same data ID will propagate changes to props. The section on the store is more or less only applicable to mutations. I'm not sure how this could have been overlooked, it's basically the whole point of Relay, and yet it's not explained anywhere. The closest thing, and it's not really close at all, is buried in the quick start guide:

> Relay will add an id field if it exists on the type for caching purpose.

Can the team please add documentation about data ID's and props? I don't want to sound hyperbolic, but I'm not sure how newcomer who isn't as stubborn as myself could possibly adopt Relay and not give up within a few days without this info. I'm concerned for the viability of this project without such basic information being provided. I hope at least that other frustrated beginners can find this issue on GH and understand a bit more clearly.

P.S.: Are all the gaps in the documentation a result of moving from Relay "classic" to "modern"?

**Comment by josephsavona** [comment]
Thanks for the feedback! You're right that object identity an essential aspect of Relay's caching - this is discussed in a few places in the docs but most specifically the [runtime architecture](https://facebook.github.io/relay/docs/en/runtime-architecture.html). We're open to suggestions about how to make this concept more obvious - and happy to accept pull requests to improve the docs!

**Comment by yuzhi** [comment]
@earksiinni I am going to close this issues since the information is mentioned in the link Joe pointed out above. Feel free to send us a PR for improving the documentation if you have ideas.
