### ISSUE TITLE
Why queries are collocated while mutations must be separated?

### ISSUE THREAD

**Issue by steida** [facebook/relay#2577]
Just a question in case of someone knows. Feel free to close it.

**Comment by steida** [comment]
I think I got it. React hook useFooMutation can be collocated with FooMutation. OK, that's fine.

**Comment by josephsavona** [comment]
Yup, there’s nothing stopping you defining the mutation in the same file where you use it.

**Comment by steida** [comment]
@josephsavona Except for the name of the file must be ok for Relay Compiler. So we must put hooks in mutations and not vice versa.

**Comment by josephsavona** [comment]
> the name of the file must be ok for Relay Compiler

What specific error did you get?

**Comment by steida** [comment]
@josephsavona I mean naming like FooMutation suffix.
