### ISSUE TITLE
clientMutationId NonNull

### ISSUE THREAD

**Issue by freiksenet** [facebook/relay#258]
Hi!

Currently in the spec the `clientMutationId` in mutations has to be non-null. The requirement seems overly strict - in GraphiQL usage or while using other clients but Relay, one doesn't *have* to use `clientMutationId` to actually make a mutation.

I propose to remove the requirement on non-nullness from clientMutationId, both in input and in payload. Instead one can say that clientMutationId *must* be returned if it was provided.

Pinging stakeholders - @dschafer.

**Comment by dschafer** [comment]
Yeah, I'm fine with this; let's change it to state that clientMutationId *may* be non-null, and it is non-null on the input if and only if it's non-null on the payload. Either way, the value of clientMutationId in the payload must be the value provided in the input, or null if the value was not provided.

**Comment by freiksenet** [comment]
Great! Do you want me to do pull request to the spec?

**Comment by dschafer** [comment]
Yep, go for it!

**Comment by steveluscher** [comment]
Closed by #308.
