### ISSUE TITLE
Relay-compiler example from docs ("GraphQL in Relay" part) isn't generated (Unchanged: 0 files)

### ISSUE THREAD

**Issue by namvt13** [facebook/relay#2582]
Currently, I am do the "GraphQL in Relay" part in the official doc, but some issue comes up: relay-compiler can't seems to generate the ".graphql.js" files from the js and schema.graphql in the example (No error though, just "Unchanged: 0 files"). I even used your "todo" MVC example (Relay example) and built it in there, but the problem still persists. Please take a look!

schema.graphql
schema {
  query: Root
}

type Root {
  dictionary: [Word]
}

type Word {
  id: String!
  definition: WordDefinition
}

type WordDefinition {
  text: String
  image: String
}

DictionaryComponent.js
const DictionaryWordFragment = graphql`
  fragment DictionaryComponent_word on Word {
    id
    definition {
      ...DictionaryComponent_definition
    }
  }
`

const DictionaryDefinitionFragment = graphql`
  fragment DictionaryComponent_definition on WordDefinition {
    text
    image
  }
`

DictionaryQuery.js
const DictionaryQuery = graphql`
  query DictionaryQuery {
    dictionary {
      ...DictionaryComponent_word
    }
  }
`

**Comment by sibelius** [comment]
please provide a failing repo to reproduce this issue

**Comment by namvt13** [comment]
Here the example repo: https://github.com/relayjs/relay-examples
I feel like there is an error in the example code, not the repo though, all the repo code are generated and works well.

**Comment by sibelius** [comment]
do you have __generated__ folders?

**Comment by namvt13** [comment]
Yes, generated folders are there, and the app is working

**Comment by sibelius** [comment]
so there is no problem

it won't regenerate if anything has changed

**Comment by namvt13** [comment]
I meant the repo, not the original folder, but thanks for looking anyway.

**Comment by sibelius** [comment]
ping us on #relay channel of graphql slack, we can help you from there
