### ISSUE TITLE
Gulp + Browserify + Relay

### ISSUE THREAD

**Issue by mfirry** [facebook/relay#259]
Hi,
I'm trying to add `relay` to [this](https://github.com/granze/react-starterify) boilerplate.

This one uses `browserify` and `gulp`.
I've added the required dependencies 
```
    "graphql": "^0.4.3",
    "graphql-relay": "^0.3.2",
    "react": "^0.14.0-beta3",
    "react-dom": "^0.14.0-beta3",
    "react-relay": "^0.2.1"
```

And tried to mimic the todo example.

However at build-time I get 
```
SyntaxError: /Users/braithwaite/react-relay-starterify/src/routes/AppHomeRoute.js: Unexpected token (4:17)
  2 |
  3 | class AppHomeRoute extends Relay.Route {
> 4 |   static queries = {
    |                  ^
  5 |     game: () => Relay.QL`query { game }`,
  6 |   };
  7 |   static routeName = 'AppHomeRoute';
```
I can't really understand the issue here.
It looks like something related to ES6 but the project uses `babelify` to deal with it -> [gulpfile.babel.js](https://github.com/Granze/react-starterify/blob/master/gulpfile.babel.js)

Any hint will be much appreciated.

**Comment by mhart** [comment]
Not sure if this is much help, but I finally got around to publishing a little starter kit I created a while back that uses browserify here: https://github.com/mhart/simple-relay-starter

**Comment by mhart** [comment]
(if you have a look at https://github.com/mhart/simple-relay-starter/blob/master/App.js#L50-L61 you can see you don't really even need to use `Relay.Route` at all)

**Comment by mfirry** [comment]
Thanks a lot @mhart. I'll start again using your starter kit.

**Comment by michshat** [comment]
@mfirry I had run into exactly same issue, I got it working adding es7 features

````
.transform(babelify.configure({
        optional: ["es7.asyncFunctions", "es7.decorators", "es7.exportExtensions", "es7.objectRestSpread", "es7.trailingFunctionCommas", "es7.classProperties"]
    }), { /* opts */ });
````

**Comment by mfirry** [comment]
Awesome! Thank you so much.

**Comment by wincent** [comment]
@mfirry, I'll close this seeing as it looks like you've resolved your issue. Let me know if i've misunderstood and we can reopen this and investigate.
