### ISSUE TITLE
relay-compiler: Remove newline characters from parsed queries

### ISSUE THREAD

**Issue by ryanmcclure4** [facebook/relay#2599]
I am setting up an [Apollo Engine Proxy](https://www.apollographql.com/docs/references/engine-proxy.html) to build some metric data from my GraphQL queries. The proxy is interpreting my queries as invalid because the text queries compiled by relay include newline characters `\n`. I understand this is default js behavior when using template literals. Is it possible to prevent this without writing a custom version of the compiler?

**Comment by sibelius** [comment]
apollo engine is deprecated

![image](https://user-images.githubusercontent.com/2005841/50791063-d726e680-12a7-11e9-8b20-326deded1ed6.png)

try to use apm https://www.elastic.co/solutions/apm

**Comment by ryanmcclure4** [comment]
Gotcha, I'll try out apm - Thanks!
