### ISSUE TITLE
query only works on the id in relay

### ISSUE THREAD

**Issue by sajadghawami** [facebook/relay#2607]
Hey there,

i have this weird problem where i can only query on the id and not on the other fields.

Thats in my schema.graphql:

```js
type Query {
  user(id: String, contractorId: String): user
}
```

This fragment returns the correct values:

```js
    fragment UserTable_usersData on Query
      {
        user (id: "1") {
            lastName
            firstName
        }
    }
```

But doing the following results in a `relay-compiler` error:

```js
    fragment UserTable_usersData on Query
      {
        user (contractorId: "1") {
            lastName
            firstName
        }
    }
```

This is the error:

```
ERROR:
You supplied a GraphQL document with validation errors:
components/Pages/PageAdminArea/User/components/UserTable.js: Unknown argument "contractorId" on field "user" of type "Query".
```

Strangely, i can query the `contractorId` with `graphiQL`.

Whats happening here?

Thank you for you time!

**Comment by sibelius** [comment]
Can you provide a repro?

**Comment by sajadghawami** [comment]
Found the solution. Even tough i generated a new `graphql.schema` it seemed like `relay-compiler` cached and compiled the `fragments` based on the older `graphql.schema`. So i had to delete the `graphql.schema`, let the new one be generated and rerun the `relay-compiler --watch`.

:)
