### ISSUE TITLE
cannot access data after mutation to update store

### ISSUE THREAD

**Issue by sajadghawami** [facebook/relay#2608]
Hey,

so i am trying to create a new record with a mutation and then pass the newly created data into my store to update it. 
I was trying to follow this following article which can be found in other related issues:

https://medium.com/entria/wrangling-the-client-store-with-the-relay-modern-updater-function-5c32149a71ac

The problem is, in this article at some point i need to access the `dataID` in the store to push the newly created data into the current store - but i can't really get the current data from the store.

This is my fragment in the component where i need to update the data.

```js    
fragment UserTable_tableData on Query @argumentDefinitions(
        contractorId: {type: "String"}
      )
      {
        users (contractorId: $contractorId) {
            userId: id
            lastName
            firstName
        }
    }
```

This here is the query for my `QueryRenderer`:

```js
const PageUserOverviewQuery = graphql`
  query PageUserOverviewQuery($contractorId: String) {
    ...UserTable_tableData @arguments(contractorId: $contractorId)
  }
`;
```

The mutation i am calling:

```js
const UserCreateMutation = graphql`
  mutation UserCreateMutation(
    $contractorId: String!
    $firstName: String!
    $lastName: String!
  ) {
    createUser(
      contractorId: $contractorId
      firstName: $firstName
      lastName: $lastName
      ) {
        id
        lastName
        firstName
    }
  }
`;
```

The commitMutation:

```js
    commitMutation(
      environment,
      {
        mutation: UserCreateMutation,
        variables: {
          contractorId: '1',
          firstName: `${firstName}`,
          lastName: `${lastName}`,
        },
        updater: (store) => {
          const payload = store.getRootField('createUser'); 
          const storeRoot = store.getRoot();  // this returns a RelayRecordProxy
          const userData = {
            id: payload.getValue('id'),
            lastName: payload.getValue('lastName'),
            firstName: payload.getValue('firstName'),
          };
          // all these dont seem to work
          const currentUsers1 = store.get('users');
          const currentUsers2 = store.get('users(contractorId:"1")'); 
          const currentUsers3 = store.getRootField('users');
          const currentUsers4 = store.getRootField('users(contractorId:"1")'); 
        },
      },
    );

```
I have basically tried all combinations of `getRoot`, `getLinkedRecord` etc.

This a screenshot of my store from the `relay-dev-tool`:

<img width="461" alt="screenshot 2019-01-18 20 33 30" src="https://user-images.githubusercontent.com/11796944/51409414-0966fc80-1b62-11e9-997b-fc5cf1c2236f.png">

What am i missing? I looked through the whole store-api but could not find a clue.

Thanks for your help.

**Comment by jstejada** [comment]
> The problem is, in this article at some point i need to access the dataID in the store to push the newly created data into the current store - but i can't really get the current data from the store.

Could you wrap commitMutation in a function that takes the use id (aka dataID), so you can access the user record you want?
