### ISSUE TITLE
Changelog for relay-compilier v2 changes?

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#2615]
Hi!

We're very happy users of relay-compilier over at Gatsby. Just noticed a new major version came out - congrats!

We're trying to see if upgrading would be a breaking change for us as we'd also like to upgrade graphql. I poked around some but couldn't find a changelog or description of any breaking changes. Is there one or could you briefly describe what's changed?

**Comment by josephsavona** [comment]
v2 isn’t pushed yet, we ran into an issue during the release. We’llnpublish release notes as always when we cut the release.

**Comment by jstejada** [comment]
hey @KyleAMathews! Release notes are here: https://github.com/facebook/relay/releases/tag/v2.0.0

As @josephsavona mentioned, there should be no major or breaking compiler changes; let us know if that's not the case!

**Comment by KyleAMathews** [comment]
Sweet! Thanks for the updates and thanks of course for the great work building and maintaining Relay! We'll check things out and report if there's any breaking changes.

This especially sounds nice:

>Improved compiler error messages, which now show locations in source.

**Comment by steida** [comment]
@KyleAMathews Also TypeScript integration should be ready for Relay 2 soon. It's really a game changer. Check this example https://github.com/este/este/blob/master/pages/signin.tsx

Everything is type checked.

(I haven't checked Gatsby recently, if Gatsby supports it already, please ignore it)
