### ISSUE TITLE
Switch from React.render to ReactDOM.render in examples

### ISSUE THREAD

**Issue by wincent** [facebook/relay#262]
Via @l-urence in #243:

>  I noticed a second deprecated warning with `React.render(/*....*/)` in the example. It seems that `React.render(/*...*/)` should be replaced with `ReactDOM.render(/*....*/)` in React v0.14.0.

**Comment by l-urence** [comment]
@wincent Give me a minute an I will submit a PR.

**Comment by l-urence** [comment]
I only get the deprecated warning if react is imported / required with ```import React from 'react'```. I looked into to the unminified source of react which is loaded via:
```
<script src="node_modules/react/dist/react.min.js"></script>
```

there ReactDOM is assigned to React. So for the examples it should be okay.

**Comment by zpao** [comment]
> So I guess for the examples it should be okay to call `React.render(/*...*/)`.

Those will begin warning as well in the RC.

**Comment by l-urence** [comment]
@zapo How to use ReactDOM with ```react.min.js```? In the examples React is loaded via the ```<script>``` Tag. I dont't know if it is a good idea to change this and ```require``` it in the js source. 

I try to submit a PR by the weekend.

**Comment by zpao** [comment]
@zapo isn't here, just me 😜

We're going to be building a `react-dom.min.js` as another browser package which will reach into the `react.min.js` file (so `react-dom.min.js` is only 712 bytes but you'll need react loaded). That's happening in https://github.com/facebook/react/pull/4814 so you won't be able to do it before the next version we ship (almost certainly RC later this week).

You'll want to do this when you can:

```html
<script src="node_modules/react/dist/react.min.js"></script>
<script src="node_modules/react/dist/react-dom.min.js"></script>
```

**Comment by l-urence** [comment]
@zpao Thanks. Then I will fix this after the RC release.

**Comment by steveluscher** [comment]
Done in #290.
