### ISSUE TITLE
QueryRenderer fails to provide props

### ISSUE THREAD

**Issue by HorizonShadow** [facebook/relay#2623]
I'm having an issue getting QueryRenderer to provide props to a fragment container.

I have 3 components, App, GameList, and Game. The query I'm trying to run is

```
query App_GameListQuery {
    games {
        edges {
            node {
                id,
                name
            }
        }
    }
}
```

If I place the entire query into QueryRenderer, all works fine. However, if I move `game { ... }` into a fragment, I no longer receive the `games` prop in GameList.

So, using the code below, I get the following as props

![image](https://user-images.githubusercontent.com/1729810/52057761-43f66f00-253c-11e9-8f83-e984ffa83b51.png)

```
// App.jsx
const App = () => (
    <QueryRenderer
        environment={environment}
        query={graphql`
            query App_GameListQuery {
                ...GameList_games
            }
        `}
        render={({error, props}) => {
            if(error) {
                return "error";
            }
            if(!props) {
                return "loading";
            }
            console.log(props);
            return <GameList games={props.games} />
        }}
    />
);

export default App;
```

```
// GameList.jsx
const GameList = ({games}) => (
    <div>
        {
            games.edges.map(edge => <Game key={edge.node.id} game={edge.node} />)
        }
    </div>
);

export default createFragmentContainer(
    GameList,
    graphql`
        fragment GameList_games on Query {
            games {
                edges {
                    node {
                        id,
                        ...Game_game
                    }
                }
            }
        }
    `
)
```

I'm sure this is something completely obvious, but I'm just trying to learn relay and I can't seem to puzzle out why this would be happening, especially since it works if I don't separate the query into fragments.

I thought maybe the GameList fragment should be called GameList_data, since the root response from the server is data: { games: [] }, but I get an error
```
BabelPluginGraphQL: Fragment `GameList_data` should not end in `_data` to avoid conflict with a fragment named `GameList` which also provides resulting data via the React prop `data`. Either rename this fragment to `GameList` or choose a different prop name.
```

Which of course led me to rename the fragment to GameList, which gave me the same result as above ^.

**Comment by sibelius** [comment]
your fragment GameList, should be called GameList_query on Query, it is a fragment on query instead of a fragment on games

You also want to pass the query renderer props to your fragment container like this

https://github.com/entria/entria-fullstack/blob/master/packages/web/src/relay/createQueryRendererModern.tsx#L39

```
<FragmentComponent {...this.props} query={props} />;
```

as all props will be the `query` one

**Comment by HorizonShadow** [comment]
That solves it!

So the _<propname> portion of the fragment name corresponds to the parent of the fragment?

**Comment by sibelius** [comment]
not the parent, but the Type of the fragment

MyFragment_user on User
MyFragment_query on Query

tks
