### ISSUE TITLE
Refetch container - Uncaught ReferenceError: r is not defined

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/relay#2642]
Hello, I am getting this error when I try to refetch too quickly and the previous request has to be canceled. Unfortunately, I have hard times to debug it properly:

```
13:47:24.877 RelayObservable.js:615 Uncaught ReferenceError: r is not defined
    at Object.unsubscribe (<anonymous>:1:2238)
    at Object.eval [as unsubscribe] (RelayObservable.js:169)
    at Object.unsubscribe (RelayObservable.js:504)
    at doCleanup (RelayObservable.js:482)
    at Object.unsubscribe (RelayObservable.js:510)
    at doCleanup (RelayObservable.js:482)
    at Object.unsubscribe (RelayObservable.js:510)
    at eval (RelayObservable.js:362)
    at Array.forEach (<anonymous>)
    at eval (RelayObservable.js:361)
```

To make it easier for you I replicated the issue in the [example TODO project](https://github.com/relayjs/relay-examples/tree/master/todo). I made only few small changes: https://github.com/mrtnzlml/relay-r-is-not-defined/commit/2605118ef25dc404737494d6ba2dbe511ce4ba44

It honestly seems like everything works fine (even the previous request is correctly canceled with `Status: execution is unsubscribed.` message in the logs). The error is still there though. Is it a bug or am I doing something wrong? I could obviously fix it very easily by not sending the second request when the first one is not finished yet. However, seems like it should work since the first request is being canceled. Thank you very much for checking it... :)

**Comment by vala** [comment]
This seem to be related to relay devtools. As you can see in your  stack trace the line 
```
    at Object.unsubscribe (<anonymous>:1:2238)
```
seem to come from the minified code of Relay devtools.

**Comment by mrtnzlml** [comment]
Oh wow, nice! I didn't even notice that. I am closing this issue then because it's not related to Relay but to the Chrome extension. Thanks, @vala! 🙂
