### ISSUE TITLE
Error: The macro you imported from "undefined" is being executed outside the context of compilation with babel-plugin-macros

### ISSUE THREAD

**Issue by Elminday** [facebook/relay#2648]
Trying to use `babel-plugin-relay/macro` with [custom-react-scripts](https://www.npmjs.com/package/custom-react-scripts)

Rendering **Test** component into index page:

```
import {QueryRenderer} from 'react-relay';
import graphql from 'babel-plugin-relay/macro';

const Test = () => <QueryRenderer
   environment={environment}
   query={graphql'
    ...
  '}
  render={() => {
    return <div>test</div>;
  }}
/>
```

Throws:
> Uncaught Error: The macro you imported from "undefined" is being executed outside the context of compilation with babel-plugin-macros. This indicates that you don't have the babel plugin "babel-plugin-macros" configured correctly. Please see the documentation for how to configure babel-plugin-macros properly

Even though I configured my .babelrc:

```
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    "relay",
    "macros"
  ]
}
```

Repository I am using trying setup relay on: https://github.com/gothinkster/react-mobx-realworld-example-app

Package.json devDeps:

```
  "devDependencies": {
    "babel-plugin-relay": "^2.0.0-rc.2",
    "babel-plugin-macros": "^2.5.0",
    "custom-react-scripts": "0.2.0",
    "relay-compiler": "^2.0.0"
  }
```

**Comment by sibelius** [comment]
Make sure you have the same version of relay dependencies

**Comment by Elminday** [comment]
@sibelius changing  to `"babel-plugin-relay": "^2.0.0"` did not help.

**Comment by sibelius** [comment]
have you tried following this guide https://facebook.github.io/create-react-app/docs/adding-relay#docsNav

can you try to use babel 7 as well?

check our babel config https://github.com/entria/entria-fullstack/blob/master/packages/babel/index.js#L18

**Comment by sibelius** [comment]
repro here on codesandbox https://codesandbox.io/s/0vnk5jv00

**Comment by sibelius** [comment]
I made this repo that is based on CRA 2 with relay and babel plugin macros

https://github.com/sibelius/create-react-app-relay-modern

I think your custom-react-scripts does not have the latest version of babel-plugin-macros and this is causing troubles

**Comment by Elminday** [comment]
@sibelius huge thanks for the repo. Seems to be a problem with custom-react-scripts.

**Comment by w10036w** [comment]
@sibelius 
> repro here on codesandbox https://codesandbox.io/s/0vnk5jv00

The repo you give is showing the exact error reported.
I am here since I am facing the same issue when I am using [penv.macro](https://www.npmjs.com/package/penv.macro)

![](https://i1316.photobucket.com/albums/t608/sklr1/Screenshot%202019-05-02%20at%2004.40.29_zps7imfpanl.png)

**Comment by sibelius** [comment]
the error is on codesandbox itself https://github.com/codesandbox/codesandbox-client/issues/1604

**Comment by j0lv3r4** [comment]
I found this issue while trying to fix the exact same problem in a completely different context (A Next.js app).

I was able to fix my problem adding a `.babelrc` file with this:

```js
{
    "presets": ["next/babel"],
    "plugins": ["preval", "macros"]
}
```

Not sure if it'll help y'all, but leaving it here anyway.

**Comment by adam-hanna** [comment]
If it adds to the discussion. I'm also experiencing this error but only with `ts-jest`. My app runs fine on its own.

```javascript
// apps/core/jest.config.js
module.exports = {
  name: 'core',
  preset: '../../jest.config.js',
  transform: {
    '^.+\\.[tj]sx?$': 'ts-jest',
    '^(?!.*\\\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'html'],
  coverageDirectory: '../../coverage/apps/core',
  snapshotSerializers: ['jest-emotion'],
  testEnvironment: 'jsdom',
  globals: {
    'ts-jest': {
      babelConfig: "apps/core/babel.config.js"
    }
  }
}

// apps/core/babel.config.js
module.exports = {
  "presets": [
    "next/babel",
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "preval",
    [ "relay", { "artifactDirectory": "./__generated__" } ],
    "macros",
  ]
}

```

**Comment by georgewilde** [comment]
@adam-hanna I am also getting this error with ts-jest despite adding a .babelrc file as suggested by @j0lv3r4

**Comment by ianfabs** [comment]
I am also experiencing the same issue with ts-jest and next.js. adding `preval` and `macros` to babelrc did not resolve my issue

**Comment by wholenews** [comment]
I was getting the same error with next.js and @j0lv3r4's fix didn't help.  However it worked after replacing `.babelrc` with `babel.config.js` containing:
```
module.exports = {
  presets: [require.resolve('next/babel')],
  plugins: [[require.resolve('babel-plugin-macros')]],
}; 
```

**Comment by ChrisClaude** [comment]
I am experiencing the same issue with Next JS. I have tried [this approach](https://github.com/facebook/relay/issues/2648#issuecomment-499250143) and [that approach](https://github.com/facebook/relay/issues/2648#issuecomment-761086818) but they are not helping.

**Comment by Yiyue15** [comment]
Me neither... Is there any update on this?

**Comment by wangcch** [comment]
This question confused me for two days.🙁

**Comment by AthfanFasee** [comment]
> 

This worked for me finally as for 14th December 2021. Hope they fix this sooner. I spent 2 hoursto fic this :'D

**Comment by ameshkin** [comment]
> Me neither... Is there any update on this?

The babel fix seemed to work for me. I use blitz and the next config did not work, at all.

That usually works on my other projects. But for this one, I am using twin macro and had to update my babel files.


I was able to fix my problem adding a .babelrc file with this:

```
{
    "presets": ["next/babel"],
    "plugins": ["preval", "macros"]
}

```
