### ISSUE TITLE
Relay Prototyping tool should surface GraphQL transform errors reliably

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#265]
Currently, here's what the Relay Prototyping tool does to surface errors that originate from the Babel Relay plugin:
1. Collect `console.warn` logs; throw them out after they're 500 ms old.
2. Watch for exceptions thrown that contain the text “GraphQL Validation error”
3. Present the collected warnings

This means that errors that crop up under the following conditions will not be displayed:

a. You performed a mutation with GraphQL errors >500ms after the transform
b. You late-added a RelayContainer with GraphQL errors to the tree >500ms after the transform

To fix this, we could modify the `babel-relay-plugin` to accept a config param that tells it to throw errors right away instead of printing console warnings. Thoughts, @josephsavona?

**Comment by josephsavona** [comment]
A param to throw on errors instead of logging makes sense. This would be useful in static build steps too.

**Comment by grydstedt** [comment]
+1

**Comment by josephsavona** [comment]
added an option for this in #292

**Comment by josephsavona** [comment]
Realized that the option is present but we still need to use this in the prototyping tools ;-)
