### ISSUE TITLE
Prototypes should offer permalinks

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#266]
As you type into [the prototyper](http://facebook.github.io/relay/prototyping/playground.html), update the URL with `#source={URLEncodedAppSource}&schema={URLEncodedSchemaSource}` such that it can be copy and pasted to a friend.

Notes:
* When loading a prototype with injected code, don't evaluate and run it. Cover the UI on the right side with a message and a button. The viewer must click the button to hide the cover and start the prototyper.
* Once this is done, turn on localStorage-caching-by-default; right now it's opt-in.

**Comment by kassens** [comment]
Since URLs have a maximum length, we should consider saving the source on parse?

**Comment by steveluscher** [comment]
I'm not too fussed about URL length. Chrome, Safari, and Firefox accept over 100K characters.

**Comment by wincent** [comment]
> Since URLs have a maximum length

Alas, they [don't all agree](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) about what that length should be.

**Comment by steveluscher** [comment]
Closed by #342.
