### ISSUE TITLE
Uncaught Invariant Violation: commitRelayModernMutation: expected `environment` to be an instance of `RelayModernEnvironment`

### ISSUE THREAD

**Issue by arjun-kava** [facebook/relay#2684]
Error: Uncaught Invariant Violation: `commitRelayModernMutation`: expected environment to be an instance of `RelayModernEnvironment`. When using Relay Modern and Relay Classic in the same application, ensure mutations use Relay Compat to work in both environments.

I am using different client and server setup for Relay. I have used `graphql-relay-js` at the backend while used relay modern at the front end.

I have used simple `relay-runtime` for Network.

```javascript
import { SubscriptionClient } from "subscriptions-transport-ws";
import { Environment, Network, RecordSource, Store } from "relay-runtime";


import { getToken } from "./utils/jwt"

/**
 * Create store for relay connection
 */
export const store = new Store(new RecordSource());

/**
 * Load Environment Configuration
 */
const host = process.env.GRAPH_QL_HTTP_SERVER_HOST.toString()
const port = process.env.GRAPH_QL_HTTP_SERVER_PORT
const httpEndPointUrl = process.env.GRAPH_QL_HTTP_SERVER_URL
const wsEndPointUrl = process.env.GRAPH_QL_SUBSCRIPTION_SERVER_URL
const httpEndPoint = `http://${host}:${port}/${httpEndPointUrl}`
const socketEndPoint = `ws://${host}:${port}/${wsEndPointUrl}`



/**
 * Fetch query from relay server
 * @param {*} operation 
 * @param {*} variables 
 */
const fetchQuery = (operation, variables) => {
  return fetch(`${httpEndPoint}`, {
    method: "POST",
    headers: {
      "Accept": "application/json",
      "Content-Type": "application/json",
      "Authorization": getToken()
    },
    body: JSON.stringify({
      query: operation.text,
      variables
    })
  }).then(response => {
    return response.json();
  });
};

/**
 * Setup subscription server
 * @param {*} config 
 * @param {*} variables 
 * @param {*} cacheConfig 
 * @param {*} observer 
 */
const setupSubscription = (config, variables, cacheConfig, observer) => {
  const query = config.text;
  const { onNext, onError, onCompleted } = observer;
  const subscriptionClient = new SubscriptionClient(
    `${socketEndPoint}`,
    { reconnect: true }
  );
  subscriptionClient
    .request({ query, variables })
    .subscribe(onNext, onError, onCompleted);
};

/**
 * Initialize network with fetch query and subscription
 */
const network = Network.create(fetchQuery);

const environment = new Environment({
  network,
  store
});

export default environment;
```

I am new to Realy and I would appreciate any help, Please let me know If I am missing some fundamental concepts over here. Commenting any reference link will be helpful also. Thank You

**Comment by sibelius** [comment]
In which version is this happening?

What is the code that is causing this issue?

**Comment by arjun-kava** [comment]
Hello @sibelius ,
Versions are as below:
"relay-runtime": "^3.0.0"
"react-relay": "^2.0.0"
"found-relay": "^0.4.0-alpha.4"

While passing `environment` to 'commitMutation', it throws an error that `environment` to be an instance of `RelayModernEnvironment`

I might be wrong but I had setup modern relay enviroment as define in official documents. [elay-environment](https://facebook.github.io/relay/docs/en/relay-environment.html)

I am using `found-relay` to handle routing.

**Comment by sibelius** [comment]
can you show me the full code?

can you use environment directly instead of from `relay.environment`?

**Comment by arjun-kava** [comment]
Hello, I had done the same. I think it might be an issue related to `found-relay` because importing `environment` directly works fine. Thank you for your help. I have added issue at `found-relay` repo. [found-relay/issues/179](https://github.com/relay-tools/found-relay/issues/179). Thanks again!

**Comment by arjun-kava** [comment]
I think the issue generated with:
```
"react-relay": "^3.0.0",
"relay-runtime": "^3.0.0",
"babel-plugin-relay": "^3.0.0",
"relay-compiler": "^3.0.0",
```

I assume that `react-relay` and `relay-runtime` might be incompatible.

**Comment by sibelius** [comment]
does importing directly works?

remove  `^` from package.json packages version

run `yarn why react-relay` and for other version to make sure you have only one version of it and the correct one

**Comment by arjun-kava** [comment]
> does importing directly works?

Yes, It is working fine.

>remove ^ from package.json packages version

Tried, But isssue remains same.

**Comment by sibelius** [comment]
If importing directly works

It is not a problem with relay

**Comment by arjun-kava** [comment]
Okay, Thank you. I will try to find out other causes.
