### ISSUE TITLE
Best way to use QueryRenderer in Relay Modern

### ISSUE THREAD

**Issue by PavanBahuguni** [facebook/relay#2687]
I recently started grokking Relay Modern. I understand that QueryRenderer is used to fetch data using GraphQL query, your root component will have query renderer and all the child components define the data they need in terms of GraphQL fragments.
But is having just one QueryRenderer a good way to go ahead, wouldn't it be difficult pass the query and fragment parameters way upto the root?
If we are having multiple QueryRenderer we are not really making use of Relay caching mechanism as each QueryRenderer creates it's own store tree.

Any thoughts or best practices on how to use QueryRenderer is much appreciated.

**Comment by kassens** [comment]
The parent component containing the QueryRenderer and query can include fragments from child components and they can embed their sub-fragments and so on.
Typically, you'd have one QueryRenderer on the root of your per route/url and ensure the full page can be loaded in a single request. You can also create a different queryrenderer for a menu or similar if you want data fetching to be independent.

Check out https://github.com/relayjs/relay-examples/tree/master/todo/js/components, maybe that helps clarify?

**Comment by PavanBahuguni** [comment]
@kassens Thank you for the insight. Appreciate the effort. 😄 
Just a followup question, Assuming we are using only one QueryRenderer, and QueryRenderer is the only way you can send the variables defined by your fragments to the GraphQL server. In some case the component which is several level down the component tree from QueryRenderer and it has holds the knowledge of what variable needs to be sent to the server (lets say we click on a button and that component knows what button was clicked). How would we propagate that data to the QueryRenderer so that it can be passed to GraphQL server.

**Comment by ntelkedzhiev** [comment]
You would need to pass it to the QueryRenderer. That usually comes from a parent component. Why not just use a refetchContainer (together with @include/skip if needed)?

**Comment by Yashika-Sorathia** [comment]
Let say i am routing to another component, than can i query that component with the root QueryRenderer or for every new route I have to create a new QueryRenderer?

**Comment by aounleonardo** [comment]
I have the same question as @Yashika-Sorathia 

Is there any workaround to having one QueryRenderer per route? Can we pass fragments through routes? 

Sorry for the n00b question :/

**Comment by sibelius** [comment]
one query render per route is the way to go

use fetchPolicy to avoid network request in some cases

**Comment by aounleonardo** [comment]
Thank you @sibelius . I will look at fetchPolicy :)

But again sorry for another (maybe) easy question. What about sub-routes? I want to walk my user through different components in a profile editing phase:
- fill missing basic information
- add friends
- set privacy policies
I have common queries for all of these subpages, but what I'm worried about most is not the network request (I can live with unnecessary requests for now) but mainly reducing duplicate code. What would my best logic be?
- Have a query renderer for each sub-route?
- Save the needed page (or can I call it Tab?) as a state and conditionally render it?

I'm wondering what does the new Facebook do in its Settings page, I can see in the router that we get `facebook.com/settings` with `?tab=<X>` appended to it when we open the different tabs.

**Comment by sibelius** [comment]
the best place to ask this is in graphql slack #relay channel (join here 
Join GraphQL on Slack!graphql-slack.herokuapp.com
)
