### ISSUE TITLE
Chore: Remove Relay Classic docs + migration guides

### ISSUE THREAD

**Issue by orta** [facebook/relay#2693]
Now that Relay Classic isn't shipped at all in Relay, it's time to knock off a few documents from the site:

<img width="256" alt="Screen Shot 2019-03-16 at 5 25 16 PM" src="https://user-images.githubusercontent.com/49038/54479004-89cb7600-4810-11e9-815a-15d149a02aef.png">

**Comment by kassens** [comment]
I guess it didn't make it into the 3.0 cut, but I think I removed everything in the "next" version already: http://facebook.github.io/relay/docs/en/next/introduction-to-relay.html

Do you see anything else left?

**Comment by orta** [comment]
Looks good yeah, is it worth thinking about trying to reframe when it's called "Relay Modern" to just "Relay" ( e.g. [here](https://facebook.github.io/relay/docs/en/community-learning-resources.html#relay-modern-what-is-a-fragment) )

**Comment by kassens** [comment]
Yeah, we were thinking to drop the Modern suffix since that's the only Relay there is.

**Comment by daniloab** [comment]
Could we close this issue since the relay classic docs don't exist at the actual docs on relay.dev?
