### ISSUE TITLE
Non-deterministic generated output

### ISSUE THREAD

**Issue by xaviershay** [facebook/relay#2703]
Apologies, I don't have a minimal test case for this, but we are seeing semantically equivalent but textually different output when using node v10 vs node v11. Specifically, `selections` is being re-ordered.

I suspect that selections needs to be sorted (maybe here? https://github.com/facebook/relay/blob/master/packages/relay-compiler/codegen/ReaderCodeGenerator.js#L85 ) for the same reasons as documented here https://github.com/facebook/relay/blob/master/packages/relay-compiler/codegen/ReaderCodeGenerator.js#L173

This is causing issues in our team as we update our node version.

**Comment by sibelius** [comment]
is this still happening on master?

**Comment by josephsavona** [comment]
I believe this was already fixed on master, cc @kassens

**Comment by kassens** [comment]
This was fixed by @eliperkins with #2681.

**Comment by xaviershay** [comment]
Amazing, thanks everyone!
