### ISSUE TITLE
Plural tag not working in 4.0

### ISSUE THREAD

**Issue by NickDubelman** [facebook/relay#2717]
After upgrading to relay 4, my generated types (typescript) are seemingly not detecting my plural directive tags. They are generated as though the directive is not there

**Comment by alunyov** [comment]
I wonder if this is related to https://github.com/facebook/relay/issues/2710

Are you using `relay-compiler 4.0.0`?

**Comment by NickDubelman** [comment]
I am using relay-compiler 4.0.0. I don’t believe it is related to that, as I have fixed/patched the import causing that error you linked.

**Comment by taion** [comment]
relay-compiler-language-typescript hasn't been updated for v4.x yet, and this is a known issue with the current WIP PR in https://github.com/relay-tools/relay-compiler-language-typescript/pull/106. How are you generating these types?

**Comment by NickDubelman** [comment]
What makes you say it’s a known issue? I don’t see anything in that PR related to directives?

**Comment by taion** [comment]
The patch attached to the PR doesn't work (it's just the PR code). You can see in the snapshots that all the generated types for fragments are broken.

**Comment by taion** [comment]
e.g. https://github.com/relay-tools/relay-compiler-language-typescript/pull/106/files#diff-44a2d83f785197f00acb5a4860e6f100R561
