### ISSUE TITLE
BabelPluginRelay Error in 4.0

### ISSUE THREAD

**Issue by SatyaFariz** [facebook/relay#2720]
I got an error ```Error: BabelPluginRelay: Expected exactly one definition per graphql tag.```  while running Metro Bundler in React Native after upgrading from 3.0 to 4.0

**Comment by sibelius** [comment]
check breaking changes https://github.com/facebook/relay/releases/tag/v4.0.0

You need to run this codemod to fix your problems

https://gist.github.com/kassens/3e2ef9af1e5e1128f8fba3362bb92f98
