### ISSUE TITLE
Unexpected after cursor if nesting pagination container inside refetch container

### ISSUE THREAD

**Issue by SatyaFariz** [facebook/relay#2721]
When refetching the whole data using ```this.props.relay.refetch({}, {}, cb, { force: true })``` for pull-refresh functionality, the pagination cursor will be reset to null (fetching only the first page). But it seems the cursor in the pagination container doesn't get updated after paginating through the list.
Therefore giving me the unnecessary warning message even though the props are updated properly and the pagination is working like expected.

**Comment by SatyaFariz** [comment]
Turns out it's not related to relay. It's because of my caching strategy.

**Comment by gpbaculio** [comment]
how did u fix this?
