### ISSUE TITLE
The wrong usage of createFragmentContainer in the quick start guide

### ISSUE THREAD

**Issue by xamgore** [facebook/relay#2729]
Hi!

I had been trying to repeat the tutorial, the section ["Using Fragments"](https://facebook.github.io/relay/docs/en/quick-start-guide#using-fragments), when got an error. In its end you can see the source code of a react component, that is wrapped with the `createFragmentContainer` function call:

```js
export default createFragmentContainer(
  Todo,
  graphql`
    # As a convention, we name the fragment as '<ComponentFileName>_<propName>'
    fragment Todo_todo on Todo {
      complete
      text
    }
  `
)
```

Check out the second argument. According to the [API reference](https://facebook.github.io/relay/docs/en/fragment-container.html#createfragmentcontainer) it must be a mapping `{[string]: GraphQLTaggedNode}`, though in the example above it is a `graphql` string.

After I run this code, I get an error message ``Could not create Relay Container for `Todo`. Expected a set of GraphQL fragments, got …`` with some webpack code implaced. There is a similar stack-overflow [question](https://stackoverflow.com/questions/55961762/could-not-create-relay-container-graphql-js-file-appears-to-have-webpack-artifa), but they use react native.

To fix the issue above I had to replace the second arguement with this:

```
export default createFragmentContainer(
  Todo,
  { todo: graphql`
    # As a convention, we name the fragment as '<ComponentFileName>_<propName>'
    fragment Todo_todo on Todo {
      complete
      text
    }
  ` }
)
```

I suppose, the guide should be fixed. What do you think about it?

**Comment by sibelius** [comment]
Send a PR fixing this please

**Comment by xamgore** [comment]
@sibelius ready :)
