### ISSUE TITLE
[website][docs] search is broken

### ISSUE THREAD

**Issue by jgcmarins** [facebook/relay#2735]
It is not related to relay, but the search is broken at https://facebook.github.io/relay.

#### searching for QueryRenderer
<img width="1423" alt="Screen Shot 2019-05-15 at 17 13 09" src="https://user-images.githubusercontent.com/5133450/57806350-4f5d5700-7735-11e9-893e-17561b6998cf.png">

#### searching for createFragment
<img width="1431" alt="Screen Shot 2019-05-15 at 17 14 11" src="https://user-images.githubusercontent.com/5133450/57806366-584e2880-7735-11e9-8396-8cae3bc4bcd8.png">

I have no experiences with Algolia, but I can work on the fixes if someone helps me.

**Comment by babangsund** [comment]
This issue seems to have been resolved, right? @jgcmarins 
Can we close this issue? 🙂

**Comment by jgcmarins** [comment]
fixed
thanks
