### ISSUE TITLE
Can't compile after I added another fragment

### ISSUE THREAD

**Issue by michaloslav** [facebook/relay#2773]
First I just want to say I literally started learning about Relay like 5 hours ago so it's quite likely I screwed something up at some point and it's all my fault.

So I made an app, compiled it with yarn relay and then ran it with yarn start. I kept working on it, realized I needed some more functionality so I added another file where I used the createFragmentContainer and graphql functions again. When I tried to recompile after this change, I got the following error:

GraphQLCompilerContext: Unknown document `{NewFileName}_{newprop}`.

It then failed and exited with code 100 and I'm unable to run the app from then on. I tried re-running it and looking all over the interwebs for a solution, nada

So, am I doing something stupid or am I doing something stupid?

**Comment by sibelius** [comment]
Can you provide more info?

do you have a file called `NewFileName`?

**Comment by michaloslav** [comment]
Yeah, I guess I could be a little more specific, I'm making a dumb hello-world app about heroes and movies.

I made a new file called HeroInfo.js, that file contains a component wrapped in createFragmentContainer. That means I call graphql while creating the container (in the second parameter, like you normally would). The call implements a new fragment called HeroInfo_hero.

Did I still leave something potentially relevant out?

**Comment by michaloslav** [comment]
I guess I could rephrase the whole thing. How are you supposed to add new fragments after you first compiled? Maybe if you give me the step by step, I can figure out what I did wrong

**Comment by sibelius** [comment]
can you share your repo and the whole error?

**Comment by michaloslav** [comment]
Okay sure

https://github.com/michaloslav/dumb-relay-thing

`
yarn run v1.16.0
$ relay-compiler --src ./src --schema ./schema.graphql

Writing js
ERROR:
GraphQLCompilerContext: Unknown document `HeroesInfo_hero`.
error Command failed with exit code 100.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by michaloslav** [comment]
Any ideas? Anyone?

**Comment by sibelius** [comment]
there is no fragments called `HeroesInfo_hero` in your codebase

check https://github.com/michaloslav/dumb-relay-thing/search?q=HeroesInfo&unscoped_q=HeroesInfo

the name is `HeroInfo_hero`
