### ISSUE TITLE
I'm fairly sure `dataFrom` prop isn't being honoured in `QueryRenderer`

### ISSUE THREAD

**Issue by stan-sack** [facebook/relay#2782]
Im just running a standard `QueryRenderer` in a next.js app based off [this example](https://github.com/zeit/next.js/tree/canary/examples/with-react-relay-network-modern). I've been noticing that old data from the store is flashing for an instant before the network request completes and the correct network data is displayed.

My `QueryRenderer` is as follows:

```
<QueryRenderer
    environment={environment}
    query={Component.query}
    variables={variables}
    cacheConfig={{ force: true }}
    dataFrom={"NETWORK_ONLY"}
    render={({ error, props }) => {
        console.log(props)
        return (
            <Component
                {...props}
                {...this.props.pageProps}
                error={error}
            />
        )
    }}
/>
```

I also checked what happens if I set `dataFrom={"SOME_OTHER_VALUE"}` - There are no errors thrown which is why I think the prop isn't being read.

I'm running the following relay versions:
```
"babel-plugin-relay": "^5.0.0",
"relay-compiler": "^5.0.0",
"react-relay": "^5.0.0",
"react-relay-network-modern": "4.0.1",
"react-relay-network-modern-ssr": "1.2.4",
```

**Comment by sibelius** [comment]
can you add a failing test?

**Comment by stan-sack** [comment]
I can have a go later this week. Should I be getting an error when I set `dataFrom={"SOME_OTHER_VALUE"}`? Would it be enough to show that I'm not getting an error there?

**Comment by stan-sack** [comment]
OK so the value of `dataFrom` is read the following way: 

```
var storeSnapshot =
                props.dataFrom === STORE_THEN_NETWORK
                    ? queryFetcher.lookupInStore(genericEnvironment, operation)
                    : null
```

which is why its not throwing an error.

I now think that the issues is coming from `react-relay-network-modern-ssr`.
