### ISSUE TITLE
relay-compiler with relay-config

### ISSUE THREAD

**Issue by artola** [facebook/relay#2786]
I would like to migrate `relay-compiler` from CLI configuration to `relay-config` style (`relay.config.js`) for a mixed schema client/server files.

Until now I used a script `relay-compiler --src src --schema schema.server.graphql` and inside `src` folder I place my `schema.clent.grapql`.

Here a mini repro: https://github.com/artola/relay-bug2.git
where the type `User` contains 1 server field `foo` and 1 client field `bar`.

Migrating to `relay.config.js`:

```js
module.exports = {
  schema: 'schema.server.graphql',
  src: 'src',
  extensions: ['js'],
  include: ['**/*'],
  exclude: [],
  verbose: true,
  watchman: true,  // <== only works if watchman = true
  watch: false,
  validate: false,
  quiet: false,
  persistOutput: undefined,
  noFutureProofEnums: true,
//   language: 'typescript',
  artifactDirectory: 'src/__generated__',
  customScalars: {},
};
```
Once we place this config, the compiler will use it, and with the above config will not find the client schema file (and will break with error) unless `watchman: true`. 

It seems that there is something wrong with the `include` option when `watchman: false`, and of course the use of watch/watchman is apart from finding/including the schema files.

@alloy @en_js @sibelius  Here the issue as requested on Slack chat.

**Comment by maraisr** [comment]
Where be this slack channel? 👀 cc @alloy @sibelius @artola

**Comment by sibelius** [comment]
Search for graphql slack on #relay channel

**Comment by sorenhoyer** [comment]
Worked fine when I removed `include: ['**/*'],`.

**Comment by artola** [comment]
@sorenhoyer Updating the dependencies to last version (latest minor/patch), for me it is working with `include: ['**/*']` and running `"relay": "relay-compiler"` as long we keep `watchman: true`, else it is not breaking but there is no file generated.

**Comment by artola** [comment]
@kassens In v5 (no tested in v6) it is not working when no watchman support. While in the CLI without a config we were able to run `--watchman false` with a config when we set `watchman: false, watch: false` it just breaks when `watchman` is not installed. It seems that the options is not honored.

Do you have some hint please?
