### ISSUE TITLE
Logo on website is overlapping page title

### ISSUE THREAD

**Issue by PKief** [facebook/relay#2788]
Hi Relay-Team,

I just wanted to let you know that on my screen resolution the relay logo is overlapping the project title, which is not looking so nice:

![image](https://user-images.githubusercontent.com/12248527/60381016-80c48480-9a4e-11e9-8f66-973f6f55a51a.png)

I could figure out that the issue occurs if the width of the resolution is between 1200 and 1500px.

**Comment by thedanielforum** [comment]
@PKief created a PR for this issue: https://github.com/facebook/relay/pull/2932

**Comment by kassens** [comment]
Thanks @thedanielforum this is now fixed!

Thanks @PKief  for reporting.
