### ISSUE TITLE
React hooks status?

### ISSUE THREAD

**Issue by BruceL33t** [facebook/relay#2792]
Just started working with Relay and being used to working with modern React code (Context + Hooks), using render props and especially HoC seems like a step back in the stone-age.

So I'd really be interested in hearing about the status, and if possible and eta on a public hooks api? It would just make things a little more elegant ;-)

**Comment by taion** [comment]
There are a couple of open-source libraries that add hook support for a good bit of Relay functionality. Take a look at https://github.com/relay-tools/relay-hooks and https://github.com/relay-tools/react-relay-mutation.

There are a few challenges in exactly matching the upcoming Relay hooks API. See https://github.com/relay-tools/relay-hooks/issues/5#issue-453957030 for more details.

**Comment by BruceL33t** [comment]
@taion I know about relay-tools/relay-hooks, however it probably does not make sense to use them, if they differ so much from the hooks implementation that facebook is using internally right now. They might release their hooks implementation tomorrow, and we'd have to make huge refactors to migrate our code - hence this question. I was hoping to get an ETA on whe to expect being able to use  hooks with Relay, without having to write our own or use a custom library, such as relay-tools :-)

**Comment by sibelius** [comment]
You can always codemod

**Comment by JohannesKlauss** [comment]
Hooks got added few hours ago: https://github.com/facebook/relay/commit/b83aace7a95f5fd82cbb30d1f6888bcc4767eeb5

**Comment by pie6k** [comment]
@JohannesKlauss while they're added to this repository - they're not yet published to npm.

**Comment by JohannesKlauss** [comment]
But now they are with `6.0.0`

**Comment by sibelius** [comment]
relay-experimental is taken on npm by another user

**Comment by pie6k** [comment]
@JohannesKlauss I've checked `react-relay` `6.0.0` and seems there are no hooks included there. Am I missing something?

**Comment by JohannesKlauss** [comment]
Oh sorry, yes. It's inside the `relay-experimental` package. My bad.

**Comment by pie6k** [comment]
So to confirm, there is no way to use them without building them manually from this repo at the current moment?

**Comment by JohannesKlauss** [comment]
@pie6k You can use this package: https://github.com/relay-tools/relay-hooks
It tries so be as close as possible to the current experimental implementation.

Also the release notes for 6.0.0 state, that those Hooks APIs are also very likely to change, hence they are experimental and not in the main package :).

**Comment by akomm** [comment]
I would not recommend the relay-hooks library for everyone. It looks like relay-hooks does not even properly support `@relay(plural: true)`. From the issue history and fixes on  this matter it seems to me, they are not away that react-relay library can also be used for stuff outside of relay connections, as the only checks in the code make edge/node structure assumptions as it seems. Typing-wise (TS) I also had to go from just using the the emitted fragment/query type to using those two plus the `*$ref` types on outer api of my props. All in all I dropped the usage of it. Hope for some first-class hook support, as hooks are awesome. Until than use my own hooks for that...

**Comment by sibelius** [comment]
you can try relay hooks using experimental builds

https://relay.dev/docs/en/experimental/a-guided-tour-of-relay#installation

```jsx
yarn add react@experimental react-dom@experimental react-relay@experimental
```

**Comment by akomm** [comment]
@sibelius I try to avoid experimental if not dire needed. I have currently a solution which should be simple to migrate later when needed. Its tempting, but I pass out of experience.

**Comment by akomm** [comment]
I got to correct my previous post. There were three issues that looked like one, one major on my side. Two resolved by the maintainer of the relay-hooks library and the third by me. Other than this the hooks work perfectly well so far!
