### ISSUE TITLE
[website][docs] Broken links in "GraphQL Server Specification"

### ISSUE THREAD

**Issue by lesha1201** [facebook/relay#2795]
Link to docs: https://relay.dev/docs/en/graphql-server-specification

## Description

All links that lead to relay server spec are broken. For example:
- https://relay.dev/relay/graphql/objectidentification.htm (GraphQL Object Identification)
- https://relay.dev/relay/graphql/connections.htm (GraphQL Cursor Connections)
- https://relay.dev/relay/graphql/mutations.htm (GraphQL Input Object Mutations)
- https://relay.dev/relay/graphql/connections.htm (Relay cursor connection)
- https://relay.dev/relay/graphql/objectidentification.htm (Relay global object identification)
- https://relay.dev/relay/graphql/mutations.htm (Relay input object mutation)

I  think all links should be changed
`https://relay.dev/relay/graphql/*` -> `https://facebook.github.io/relay/graphql/*`

## Update

`https://relay.dev/relay/graphql/*` -> `https://relay.dev/graphql/*`

**Comment by Demintika** [comment]
`https://relay.dev/relay/graphql/*` -> `https://relay.dev/graphql/*` works for me.

**Comment by jgcmarins** [comment]
maybe related to https://github.com/facebook/relay/issues/2735
