### ISSUE TITLE
D: Fragment type checking

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#282]
Daydreaming a little bit, it might be nice if the sort of thing in #268 could be baked into Relay (or a Relay add-on) in some capacity in a way that prevents developer errors. I'm imagining something like:

```js
'post': () => Relay.QL`
  fragment on Post {
    ${Video.getFragment('video')},
    ${Picture.getFragment('picture')}
  }
`
```
(notice that there's no explicit `__typename` query)

Instead, a developer would just do something like:

```js
const element = this.props.relay.matchFragmentType(this.props.post, {
  'Video': () => <Video post={this.props.post} />,
  'Picture': () => <Picture post={this.props.post} />,
}, () => <span>Uh oh! This type was not considered...</span>)();
```

Now the babel plugin could find any calls to `matchFragmentType` and automatically insert `__typename` into the fragment as appropriate.

`matchFragmentType` would raise an invariant if a key passed in does not match one of the possible types. There would be a required 3rd parameter that specifies the return value if none of the types match (for forward compatibility), that will also raise a warning.

Thoughts?

(Extracted from #280)

**Comment by devknoll** [comment]
`matchFragmentType` could almost be implemented today in a separate library (with `__typename` added by the developer).

Whether or not this belongs in the Relay core probably depends on how common this pattern actually is.

**Comment by josephsavona** [comment]
The plugin can (and perhaps should) insert `__typename` automatically whenever the type is not concrete, based purely off information on the schema (ie no need for `matchFragmentType`). You could then trivially implement `matchFragmentType()`.

**Comment by josephsavona** [comment]
@wincent @yuzhi  @yungsters thoughts on automatically adding `__typename` for interface/union types?

**Comment by wincent** [comment]
> thoughts on automatically adding `__typename`

This adds a small amount of overhead, but I think it's likely worth it in terms of the value it could add.

**Comment by devknoll** [comment]
Updated the proposal: 

`matchFragmentType` would **require** a 3rd argument that acts as a default (and warn in development when it's used), so that forward compatibility is always considered.

**Comment by josephsavona** [comment]
We discussed this offline and agreed that for now, it's best for product developers to manually add `__typename` when necessary. Relay doesn't need this field to operate correctly, and applications won't need the field for every instance of an interface or union. Not including the field reduces network/cpu/memory overhead by default, and leaves open the option of adding it later.

A `matchFragmentType` function is easy enough to implement outside of Relay core.

@devknoll Thanks for bringing up this idea! I'm going to close but feel free to comment to continue the discussion
