### ISSUE TITLE
feature: move ReactRelayQueryFetcher to relay-runtime 

### ISSUE THREAD

**Issue by morrys** [facebook/relay#2827]
Hi all,
I wanted to propose to move in the next version of Relay `ReactRelayQueryFetcher` into the `relay-runtime` package as it has no real dependence on React. This makes it easier to extend react-relay (for example [vue-relay](https://github.com/ntkme/vue-relay/blob/master/src/VueRelayQueryFetcher.js))

Thanks,
Lorenzo

**Comment by josephsavona** [comment]
ReactRelayQueryFetcher is a transitional API to get basic concurrent/suspense compatibility for QueryRenderer. We expect to change the implementation of QueryRenderer going  forward to share more infrastructure with hooks, and then remove QueryFetcher -  so we'd rather not expose this as public API.
