### ISSUE TITLE
feature: adding the possibility of passing a function as fetchPolicy

### ISSUE THREAD

**Issue by morrys** [facebook/relay#2828]
I would like to suggest adding the possibility of passing a function as fetchPolicy. This change will be useful when new [fetchPolicy](https://github.com/relay-tools/relay-hooks/issues/5) will be added.

```
export type FetchType = store-or-network | store-and-network | network-only | store-only

export type RefetchOptions = {|
   + force ?: boolean,
   + fetchPolicy ?: FetchType | (() => FetchType),
   + metadata ?: {[key: string]: mixed},
|};

export type FetchPolicy = FetchType | (() => FetchType);
```

This allows you to have dynamic policies without having to change the parameter, for example:

```ts

// ...
const fetchPolicy = function () {
   if (<condition>) {
      return 'store-only';
   }

   return 'store-then-network';
}
// ...
```

**Comment by josephsavona** [comment]
Can you clarify the use-case? It isn't immediately obvious what additional flexibility this offers, since you can just execute the function yourself to decide the value.

**Comment by jstejada** [comment]
@morrys also curious if you could elaborate why you need this type of behavior. I'm not sure I follow why the fetchPolicy would change for the same request. Can you dynamically pass the fetchPolicy you need (to useQUery or the refetch function) from above?

**Comment by sibelius** [comment]
I think you can handle this using `useQuery` hook

it is more composable

**Comment by morrys** [comment]
As @sibelius says with the introduction of hooks this can be handled in other ways.
