### ISSUE TITLE
yarn start has no effect

### ISSUE THREAD

**Issue by j4nos** [facebook/relay#2836]
yarn start has no effect

<img width="915" alt="Képernyőfotó 2019-08-27 - 14 38 13" src="https://user-images.githubusercontent.com/11924475/63771908-55d4a080-c8d8-11e9-863f-792219c71214.png">

<img width="572" alt="Képernyőfotó 2019-08-27 - 14 37 43" src="https://user-images.githubusercontent.com/11924475/63771877-47868480-c8d8-11e9-9079-de59a0f821b6.png">

**Comment by kassens** [comment]
This is for relay-examples. Let's open an issue there: https://github.com/relayjs/relay-examples/issues/101
