### ISSUE TITLE
Add tentative roadmap documentation

### ISSUE THREAD

**Issue by wincent** [facebook/relay#284]
Splitting this off as an actionable subtask from #263.

The notion is to give a suitably vague/tentative overview of some of the major upcoming areas of work. Issues themselves are a little too fine-grained and numerous to get a sense for the big picture of what lies in store.

**Comment by devknoll** [comment]
Thanks @wincent :+1: 

Concrete ideas for the short term:

1. An inverse of the "help wanted" label. This is mostly covered by the issue assignments that are already happening, but I'm not sure if this is codified yet. Then "help wanted" just becomes the set of everything that isn't already assigned to FB :wink: 

2. Add/assign GH issues for current internal tasks -- I don't see any GH tasks for the deferred query work that you're currently doing :wink:

3. I like facebook/react's "good first bug" label. It helped encourage me to try and contribute!

Given the current age of the project and that most development is happening internally, I think 2 would provide a sufficient roadmap in the short term.

**Comment by wincent** [comment]
> I don't see any GH tasks for the deferred query work

Good point. Created one.

> I like facebook/react's "good first bug" label. It helped encourage me to try and contribute!

Nice idea!

**Comment by josephsavona** [comment]
We now have a [roadmap](https://github.com/facebook/relay/wiki/Roadmap).
