### ISSUE TITLE
Add top-down "birds' eye view" documentation for concepts and design principles

### ISSUE THREAD

**Issue by wincent** [facebook/relay#285]
We've had feedback that:

- Relay has a large number of new concepts with new terminology attached that can make it hard to apprehend.
- It is hard to get a "big picture" sense of *why* things are designed the way they are. As such, people are reduced to monkey-see-monkey-do copying of examples and may not really understand how things are working, or whether their approach ends up being The Correct Way™.
- Without the "big picture", making sense of the API docs and guides can be difficult, and they seem relatively terse or thin.

The idea here, then, is to produce a top-down conceptual doc that complements the existing bottom-up tutorial-based documentation and reference material.

I'm thinking here of something like the wonderful "Git for computer scientists", that I read years ago when DVCS was still a new thing, and which laid a foundation for understanding all the new stuff (then-foreign concepts like rebasing and the index) that rest upon some simple under pinnings like the DAG and a content-addressable database.

cc @josephsavona per our offline discussion

**Comment by wincent** [comment]
Ugh.... hit Return before I'd actually typed anything... will fill out with actual content.

**Comment by kastermester** [comment]
This sounds awesome! Looking forward to it :)

**Comment by AnSavvides** [comment]
This would be incredibly helpful actually. Having just gone through the docs, the first half did feel a lot like "Let's copy paste a bunch of stuff and try figure out how it all works together". Going through the GraphQL and API Reference sections did help with understanding what's happening and why, but there is quite a lot there which makes it a tad difficult to digest without reading it all over and over again a few times.

If all this information could somehow be put into a high-level one-pager sort of thing, that'd be great.

**Comment by wincent** [comment]
We've now added [Thinking in GraphQL](http://facebook.github.io/relay/docs/thinking-in-graphql.html) and [Thinking in Relay](http://facebook.github.io/relay/docs/thinking-in-relay.html), which is our first cut at this. Anywhere where we still feel like this is lacking, we can probably add to those docs, so I am going to close this for now.

**Comment by AnSavvides** [comment]
Awesome :+1:
