### ISSUE TITLE
Proposal: QueryRenderer render stale variables

### ISSUE THREAD

**Issue by janicduplessis** [facebook/relay#2863]
## Problem

Currently when changing variables in a `QueryRenderer` the component goes into the loading state immediately until the new data arrives. This behaviour is useful for things like search where you want instant feedback on variable change but sometimes it would be preferable to keep rendering the current content until new data arrives.

## Proposal

We could add a `renderStaleVariables` (or whatever better name we can find) boolean prop to control this behaviour. It would default to false to prevent breaking changes. When it is set to true, Relay would continue rendering with the current render props until new data arrives.

We can also add a stale prop that gets passed to the render function so consumer can know that the data is being changed and is stale. This allows doing things like rendering a disabled or custom loading UI.

## Implementation

I have a test implementation I've been using in production for a while. I just rebased it to the latest version of QueryRenderer in relay@6.0.0

https://gist.github.com/janicduplessis/facf30f35e647af870d43753d8159b87

If that makes sense I can work on a PR to upstream this code.

**Comment by babangsund** [comment]
Couldn't you implement the same behaviour by passing new variables to a `refetch`, instead of the `QueryRenderer`?

**Comment by janicduplessis** [comment]
I started using the hooks api and this is solved by suspense.
