### ISSUE TITLE
Is relay-experimental unpublished?

### ISSUE THREAD

**Issue by dminkovsky** [facebook/relay#2871]
I am trying to install relay experimental

yarn add relay-experimental@6.0.0

and it appears to be unpublished.  Is that intentional or am I missing in the wrong place?

**Comment by dminkovsky** [comment]
> Added unreleased relay-experimental package which contains experimental version of Relay Hooks using React Suspense.

I guess "unreleased" means unpublished

**Comment by josephsavona** [comment]
Yes, this is intentional. We plan to publish hopefully later this year.

**Comment by dminkovsky** [comment]
Great, thanks a lot

**Comment by sibelius** [comment]
you can try relay hooks using experimental builds

https://relay.dev/docs/en/experimental/a-guided-tour-of-relay#installation

```jsx
yarn add react@experimental react-dom@experimental react-relay@experimental
```

**Comment by dminkovsky** [comment]
Hey thanks a lot, I didn't know this. I had been using @entria/relay-experimental.

**Comment by dminkovsky** [comment]
Great docs over there.
