### ISSUE TITLE
--watch option not working even with watchman installed

### ISSUE THREAD

**Issue by Thomazella** [facebook/relay#2873]
![Screen Shot 2019-09-28 at 7 27 51 PM](https://user-images.githubusercontent.com/15015324/65823092-1924fd80-e226-11e9-8add-4160a2f8f2ad.png)

I have watchman installed at `/usr/local/bin/watchman` so I'm not sure why it's not working. Thanks for any help.

**Comment by sibelius** [comment]
try with:

```jsx
relay-compiler --watchman false --watch
```

**Comment by Thomazella** [comment]
@sibelius `relay-compiler --watchman --watch` works for me
