### ISSUE TITLE
Question: How to setup subscriptions in v6

### ISSUE THREAD

**Issue by SatyaFariz** [facebook/relay#2882]
After I upgraded to v6, I got an error like this:

![d465e323-87ef-48f8-b8e9-ed48f523ef4e](https://user-images.githubusercontent.com/25284201/66517208-e83da600-eb0c-11e9-9a3c-1cd802703ea1.jpg)

This is my code in v5:

<img width="644" alt="relay error" src="https://user-images.githubusercontent.com/25284201/66517237-f5f32b80-eb0c-11e9-96f1-d3b1fc88c8e5.PNG">

Is there any documentation on subscription setup in v6 ?

**Comment by sibelius** [comment]
you need to return an observable

check this https://github.com/facebook/relay/issues/2869#issuecomment-534905537
