### ISSUE TITLE
Multiple schema/graphql files

### ISSUE THREAD

**Issue by pula2000** [facebook/relay#2887]
Is it possible to pass multiple graphql files if one had to split their mutation, query and schema in different graphql files?

**Comment by alunyov** [comment]
Hmm, @pula2000 not sure I understand the question.

Can you provide more context on what you're trying to do, with the code example if possible?

**Comment by JohannesKlauss** [comment]
I think what he means is that he would like to split queries, types and mutations into different .gql files depending on their scope and concern and if Relay is able to create one single source of truth out of multiple files.

**Comment by sibelius** [comment]
I recommend having a single .schema file

**Comment by pula2000** [comment]
As @JohannesKlauss said I'd like my types, queries and mutations to be in separate files but the relay-compiler command doesn't seem to be accepting multiple files. Would appreciate it if it did.

**Comment by alunyov** [comment]
@pula2000 

I'm not sure if we will be able to work on this soon. PR is welcome, if you think this feature will be useful for other developers.

For now, you probably need to concatenate (something like `cat file1 file2 file3 > schema.graphql`) those files to produce a single SDL file for the schema.
