### ISSUE TITLE
Hyperlinked "community-maintained list" leads to 404

### ISSUE THREAD

**Issue by davegoldblatt** [facebook/relay#2896]
Steps to repro:

1. navigate to https://github.com/facebook/relay
2. click on "community maintained list" under "Users" header
3. Get 404

Video: https://i.imgur.com/xcNQkg5.mp4

**Comment by kassens** [comment]
Thanks for noticing, we've replaced this file with this config https://github.com/facebook/relay/blob/master/website/siteConfig.js that generates this page: https://relay.dev/en/users

I've sent a PR to update the link in the README, thank you!
