### ISSUE TITLE
useLazyLoadQueryNode does not handle remote errors

### ISSUE THREAD

**Issue by dminkovsky** [facebook/relay#2901]
Upon success, [`preparedQueryResult`](https://github.com/facebook/relay/blob/a0fc1019f07bec45e0a0d887963961a08f24adaf/packages/relay-experimental/useLazyLoadQueryNode.js#L64) looks like:

<img width="622" alt="Screen Shot 2019-10-23 at 12 06 47 PM" src="https://user-images.githubusercontent.com/218725/67412646-a9d4cc00-f58d-11e9-8fe0-0341ed47ab42.png">

but upon error looks like:

<img width="577" alt="Screen Shot 2019-10-23 at 12 09 06 PM" src="https://user-images.githubusercontent.com/218725/67412842-0b953600-f58e-11e9-80f4-2709190c3afa.png">

which leads to failure at: https://github.com/facebook/relay/blob/a0fc1019f07bec45e0a0d887963961a08f24adaf/packages/relay-experimental/useLazyLoadQueryNode.js#L86-L91

**Comment by josephsavona** [comment]
Hmm, can you give a bit more context about your setup? This hook does (should) handle remote errors  (and we have tests for this), but there may be a case we aren't handling. What  does  your network fetch  function look like  (if you can share), and what is the  error / where is it thrown?

**Comment by dminkovsky** [comment]
Hey whoops sorry I didn't post the error :(.

Here is my network function:

<details>

```js
import {Network, Observable} from 'relay-runtime';
import axios from 'axios';

import {GRAPHQL_URL} from './constants';

export default Network.create(
    (operation, variables, cacheConfig, uploadables) => {
        const data = new FormData();
        data.append('query', operation.text);
        data.append('variables', JSON.stringify(variables));
        if (uploadables) {
            Object.keys(uploadables).forEach(key => {
                data.append(`file:${key}`, uploadables[key]);
            });
        }
        return Observable.create(sink => {
            const source = axios.CancelToken.source();
            axios({
                method: 'post',
                url: GRAPHQL_URL,
                data,
                withCredentials: true,
                cancelToken: source.token,
                onUploadProgress: e => {
                    uploadables &&
                        cacheConfig &&
                        cacheConfig.onUploadProgress &&
                        cacheConfig.onUploadProgress(e);
                },
            })
                .then(({data}) => data)
                .then(throwIfErrors)
                .then(complete(sink))
                .catch(error(sink));
            return {
                unsubscribe: () => {
                    source.cancel();
                },
            };
        });
    },
);

function throwIfErrors(payload) {
    if (payload.errors && payload.errors.length) {
        throw payload.errors;
    }
    return payload;
}

const complete = sink => payload => {
    sink.next(payload);
    sink.complete();
};

const error = sink => e => {
    if (!axios.isCancel(e)) {
        sink.error(e);
    }
};
```

</details>


> and what is the error / where is it thrown?

I don't remember exactly, but it was just a few frames down where either `fragmentNode` or `fragmentRef` from `preparedQueryResults` is `undefined`. When I try `useLazyLoadQuery` next I'll update this post if I can replicate. Should I close for now?

**Comment by josephsavona** [comment]
Let’s close if you can’t reproduce. Feel free to open again if the error re-occurs and you have more information!

**Comment by WhippetsAintDogs** [comment]
I'm having the same problem when I call a `@reach/router` `redirectTo()` in my network fetch function. `redirectTo()` throws a RedirectRequest Error that is handled by its LocationProvider's componentDidCatch lifecycle to navigate.
