### ISSUE TITLE
[Feature] Implement @once directive

### ISSUE THREAD

**Issue by fedbalves** [facebook/relay#2907]
Once fragment has 'once' directive, all refetch queries get data from Relay Store and not from API.

**Comment by mrtnzlml** [comment]
@fedbalves Refetch container has `fetchPolicy` with `store-or-network` value. Is this what are you looking for?

**Comment by fedbalves** [comment]
> @fedbalves Refetch container has `fetchPolicy` with `store-or-network` value. Is this what are you looking for? https://relay.dev/docs/en/refetch-container#arguments-1

Maybe. I'll look into it.
Thanks

**Comment by sibelius** [comment]
use fetchPolicy to fix this

also read this to improve your cache strategy

https://medium.com/@helielson/caching-fields-on-relay-modern-with-hooks-30d76502e404
