### ISSUE TITLE
[Suggestion] Ignore Fragment FileName and use FolderName when filename is lowercase

### ISSUE THREAD

**Issue by fedbalves** [facebook/relay#2908]
I understand naming convention for fragments and agree with it.
However, in order to reach more and more developers, I suggest ignore filenames with lowercase (ex: component, fragment, etc...)

**Comment by kassens** [comment]
Thanks for the comment!

I'd love to hear more thoughts on this from other people how this works for you in OSS.

The fragments would still need to be unique though, but maybe we should just remove the enforcement to match the file/path name in any way and just let you use the linter if you want to?

**Comment by fedbalves** [comment]
Hi @kassens !
I believe removing the enforcement would bring more confusion than productivity.
Matching file/path name would still remain mandatory and would unique as well. My point is when fragment File name is lowercase, it would use Folder name. Just like 'index' case.
