### ISSUE TITLE
Hooks removed in react-relay v7.1.0

### ISSUE THREAD

**Issue by sorenhoyer** [facebook/relay#2933]
In relay version 7.0.0 you could use hooks by `import { xyz } from 'react-relay/hooks`. 

In the recent minor update v7.1.0, hooks were removed. This is quite radical for a minor version bump - is this intentional?

As TypeScript-relay users, we have no possibility to use the experimental channel, since the relay-compiler-language-typescript will always be outdated, so we are depending on those hooks from v. 7.0.0 instead.

Is there any chance you could publish a v7.1.1 and add back hooks? :-)

**Comment by jstejada** [comment]
@sorenhoyer hooks have never been available in the main release, they are only available on the experimental channel: `react-relay@experimental`

**Comment by mrtnzlml** [comment]
Hi @jstejada! :)

It happened again that relay-experimental with `hooks.js` is available in version 8.0.0 (just like it was in 7.0.0 but removed in 7.1.0). I wanted to ask if it's on purpose? Would it be possible to leave it there maybe? 🙂 

<img width="696" alt="Screenshot 2019-12-22 at 13 26 17" src="https://user-images.githubusercontent.com/978368/71321782-d25e4100-24be-11ea-9913-b8d60a2a0491.png">

**Comment by jstejada** [comment]
sorry this wasn’t on purpose, it was a mistake again; please use them from
the experimental npm tag, the will be removed in the next version.
