### ISSUE TITLE
Add test examples for fetchQuery

### ISSUE THREAD

**Issue by Aror** [facebook/relay#2946]
Running into problems with testing fetchQuery and there seems to be no examples available here: 
https://relay.dev/docs/en/v6.0.0/testing-relay-components

**Comment by mariomerendino** [comment]
Leaving a comment here since I just ran into this and google brought me here.

You can just use a similar mocking strategy as you would for `useLazyLoadQuery`:
```
it('does something', () => {
  [Render the component]
  [Fire event that triggers the fetchQuery call]

  act(() => {
    environment.mock.resolveMostRecentOperation(operation =>
      MockPayloadGenerator.generate(operation, {
        [MOCKED PAYLOAD FROM fetchQuery]
      }),
    );
  })

  [expect something]
}
```
