### ISSUE TITLE
FIELDS_CHANGE does not, when removing last item in an GraphQLList

### ISSUE THREAD

**Issue by quazzie** [facebook/relay#295]
How do i get the mutation to update a GraphQLList property.

Say i have ```user { id: '...', tags: ['hey', 'ho', 'do'], ...}```
Then i have a mutation that removes 'ho' from the list and i return the new list in the payload:
```payload { user: { id: '...', tags: ['hey', 'do'] } }```

If i use FIELDS_CHANGE its not reflected (because it merges ?) in the store.
```
getConfigs() {
  return [{
    type: 'FIELDS_CHANGE',
    fieldIDs: {
      user: this.props.user.id
    }
  }];
}
```

And i can't use NODE_DELETE because it requires a connection ?

Update: Its when you remove item(s) at the end of the list.

**Comment by quazzie** [comment]
```
fatQuery() {
  return Relay.QL`
    fragment on RemoveUserTagPayload {
      user { tags }
    }
  `;
}
```

**Comment by quazzie** [comment]
Found a bug, see 18964ef05d753ef991d5f621367d7b1849352fc6
With that it works.

**Comment by steveluscher** [comment]
Curious: when you remove the last item, does the payload return `tags: null` or `tags: []`?

**Comment by quazzie** [comment]
I ment the item at the last index. But i plan to return [] if empty.

**Comment by yuzhi** [comment]
@quazzie did 18964ef fix it for you? That code is for connections. Basic lists are considered as scalars and should have been updated here: https://github.com/facebook/relay/blob/18964ef05d753ef991d5f621367d7b1849352fc6/src/store/RelayQueryWriter.js#L259

**Comment by quazzie** [comment]
yuzhi: yes 18964ef did fix it and it's a GraphQLList(<othertype>).

**Comment by kassens** [comment]
Sounds like all issues are resolved here.
