### ISSUE TITLE
[react-native] Avoid using `ExecutionEnvironment.canUseDOM`

### ISSUE THREAD

**Issue by morrys** [facebook/relay#2954]
The canUseDOM variable defined with the following condition: `!!(typeof window !== 'undefined' && window.document && window.document.createElement);`
This condition returns **false** in react-native context.

The change only affects relay-experimental & tests:
 * https://github.com/facebook/relay/blob/master/packages/relay-experimental/QueryResource.js#L155

 * https://github.com/facebook/relay/blob/master/packages/relay-experimental/preloadQuery_DEPRECATED.js#L162

 * https://github.com/facebook/relay/blob/master/packages/relay-experimental/preloadQuery_DEPRECATED.js#L194

**Comment by josephsavona** [comment]
What is the issue here?

**Comment by morrys** [comment]
I try to explain myself better:

As specified in the comment below, this condition must be true when “executed in a server environment”.
https://github.com/facebook/relay/blob/master/packages/relay-experimental/QueryResource.js#L153-L157

> // NOTE: If we're executing in a server environment, there's no need
> // to create temporary retains, since the component will never commit.
> if (!ExecutionEnvironment.canUseDOM) {
>   return {dispose: () => {}};
> }

While it is true even when it is executed in a react-native environment because ExecutionEnvironment.canUseDOM is false both on the server side and in react-native.

So even in react-native does not do the temporaryRetain.

**Comment by jstejada** [comment]
I think this makes sense, will test internally and land

**Comment by morrys** [comment]
This issue can be closed as it is resolved in this PR https://github.com/facebook/relay/pull/2960.
