### ISSUE TITLE
Invalid directives @relay found on FIELD

### ISSUE THREAD

**Issue by ryanmcclure4** [facebook/relay#2968]
I recently upgraded my project from using relay-compiler v.1.5.0 to v7.1.0. After upgrading, I'm now getting errors for using @relay and @inline directives when running relay-compiler:

```
relay-compiler --src ./src --schema ./node_modules/@reachify/graphql-schema/schema.graphql --watch
```
Output:
```
ERROR:
Invalid directives @relay found on FIELD.
...
- Invalid directives @inline found on FRAGMENT_SPREAD.
  mutations/routing/routing-flows/updateRoutingFlowMutation/index.js (8:46)
  7:       flow {
  8:         ...RoutingComponent_routingComponent @inline
                                                  ^
  9:       }
```
I checked in the code and it seems only arguments and argumentDefinitions are [whitelisted](https://github.com/facebook/relay/blob/5da3be070283c6dcd42774ba33c1590db65fe3c7/packages/relay-compiler/core/RelayParser.js#L107) now, and all other directives throw this error. Has support for these been removed entirely? Or am I missing something that happened between version 1.5.0 and 7.1.0? I'm really not finding anything when searching for related issues, and the [docs](https://relay.dev/docs/en/graphql-in-relay#directives) don't seem to mention that they shouldn't be working...

**Comment by sibelius** [comment]
@inline should be on fragment definition, not in fragment spread

check the docs

https://relay.dev/docs/en/graphql-in-relay.html#inline

````
fragment RoutingComponent_routingComponent @inline {
}
```

so you don't have @inline on spread

**Comment by ryanmcclure4** [comment]
I see, my bad! Thanks
