### ISSUE TITLE
relay-compiler should accept multiple paths in CLI

### ISSUE THREAD

**Issue by itelo** [facebook/relay#2973]
Hey everyone, nowadays we could only pass a path as an argument.

What I want is a option to pass multiple paths to relay compiler.

A possible solution could be:

`relay-compiler --src "./src/files1 ./src/files2" --others-arguments`

**Comment by sibelius** [comment]
there are some misunderstanding about `src` relay compiler parameter

src will be the root where relay compiler will try to find graphql tags

if you want to compile more places, you should do something like this:

relay.config.js

```jsx
module.exports = {
  schema: './data/schema.graphql',
  language: 'typescript',
  src: '../.',
  include: [
    './web/src/**',
    './shared/src/**',
  ],
};
```

gist: https://gist.github.com/sibelius/a337cdd1e804cfbb45dcb138d6b10600

what you really want, it to use includes in your use case

**Comment by mmmulani** [comment]
sorry to bump a closed issue but is there a way to solve this with the new compiler? the `include` field is deprecated in it

**Comment by mmmulani** [comment]
for anyone else who wanders here looking for how to make this work: https://github.com/mmmulani/relay-multi/blob/main/web-app/package.json#L20-L37

it seems like the right way to do it is use the relay multi project config style, with your shared project acting as the `base` for another project. It's not a straight forward map from including folders, but you can accomplish the same thing. (while also guaranteeing that files in the `base` project don't reference things outside it)
