### ISSUE TITLE
Error loading relay config with babel 

### ISSUE THREAD

**Issue by pula2000** [facebook/relay#2976]
Everything with Relay works fine, but when the react app starts in development mode I get the below warning message -
`There was an error trying to load the config "relay" for the macro imported from "babel-plugin-relay/macro. Please see the error thrown for more information.
`

**Comment by sibelius** [comment]
Can you share more code?

Are you using CRA? Follow CRA readme of how to use relay with CRA

**Comment by pula2000** [comment]
Given below is my babel.config.js. And I'm using typescript - 
```
module.exports = function (api) {
    api.cache(true);

    var plugins = [
        "relay",
        "macros"
    ];
    var presets = [
        "env"
    ];

    return {
        plugins: plugins,
        presets: presets
    };
};
```

**Comment by babangsund** [comment]
I'd recommend trying to reproduce it in a codesandbox @pula2000

**Comment by pula2000** [comment]
When I upgraded to version 8, the error went away.
