### ISSUE TITLE
unable to get correct data using `useLazyLoadQuery` when compose fragment into query.

### ISSUE THREAD

**Issue by videni** [facebook/relay#2979]
I do see a sucessfull API request

![image](https://user-images.githubusercontent.com/4058341/71641302-6ce72d00-2cd4-11ea-9a6e-85c29ee34bf8.png)

```
const data = useLazyLoadQuery<brandQuery>(
    graphql`query
      brandQuery {
        ...brand_autoBrands
      }
    `,
    {
      first: 10,
    },
    {
      fetchPolicy: "network-only",
    }
  );

  console.log(data);
```
 But I got following output. it is supposed to be a json object returned from my API.

![image](https://user-images.githubusercontent.com/4058341/71641283-21348380-2cd4-11ea-94ce-64f77dad8084.png)

brand_autoBrands fragment  somewhere
```
const autoBrands = graphql`
    fragment brand_autoBrands on AdminQuery
      @argumentDefinitions(
        first: { type: "Int", defaultValue: 10 }
        after: { type: "String", defaultValue: "" }
        last: { type: "Int" }
        before: { type: "String" }
        filters: { type: "[Filter]" }
        sorters: { type: "[Sorter]"}
      )
      @refetchable(queryName: "BrandListPaginationQuery") {
      autoBrands(first: $first, after: $after, last: $last, before: $before, filters: $filters, sorters: $sorters)
      @connection(key: "BrandList_autoBrands") {
        edges {
          node {
            ...brandFragment
          }
        }
        pageInfo {
          startCursor
        }
        totalCount
      }
    }
  `;

  const {
    data,
    loadNext,
    hasNext
  } = usePaginationFragment<BrandListPaginationQuery, _>(
    autoBrands,
    props.autoBrands,
  );

```

**Comment by videni** [comment]
this will happen when I compose fragment, for example , the following code will have the same problem

```
 const metadata = useFragment(
    graphql`
      fragment Grid_metadata on GridMetadata {
        filterSchema
        columns
        actions
        gridViews
      }
    `,
    props.metadata
  );

 const { gridMetadata } = useLazyLoadQuery<brandGridMetadataQuery>(
    graphql`
      query brandGridMetadataQuery($gridName: String!) {
        gridMetadata(gridName: $gridName) {
          ...Grid_metadata
        }
      }
    `,
    {
      'gridName': 'brand-grid'
    },
    {
      fetchPolicy: "network-only",
    }
  );
```

it will work however if we make following changes. how strange it is. 
```
const { gridMetadata } = useLazyLoadQuery<brandGridMetadataQuery>(
    graphql`
      query brandGridMetadataQuery($gridName: String!) {
        gridMetadata(gridName: $gridName) {
          filterSchema
         columns
         actions
         gridViews
        }
      }
    `,
    {
      'gridName': 'brand-grid'
    },
    {
      fetchPolicy: "network-only",
    }
  );
```

**Comment by videni** [comment]
can anybody help me with this problem ? I have no idea what is going on.

**Comment by sibelius** [comment]
Add console log to understand the data returned by each hook, you need to pass the right fragmentRef to get the correct data

**Comment by videni** [comment]
@sibelius , thanks,  can you give  me some more specific clues? the fragment I passed I think is correct.

> const metadata = useFragment(
>     graphql`
>       fragment Grid_metadata on GridMetadata {
>         filterSchema
>         columns
>         actions
>         gridViews
>       }
>     `,
>     props.metadata
>   );
> 
>  const { gridMetadata } = useLazyLoadQuery<brandGridMetadataQuery>(
>     graphql`
>       query brandGridMetadataQuery($gridName: String!) {
>         gridMetadata(gridName: $gridName) {
>           ...Grid_metadata
>         }
>       }
>     `,
>     {
>       'gridName': 'brand-grid'
>     },
>     {
>       fetchPolicy: "network-only",
>     }
>   );

this did not return correct json object, I got something like in the following picture.
![image](https://user-images.githubusercontent.com/4058341/71641283-21348380-2cd4-11ea-94ce-64f77dad8084.png)

**Comment by videni** [comment]
@sibelius , please do some help,  I log the two queries , the only difference is  the params text field
![image](https://user-images.githubusercontent.com/4058341/71773716-09dbeb80-2f9d-11ea-9a66-26354c2492f6.png)

```
// query without `...` 
"query brandGridMetadataQuery(
  $gridName: String!
) {
  gridMetadata(gridName: $gridName) {
    filterSchema
    columns
    actions
    gridViews
  }
}
"

//query with '...'
"query brandGridMetadata1Query(
  $gridName: String!
) {
  gridMetadata(gridName: $gridName) {
    ...Grid_metadata
  }
}

fragment Grid_metadata on GridMetadata {
  filterSchema
  columns
  actions
  gridViews
}
"
```

**Comment by sibelius** [comment]
what did you change to make it work?

**Comment by videni** [comment]
@sibelius , Disable data mask as you suggested [here](https://github.com/facebook/relay/issues/2982).

**Comment by sibelius** [comment]
Disabling is not the right solution

**Comment by tony** [comment]
@videni Question, what type goes in `_` in:

```typescript
usePaginationFragment<BrandListPaginationQuery, _>(
    autoBrands,
    props.autoBrands,
  );
```
