### ISSUE TITLE
CompilerContext misses info about directives defined in schema

### ISSUE THREAD

**Issue by jaroslav-kubicek** [facebook/relay#2981]
Hello in 2020 👋 

I'm trying to implement custom relay-compile transform which behaves as validator - when a deprecated field is used in some fragment, it should warn the user about that - initial commit here: https://github.com/adeira/universe/pull/281/files#diff-4d4b550b0922b3faffdec67d2f77bf60R5

The problem I have right now is that `CompilerContext` contains schema parsed by this utility: https://github.com/facebook/relay/blob/master/packages/relay-compiler/core/Schema.js  where such info is missing AFAIK -> looking on `_parseScalarNode` https://github.com/facebook/relay/blob/master/packages/relay-compiler/core/Schema.js#L1474 it receives `EnumTypeDefinitionNode`, but only its `name` property is stored. So I can effectively tell which directive was used by the user in a client app, but can't say much how directives are set in server schema (`@deprecated` being the main concern in this use case)

Could you confirm that such info is not there (except parsing `context.__source` property) or give a hint if I missed something?

Related commit where using transform as validator was suggested: https://github.com/facebook/relay/commit/15e8d2201fdad47596e1acfb3a5daa3fb7511a8e

**Comment by alunyov** [comment]
Thank you for question @jaroslav-kubicek 

When we've built this utility - the intention was to keep as minimal schema information during compiler runtime as possible. Relay Compiler (and Relay Runtime) doesn't use the information in the @deprecated directives by default, and we don't warn about it.

So we decided to skip this information in our internal Schema utility. And I don't think we have plans to add this in the upcoming releases.

Theoretically, you can create an instance of `graphql-js` schema (if it's not too big) in your custom directive, and use it to check if the field is deprecated.

**Comment by jaroslav-kubicek** [comment]
I was afraid of such news, but thanks @alunyov for your answer and tip! :)

I'm closing this then as it's not planned and I will probably follow your advice.
