### ISSUE TITLE
useMutation not exported in hook.js

### ISSUE THREAD

**Issue by matteoabbruzzo** [facebook/relay#2988]
Hi,
I have noticed in last release v8.0.0 experimental (0.0.0-experimental-5f1cb628) that the new hook for mutation isn't exported in hook.js like the other hooks. 
Is it possible to add the export ? Or should I import in my project in other way ?
Thanks

**Comment by jstejada** [comment]
Hey @matteoabbruzzo, thanks for flagging this, we missed it. We will export it in the next release. thanks!

**Comment by koistya** [comment]
Does the `useMutation(...)` hook even work (in the current `react-relay@experimental` package)?
It doesn't seem to trigger an HTTP request, but no errors either.

**Comment by jstejada** [comment]
are you calling the commit function you get back from the hook?

**Comment by koistya** [comment]
Yes, sure.

```jsx
import { graphql } from 'react-relay';
import { useMutation } from 'react-relay/lib/relay-experimental';

function PasswordReset() {
  const [state, setState] = React.useState({});

  const [resetPassword, loading] = useMutations(graphql`
    mutation PasswordResetMutation($email: String) {
      resetPassword(email: $email)
    }
  `);

  function handleSubmit(event) {
    event.preventDefault();
    resetPassword({
      variables: { email: state.email },
      onCompleted(res, errors) { ... },
      onError(err) { ... }
    });
  }

  // ...
}
```

**Comment by sibelius** [comment]
`import { useMutation } from 'react-relay/hooks'` 

should also work

**Comment by wadamek65** [comment]
Is this still the case? I'm on `0.0.0-experimental-8cc94ddc` and the hook still seems to not be exported properly? Or should I use a different version for the experimental relay?

**Comment by jstejada** [comment]
`0.0.0-experimental-895a6fe0` should include it
