### ISSUE TITLE
Can we pass arbitrary query string to a Relay query without variables declared first inside that query, or any workaround?

### ISSUE THREAD

**Issue by videni** [facebook/relay#3001]
I have a url like `/admin/product/create?_org_id=1`, the `_org_id` is very special which is globally available for resource creation, I don't like to add it to `CreateProductInput`, because if we follow this way, we need to add it to every resource creation input type. Can we pass arbitrary query string to a Relay query without variables declared first inside that query? or any workaround?
```
input CreateProductInput {
  name: String
  description: String
  images: [File]
  price: Int
  onHand: Int
  tracked: Boolean
  autoSeries: String
  channels: String
  clientMutationId: String
}

```

**Comment by robrichard** [comment]
@videni you can pass the value as a query param or header to your graphql server in the relay network layer

**Comment by videni** [comment]
@robrichard, I see, thanks,

**Comment by tony** [comment]
Can we have an example of a query string added at the relay network level?

**Comment by sibelius** [comment]
Just modify your fetch call inside network layer
