### ISSUE TITLE
Error: spawn ENOTDIR caused from missing Watchman CLI

### ISSUE THREAD

**Issue by ryparker** [facebook/relay#3008]
```
$ yarn relay
> relay-compiler --src ./src --schema ./data/schema.graphql
Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at Object.spawn (child_process.js:548:9)
    at /Users/~/GitHub/MERG-FE/node_modules/relay-compiler/bin/relay-compiler:1741:31
```

The above error can be reproduced if you do not have Watchman CLI installed when running the relay-compiler code. I tested on a few projects including the `https://github.com/relayjs/relay-examples` todo example. 

The obvious fix was to install Watchman CLI however i'm curious if this is in fact an intentional dependency? 

This is the code I found from investigating the node stack trace:

```
var GraphQLWatchmanClient =
/*#__PURE__*/
function () {
  GraphQLWatchmanClient.isAvailable = function isAvailable() {
    return new Promise(function (resolve) {
      // This command not only will verify that watchman CLI is available
      // More than that `watchman version` is a command that runs on the server.
      // And it can tell us that watchman is up and running
      // Also `watchman version` check ``relative_root`` capability
      // under the covers
      var proc = childProcess.spawn('watchman', ['version']);  <<<<< Stack trace
      proc.on('error', function () {
        resolve(false);
      });
      proc.on('close', function (code) {
        resolve(code === 0);
      });
    });
  };
```

**Comment by jgcmarins** [comment]
this should happen only if you pass `--watch` args
which version did you test?
can we close this one?

**Comment by ryparker** [comment]
The version used at the time was `8.0.0`

After retesting just now, I am no longer experiencing the same issue. I noticed the error has been replaced with the following message:

`[relay] Watchman is required to watch for changes. Running with watch mode disabled.`
