### ISSUE TITLE
We will have an useSubscription hook?

### ISSUE THREAD

**Issue by rayronvictor** [facebook/relay#3029]
Like `useMutation`, `useLazyLoadQuery` and `usePreloadedQuery` we will have an `useSubscription`?

**Comment by sibelius** [comment]
this is a simple `useSubscription` hook 

https://gist.github.com/sibelius/a5e233d908928d4ab45e5924bf69df88

I think you can add `config` to array dependencies of useEffect to make it more correct

**Comment by josephsavona** [comment]
Yes, we're working on adding a `useSubscription` hook :-)

**Comment by sibelius** [comment]
yes https://github.com/facebook/relay/commit/42056a7865e2b4020514dd1517bd450c86701779
