### ISSUE TITLE
Hooks not exported in v9.0.0 like described in the docs

### ISSUE THREAD

**Issue by sambou** [facebook/relay#3032]
In the [docs](https://relay.dev/docs/en/api-reference#relayenvironmentprovider) hooks are imported via the `react-relay` package:
```
const {RelayEnvironmentProvider} = require('react-relay/hooks');
```

However, compared to v8.0.0, in v9.0.0 the hooks.js file in the package disappeared.

**Comment by renanmav** [comment]
Are you on the `experimental` tag version of `react-relay`?

**Comment by sambou** [comment]
No, i'm on v8.0.0 at the moment.

**Comment by sibelius** [comment]
hooks are only available on `experimental` builds

relay v8 with hooks was a release mistake

**Comment by sambou** [comment]
Thanks for clearing that up! :)
