### ISSUE TITLE
GraphQLTag: Expected a request, got

### ISSUE THREAD

**Issue by t-heu** [facebook/relay#3033]
Error:
```
GraphQLTag: Expected a request, got `"/static/media/UserGra.59e836d8.graphql"`.
```
Aa.tsx
```
import React from 'react';
import {graphql, QueryRenderer} from 'react-relay';

import environment from '../Environment'

type Props = {
  ggmail: string,
  ggpass: string
};

const query = graphql`
  mutation UserGra($ggmail: String, $ggpass: String) {
    register(email: $ggmail, password: $ggpass)
  }
`;

export default class Aa extends React.Component<Props> {
  render() {
    const {ggmail, ggpass} = this.props;
    
    return (
      <>
      <QueryRenderer 
        environment={environment} 
        query={query} 
        variables={{ 
          ggmail, 
          ggpass
        }}
        render={({ error, props }: any) => {
          if (error) {
            return <h1>{error.message}</h1>;
          } else if (props) {
            return <h1>{ props } is great!</h1>;
          }
          
          return <h1>Loading...</h1>;
        }}
      />
      </>
    )
  }
}
```

Environment.ts
```
import {
  Environment,
  Network,
  RecordSource,
  Store,
} from 'relay-runtime';

function fetchQuery(operation: any, variables: any) {
  return fetch('/graphql', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query: operation.text,
      variables,
    }),
  }).then(response => {
    return response.json();
  });
}

const environment = new Environment({
  network: Network.create(fetchQuery),
  store: new Store(new RecordSource()),
});

export default environment;
```

recently I had this error without understanding in any way why, I researched a lot about nothing else ... I'm using relay and react and TypeScript.

versions:
- graphql-tag": "^2.10.3",
- react": "^16.12.0",
- react-dom": "^16.12.0",
- react-relay": "^9.0.0",
- relay-runtime: "^9.0.0"
- typescript": "^3.7.5"

-  "@types/react-relay": "^7.0.3",
-  "@types/relay-runtime": "^8.0.6",
-   "graphql": "^14.6.0",
-   "relay-compiler": "^9.0.0",
-   "relay-config": "^9.0.0"

**Comment by sibelius** [comment]
did you just upgrade to relay v8 or v9?

this looks like a  cache issue

check this issue https://github.com/facebook/relay/issues/2990 for some solution

**Comment by t-heu** [comment]
@sibelius already tried to use version 8 and 9 already tried to clear cache reinstall dependencies again nothing more

**Comment by sibelius** [comment]
can you share a repro? are you using CRA?

**Comment by t-heu** [comment]
@sibelius I'm using CRA (create react app) follow tutorial to give an "eject"

package.json
```
"babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      [
        "relay"
      ]
    ]
  }
```
package was the only place I set up

**Comment by t-heu** [comment]
@sibelius problem
![Screenshot_20200227-010825](https://user-images.githubusercontent.com/25287877/75411369-c6975c80-58fd-11ea-918a-dfc260aa2ce1.png)

**Comment by t-heu** [comment]
I'm closing here, because I managed to solve, I decided to redo the configuration of the relay in general.
