### ISSUE TITLE
props is passing null value was to receive an error

### ISSUE THREAD

**Issue by t-heu** [facebook/relay#3036]
`TypeError: Cannot read property 'email' of null`

I tested in the same way in the graphql as query I get the expected error, but when I try cok relay it returns props.me null and it was not to pass it was to give an error.

- relay 9.0.0

```
export function Dash(props: any) {
  return (
    <p>{props.view.me.email}</p>
  )
}

export default () => (
  <QueryRenderer
    environment={environment}
    query={query}
    variables={{}}
    render={({error, props}) => {

      if(error) {
       // it was supposed to fall here
        return <h5>{error.message}</h5>
      }

      if (!props) {
        return ( <p>Loading...</p> );
      }
      // props receive null 
      return (<Dash view={props} />);
    }}
  />
)
```

Backend
```
async me(_, __, { req }) {
    if (!req.userId) {
      throw new Error('You are not authenticated!');
    }

    return await User.findOne(req.userId);
  }
```

**Comment by sibelius** [comment]
Can you provide more code? This could be a problem in how you have implemented your network layer

Are you throwing errors there?

**Comment by t-heu** [comment]
@sibelius 
```
function fetchQuery(operation: any, variables: any) {
  return fetch('http://localhost:4000/graphql', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query: operation.text,
      variables,
    }),
  }).then(response => {
    return response.json();
  });
}

const environment = new Environment({
  network: Network.create(fetchQuery),
  store: new Store(new RecordSource()),
});

export default environment
```
problem that it is returning me null and the correct one was it returns an error this behavior is strange

**Comment by t-heu** [comment]
@sibelius give me a signal there, I spent a console in the Environment in the response there is returning the error but in QueryRender not only comes null in the props

**Comment by sibelius** [comment]
Check my blog post relay modern network layer deep dive

**Comment by t-heu** [comment]
@sibelius link?

**Comment by t-heu** [comment]
@sibelius so ... I found your example a bit complex for me, so I solved this problem in another way, so, I want to know your opinion if it is correct for me to do sessions correctly?
```
async function fetchQuery(operation: any, variables: any) {
  try {
    const response = await fetch("http://localhost:4000/graphql", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        query: operation.text,
        variables
      })
    });

    const dat = await response.json()
    if(dat.errors[0].message) {
      delete dat.data
      return dat
    }

    return await response.json()
  } catch(err) {
    return err
  }
}

export default new Environment({
  network: Network.create(fetchQuery),
  store: new Store(new RecordSource())
})
```

**Comment by sibelius** [comment]
Why not throw errors?

**Comment by t-heu** [comment]
@sibelius so i tried to throw a throw there, but i got another "data" error, then i decided to pass a console to see what is happening i realized i was getting "data" and "errors" so i decided to make a condition on this error and delete "data" so when the answer arrives in QueryRender it comes from the server error which is what I want, of course I intend to improve this condition.

**Comment by sibelius** [comment]
what is query?

**Comment by t-heu** [comment]
I forgot to close this issue, at the time I had this problem I redid the entire installation and solved it, apparently it was a bug from a poorly installed dependency.
