### ISSUE TITLE
Global types

### ISSUE THREAD

**Issue by c0m1t** [facebook/relay#3038]
I looked over the relay documentation and I could not find my answer anywhere.
Im wondering if there is a thing like global types as in apollo.

For instance I have an enum which I use in different components, each time relay defines that enum over and over. Although that enum is something global.

**Comment by sibelius** [comment]
yes

check this https://github.com/relay-tools/relay-compiler-language-typescript/issues/175

we just need to implement it

wanna try it out?

**Comment by c0m1t** [comment]
I couldnt find any reference to [RelayGraphQlEnumsGenerator](https://github.com/facebook/relay/blob/master/packages/relay-compiler/core/RelayGraphQLEnumsGenerator.js).
How would it will be called inside `relay-compiler`?

**Comment by c0m1t** [comment]
#3051

**Comment by c0m1t** [comment]
I dont think `relay` has any intention to make this possible, so we wrote a [package](https://github.com/c0m1t/relay-enum-generator) for this purpose:
`relay-enum-generator`.
