### ISSUE TITLE
relay.dev site is broken: GitHub Pages 404

### ISSUE THREAD

**Issue by subwindow** [facebook/relay#3054]
https://relay.dev/ returns a 404, the GitHub pages site cannot be found.

<img width="1229" alt="Screen Shot 2020-03-31 at 4 24 21 PM" src="https://user-images.githubusercontent.com/6236/78084070-1c7f7a00-736c-11ea-9fb7-f1e93690bf6c.png">

**Comment by Nilomiranda** [comment]
I think this can be closed now. Everything seems back to normal
<img width="1560" alt="Screen Shot 2020-04-01 at 07 25 18" src="https://user-images.githubusercontent.com/25915040/78127559-c0a80600-73ea-11ea-988f-039b5fc2a0f0.png">
