### ISSUE TITLE
Module not found: Can't resolve './__generated__/**.graphql' in Component class

### ISSUE THREAD

**Issue by pula2000** [facebook/relay#3055]
I'm using Relay in CRA with Typescript. Running the relay compiler does successfully create the runtime artifacts in `src/__generated__` folder. But I don't know why I get the above error when starting the react app?

It seems it's looking for the artifact in the same directory where the component resides. But all the artifacts are in one directory (`src/__generated__`). How do I fix this?

**Comment by sibelius** [comment]
check this https://create-react-app.dev/docs/adding-relay/

or this https://github.com/sibelius/create-react-app-relay-modern

**Comment by kirkbross** [comment]
+1
I'm not using CRA but I can't seem to get it to resolve any of my `__generated__/*.graphql` files.

**Comment by mikejackowski** [comment]
Same issue.

**Comment by mickdelaney** [comment]
for anyone who lands here. 
double check this 

https://github.com/relay-tools/relay-compiler-language-typescript#relay-compiler
