### ISSUE TITLE
RelayMutationRequest: Expected mutation to have exactly one variable

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#307]
I am getting this invariant in relay 0.3.1.

Reason is that query in the mutation also requires some variables for field arguments. 

I shortened output, as its very long but should illustrate the issue.

This invariant is in [getQueryString](https://github.com/facebook/relay/blob/master/src/network/RelayMutationRequest.js#L80)

`printedQuery.text`
```
mutation TagImagesMutation($input:tagImagesInput!){tagImages(input:$input){clientMutationId,...__RelayQueryFragmentgctwphk}} fragment __RelayQueryFragmentgctwphk on tagImagesPayload{viewer{_images7wkvra:images(first:50){edges{cursor,node{_relatedImagescfvst1:relatedImages(relationType:$relationType_0) .......
```
`printedQuery.variables`
```
Object {relationType_0: "SERIES", relationType_1: "PERSON", relationType_2: "MOTIVE", relationType_3: "SERIES", relationType_4: "PERSON"…}
```

**Comment by jardakotesovec** [comment]
And if I remove this invariant, server gives me:
```
{"message":"Variable \"$relationType_0\" is not defined by operation \"TagImagesMutation\"."},..}
```

Since field arguments were moved to `variables` I have troubles :-). Is this also bug or I am doing something wrong? Clearly `variables` can't have only $input, as they need to contain also field arguments for the query.

So I am still stuck with 0.1.1.

**Comment by josephsavona** [comment]
This is a bug, and I missed this when adding support for extracting enums & input objects from `query` types to the printer. For context, enums and input objects are new in GraphQL RFC so our support for them isn't as fully tested. @jardakotesovec we apologize that you've run into some bugs when using them and we'll get this fixed for the next release.

**Comment by jardakotesovec** [comment]
@josephsavona ok, thanks a lot for quick response. I will look forward to new version and meanwhile stick with 0.1.1

**Comment by josephsavona** [comment]
Alternately, use strings instead of enums ;-)

**Comment by josephsavona** [comment]
@jardakotesovec this is now addressed on master and will be out in the next release. thanks for filing the issue!

**Comment by jardakotesovec** [comment]
@josephsavona Great, thanks..  Noticed that it just missed 0.3.2 release. Hope another minor version bump will be soon :-).
