### ISSUE TITLE
LocalQueryRenderer returns undefined on node returned by fetchQuery on connection (or regular pagination container)

### ISSUE THREAD

**Issue by agdt3** [facebook/relay#3086]
The use case:
At some point in the app's lifecycle, I use `fetchQuery` to manually fetch a connection of edges with nodes, etc. This is to allow for a kind of windowed bidirectional pagination.
```
 const query = graphql`
   query paginatedPhotoDetailListQuery(
     $after: String
     $first: Int = 5
     $before: String
     $last: Int
     $photoLegacyId: String!
   ) {
     userPhotos(
       after: $after
       first: $first
       before: $before
       last: $last
       photoLegacyId: $photoLegacyId
     ) {
       edges {
         node {
           id
           ...
```

Somewhere down the line, I would like to load a store-aware node all by itself, from the existing store (so that mutations will cause a component re-render). Since the fetch options on `QueryRenderer` are `network-only` or `store-and-network`, I decided to try the `LocalQueryRenderer`, grabbing the ID param from a node in the connection returned by `fetchQuery`.

```
<LocalQueryRenderer
  environment={environment}
  query={graphql`
    query MyLocalQueryRendererQuery (
      $id: ID!
    ) {
        node(id: $id) {
          ...on Photo {
              id
          }
        }
      }
  `}
  variables={{
    id,
  }}
  render={({ error, props }) => {
    if (props) {
      return (
        <PhotoDetail
           photo={props.node}
        />
      );
    }
}}
/>
```

However, props consistently returns `{node: undefined}`.

I've also tried this with items loaded more traditionally from a paginated container, without any luck.

If I check the store manually via `envrionment.getStore().getSource().get(id)` the item exists, but `LocalQueryRenderer` doesn't return it.

Is there a way to get `LocalQueryRenderer` to return a node that had been loaded via a connection? If not, is it possible to render a component aware of the store (so that mutation work correctly) from the data fetched by `fetchQuery` or some other paginationContainer? Barring that, is there some way to subscribe to store changes for specific nodes to force manual component updates?

Any help is appreciated!

Dependencies:
```
"react-relay": "^9.0.0"
"react-relay-network-modern": "^4.4.0"
"relay-runtime": "^9.0.0"
```

Dev dependencies:
```
"babel-plugin-relay": "^9.0.0"
"relay-compiler": "^9.0.0"
```

**Comment by sibelius** [comment]
it looks like you need `MissingFieldHandler` to handle this properly

check this blog post: https://medium.com/jusbrasil-tech/caching-fields-on-relay-modern-with-hooks-30d76502e404

**Comment by agdt3** [comment]
Thanks @sibelius. The example you posted seems a bit out of date (throws a read-only error on `RelayDefaultMissingFieldHandlers`), but that did lead me to find a more current example here: https://github.com/facebook/relay/blob/master/website/versioned_docs/version-experimental/RelayHooks-AGuidedTourOfRelay.md

Forgot to actually retain the local operation too. For anyone who's intersted, here are the pieces:
1. Allow lookup by node and id
```
import {
  Environment,
  Network,
  RecordSource,
  Store,
  ROOT_TYPE,
} from 'relay-runtime';

const missingHandlerByRefConcreteTypeField = {
  kind: 'linked',
  handle(field, record, argValues) {
    try {
      if (
        record !== null &&
        record.__typename === ROOT_TYPE &&
        field.name === 'node' &&
        argValues.hasOwnProperty('id')
      ) {
        return argValues.id;
      }
    } catch (e) {
      // it wasn't be possible to transform the field ref
      return null;
    }
  },
};

export const env = new Environment({
  network: Network.create(...),
  store: new Store(new RecordSource()),
  missingFieldHandlers: [
    missingHandlerByRefConcreteTypeField,
  ],
});
```

2. Actually retain the fetchQuery operation
```
import {
  fetchQuery,
  graphql,
  createOperationDescriptor,
  getRequest,
} from 'relay-runtime';

const query = ...;

const operation = createOperationDescriptor(
  getRequest(query),
  {
    after,
    first,
    before,
    last,
    photoLegacyId,
  },
);

fetchQuery(env, query, variables).then(response => { env.retain(operation); })
```

3. User LocalQueryRenderer (as above)
