### ISSUE TITLE
It's possible to add several edges using RANGE_ADD

### ISSUE THREAD

**Issue by ricglz0201** [facebook/relay#3087]
I have this question because taking in consideration that's possible for cases like:

```javascript
const mutation = graphql`
  mutation RemoveTagMutation($todoID: ID!, $tagID: ID!) {
    removeTag(todo: $todoID, tag: $tagID) {
      removedTags {
        id
      }
    }
  }
`;
```

It is possible to do the following to remove all of those ids of a connection

```javascript
configs: [{
      type: 'RANGE_DELETE',
      parentID: todoID,
      connectionKeys: [{
        key: 'RemoveTags_tags',
      }],
      pathToConnection: ['todo', 'tags'],
      deletedIDFieldName: 'removedTags',
    }],
```

Thus, I am questioning myself why is not possible a similar behavior but for adding edges, or if actually it exists, all of this while using `RANGE_ADD`.

**Comment by sibelius** [comment]
for specific use cases, you need to use `updater`

check @zth relay-utils https://github.com/zth/relay-utils

**Comment by ricglz0201** [comment]
I am aware `updater` exists, though, I want to know why it's not implemented for `RANGE_ADD`, if it exists for `RANGE_DELETE`. Just mere curiosity

**Comment by sibelius** [comment]
if you take a look in the code, you gonna see that configs are like predefined updaters

**Comment by ricglz0201** [comment]
I did looked at it, that's why I noticed that the behavior of `RANGE_ADD` and `RANGE_DELETE` was different besides just the simple difference of instead of adding, removing.

So my problem/question is primarily why is that that their behavior is not exactly the same to be able to add/delete several nodes at the same time? Why did that was decided instead of providing a possibly more complete solution?

**Comment by sibelius** [comment]
I think they prefer to move these configs (similar to relay classic approach) outside Relay repo, so users can improve them

if something can be fixed in userland, it is better let users fix them, so we can avoid maintaining this complexity
