### ISSUE TITLE
Data rendering is not smooth after relay query fetch.

### ISSUE THREAD

**Issue by devethan** [facebook/relay#3101]
## Description
Hi. I am currently developing [expo-relay-boilerplate](https://github.com/dooboolab/expo-relay-boilerplate) based on `expo-web`.

During the implementation of authentication flow, the following unknown bugs were identified.

After relay queries runs, relay fetched the data and think it need to be render, but some components have not been rendered since the data was fetched, leaving the stale data in the view.

## Reproduction
Once logged in, the `<Home>` component is rendered according to `MainStackNavigator`.
The `<Home>` component consists of two main components.

1. `<Header>` : It renders user profile info
2. `<Friends>` : It renders friends list of the logged in user

`ethan1@test.com` has one friend list, `ethan2@test.com` has no friends.

The screenshot below is the result of printing console logs according to data fetching and component rendering.

<img width="1392" alt="Screen Shot 2020-06-16 at 11 21 31 AM" src="https://user-images.githubusercontent.com/55861805/84726677-66b9e400-afc8-11ea-944f-feade3875bd3.png">

### Step
1. Signin with `ethan1@test.com`, then signout.
2. Signin with `ethan2@test.com` (You can use password already given)
3. Render `<MainStackNavigator>` after fetching data by mutation
4. Execute `Header_Query`
5. Render `<Header>`
6. Render `<Friends>`
7. Complete fetching data by `Header_Query`
8. Render `<Header>`
9. Execute `FriendsQuery`
10. Render `<Friends>` (It has list of `ethan1@test.com`)
11. Complete fetching data of `FriendsQuery`
12. It should be rendered for updated data but it's not :(

`<Header>` and `<Friends>` are composed with same structure.
- `<Header>` : execute query > `<HeaderRightWidget>` : Declare data with Fragment
- `<Friends>` : execute query > `<Friend>` : Declare data with Fragment

Render timing is different though they are same structure.

You can check out the public source in [here](https://github.com/dooboolab/expo-relay-boilerplate/tree/enh/recreate-relay-instance-for-new-user)

Thank you for taking the time to read it.
Ask for help.

Thank you.

**Comment by sibelius** [comment]
if you want to avoid stale data

try to modify your fetchPolicy https://github.com/dooboolab/expo-relay-boilerplate/blob/master/src/App.tsx#L74

you also need to clean store when logging out (create a new environment)

**Comment by devethan** [comment]
@sibelius Thanks for your reply 👍 

I tried to change `fetchPolicy` from `store-or-network` to `store-and-network` but it still has same problem.

Here's my `<Friends>` component code

<img width="582" alt="Screen Shot 2020-06-17 at 11 58 37 AM" src="https://user-images.githubusercontent.com/55861805/84850109-e5c71f00-b091-11ea-9702-e5badcf89c84.png">

And this is the logs by result

<img width="387" alt="Screen Shot 2020-06-17 at 11 12 12 AM" src="https://user-images.githubusercontent.com/55861805/84847154-66365180-b08b-11ea-9c36-1511e631dffb.png">

It still doesn't render after fetching data from `RelayEnvironment`.

### What I intend
1. Fetching `FriendsQuery`
2. Complete fetching data from `FriendsQuery`
3. render Friends with the data

### What I did
1. Modify  `fetchPolicy` from `store-or-network` to `store-and-network` ([Check it](https://github.com/dooboolab/expo-relay-boilerplate/blob/54bb7d18833880c3975082403d657d5f5f7b8b1a/src/components/ui/Friends.tsx#L62))
2. Clean store when logging out by re-creating `RelayEnvironment` instance([Check it](https://github.com/dooboolab/expo-relay-boilerplate/blob/54bb7d18833880c3975082403d657d5f5f7b8b1a/src/relay/RelayEnvironment.ts#L40))

**Comment by sibelius** [comment]
check if you are getting the data from your network layer cache  (you should also clear it after logout) https://github.com/dooboolab/expo-relay-boilerplate/blob/master/src/relay/cacheHandler.ts#L23

try network-only in this cache https://github.com/sibelius/relay-workshop/blob/master/packages/web/src/routes.tsx#L46

**Comment by devethan** [comment]
Oh, It was my fault.
I reset relay environment but didn't updates global state.

Thanks to your support.
Have a good day. @sibelius
