### ISSUE TITLE
handle arguments on inline fragments

### ISSUE THREAD

**Issue by daniloab** [facebook/relay#3106]
When I try to pass some arguments to my inline fragment I got (that I imagined would happen)

```
ERROR:
Variables are not yet supported inside @inline fragments.
```

My question is whether inline fragments will support variables or any information about it.

**Comment by josephsavona** [comment]
`@inline` is a relatively newer feature so it's not fully flushed out yet. This is on our backlog but hasn't come up much - especially now that hooks make it easy to use the regular APIs (ie `useFragment`) as part of composable units of logic.

**Comment by webican** [comment]
Hi @josephsavona 

I'm already using useFragment hooks from the experimental tag. Occasionally I need to use fragments outside any React components though and neither @inline or @relay(mask: false) work with @arguments directive. Unfortunately I haven't found a workaround yet. Do you know when it will be implemented?

**Comment by josephsavona** [comment]
This hasn't come up a lot so it continues to be lower on our radar. Once we ship the Rust-based compiler to OSS (high on priority list) we will definitely revisit this.

**Comment by fdutey** [comment]
I need it too!!). Very convenient for localized fields in shared fragments ;)

**Comment by thibaultboursier** [comment]
Hello,

Has someone some news about the possibility to provide arguments to inline fragment?  
As @webican said, it seems there is no workaround, and it's necessary to have this option when we need to unmask fragment outside of React.

Thanks.

**Comment by josephsavona** [comment]
cc @alunyov @kassens — seems like this wouldn't be too hard to support now? Are we open to a PR to enable this?
