### ISSUE TITLE
Can not use react-relay/hooks

### ISSUE THREAD

**Issue by malay-adrixus** [facebook/relay#3107]
While using this statement 

`import { useRelayEnvironment } from "react-relay/hooks"; `

I always end up getting 

`Cannot find module 'react-relay/hooks' from 'src/components/TodoComponent/__tests__/TodoComponent.test.js'`

Is there any specific configuration that needs to be done in order to use this because documentation does not provide any such information regarding usage of hooks.

The react-relay version I am using is v9.1.0

**Comment by zth** [comment]
You need to install the experimental version of `react-relay`. I like to pin it to a specific version, so for example: `yarn add react-relay@0.0.0-experimental-94e87455`.

**Comment by malay-adrixus** [comment]
But then in that case how come the docs for relay v9.1.0 contains thee guide to use it?
https://relay.dev/docs/en/api-reference#relay-hooks

**Comment by zth** [comment]
🤷‍♂️ 

Here's the [index of doc versions](https://relay.dev/en/versions), you can go to the experimental docs from there.

**Comment by malay-adrixus** [comment]
Thanks
