### ISSUE TITLE
preloadQuery doesn't work as intended [PreloadedQuery_DEPRECATED]

### ISSUE THREAD

**Issue by devethan** [facebook/relay#3120]
## Description

We are currently creating a flow that shows user profile information when the user is logging in and out. 
However `preloadQuery` is not working as intended.
After the first preload query, the preload result, `type = "PreloadedQuery_DEPRECATED"` is returned, failing to receive the newly updated data and leaving the previous data.

The following oddities were found in the `preloadQuery`, which was checked every time the component was rendered.

This is the component in which is `preloadQuery` used.
<img width="588" alt="Screen Shot 2020-07-07 at 5 18 56 PM" src="https://user-images.githubusercontent.com/55861805/86750648-14289080-c079-11ea-8ee4-1bf2ef249bda.png">

<img width="951" alt="Screen Shot 2020-07-07 at 4 48 11 PM" src="https://user-images.githubusercontent.com/55861805/86750644-12f76380-c079-11ea-9fc7-7e331195f8a8.png">

There is no problem with the first preload, but it has not been able to show updated data since the second rendering, returning these types.

You can check in detail from [here](https://github.com/devethan/hackatalk/blob/684b988ae997dff8a3a4643f30f26e5d4d2fbc62/client/src/components/screen/ProfileUpdate.tsx#L95).

## Expectation

I expected the profile data will be preloaded and stored in the store after the first user login, and at the next user login, the preloadQuery, configured `fetchPolicy` as "network-only", will re-request the server to store and read the profile of the new login user.
I've also used `store.invalidateStore();` in the `mutation` updater to invalidate the cache of the previous user, but still `preloadQuery` has the cache value of the previous user.

I also created and replaced a new relay instance to solve this problem. (as [your guide](https://github.com/facebook/relay/issues/3101))

However, as [this problems](https://github.com/dooboolab/hackatalk/pull/153) arise, the app is eventually being configured as one instance.

**Comment by josephsavona** [comment]
Thanks for posting. Note that `preloadQuery` fetches data when it is called (depending on the fetch policy and if the query can be fulfilled from store). In your code, the call to `preloadQuery` is outside of any function and will therefore only run once, when the module is initialized. To refetch the data, you have to call preloadQuery again.

**Comment by josephsavona** [comment]
Please feel free to reopen if that doesn’t address the issue!
