### ISSUE TITLE
Typescript error in Relay generated files  "identifierField" not exist..

### ISSUE THREAD

**Issue by damikun** [facebook/relay#3156]
**# Issue**

Relay Generated files contains typescript error on _"identifierField"_.. App runs without problem in case ts is ignored...

This field does not exist under ReaderNode.d.ts

**Error:**

![image](https://user-images.githubusercontent.com/54806834/89100569-33a4a600-d3f8-11ea-9aad-9dae6fa786d8.png)

**TS Error Message**

(property) "identifierField": string
Type '{ connection: null; fragmentPathInResult: string[]; operation: any; identifierField: string; }' is not assignable to type 'ReaderRefetchMetadata'.
  Object literal may only specify known properties, and '"identifierField"' does not exist in type 'ReaderRefetchMetadata'.ts(2322)
`

**Is this field normaly part of relay ? because under ReaderNode.d i cannot find it...**

I saw _"identifierField"_ is searchable under **experimental** part...  can be missing typing...

```

Current one does not have it..
export interface ReaderRefetchMetadata {
    readonly connection: ReaderPaginationMetadata | null | undefined;
    readonly operation: string | ConcreteRequest;
    readonly fragmentPathInResult: ReadonlyArray<string>;
}
```
I have all in last versions  ( i think )  I also tried to go back with _react-relay_ from experimental to 10.0.1 but not results...

**# Versions** 
    "@types/relay-compiler": "^8.0.0",
    "@types/relay-runtime": "^10.0.1"
    "typescript": "^3.9.7"
    "babel-plugin-macros": "^2.8.0",
    "babel-plugin-relay": "^10.0.1",
     relay-compiler": "^10.0.1",
    "relay-compiler-language-typescript": "13.0.0",
    "relay-config": "^10.0.1",
    "relay-hooks": "^3.5.2",
    "react-relay": "0.0.0-experimental-8058ef82",

**Code include query** 

```
  const userquery = graphql`
    query UserDetailQuery($user_id: ID!) {
      userByID(user_id: $user_id) {
        ...UserDetail_user
      }
    }

  `;

  //@ts-ignore
  const UserDetailfragment = graphql`
    fragment UserDetail_user on User_DTO
      @refetchable(queryName: "UserDetailRefetchQuery") {
      id
      firstName
      lastName
      avatarImageName
      deactivated
      activTimestamp
      role {
        iD
        name
        code
      }
      # ...UserDetailGroups_user
      # ...UserDetailRole_user
      # ...UserDetailPremissions_user
    }
  `;

    const userdetaildata = useLazyLoadQuery<UserDetailQuery>(
      userquery ,
      {
        user_id: props.userid,
      },
      {
        fetchPolicy: "store-or-network",
      }
    );
  
    const [data, refetch] = useRefetchableFragment<
      UserDetailRefetchQuery,
      UserDetail_user$key
    >(UserDetailfragment, userdetaildata.userByID as UserDetail_user$key);

```

**Comment by taion** [comment]
This would be an issue for https://github.com/relay-tools/relay-compiler-language-typescript, not here.

**Comment by damikun** [comment]
> This would be an issue for https://github.com/relay-tools/relay-compiler-language-typescript, not here.

Thx for info of concrete repo... Im moving issue and closing this one....
