### ISSUE TITLE
Testing components with relay hooks keeps failing 

### ISSUE THREAD

**Issue by ben-elsen** [facebook/relay#3159]
## Description
I am trying to get testing working on the demo app, Issue tracker, of Relay but I keep getting stuck on the following error message: **Invariant Violation: preloadQuery(): Expected a RelayModernEnvironment**
`

      15 |   );
      16 |   const prepared = {
    > 17 |     rootQuery: preloadQuery(environment, RootQuery, {}),
         |                ^
      18 |   };
      19 | 
      20 |   const renderer = ReactTestRenderer.create(<Root props={prepared} />);

      at invariant (node_modules/fbjs/lib/invariant.js:40:15)
      at preloadQuery (node_modules/react-relay/lib/relay-experimental/preloadQuery_DEPRECATED.js:40:83)
      at Object.<anonymous> (src/Root.test.js:17:16)`

## My test file: Root.test.js:
` Root.test.js
import React from 'react';
import Root from './Root';
import ReactTestRenderer from 'react-test-renderer';
import { createMockEnvironment, MockPayloadGenerator } from 'relay-test-utils';
import { preloadQuery } from 'react-relay/hooks';

const RootQuery = require('./__generated__/RootQuery.graphql');

test('Link changes the class when hovered', () => {
  const environment = createMockEnvironment();

  environment.mock.queueOperationResolver(operation =>
    MockPayloadGenerator.generate(operation),
  );
  const prepared = {
    rootQuery: preloadQuery(environment, RootQuery, {}),
  };

  const renderer = ReactTestRenderer.create(<Root props={prepared} />);

  // At this point operation will be resolved
  // and the data for a query will be available in the store
  expect(
    renderer.root.find(node => node.props['data-testid'] === 'myButton'),
  ).toBeDefined();
}); `

## My environment:

- The repo: https://github.com/relayjs/relay-examples/tree/master/issue-tracker/src
- Dependencies: 
`dependencies": {
    "history": "^4.10.1",
    "husky": "^3.0.9",
    "lint-staged": "^9.4.2",
    "react": "0.0.0-experimental-f42431abe",
    "react-dom": "0.0.0-experimental-f42431abe",
    "react-markdown": "^4.2.2",
    "react-relay": "0.0.0-experimental-8cc94ddc",
    "react-router": "^5.1.2",
    "react-router-config": "^5.1.1",
    "react-scripts": "3.2.0",
    "relay-runtime": "9.0.0"
  },
`
- Dev dependencies: 
`"devDependencies": {
    "babel-plugin-relay": "^9.0.0",
    "concurrently": "^5.0.0",
    "cypress": "^4.5.0",
    "cypress-cucumber-preprocessor": "^2.2",
    "eslint-plugin-prettier": "^3.1.1",
    "get-graphql-schema": "^2.1.2",
    "graphql": "^14.5.8",
    "prettier": "^1.18.2",
    "react-test-renderer": "^16.13.1",
    "relay-compiler": "^9.0.0",
    "relay-test-utils": "^10.0.1"
  },`

**Comment by zth** [comment]
Can you try making sure that all Relay dependencies are pinned to the exact same version? Except for the experimental react-relay, which needs to match an experimental release after the major version you choose (and preferably before the next major if you're not using the latest version).

You seem to have version 10 of the test utils, but 9 of the rest of the packages.

**Comment by ben-elsen** [comment]
Hi @zth 

I just updated the package but the error keeps the same.. 

`issue-tracker yarn list --pattern relay            
yarn list v1.5.1
(node:21640) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
├─ babel-plugin-relay@9.1.0
├─ react-relay@0.0.0-experimental-8cc94ddc
├─ relay-compiler@9.1.0
│  └─ relay-runtime@9.1.0
├─ relay-runtime@9.0.0
└─ relay-test-utils@9.1.0
   └─ relay-runtime@9.1.0
✨  Done in 0.87s.`

**Comment by ben-elsen** [comment]
When I comment out line 40 in 'react-relay/lib/relay-experimental/preloadQuery_DEPRECATED.js', the tests succeed.

**Comment by zth** [comment]
It looks like you have two versions of relay-runtime installed, no? 9.1.0 and 9.0.0?

**Comment by ben-elsen** [comment]
It was indeed a strange problem with versions. I started a new project with a clean install and everything worked. Thanks for the help!
