### ISSUE TITLE
Mutation with config RANGE_ADD not working as expected on a newly created item.

### ISSUE THREAD

**Issue by Eldow** [facebook/relay#3174]
Hello everyone,

I'm facing an issue when updating optimistically the store with the help of the RANGE_ADD config.

I have a root query containing the list of car brands fragment.
```
  query BrandedCarQuery {
     ...BrandList_data
  }
```

The fragment in question :
```
  fragment BrandList_data on Query {
    brands(first: null, after: null)
      @connection(key: "BrandList_data_brands") {
      edges {
        node {
          id
          ...CarList_data
        }
      }
    }
  }
```

The brands fragment also contains a car list fragment.
```
  fragment CarList_data on Brand {
    cars(first: null, after: null)
      @connection(key: "CarList_data_cars") {
      edges {
        node {
          id
          name
        }
      }
    }
  }
```

I am performing creation mutations on both lists with this kind of mutations : (I use the nearly exact same for brand)
``` 
  mutation CarCreateMutation($carId: ID!, $name: String!, $brandId: ID!) {
    createCar(
      input: { id: $carId, car: { name: $name, brand: $brandId } }
    ) {
      carEdge {
        node {
          id
          name
        }
      }
    }
  }
```

with this kind of config (same one for brands): 
```
      configs: [
        {
          type: 'RANGE_ADD',
          parentID: brand.id,
          connectionInfo: [
            {
              key: 'CarList_data_cars',
              rangeBehavior: 'append'
            }
          ],
          edgeName: 'carEdge'
        }
      ]
```

It works perfectly fine when creating a car or a brand in an isolated manner. Let's say I create a brand - it gets created optimistically, reload the page, create a car -> Everything works fine, the view gets updated immediatly.
But if I create a brand, and create a car right after, the update stays stuck in client:local and the view doesn't show the newly created car. If I reload the page, the creation worked so the brand.id must be correct.

I suppose there is something that is not happening when updating the brands that prevent the optimistic update on cars to succeed, but I can't get a grasp on what and why.

Thanks for your read :)

**Comment by boo1-boo1** [comment]
Hey! I think the issue is with the CarList_data fragment. Since the fragment is on Query the parent is Query. Have you tried `fragment CarList_data on Brand`? I think this may solve the issue 🙂 I am new to Relay too, so I can't guarantee this is the solution.

**Comment by Eldow** [comment]
Thanks you for your reply, this was actually a mistake from me (oops !). I updated the post with the appropriate nested fragment. I am really interested in achieving this with configs instead of implementing the updaters by hand but do not know if this is actually feasible.

**Comment by boo1-boo1** [comment]
Hey, can you add the code where you add a brand and then a car immediately after? It will help us understand the problem a bit better.

**Comment by Eldow** [comment]
I made a small sandbox to have a better overview :) 
https://codesandbox.io/s/relay-nested-optimistic-creates-8hfoc?file=/src/Cars.tsx
It's not compiling / generated relay artifacts though

**Comment by Eldow** [comment]
I happened to work around this issue by performing my optimistic updates on the same connection key. Instead of having two nested connections and performing RANGE_ADD and RANGE_DELETE on both of these, I only kept the root one to perform updates on its nested array. Still a shame that the latter isn't supported because it felt right to use configs this way. I close the issue as this is not a problem to me anymore, but feel free to re-open it if you think this would be a nice to have.
