### ISSUE TITLE
Bug: unexpected field in the response (__typename alias)

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/relay#3179]
_Affected version: Relay 10_

Hi! 👋 We have a fairly complex mutation which returns large union (different types) and also some error types (under one `Error` interface). Example:

```graphql
mutation Test($input: TestInput!) {
  updateValue(input: $input) {
    __typename
    ... on Error { # could be UserInputError, SystemError, ...
      __isError: __typename
    }
    ... on FieldLargeText {
      text
    }
    ... on FieldText {
      id
    }
    # many other types ...
  }
}
```

The `... on Error` inline fragment is important here. My thinking was that I could fetch `__isError` field and if it's present, then I know it returned some error (any, don't care about the type). Sort of like `__isNode` works in Relay 10. This idea is supported by the response from our server (no `__isError` so it's a success):

```json
{
  "data": {
    "updateValue": {
      "__typename": "FieldNumeric"
    }
  }
}
```

**However**, when I try this in Relay I get the following (in both `updater` and `onCompleted`):

```json
{
  "updateValue": {
    "__fragmentOwner": " ... ",
    "__fragments": " ... ",
    "__id": "abcdef==",
    "__isError": "FieldNumeric"  // <<<
  }
}
```

This is an unexpected result. I wouldn't expect it in the response even though I can see how it happens. Generated Flow types correctly mark the field as optional. Is it a bug? 🤔 

Thanks for having a look!

**Comment by mrtnzlml** [comment]
Possible workaround is to fetch it like this (`Error` interface has a `message` field):

```graphql
... on Error {
# __isError: __typename
  __isErrorFIXME: message
}
```

The principle is the same: it's an error if the `__isErrorFIXME` field is available and has some value.

**Comment by mrtnzlml** [comment]
I am afraid this is still valid and should not be closed.

**Comment by josephsavona** [comment]
This result is expected: you’ve aliased `isError: __typename` so the typename is available under that field value. That happens bc by default in Relay we try to read any inline abstract fragment regardless of whether the type implements the interface. Can you try enabling the precise type refinement feature flag? That should get you the result you expect.

https://github.com/facebook/relay/blob/master/packages/relay-runtime/util/RelayFeatureFlags.js

**Comment by mrtnzlml** [comment]
Thanks for the explanation @josephsavona! 👍 

> Can you try enabling the precise type refinement feature flag?

Unfortunately, I am not working on the project anymore so I cannot try it. I was just driving this issue a bit longer. 😊 

I am going to close this issue for now since there is an explanation and hint about what to do next. Thanks again!
