### ISSUE TITLE
Typescript generator as something configured in the compiler config.json

### ISSUE THREAD

**Issue by maraisr** [facebook/relay#3181]
Following on from #3180, this here is to track the progress and implementation of the Typescript relay-typegen initiative. 

I think a good place to start looking is https://github.com/facebook/relay/tree/master/compiler/crates/relay-typegen/src

But @kassens  if you don't mind dropping some notes (or even edit this issue) about where to go, what to do and some rough implementation guide. I'd be more than happy to tackle this, this weekend! (I know I've said this in the past, but got stuck pretty quick).

**Comment by kassens** [comment]
This was resolved by ab5c96b, I'll try to add more details to the main issue how to run from OSS!
