### ISSUE TITLE
Allow to extend Input type

### ISSUE THREAD

**Issue by aleksandrlat** [facebook/relay#3186]
It is possible to extend on client `type`s and `interface`s

Add support for `input` extensions. Or add support to override field definitions with client schema extensions.

Allow to define input types in schema extensions.

See this piece for references of supported types https://github.com/facebook/relay/blob/master/packages/relay-compiler/core/Schema.js#L1821-L1845

Any reason why it is not implemented? After looking a bit at code implementation looks straight forward to me if I'm not missing anything.

**Comment by aleksandrlat** [comment]
I know relay team does not care about community. But will PR be accepted?

**Comment by josephsavona** [comment]
Apologies for the late reply. It isn't immediately clear how this would work. Extending types and interfaces with client-only fields allows developers to put values for those fields into the store and then read them back out in components. But extending an input type would allow passing additional values into an object that the server doesn't understand, which would cause runtime failures.

**Comment by aleksandrlat** [comment]
Thank you @josephsavona for reply!
My use case is when I mock server entirely. For example when we have new contract but it is not implemented yet on BE, but I want to implement FE and with mocked server.

**Comment by josephsavona** [comment]
I understand how allowing this feature would be handy for that use-case, but unfortunately I don't think this feature can be implemented as in the general server would reject the unknown input fields. For that use-case I would recommend either mocking the server entirely, or using a new (mock) field on the client that uses a mock input type (note that you cannot _extend_ a server input type, but you should be able to define your own _new_ client-only input type).

**Comment by aleksandrlat** [comment]
Thank you @josephsavona! Can/should we remove client only input types too?

**Comment by josephsavona** [comment]
No, client-only input types are fine, because those types can be used for the arguments of client-only fields.

**Comment by josephsavona** [comment]
I'm closing since we don't plan to add this feature, but happy to answer additional questions.
