### ISSUE TITLE
Document that existing Routing solutions to do not work with Relay Hooks

### ISSUE THREAD

**Issue by gajus** [facebook/relay#3189]
https://relay.dev/docs/en/routing

Does not mention anything about either of the suggested solutions not working with Relay Hooks.

It is a bit of a painful thing to learn midway through adopting Relay Hooks.

Even though it is an experimental technology, it would be a simple pain to avoid with a mention in the docs.

**Comment by zth** [comment]
How is it not working?

**Comment by hegelstad** [comment]
I believe that it is required to roll your own custom routing implementation based on for example history and react-router-config to do routing based on the "render-as-you-fetch"-approach with Relay Hooks. Here is an example of just that: https://github.com/relayjs/relay-examples/tree/master/issue-tracker/src/routing

**Comment by gajus** [comment]
We have since released https://www.npmjs.com/package/yarr
