### ISSUE TITLE
[rust] add non-Watchman file source

### ISSUE THREAD

**Issue by kassens** [facebook/relay#3193]
Currently the new Rust based compiler has a dependency on having `watchman` () available.

This isn't a hard blocker as watchman is available for all platforms, but it might be nice to remove this dependency to make usage easier.

The code in this directory: https://github.com/facebook/relay/tree/master/compiler/crates/relay-compiler/src/watchman
takes in a config of directories and builds a query to find js/typescript files in these directories as well as schema files.
It also supports watching for changes.

We were keeping the config file pretty high level so it should be possible to implement a glob based file searcher fairly easily. Maybe without support for watch mode?

This would need to integrate somehow via the config file to switch to a different file source.

**Comment by alunyov** [comment]
Added here: https://github.com/facebook/relay/commit/e5dd81f1bdb8b2e638a75751e8a3553efa034c7c
