### ISSUE TITLE
[rust] figure out how to deploy pre-built binary to npm

### ISSUE THREAD

**Issue by kassens** [facebook/relay#3194]
I don't want folks to need a Rust compiler just to use the Relay compiler.

The `flow-bin` npm package publishes a binary Flow type checker. We can probably borrow what they're doing.

This issue is to keep track what needs to be done for that. Maybe we need hosting space for binary files if they're loaded on demand?

**Comment by zth** [comment]
Just a note: I _think_ it's a fairly common approach to pre-build binaries for all platforms, ship all binaries in the npm package, and then have a node postinstall script that figures out the current platform and removes the rest of the binaries. 

Here's an example of the postinstall I have for `reason-relay` which ships binaries for Linux and macOS currently: https://github.com/zth/reason-relay/blob/master/packages/reason-relay/scripts/release-postinstall.js

**Comment by maraisr** [comment]
Thing is that is pretty huge download then. node-sass afaik uses node-gyp or something to build as soon as it lands on the system. Granted that's a c++ thing, but maybe something similar could work.

Heck we could even host the binaries out of GitHub releases, and just download it that way.

Or you know what'll be sick, a brew, choco style install too maybe if you want a binary rather than wasm.

**Comment by zth** [comment]
Yeah, the package size might def. be problematic. On the other hand, it ensures that if you have the package cached (your own mirror, locally in the yarn/npm cache, or whatnot) it's guaranteed to work forever with no maintenance (external hosting changes, which breaks all old packages, etc).

Do we know how large the compiler binaries are?

**Comment by alunyov** [comment]
@zth the size is 7.9MB - so it's not terrible, I think.

<img width="264" alt="Screen Shot 2021-03-14 at 10 22 16 PM" src="https://user-images.githubusercontent.com/102968/111095407-bdcaf600-8513-11eb-8dd1-df6f9e4522d1.png">

An interesting fact, I find this issue via google search: `rust binary via npm` - and it's the fourth
 item in the search results :-)

**Comment by kassens** [comment]
I recently landed a change that now builds and uploads a `--release` build during CI, e.g.:
https://github.com/facebook/relay/actions/runs/680416644

(Screenshot in case that's somehow only available to maintainers)
![image](https://user-images.githubusercontent.com/11849/112216833-5807f980-8bf8-11eb-9626-733975f049e3.png)

There might be more flags to strip debug symbols or we might need to statically link some libraries, but about 10mb seems fine. `flow-bin` for example contains 4 pre-built binaries of about 30mb:
```
 33M	node_modules/flow-bin/flow-linux-arm64-v0.147.0
 27M	node_modules/flow-bin/flow-linux64-v0.147.0
 23M	node_modules/flow-bin/flow-osx-v0.147.0
 39M	node_modules/flow-bin/flow-win64-v0.147.0
```

I think we can do the same which avoids us depending on downloading a thing on first use (which IIRC is what flow did in earlier versions)

**Comment by kassens** [comment]
Copied the approach from flow-bin with #3419, for now under a new npm module name: `relay-compiler-experimental`.

**Comment by alunyov** [comment]
I think we can close this for now. The deployment is working.
