### ISSUE TITLE
[rust] missing flow typegen config options

### ISSUE THREAD

**Issue by kassens** [facebook/relay#3195]
The Rust compiler doesn't have all the options and capabilities to print Flow code that we have in the OSS compiler (we cut some corners in configurability to get this massive project over the finish line!)

Let's track here what options are missing and if someone is working on a PR for parts of it!

**Comment by alunyov** [comment]
I think we're now have all of the typegen flag supported in rust (with this commit: https://github.com/facebook/relay/commit/dc74f42f22343801203fa98f4d6172e5fb2d0287)
