### ISSUE TITLE
[rust] refine typescript type generation

### ISSUE THREAD

**Issue by kassens** [facebook/relay#3196]
@MaartenStaa send a huge first chunk of type generation for TypeScript on the new Rust based compiler.

There is an existing OSS project to generate TypeScript types and there are some differences in the output. We should probably check what's different and what makes sense to incorporate.

OSS project: https://github.com/relay-tools/relay-compiler-language-typescript/blob/e1b092f081d4e816ecd17fb0d3b4e62cdf3db917/test/__snapshots__/TypeScriptGenerator-test.ts.snap

**Comment by maraisr** [comment]
@kassens think you meant "to generate Relay types slightly differently?".

I can put this side-by-side, using their schema and see where the differences are. Would you want a PR here to add that as an "acceptance-test". Or just perform that in another repo, and link for validation?

**Comment by kassens** [comment]
@maraisr Correct, I edited the text now.

It looks like the `relay-tools` project is already using some fork of the Relay flow fixtures for the test so it should be somewhat easy to compare the differences.
