### ISSUE TITLE
Nested fragments seem to GC even though still referenced

### ISSUE THREAD

**Issue by maraisr** [facebook/relay#3215]
### Scenario
We have a scenario where we have a base implementation that get's overrides from consumers. Think of a "Status" component, to one audience this needs to be Yellow to another its Green.

So for this we have a fragment called `Status` (base), then another that's called `StatusConsumer` (consumer).

The `StatusConsumer`, spreads the `Status` fragment, and then finally the consumer's query, spreads the `StatusConsumer` fragment.

`Query (query) -> StatusConsumer (fragment) -> Status (fragment)`

### Symptom 

Now, what we believe to be happening is—if we unmount the `StatusConsumer` component, come back 1s later (within the GC time), we get presented with the warning at https://github.com/facebook/relay/blob/9c0ce66c667f1f7c1418e43469872894a75a07a6/packages/relay-experimental/FragmentResource.js#L228-L247 even though we still render ok??? (We don't unmount, query, just the component @ StatusConsumer)

To alleviate the issue, all we did was also spread the `Status` fragment in our consumers query, which took this problem away.

`Query -> { Status, StatusConsumer -> Status }`

But, I don't think this is right? 

### Maybe cause?

So my question is, if a root Query that isnt loosing reference to things, should that drop references, if child components unmount? Are the reference checks keeping its hierarchy. 

Ie `Query -> StatusConsumer -> Status`, unmounting `StatusConsumer` shouldn't _loose reference_ to `Status` as `StatusConsumer` is still "active" by `Query`, and `Status` still being a transitive dependency of `Query`.

---

react-relay: 0.0.0-experimental-183bdd28
relay-runtime: 0.0.0-master-817590d4

using: `useFragment` and `useLazyLoadQuery`

**Comment by hegelstad** [comment]
I am seeing the same errors and I am not able to make sense of it.. Here is a concrete instance of these errors.

Warning: Relay: Tried reading fragment `Avatar_user` declared in `useFragment()`, but it has missing data and its parent query `RootQuery` is not being fetched.
This might be fixed by by re-running the Relay Compiler.  Otherwise, make sure of the following:
* You are correctly fetching `RootQuery` if you are using a "store-only" `fetchPolicy`.
* Other queries aren't accidentally fetching and overwriting the data for this fragment.
* Any related mutations or subscriptions are fetching all of the data for this fragment.
* Any related store updaters aren't accidentally deleting data for this fragment.

<img width="1420" alt="Screenshot 2020-10-15 at 20 11 56" src="https://user-images.githubusercontent.com/6997343/96169614-b1218200-0f22-11eb-96ac-6581f7a220de.png">

**Comment by hegelstad** [comment]
```javascript
component: JSResource('Root', () => import('./Root')),
prepare: (params) => {
  const RootQuery = require('./__generated__/RootQuery.graphql');
  return {
     RootQuery: preloadQuery(
        RelayEnvironment,
        RootQuery,
        {},
        // Use (network-only) to always return fresh results for currentUser.
        { fetchPolicy: 'network-only' },
     )
  };
},
routes: [
  {
    path: '/',
    exact: true,
    component: JSResource('Intro', () => import('./MainCourse/Intro')),
    prepare: (params) => {
      const RootQuery = require('./__generated__/MainCourse/IntroQuery.graphql');
      return {
        IntroQuery: preloadQuery(
          RelayEnvironment,
          IntroQuery,
          {},
          { fetchPolicy: 'store-or-network' },
        )
      };
    },
  }
]
```

It seems if I add a query, IntroQuery, to the child route that holds RootQuery, then if the queries read the same fields, I get the error: `"Warning: Relay: Tried reading fragment `Avatar_user` declared in `useFragment()`, but it has missing data and its parent query `RootQuery` is not being fetched."`

Instinctively I try to use a fragment in the Intro-route, however I don't find an obvious way to pass down the required fragment reference needed to do that.

Am I doing something wrong?

**Comment by jstejada** [comment]
hey @maraisr, sorry for the delay here, this definitely sounds off. quick question: which versions of react and relay were you using? were you using react concurrent mode?

**Comment by jstejada** [comment]
hey @maraisr, this should be fixed with 24bac58f46bc7694f069e46c4493201dfea60786, so closing. if you find any additional issues feel free to reopen

**Comment by tslater** [comment]
@jstejada, I've been getting these errors and am excited for your fix! Thanks! I'm currently using hooks on the experimental release, do you know if there is a way to use hooks on master so I can try this now?

**Comment by jstejada** [comment]
we will have a new release out hopefully by the end of this month, or early next month
