### ISSUE TITLE
[question] When hooks will become stable?

### ISSUE THREAD

**Issue by aleksandrlat** [facebook/relay#3216]
Hooks have been part of experimental version of relay for ages.

Any plans to make them part of "stable" version?

**Comment by maraisr** [comment]
It's waiting for Suspense to land in stable React, before this can be. But if i was to guess, it'll be soon.

**Comment by aleksandrlat** [comment]
Here is Releasing Suspense issue in react repo https://github.com/facebook/react/issues/13206#issuecomment-614082019
It does not sound like soon
