### ISSUE TITLE
[Feature request for experimental] Need a new API for accessing the RelayRecordSourceProxy instance outside a `updater` of a mutation

### ISSUE THREAD

**Issue by Albert-Gao** [facebook/relay#3219]
My use case is simple,

- On the list page, the page has a connection query to fetch a list of items
- clicks the item, the app goes to item detail page
- on the detail page, i check if the item is there in the Relay store or not (Because the user could refresh the page)
- if the data is in Relay store, i use it
- otherwise, i send my own query

I am using the experimental version, and this requirement seems pretty hard, the best approach i can come up with is to save the response to the Redux, but that will deprecate the relay's fragment usage, and fetch everything on the list page level then pass down to the item like the traditional way.

===========
1. Currently, the only way I know is to use `commitLocalUpdate()`

```javascript
const useProjectFromRelayStore = (projectId: string) => {
  const relayEnv = useRelayEnvironment()
  const [projectName, setProjectName] = React.useState('')
  
  React.useEffect(() => {
    commitLocalUpdate(relayEnv, (store) => {
       // get the data
       setProjectName(projectName)
      }
    })
  }, [relayEnv])

  return projectName
}
```

It works, but it will trigger multiple re-render since the reading happens inside a callback

2. I tried to use the `lookup()` from a relayStore instance, however, it won't return a nested data. for example, a connection fragment under a `Query`.

3. I tried to recreate the implementation of `commitLocalUpdate()`: https://github.com/facebook/relay/blob/56dd671b100bb119d4fca50f23333e9024dc71be/packages/relay-runtime/store/RelayPublishQueue.js#L292 However, the `RelayRecordSourceMutator`, `RelayRecordSourceProxy` are not exported, and received an error of `RelayRecordSourceMutator` is not a constructor function when imported like `const {RelayRecordSourceMutator} = require('relay-runtime/lib/mutations/RelayRecordSourceMutator')`

What am I missing here? Or is there a Relay idiomatic way of reading data from the Relay Store directly? Thanks :)

A new API to access the RelayRecordSourceProxy instance in a sync way like what we receive from the parameter of the updater() is more than welcome.

**Comment by zth** [comment]
Hmm, I'm not sure I quite follow what you're trying to do. Could you elaborate some? Are you simply looking to only make a request if there's no cached data you can use, and if there's cached data only use that...?

**Comment by sibelius** [comment]
can't you use fetch policy for this?

**Comment by tbergq** [comment]
[readInline](https://relay.dev/docs/en/graphql-in-relay.html#inline)?

**Comment by zth** [comment]
Or are you perhaps talking about that Relay does not understand that the item you're navigating to is in fact already in the store (since it was fetched with the list) when you navigate to the details page? If that's the problem, you should look into missing data handlers: https://relay.dev/docs/en/experimental/a-guided-tour-of-relay#filling-in-missing-data-missing-data-handlers

**Comment by Albert-Gao** [comment]
Thanks for the replies, guys!

@sibelius no, it does not work, since Relay can not relate that `projectConnection` query to a `node on Project` query. :(

@tbergq Learned a new API, thanks! but it won't work, since the detail page is on a different route, which means, I can not pass the fragementRef down to it.

@zth This seems to be what I am looking for! but I do not know how to link the `projectConnection` query to a `node on Project` query. 

for a connection query like the below:

```typescript
const connectionQuery = graphql`
  fragment useProjectListQuery_FragmentQuery on Query
  @argumentDefinitions(
    orgId: { type: "String!" }
    first: { type: "Int", defaultValue: 50 }
    after: { type: "String" }
    last: { type: "Int" }
    before: { type: "String" }
  )
  @refetchable(queryName: "useProjectListQueryPaginationQuery") {
    projectConnection(orgId: $orgId, first: $first, after: $after)
      @connection(key: "useProjectListQuery_projectConnection") {
      edges {
        node {
          id
          ...useProjectListItemFragment_project
        }
      }
    }
  }
`
```

and a `node` query like this:

```typescript
const projectHeaderQuery = graphql`
  query ProjectHeaderQuery($projectId: ID!) {
    node(id: $projectId) {
      ... on Project {
        name
        taskInfo {
          all
        }
      }
    }
  }
`
```

How to link them together?

The `connection` receives these params, 
![image](https://user-images.githubusercontent.com/18282328/96646513-be0dfd80-1388-11eb-9197-8d7c58a80ca8.png)


The problem is, they are all definitions, not real data, and without knowing the `id` for `node`, how could i possiblely link an array of object with id to one specific id?

Some help would be grateful,

that doc is a little bit confusing, as it is comparing the `node` query to a `user` query, but the example does not have a `node` query but a `story` query? Kind of get it though.

**Comment by sibelius** [comment]
maybe missing field handlers?

https://medium.com/jusbrasil-tech/caching-fields-on-relay-modern-with-hooks-30d76502e404?source=---------0-----------------------

**Comment by Albert-Gao** [comment]
@sibelius Thanks,

solved it now!

```typescript
const missingFieldHandlers: MissingFieldHandler[] = [
  {
    handle(field, record, argValues) {
      if (
        record != null &&
        record.__typename === ROOT_TYPE &&
        field.name === 'node' &&
        argValues.id
      ) {
        return argValues.id
      }
    },
    kind: 'linked',
  },
]
```

works beautifully!

I finally understand its API, it is used to transform the id of a missing field to another id which might exist in Relay Store. The `return null` part in the doc is what blocked me. I thought it is only for that case, actually, it will be called for all the missing fields!

Thanks so much, this is how things should work! I already solved it by reading cache from the store instance, but this is just more elegant!

Thanks!
