### ISSUE TITLE
Unable to retrieve connection from store - returns undefined

### ISSUE THREAD

**Issue by nihiluis** [facebook/relay#3223]
I'm unable to retrieve the `RightSidebarQuery_recently_viewed_document_connection` connection from the store (in an updater function for a mutation). I have no clue why. Using `ConnectionHandler.getConnection` returns undefined. I checked the redux devtools infos, docs and the #help-graphql channel on the reactiflux discord to no avail. Can I debug this further?

https://gist.github.com/nihiluis/1b99042a8a262a757a309cb8c9173745

I'm on experimental ("^0.0.0-experimental-183bdd28") Using next.js and Harusa.

Here you can see that the connection (should) be available in the store.
![image](https://user-images.githubusercontent.com/24858082/96773814-62be2880-13e5-11eb-909a-b746f09b2349.png)

# Creating issues for Relay

## Questions regarding how to use Relay and/or GraphQL

We want to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Relay.

If you have a question on how to use Relay, please get in touch with community members through one of the channels listed [here](https://facebook.github.io/relay/en/help.html) instead.

## Reporting issues with Relay

We will be using GitHub Issues for our public bugs. We will keep a close eye on this and try to make it clear when we have an internal fix in progress. Before filing a new issue, make sure an issue for your problem doesn't already exist.

The best way to get your bug fixed is to provide a reduced test case. To make reproduction simple for you, and set-up simple for Relay's maintainers, you can use Glitch:
https://glitch.com/edit/#!/remix/relay-starter-kit

You can also provide a public repository with a runnable example.

## Security bugs

Facebook has a [bounty program](https://www.facebook.com/whitehat/) for the safe disclosure of security bugs. With that in mind, please do not file public issues; go through the process outlined on that page.

**Comment by sibelius** [comment]
try

```jsx
@connection(key: "RightSidebarQuery_recently_viewed_document_connection", filters: [])
```

https://relay.dev/docs/en/graphql-in-relay#connectionkey-string-filters-string

this will create only one connection instead one connection for each argument

**Comment by nihiluis** [comment]
that does return a connection. Thank you

CAn you also pass the filter variables in experimental?

```
const connectionRecord = ConnectionHandler.getConnection(
          baseRecord,
          connectionName,
          { order_by: { timestamp: "desc" } }
        )
```

I suppose that would be a better solution. Is the format here correct though? With that alone it returns undefined. or would I specify the filters differently?

**Comment by sibelius** [comment]
yes

**Comment by nihiluis** [comment]
thank you. per chance do you have any idea where this is coming from?

```
![image](https://user-images.githubusercontent.com/24858082/96786915-38726800-13f1-11eb-8538-f0c722a52cdd.png)
```

I have checked the conditions and the only one that seems suspicious is this one:
`* Any related mutations or subscriptions are fetching all of the data for this fragment.`

apparently the created edge is stored differently:

compare this
![image](https://user-images.githubusercontent.com/24858082/96787125-86876b80-13f1-11eb-95c2-7961e1d476d4.png)

to this (naming scheme different and the original edges have a cursor property)

![image](https://user-images.githubusercontent.com/24858082/96787168-9acb6880-13f1-11eb-92a5-adbeca9e37b4.png)

**Comment by nihiluis** [comment]
when I pass junk like this the warning disappears:

![image](https://user-images.githubusercontent.com/24858082/96788885-7de46480-13f4-11eb-8bc3-975032cd9601.png)

**Comment by sibelius** [comment]
related to https://github.com/facebook/relay/issues/3215
