### ISSUE TITLE
[relay-compiler] Compiler fails to parse .graphql with old interface syntax

### ISSUE THREAD

**Issue by ben-elsen** [facebook/relay#3240]
The compiler isn't able to parse a graphQL schema with the old syntax for implementing multiple interfaces. 

The old syntax is: 
```
""" The field type for link fields """
type LinkField implements Node, FieldInterface @aws_cognito_user_pools @aws_api_key{
  """ The id field """
  id: ID
  """ The label of the field """
  label: String
  """ The url to link to """
  href: String
  """ The column number the field in the original csv """
  columnNumber: Int
  """ The values of a field """
  values: [String]
}
```

The new (supported by relay-compiler) syntax is: 
```
type LinkField implements Node & FieldInterface @aws_cognito_user_pools @aws_api_key{
  """ The id field """
  id: ID
  """ The label of the field """
  label: String
  """ The url to link to """
  href: String
  """ The column number the field in the original csv """
  columnNumber: Int
  """ The values of a field """
  values: [String]
}
```

The reason I am still using the old syntax is because I use AWS Appsync and they don't (yet) support the new syntax. 

Could we do something like at [graphql-schema-linter](https://github.com/cjoudrey/graphql-schema-linter)? They have a flag that can be used to indicate if you want to use the old syntax. 

Kind regards, 
Ben

**Comment by zth** [comment]
Hmmm, if you introspect AWS AppSync, shouldn't you be able to just reprint the schema in the newest syntax? Shouldn't that "just work"? How're you retrieving your `schema.graphql` file right now?

**Comment by ben-elsen** [comment]
To be honest, I haven't tried that.. Untill now, I just copy paste my schema from my backend project. I will do so! Do you have an example of such a script?

**Comment by sibelius** [comment]
I do thing we should only accept the newer syntax

**Comment by zth** [comment]
@ben-elsen check out `get-graphql-schema`, that should do the trick.

**Comment by ben-elsen** [comment]
@zth Thanks!
