### ISSUE TITLE
Props not updated when refetch container fired

### ISSUE THREAD

**Issue by guanw** [facebook/relay#3252]
# Creating issues for Relay

## Questions regarding how to use Relay and/or GraphQL

Hi, I understand that people try to keep github for the best place to track issues but i couldn't find any good explanation or doc on this issue.

I'm trying to make refetch container works. A reproducible example is [here](https://github.com/guanw/relay-refetch-example)

## What I've done
1. I've already checked issues like #2244 but since no complete code samples were given so it's bit hard to grasp what happened there.
2. I also asked this question in slack but no one seemed to have an answer (nor care to give an answer)

Would really appreciate if anyone can help pointing out what i did wrong in sample code. Thanks in advance!

**Comment by jstejada** [comment]
hey, we'd recommend using `useRefetchableFragment` here, which is the recommended api for refetch going forward and addresses these types of issues.

It is available in v11.0.0-rc.0, and we will include docs for it when v11 stable is released
