### ISSUE TITLE
Hooks unavailable in 10.1.0

### ISSUE THREAD

**Issue by tslater** [facebook/relay#3259]
I know hooks are experimental, but I was able to use them with the standard production release 10.0.1 via `import {usePaginationFragment} from 'react-relay/hooks'`. I've upgraded to 10.1.0 and now hooks seem to be gone: `unable to resolve module`. 'hooks.js' is no longer in the package.

Were hooks only available by accident in the non-experimental 10.0.1 release?
Or is there a new way of importing them in 10.1.0?

**Comment by tslater** [comment]
Just to confirm my understanding: I need to install `react-relay@experimental`, they're no longer in the non-experimental release, is that right?

**Comment by piotrblasiak** [comment]
> Just to confirm my understanding: I need to install `react-relay@experimental`, they're no longer in the non-experimental release, is that right?

npm install relay-experimental

**Comment by josephsavona** [comment]
Correct, while they're experimental we have been releasing them as react-relay@experimental

**Comment by tslater** [comment]
Cool. It looks like there was just a single release where they showed up in
non-experimental for 10.0.1...so I started transitioning...oops.
