### ISSUE TITLE
relay-compiler: upgrade yargs to v16

### ISSUE THREAD

**Issue by dargmuesli** [facebook/relay#3264]
See https://snyk.io/test/npm/relay-compiler/10.1.0?utm_medium=referral&utm_source=yarn&utm_campaign=snyk-widget.

https://github.com/facebook/relay/blob/4b727bb0066110a8d01e1de0ba326ba7ca12fb7e/packages/relay-compiler/package.json#L33

**Comment by sibelius** [comment]
feel free to send a pull request

**Comment by dargmuesli** [comment]
Somehow the linked vulnerability vanished 🤔
