### ISSUE TITLE
How do I not duplicate fragments at root? 

### ISSUE THREAD

**Issue by simkessy** [facebook/relay#3273]
I have parent component that ends up with nested fragments looking like this: 

    query MyAppQuery(
        $id
        $a
        $b
        $c
    ) {
        viewer {
          ...App_viewer
          ...ComponentA_viewer @include(if: $a)
          ...ComponentB_viewer @include(if: $b)
          ...ComponentC_viewer @include(if: $c)
        }
        allEmployees: allUsers(userType: "1") {
            ...ComponentA_allEmployees @include(if: $a)
            ...ComponentB_allEmployees @include(if: $b)
            ...ComponentC_allEmployees @include(if: $c)
        }
    };

Relay fails if I don't include all this child fragments but the data is the same for all these, it seems pretty dumb having to declare a view fragment on all my child components that require the signed in user. 

How can I request this piece of data at the top of my application and have it available to child components without having to include the all these fragments. 

This is starting to feel like reverse prop drilling with I have to declare a fragment at the lower end of my app and pass it up the chain.

Same with allEmployees. It's the same data that I should only get once and pass down or access through context but I have to pass in all these stupid fragments or relay complains.

**Comment by sibelius** [comment]
you can have many QueryRenderer

**Comment by simkessy** [comment]
Does that mean I have to wrap component A | B | C in a query renderer just so I can get a varial I could request at the Root? 
I don't think that's any better.

**Comment by sibelius** [comment]
Why do you need all these different includes?

**Comment by simkessy** [comment]
This component is a Wrapper component so inside of it I render conditionally Component A, B or C. 
All those components make sure of viewer and allEmployees. 

For example: 

`export default createContainer(ComponentA, {viewer: ComponentA_view, etc })`

So inside <MyApp><Component(A|B|C) /></MyApp>

I use @include to determine which component to render and all those fragments require it so Relay doesn't complain about the missing fragment. 

But I find it pretty dumb I need to do this and wondering if there's a pattern im missing or a better way.

**Comment by captainkovalsky** [comment]
I faced with the same issue. We have got one pagination container which defines two fragment containers.

That containers actually define the same set of fields. Basically, it's a code duplication. I want to avoid it as it causes the problems. 

We added two fragments as we have the possibility to switch which component should be used for rendering items: Row or Card
