### ISSUE TITLE
[relay-test-utils] mock.resolve does not update component that uses experimental hook

### ISSUE THREAD

**Issue by ryym** [facebook/relay#3276]
Hi,
I am writing tests referring to the document <https://relay.dev/docs/en/testing-relay-components#examples>, but 
 the component tree does not be updated after calling `environment.mock.resolveMostRecentOperation` if the component uses `useLazyLoadQuery`.
Does not `relay-test-utils` support `react-relay@experimental` yet?

### Reproduction

1. Clone <https://github.com/ryym/relay-experimental-test-issue>
1. Run `yarn && yarn test`

### Code samples

```js
const App = ({ children, environment }) => {
  return (
    <RelayEnvironmentProvider environment={environment}>
      <Suspense fallback="loading">{children}</Suspense>;
    </RelayEnvironmentProvider>
  );
};
```

```js
const HookComponent = () => {
  const data = useLazyLoadQuery(
    graphql`
      query HookComponentQuery {
        name
      }
    `,
    {}
  );
  return <h1>Hello, {data.name}</h1>;
};
```

The following test fails, though it passes if the component uses `<QueryRenderer />` instead of `useLazyLoadQuery`:

```js
it("renders data", () => {
  const environment = createMockEnvironment();
  const renderer = TestRenderer.create(
    <App environment={environment}>
      <HookComponent />
    </App>
  );

  environment.mock.resolveMostRecentOperation((op) => {
    return MockPayloadGenerator.generate(op);
  });
  expect(renderer.root.findAllByType("h1").length).toEqual(1);
  //=>
  // Expected: 1
  // Received: 0
});
```

I also tried wrapping the `resolveMostRecentOperation` call by `TestRenderer.act`, but it did not solve the problem.

### Versions

- `react-relay` - `0.0.0-experimental-c818bac3`
- `relay-test-utils` - `10.1.0`

**Comment by sibelius** [comment]
Try mocking before rendering the component

**Comment by ryym** [comment]
Thank you, it works with `queueOperationResolver`!

```js
environment.mock.queueOperationResolver((op) => {
  return MockPayloadGenerator.generate(op);
});

const renderer = TestRenderer.create(
  <App environment={environment}>
    <HookComponent />
  </App>
);

// OK
expect(renderer.root.findAllByType('h1').length).toEqual(1);
```

Though it would be nice if `resolveMostRecentOperation` works as well, this solution is fine for me so I close the issue.
