### ISSUE TITLE
Does Caching work by default with hooks

### ISSUE THREAD

**Issue by simkessy** [facebook/relay#3281]
I'm confused about how caching works and if the relay store automatically handles caching when using hooks?

**Comment by alunyov** [comment]
With `relay-experimental,` we're trying to use data available in the Relay store. It depends on the configuration settings of your environment and fetch-policy.


More details about this here:
https://relay.dev/docs/en/a-guided-tour-of-relay#reusing-cached-data-for-render

**Comment by simkessy** [comment]
is useLazyLoadQuery available in relay 10.1.1

**Comment by alunyov** [comment]
>is useLazyLoadQuery available in relay 10.1.1?

Hooks are only available in the experimental package:
https://relay.dev/docs/en/a-guided-tour-of-relay#installation
