### ISSUE TITLE
When conditional fragments leave a field without subfields

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#330]
Consider this query fragment:

```js
Relay.createContainer(Story, {
  initialVariables: {
    showComments: false,
  },
  fragments: {
    story: (variables) => Relay.QL`
      fragment on Story {
        comments(first: 10) { ${Comments.getFragment('story').if(variables.showComments)} },
      }
    `,
  }
});
```

If `showComments` is false, the GraphQL server will throw an error that `comments` must have a sub selection.

We can prevent this by hoisting the inner fragment to the connection level:

```js
Relay.createContainer(Story, {
  initialVariables: {
    showComments: false,
  },
  fragments: {
    story: (variables) => Relay.QL`
      fragment on Story {
        ${Comments.getFragment('story').if(variables.showComments)},
      }
    `,
  }
});
```

…but perhaps there's something we should do to protect against leaving a field without sub selections and sending it up to the server.

Is the solution to deprecate `if()` and `unless()` in favor of a directive on the connection itself?

```js
Relay.createContainer(Story, {
  initialVariables: {
    showComments: false,
  },
  fragments: {
    story: () => Relay.QL`
      fragment on Story {
        comments(first: 10) @include(if: $showComments) {
          ${Comments.getFragment('comments')},
        },
      }
    `,
  }
});
```

**Comment by steveluscher** [comment]
cc/ @josephsavona

**Comment by josephsavona** [comment]
> Is the solution to deprecate if() and unless() in favor of a directive on the connection itself?

Yup, these directives (actually, *any* directives) are supported on master now.

**Comment by steveluscher** [comment]
So they are! Let's use those instead.

**Comment by alex-wilmer** [comment]
Is it possible to do this on a root query? If I have the following:

```
fragments: {
      viewer: () => Relay.QL`
        fragment on Root {
          files @include(if: $getFiles) {
            hits(first: $first, offset: $offset, filters: $filters, sort: $sort) {
              ${FileTable.getFragment('hits')}
            }
          }
        }
      `,
    },
```

I'm getting "Field "viewer" of type "Root" must have a sub selection."
