### ISSUE TITLE
Using fetchQuery to imperatively run a query with fragments returns empty fragments

### ISSUE THREAD

**Issue by hazzo** [facebook/relay#3317]
Hi i'm using `fetchQuery` function to fetch queries in an imperative manner. Works fine, but when I try to put a fragment this will will always empty inside the object `__fragment`.

This query runs okey on GrpahQL

```
  {
    fooSearch {
      edges {
        node {
          ...fooFragment
        }
      }
    }
  }
  
  fragment fooFragment on FooType {
    id
    name
  }
```

But using `fetchQuery` will return inside each node a `__fragment` object with the property `fooFragment` but this will be empty.

**Comment by sibelius** [comment]
this is because Relay has data masking

you can only see what you asked for

only `fooFragment` can see what is inside the fragment

you can use `@relay(mask: false)` to disable masking
or you can use `@inline` to consume masked data using readInline

**Comment by hazzo** [comment]
@sibelius thanks! @relay(mask: false) working great
