### ISSUE TITLE
Introduce the concept of optional and required fragments

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#333]
Currently Relay offers no warning for failing to compose a fragment all the way down to the root of your application. We have no sensible way of presenting such a warning, since all fragments are considered optional.

Let's consider introducing the notion of required/optional fragments, to both containers and to mutations.

Consider, in the latter case, a mutation that could make use of a fragment for the purposes of crafting an optimistic mutation, but otherwise doesn't absolutely need it to operate. This might look something like this:

``` js
class RemoveTodoMutation extends Relay.Mutation {
  static fragments = {
    todos: () =>  Relay.QL`
      fragment on TodosConnection @relay(optional: true) { totalCount }
    `,
    viewer: () => Relay.QL`
      fragment on Viewer @relay(required: true) { id }  # (required: true) is the default
    `,
  };
  /* ... */
  getOptimisticResponse() {
    var payload = {viewer: {id: this.props.viewer.id}};
    if (this.props.todos) {  // If we have it, great! If not, skip it.
      payload.viewer.todos = {
        totalCount: this.props.todos.totalCount - 1,
      };
    }
    return payload;
  }
}
```

Upon introduction, we can slowly migrate to making fragments required-by-default. That way, we'll be able to warn when a developer misses a composition step.

**Comment by BlooJeans** [comment]
Any update on the idea of optional fragments/fields for mutations?

**Comment by josephsavona** [comment]
This comes up periodically but hasn't been enough of a problem to warrant needing a fix. I'm going to close for now: if you have a strong use-case for this, feel free to reopen or file a new issue!
