### ISSUE TITLE
What's the query reference Flow type?

### ISSUE THREAD

**Issue by simkessy** [facebook/relay#3342]
```
// @flow
import { Suspense, useEffect, type Node } from 'react';
import { Box, Spinner } from 'gestalt';

import { graphql, useQueryLoader, usePreloadedQuery } from 'react-relay/hooks';
import Banner from './banner/Banner.react';
import Loader from '../components/common/Loader';
import type { LayoutContainerQuery } from './__generated__/LayoutContainerQuery.graphql';

const query = graphql`
  query LayoutContainerQuery {
    viewer {
      id
      email
      ...Banner_viewer
    }
  }
`;

type Props = {|
  children: Node,
|};

const LayoutContainer = ({ children }: Props): Node => {
  const [queryReference, loadQuery] = useQueryLoader(query);

  useEffect(() => {
    loadQuery({});
  }, [loadQuery]);

  if (queryReference === null) {
    return <Spinner show={true} accessibilityLabel="Spinner" />;
  }

  return (
    <Suspense fallback={<Loader show={true} />}>
      <Container queryReference={queryReference}>{children}</Container>
    </Suspense>
  );
};

type ContainerProps = {|
  queryReference: ???, //// I DON'T GET AN ERROR WHEN I USE OBJECT, BUT I WANT TO USE THE CORRECT TYPE
  children: Node,
|};

const Container = ({ queryReference, children }: ContainerProps): Node => {
  const data = usePreloadedQuery<LayoutContainerQuery>(query, queryReference);

  return (
    <Box height="100vh" color="white" display="flex" direction="column">
      <Suspense fallback={<Loader show={true} />}>
        <Banner viewer={data.viewer} />
      </Suspense>
      <Suspense fallback={<Loader show={true} />}>{children}</Suspense>
    </Box>
  );
};

export default LayoutContainer;


```

**Comment by sibelius** [comment]
it is the return of a loadQuery call https://github.com/sibelius/relay-workshop/blob/master/packages/web/src/routes.tsx#L60

you need to use loadQuery + usePreloadedQuery

**Comment by simkessy** [comment]
@sibelius I am using useLoadQuery which returns `queryReference` and `loadQuery`. When I pass the `queryReference` to the child component, it requires that I set a type: 

```
type ContainerProps = {|
  queryReference: ???, //// I DON'T GET AN ERROR WHEN I USE OBJECT, BUT I WANT TO USE THE CORRECT TYPE
  children: Node,
|};
```

Where do I import this type from or what type should I be using? 

When I don't provide a type to the `Container` component, I get this error: 

![image](https://user-images.githubusercontent.com/5871660/106703054-86b90a80-658d-11eb-8c7f-61608b79196f.png)

**Comment by sibelius** [comment]
you can read the relay codebase to figure it out

**Comment by simkessy** [comment]
Great library and docs, completely useless.

**Comment by josephsavona** [comment]
The full type signature for `usePreloadedQuery()` is:

```javascript
function usePreloadedQuery<TQuery: OperationType>(
  gqlQuery: GraphQLTaggedNode,
  preloadedQuery: PreloadedQuery<TQuery>,
  options?: {|
    UNSTABLE_renderPolicy?: RenderPolicy,
  |},
): $ElementType<TQuery, 'response'> 
```
[source](https://github.com/facebook/relay/blob/master/packages/relay-experimental/usePreloadedQuery.js#L35-L41)

This type _should_ be exported from `react-relay` (experimental version).

**Comment by simkessy** [comment]
@josephsavona are you saying I should type the queryReference as `PreloadedQuery<TQuery>` I tried this and it says it can't find a reference to those types: 

![image](https://user-images.githubusercontent.com/5871660/106938004-83736b00-66c2-11eb-95f9-b7a6a43fff31.png)


What is the type that `queryReference` need to be? 

![image](https://user-images.githubusercontent.com/5871660/106938324-ec5ae300-66c2-11eb-9458-e906bbe395da.png)

**Comment by josephsavona** [comment]
You'll need to `import type {PreloadedQuery} from 'relay-runtime'`, and then the type would be `PreloadedQuery<YourQueryType>`

**Comment by simkessy** [comment]
That type doesn't exist in the `relay-runtime` package 

![Uploading image.png…]()

**Comment by jstejada** [comment]
@simkessy, I think that type wasn't exported in the experimental build, but in v11.0.0-rc.0 you should be able to import that type from `react-relay`

**Comment by simkessy** [comment]
should the docs be updated to include this?

**Comment by jstejada** [comment]
yes, they will be with the release of v11
