### ISSUE TITLE
React-relay@experimental returning empty folder

### ISSUE THREAD

**Issue by simkessy** [facebook/relay#3347]
trying to download the latest version of react-relay@experiemental but im just getting an empty folder 

![image](https://user-images.githubusercontent.com/5871660/106997724-76d52e00-6727-11eb-967d-33a163ee013b.png)

**Comment by poteto** [comment]
I suggest checking your lockfile to confirm that the right version was installed. You could also try removing and adding it again. 

The latest experimental version was [published correctly](https://unpkg.com/browse/react-relay@0.0.0-experimental-4c4107dd/), so it seems like something in the install process must have broken.
