### ISSUE TITLE
[relay-compiler] eager es module mode does produce require calls

### ISSUE THREAD

**Issue by n1ru4l** [facebook/relay#3354]
Despite using the `eagerESModules` option for the `relay-compiler` the generated code requires `require` calls.

The following function is responsible for this: https://github.com/facebook/relay/blob/ba9a3f031f8adc0f60bef603a76385433518cd90/packages/relay-compiler/codegen/createPrintRequireModuleDependency.js

I was able to create a workaround for this within the formatter function inside `relay-compiler-language-typescript` over here: https://github.com/relay-tools/relay-compiler-language-typescript/pull/269

My specific question is whether this can or should be addressed withing `relay-compiler` or whether it is better of being inside the language package?

**Comment by sibelius** [comment]
I think this belongs to relay-compiler

https://github.com/relay-tools/relay-compiler-language-typescript/pull/269 feels a bit hacky

**Comment by n1ru4l** [comment]
It is indeed hacky, the real question is, whether this would be easy to solve within relay-compiler or whether it would require a lot of changes. Also afaik there is a new rust relay-compiler version coming...

**Comment by n1ru4l** [comment]
Note: The relay-compiler flow formatter implementation for es modules does the exact same: https://github.com/facebook/relay/pull/2841/files#diff-8258e3677c0534bd73d878b16093be514b2227f8972766d881bf903ff5f0e0d9R15-R27

**Comment by TrySound** [comment]
When this "require" is added? I have non "requires" in my `__generated__` modules.

**Comment by n1ru4l** [comment]
When using the `@refetchable` directive on a fragment

**Comment by asterikx** [comment]
This bug still exists in `relay-compiler@11.0.2`. Are there any plans on fixing it in the near future? It prevents me from using Relay in a Vite project. Thanks

**Comment by samwightt** [comment]
[See here for an example of how to fix this issue with Snowpack](https://github.com/samwightt/pine/blob/main/app/relay.snowpack.js). 

Necessary packages:

- `babel-plugin-relay`
- `babel-plugin-transform-commonjs`
- `@babel/core`

Just copy and paste the file into your Snowpack project and import it in your Snowpack config (see the repo for an example).

Explanation of what's going on in the plugin:

It's running two passes of Babel. The first pass runs `babel-plugin-relay` (with esm turned off), which outputs the CommonJS `require` statements, and `babel-plugin-transform-commonjs`, which transforms those imports to esm imports. The second pass cleans up the output: it removes the extra import that `babel-plugin-transform-commonjs` adds, and it imports the correct `graphql.js` file. This should make Relay work.

Implementing this in Vite should be fairly trivial, but I strongly suspect that it does things a little wonkier, which would require some tweaks. The necessary changes should be fairly trivial though, just copy and paste the `transformAsync` files and you're good.

**Comment by samwightt** [comment]
Regardless, this really should be fixed. It's incredibly annoying that the core transformer needed to run Relay doesn't support the standard JS module format.

**Comment by madebyherzblut** [comment]
An alternative solution may also be [babel-plugin-module-rewrite](https://github.com/liady/babel-plugin-module-rewrite#readme):

```javascript
// Babel config
{
  presets: ["@babel/preset-typescript", "@babel/preset-react"],
  plugins: [
    "babel-plugin-relay",
    ["module-rewrite", { replaceFunc: "./build/fixGraphQLImports.js" }],
  ],
}

// ./build/fixGraphQLImports.js
module.exports = function replaceImport(originalPath, callingFileName) {
  if (callingFileName.endsWith(".graphql.ts")) {
    return originalPath.replace(".graphql.ts", ".graphql");
  }
  return originalPath;
};
```

**Comment by n1ru4l** [comment]
@samwightt That is to be expected as relay is not open-source first but facebook first. AFAIK they do not use es modules but their own custom format based on require.

**Comment by XiNiHa** [comment]
I just built and tested with https://github.com/facebook/relay/commit/8ac91d7e9783af11e0f6aef545d3cb5e206d3372 and that fixed the issue in my case (realized that commit got published right before sending my own PR for this 🤣)

**Comment by cedrickring** [comment]
I tested with `eagerEsModules` and the v13 compiler and it produces correct es module imports instead of `require` calls. I guess this is fixed now. 👍🏼

**Comment by n1ru4l** [comment]
haven't used the v13 compiler yet - but gonna close this as I trust you 😇
