### ISSUE TITLE
Add option to only print errors but nothing else (i.e. `--quietExceptErrors`)

### ISSUE THREAD

**Issue by LukasKalbertodt** [facebook/relay#3362]
When executing `relay-compiler` (and there are no errors), it writes something like this to stdout:

```

Writing ts
Unchanged: 4 files
```

In some situations, I want to avoid this output as it adds noise to a build script output. There is of course the `--quiet` flag, but it also leads to `relay-compiler` not printing errors! I would like to have a way to have `relay-compiler` print errors (if any occur) but nothing else. 

On a related note, shouldn't errors printed to stderr instead of stdout?

**Comment by LukasKalbertodt** [comment]
Still a problem.

**Comment by alunyov** [comment]
This option was added in https://github.com/facebook/relay/pull/3763. Thanks @ch1ffa!
