### ISSUE TITLE
resetting a pagination to refetch on default variables on pull to refresh throw cursor warning?

### ISSUE THREAD

**Issue by gpbaculio** [facebook/relay#3363]
i have this props on my flatlist:
```
 onRefresh={() => {
          setIsRefreshing(true);
          refetch(
            { categoriesCount: 4, categoriesCursor: '' },
            {
              fetchPolicy: 'network-only',
              onComplete: () => {
                setIsRefreshing(false);
              },
            }
          );
        }}
```
this is how i initialize pagination:
```
const { data, loadNext, isLoadingNext, hasNext, refetch } = usePaginationFragment<
    CategoriesPaginationQuery,
    Categories_viewer$key
  >(
    graphql`
      fragment Categories_viewer on Viewer
      @argumentDefinitions(
        categoriesCount: { type: "Int", defaultValue: 4 }
        categoriesCursor: { type: "String", defaultValue: "" }
      )
      @refetchable(queryName: "CategoriesPaginationQuery") {
        categories(first: $categoriesCount, after: $categoriesCursor)
          @connection(key: "Categories_viewer_categories", filters: []) {
          pageInfo {
            startCursor
            endCursor
            hasNextPage
            hasPreviousPage
          }
          edges {
            cursor
            node {
              id
              pk
              name
            }
          }
        }
      }
    `,
    viewer
  );
```

this is the warning:

> ` Warning: Relay: Unexpected after cursor ``, edges must be fetched from the end of the list (`YXJyYXljb25uZWN0aW9uOjc=`).`

what i want to do is make the pagination "forget it's current edges" and go back like the beginning on pull to refresh?

**Comment by gpbaculio** [comment]
ended up using fetchQuery, making parent of useRefetchableFragment and usePaginationFragment throws warning atm.

**Comment by jstejada** [comment]
@gpbaculio other than the warning, are things working as expected?

It seems like the problem is that your server is not returning a cursor, so Relay is producing that warning, but otherwise the initial code you published should work as expected, and I don't think this is unexpected behavior in Relay.

your initial example looks correct, except that you shouldn't need to use the isRefetching state, since refetch will suspend. if you want to avoid suspending, you can use fetchQuery (i will add additional docs for that)

**Comment by gpbaculio** [comment]
@jstejada it's actually working but i was thinking if i can do that without the warning throwing?

**Comment by lprhodes** [comment]
@gpbaculio did you find that calling a `refetch` on the default vars would cause the "after" cursor to reset? The result being that "loadMore" ends up loading the wrong data?
