### ISSUE TITLE
ErrorBoundaryWithRetry example doesn't work in an appropriate way

### ISSUE THREAD

**Issue by serche** [facebook/relay#3369]
In case of using useLazyLoadQuery Relay Experimental caches network error for about 5 minutes. So, retry handler in ErrorBoundaryWithRetry has no chance to initiate next network request till the error is cached.

Expected behavior: 
Retry initiates network request immediately.

**Comment by jstejada** [comment]
Hey @serche, thanks for bringing this up. This should be fixed in the latest RC release. let me know if you still are still encountering this issue even in the RC

**Comment by serche** [comment]
Unfortunately not. The problem is still there. I understand that you have to cache an error, but why it's so long - 5min?

**Comment by jstejada** [comment]
hey @serche, this sounds like a bug, we'll look into it

**Comment by jstejada** [comment]
hey @serche, the example was incorrect, I updated it here: https://github.com/facebook/relay/commit/b43b8b95f0cf6ec21e24e945d4c56d971cd55fd9

and will be published when v11 comes out
