### ISSUE TITLE
Add skip option to useLazyLoadQuery

### ISSUE THREAD

**Issue by piotrblasiak** [facebook/relay#3370]
Because of the way hooks work, using hooks conditionally is not an option and will throw an error. So the relay hooks need to give you an option to skip the query. I suggest adding a skip boolean option to useLazyLoadQuery, useSubscription and any others that might need it.

**Comment by jstejada** [comment]
hey @piotrblasiak, thanks for the suggestion. could you elaborate a bit more under which circumstances you need to skip the query?

This also applies to hooks in general, but i think the recommended way of doing this is wrapping the hook in a component, and then conditionally rendering that component

**Comment by piotrblasiak** [comment]
One example could be where I have to load some data only for the users that have some specific permissions that are only known after the first query has loaded. Like:

1) Fetch current user roles
2) If user is admin, fetch unpaid invoices
3) If unpaid invoices, redirect to...

Currently this can be done with a useEffect and fetchQuery, but it would be great if you could use just 2 useLazyQuery, and even better if this could be done to work with Suspense in such a way that there would only be 1 fallback loading screen until the 1 or 2 queries finished.

The relay-tools lib had this discussion and implemented the skip option not long ago:

https://github.com/relay-tools/relay-hooks/issues/57

**Comment by jstejada** [comment]
@piotrblasiak is using different components for each useLazyLoadQuery not an option here? that way it would also work with Suspense as you expect

**Comment by piotrblasiak** [comment]
Maybe you can, but adds some complexity. I eventually solved it with the @skip annotation for relay, which is another workaround. I guess we may need some more input on this :)

**Comment by jstejada** [comment]
I'm going to close this for now as it is unlikely that we will add a skip option to useLazyLoadQuery, but feel free to continue the conversation here

**Comment by tony** [comment]
@jstejada Due to these being hooks - we need the ability to make the whole query itself conditional

1. It avoids the expense of a whole graphql - `@skip` is field level, but [relay hook's](https://github.com/relay-tools/relay-hooks#relay-hooks-1) skip saves us an unneeded query.
2. It works with relay hooks + typescript

**Comment by squidsoup** [comment]
I'd just like to second this, there are definitely scenarios where `skip` would be useful, e.g. a view where the query only makes sense with user provided values/filters, and input from the user is first required.
