### ISSUE TITLE
Not possible to wait for subscription to subscribe

### ISSUE THREAD

**Issue by aleksandrlat** [facebook/relay#3377]
It is not possible to wait for subscription to subscribe and be notified about it.

**Example 1**
For example we want to implement async mutations. We send mutation request but response comes via websocket/subscription.
Response can come immediately or with some delay (this depends on many circumstances).

We want to make sure we are subscribed before making mutation request.

**Example 2**
Or we want to make query only after we are sure we subscribed so we don't miss any updates to the query.

**Comment by josephsavona** [comment]
I'm going to close this is more of a "how to" question than a bug or feature request, but please feel free to ask follow-up questions.

**Comment by aleksandrlat** [comment]
Thank you @josephsavona!

> each application would still have to implement some logic to tell Relay when a subscription was established

Yes sure.

> for example your network layer could automatically delay any mutations while there are pending subscriptions

While this is an option it is no ideal. We don't want to wait for any subscriptions. Only for particular one.

> We send mutation request but response comes via websocket/subscription.

Sorry for confusion about it. I meant we send mutation request and server returns response (like request is accepted and server started to process it). But we don't use mutation response. 
Server processes request and sends real response with data to subscription.

The problem is with Observable which does not have something like "connected" event
What do you think about special "next" event for this? 
For example when server confirms subscription we do 
```
// { connected: true } is only for example
sink.next({ connected: true })
```
Instead of normal subscription data defined in graphql

Can relay handle this or not?

**Comment by josephsavona** [comment]
> The problem is with Observable which does not have something like "connected" event

You'd have to find a way to return the `connected: true` data as a valid GraphQL response. There's a loophole in the spec where you can have a response that is basically `extensions` only (no `data` or `errors`), which might work for this.

**Comment by aleksandrlat** [comment]
Oh interesting @josephsavona! Thank you very much! 
I will investigate this more.

**Comment by livwvil** [comment]
> Oh interesting @josephsavona! Thank you very much! I will investigate this more.

Hello! Have you found a good way to do this?
