### ISSUE TITLE
the generated refetch query does NOT bring the directives on query.

### ISSUE THREAD

**Issue by bonafideyan** [facebook/relay#3378]
when a fragment has a directive @refetchable, compiler will generate a refetch query.

when refetch, I expect it is like the initial query, which has a directive defined on server side.

but it does NOT, the generated persist query has no the directive, and I read some code in compiler, 

RefechableFragmentTransform.js

the expected behavior is not implemented. 

I try to add the implementation, now it works, but still not completed. if need, I can paste it.

my question is whether it will be implemented. (I thought it should be implemented, )

**Comment by sibelius** [comment]
Try to send a PR

**Comment by josephsavona** [comment]
> when refetch, I expect it is like the initial query, which has a directive defined on server side. but it does NOT, the generated persist query has no the directive

To clarify, are you saying that your fragment definition has some other directives, which aren't propagated on the refetch query?

**Comment by bonafideyan** [comment]
@josephsavona  

```
Writing ts
ERROR:
- Invalid directives @withUser found on FRAGMENT_DEFINITION.
  
  home/main.tsx:3:3
  2 | fragment mainLinksForMe on Query  
  3 |   @withUser(isVendorUser: $isVendorUser)
    |   ^
  4 |   @refetchable(queryName: "MainLinksForMeQuery") {
error Command failed with exit code 100.
```

**Comment by bonafideyan** [comment]
@sibelius 

https://github.com/facebook/relay/pull/3380

**Comment by josephsavona** [comment]
That error indicates that you have defined the `@withUser` directive as only being valid on queries. If you want to use one of your application-defined directives on a fragment, you have to define it in your schema as being allowed on fragment definitions too.

**Comment by bonafideyan** [comment]
> That error indicates that you have defined the `@withUser` directive as only being valid on queries. If you want to use one of your application-defined directives on a fragment, you have to define it in your schema as being allowed on fragment definitions too.

now I see, thank you.
and I have not met the problem you said that in case of different query reference the same refetch fragment. I will continue use the fix until it breaks.
