### ISSUE TITLE
createFragmentContainer migration gudelins

### ISSUE THREAD

**Issue by kushwahashiv** [facebook/relay#3413]
Where I can find migration guidelines? to latest relay version or any blog like will be helpful.

/Shiv

**Comment by sibelius** [comment]
![image](https://user-images.githubusercontent.com/2005841/111211670-72652600-85ad-11eb-93cc-612c96a60a25.png)

https://relay.dev/docs/migration-and-compatibility/relay-hooks-and-legacy-container-apis/
