### ISSUE TITLE
Rust compiler: definition of 'XYZQuery' appears to have changed

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/relay#3437]
Hello! 👋 I am trying the new Relay Rust compiler and I managed to convert all artifacts successfully. However, I am getting the following errors in runtime:

```text
The definition of 'XYZQuery' appears to have changed. Run `relay-compiler` to update the generated files to receive the expected data.
```

It works fine with the "old" compiler so I guess there is some kind of incompatibility. Is it a bug? Is there something I am missing? Thanks for having a look!

My config:

```json
{
  "root": "..",
  "sources": {
    "ya-comiste-backoffice/src": "default"
  },
  "codegenCommand": "yarn workspace @adeira/ya-comiste-backoffice relay",
  "projects": {
    "default": {
      "schema": "ya-comiste-rust/schema.graphql",
      "jsModuleFormat": "commonjs",
      "haste": false,
      "customScalarTypes": {
        "ProductImageUploadable": "String"
      }
    }
  },
  "isDevVariableName": "__DEV__"
}
```

Executing like this: `relay-compiler-experimental ./relay.config.json`

You can see all the changes in this PR: https://github.com/adeira/universe/pull/2116

**Comment by kassens** [comment]
What happens is:
- the compiler produces a hash at compile time
- the babel plugin (when a DEV variable is set) produces a bit of code instead of just a require() statement that also contains a hash.

The hash used to be `md5(graphql.print(graphql.parse(text)))` and in the Rust compiler we just updated it to `md5(text)` to avoid needing 100% replication of graphql-js printing.

I thought we also made that change to the OSS babel plugin, but I guess we never migrated OSS? I need to double check this when I'm back at my work computer.

**Comment by mrtnzlml** [comment]
> I thought we also made that change to the OSS babel plugin, but I guess we never migrated OSS? I need to double check this when I'm back at my work computer.

Thanks for having a look @kassens, much appreciated!

**Comment by kassens** [comment]
Moving comments from the wrong thread: https://github.com/facebook/relay/issues/3438#issuecomment-829726323

# from @kassens 

@mrtnzlml : Actually, I was wrong:
Rust also does `md5(print(definition))` here:

https://github.com/facebook/relay/blob/b87e6b12aa42b76da5e0a88eafd1fd58d2e587b2/compiler/crates/relay-compiler/src/build_project/build_ir.rs#L33

which should match this code

https://github.com/facebook/relay/blob/b87e6b12aa42b76da5e0a88eafd1fd58d2e587b2/packages/babel-plugin-relay/compileGraphQLTag.js#L117-L120

Maybe you have an example fragment where the output is different? Is it `console.error`ing for all definitions or a few exceptions? I could see that happen when you have escaped characters in strings or something uncommon maybe? That would be a bug internally as well though.

# from @mrtnzlml 

Hi @kassens! First and foremost, I verified whether this issue still exists in the latest version, and seems like yes. You can see the migration from "old" Relay Compiler to the "new" Relay Rust Compiler in this PR: https://github.com/adeira/universe/pull/2119

Here are all the files I saw that changed their hash from the previous version:

```text
src/abacus-backoffice/src/products/__generated__/CreateProductFormMutation.graphql.js
src/abacus-backoffice/src/products/__generated__/EditProductFormMutation.graphql.js
src/abacus-backoffice/src/products/__generated__/ProductsCardsQuery.graphql.js
src/abacus-backoffice/src/products/__generated__/ProductsEditLayoutQuery.graphql.js
src/kochka.com.mx/src/shop/__generated__/ProductPageLayoutQuery.graphql.js
src/kochka.com.mx/src/shop/__generated__/ShopLayoutContentQuery.graphql.js
```

I am having a hard time figuring out what could be the problem though. For example, check [`src/abacus-backoffice/src/products/__generated__/ProductsCardsQuery.graphql.js`](https://github.com/adeira/universe/pull/2119/files#diff-5aac79b620d83ed4ca9bbb7427602048cc6c40b17e67b32c23288d37893c64db) which results from the following query:

```graphql
query ProductsCardsQuery {
  commerce {
    products: searchAllProducts(clientLocale: en_US, priceSortDirection: LOW_TO_HIGH) {
      id
      key
      name
      imageCover {
        blurhash
        url
      }
      price {
        unitAmount
        unitAmountCurrency
      }
    }
  }
}
```

Doesn't look suspicious. 🤔 Do you have any idea what could it be?

>  Is it console.erroring for all definitions or a few exceptions?

A few exceptions listed above in the whole PR (https://github.com/adeira/universe/pull/2119).

Thanks for having a look!

**Comment by alunyov** [comment]
Added a PR for this: https://github.com/facebook/relay/pull/3628
