### ISSUE TITLE
Can not use appendNode on field with agruments

### ISSUE THREAD

**Issue by giautm** [facebook/relay#3457]
How do this variant?
```
mutation CommentCreateMutation(
  $connections: [String!]!
  $input: CommentCreateInput
) {
  commentCreate(input: $input) @appendNode(
      connections: $connections
      edgeTypeName: "CommentEdge"
    ) {
      id
      ...Comment_comment
    }
  }
}
```
index.js:1 Warning: MutationHandlers: Expected target node to exist.

__Originally posted by @anatooly in https://github.com/facebook/relay/pull/3155#issuecomment-817754946__

**Comment by anatooly** [comment]
On example, mutaiton commentCreate return node type Comment (all fields on top level)

I use wrapper type for correct work like official docs commentCreate -> CommentResponsePayload -> Comment

commentCreate(input: $input) {
    comment @appendNode(
      connections: $connections
      edgeTypeName: "CommentEdge"
    ) {
      id
      ...Comment_comment
    }
  }
  
  this work correct.

**Comment by giautm** [comment]
Yep, but if createComment return a Node/Edge you will not able to use directive on that field.

**Comment by georgekaran** [comment]
I was facing the same issue as @anatooly, and my solution was also very similar. I've added a "self" that returns in my case the created organization.

```graphql
createOrganization(payload: {
    email: $email
    type: $type
    slug: $slug
    name: $name
    logo: $logo
    website: $website
}) {
    self @appendNode(
        connections: ["client:root:__organizationList_organizations_connection"],
        edgeTypeName: "organizationEdge"
    ) {
        id
        name
        logo
        slug
        memberCount (status: ACTIVE)
    }
}
```

But I'm not sure if we should be doing this or there's a bug in the `appendNode` directive.

**Comment by advanderveer** [comment]
I've also rand into this issue, it seems common that mutations return a node AND that mutations take an argument so.

**Comment by axhl** [comment]
Bumping issue. Agreed this seems like a common use case. Should we consider this a bug? 

> I've also rand into this issue, it seems common that mutations return a node AND that mutations take an argument so.

**Comment by yonidavidson** [comment]
Isn't it designed like this? 
wrap the node with a "payload" in the example at #3155 it looks like it.

```yaml
createSomething(
    input: CreateSomethingInput
  ): SomethingPayload!

type SomethingPayload {
  something: Something!
}
```

**Comment by giautm** [comment]
the example isn't a specification. If the relay team want to support only that, please update the specification.

**Comment by yonidavidson** [comment]
Hi, was this fixed or documented in the new relay version?

**Comment by theseyi** [comment]
Seem like the use case in this issue should be supported. There are a lot of implementation where a mutation directly returns the object that was mutated or created without nesting under a top level field. Having to implement a workaround by introducing a field just for the purpose of decorating it with a directive should not be the defacto solution here

**Comment by tyao1** [comment]
This should be fixed in https://github.com/facebook/relay/commit/cd1e9ae06d114c3e353d384ccbe956e6800a8679
Feel free to reopen if this still occurs.

**Comment by johnsonjo4531** [comment]
Hey @tyao1, still isn't working for me, by chance it's because I'm using `@appendNode` instead of `@appendEdge`. I notice that appendEdge is in the test cases you wrote for https://github.com/facebook/relay/commit/cd1e9ae06d114c3e353d384ccbe956e6800a8679 but not appendNode maybe it could be added to the test case and then debugged from there... thanks!
