### ISSUE TITLE
How use Query cache or why ConfigCache force true?

### ISSUE THREAD

**Issue by anatooly** [facebook/relay#3462]
Hello all.

1) I use react-relay-network-modern (last v.6 and relay v.11)
2) My network queries newer cached, because cacheMiddleware see
`if (req.cacheConfig && req.cacheConfig.force) {`
it's https://github.com/relay-tools/react-relay-network-modern/blob/master/src/middlewares/cache.js
but CacheConfig hardcode always `force: true` and query cache always disable by default
https://relay.dev/docs/api-reference/types/CacheConfig/

Example:
useLazyLoadQuery
```
    options && options.networkCacheConfig
      ? options.networkCacheConfig
      : {force: true},
 ``` 
 and all other method fetchQuery, etc
 ```
  const networkCacheConfig = {
    force: true,
    ...options?.networkCacheConfig,
  };
 ```

How correct cook Relay cache response data?
---

When we mount/unmount React component query send again, am I right?
```
export const User = () => {
  const { viewer } = useLazyLoadQuery(graphql`
  query UserQuery {
    viewer {
      user {
        name
      }
    }
  }
`)
  return <>{viewer.user.name}</>
}
```
```
const Test = () => {
  const [show, setShow] = useState(true)
  return (
    <>
      {show && <User />}
      <button onClick={() => setShow(s => !s)} />
    </>
  )
}
```
Work code for cache network response for me now:
```
  const data = useLazyLoadQuery(query, variables, {
    networkCacheConfig: { force: false },
  })
  ```
all variant of fetchPolicy not help. Thx.

---
Updated: I find my problem.

fetchPolicy: 'store-or-network' work correct for query, but in my package.json
```
    "relay-runtime": "^10.1.2",
    "react-relay": "latest",
```   
in result compile main.js

react-relay:
var DEFAULT_RELEASE_BUFFER_SIZE = 10;

react-runtime
var DEFAULT_RELEASE_BUFFER_SIZE = 0;

reset default garbage collector logic, if gcReleaseBufferSize equal 0 cached is disabled.

P.S.S.: this fix commit 26.02.2021

or help this of doc https://relay.dev/docs/guided-tour/reusing-cached-data/presence-of-data/
`const store = new Store(source, {gcReleaseBufferSize: 10});`

Other problem of react-relay-network-modern when it return cached response Relay not have consistend data.
Relay local updater not correct work together with cacheMiddleware.
---

_Relay query -> (cache data | one cache layer) -> cacheMiddelware (cache response | other cache layer) -> GC_

**Comment by conradobarbera** [comment]
Could you fix it?

**Comment by anatooly** [comment]
> Could you fix it?

For last relay version 12 it's not actual, all work correct, like into documentation.
