### ISSUE TITLE
renderFailure error is actually a fetch response object

### ISSUE THREAD

**Issue by emmenko** [facebook/relay#347]
I was looking into the `renderFailure` callback and it actually returns a `Response` object from the `fetch` library. The documentation says it returns an object and you can access the message like `error.message`.

<img width="660" alt="screen shot 2015-09-19 at 00 39 21" src="https://cloud.githubusercontent.com/assets/1110551/9972667/2d16935e-5e67-11e5-8794-7c4124e89d4d.png">

Which one is correct? How should I render the error with the fetch response object?
If I resolve the response and then return the render component I get an error.

```js
<Relay.RootContainer
  Component={Home}
  route={homeQueries}
  renderFailure={(error, retry) => {
    error.json().then(result => {
      return (
        <div>
          <p>{result.errors}</p>
          <p><button onClick={retry}>Retry?</button></p>
        </div>
      )
    })
  }}
/>
```

<img width="713" alt="screen shot 2015-09-19 at 00 48 49" src="https://cloud.githubusercontent.com/assets/1110551/9972734/3c23a6d8-5e68-11e5-9ece-32c8ac7c6d8d.png">

**Comment by steveluscher** [comment]
You're right! When `fetchWithRetries` errors out, it rejects the promise with an `Error`. When it simply gets tired of retrying, though, it rejects the promise with a `Response` object. It should really be an `Error` object that says “I gave up.”

Do you mind hopping over to `facebook/fbjs` and filing a bug [for this line](https://github.com/facebook/fbjs/blob/master/src/fetch/fetchWithRetries.js#L89) (or send us a PR!).

**Comment by emmenko** [comment]
Will do, thanks!

PS: the error should also contain the parsed response body right? For example the validation response from a malformed graphql query.
