### ISSUE TITLE
help page doesn't exist

### ISSUE THREAD

**Issue by ZohebMOPO** [facebook/relay#3510]
Hey There,
I need some help on how to understand this large codebase of the relay project. As written in [contribution markdwon](https://github.com/facebook/relay/blob/master/.github/CONTRIBUTING.md) to head over to [Help](https://relay.dev/en/help.html) but this page doesn't exist. So how can I ask for help?

Hope to hear from you soon

**Comment by lucasweng** [comment]
Hi @ZohebMOPO,

The help page has been moved to https://relay.dev/help

**Comment by ZohebMOPO** [comment]
Hmm Ok Thanks.
