### ISSUE TITLE
Returning Null on missingFieldHandlers skips network request

### ISSUE THREAD

**Issue by PedroBern** [facebook/relay#3526]
### Problem

When following the [docs example](https://relay.dev/docs/guided-tour/reusing-cached-data/filling-in-missing-data/) and making a request with `store-or-network`, the network request never happens, even when returning `null`.

```js
const {ROOT_TYPE, Environment} = require('relay-runtime');

const missingFieldHandlers = [
  {
    handle(field, record, argValues): ?string {
      if (
        record != null &&
        record.__typename === ROOT_TYPE &&
        field.name === 'user' &&
        argValues.hasOwnProperty('id')
      ) {
        // If field is user(id: $id), look up the record by the value of $id
        return argValues.id;
      }
      if (
        record != null &&
        record.__typename === ROOT_TYPE &&
        field.name === 'story' &&
        argValues.hasOwnProperty('story_id')
      ) {
        // If field is story(story_id: $story_id), look up the record by the
        // value of $story_id.
        return argValues.story_id;
      }
      return null;
    },
    kind: 'linked',
  },
];

const environment = new Environment({/*...*/, missingFieldHandlers});
```

### Solution

When returning `undefined`, it works as expected (making the network request).

I propose updating the docs to:

```diff
--- return null
+++ return undefined
```

Or alternatively, write a section explaining this behavior. 

If maintainers agree, I'd be happy to send a PR!

**Comment by sibelius** [comment]
You should return undefined for missing data

**Comment by PedroBern** [comment]
@sibelius thanks for the response. Yes, this is exactly what I expected! But the docs do not mention it. What's the case when we would like to return `null`?

**Comment by sibelius** [comment]
When you expect the field to be null
