### ISSUE TITLE
rendering fragments server side 

### ISSUE THREAD

**Issue by hibaAkroush** [facebook/relay#3536]
hello 

Im adding relay to my project which uses React.createElement to render components on server side 
I have a parent component` <usersView>` and three child components `<userCard>`
parent components render without any problem but I discovered that for child components the data is masked on server side therefore 
props here is an empty object

```
  let element: RenderingResult = React.createElement(
    component,
    props
  );
```

when the page hydrates and the props are passed to the component the masked data is available 

```
    const userData = useFragment<userCard$key>(
      userCardQuery,
      props.componentData as userCard$key
    );

```

is there a way to do this on server side?

**Comment by sibelius** [comment]
what is the error?

**Comment by hibaAkroush** [comment]
I figured it out it was totally my fault 

my codebase is a but complicated and with relay being opinionated it was tough to figure out why it did not work 
i fixed it by passing the object containing the masked fragment data under props.data exactly 

thanks I will close the issue
