### ISSUE TITLE
How to get data without render another component

### ISSUE THREAD

**Issue by BiancaArtola** [facebook/relay#3554]
I am using Relay with React and Graphql. I am using the last version of all the libraries.

I have a react component and I need to load data on a button onClick, but I don't need to show that data, so having another component with the hook `usePreloadedQuery` is not a solution for me. 
I am following this example: https://relay.dev/docs/api-reference/use-preloaded-query/ but the NameDisplay component, as I said before, is not useful for me.
Can you please give me some information about this? I will provide a piece of code to help you to understand my question. Thanks!

```
const Events: React.FC = () => {
  const [queryReference, loadQuery, disposeQuery] = useQueryLoader(
    ProductTypeBySerialNumberQuery
  );

  const onClick = () => {
    loadQuery({
      serialNumber: 1234,
    });

    // I NEED TO GET THE DATA HERE
  };

  return (
        <Grid item xs={4}>
              <Button  onClick={onClick}>
                Search Events
              </Button>            
         </Grid>
  );
};
```

**Comment by sibelius** [comment]
useFragment?

**Comment by BiancaArtola** [comment]
Thanks @sibelius, I think that it can help. But I have another question, how can I send params to useFragment? 
`    const data = useFragment(ProductTypeBySerialNumberQuery, ????);
`

**Comment by sibelius** [comment]
https://relay.dev/docs/api-reference/graphql-and-directives/#argumentdefinitions

**Comment by BiancaArtola** [comment]
Hmmm.. looks good. The only way to do this is using fragments?

**Comment by sibelius** [comment]
can you share more code and context?

**Comment by BiancaArtola** [comment]
Yes. For example, this is the query that I am using:

```
const graphql = require("babel-plugin-relay/macro");

const ProductTypeBySerialNumberQuery = graphql`
  query productTypeBySerialNumberQuery($serialNumber: Long!) {
    productTypeBySerialNumber(serialNumber: $serialNumber) 
  }
`;

export default ProductTypeBySerialNumberQuery;

```

**Comment by sibelius** [comment]
can you provide more context?

what do you wanna do?

**Comment by sibelius** [comment]
why do you need to do a query only after clicking the button?

you can use `fetchQuery` for imperative query fetching https://relay.dev/docs/api-reference/fetch-query/#internaldocs-banner

**Comment by BiancaArtola** [comment]
Because I am waiting for the input of the user. This is the code with `fetchQuery`:

```
const Events: React.FC = () => {
  const [searchValue, setSearchValue] = useState<string>();
  
  const onClick = () => {
    fetchQuery(RelayEnviroment, ProductTypeBySerialNumberQuery, {
      serialNumber: searchValue,
    }).subscribe({ next: (data) => console.log(data) });
  };
  

  return (
  <>
	  <PureInput
		onChange={(value) => setSearchValue(value)}
		value={searchValue}
		placeholder="Enter serial number"
		label="Serial Number"
	  />
	  <Button
		onClick={onClick}
	  >
		Search Events
	</Button>
  </>
  );
};
```

I don't know if it is the better option for my case, but it works, so I will no bother you anymore. I am really pleased with your help, you save me. Thanks

**Comment by sibelius** [comment]
useRefetchableFragment is the proper hook for this

https://relay.dev/docs/api-reference/use-refetchable-fragment/#userefetchablefragment

you should aim for a declarative data fetching approach

**Comment by BiancaArtola** [comment]
I will try with that,thanks

**Comment by BiancaArtola** [comment]
Ey @sibelius, I have a new question. I am using usePaginationFragment to load data into a table. 
I am creating my fragment but I don't know what I am doing wrong
![image](https://user-images.githubusercontent.com/21174759/128707053-bd01abd0-c8fe-4fb4-ac68-703b7a83821d.png)

Can you give me some help?

**Comment by sibelius** [comment]
your fragment should be in the parent field of the connection

example

```graphql
 fragment App_user on User {
    posts(first: 10) { } 
 }
```

**Comment by BiancaArtola** [comment]
Hmmm... This is the original query that works fine:
```
query {
  robotEventsBySerialNumber (
  serialNumber: 1234
  ) {
    nodes {
      event {
        details
      }
  }
}
}
```

So as I want to paginate my table I decided to use usePaginationFragment because I read that is the best option for pagination on Relay. So I tried to create a fragment and use it:

```
const RobotEventsBySerialNumberQuery = graphql
  query robotEventsBySerialNumberQuery {
    robotEventsBySerialNumber(serialNumber: 1234) {
      ...robotEventsBySerialNumberFragment
    }
  }
;
```

```
const RobotEventsBySerialNumberFragment = graphql
  fragment robotEventsBySerialNumberFragment on RobotEventConnection
  @refetchable(queryName: "robotEventsBySerialNumberFragmentPaginationQuery") {
      edges {
        node {
          event {
            details
          }
        }      
    }
  }
;
```

Is my logic okay? Or it's ridiculous to use a fragment only to use the hook usePaginationFragment?

**Comment by sibelius** [comment]
`usePaginationFragment` will also generate a Refetch Query (Pagination Query) to enable you to get more data

**Comment by BiancaArtola** [comment]
Sure! this is the reason why I am trying to use that, but my fragment does not work 😢

**Comment by sibelius** [comment]
which field is the parent of RobotEventConnection ?

the fragment should be in that field

**Comment by BiancaArtola** [comment]
The code you shared with me was REALLY helpful to me. Now it works. I have no words to thank you!

**Comment by sibelius** [comment]
can you share your final solution here, and close the issue?

**Comment by BiancaArtola** [comment]
Sure!

```
const RobotEventsBySerialNumberFragment = graphql`
  fragment robotEventsBySerialNumberFragment on Query
  @argumentDefinitions(
    serialNumber: { type: "Long!" }
    first: { type: Int, defaultValue: 10 }
    after: { type: String }
  )
  @refetchable(queryName: "robotEventsBySerialNumberFragmentPaginationQuery") {
    robotEventsBySerialNumber(
      serialNumber: $serialNumber
      first: $first
      after: $after
      order: $order
    ) @connection(key: "test_robotEventsBySerialNumber") {
      edges {
        node {
          event {
            details
        }
      }
    }
  }
`;
```

```
const RobotEventsBySerialNumberQuery = graphql`
  query robotEventsBySerialNumberQuery($serialNumber: Long!) {
    ...robotEventsBySerialNumberFragment @arguments(serialNumber: $serialNumber)
  }
`;
```

**Comment by sibelius** [comment]
to avoid naming confusing, try this instead

```graphql
fragment robotEventsBySerialNumberFragment_query on Query
```

```graphql
fragment App_<type> on Type
```

**Comment by BiancaArtola** [comment]
thanks!
