### ISSUE TITLE
Use two differents schemas

### ISSUE THREAD

**Issue by BiancaArtola** [facebook/relay#3562]
I'm using the last version of Relay on mi React application, and I need to consume data from two different APIs. Each API has a different schema.

Is there a way to set two differents schemas on Relay?

**Comment by sibelius** [comment]
you can call relay-compiler N times

but you can't share fragments from 2 different schemas

**Comment by BiancaArtola** [comment]
Thanks for the response. I called the `relay-compiler` two times but when I run the code I have some issues that I think are related to the fact that I have two schemas.
This is my query:
```
const CallDetailRecordsQuery = graphql`
  query callDetailRecordsQuery(
    $order: [CallDetailRecordsViewSortInput!]
    $where: CallDetailRecordsViewFilterInput
    $first: Int
  ) {
    ...callDetailRecordsFragment_query
      @arguments(
        order: $order
        where: $where
        first: $first
      )
  }
`;
export default CallDetailRecordsQuery;
```

My schema:

```
schema {
  query: Query
....
type Query {
  callDetailRecords(first: Int after: String last: Int before: String where: CallDetailRecordsViewFilterInput order: [CallDetailRecordsViewSortInput!]): CallDetailRecordsViewConnection
}
```

Then I used `useLazyLoadQuery`:
```
  const queryRef = useLazyLoadQuery(CallDetailRecordsQuery, {
    first: 10,
    order: tableOrder,
    where: tableFilter,
  });
```

But I am having this issue:

![image](https://user-images.githubusercontent.com/21174759/130099757-836ee79b-4cdc-4913-aa16-1610c5db09e9.png)

Do you think that this is related to the fact that I am having two different schemas? 
How can I fix that?

**Comment by sibelius** [comment]
are you mixing fragments from different schemas?

**Comment by BiancaArtola** [comment]
No, I have a fragment for one schema and another from the other schema.
Here is my structure:
![image](https://user-images.githubusercontent.com/21174759/130122417-0c60a43b-4b2d-4168-b9b9-02d5e2d78294.png)

**Comment by BiancaArtola** [comment]
I noticed that both schemas begin with:
![image](https://user-images.githubusercontent.com/21174759/130123348-0f68a68f-600a-4a2f-9b43-e367e9fa7989.png)
And both fragments are declared as `fragment name on Query`:
![image](https://user-images.githubusercontent.com/21174759/130123414-acdcde76-8580-4ccf-86a3-3df2aba13323.png)

Could this be causing the problem?

**Comment by sibelius** [comment]
how are you calling relay compiler?

I don't think fragments of different schemas could be in the same folder, as one relay compiler will override the __generated folder from another

**Comment by BiancaArtola** [comment]
```
 "relay": "relay-compiler --src ./src/app/graphql/queries/monitoring --schema ./schema.graphql --extensions=ts"
 "relay2": "relay-compiler --src ./src/app/graphql/queries/fms --schema ./schemaFms.graphql --extensions=ts"
```

The `__generated` folders _looks_  to be generated fine. It's a bit strange

**Comment by sibelius** [comment]
how are you handling this at network layer?

how do you know which graphql endpoint to call?

**Comment by daniloab** [comment]
do you have access to one of the backends? If yes, maybe can you do your request on the backend and expose it in one schema.


Like a gateway, you request the Backend B on backend A, expose the query of Backend A and keep working with only one schema on the frontend.

**Comment by BiancaArtola** [comment]
@sibelius This is the hook that I am using on React component:
```
  const queryRef = useLazyLoadQuery(CallDetailRecordsQuery, {
    first: 1,
    after: "OK==",
    order: { srcSpecialty: "ASC" },
    where: { srcSerialNumber: { eq: 25010 } },
  });
```
On network tab:
![image](https://user-images.githubusercontent.com/21174759/130131647-11e60651-8e42-40db-b586-db720839596f.png)
![image](https://user-images.githubusercontent.com/21174759/130131698-01f38cc0-152d-44fa-9cd7-fbe4599640a3.png)
The second error message is confusing me 😕 

@daniloab yeah, the idea sounds really good! We will try with that, but if I can make this work also would be great

**Comment by BiancaArtola** [comment]
FYI the optimal solution that we found for this was to make stitching on the back-end. thanks for helping me

**Comment by pachkovska** [comment]
when I am trying to set-up 2 different schemas, should I use a single relay environment or 2 different ones ?
