### ISSUE TITLE
Combining deleteNode and deleteEdge throws errors

### ISSUE THREAD

**Issue by bardouni** [facebook/relay#3565]
Hi
We are using v11 of relayjs on our app, and I get this error when I try to use both deleteNode and deleteEdge directives.
- Both @deleteNode and @deleteEdge are used on field ... Only one directive is supported for now.
The issue is I want to be able to remove the node from both locations ( connection and store! ), in one mutation.
Thank you.

**Comment by tyao1** [comment]
hi @bardouni, `@deleteNode` and `@deleteEdge` are both for removing an item from a connection. `@deleteNode` removes the `node`  selection and `@deleteEdge` removes the `edge`. For removing it from the store, I think you need `@deleteRecord`.

**Comment by bardouni** [comment]
Hi @tyao1 , It looks like a bug, Im not even using @deleteNode in the fragment, and it shows it in the error.

![image](https://user-images.githubusercontent.com/11160251/132001034-b04e3030-8e92-4b1e-be9e-789f504a9c44.png)
