### ISSUE TITLE
Request: Please keep renderPolicy for createFragmentContainer

### ISSUE THREAD

**Issue by mattkrick** [facebook/relay#3568]
In v11.0.2, `createFragmentContainer` does not trigger suspense by default (when `renderPolicy == 'partial'`).

I'd like to request that `UNSTABLE_renderPolicy` be kept in the API until `createFragmentContainer` is removed :pray: 

To reproduce, use `createFragmentContainer` in a child component of `usePreloadedQuery`. 
If the child component has partial data, it will throw a runtime error as that data is `undefined`.

In new apps, it's probably uncommon to mix the legacy API with hooks, but when migrating to relay-hooks, it's helpful to first migrate from `QueryRenderer` to the `useQueryLoader, usePreloadedQuery` pattern without refactoring every child component to `useFragment`.

Thanks to @zth for the tip!

**Comment by sibelius** [comment]
Migrate to new relay hooks, if the issue still valid, open another issue
