### ISSUE TITLE
star-wars example doesn't load in browser, shows "Invariant Violation" error in console

### ISSUE THREAD

**Issue by shanecav** [facebook/relay#358]
With a fresh clone of relay, then running `npm install` and `npm start` from examples/star-wars/, going to http://localhost:3000 displays the following error in the console:

>Invariant Violation: RelayOSSNodeInterface: Expected payload for root field `factions` to be a single non-array result, instead received an array with 1 results.
>_markAsRejected @ relay.js:7312

**Comment by steveluscher** [comment]
cc/ @yungsters

**Comment by yungsters** [comment]
I was able to reproduce the issue.

It seems like when we try to write the payload for `['empire', 'rebels']`, the query we have looks like:

```
factions(names: 'empire') { ... }
```

I suspect this issue is due to `diffRelayQuery` splitting off the `faction(names: ...)` query and not correctly preserving the `Array`-ness of the argument.

**Comment by kassens** [comment]
be0111d doesn't seem to fix the issue

**Comment by josephsavona** [comment]
@kassens Are you sure you updated? I've confirmed the fix on latest.

**Comment by josephsavona** [comment]
@shanecav thanks for reporting this issue, this is fixed on master :-)

**Comment by kassens** [comment]
Okay, works for me as well now. Not sure what was going on.

**Comment by shanecav** [comment]
Perfect, thanks @josephsavona!

**Comment by kevinSuttle** [comment]
This is what I'm getting. 
<img width="1440" alt="screen shot 2016-03-25 at 12 33 15 am" src="https://cloud.githubusercontent.com/assets/95672/14038000/33ae7274-f221-11e5-8143-4b54947fa924.png">
<img width="404" alt="screen shot 2016-03-25 at 12 31 52 am" src="https://cloud.githubusercontent.com/assets/95672/14038001/33ba5968-f221-11e5-979e-cd018e9c0b7a.png">

**Comment by kevinSuttle** [comment]
This is what I'm getting. 

<img width="1440" alt="screen shot 2016-03-25 at 12 40 58 am" src="https://cloud.githubusercontent.com/assets/95672/14038085/434bd036-f222-11e5-8462-e9aa840523e0.png">


<img width="1440" alt="screen shot 2016-03-25 at 12 34 22 am" src="https://cloud.githubusercontent.com/assets/95672/14038086/4ae453e0-f222-11e5-8bd2-f4a6cb96730e.png">
