### ISSUE TITLE
useFragment does not verify that fragmentInput type matches output data

### ISSUE THREAD

**Issue by hellocontrol-bng** [facebook/relay#3597]
As the title says, it's possible to pass a fragmentInput and fragmentRef that are mismatched, and useFragment does nothing to prevent this. This is most apparent when using multiple fragments of different kinds at the same time (if, for example, you have an array of multiple possible types of data, and create fragments for each one).

Let's say I have a connection which contains multiple possible types of data:

```
	query FooPageQuery($slug: String!)
	{
		all_foo_pages(where: { url: $slug })
		{
			items 
			{


				sectionsConnection
				{
					edges
					{
						node
						{
							...BarFragment
							...FizzFragment
							...BuzzFragment
						}
					}
				}
			}
		}
	}
```

Perhaps I'm creating a page with arbitrary "sections" which may be of types `Bar`, `Fizz` or `Buzz`. Now, it's very possible that I'm doing this wrong, but this is how I've written this:

```typescript
const data = useLazyLoadQuery<FooPageQuery>(graphql`
	query FooPageQuery($slug: String!)
	{
		all_foo_pages(where: { url: $slug })
		{
			items 
			{
				sectionsConnection
				{
					edges
					{
						node
						{
							...BarFragment
							...FizzFragment
							...BuzzFragment
						}
					}
				}
			}
		}
	}
`, {slug: `/${params.slug}`});

const foundPage = data.all_foo_pages.items[0];

return (
	<div>
		{foundPage .sectionsConnection.edges.map(({node}) => (
			<>
				<Bar input={node} />
				<Fizz input={node} />
				<Buzz input={node} />
			</>
		)}
	</div>
);
```

Each of the three fragment components follow a similar pattern but with differing data in each:

```
export const Bar = ({input}) =>
{
	const data = useFragment(graphql`
		fragment BarFragment on Bar {
			barProperty
		} 
	`, 
	input);

	return (
		<div>{data?.barProperty}</div>
	);
}
```

The result of the above is that each of `<Bar />`, `<Fizz/>`, and `<Buzz />` will render even if the data is not for the fragment they expect. To circumvent the problem, I'm using a wrapper hook, which ensures that the data that comes back is of the same type as the fragmentInput, but I think it's reasonable to expect this to be handled for me:

```
export function useTypedFragment<TKey extends ArrayKeyType>(fragmentInput: GraphQLTaggedNode, fragmentRef: TKey): ArrayKeyTypeData<TKey>;
export function useTypedFragment<TKey extends ArrayKeyType>(fragmentInput: GraphQLTaggedNode, fragmentRef: TKey | null): ArrayKeyTypeData<TKey> | null;
export function useTypedFragment<TKey extends KeyType>(fragmentInput: GraphQLTaggedNode, fragmentRef: TKey): KeyTypeData<TKey>;
export function useTypedFragment<TKey extends KeyType>(fragmentInput: GraphQLTaggedNode, fragmentRef: TKey | null): KeyTypeData<TKey>
{
	const data = useFragment(fragmentInput, fragmentRef);

	if ((data as any).__typename !== (fragmentInput as any).default.type)
	{
		return null;
	}

	return data;
}
```

**Comment by josephsavona** [comment]
In cases such as this where you have an item (or items) that can be of a variety of different types (interface/union), our recommended approach is to fetch `__typename` and switch rendering based on the type. So instead of rendering:

```
// anti-pattern
<>
  <Bar input={node} />
  <Fizz input={node} />
  <Buzz input={node} />
</>
```

You would instead do something like:

```
if (node.__typename === 'Bar') {
   return <Bar input={node} />;
} else if (node.__typename === 'Fizz') {
   return <Fizz input={node} />;
} // etc
```

**Comment by hellocontrol-bng** [comment]
@josephsavona Thanks for the reply. I ended up writing a React hook that took a mapping of fragment names to components and renders the appropriate component given the fetched data.
