### ISSUE TITLE
Error on mutation spec

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#360]
Can't find [info](https://facebook.github.io/relay/graphql/mutations.htm) what exactly server should return when mutation fails. 

I guess there should be some particular format for relay, so it somehow contains `clientMutationId` and error, right?

**Comment by yuzhi** [comment]
cc @dschafer

**Comment by dschafer** [comment]
For errors on mutations, we usually return a null `data` and non-null `errors`. So we don't return the `clientMutationId` in that case; we haven't needed it, but it's reasonable to return it in some way if that is useful.

**Comment by yuzhi** [comment]
@jardakotesovec  Is Dan's response what you were looking for?

**Comment by jardakotesovec** [comment]
@yuzhi Yes, thanks. I did not realize that this convention is described directly in graphQL [spec](https://facebook.github.io/graphql/#sec-Errors), so I guess no need to have it explicitly in [graphQL - Relay spec](https://facebook.github.io/relay/graphql/mutations.htm). 

So closing, thanks!
