### ISSUE TITLE
Types inside querys

### ISSUE THREAD

**Issue by BiancaArtola** [facebook/relay#3614]
I am using **typescript** and **relay**.
Suppose that my query is something like this:
```
query test {
       test {
         test2 {
           a
           b
           c
        }
     }
}
```
Is there a way to get the type of any of the internal properties of my query? For example, for `test2`.

**Comment by sibelius** [comment]
test['test']['test2] ?

**Comment by BiancaArtola** [comment]
Yes I didn't know that thanks

**Comment by BiancaArtola** [comment]
What's the issue here? 
My schema:
```
export type callDetailRecordsFragment_query = {
    readonly callDetailRecords: {
        readonly edges: ReadonlyArray<{
            readonly __typename: string;
            readonly node: {
                ...
            } | null;
        }> | null;
        readonly totalCount: number;
    } | null;
    readonly " $refType": "callDetailRecordsFragment_query";
};
```
When I tried to access:
![image](https://user-images.githubusercontent.com/21174759/137487510-48c40e14-8d0f-490c-8ff1-dece9e2edca2.png)

**Comment by BiancaArtola** [comment]
looks great but I still don't understand why I am getting an error

![image](https://user-images.githubusercontent.com/21174759/137489473-14bdb22e-d164-4c97-8696-4407d984d9d7.png)
