### ISSUE TITLE
relay-compiler - @stream argument naming does not follow spec:  `initialCount` vs `initial_count` ? 

### ISSUE THREAD

**Issue by damikun** [facebook/relay#3619]
Current compiler (not rust experimental) require for @stream argument naming as @stream(`initial_count`:value) but gql-specification define this as `initialCount`...

If i go over sources relay specialy check for `nitial_count` naming :

https://github.com/facebook/relay/blob/a07750f252e409e419e6886ec4a3d2a20cc4c48c/packages/relay-compiler/transforms/DeferStreamTransform.js#L119

If GraphQL server follow schema specification (`initialCount`) it is not possible to compile with error:

```
- Invalid use of @stream, the 'initial_count' argument is required. ...
```

Schema specification for @defer and @stream:

https://graphql.org/blog/2020-12-08-improving-latency-with-defer-and-stream-directives/
or
https://github.com/graphql/graphql-spec/pull/742/files

**Compiler should follow schema specification or don't check this and use type from schema definition...**

**Versions:**
  "relay-compiler": "12.0.0",

**Comment by alunyov** [comment]
Thanks for the report!

> Current compiler (not rust experimental)

Our overall plan is to deprecate the current JS compiler: https://github.com/facebook/relay/issues/3180. So all our current efforts are focused on that, and we're not planning on adding/fixing issues in the JS version.

**Comment by damikun** [comment]
@alunyov  Are you sure that rust one has not equal problem ? i can see usage of `initial_count` (not spec variable) in test and in sources...

Source
https://github.com/facebook/relay/blob/16753a5d5b2e5998a18b5b22ae847fb78bb7d9ef/compiler/crates/relay-transforms/src/defer_stream/mod.rs

Some test
https://github.com/facebook/relay/blob/86842c141eb59b31269893f224bf24375a2b3539/compiler/crates/relay-transforms/tests/defer_stream/fixtures/fragment-with-stream-missing-initial-count-arg.invalid.expected

**Comment by josephsavona** [comment]
Yeah, our implementation is based on Facebook's internal implementation of stream and defer upon which the official GraphQL spec version was based. However the spec made some changes such as renaming some fields. We have an outstanding task to update to support the OSS spec in addition to our internal version.

**Comment by damikun** [comment]
Heh ok understand that... Good thanks, that server I'm using able me to override core framework types so i can use it..

**Comment by maraisr** [comment]
Fairly sure this is all you need to override in a server to be Relay compliant:

https://github.com/maraisr/meros/blob/aba7ad1be69bcd7e4ee76304d5079fb0e2933b83/examples/relay-with-helix/server.ts#L66

https://github.com/maraisr/meros/blob/aba7ad1be69bcd7e4ee76304d5079fb0e2933b83/examples/relay-with-helix/server.ts#L97-L101

**Comment by damikun** [comment]
@maraisr  I'm currently doing this on server since HC enable to write TypeInterceptor. But yes thats server specific workeround..

```
public class StreamTypeInterceptor : TypeInterceptor{

        #nullable enable
        public override void OnBeforeCompleteType(
        ITypeCompletionContext completionContext,
        DefinitionBase? definition,
        IDictionary<string, object?> contextData)
        {
        #nullable disable

            if(definition is DirectiveTypeDefinition directiveTypeDefinition 
            && directiveTypeDefinition?.RuntimeType == typeof(StreamDirective)){
                                
                var InitCountArg = directiveTypeDefinition.Arguments
                    .First(e=>e.Property?.Name == "InitialCount");

                if(InitCountArg != null){
                    InitCountArg.Name = "initial_count";
                }
            }
        }
    }
```

**Comment by maraisr** [comment]
Ya just a rename and all is well. 🚀 

Hope this lands in OSS under similar flags as the other things do.
