### ISSUE TITLE
Every unique page of the Relay website should have a unique page title

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#362]
For instance, the page title for http://facebook.github.io/relay/docs/getting-started.html should be: “Getting Started | Relay Docs” and the page title for http://facebook.github.io/relay/support.html should be “Relay Support”.

The *only* page that should have the title “Relay | A JavaScript framework for building data-driven React applications” should be the home page.

**Comment by zpao** [comment]
See https://github.com/facebook/react-native/commit/129d1548a8f8537ee90c17ed1e9d5d5ec35204e0 for how React Native did it.

**Comment by michaelchum** [comment]
Resolved in #374 This can be closed!

**Comment by kassens** [comment]
Thanks for your help @michaelchum!
