### ISSUE TITLE
Get GraphQL error response

### ISSUE THREAD

**Issue by BiancaArtola** [facebook/relay#3621]
I am using `React`, `Typescript`, and `Relay`.

I am facing the following situation:
When a user inserts a number with more than 20 digits, a query will be executed and will return a `500 `error. I want to manage that error on the front end and get the error message provided by the query (the error code is something that will be useful to have). For example:

![image](https://user-images.githubusercontent.com/21174759/139728162-eb80105e-cc19-4fa3-8d6e-052bd967b890.png)

I tried with Error Boundary but the error that I get is different, like this:

![image](https://user-images.githubusercontent.com/21174759/139728191-bf760013-93c9-4d53-8f41-7e8599a1f176.png)

How can I do that?

**Comment by sibelius** [comment]
it looks like a backend problem

**Comment by BiancaArtola** [comment]
yeah, but it is an expected error. is no way to catch this message?

**Comment by josephsavona** [comment]
The way we handle this internally is to attach a severity code to each error on the server, and then the Relay network layer throws for any request that contains severe errors. For example, in your network layer you might do something like:

```javascript
async function fetchGraphQL(text, variables) {
  const REACT_APP_GITHUB_AUTH_TOKEN = process.env.REACT_APP_GITHUB_AUTH_TOKEN;

  // Fetch data from GitHub's GraphQL API:
  const response = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      Authorization: `bearer ${REACT_APP_GITHUB_AUTH_TOKEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query: text,
      variables,
    }),
  });

  // Get the response as JSON
  const result = await response.json();
  
  if (result != null && Array.isArray(result.errors)) {
     for (const error of result.errors) {
       // your logic to decide when to throw, you probably don't want to throw for all errors but just critical ones
       if (shouldFailRequestForError(error)) { 
         throw new Error(error.message);
       }
     }
  }
  return result;
}

```

**Comment by BiancaArtola** [comment]
thanks @josephsavona
