### ISSUE TITLE
[Rust][Compiler] Add Configuration/Document Query Persisting in the OSS Compiler

### ISSUE THREAD

**Issue by alunyov** [facebook/relay#3627]
- [x] Add config to SingleProjectConfigFile
- [x] #3660

**Comment by maraisr** [comment]
This in order to support `@preloadable` in OSS?

**Comment by alunyov** [comment]
In the rust version, we decided to expose the persisting mechanism we are using internally. Basically, we're sending (HTTP post) full query text to the API endpoint, that knows how/where to save the query text, and it can return a persisted query ID for it.

See: https://github.com/facebook/relay/blob/main/compiler/crates/persist-query/src/lib.rs#L53-L72

This task is just to add documentation for it and expose it via SingleProjectConfigFile,  here: https://github.com/facebook/relay/blob/main/compiler/crates/relay-compiler/src/config.rs#L630

And yeah, with persisted query IDs @preloadable can generate $parameters files that can be used with entry-points. But maybe there is something else we need to add.

**Comment by wongmjane** [comment]
It’s great to know the Rust version of the Relay compiler has `RemotePersister` for persisting queries remotely: 

https://github.com/facebook/relay/blob/87696f9cbf61739cb7474be447cf1d88e6eec0c8/compiler/crates/relay-compiler/src/remote_persister.rs

Will there still be a way to locally persist the queries (e.g. writing into a JSON file locally like the JS version)? Thanks!

**Comment by alunyov** [comment]
Thanks @wongmjane!

Currently, we don't have this, but it should not be difficult change to add support for this. 
This new JSON local persister just needs to implement the `OperationPersister` trait. 

We always welcome contributions and are happy to review and merge them :-)
