### ISSUE TITLE
Relay Compiler adds "| undefined" type check

### ISSUE THREAD

**Issue by elbarryamine** [facebook/relay#3629]
I am working with a team on an app , I am running windows and they are on mac and when we run relay compiler script i get this :

i am not sure if the os the one causing this ?

but i get this :

`readonly " $data"?: productsListPagination$data | undefined;`

and they get this instead : 

`readonly " $data"?: productsListPagination$data;`

any idea why ?

this is my relay.config.js

module.exports = {
  src: "./assets/js",
  schema: "./assets/js/schema.graphql",
  exclude: ["**/node_modules/**", "**/__mocks__/**", "**/__generated__/**"],
  extensions: ['tsx', 'jsx', 'js', 'ts'],
  language: 'typescript',
}

and this is the command i run

`"relay" : "relay-compiler"`

Thank you in advance

**Comment by voj** [comment]
@elbarryamine what was your resolution on this? I'm seeing a similar problem.
