### ISSUE TITLE
Docs examples don't work

### ISSUE THREAD

**Issue by Strandedpirate** [facebook/relay#3639]
Almost every example in the relay docs are non-functional. Magic variables that are not declared, missing imports, missing commas and component properties and so on. I can't learn from these docs because I can't see what all these missing bits are and how they involve themselves in the context of each example.

**Comment by Strandedpirate** [comment]
You should add several **functioning** quick starts to your documentation. While your docs look great they suffer from being written from the perspective of the developers using it daily, and neglect to detail what all the things are, were things are coming from, and why they are coming from said location. Such as mentions of query references, routers and so on.

Trying to onboard myself has taken weeks and I still don't know if I'm doing things correctly.

**Comment by alunyov** [comment]
Thank you for feedback. 
Have you tried using our code sandbox example: https://codesandbox.io/s/relay-sandbox-nxl7i?from-embed?

We're planning on investing more in the quality of docs/examples next year.
