### ISSUE TITLE
Rust compiler does not parse tab-indented queries

### ISSUE THREAD

**Issue by kesne** [facebook/relay#3642]
When using the new rust compiler, it looks like it fails to parse any queries that have leading tabs before the operation type. It looks like newlines and spaces are handled fine though.

For example, this results in the Relay compiler generating no code:
```js
graphql`
	query AppQuery {
		node(id: "test") { id }
	}
`;
```

Meanwhile if we just dedent before the operation type, the compiler will pick it up fine:
```js
graphql`
query AppQuery {
		node(id: "test") { id }
	}
`;
```

**Comment by maraisr** [comment]
relates to: https://github.com/facebook/relay/issues/3473
