### ISSUE TITLE
parts of fragments get ignored

### ISSUE THREAD

**Issue by u9520107** [facebook/relay#365]
I've got this strange issue where sometime part of a fragment would be missing from the actual query.

```
fragment on Viewer {
  id,
  user {
    id
  },
  categories {
    id,
    ...
  },
  products {
    ...
  }
}
```

Using react-router-relay for client-side route handling. When the page loads directly into this route, somehow the fragment composer would omit the categories portion, and only fetch back the user and products fields. But if the page initializes in a different route, then navigated to this route, then the query will be whole.

Where should I be looking first to track this problem?

**Comment by yuzhi** [comment]
The first place I would look at is the network tab on the browser to see if the query is being properly sent and if the server is returning reasonable payloads. 
Can you check that first to see if you find anything useful?
I can suggest a few more places to look after you do that.
It might also be useful if you share more information about the specific route you have and the fragments in the component in question.

**Comment by u9520107** [comment]
The query that was sent to server contains the portion with products, but not categories. This is by printing the raw text received on the server side.
So I think the error happens when Relay is gathering up fragments.
The strange thing is that products and categories are requested on the same fragment. Dunno why one of them goes missing.

**Comment by yuzhi** [comment]
Can you include more information about what your current route looks like and also what's defined on the schema for `categories`? Did you get any babel transform errors?

cc @josephsavona could this be printer related?

**Comment by u9520107** [comment]
Type Category is basically like this.
```
type Category {
   id: globalIdField('Category'),
   tags: [GraphQLString],
   subCategories: [Category]
}
```
Type Viewer:
```
Type Viewer {
  id: globalIdField('Viewer'),
  products {
     type: ProductList    #sort of like connection with customized search features
  },
  productCategories {   #renamed to productCategories 
    type: [Category]
  }
}
```

Router setup:
```
<Router ...
>
  <Route
    path="/test"
    component={Test}
  />
  <Route
    path="/"
    component={App}
    queries={AppQueries}
  >
    <Route
      path="products"
      component={Products}
      queries={ProductsQueries}
    >
    </Route>
  </Route>
</Router>
```

App queries basically only viewer's id,
Product's fragments: 
```
const Products = Relay.createContainer(ProductsView, {
  viewer: () => Relay.QL`
    fragment on Viewer {
      id,
      user {
        id
      },
      products {
        total,
        list {
          id,
          ...
         }
      },
      productCategories {
        id,
        subCategories {
          id
        }
      }
    }
  `,
});
```

There are no babel errors. In fact, if the page is loaded via '/test', then navigated to '/products', then the data fetch would be complete. ProductCategories is only missing when I try to access '/products' from the server directly.

**Comment by josephsavona** [comment]
I understand that the `productCategories` field isn't sent to the server, but is the data for this field available in the component? Is this field queried anywhere else in the app, such that it might have already been cached?

**Comment by u9520107** [comment]
@josephsavona This field would be undefined when the query's missing. This is the only place productCategories is used in a fragment.

**Comment by josephsavona** [comment]
Ok, this is definitely weird. Can you produce a minimal repro case? The [Relay playground](http://facebook.github.io/relay/prototyping/playground.html#/) would be perfect for this.

**Comment by u9520107** [comment]
Ok... I can't seem to reproduce this on the Relay playground.
 
Our team has decided in favor of dropping relay for now, and rely on basic flux architecture, while using graphQL as the query language. So, my hands are pretty much tied at the moment.

I'll try to put together a repro case over the weekend.

**Comment by josephsavona** [comment]
@u9520107 Yeah, a repro case would be great to have if possible. Thanks again for filing an issue!

**Comment by josephsavona** [comment]
We have extensive tests that fields aren't removed from queries unless data exists in the cache. There isn't much we can do without a repro case - @u9520107, let us know if you're able to create one!

**Comment by u9520107** [comment]
Sorry, I am currently caught up on project schedules, and probably won't be able to work on this for a while. I'll try to create a repro case if I can squeeze out some time during next month.
