### ISSUE TITLE
Using `console.error()` for Query Failures causes red screen of death on React Native

### ISSUE THREAD

**Issue by skevy** [facebook/relay#366]
https://github.com/facebook/relay/commit/a0d80d5f4c9802b5eb6bda4a5d3d2855fb301197

This commit changed to using `console.error()` to report query failures. In a browser, hidden away in dev tools, this doesn't really matter. On React Native however, in development specifically, using `console.error()` rather than `console.log()` causes a red screen of death. This seems like incorrect behavior for relay, as it prevents the developer from handling query errors (such as an unavailable server) gracefully.

**Comment by kassens** [comment]
We should probably change this to `console.warn`. What do you think @yungsters?

**Comment by yungsters** [comment]
When I originally decided on `console.error`, my assumption was that in development, you spend majority of your time assuming the request does not fatal. Under this assumption that server errors are unexpected in development, I thought a big red box was better.

That said, I have not had sufficient experience iterating on a product and its error states. I would be fine with changing this to use `console.warn` if this is a source of pain.

**Comment by skevy** [comment]
The specific use case, if it helps, is the first screen in my app. My graphql endpoint is authenticated, and so when the app first loads (because this first screen is a RelayContainer), the request fails. This is ok - i want to show data on this screen AFTER the user has tapped the 'login w/ Facebook' button.

**Comment by yungsters** [comment]
Ahh... okay. We should definitely change that to use `console.warn`.
