### ISSUE TITLE
[Feature Request][Compiler]: watch schema file

### ISSUE THREAD

**Issue by taras** [facebook/relay#3661]
# Context

We use Relay in a monorepo where we have both frontend and backend packages. We have a backend package that generates a schema file. In our monorepo, it's possible to work on the frontend and backend at the same time. relay-compiler has a nice workflow when editing source code in the frontend package. A change to the source code automatically triggers types to get re-generated.  Unfortunately, the same doesn't happen when we make a change to the backend package which updates the schema file. When the schema file changes, we need to manually restart `relay-compiler`.

Currently, we use a workaround using `sane` that automatically restarts relay with a command like this `sane 'relay-compiler --watch'  externa_directory_location --glob=schema.graphql --change-only`

# Feature Request

It would improve the full-stack developer experience and eliminate the need for `sane`  if the `relay-compiler` watched the schema file and automatically rebuilt types when the schema changes.

**Comment by alunyov** [comment]
what version of the compiler is it? If it's 12 (or below) - JS version, we probably won't be able to fix this. But the new version (upcoming release v13) definitely should have this working correctly (`watchman` is required).

**Comment by taras** [comment]
We're having this problem with v11, but I'm happy to have this in v13.

**Comment by alunyov** [comment]
Should be fixed in v13.
