### ISSUE TITLE
[relay-compiler][v13] create __generated__, if it's not available 

### ISSUE THREAD

**Issue by alunyov** [facebook/relay#3663]
1) Clone https://github.com/vincentriemer/new-relay-compiler-issues-repro
2) npm install & npm test

Actual result:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to canonicalize file \"/Users/alunyov/new-relay-compiler-issues-repro/src/__generated__\". Error: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }"', crates/relay-compiler/src/config.rs:128:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Expected result:
Option 1) `__generated__` directory is created automatically.
Option 2)(not great)  Error message clearly explains the issue and how to resolve it.

**Comment by taras** [comment]
@alunyov what are you using for the `Mock query persistence server`?

**Comment by alunyov** [comment]
In v13 we'll have an option to specify persisting configuration (url, params) for query persisting API. Relay compiler will send a full query `text` to this `url` and expect the API to return and `id` for the query. This `id` will be used as persisted query ID in generated artifacts for query (Normalization, $Parameters files).

A mock implementation just returns a `hash` of the query text and doesn't save it anywhere (
this is just for testing):

https://github.com/vincentriemer/new-relay-compiler-issues-repro/blob/main/mockQueryPersistServer.js
