### ISSUE TITLE
Relay Compiler generates Typescript Synthax error

### ISSUE THREAD

**Issue by bardouni** [facebook/relay#3668]
I'm running relay-compiler with type script and it generates this exact line ( Empty Alias ) when using "conections".
import { FragmentRefs as  } from "relay-runtime".
Thank you
![image](https://user-images.githubusercontent.com/11160251/144334977-ace9db95-b9f4-47a4-bcfd-558f35ffe3a2.png)

Packages versions:
![image](https://user-images.githubusercontent.com/11160251/144335071-b2a8614f-acd4-44a2-a258-027a5953c072.png)

**Comment by TrySound** [comment]
@bardouni See https://github.com/relay-tools/relay-compiler-language-typescript/releases/tag/v15.0.0

**Comment by TrySound** [comment]
Ah, see you already have 15. Still better address this to https://github.com/relay-tools/relay-compiler-language-typescript repo.

**Comment by bardouni** [comment]
Thank you

**Comment by alunyov** [comment]
Issue in `relay-compiler-language-typescript`. Thanks @TrySound  for looking into this.
