### ISSUE TITLE
[relay 13]-useFragment Typescript compiler issue

### ISSUE THREAD

**Issue by sync** [facebook/relay#3670]
Tried to use the latest Relay "13.0.0-rc.0" with TypeScript and having issues with useFragment typings. 

Here is a reproduction:
https://github.com/sync/react-relay-13

Then run 
```sh
yarn
yarn relay
yarn typecheck
```

You'll end up getting this type error:
<img width="720" alt="Screen Shot 2021-12-04 at 3 42 34 pm" src="https://user-images.githubusercontent.com/21725/144697305-e088eaab-c303-4382-b135-43d28c8bd7ec.png">

<img width="1177" alt="Screen Shot 2021-12-04 at 3 43 28 pm" src="https://user-images.githubusercontent.com/21725/144697316-fa9a3aef-bbc3-415a-af95-008189b8c941.png">

<img width="729" alt="Screen Shot 2021-12-04 at 3 43 21 pm" src="https://user-images.githubusercontent.com/21725/144697325-f1225aa6-54c0-4b6e-b635-738d5f8e6211.png">

For comparison, here is a relay 12 version (no issues):
https://github.com/sync/react-relay-13/pull/1/files

Perhaps some @types for relay need to be updated with `fragmentSpreads` support ?

**Comment by sync** [comment]
yes by the look of it

```
export type KeyType<TData = unknown> = Readonly<{
    ' $data'?: TData | undefined;
    ' $fragmentRefs': FragmentReference;
}>;
```

let me have a look if I can easily fix it

**Comment by sync** [comment]
Yes indeed need to update the @types for relay useFragment, 

<img width="1566" alt="Screen Shot 2021-12-04 at 4 09 07 pm" src="https://user-images.githubusercontent.com/21725/144698039-df3c6f8d-cf66-4fe0-9e64-5488dcd0f70f.png">

I'll try to fix it locally and then can submit a PR to @types, not sure how to deal with rc version with the @types repo

**Comment by sync** [comment]
Yes changing this type fixes the issue

```
export type KeyType<TData = unknown> = Readonly<{
    ' $data'?: TData | undefined;
    ' $fragmentSpreads': FragmentReference;
}>;
```

**Comment by AndrewIngram** [comment]
The above patch worked for me too

**Comment by sibelius** [comment]
can anybody contribute this patch to the https://github.com/DefinitelyTyped/DefinitelyTyped ?

**Comment by maraisr** [comment]
pr raised https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57614

**Comment by orta** [comment]
That PR is merged, I think the new version will be @types/react-relay 11.0.3 and works with relay 12 and 13
