### ISSUE TITLE
[relay13] Cannot access schema which is further up the directory tree

### ISSUE THREAD

**Issue by orta** [facebook/relay#3673]
My folder structure looks roughly like:

```
/
 .redwood
   schema.graphql

  web
   package.json
     src
       ...
```

Which means I'd use this config:

```
 "relay": {
    "schema": "../.redwood/schema.graphql",
  },
```

in `web/package.json`, but it seems to be ignored:

```
❯ yarn relay-compiler
yarn run v1.22.17
$ /Users/ortatherox/dev/redwood/relay-redwood-app-example/node_modules/.bin/relay-compiler
[ERROR] Config `/Users/ortatherox/dev/redwood/relay-redwood-app-example/web/package.json` is invalid:
 - The `schema` configured for project `default` does not exist at `/Users/ortatherox/dev/redwood/relay-redwood-app-example/web/schema.graphql`.
```

I wondered if it was the relative path, but the absolute path also didn't work. Changing my command to `yarn relay-compiler --schema ../.redwood/schema.graphql` worked though.

**Comment by orta** [comment]
This is very likely due to paths which go back through the folder structure not being respected, (after #3674) and copying the GraphQL schema to `/web/src/graphql.schema` then setting this in the `package.json` the compiler loads up fine:

```
  "relay": {
    "language": "typescript",
    "src": "./src",
    "schema": "./src/schema.graphql",
    "artifactDirectory": "./src/components/__generated__"
  },
```

```
❯ env RUST_BACKTRACE=1 yarn relay-compiler
yarn run v1.22.17
$ /Users/ortatherox/dev/redwood/relay-redwood-app-example/node_modules/.bin/relay-compiler
querying files to compile...
[default] compiling...
[default] compiled documents: 7 reader, 6 normalization, 7 operation text
Done
```

**Comment by bigfootjon** [comment]
(I'm not a Relay engineer, I just also work at Meta and hit this in a personal project)

You can workaround this problem by setting the root to a parent directory and using "multi project mode" which is undocumented but you can read about in the source code. Example for the dir structure given in the OP (I think):

```
{
    "root": "../",
    "sources": {
        "web": "default"
    },
    "projects": {
        "default": {
            "schema": ".redwood/schema.graphql",
        }
    }
}
```

**Comment by orta** [comment]
Confirming that setting my package JSON to:

```json
{
  "relay": {
    "root": "../",
    "sources": {
        "web": "default"
    },
    "projects": {
        "default": {
            "schema": ".redwood/schema.graphql",
            "language": "typescript"
        }
    }
  },
}
```

Got the artifacts building 👍🏻

**Comment by alunyov** [comment]
Thanks @orta and @bigfootjon for reporting/commenting on this issue.
The fix is coming.

**Comment by alunyov** [comment]
Should be fixed here: https://github.com/facebook/relay/commit/6eea5a8c97f6479cf71697447f78d60ef7aa7745

**Comment by orta** [comment]
Thanks, will switch to tomorrow's nightly

**Comment by orta** [comment]
Confirmed as working well with my original settings: 

```json
  "relay": {
    "language": "typescript",
    "src": "./src",
    "schema": "./src/schema.graphql",
    "artifactDirectory": "./src/components/__generated__"
  },
```

in RC1, it also fixed an unreported (because I was just working around it) case where the compiler was working from the wrong cwd - nice work
