### ISSUE TITLE
[relay 13] Change in type output from JS Typescript Relay Compiler

### ISSUE THREAD

**Issue by robrichard** [facebook/relay#3679]
Was it intentional that the Rust compiler removed the type export with the same name as the fragment?

For example, this was previously allowed by `relay-compiler-language-typescript`

```ts
import { MyComponent_user } from './__generated__/MyComponent_user.graphql';
```

`MyComponent_user` would be defined as the data type for `MyComponent_user` and aliased to `MyComponent_user$data`

```ts
export type MyComponent_user$data = MyComponent_user;
```

Should we only use the `<fragment-name>$data` type in component code, or could the alias be restored? If not, we'll have to codemod a large number of files to upgrade to v13.0.0

**Comment by alunyov** [comment]
@robrichard thanks for the report. I don't think it was intentional, I'll take a look at this.

**Comment by kassens** [comment]
The types were kind of a mess with operations using a pattern like `MyQueryVariables` and `MyQueryResponse` where fragments used to export the types as `MyFragment$key` and `MyFragment`.

For now, you might be able to set this in the config which has aliases to the "old names" exported:
```
"flowTypegen": {
   "phase": "Phase4"
},
```

I think we can keep the alias at least for the non-suffix version for the moment.

**Comment by robrichard** [comment]
@kassens adding `flowTypegen` to our config (even though we are using typescript) restored the non-suffix keys we were using.

**Comment by hanford** [comment]
@robrichard where did you add

```
"flowTypegen": {
  "phase": "Phase4"
},
```

I've tried adding it to my `package.json#relay` config but that throws

```
It also cannot be a single project config file due to:
- Error("unknown field `flowTypegen`, expected one of `schema`, `src`, `artifactDirectory`, `excludes`, `schemaExtensions`, `noFutureProofEnums`, `language`, `customScalars`, `eagerEsModules`, `persistConfig`", line: 0, column: 0).
```

**Comment by robrichard** [comment]
@hanford my config looks like this

```json
{
    "root": ".",
    "excludes": ["**/node_modules/**"],
    "sources": {
        "": "myProject"
    },
    "projects": {
        "myProject": {
            "schema": "schema.graphql",
            "language": "typescript",
            "flowTypegen": {
                "phase": "Phase4"
            }
        }
    }
}
```

**Comment by alunyov** [comment]
In the lates version `relay-compiler@main` we've change the default configuration, so there is no need to pass `Phase4` via configs to emit "old" operation types. Also `Phase4` renamed to `Compat`.

**Comment by janicduplessis** [comment]
Posting here for visibility, wrote a codemod to update types https://github.com/facebook/relay/issues/3792#issuecomment-1120460532
