### ISSUE TITLE
getOptimisticResponse for custom scalars not working as expected

### ISSUE THREAD

**Issue by juhaelee** [facebook/relay#368]
I have a custom scalar that is called `coordinate` that takes a shape like this {x: INT, y: INT}

When I try to do use `getOptimisticResponse` on an `"RANGE_ADD"` I have something like this:

```javascript
return {
      gridEdge: {
        node: {
          coordinate: this.props.point
        }
      }
}
```

but when my container receives this update, coordinate exists, but appears as an empty object without the coordinate attributes. ( coordinate: {__dataID__: "client:SOMENUMBER"} ). `this.props.point` has the correct value before it is returned in `getOptimisticResponse` as well.

I've also tried something like this, to no success:
```javascript
return {
      gridEdge: {
        node: {
          coordinate: {
               x: this.props.point.x,
               y: this.props.point.y
          }
        }
      }
}
```

Wondering if Relay can't support custom scalars in optimistic updating yet?

**Comment by juhaelee** [comment]
It looks like that objects can't be passed through a field in `getOptimisticResponse`? I'm getting around this situation currently, by using JSON.stringify(coordinate) and passing that though

**Comment by josephsavona** [comment]
@juhaelee What is the fat query for this mutation?

**Comment by juhaelee** [comment]
@josephsavona 
```javascript
getFatQuery(){
    return Relay.QL`
      fragment on CreatePointPayload {
        gridEdge,
      }
    `;
  }
```

**Comment by josephsavona** [comment]
Custom scalar types are a new feature in OSS GraphQL, but it would seem that the value for such a field would have to actually be a scalar, ie, it should serialize to a string, number, or boolean. I think that `JSON.stringify` is the right solution here.

**Comment by juhaelee** [comment]
Just to clarify, `JSON.stringify` in `getOptimisticResponse` and not the custom scalar implementation correct?

**Comment by josephsavona** [comment]
I'm double-checking my assumption with @dschafer - but yeah, I was thinking  in `getOptimisticPayload`

**Comment by josephsavona** [comment]
I looked into this and the problem is in `inferRelayFieldsFromData`, where we attempt to infer the query that would correspond to an optimistic payload: objects are assumed to correspond to records, so in this case Relay traverses `coordinate` as if it were a non-scalar and writes the optimistic values for x/y as if they were subfields.

Using `JSON.stringify` in `getOptimisticResponse` is a temporary workaround, but this means that view code will have to handle both the JSON-stringified value and object value for `coordinate`. Long-term we should evaluate using tracked queries to construct a more correct query to match the optimistic response payload.

cc @yuzhi @yungsters

**Comment by juhaelee** [comment]
Cool, thanks for all your help!

**Comment by yuzhi** [comment]
`inferRelayFieldsFromData` does an best effort for inferring queries for optimistic. We didn't intend it to work for every case. It's mainly for basic queries. It doesn't work for fields with calls or custom scalar types. It also doesn't have access to the schema. 
We used to have a way for people to supply custom queries for optimistic payloads for these cases. We should consider bringing that back.

**Comment by josephsavona** [comment]
This looks related to #91 - Relay only supports custom "scalar" types if those types are JS scalar values - boolean, number, or strings. Let's merge the discussion into #91.
