### ISSUE TITLE
[relay 13] No files generated on windows without watchman

### ISSUE THREAD

**Issue by ch1ffa** [facebook/relay#3680]
It seems relay-compiler `v13.0.0-rc.0` can't generate files at Windows without watchman. The only output is the `Done` message. After installing watchman everything is correct.

It can be reproduced in https://github.com/relayjs/relay-examples installing `v13.0.0-rc.0` version and running build.

If you have any ideas how to get the detailed output to provide new information, let me know.

**Comment by alunyov** [comment]
Thanks for the report and what version of OS is this?

Can you also try it with `RUST_LOG=debug yarn build`?

**Comment by ch1ffa** [comment]
> Thanks for the report and what version of OS is this?
> 
> Can you also try it with `RUST_LOG=debug yarn build`?

Windows 10 Pro version 20H2 build 19042.1348

Build output:
```
[DEBUG]    0ms create_compiler_state_file_files
[DEBUG]    0ms categorize_files_time
[DEBUG]    0ms parse_sources_time
[DEBUG]    2ms build_projects_time
[DEBUG]    0ms post_build_projects_time
Done
```
