### ISSUE TITLE
mockClear does not clean the recordsource

### ISSUE THREAD

**Issue by artola** [facebook/relay#3686]
The `environment` returned by `createMockEnvironment` has a method `mockClear` which does not reset the recordsource to the [initial state](https://github.com/facebook/relay/blob/5c1045dcc05f522644fa5079ba5880d169546357/packages/relay-test-utils/RelayModernMockEnvironment.js#L185).
`mockClear` does care about cleaning the [`cache`](https://github.com/facebook/relay/blob/5c1045dcc05f522644fa5079ba5880d169546357/packages/relay-test-utils/RelayModernMockEnvironment.js#L569) but does not the same with the recordsource. Specially this difference between them it seems to me just like missing.

```javascript
import {createMockEnvironment} from 'relay-test-utils';

const environment = createMockEnvironment();

afterEach(() => {
  environment.mockClear(); // <= does not clear the recordsource
});
```

Of course we could force to create a new environment between tests, but it seems not intended such case else whole `mockClear` makes no sense.

```javascript
import {createMockEnvironment} from 'relay-test-utils';

let environment;

beforeEach(() => {
  environment = createMockEnvironment();
});
```

Other possibilities which require extra scaffolding are:

- by passing own `store` to the `createMockEnvironment` and handling cleanup with `recordsource.clear()`.
- by making a "snapshot" (`environment.getStore().snapshot()`) before the test and "restore" after the test.

**Comment by sibelius** [comment]
The recommended approach is to have 1 environment per test

**Comment by artola** [comment]
> The recommended approach is to have 1 environment per test

Until now we have being able to setup the Provider using RTL wrapper (on jest setup), and doing the cleanup between tests.
We have several thousands of tests and just 1 wrapper for all of them.
As said above `mockClear` cleans the `cache`, but it does not the recordsource. It feels just like missing.

**Comment by sibelius** [comment]
I think it makes sense a pull request to improve the current behavior

**Comment by artola** [comment]
@sibelius Thanks. PR #3687
