### ISSUE TITLE
[relay 13] Rust Compiler `customScalars`

### ISSUE THREAD

**Issue by hanford** [facebook/relay#3695]
Hello, I've very excited about Relay 13!

I was wondering if the ability to utilize customScalars was planned.

My Relay config looks something like this:

```
    src: './',
    artifactsDirection: ..,
    customScalars: {
      NonEmptyString: 'String',
      EntityId: 'EntityId',
      UnixTimestamp: 'Int',
      DateTime: 'DateString',
      Date: 'DateString',
      Time: 'String',
    },
```

When trying to run:

```
relay-compiler --artifactDirectory './dazzle-types' --src . --schema ../weaver/schemas/__generated__/main.graphql --customScalars.NonEmptyString String --customScalars.EntityId String --customScalars.UnixTimestamp Int --customScalars.Date DateString --customScalars.DateTime DateString --customScalars.Time String
```

I see the following:

```
error: Found argument '--customScalars.NonEmptyString' which wasn't expected, or isn't valid in this context
```

![image](https://user-images.githubusercontent.com/2148168/146300973-284a4f24-f1f9-40da-aaec-348b36c9f7f3.png)

**Comment by alunyov** [comment]
@hanford in the v13 we don't have support for majority of CLI arguments. Instead, you can put these in the "relay" section of the `package.json`:

```json
{
  "relay": {
    "src": "./",
    "artifactsDirectory": "..",
    "customScalars": {
      "NonEmptyString": "String",
      "EntityId": "EntityId",
      "UnixTimestamp": "Int",
      "DateTime": "DateString",
      "Date": "DateString",
      "Time": "String"
    }
  }
}
```
See the example here: https://github.com/alunyov/relay-examples/blob/main/todo/package.json#L59-L67

**Comment by sibelius** [comment]
does this also work on relay.config.js ?

**Comment by alunyov** [comment]
> does this also work on relay.config.js ?

Yes, it should work.
