### ISSUE TITLE
Type error when use Relay v12 with TypeScript.

### ISSUE THREAD

**Issue by xyy94813** [facebook/relay#3697]
I try to upgrade react-relay to v12 and got the error: 

```shell
TS2322: Type 'RelayModernEnvironment' is not assignable to type 'Environment'.
  The types returned by 'getOperationTracker()' are incompatible between these types.
    Property 'getPromiseForPendingOperationsAffectingOwner' is missing in type
```

I found the latest version of `@types/react-relay`  is `11.0.3`.
Is the Relay team maintenance `@types/react-relay`?
With the upgrade to version 12, there is a new solution?

**Comment by xyy94813** [comment]
The problem is cause by different TS declaration.

And `@types/relay-test-utils` depende on `@types/react-relay` `v11.0.3` and `@types/relay-runtime` `v11.0.3`.

**Comment by alunyov** [comment]
Hey @xyy94813 we don't own these TypeScript types. Feel free to send a PR with the fix here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-relay

**Comment by xyy94813** [comment]
Is there anyone who can provide me with a guide to maintain it?

**Comment by sibelius** [comment]
fork and send a pull request
