### ISSUE TITLE
[relay-compiler 13]  The root of subscription must be a simple selection

### ISSUE THREAD

**Issue by RadoslavK** [facebook/relay#3703]
## Reporting issues with Relay

Given schema
```graphql
type Subscription {
    changed: String!
}
```

And App.tsx
```graphql
graphql`
  subscription App_Subscription {
      changed
  }
`;
```
I get this error: [ERROR] ✖︎ The root of subscription 'App_Subscription' must be a simple selection.

It seems like the subscription result needs to be an object. However, returning simple scalars worked in older versions. Is this a breaking change/intended way to use subscriptions?

**Comment by kassens** [comment]
This is an accidental regression. We need this for an internal purpose (I think logging the subscription name or something), but the validation shouldn't happen in OSS code. We'll move this to private extensions.

**Comment by alunyov** [comment]
This should be fixed with `relay-compiler@main`.

**Comment by artola** [comment]
@alunyov This issue was closed, but it remains for me. It is not working with newest v13 neither  `relay-compiler@master`.
@RadoslavK is it working for you?

**Comment by alunyov** [comment]
Hey @artola can you provide more details here? Are you seeing the same error message?

**Comment by artola** [comment]
@alunyov I confirm the same error reported above.

```text
[ERROR] ✖︎ The root of subscription 'demo4Subscription' must be a simple selection.

  pages/demo4.js:2:22
    1 │ 
    2 │         subscription demo4Subscription($from: Int!) {
      │                      ^^^^^^^^^^^^^^^^^
    3 │           countdown(from: $from)

[ERROR] Compilation failed.
```

Same result for:
 - @latest - 13.0.0
 - @main - 0.0.0-main-35e0c2bd

This produces the error:

```graphql
type Subscription {
  countdown(from: Int!): Int
}
```

While this works:

```graphql
type Countdown {
  current: Int!
}

type Subscription {
  countdown(from: Int!): Countdown
}
```

**Comment by alunyov** [comment]
Hmm, this is strange. Let me reopen this to double-check.

**Comment by alunyov** [comment]
@artola can you check with this version: https://github.com/facebook/relay/commit/97a0e95d7425154862f95eb0b238a8401bd023e7

it should be available on NPM as relay-compiler@main

**Comment by artola** [comment]
> @artola can you check with this version: [97a0e95](https://github.com/facebook/relay/commit/97a0e95d7425154862f95eb0b238a8401bd023e7)
> 
> it should be available on NPM as relay-compiler@main

@alunyov IT WORKS!!! ... now it is possible to return some scalar as in the examples above. Thanks!
