### ISSUE TITLE
relay-compiler v12.0 not work with graphql v16.0

### ISSUE THREAD

**Issue by heerzhang** [facebook/relay#3705]
I use:  relay-compiler-language-typescript  "version": "15.0.0" 
"relay-compiler": "^12.0.0",
 "graphql": "^16.0.0", 
it thows ERROR:
Invalid AST Node: { kind: "Root", operation: "query", loc: { kind: "Source", start: 11, end: 245, source: [Source] }, metadata: null, name: "PipeMainQuery", arg
umentDefinitions: [[Object], [Object], [Object]], directives: [], selections: [[Object]], type: Query }.

While I change to  "graphql": "^15.8.0", 
all is OK!

**Comment by sibelius** [comment]
Use relay 13 rc

**Comment by alunyov** [comment]
Yeah, v16.0 has breaking changes that we do not support in v12.

- Possible workarounds: use v15
- Update to v13 RC: https://github.com/facebook/relay/releases/tag/v13.0.0-rc.1
