### ISSUE TITLE
[relay 13] Types for useLazyLoadQuery not backwards compatible with v12

### ISSUE THREAD

**Issue by bigfootjon** [facebook/relay#3711]
I imagine not many people in the OSS community use Flow, but I do for a personal project.

I just updated to rc2 and got hit with a bunch of flow errors. Example:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ minecraft/Minecraft.react.js:27:18

Cannot use function type [1] with fewer than 2 type arguments. [missing-type-arg]

     minecraft/Minecraft.react.js
     24│
     25│ function Minecraft(): React.Node {
     26│     const { isStaff } = useCurrentUser();
     27│     const data = useLazyLoadQuery<MinecraftQuery>(
     28│         graphql`
     29│             query MinecraftQuery {
...
```

I believe this is intentional as part of the Relay-Flow project (this specific problem was introduced in [this commit](https://github.com/facebook/relay/commit/3c45f95763eadb7dc8f36e1275a27f3224f160b7)) so I removed the type-hints from the `useLazyLoadQuery` callsites and then enabled the required flags in `.flowconfig`:

```diff
 [options]
 ...
+relay_integration=true
+relay_integration.module_prefix=__generated__/
 ...
```

This fixed the problems, but it feels half-baked: `useMutation` [still requires explicit types](https://github.com/facebook/relay/blob/main/packages/react-relay/relay-hooks/useMutation.js#L55-L56) as well as [`usePreloadedQuery`](https://github.com/facebook/relay/blob/main/packages/react-relay/relay-hooks/usePreloadedQuery.js#L34-L35).

This seems like an understandable breaking change in v13 (even if it is outside the "new compiler" theme) but I'm worried that the new OSS version will be released while the relay-flow project is still ongoing resulting in multiple breaking changes for relay-flow across OSS releases.

Will v13 be released with a "completed" relay-flow migration or will it be broken up over multiple releases?

(personally, I'm totally fine with a partial release, but I wanted to flag this as a potential v13 problem)

Furthermore, will the relay-flow automatic typing features be backported to relay-modern? I'm mostly asking because I make heavy use of `<QueryRenderer />` due to a quirk of how preloading works in my personal project.

CC @alunyov (as v13 release owner I think?) @kassens (looks like you're handling the commits in the relay-flow project, at least from OSS's perspective, I refuse to turn on my work laptop while on PTO :P)

**Comment by alunyov** [comment]
Thanks @bigfootjon!

> Will v13 be released with a "completed" relay-flow migration or will it be broken up over multiple releases?

Yes, the migration is still in progress. But I think we will be able to release the complete set of updated APIs with v13.
We are mostly close to completion there. It is just a lot of internal changes that need to land for this to happen.

> Furthermore, will the relay-flow automatic typing features be backported to relay-modern? I'm mostly asking because I make heavy use of <QueryRenderer /> due to a quirk of how preloading works in my personal project.

I think It should. The goal of this integration is to return the correct type from the `graphql` tag. So instead of the `GraphQLTaggedNode` type, it returns the actual type of the GraphQL document inside the `graphql` tag.
