### ISSUE TITLE
@defer -  Does not compile + No documentation

### ISSUE THREAD

**Issue by ro-savage** [facebook/relay#3715]
@rbalicki2 mentioned the @defer directive in the "Re-introducing Relay" video (https://youtu.be/lhVGdErZuN4?t=650)

However, there is no documentation in Relay as to how his can be used and just adding `@defer` like in the youtube video causes relay 12 compiler to fail.

The only mention is here: https://relay.dev/docs/glossary/#defer
Which just links to Facebook's internal docs.

```
$ relay-compiler --src ./app --schema ./schema.graphql --language typescript

Writing ts
ERROR:
- Unknown directive 'defer'.

  ProjectPlanner/ProjectRowSummary.relay.tsx:25:30
  24 |       ...ProjectBudgetDonut_project @arguments(clientDate: $clientDate)
  25 |       ...ProjectLine_project @defer
     |                              ^
  26 |       ...ProjectMilestones_project
error Command failed with exit code 100.
```

**Comment by maraisr** [comment]
Can you try this again with relay 13 — the js compiler is now deprecated.

**Comment by josephsavona** [comment]
Note that your schema must define this directive if it supports this feature. Unlike some other Relay features (eg `@refetchable`, `@connection`) which are provided by Relay and "compile away", `@defer` must be understood by the server and present in the server schema if the server supports it.

**Comment by ro-savage** [comment]
Our server does understand @defer - and it's failing on the compiler anyway.

Unfortunately I can not test with the new compiler, as we use a forked version of the relay-compiler and we haven't started work on the new rust compiler fork.

I think the documentation still need to be updated regardless - since there are no docs at the moment.

But I am unsure if this works with the rust compiler or not.

**Comment by zth** [comment]
@ro-savage can you verify that there's indeed a `@defer` directive defined in the `schema.graphql` you're pointing the compiler to? I've been using `@defer` successfully with the JS compiler, but I vaguely recall I had an issue where some methods for exporting the schema would not include the directive in the output.

**Comment by ro-savage** [comment]
Thanks @zth - It looks like the defer hadn't been setup correctly on our server for this case, and wasn't being added to the schema.graphql

This looks like an issue on our side. Thanks for taking the time to provide feedback - once the docs have been created we'll give implementation another go.
