### ISSUE TITLE
Test utils 13.0.0-rc.2: cannot find module 'relay-runtime/store/ResolverFragments'

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/relay#3720]
Hello, we have [one simple test](https://github.com/adeira/universe/blob/f57e653849330997ae270256dbf2d70b1d0979bf/src/example-relay/src/mutations/RangeAdd/__tests__/RangeAdd.test.js) that we didn't change during upgrading Relay and it seems like it doesn't work with Relay 13:

```text
 FAIL   @adeira/example-relay  src/example-relay/src/mutations/RangeAdd/__tests__/RangeAdd.test.js
  ● Test suite failed to run

    Cannot find module 'relay-runtime/store/ResolverFragments' from '../../node_modules/relay-test-utils/lib/RelayResolverTestUtils.js'

    Require stack:
      /Users/martinzlamal/Work/adeira/universe/node_modules/relay-test-utils/lib/RelayResolverTestUtils.js
      /Users/martinzlamal/Work/adeira/universe/node_modules/relay-test-utils/lib/index.js
      /Users/martinzlamal/Work/adeira/universe/node_modules/relay-test-utils/index.js
      src/mutations/RangeAdd/__tests__/RangeAdd.test.js

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (../../node_modules/relay-test-utils/lib/RelayResolverTestUtils.js:13:25)

Test Suites: 1 failed, 1 total
```

The same error is for any other test using Relay Test Utils.

Maybe something changed in a way how are the packages exported? Perhaps OSS version cannot access `relay-runtime/store/ResolverFragments` directly? 🤔

Thanks for having a look!

**Comment by alunyov** [comment]
Should be fixed here: https://github.com/facebook/relay/commit/a93d92231215f680d81482675971b33afd6c1ba0

**Comment by mrtnzlml** [comment]
Thanks, @alunyov! 👏 I will wait for this to be released and will take care of closing this issue.

**Comment by mrtnzlml** [comment]
Fixed in v13 release
