### ISSUE TITLE
[v13] Compilier does not create artifactDirectory if does not exist

### ISSUE THREAD

**Issue by erictaylor** [facebook/relay#3727]
Testing the new compiler in v13 we have noticed that usage of `artifactDirectory` does not work the same as v12. If specified artifact directory does not exist, no directory is created the following error is thrown:

```
 - The `artifactDirectory` does not exist at `./src/__generated__`.
 ```
 
 I'm curious if this is intended behavior or not.
 
 In our project we do _not_ check-in the generated files for Relay into our repo, but opt to rebuild them during build time. So since our artifact directory is git ignored this new behavior breaks our CI usage.
 
 This _wouldn't_ be a problem if I could use a `.gitkeep` in our artifact directory, but the compiler removes non generated files from the directory.

**Comment by alunyov** [comment]
> I'm curious if this is intended behavior or not.

Yes, it was intentional. The idea here is that the compiler cannot safely assume that the value in the configuration is valid. It is possible to misspell the directory name, and the compiler will automatically create it.

> This wouldn't be a problem if I could use a .gitkeep in our artifact directory, but the compiler removes non generated files from the directory.

There is PR for this should land soon: https://github.com/facebook/relay/pull/3700

**Comment by erictaylor** [comment]
Thank you for the info!

Closing this issue as the PR you linked should address our issue.

**Comment by alunyov** [comment]
Adding README/.gitkeep files to `artifactDirectory` should be possible with this https://github.com/facebook/relay/commit/0b5a8b97b4c6bc938998885873bc127964c50785 change. Should be available as `relay-compiler@main` on NPM.
