### ISSUE TITLE
[v13] Throttle persisted query uploads

### ISSUE THREAD

**Issue by robrichard** [facebook/relay#3728]
I'm setting up my codebase to use relay v13 with persisted queries. I wrote a simple node http server based on the example here: https://relay.dev/docs/guides/persisted-queries/ but am running into the following issue.

```
[DEBUG] project: myproject
[DEBUG] persist_documents: 1647
[DEBUG] worker_count: 0
[DEBUG] done persisting
[DEBUG] error: Persisting operation(s) failed:
 - Network error: error trying to connect: tcp connect error: Connection reset by peer (os error 54)
 - Network error: error trying to connect: tcp connect error: Connection reset by peer (os error 54)
 - Network error: error trying to connect: tcp connect error: Connection reset by peer (os error 54)
 - Network error: error trying to connect: tcp connect error: Connection reset by peer (os error 54)
 - Network error: error trying to connect: tcp connect error: Connection reset by peer (os error 54)
 // repeated many times
```

It appears that relay-compiler is sending a concurrent http connection for each document (1,647 in my case) to the node server and I am hitting either an OS or node connection limit. Is it possible to throttle these connections to avoid this type of issue?

**Comment by maraisr** [comment]
I'd love this. But also do vaguely remember seeing a concurrency config somewhere 🤔 can't find it now though 😔
