### ISSUE TITLE
relay v13 not generating the __generated__ folder and files after upgrading

### ISSUE THREAD

**Issue by daniloab** [facebook/relay#3729]
I have been migrated to the new relay-compiler 13. I changed my relay config removing the includes array and adding the excludes. But, now do not generate my `__generated__` folder anymore.

## exemplifying how is my environment
my folder structure example:

```bash
packages
  applicationA
  applicationB
  applicationC
```

my application `relay.config.js` file:

```js
module.exports = {
  schema: './data/schema.graphql',
  language: 'typescript',
  src: '../.',
  excludes: [
    '**/applicationB/**',
    '**/applicationC/**',
  ],
};
```

relay command in package.json:
```json
{
  ...
  "scripts": {
    ...
    "relay": "relay-compiler",
  }
}
```

## terminal result after running the relay command
running the relay command:
```bash
yarn relay
```

terminal output
<img width="699" alt="Screen Shot 2022-01-07 at 18 23 16" src="https://user-images.githubusercontent.com/19939822/148609792-4bc9351c-ed1c-4594-b5b2-b18c7c8ff38a.png">

Does anyone know what could I doing wrong or it could be a bug?

**Comment by alunyov** [comment]
I think you need to specify `artifactDirectory` in the config. Please note, that the compiler will not generate this directory automatically.

Without `artifactDirectory` the generated files are written next to the source files into the `__generated__` directory.

**Comment by daniloab** [comment]
> I think you need to specify `artifactDirectory` in the config. Please note, that the compiler will not generate this directory automatically.
> 
> Without `artifactDirectory` the generated files are written next to the source files into the `__generated__` directory.

This is the behavior that we respect. We do not specify the `artifactDirectory` to generate the types close to the owner file. 

Example:
```
components
  list
    MyAwesomeList
```

Fo the `MyAwesomeList` component we expect that the `__generated__` files be generates at the same level of folders:

```
components
  list
    __generated__
    MyAwesomeList
```

Look at this example below. For query components, the generated files were generated normally. But, my mutation does not generate. And when I run my application complains about this mutation:

![Screen Shot 2022-01-09 at 14 11 51](https://user-images.githubusercontent.com/19939822/148692908-b772bb9a-6a95-4e6e-aa36-71371a476075.png)

![Screen Shot 2022-01-09 at 14 14 00](https://user-images.githubusercontent.com/19939822/148692944-f72959e6-2e29-4c7b-bce7-5be050d24cc5.png)

**Comment by alunyov** [comment]
Hmm, this is strange.

Is there something in these mutation files that the compiler could not find `graphql` tags in them. Maybe somehow the name of their directory is overlapping with your `excludes`? Can you create a simple repro for this case?

**Comment by plamenh** [comment]
I think I am having the same issue, but this only happens for ts andn tsx files for me. @daniloab, can you confirm this? Try adding a js file with graphql query inside and see, if you get the __generated__ folder.

**Comment by MoSattler** [comment]
same problem here with TS(X). 
> [INFO] [default] compiled documents: 0 reader, 0 normalization, 0 operation text
It worked fine with 12. The queries and mutations are all properly tagged.

**Comment by MoSattler** [comment]
Same problem over here. Not generating any files for TS(X). Queries are properly tagged. Worked fine in 12 - I am not sure what is going on.

**Comment by daniloab** [comment]
actually, Im working on this migration yet but looks like it is working ok. 

We have a big monorepo where I'm fixing the fragments yet with variables not being used, variables declared as nonnull, the spread of fragment into query renderer passing it null, errors from relay compiler.

I believe that I will finish this migration this week and I can return and say if I still having the same problem

**Comment by daniloab** [comment]
Fixed here.

a final result of relay.config.js as an example

```
module.exports = {
  schema: './data/schema.graphql',
  language: 'typescript',
  src: '../.',
  excludes: [
    '**/applicationB/**',
    '**/applicationC/**',
  ],
};
```

console and register
