### ISSUE TITLE
[relay v13] Relay compiler throws 'Unsupported (user-defined) scalar type' error for scalars as arguments

### ISSUE THREAD

**Issue by christianvuerings** [facebook/relay#3730]
Scalar types passed in as arguments are no longer supported in Relay v13 (they are in v12).

This breaking change blocks us from upgrading to v13.

# Example

`schema.graphql`
```graphql
scalar ImageSpec @serializationPrimitive(type: STRING)

interface Node {
  id: ID!
}

type User implements Node {
  contextualPinImageUrls(spec: ImageSpec): [ImageDetails]
  websiteUrl: String
}

type ImageDetails {
  height: Int
  url: String
  width: Int
}

type Query {
  v3UserQuery(user: String!): User
}
```

`Root.js`

```jsx
import graphql from 'babel-plugin-relay/macro';
import React from 'react';
import { usePreloadedQuery } from 'react-relay/hooks';

export default function Root(props) {
  const data = usePreloadedQuery(
    graphql`
      query RootQuery($user: String!) {
        v3UserQuery(user: $user) {
          contextualPinImageUrls(spec: "222x") {
            height
            width
            url
          }
        }
      }
    `,
    props.prepared.rootQuery,
  );
  const { contextualPinImageUrls } = data;

  console.log(contextualPinImageUrls);

  return <div />;
}
```

In Relay v13, this fails when you run `yarn relay-compiler`

![image](https://user-images.githubusercontent.com/127199/148616322-0b330a5e-c0f0-46cb-aa9e-6928e5c0fc9f.png)

# Repro

https://github.com/christianvuerings/relay-v13-argument-scalars contains 2 directories with the exact same code but different relay versions:

* `relay-v12` => Relay v12
* `relay-v13` => Relay v13

## Steps
```
git clone https://github.com/christianvuerings/relay-v13-argument-scalars.git
cd relay-v13-argument-scalars
(cd relay-v12; yarn; yarn relay)
(cd relay-v13; yarn; yarn relay)
```

### Relay v12

```sh
$ cd relay-v12; yarn relay
$ yarn run relay-compiler --schema ./schema/schema.graphql --src ./src

Writing js
Unchanged: 1 files
✨  Done in 3.76s.
```

### Relay v13

```sh
$ cd relay-v13; yarn relay
$ yarn run relay-compiler --schema ./schema/schema.graphql --src ./src

querying files to compile...
[default] compiling...
[ERROR] ✖︎ Unsupported (user-defined) scalar type 'ImageSpec'

  src/Root.js:4:40
    3 │         v3UserQuery(user: $user) {
    4 │           contextualPinImageUrls(spec: "222x") {
      │                                        ^^^^^^
    5 │             height

[ERROR] Compilation failed.
[ERROR] Failed to build:
 - Validation errors:
 - Unsupported (user-defined) scalar type 'ImageSpec':src/Root.js:115:121
```

**Comment by josephsavona** [comment]
Thanks for the detailed report and repro. This is something we should support but missed since we don't use custom scalars much — we'll prioritize adding this in a point release.

This will likely require developers annotating (in the project config) what the corresponding input type is so we can perform basic validation (ie telling the compiler that `ImageSpec` should be provided using a `String` value). We could easily support custom scalars _without_ validation, but that isn't ideal either.

**Comment by christianvuerings** [comment]
> This is something we should support but missed since we don't use custom scalars much — we'll prioritize adding this in a point release.

@josephsavona thank you, really appreciate it.

> This will likely require developers annotating (in the project config) what the corresponding input type is so we can perform basic validation (ie telling the compiler that ImageSpec should be provided using a String value). We could easily support custom scalars without validation, but that isn't ideal either.

For that use case, do you think we can use the `customScalars` setting in `relay.config.js`?

```js
module.exports = {
  src: './src',
  schema: './schema/schema.graphql',
  customScalars: {
    ImageSpec: 'string',
  },
};
```

We already do this for all of our custom scalars since it improves the generated flow types.

**Comment by leoasis** [comment]
Worth noting that this fails only when setting a literal value on an input that has a custom scalar as the type. Declaring it as a variable and passing it at runtime works fine.

So in this example, this compiles fine with the new compiler:

```
query RootQuery($user: String!, $spec: ImageSpec) {
  v3UserQuery(user: $user) {
    contextualPinImageUrls(spec: $spec) {
      height
      width
      url
    }
  }
}
```

**Comment by Meemaw** [comment]
@alunyov How big of an effort is it to support this? This is our main blocker for upgrading to Relay 13/14 as it just breaks in too many places, and would require significant efforts to refactor.

**Comment by artola** [comment]
Same than for @Meemaw ... this produce a breaking change for us, it would be nice to have a config value to downgrade custom-type to `warning` in place of `error` or just skip them.

**Comment by Motoxpro** [comment]
Would love this so we could update to 14 :)

**Comment by christianvuerings** [comment]
@alunyov Thank you for the fix! Could we create a Relay 14.x release which includes the fix?
