### ISSUE TITLE
relay-compiler --validate option no longer available

### ISSUE THREAD

**Issue by jcolakk** [facebook/relay#3738]
Hi 👋  we used to run `relay-compiler --validate` in our CI, but its no longer available in v13. What should we use instead? 

It was really useful for us as it would catch when we forget to run `relay-compiler`

**Comment by alunyov** [comment]
Oh, I think we don't use this internally. We just look for unexpected changes in the source control.

Something like this:

```
git diff-index --quiet HEAD -- || echo >&2 "Unexpected Changes";
```

But, I think it make sense to add this `--validate` flag to the compiler.

**Comment by jcolakk** [comment]
That could work as well, I'll try to add something like that until `--validate` lands again. 
Btw thanks for the fast responses on the issues 👍

**Comment by jcolakk** [comment]
Btw is there any estimate when this could land?

**Comment by alunyov** [comment]
I don't think we have an estimate, we mostly focus on "bad" issues: incorrect output, invalid configs, something that completely prevents people from using the new version. The --validate is almost a "new" feature for the V13, but I agree that this is a regression compared to the JS version.

Also, as a wise man said: "Be the change you want to see in the world.".

**Comment by jcolakk** [comment]
Of course, completely agree. I was just wondering if there is some kind of roadmap where this would be included. Understandably, its not a high prio. 

> Also, as a wise man said: "Be the change you want to see in the world.".
I need some courage to dive into rust but I might try 👍
