### ISSUE TITLE
Relay Compiler v13: Providing a statically linked binary?

### ISSUE THREAD

**Issue by henkerik** [facebook/relay#3739]
Relay compiler v13 fails to run on our CI system:

```
/worker/build/f83b02af11d8b45f/root/node_modules/relay-compiler/linux-x64/relay: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

The `relay` executable requires a couple of shared libraries:

```
> objdump -p relay | grep NEEDED
  NEEDED               libssl.so.1.1
  NEEDED               libcrypto.so.1.1
  NEEDED               libgcc_s.so.1
  NEEDED               libpthread.so.0
  NEEDED               libm.so.6
  NEEDED               libdl.so.2
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2 
```

Since we are running our builds in a Bazel sandbox (with remote build execution) we can have no control over the CI runner, so we can't simply install the missing libraries. This would also make our build non-hermetic which is not something we want. A solution would be to provide self contained statically linked binaries instead. 

Related to: https://github.com/facebook/relay/issues/3725

**Comment by alunyov** [comment]
> A solution would be to provide self contained statically linked binaries instead.

Yes. Our build configuration is very simple at the moment:

https://github.com/facebook/relay/blob/main/.github/workflows/ci.yml#L121-L125

What should we change?

**Comment by alunyov** [comment]
Thanks for looking into this @ch1ffa!

This action https://github.com/marketplace/actions/rust-musl-builder-slim were not updated since 2019. Not sure if we should use that version.

> but for CI it requires a custom docker image

Can we add our own Dockerfile here and build with `--target x86_64-unknown-linux-musl`?

**Comment by ch1ffa** [comment]
@alunyov yeah, I think so. My personal preference is to have a dedicated repo with an action, so the main pipeline would be looking cleaner. But I can test both options and then we can choose.

**Comment by alunyov** [comment]
Hey @henkerik the fix by @ch1ffa just landed and available on NPM as `relay-compiler@main`. Can you verify if it fixes the issue for you?

Thank you!

**Comment by crubier** [comment]
For people running in this problem, if the latest npm version does not fix the problem, a dirty workaround using docker is:

```
docker run -v $(pwd):/mnt node:14 bash -c "cd /mnt && npm i -g relay-compiler && relay-compiler"
```

(Might need to adapt to your repo file structure, but you get the idea), worked for us.
