### ISSUE TITLE
Server request fails with undefined reasons

### ISSUE THREAD

**Issue by Aweary** [facebook/relay#375]
I have a really simple Relay app at the moment which fails with the error:

```js
Server request for query `RootQueryType` failed for the following reasons:

1. undefined

_markAsRejected	                @  relay.js:7313
_handleSubtractedQueryFailure	@  relay.js:7294
tryCallOne	                    @  relay.js:3340
(anonymous function)	        @  relay.js:3406
flush                           @  relay.js:8759
```

The query that is supposed to be submitted to my API is, according to the `_printedQuery` property:

```js
"query RootQueryType{property{...__RelayQueryFragment0nrk9vk}} fragment __RelayQueryFragment0nrk9vk on Property{propertyName,id}"
```

Which I've verified returns the expected results if I run the query directly against the server using `curl`.  My API is running on a different port so I'm using `Relay.injectNetworkLayer` to point Relay to the proper endpoint. I've noticed that, whenever I start my Relay application, my GraphQL API logs the `request.body` as an empty object, which says to me that its making the request but not with the right information.

Here are my files, as they pertain to the Relay app:

**app.js**

```js
import Property from './components/Property';
import AppHomeRoute from './routes/AppHomeRoute';

Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://localhost:3000/')
);

ReactDOM.render(
  <Relay.RootContainer
    Component={Property}
    route={new AppHomeRoute()}
  />,
  document.getElementById('root')
);

```

**components/Property.js**

```js

import 'babel/polyfill';
import '../../styles/main.css';

class Property extends React.Component {
    render() {
      return (
        <div>
          <h1> Working! </h1>
        </div>
      );
    }
}

export default Relay.createContainer(Property, {
  fragments: {
    property: () => Relay.QL`
      fragment on Property {
        propertyName,
        id
      }
    `
  }
});
```

**routes/AppHomeRoute.js**

```js

export default class extends Relay.Route {
  static queries = {
    property: () => Relay.QL`
       query RootQueryType {
         property
      }
    `
  };
  static routeName = 'PropertyRoute';
}

```

I'm hoping its just user error, but in any case it shouldn't be returning `undefined` as a reason.

**Comment by Aweary** [comment]
Looks like the issue was that Relay was setting the `Content-Type` header to `application/json` and my API was set to parse `application/graphql`. 

Should `application/graphql` be supported?

**Comment by fson** [comment]
@Aweary express-graphql supports both.
- `application/json` means the body is JSON, e.g.
```json
{"query": "{viewer{id}}", "variables": {}}
```
- `application/graphql` means the body is the query string itself, e.g.
```graphql
{viewer{id}}
```
The default network layer in Relay always uses `application/json`.

**Comment by josephsavona** [comment]
@fson beat me to it - Relay sends JSON, hence `application/json`.

**Comment by Aweary** [comment]
:+1:
