### ISSUE TITLE
Input Types generated as readonly in TypeScript with Relay 13

### ISSUE THREAD

**Issue by TassiloSinghammerVolue** [facebook/relay#3753]
Is it on purpose that with Relay 13 arrays in input types are now being generated as ReadonlyArray?
That's kind of cumbersome, as one especially wants to modify inputs like adding/removing filters etc.

**Comment by robrichard** [comment]
@TassiloSinghammerVolue see https://github.com/facebook/relay/pull/3740

**Comment by TassiloSinghammerVolue** [comment]
Thanks @robrichard I will close this one
