### ISSUE TITLE
405 (Method Not Allowed) in TodoMVC example

### ISSUE THREAD

**Issue by davidhq** [facebook/relay#377]
I get 

    http://localhost:3000/graphql Failed to load resource: the server responded with a status of 405 (Method Not Allowed)`

And the app looks like this:

![screen shot 2015-09-24 at 00 08 01](https://cloud.githubusercontent.com/assets/3899/10060309/5f29a81c-6250-11e5-9212-44f45bd471b7.png)

Tried in Chrome and Safari

**Comment by kassens** [comment]
When you use the browser developer tools, can you see what the request/response is from the server?

What node version and OS are you running?

**Comment by Aweary** [comment]
Sounds like its using CORS and `express-graphql` is [sending a 405 response to the `OPTIONS `call](https://github.com/graphql/express-graphql/issues/14)

**Comment by davidhq** [comment]
I just tried treasurehunt, same problem...

`node 4.1.0`

![screen shot 2015-09-24 at 00 23 12](https://cloud.githubusercontent.com/assets/3899/10060631/843393a0-6252-11e5-9847-31eca852b054.png)

**Comment by kassens** [comment]
The `[RWeb]` and `PAGE_LOADED` are not part of Relay. Sounds like you might have some extra layer that would trigger the problem @Aweary referenced?

**Comment by davidhq** [comment]
Not likely... RWeb is just a Chrome extension but here is the Safari error log:

![screen shot 2015-09-24 at 01 27 07](https://cloud.githubusercontent.com/assets/3899/10061697/7520d496-625b-11e5-9ba7-ea686284ad7c.png)

**Comment by Aweary** [comment]
I wasn't able to reproduce this on `4.0.0` or `4.1.1`, did you pull the source directly from this repository and did you make any changes at all? `express-graphql` doesn't support CORS, so the examples work around that by proxying the GraphQL path, but for some reason that doesn't seem to be working for you.

**Comment by davidhq** [comment]
I didn't do anything extra... I can ask a friend later today to check at his machine.. will report tomorrow if the same happens there

**Comment by davidhq** [comment]
The problem was that I had RethinkDB running on 8080 and GraphQL Server couldn't start on that port..

Maybe there should be error message in console if this happens...

thank you for you time

**Comment by davidhq** [comment]
I checked again and in case something is already on port 8080, there is still this message:

`GraphQL Server is now running on http://localhost:8080`

in console... should probably detect that and show error in red
