### ISSUE TITLE
[relay-compiler 13] thread panic instead of human-readable error

### ISSUE THREAD

**Issue by codebling** [facebook/relay#3770]
Currently a few errors will result in the same (rather opaque) message in Relay Compiler 13. 

| Relay Compiler 12 Error | Relay Compiler 13.0.1 Error |
| --- | --- |
| Parse error: Error: RelayFindGraphQLTags: Operation names in graphql tags must be prefixed with the module name and end in "Mutation", "Query", or "Subscription". Got \`ExampleQuery\` in module \`query\`. in "query.jsx" | thread 'main' panicked at 'no entry found for key', crates/relay-compiler/src/build_project/build_schema.rs:37:17 |
| `Unknown field 'a' on type 'Query'.` (with dump of actual query) | thread 'main' panicked at 'no entry found for key', crates/relay-compiler/src/build_project/build_schema.rs:37:17 |

Let me know if you need a sample repo to reproduce or need any other info.

**Comment by alunyov** [comment]
Hey @codebling it's probably something wrong with the configs. Can you share your config file, or if you have a simple repro - this would be even better?

**Comment by codebling** [comment]
Sure! Sample repo [here](https://github.com/codebling/relay-compiler-test-repo). I'm running the compiler with `npx relay-compiler@13.0.1`

**Comment by codebling** [comment]
Don't think this will change anything, since it's the same stack trace as #3647, but for completeness,
```
thread 'main' panicked at 'no entry found for key', crates/relay-compiler/src/build_project/build_schema.rs:37:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_display
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:64:5
   3: core::option::expect_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:1638:5
   4: relay_compiler::build_project::build_schema::build_schema
   5: relay_compiler::build_project::build_project
   6: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume
   7: rayon::iter::plumbing::Folder::consume_iter
   8: rayon::iter::plumbing::bridge_producer_consumer::helper
   9: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
  10: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: tokio::park::thread::CachedParkThread::block_on
  14: tokio::runtime::thread_pool::ThreadPool::block_on
  15: tokio::runtime::Runtime::block_on
  16: relay::main
```

**Comment by alunyov** [comment]
Oh, I think it's a duplicate of this: https://github.com/facebook/relay/issues/3772#issuecomment-1019665528

**Comment by codebling** [comment]
It's totally that. Sorry for the misleading description. I'll edit it
