### ISSUE TITLE
[relay-compiler 13] thread panic when using .gql extension schema file

### ISSUE THREAD

**Issue by botsvik** [facebook/relay#3772]
Running `relay-compiler` with schema configured with `.gql` file produces:
```
thread 'main' panicked at 'no entry found for key', crates/relay-compiler/src/build_project/build_schema.rs:37:17
```

`relay.config.js`
```js
module.exports = {
  src: "./src",
  schema: "./src/schema.gql",
  exclude: ["**/node_modules/**", "**/__mocks__/**", "**/__generated__/**"],
  language: "typescript",
};
```

**Comment by alunyov** [comment]
Yeah, we do not currently support `.gql` file extensions. As a workaround, can you try changing it to `schema.graphql`?

**Comment by botsvik** [comment]
@alunyov Sure I did, thanks. Just created the issue. Could be helpful for others with same issue.
