### ISSUE TITLE
RelayOSSNodeInterface: Expected root field to be a single non-array result

### ISSUE THREAD

**Issue by Aweary** [facebook/relay#378]
I have a `GraphQL` server running that exposes `property` as a root field, with the following schema:

```js
export const property = {
  type: new GraphQLList(propertyType),
  args: {
    id: {
      description: 'ID of the property',
      type: new GraphQLList(GraphQLInt)
    }
  },
  resolve: resolver(Property)
};
```

It should return a list of `propertyType` items which have properties such as `propertyName`, `propertyDescription`, etc. 

```
const query = new GraphQLObjectType({
  name: 'RootQueryType',
  fields: () => fields
});
```

`property` is a property of the returned `fields` object and everything works fine with direct queries. Now I also have a Relay app with the route:

```js
export default class extends Relay.Route {
  static queries = {
    property: () => Relay.QL`query { property }`
  };
  static routeName = 'PropertyRoute';
}
```

Which is used by the component

```js
class Property extends React.Component {
    render() {
      console.log(this.props);
      return (
        <div>
          <ul>
          <p> I dont do anything yet </p>
          </ul>
        </div>
      );
    }
  }

export default Relay.createContainer(Property, {
  fragments: {
    property: () => Relay.QL`
      fragment on Property {
        propertyName,
        id
      }
    `
  }
});
```

The issue is, I'm getting the error:

```js
Invariant Violation: RelayOSSNodeInterface: Expected payload for root field `property` to be a single non-array result, instead received an array with 300 results.
```

300 is the right number and what I want is a `property` property returned with an array of objects with the `propertyName` and `id`. I thought https://github.com/facebook/relay/pull/361 would fix it, but I've pulled and built the most current version of Relay from this repository and the issue still occurs.

**Comment by josephsavona** [comment]
This relates to #112

**Comment by Aweary** [comment]
Is there a workaround currently, or a better (recommended) way to format my schema? I guess using a root field like `viewer` with `property` as a field would resolve this then?

**Comment by Aweary** [comment]
:+1: closing
