### ISSUE TITLE
[v13.1.0] file/query name change of behaviour. 

### ISSUE THREAD

**Issue by matclayton** [facebook/relay#3791]
# Creating issues for Relay
```
[ERROR] ✖︎ Queries in graphql tags must start with the module name ('index') and end with 'Query'. Got 'LiveUserCardQuery' instead.

  www/components/UserCards/LiveUserCard/index.stories.js:33:11
   32 │ 
   33 │     query LiveUserCardQuery($id: ID!) @relay_test_operation {
      │           ^^^^^^^^^^^^^^^^^
   34 │         liveStream(id: $id) {
```

Sorry is this is a question/mistake and not a "bug" but we use relay in storybook, and would typically name the queries as above. In v11.0.2 this didn't cause us any issues, however we're now seeing lots of this issue repeating,

**Comment by radix** [comment]
the problem here is that it's not handling files like "index.stories.js". It knows how to deal with "index.js". The same thing happened to me in an "index.spec.js" file.

**Comment by matclayton** [comment]
I believe this is fixed. We’re no longer seeing the issue on recent builds. V14.1.0
