### ISSUE TITLE
[V13] UTF-8 with BOM encoded schema file causes 'unsupported character' compiler error

### ISSUE THREAD

**Issue by tobias-tengler** [facebook/relay#3798]
Since I've upgraded all my `relay` packages to v13, I've been getting the following error when running the `relay-compiler`:

![image](https://user-images.githubusercontent.com/45513122/154430783-6c995320-6995-4398-b11e-951a24f4def0.png)

The configuration in my `package.json` file is the following:

```json
"relay": {
    "language": "typescript",
    "src": "./src",
    "schema": "./src/schema.graphql",
    "exclude": [
      "**/node_modules/**",
      "**/__mocks__/**",
      "**/__generated__/**"
    ],
    "artifactDirectory": "./src/__generated__"
  },
```

I have also setup the `babel-plugin-relay` as instructed with the `artifactDirectory`.

How would I go about debugging this? I tried to find whether the compiler has a verbose flag that would help me diagnose the issue, but I haven't been successful.

**Comment by alunyov** [comment]
Hi @tobias-tengler thanks for the report. There's probably something in your source files that our parser could not recognize.

I think you can use `--output` flag to enable verbose logging.

https://github.com/facebook/relay/blob/427c01b0eac58a2a9dec17b9706c66dc290b4050/packages/relay-compiler/README.md?plain=1#L126-L127

If you have a smaller repro, it would help identify and fix the problem.

**Comment by alunyov** [comment]
> Could the issue maybe be related to styled-components?

Probably not, I just run compiler with styled-components example. And everything seem to work fine there. 

> but I'll try to create a smaller repro.

Thank you!

**Comment by NicolaBizzoca** [comment]
Hi,
We're experiencing the same, and there using ts + styled components
Is there a way to debug this?

**Comment by tobias-tengler** [comment]
@alunyov Sorry it took so long, but I was busy with other stuff and we just stayed on v12 for the moment.
I've created a repository containing a stripped-down version of our application that manages to reproduce the bug when running `yarn relay`: https://github.com/tobias-tengler/relay-rust-compiler-unsupported-character-reproduction
Something interesting I've noted is that the issue also occurs, if now `graphql` annotated literals are present. I've thought that maybe the custom defer / stream directives in our schema might be a problem, but commenting them didn't solve the issue.

**Comment by tobias-tengler** [comment]
You can even replicate this with a fresh `create-react-app` project

1. `yarn create react-app test-app --template typescript`
2. `yarn add react-relay`
3. `yarn add --dev relay-compiler`
4. Add the script to `package.json`
```json
"scripts": {
  "relay": "relay-compiler"
}
```
5. Place a `schema.graphql` file in the `./src` directory
```graphql
schema {
  query: Query
}

type Query {
  test: String
}
```
6. Add relay-compiler config to `package.json`
```json
"relay": {
  "language": "typescript",
  "src": "./src",
  "schema": "./src/schema.graphql",
  "exclude": [
    "**/node_modules/**",
    "**/__mocks__/**",
    "**/__generated__/**"
  ],
  "artifactDirectory": "./src/__generated__"
}
```
7. Execute the compiler and observe the described issue.

There are not `graphql` template literals in the project at this point and the babel-plugin has not been setup, but I think this shouldn't be an issue. Since with create-react-app you would use the babel macro probably.

So this should affect any new person trying out relay in this manner, right?

**Comment by tobias-tengler** [comment]
I found out what the issue is. The issue is that the `schema.graphql` file was saved using the `UTF-8 with BOM` encoding. Switching to `UTF-8` resolves the compiler panic. :)

I'm not closing this for now, since I feel like the compiler should be able to handle this.
