### ISSUE TITLE
relay-compiler v13: Linux-ARM platform support

### ISSUE THREAD

**Issue by atatarenko** [facebook/relay#3799]
Hello relay team! Thank you for all the effort you've been putting into the relay!

I have a question (or even a feature request) but let me quickly describe the context.

My laptop is on based apple m1 platform, at the same my team and I prefer to develop in docker containers.
It means that my usual platform is linux-arm64 which is not supported among other platforms listed below:
https://github.com/facebook/relay/blob/427c01b0eac58a2a9dec17b9706c66dc290b4050/packages/relay-compiler/index.js#L16-L26

Now I have to run the new relay-compiler in a docker container forcing the platform for it this way `platform: linux/x86_64` which doesn't bring any benefits of node -> rust migration when it comes to speed. And actually brings another layer of virtualization to the whole app. Not that bad but not perfect too.

Do you have any plans regarding linux-arm64 support for the new compiler?

**Comment by alunyov** [comment]
Thanks for suggestion, I think we could add support for this here:

https://github.com/facebook/relay/blob/427c01b0eac58a2a9dec17b9706c66dc290b4050/.github/workflows/ci.yml#L83-L101

The downsides:
-  it will decrease the CI time (probably fine)
-  it will increase the npm package size, as we're uploading all artifacts for all platforms there. 
 
There is a PR to add platform-specific compilers as optional dependencies, but this approach also has downsides (as optional dependencies may be disabled in some cases).

I suggest keeping this issue open for now, if more people will want this, we can add support for this.

**Comment by ro-savage** [comment]
@alunyov - This is certainly very important - every new macbook is going to be arm-based. Given a large percentage of developers use macs - this issue is only going to increase.

As our organisation about 80% of developers are now on M1 Macbooks and would be unable to do builds using Relay v13.

**Comment by wasd171** [comment]
@alunyov you have added a "help wanted" label. How exactly could the community help? This issue is slowing down our development, I'd be willing to invest my time to fix it

**Comment by alunyov** [comment]
@wasd171 something similar to this PR: https://github.com/facebook/relay/pull/3667 - where we need to update CI to include a new target, also update the JS part of the compiler to resolve the correct binary.

**Comment by wasd171** [comment]
@alunyov I have created a PR https://github.com/facebook/relay/pull/3882 that addresses this issue

**Comment by TrySound** [comment]
Does it mean relay package size will be ~10-20MB bigger?

**Comment by wasd171** [comment]
@TrySound additional binary is ~5 MB

**Comment by bencoveneyttl** [comment]
Looks like the fix was shipped in https://github.com/facebook/relay/releases/tag/v14.0.0 and this can be closed.
