### ISSUE TITLE
pageInfo does not get pulled in when edges are only included via fragment

### ISSUE THREAD

**Issue by taion** [facebook/relay#381]
This looks like a bug in babel-relay-plugin. The logic here: https://github.com/facebook/relay/blob/615787490db3bd62b15e8bf22d9c46b2d59bbf73/scripts/babel-relay-plugin/src/GraphQLPrinter.js#L503 for pulling in `pageInfo` on connections doesn't seem to work when the connection `edges` are only pulled in via a fragment.

For example, in the current (non-routing) TodoMVC example, if you remove these lines: https://github.com/facebook/relay/blob/58e45dbb9fd08215884597171ce072551f344c06/examples/todo/js/components/TodoApp.js#L64-L68 (the data fetched there isn't actually used by the `TodoApp` component at all, so naively that part of the GraphQL query seems vestigial), you can see that the GraphQL query sent to the server does not request `pageInfo`, and correspondingly does not request `hasNextPage` or `hasPreviousPage`, and consequently, Relay assumes that those fields are false, and pagination doesn't work (or wouldn't work, in more elaborate cases that involve pagination).

**Comment by josephsavona** [comment]
Good find! Fix it? ;-)

**Comment by josephsavona** [comment]
Re the fix: it seems reasonable to always add `pageInfo` on a connection field if it isn't already present **and** one of the following applies:
- the `edges` field is present
- a fragment reference is present (which is likely enough to contain `edges` that we should fetch `pageInfo`).

Put another way, the only time we shouldn't add `pageInfo` is if only connection-level fields are being fetched (ex: `storiesConnection { totalCount }` doesn't need page info)

**Comment by taion** [comment]
I have literally never looked at a Babel plugin before. But fine, challenge accepted.

I would think the right way to handle this would just be to extend the `pageInfo` check to cases where a fragment is on a connection type, though, rather than when a field is on a connection. Is there some reason why this would not be a good approach?

**Comment by kassens** [comment]
We're adding the `pageInfo` during the static transform of the code [here in GraphQLPrinter](https://github.com/facebook/relay/blob/58e45dbb9fd08215884597171ce072551f344c06/scripts/babel-relay-plugin/src/GraphQLPrinter.js#L502-L504). During the transform, we can only look at the current file / GraphQL fragment we're transforming. This means we can't inspect what's inside fragments.

When you want to work on the transform, it will be helpful to create a new test by adding a fixture to [this directory](https://github.com/facebook/relay/tree/58e45dbb9fd08215884597171ce072551f344c06/scripts/babel-relay-plugin/src/__fixtures__).

We could potentially look at this metadata when we generate the query during runtime, but I'm not sure what the implications are of that. I think the heuristic that @josephsavona suggested is pretty good. (How likely is it that you have a fragment just to display the count?)

**Comment by taion** [comment]
@kassens Probably easier just to demonstrate with code what I mean - see https://github.com/facebook/relay/pull/385

**Comment by taion** [comment]
Fixed by #385.
