### ISSUE TITLE
Partial data returning null (despite only errors being field errors)

### ISSUE THREAD

**Issue by alex-statsig** [facebook/relay#3813]
useLazyLoadQuery seems to throw an Error rejecting the entire query, despite the network returning successful partial data (ex. `{data: {viewer: {a: true, b: null}}}`) with a list of errors only for certain fields (ex. with path: `['data', 'viewer', 'b']`).  I also tried manually issuing a `fetchQuery()`, but this also returns `data: null`. I'm not sure when exactly this behavior changed, but it seems to be after relay 13 (but downgrading to confirm this is non-trivial).

Was there an intentional change around this? Or is this something wrong with my configuration?

The error is:
```
RRNLRequestError: Relay request for `myQuery` failed by the following reasons:

(... errors for each field listed out)
```

**Comment by zth** [comment]
What is `RRNLRequestError`, where's that coming from?

**Comment by alex-statsig** [comment]
> RRNLRequestError

I think it comes from react-relay-network-layer, so maybe the issue is there. Although at the end of the middleware chain it seemed to have successfully gotten partial data with field errors.

**Comment by alex-statsig** [comment]
Seems like this is an artifact of react-relay-network-layer maybe, adding a middleware that removes the errors field if there's any data fixes it. I thought I had read a post implying that would be the default, but I was mistaken. Thanks!
