### ISSUE TITLE
Cannot install react-relay with React 18

### ISSUE THREAD

**Issue by wonu** [facebook/relay#3820]
I've read that [Relay has full support for React 18](https://github.com/reactwg/react-18/discussions/113#discussion-3687159) as below:

> <h3>Relay</h3>
>
> Suspense was developed in close cooperation with the Relay team, so Relay has full support for React 18 and concurrent features, including Suspense transitions. https://relay.dev/docs/guided-tour/rendering/loading-states/
<br>

But I couldn't install react-relay package with React 18 RC because of [peerDependencies](https://github.com/facebook/relay/blob/main/packages/react-relay/package.json#L26):
```json
"peerDependencies": {
  "react": "^16.9.0 || ^17"
}
```
<br>

What am I missing? Is that an intended result?

**Comment by josephsavona** [comment]
Looks like we need a version bump here

**Comment by wonu** [comment]
@josephsavona Is the update scheduled?

**Comment by voideanvalue** [comment]
@wonu thanks for reporting. I'll update the peerDependencies (#3829) and publish a new version of react-relay on npm this week.

**Comment by voideanvalue** [comment]
https://github.com/facebook/relay/releases/tag/v13.2.0 is now published
