### ISSUE TITLE
[v13] Compiler expects no whitespace in graphql template tagged literal

### ISSUE THREAD

**Issue by cliedeman** [facebook/relay#3831]
# Creating issues for Relay

The following graphql tagged template literals are not detected by the compiler

```graphql
graphql `
  fragment Test on User {
    name
  }
`;

graphql
`
  fragment Test on User {
    name
  }
`;
```

The offending line is https://github.com/facebook/relay/blob/main/compiler/crates/extract-graphql/src/lib.rs#L97

I only stumbled onto this issue due to the deafult dprint formatting.

fix for dprint:
```json
  "typescript": {
    "taggedTemplate.spaceBeforeLiteral": false
  },
```

See test case #3828

Possibly related #3786

**Comment by voideanvalue** [comment]
Closing as bb7c65fa326889511d85adaf26f2565ba053b0ed addressed this. We'll publish a new release that contains this fix soon.
