### ISSUE TITLE
persistConfig with a `file` option is non-deterministic

### ISSUE THREAD

**Issue by hayes** [facebook/relay#3834]
When creating a relay config like:
```js
module.exports = {
  ...
  persistConfig: {
    file: './operations.json'
  }
```

The entries in the generated file will be re-ordered on every run.   This makes it hard to check the generated file into source control.  Would be great if the entries were sorted alphabetically by id or something.

**Comment by voideanvalue** [comment]
Thanks @hayes for reporting the issue and also sending a pull request to fix 🎉
