### ISSUE TITLE
Add authentication on Subscriptions

### ISSUE THREAD

**Issue by BiancaArtola** [facebook/relay#3837]
I am using Relay and `subscriptions-transport-ws` for calling subscriptions on my front-end. I know that `subscriptions-transport-ws` is a legacy library but is the only one that works with the back-end subprotocol.

Everything was working fine until the back-end requires adding authentication on the subscription. I really don't know how to add it to the subscriptions and I did not find any documentation about this. Can you help me with that? I'll provide my RelayEnvironment.

```
const subscriptionClient = new SubscriptionClient(
  `wss://localhost:XXXX/graphql`,
  {
    reconnect: true,
  }
);

const subscribe = (
  request: RequestParameters,
  variables: Variables
): Observable<any> => {
  if (!request.text) throw new Error("Request text cannot be empty");

  const subscribeObservable = subscriptionClient.request({
    query: request.text,
    operationName: request.name,
    variables
  });

  //@ts-ignore
  return Observable.from(subscribeObservable);
};

....

export default new Environment({
  network: Network.create(fetchRelay, subscribe),
  store: new Store(new RecordSource(), {
    queryCacheExpirationTime: 2 * 60 * 1000,
  }),
  handlerProvider,
});
```

**Comment by giautm** [comment]
You can provide a `connectionParams` function to send params to server when connection is initialation. The structure/data is dependent on your server.
```js
const subscriptionClient = new SubscriptionClient(SUBSCRIBE_URL, {
  reconnect: true,
  connectionParams: async () => {
    const token = (await AsyncStorage.getItem('JWT_TOKEN')) ?? ''

    return { token, hello: 'world' }
  },
})
```

**Comment by BiancaArtola** [comment]
Thanks for answering @giautm! I tried what you suggested but I continue having the following issue:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/21174759/158380223-9720f98d-92c4-4116-bcf2-5e7f5e0520ed.png">

Any idea what could it be?

**Comment by giautm** [comment]
As I said, the way in which the server authenticates the WebSocket connection is up to you. If there's no specification document on how the server authenticates the connection, unfortunately, I can't help.

**Comment by BiancaArtola** [comment]
I need to add the Authorization header on the subscription. In the way that you mentioned, I could add the Authorization as a part of the payload, but not in the header. Is there a chance to add it to the Header? I will post my Postman screen

<img width="623" alt="image" src="https://user-images.githubusercontent.com/21174759/158386200-e61ffd2a-792a-4ba3-9bae-2ee5f403387b.png">

Thanks in advance @giautm 👏🏽

**Comment by BiancaArtola** [comment]
Thanks for all the information, it was really useful for us! I was a little blocked with this and now I understand my options 😄

**Comment by voideanvalue** [comment]
Handling authentication appropriately is intentionally designed to be the sole responsibility of the Network interface implementation that you provide to Relay. The information @giautm provided (thanks!) puts you on the right path towards figuring this out for your implementation.

I'm going to close this because I don't think there's any further action required here.
