### ISSUE TITLE
Paginated connection plus added edge from mutation

### ISSUE THREAD

**Issue by grydstedt** [facebook/relay#384]
I'm having trouble figuring out how to accomplish what seems to be a pretty standard pattern when doing a `RANGE_ADD` mutation.

Say on page load I pull in and render a connection `messages` with `first: 10` pagination. I now do a `AddMessageMutation` which does a `prepend` to the that same connection. Since the connection is paginated by `first: 10` the last item of the connection is now gone to give room for my new edge and is thus removed from rendering. I can of course add +1 to `first` on the `onSuccess` of the mutation, but this  often leaves a weird flickering effect of removing and reinserting the edge at the end.

This problem seem to get even more difficult if I want to do an optimistic update to the connection since there is no `onOptimistic` callback. 

Since this seems like a pretty common pattern I figured I'd ask if I'm approaching this the wrong way.

**Comment by grydstedt** [comment]
If this is better suited for StackOverflow, I can post it there as well.

**Comment by kassens** [comment]
Yes, since there's no direct bug or concrete missing feature here, let's move this to StackOverflow. This will help us keep Github for issues that can be worked on and also better SEO for the questions so others can find them on StackOverflow. Thanks :)

PS: please post a link here in case someone else should find this page.

**Comment by grydstedt** [comment]
https://stackoverflow.com/questions/32776189/paginated-connection-plus-added-edge-from-mutation

**Comment by grydstedt** [comment]
Anyone available to answer this one?
