### ISSUE TITLE
Allow disabling "%future added value" enum type addition

### ISSUE THREAD

**Issue by jasonkuhrt** [facebook/relay#3857]
This is a follow up to https://github.com/facebook/relay/issues/2351.

Although in my case I am working with TypeScript but the concept/problem is the same.

I understand the rationale laid out there, the GraphQL API can extend thee enum at any time. It is a clever idea to extend the enum type statically to help the client keep this in mind.

That said, when the client/server are tightly coupled it might not be the desired behaviour. For example in our case, a Nextjs app.

I would like a way to opt out of this behaviour of the replay compiler.

Meanwhile we're resorting to type casting to undo what Relay generated which is easy to do but also a hack.

**Comment by mrtnzlml** [comment]
@jasonkuhrt Are you on the latest Relay Compiler? You can disable this via `no_future_proof_enums`, see: https://github.com/facebook/relay/blob/7a27722dc2221eee6e163ab876a33bae1f7bdc02/compiler/crates/relay-compiler/src/config.rs#L597-L601

**Comment by jasonkuhrt** [comment]
@mrtnzlml Thanks will check that out. Did I miss something in the docs about this?

**Comment by jasonkuhrt** [comment]
Found it :)

https://github.com/facebook/relay/tree/main/packages/relay-compiler#configuration

**Comment by Lalitha-Iyer** [comment]
Does this work on a multi-project config, it doesn't work when I specify it t under a project like so
```
{
    projects: {
        foo: {
            language: 'typescript',
            noFutureProofEnums: true,
            schema: 'schemaFoo.graphql',
        },
    },
}
``` 
Error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("The config file cannot be parsed as a multi-project config file due to:\n- Error(\"unknown field `noFutureProofEnums`
```

**Comment by Amorim33** [comment]
> Does this work on a multi-project config, it doesn't work when I specify it t under a project or at the top level like so
> 
> ```
> {
>     projects: {
>         foo: {
>             language: 'typescript',
>             noFutureProofEnums: true,
>             schema: 'schemaFoo.graphql',
>         },
>     },
> }
> ```
> 
> ```
> {
>     noFutureProofEnums: true,
>     projects: {
>         foo: {
>             language: 'typescript',
>             schema: 'tools/@tvui/graphql-compiler/schema-prod.graphql',
>         },
>     },
> }
> ```
> 
> Error
> 
> ```
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("The config file cannot be parsed as a multi-project config file due to:\n- Error(\"unknown field `noFutureProofEnums`
> ```

Any updates?
I am facing the same problem
