### ISSUE TITLE
relay examples `npm run-script update-schema` is broken by copyright headers

### ISSUE THREAD

**Issue by happypoulp** [facebook/relay#387]
Hi,

It seems that since https://github.com/facebook/relay/commit/fb2720516ccadf1d696299780084296a7966288e we can longer run `npm run-script update-schema`. The copyright headers at top of script files (`todo/scripts/updateSchema.js`, `star-wars/scripts/updateSchema.js`, `relay-treasurehunt/scripts/updateSchema.js`) are preventing babel-node from correctly parsing the shebang interpreter directive. I noticed it on the treaasure-hunt example but I guess that this issue is present on all examples.

**Comment by wincent** [comment]
Thanks for noticing this! Would you like to submit a PR to fix?

**Comment by happypoulp** [comment]
I'd be glad to! But to be honest I am not sure about what's the correct fix for this issue.

I could move headers below the shebang directive but I don't know if this is correct since those headers were added automatically via `arc lint --lintall --apply-patches static_upstream/relay/**/*.js` according to fb2720516ccadf1d696299780084296a7966288e. So I guess that there are chances that a manual fix would be overwritten the next time this command is run. Then the best way would be to fix the command above and only after that, to manually update those scripts (and I don't know where/when this command is actually run). Am I over-thinking here?

**Comment by wincent** [comment]
I believe the linter is smart enough to look past the shebang line (and it it isn't, we'll fix it).
