### ISSUE TITLE
relay + nextjs cannout build because do not found the generated folder

### ISSUE THREAD

**Issue by daniloab** [facebook/relay#3879]
I'm trying to replicate this https://github.com/relayjs/relay-examples/tree/main/data-driven-dependencies example of nextjs with my nextjs repository.

The problem is when I try to run the project after finished the initial configs.

- [x] it is complaining about not found the generated folder
![Screen Shot 2022-04-16 at 17 07 42](https://user-images.githubusercontent.com/19939822/163689899-a46cabc5-e9a8-4080-8b60-857884964316.png)

I create a tiny repo replicating this issue to make it easier to debug and understand.
- https://github.com/daniloab/relay-13-nextjs

Also, probably this issue could be related to this one https://github.com/facebook/relay/issues/3272. but, there are seen more related to windows, and I'm developing on a mac os m1.

**Comment by alunyov** [comment]
I think you need to add `language: "typescript"` to the Next.js config here: https://github.com/daniloab/relay-13-nextjs/blob/2ee86ae306ba7c93dee62fb0136b3401f0f7f401/next.config.js#L5-L8

**Comment by daniloab** [comment]
> I think you need to add `language: "typescript"` to the Next.js config here: https://github.com/daniloab/relay-13-nextjs/blob/2ee86ae306ba7c93dee62fb0136b3401f0f7f401/next.config.js#L5-L8

You are right. It was missing. It probably doesn't have `language: typescript` in relay-examples data-driven-dependencies because it's js, right?

**Comment by alunyov** [comment]
>  It probably doesn't have language: typescript in relay-examples data-driven-dependencies because it's js, right?

yeah, it uses default for this... (which is still `flow`, that generate valid JS)

**Comment by daniloab** [comment]
Cool, I will close it since it was missing the language property only, thanks. I still with some doubts about the example data-drive-dependencies but I'm sharing them in the GraphQL discord on channel relay.
