### ISSUE TITLE
Q: Can I use react-relay isomorphically? 

### ISSUE THREAD

**Issue by mikhail-riabokon** [facebook/relay#390]
I found [this](https://gist.github.com/wincent/598fa75e22bdfa44cf47#does-relay-support-isomorphic-js) answer, but then I'm trying use react-relay on the server I got an error ```self is not defined```, this error occurs because ```fetch``` library, which used in relay, [is not isomorphic](https://github.com/github/fetch/issues/184#issuecomment-126523046).

**Comment by Gregoor** [comment]
Probably, though I have not yet tried it. I think the only thing that currently depends on the browser is the default network layer, but you can easily swap it when you're on the server: https://facebook.github.io/relay/docs/guides-network-layer.html#content

Though you should probably just check these issues:
https://github.com/facebook/relay/issues/36
https://github.com/facebook/relay/issues/136

**Comment by mikhail-riabokon** [comment]
@Gregoor thank you for quick answer, I will try, and share my result in success case.

**Comment by mikhail-riabokon** [comment]
[This comment](https://github.com/facebook/relay/issues/136#issuecomment-142681224) shows how it can be fixed, but only on local level. So this can not be solid solution.

**Comment by kassens** [comment]
Thanks for your interest!

#136 covers the remaining issues to make this happen. Internally, we already server render some Relay pages, so this can definitely be done :smile:

**Comment by mikhail-riabokon** [comment]
@kassens Hi,

How did you do that? If it's not a secret ) 

I have create [repo](https://github.com/mikhail-riabokon/relay-server-rendering) where I am trying to run Relay + GraphQL on server, but I still have error, which have not resolved yet. In case if you have time and interest, could you have a look on it and write that I did wrong?

Thank you in advance.

**Comment by josephsavona** [comment]
@mikhail-riabokon There's more discussion about server rendering with Relay in #136
