### ISSUE TITLE
[VSCode] Relay Language Server failed to start

### ISSUE THREAD

**Issue by petrbela** [facebook/relay#3907]
Hi!

I'm not sure if the VSCode extension is ready to roll yet but when I installed the pre-release version, it doesn't work. I have a simple Next.js/Relay project with `relay.config.js` in the root.

```
Starting the Relay GraphQL extension...
Using relay binary: .../node_modules/relay-compiler/macos-arm64/relay
[ERROR] Failed to read config file `lsp`.
[Error - 3:29:42 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by kejistan** [comment]
The lsp command isn’t in the current release version (13.2.0).

**Comment by captbaritone** [comment]
Sorry for the confusion. We're working on getting a release out that includes the LSP feature. The VSCode extension is still in pre-release.

cc @tbezman

**Comment by captbaritone** [comment]
I've released a new (pre-release) version of the extension  (0.0.5) which is compatible with the pre-release compiler version. You should be able to trial the extension by upgrading to (0.0.5) and upgrading to a version of the compiler like `relay-compiler@0.0.0-main-9c14d82f`.

**Comment by petrbela** [comment]
The VSCode extension worked for a while but now it fails to start the language server, getting `Relay LSP client connection got closed unexpectedly.` with the following output:

```
Using relay binary: [dir]/node_modules/relay-compiler/macos-arm64/relay
Starting the Relay Langauge Server with these options: {"options":{"cwd":"[dir]"},"command":"[dir]/node_modules/relay-compiler/macos-arm64/relay","args":["lsp","--output=debug"]}
```

If I run it directly in terminal, I get slightly more info:

```
$ ./node_modules/relay-compiler/macos-arm64/relay lsp --output=debug relay
.config.js 
[DEBUG] Initialized stdio transport layer

[ERROR] Unable to run the relay language server. Error details: 
Relay LSP unexpectedly terminated: ProtocolError(ProtocolError("expected initialize request, got Err(RecvError)"))
```

Any idea what might be causing this? I'm using v14.1.0 of all the packages.

**Comment by tbezman** [comment]
@petrbela Could you set `relay.lspOutputLevel` to `debug` in your `settings.json` and restart?

I'm specifically interested in seeing this output window "Relay LSP Logs"
<img width="885" alt="image" src="https://user-images.githubusercontent.com/6754223/183539325-360574e2-a82f-482d-a4f3-3fb7060aa41f.png">

**Comment by tbezman** [comment]
Those logs would be tremendously helpful

**Comment by petrbela** [comment]
Oh that's actually helpful, didn't realize LSP had separate output...

```
thread 'main' panicked at 'failed to execute process. Make sure you have Node installed.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/runner/work/relay/relay/compiler/crates/js-config-loader/src/loader.rs:68:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 8:04:52 AM] Connection to server got closed. Server will not be restarted.
```

...which is the problem already discussed at https://github.com/facebook/relay/issues/3975#issuecomment-1162463126

I'll close this issue to avoid duplicates.
