### ISSUE TITLE
Cache not recognizing user by ID

### ISSUE THREAD

**Issue by matthewoates** [facebook/relay#3921]
## Reporting issues with Relay

On the latest version of react and react-relay, if I have this query cached:
```
# user with ID "foo"
viewer { id name }
```

When I try to make this query, the cache is not used the first time. It doesn't seem to recognize that this is the viewer is this exact user.
```
user(id: "foo") { id name }
```

`user`'s `id` input is of type `ID!`.

But the cache is used if I instead query for the user in the same way as I did before:
```
viewer { id name }
```

It seems that Relay isn't noticing that the `user` with the `viewer`'s ID are the same. I notice this same issue with different entities in the graph. I have not implemented a node interface, and haven't found any documentation mentioning that for relay modern. I thought that the node interface was no longer needed (or even used) by relay modern.

How can I get these resources to be recognized as the same entity?

**Comment by kejistan** [comment]
You can add a [missingFieldHandler](https://relay.dev/docs/guided-tour/reusing-cached-data/filling-in-missing-data/) to your relay environment:

```js
import {ROOT_TYPE} from 'relay-runtime';

new Environment({
  // other config options omitted
  missingFieldHandlers: [
    {
      handle(field, record, args) {
        // `node()` should always result in the record with the given `id`.
        // This code will cause relay to look for the record in the cache
        // when it hasn't been fetched via `node()` previously.
        if (
          record != null &&
          record.__typename === ROOT_TYPE &&
          field.name === 'node'
        ) {
          return args.id;
        }
      },
      kind: 'linked',
    },
  ],
});
```

**Comment by matthewoates** [comment]
Awesome, that did the trick. Maybe it's just me, but I think this documentation could use more affordance. This seems like sensible default behavior to me.
