### ISSUE TITLE
Relay VSCode Extension v0.0.7 does not support Relay v14.0.0

### ISSUE THREAD

**Issue by wongmjane** [facebook/relay#3957]
Congrats and thank you all for the v14 release!

It looks like the VSCode Extension has not been updated to support the latest Relay stable version of v14.0.0

Got this error in VS Code (extension version: v0.0.7):
>The installed version of the Relay Compiler is version: '14.0.0'. We found this version in the package.json at the following path: [path]/node_modules/relay-compiler/macos-arm64/relay This version of the extension supports the following semver range: '>=13.3.x <14'. Please update your extension / relay-compiler to accommodate the version requirements.

**Comment by tslater** [comment]
I tried downgrading to 13.3.x, but unless I'm mistaken, there is no 13.3.x, so the semver range is impossible to satisfy?

**Comment by captbaritone** [comment]
Sorry for the bad experience. I've released version 1.0.1 of the VSCode extension with the fix for this.
