### ISSUE TITLE
Updating PageInfo cursor manually does not allow new edges to be added to a connection

### ISSUE THREAD

**Issue by brijeshb42** [facebook/relay#3958]
I am using Relay for chat use case where, when a conversation is opened, I first fetch the latest few events (say 20) and then establish a relay subscription to backend for receiving newer messages. For the new messages received on subscription, I manually append that message to the existing connection using 

```js
ConnectionHandler.insertEdgeAfter(messagesConnection, newMessageEdge);
```

When I receive this new message, I also get the `cursor` value in subscription which I use to manually update the `endCursor` of the connection's `pageInfo` -
```js
pageInfo?.setValue(messageCursor, 'endCursor');
```

Now coming to the main problem, suppose there was a network problem due to which the frontend missed 20 newer messages in-between. So to handle this, I try to refetch newer messages since the last message (using `loadNext` call) I received on subscription and then re-establish the relay subscription. The events are actually fetched fine at network level but there is a check in `ConnectionHandler.update` (https://github.com/facebook/relay/blob/main/packages/relay-runtime/handlers/connection/ConnectionHandler.js#L151) that still references the old `pageInfo.endCursor` fetched during query and does not allow newer edges to be appended to the connection since the newer `pageInfo.endCursor` I updated manually above does not match the one received during the initial query.

Ideally, this handler should allow such updates because the source for edges can be outside the query as well.
Could not provide a repro because this requires an elaborate backend (even in mock). Let me know if there is a way around it or if this is a bug?

**Comment by sibelius** [comment]
you can have your own connection handler

**Comment by brijeshb42** [comment]
Could you point me to any documentation around this ^ ?

**Comment by daniloab** [comment]
> Could you point me to any documentation around this ^ ?

Follow this example from @biantris repo https://github.com/biantris/graphql-relay-web/blob/bebd5ab0cf06cc8474ee3e93b188255d54f9fd28/src/relay/mutationUtils.tsx
