### ISSUE TITLE
FIELDS_CHANGE does not, when removing last item in an GraphQLList

### ISSUE THREAD

**Issue by quazzie** [facebook/relay#398]
Could not reopen, creating a new issue with better description, prev issues #295 
When you remove the last item in a GraphQLList the list does not update the list.

My change in ~~18964ef05d753ef991d5f621367d7b1849352fc6~~ fixes this issue.
It does not check if the graphqllist changes in length and does not update.

**Comment by quazzie** [comment]
Uhmm i see that i have update the wrong place in the file. 
Correct change whould be 59f8e2315b43d570388b0bb43c0b3ffc8878167b.

**Comment by yuzhi** [comment]
Can you create a PR for this?

**Comment by quazzie** [comment]
#401

**Comment by quazzie** [comment]
Closed by #401
