### ISSUE TITLE
Consider adding a warning when parentId is used instead of parentID

### ISSUE THREAD

**Issue by cesarandreu** [facebook/relay#399]
React has some pretty awesome warning messages, such as when you use componentShouldUpdate instead of shouldComponentUpdate. 

It might be useful to add a development-only warning in [RelayMutationQuery.js](https://github.com/facebook/relay/blob/c67358894c7c48588c48fdd56e726b053e6e5d64/src/mutation/RelayMutationQuery.js#L325), checking that the user passed `parentID` instead of `parentId` (for the variations that expect it).

I ended up spending a while tracking down why a mutation was failing. The codebases I work with use `fooId` instead of `fooID`, and it's really easy to overlook that you're using `parentId` instead of `parentID`.

**Comment by yuzhi** [comment]
@cesarandreu thanks for reporting this issue. We understand that current mutation configs need some work. Others have voiced this concern as well. I am going to merge this to #232
