### ISSUE TITLE
[VS Code Extension] Wrong comment token applied to template literal

### ISSUE THREAD

**Issue by akoncic** [facebook/relay#3998]
When using the key binding to comment a line in VS Code, wrong comment token is applied to the tagged template literal passed to the `graphql` function:

```tsx
const useQuery = () =>
  useLazyLoadQuery(
    graphql`
      query someQuery {
        datum {
          // id <-- Wrong comment literal; expected "#", got "//"
          name
        }
      }
    `,
    {}
  );
```

Tested on several different machines and just with "vanilla" VS Code instance with only Relay GraphQL extension enabled.

**Comment by captbaritone** [comment]
@akoncic Does this work correctly if you use the [generic GraphQL vscode extension](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) instead? 

@tbezman I wonder if this is related to our syntax highlighting? Maybe we need to do something differently to signal to VSCode that this block is GraphQL?

**Comment by akoncic** [comment]
@captbaritone yes, it works correctly with [GrapQL VSCode extension](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql).
