### ISSUE TITLE
[Relay Compiler] `--version` doesn't respect actual version

### ISSUE THREAD

**Issue by jukben** [facebook/relay#3999]
### Problem

- `yarn relay-compiler --version` returns "0.0.0"

### Expected behavior
- `yarn relay-compiler --version` returns "14.0.0"

### My exploration
- I believe this problem starts to manifest due to this contribution https://github.com/facebook/relay/commit/42de87ec0ffcbe051e93c06621819540be53fee6#diff-d83140edf1339f1f1917b24d81d44dfeb57a0b548db4518577096b333dab305f which moved CLI core features (like version command) out of relay-compiler crate. 
- The version in `relay-bin` is not updated as part of the release "commit" (https://github.com/facebook/relay/commit/f85538779e68e56dcd29f5c7a2b79ccf9a7d4611#diff-43717d1e161bdd2969b45b9451668f0cff213c82f636d261cc11103b80eab128 – https://github.com/facebook/relay/blob/main/compiler/crates/relay-bin/Cargo.toml#L4) though. 
- This outdated (not set) version is then consumed here during the build https://github.com/facebook/relay/blob/main/compiler/crates/relay-bin/src/main.rs#L37 and thus the issue. 

Unfortunately, I don't know how to fix it easily, if the deployment is automated, I would suggest just propagating the version to Cargo.toml next to relay-bin, that should do the trick. Anyway, I'd like to learn. 🙏

**Comment by captbaritone** [comment]
@jukben Thanks for flagging. We have an internal script that does these version bumps and we forgot to update it when we moved the compiler to a new rust crate.

I think the script could/should live in open source. Would you be interested in adapting it to work in open source? I think the work would mostly involve updating some paths to use the ones found in this git repo (internally some files live in different location).

If so, I can paste the internal version here for you to use as a starting point.

**Comment by jukben** [comment]
Absolutely, agree! Yeah, I’d love to give it a try!

**Comment by captbaritone** [comment]
@jukben Great! Here's what we have internally. I think you could make a version that lives in the `/scripts/` directory.

https://gist.github.com/captbaritone/3351af94fb0821b93e26e23fbbc0c4c5

I suspect the main work will be mapping the internal paths to the ones we have here on GitHub. If you get stuck, just let me know and I can answer questions here.

**Comment by jukben** [comment]
@captbaritone Can you please share how do you envision running it in the future? I feel that this is part of some bigger ecosystem (I don't know but `export.command`, etc. gives me the idea). So I'm wondering if I should keep it compatible (which would be hard to test). 

Or do I just need to make a script that you can run with arg (version) which does the magic and you then change the CD process (I'm not familiar with this either in Relay) in separate PR/s? Just want to make this smooth, so aligning expectations 😀Many thanks!

**Comment by captbaritone** [comment]
Sorry for the confusion.

In terms of code, this script just takes a single positional CLI argument that is the version and uses that to update all the different cargo.toml/package.json files.

It's not currently used in any CI jobs, it's just a step in our manual release process which is documented internally.

**Comment by jukben** [comment]
Hey @captbaritone I'm still not sure but please take a look here, I bet we figure it out when we discuss real code 🙏 https://github.com/facebook/relay/pull/4004

**Comment by jukben** [comment]
It's fixed (at least in 16.1.0)

```
yarn relay-compiler --version
Relay Compiler 16.1.0
```
