### ISSUE TITLE
GraphQLRange cannot find a segment that has the cursor

### ISSUE THREAD

**Issue by grydstedt** [facebook/relay#403]
If I try to start an initial fetch of connection with a `after` cursor the request fails with `GraphQLRange cannot find a segment that has the cursor`.

The use case for this is to fetch a range that's in middle of a connection somewhere, eg. I navigate to a `?page=2` url. I'd like to create a cursor on the front end with encoded offset information for the initial fetch.

Is this case not supported intentionally?

**Comment by yuzhi** [comment]
Sorry, Currently GraphQLRange (Connections with first and last field calls) only supports storing data based on the cursor we already have. There is little Relay can use to figure out what's before or after the edges if we encounter another segment of result without already know about the cursor first. after all cursors are opaque and can't sorted.
If you want to page directly to something like `?page=2` you might be able to use a `offset` and `limit` model instead. That will just cached the results directly without trying to stitch the edges together.

**Comment by grydstedt** [comment]
Gotcha, thanks @yuzhi
