### ISSUE TITLE
option to modify/process props while passing down to component from HOC(container) ?

### ISSUE THREAD

**Issue by chandu0101** [facebook/relay#407]
is it good idea to support this feature ? 

UseCase : I am using relay in scala.js app , i want to pass type safe classes to the component ( instead of manually deserializing json to scala classes every time i call props).

Pseudo code : 
https://github.com/facebook/relay/blob/5e77de5f2495a2932b066d225d567d594b2a5823/src/container/RelayContainer.js#L783
```js
var finalStateProps =  {...this.state.queryData}

 if(spec.processProps)  {
   finalProps = spec.processProps( {...this.state.queryData})
 }

<Component {...this.props}
          {...finalStateProps}
          {...prepareRelayContainerProps(relayProps, this)}
          ref="component" />
```

or process all pieces ({this.props,this.state.queryData,ref,relayprops})

**Comment by xsistens** [comment]
:+1:

**Comment by Globegitter** [comment]
Something that would be useful for us as well in certain use-cases. E.g. we query the same data all over our app, but in a few parts we need to prepare the data, e.g. to display it in our select-component.

**Comment by chandu0101** [comment]
any objections for this proposal ? please let know if none i'll work on a PR!

**Comment by josephsavona** [comment]
I'm a bit wary of adding more complexity to RelayContainer. What are you doing as a workaround?

**Comment by Globegitter** [comment]
The current workaround that we are using is modifying the data in the render function.

**Comment by kassens** [comment]
It appears to me that this is a fine workaround and doesn't add much boilerplate to your app and if common in your case could be moved into a higher order component or some other abstraction.

I'm with @josephsavona on this one that we should try to keep the API small.
