### ISSUE TITLE
Relay compiler: v10 to v14 generated files has changed

### ISSUE THREAD

**Issue by AlexyMQ** [facebook/relay#4073]
Hi ! On our project we use relay-compiler 10.1.3 and he crashed on MacBook Pro M2, so I upgrade to 14.1.0. Now, I can compile but some generated types var name has changed for example Mutation variable and response types:
From (v10):
```
export type CreateTemplateMutation = {
    readonly response: CreateTemplateMutationResponse;
    readonly variables: CreateTemplateMutationVariables;
};
```
To (v14):
```
export type CreateTemplateMutation = {
  variables: CreateTemplateMutation$variables;
  response: CreateTemplateMutation$data;
};
```

Can I config relay compiler to use v10 format ? And how ?
Thanks

**Comment by kejistan** [comment]
That naming convention [was removed in v14](https://github.com/facebook/relay/releases/tag/v14.0.0). You might try upgrading to 13.2 first, it can generate aliases with the old naming convention [via a config option](https://github.com/facebook/relay/tree/v13.2.0/packages/relay-compiler).

**Comment by AlexyMQ** [comment]
Fine, works if I had `"typegenPhase": "Compat"` in my relay.config.json
Don't work with 14.X, but it's OK with 13.2.
Thank you
