### ISSUE TITLE
Invariant Violation: RelayQueryField() in todo example

### ISSUE THREAD

**Issue by reginedanica** [facebook/relay#408]
I tried to remove items in the todo list and I got this error 

'Uncaught Error: Invariant Violation: RelayQueryField(): Expected field `id` to be annotated with the type of the parent field.'

**Comment by wincent** [comment]
Thanks for the report, @reginedanica. What version of the code are you running? I can't repro this on the current `HEAD` of master.

Maybe you are running an old version of the babel-relay-plugin. Try running `npm install && npm run update-schema && npm run start` in the todo example and see if you can repro.

**Comment by zigomir** [comment]
@wincent I have same problem. I'm running 1844dc940b46021befd7703b574ddbbcee8656f8 atm. 
Running `npm run update-schema` will fill few `description` fields inside `schema.json`.

**Comment by N0hbdy** [comment]
Also, at fe3e78f7fd4f9f16c883136a05efbb83a82d82b9 I'm unable to add a new todo, probably for the same reason?

**Comment by pcarion** [comment]
i have also this same error on the current HEAD - I *did* run:

```bash
npm install && npm run update-schema && npm run start
```

The error is due to an invariant at:
https://github.com/facebook/relay/blob/master/src/query/RelayQuery.js#L890

under debugger, it appears that 
`this.__concreteNode__` is:
```js
GraphQLFieldNode {
  kind: "Field", 
__proto__: GraphQLFieldNode,
  fieldName: "id"…}
```
but `this.__concreteNode__.metadata` is:
```
edgesID: undefined
inferredPrimaryKey: undefined
inferredRootCallName: undefined
isConnection: false
isFindable: false
isGenerated: false
isPlural: false
isRequisite: false
isUnionOrInterface: false
parentType: undefined
```
and so that fails the invariant in:
```javascript
getParentType(): string {
    var parentType = this.__concreteNode__.metadata.parentType;
    invariant(
      parentType,
      'RelayQueryField(): Expected field `%s` to be annotated with the ' +
      'type of the parent field.',
      this.getSchemaName()
    );
    return parentType;
  }
```

**Comment by steveluscher** [comment]
Yep! We broke this. @josephsavona is on it!

**Comment by josephsavona** [comment]
Oops! Looking at it.

**Comment by pcarion** [comment]
I can confirm that the TodoMVC app is working now. Thanks!

**Comment by josephsavona** [comment]
@pcarion thanks for double-checking ;-)

**Comment by reginedanica** [comment]
Thanks a lot guys!
