### ISSUE TITLE
[Vscode extension] Multiple relay-compiler instances attached when reloading window 

### ISSUE THREAD

**Issue by Lalitha-Iyer** [facebook/relay#4088]
### Repro 

When using   "relay.autoStartCompiler": true setting, I noticed that reloading the Vscode window causes multiple relay-compiler instances to be running.

<img width="192" alt="Screen Shot 2022-10-09 at 12 59 58 PM" src="https://user-images.githubusercontent.com/2896187/195491189-00f20221-0184-4205-b8d1-0d8c59e7936e.png">

### Setup 
OS - Mac OS 12.5.1
VScode - 1.71.0
Relay Compiler - 14.1.0
Relay Graphql Extension - v1.0.2

**Comment by acdifran** [comment]
@Lalitha-Iyer ever find a workaround for this?

**Comment by Lalitha-Iyer** [comment]
This was resolved with this [issue](https://github.com/facebook/relay/pull/4455)
