### ISSUE TITLE
CI tests failing on Windows

### ISSUE THREAD

**Issue by captbaritone** [facebook/relay#4089]
Looks like one of our tests is failing on windows because it generates different style slashes in the snapshot: https://github.com/facebook/relay/actions/runs/3246689865/jobs/5325734982
<img width="889" alt="Screen Shot 2022-10-13 at 8 07 07 PM" src="https://user-images.githubusercontent.com/162735/195753190-67b0dd7e-4826-4fd9-8a45-d374276eea1e.png">

This is also blocking publication of main-branch releases to NPM.

**Comment by lumapat** [comment]
Seems like we can just normalize all import paths in the test suite to backslash as a workaround?

**Comment by alunyov** [comment]
I'm looking into this.
