### ISSUE TITLE
Add an example mutation with parameterized/new values

### ISSUE THREAD

**Issue by LegNeato** [facebook/relay#410]
Pretty much all mutation examples have the client doing a mutation without passing an explicit new value (for example, `LikeStoryMutation` doesn't send up the like count...the server instead has the logic to calculate the new value).

It turns out there *is* an example, but it is tucked in https://facebook.github.io/relay/docs/guides-mutations.html#fields-change (note the `newName` variable). Using that example in a component isn't shown but it would look like:

:clap: This is the way to do it :clap: 

```js
  saveToServer = (userSuppliedNameValue: string): void => {
    Relay.Store.update(new RenameDocumentMutation({
      document: this.props.document,
      newName: userSuppliedNameValue,
    }));
  }
```

This was a bit non-obvious, docs were lacking, and I was looking for a "sanctioned way". I tried these things first before stumbling on the above example:

* **Setting the prop with the new value:**

:beetle: This is not the way to do it! :beetle: 
```js
  saveToServer = (userSuppliedNameValue: string): void => {
    this.props.document.name = userSuppliedNameValue; // throws because we shouldn't edit props
    Relay.Store.update(new RenameDocumentMutation({
      document: this.props.document,
    }));
  }
```
Of course this is incorrect and throws, but it was confusing as a n00b...all but the above mutation examples just transparently pass in `this.props.[someObject]`.

* **Adding plain value:**

:beetle: This is not the way to do it! :beetle: 
```js
  saveToServer = (userSuppliedNameValue: string): void => {
    let newProps = {
      document: {
        name: userSuppliedNameValue,
      }
    };
    Relay.Store.update(new RenameDocumentMutation({
      document: newProps,
    }));
  }
```
This is incorrect and throws, as Relay is expecting a Relay-specific object here. As a n00b I thought Relay might have some magic to reconcile the values and what it tracks internally.

* **Cloning props, adding new value**:

:beetle: This is not the way to do it! :beetle: 
```js
  saveToServer = (userSuppliedNameValue: string): void => {
    let newProps = Object.assign({}, this.props.document);
    Relay.Store.update(new RenameDocumentMutation({
      document: newProps,
    }));
  }
```
This is incorrect and **silently** fails. Relay internals reconcile what is in the store and effectively blows away this value with the existing one in `this.props.document.name`.

:point_right: So I think the mutation docs should have a clearer example actually sending a value back to help out n00bs (or maybe it was just me?). Happy to write a PR if you agree!

**Comment by yuzhi** [comment]
It would be awesome if you can add more info to the mutation docs!

**Comment by josephsavona** [comment]
@LegNeato Any interest in adding an example to the docs?

**Comment by wincent** [comment]
Going to close this out as stale. We'd still welcome a PR enhancing the docs, but as [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable) is just around the corner, and it will have a dramatically simpler API for mutations, we aren't going to directly allocate any resources to documenting the old system any further.

Thanks for opening the issue, @LegNeato!
