### ISSUE TITLE
Fragment type directives are not included in mutation queries

### ISSUE THREAD

**Issue by yusefnapora** [facebook/relay#415]
When a mutation payload includes union or interface types which must be queried with fragment type directives, the mutation query does not include the type directives, leading to an invalid query.

For example, I have the following types:

```
type Link {
  displayText: String
  destination: LinkDestination
}

union LinkDestination = ExternalLink | InternalLink

type InternalLink {
  paths: [String]!
}

type ExternalLink {
  url: String!
}
```

In my Relay container I use a fragment spread to get either the `paths` or `url`, depending on the concrete type of the `LinkDestination` union type.  
```
  fragments: {
    link: () => Relay.QL`
      fragment on Link {
        destination {
          ... on ExternalLink {
            url
          }
          ... on InternalLink {
            paths
          }
        }
      }
    `,
  }
```
This works as expected.

However, if a mutation payload contains an object which contains a `Link`, the resulting query on the mutation payload looks like this: 

```
AddTextAnnotationToImagePayload{
  newPostEdge {
    cursor,
    node {
      link{ destination { paths,url } },
      // ... other fields omitted
    }
  }
}
```

This is invalid, because the `LinkDestination` union type does not contain the `paths` or `url` fields; they're defined on the member types `InternalLink` and `ExternalLink`

**Comment by yusefnapora** [comment]
Looking at `refragmentRelayQuery`, it looks like that only operates on Nodes, so perhaps I'm seeing this because the types above don't conform to `Node`?

**Comment by josephsavona** [comment]
@yusefnapora Can you paste the fat query for this mutation?

**Comment by josephsavona** [comment]
Also `getConfigs()`

**Comment by josephsavona** [comment]
I suspect this is the result of how we construct the mutation query (w/o the necessary metadata for `refragmentRelayQuery` to have an effect)

**Comment by josephsavona** [comment]
@yusefnapora can you attach the fat query and configs for this mutation?

**Comment by yusefnapora** [comment]
@josephsavona sorry about the delay.

I ended up resolving the issue by making `Link` be the dynamic type, instead of a container for another dynamic type (`LinkDestination` above).   It seems that the `refragmentRelayQuery` only checks to see if the child fields of a node are of a dynamic type, but it doesn't check if the "grandchildren" are dynamic.

Here's the fatQuery and configs for one of the mutations that was failing (several were affected):

```javascript
  getFatQuery() {
    return Relay.QL`
      fragment on AddSourceAnnotationToImagePayload {
        viewer { posts }
        postingUser { posts }
        image {
          sourceAnnotations
          posts
        }
        newPostEdge
      }
    `;
  }

  getConfigs() {
    return [{
      type: 'RANGE_ADD',
      parentName: 'image',
      parentID: this.props.image.id,
      connectionName: 'posts',
      edgeName: 'newPostEdge',
      rangeBehaviors: {
        '': 'prepend',
      }
    },
    {
      type: 'RANGE_ADD',
      parentName: 'viewer',
      parentID: this.props.viewerId,
      connectionName: 'posts',
      edgeName: 'newPostEdge',
      rangeBehaviors: {
        '': 'prepend',
      }
    },
    {
      type: 'RANGE_ADD',
      parentName: 'postingUser',
      parentID: this.props.currentUserId,
      connectionName: 'posts',
      edgeName: 'newPostEdge',
      rangeBehaviors: {
        '': 'prepend',
      }
    }];
  }
```

The problem isn't really apparent looking at the mutation; the `Link` is a child of `Post`, which is the `node` for `newPostEdge`.  When relay was generating the query on `AddSourceAnnotationToImagePayload`, it was constructing something like

```
mutation AddSourceAnnotationToImagePayload_foo {
addSourceAnnotationToImage(input: {
  "clientMutationId": "0",
  ...
  newPostEdge {
    node: {
      link: {
        destination: {
          url
        }
      }
    }
  }
```

and not including the `... on ExternalLink`  around the `url` field.

**Comment by luisobo** [comment]
I'm having this problem too. @yusefnapora what do you mean by "Making a type dynamic"?

Any other workarounds? /cc  @josephsavona 

Thank you!

**Comment by josephsavona** [comment]
@luisobo Are you on the latest version of Relay and `babel-relay-plugin`?

**Comment by luisobo** [comment]
@josephsavona nope, 0.2.5. It seems the latest is 0.3.0. Updating now. Should this fix the issue tho?

**Comment by luisobo** [comment]
it works! Can this issue be closed then?

**Comment by josephsavona** [comment]
Yup, I'll close it. Thanks for confirming the fix.
