### ISSUE TITLE
Future releases

### ISSUE THREAD

**Issue by Pablogot** [facebook/relay#4150]
Hi Relay team,
This is more a query than an issue.
I have been wondering about what is the planned schedule for releases of the library since the last release has been in July and the release frequency has slowed down consistently.

- Is Relay still being maintained? 
- which is the roadmap?
- is there any place where I can access future release-related information?

Thanks in advance,
Pablo

**Comment by kmiddleton14** [comment]
Hi @Pablogot thanks for asking these questions and we're sorry for the delay in our next release. This is something we're currently working on and hoping to have a new release soon. We're also planning on sharing our roadmap for H1 with the community and being more transparent on the projects we're taking, as well as sharing potential opportunities for others to contribute.
