### ISSUE TITLE
Align @defer and @stream with current draft specification

### ISSUE THREAD

**Issue by tobias-tengler** [facebook/relay#4158]
Relay doesn't define the definition of these directives itself, but the rust compiler makes some assumptions on the shape of these directives. These assumptions are not in line with the currently proposed definitions for these directives:

- [@defer spec definition](https://github.com/robrichard/graphql-spec/blob/incremental/spec/Section%203%20--%20Type%20System.md#defer)
- [@stream spec definition](https://github.com/robrichard/graphql-spec/blob/incremental/spec/Section%203%20--%20Type%20System.md#stream)

Namely the `@stream` directive argument being `initial_count` instead of `initialCount` and the nullability of the `if` and `label` arguments.

The specification is already in the Draft stage and the current discussion is (to my knowledge) no longer focused on the definition of these directives, but rather on the shape of payload used to deliver the incremental results. I don't think there will be any further iteration on the directives, so I would propose to align Relay's assumptions of those directives with the spec. This would allow people to play around with existing server-side implementations and provide further feedback on the incremental deliver portion of the spec.

**Comment by gigabet** [comment]
@tobias-tengler Relay's current spec differs from the [GraphQL RFC](https://github.com/graphql/graphql-wg/blob/main/rfcs/DeferStream.md), which is in Stage 2. The new spec wraps the payloads in { incremental }, which Relay doesn't handle right now.
