### ISSUE TITLE
Lazily mount Relay Playground instances on main Relay page

### ISSUE THREAD

**Issue by taion** [facebook/relay#416]
When I hit http://facebook.github.io/relay/, there's a noticeable delay before I can interact with the page, which seems to come from the time it takes to set up all the Relay Playground instances.

Would it make sense to use something like react-waypoint or react-lazy to only load the playground instances when they enter the viewport? It takes a very tall viewport for anything but the first playground to be visible, so in expectation this should improve things noticeably for most users.

**Comment by wincent** [comment]
I've noticed this too. What do you think, @steveluscher?

**Comment by wincent** [comment]
We're planning on totally replacing the Relay website for the release of [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable), including rethinking how the Playground works, so I am going to close this for now.

Thanks for bringing this issue up, @taion. This had bugged me as well. We'll do our best to make things a bit smoother on the new documentation site.
