### ISSUE TITLE
[VSCode] Commenting doesn't work correctly

### ISSUE THREAD

**Issue by tobias-tengler** [facebook/relay#4163]
When commenting inside of `graphql` annotated strings, the Relay Extension doesn't correctly comment out the code:

![relay-commenting](https://user-images.githubusercontent.com/45513122/210116492-61f069a2-f001-4ed6-802f-8d1d3f5934b6.gif)

It should be using `#` to comment out the line.

The VSCode extension uses [vscode-graphql-syntax](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql-syntax) for syntax highlighting and basic GraphQL editor features.
This extension without the Relay extension on top supports commenting correctly. I suspect that the `language-configuration.json` of vscode-graphql-syntax, which defines the commenting behavior, is somehow blocked or overridden by the Relay extension.

_This could also be a VSCode bug_

**Comment by captbaritone** [comment]
I just tried this myself and it seems to work now

https://github.com/facebook/relay/assets/162735/f8bef696-c8ef-472f-ad62-409e7e799404

I'm going to close, but feel free to reopen if you can still reproduce.
