### ISSUE TITLE
Create Mongo Connection

### ISSUE THREAD

**Issue by arunoda** [facebook/relay#418]
Hi,

I'm going to create a relay connection for Mongo. Is there anyone who tried to built it?
Then, I can use that.

**Comment by clentfort** [comment]
Someone contributed an example how to use relay together with mongoose. https://github.com/sayden/relay-mongoose-example, this might be a good starting point.

**Comment by arunoda** [comment]
Thanks.

**Comment by josephsavona** [comment]
Thanks for the question and answer!

**Comment by nodkz** [comment]
@mikberg awesome! 

Try found time on this week to test it.

**Comment by nodkz** [comment]
BTW 
1 connection = 10mb RAM at mongodb server.
So if 1000 connection, then server with mongo should have 10GB RAM!!!
