### ISSUE TITLE
New tutorial uses mutation APIs not available for TypeScript users

### ISSUE THREAD

**Issue by orta** [facebook/relay#4212]
## Reporting issues with Relay

This is more of a "maybe we should provide a link elsewhere" but you cannot use `optimisticUpdater` in a TypeScript project as it triggers a compiler panic:

```
$ relay-compiler
[INFO] querying files to compile...
[INFO] [default] compiling...
thread 'tokio-runtime-worker' panicked at 'Getters and setters with different types are not implemented in typescript. See https://github.com/microsoft/TypeScript/issues/43662', crates/relay-typegen/src/typescript.rs:249:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR] A thread that the Relay compiler spun up did not shut down gracefully: panic
[ERROR] Compilation failed.
[ERROR] Unable to run relay compiler. Error details: 
A thread that the Relay compiler spun up did not shut down gracefully: panic
error Command failed with exit code 1.
```

Not strictly a problem ( because you can read the thread and see someone from this team saying "hey this thing is blocking relay") but it does mean folks outside of FB can't [follow the mutations section](https://relay.dev/docs/tutorial/mutations-updates/#improving-the-ux-with-an-optimistic-updater)

Maybe just a link to the reference to optimisticResponse part of [`useMutation`](https://relay.dev/docs/api-reference/use-mutation/#return-value)'s reference?

**Comment by fveracoechea** [comment]
I'm experiencing a similar issue with the `optimisticUpdater` function from `useMutaion`:
![Screenshot 2023-02-17 at 9 49 01 PM](https://user-images.githubusercontent.com/26258895/219827873-d30da69f-4e91-4153-950b-9c05bcc436fd.png)

This is my error message:
`Property 'readUpdatableFragment' does not exist on type 'RecordSourceSelectorProxy<SearchListDeleteMutation$data>'.`

**Comment by tslater** [comment]
@fveracoechea, at runtime `readUpdatableFragment_EXPERIMENTAL` is defined, but `readUpdatableFragment` is not. Neither have types for me.

**Comment by fveracoechea** [comment]
was this fixed on the new version v15? does anyone know? I haven't tried it yet

**Comment by eunsukimme** [comment]
Same issue exists on v15.

**Comment by kbumsik** [comment]
So, here is what happens to me:

- 14.1.0
  - readUpdatableFragment: Not defined
  - readUpdatableFragment_EXPERIMENTAL: both runtime and type defined
  - So the tutorial doesn't work
- 15.0.0
  - readUpdatableFragment: runtime defined, but type not defined
  - readUpdatableFragment_EXPERIMENTAL: type defined
  - So the tutorial does work, but got typing error.

**Comment by tobias-tengler** [comment]
I've updated the `@types/relay-runtime`, so the types should now match the implementation.

The PR to implement the type generation into the compiler can be found here: https://github.com/facebook/relay/pull/4370
