### ISSUE TITLE
useRelayEnvironment in a Storybook story errors if used directly in story

### ISSUE THREAD

**Issue by Pikachews** [facebook/relay#4223]
## Issue

When `useRelayEnvironment` is used in a Storybook story:
* if called directly in the story, it will fail to see an environment and error
* if called indirectly (i.e. within a child component), it will see the environment properly

Likewise, usages of other relay hooks that utilize `useRelayEnvironment` results in the same issue.

I don't believe this is an issue with Storybook itself because it appears to work properly with other usages of React contexts (included in reproduction), but I'll file an issue there if that is not the case.

## Reproduction

https://github.com/Pikachews/storybook-relay-issue

1. `git clone https://github.com/Pikachews/storybook-relay-issue && cd storybook-relay-issue`
3. `yarn install`
4. `yarn storybook`
5. Observe `Relay` -> `No Error` story works properly
6. Observe `Relay` -> `With Error` fails to render with `Expected to have found a Relay environment...`
7. Observe `TestContext` -> `No Error` works properly (will require a reload of the page after viewing the error)

**Comment by edvinerikson** [comment]
https://github.com/Pikachews/storybook-relay-issue/blob/main/.storybook/decorators/withRelayEnvironment.tsx#L14
Since you're calling storyFn here, the top-level component isn't rendered as a component. I'm not a storybook expert, but either your top level component shouldn't be a component at all, or you should render it as one like `<StoryFn />`
```
 <RelayEnvironmentProvider environment={environment}>
        <>{storyFn(context)}</>
      </RelayEnvironmentProvider>
```

**Comment by Pikachews** [comment]
Thanks @edvinerikson, that appears to be the problem! After changing it to `<StoryFn />` (and ignoring the type errors 😅), it does appear to work.

I guess I'll have avoid using the [makeDecorator](https://storybook.js.org/docs/react/addons/addons-api#makedecorator-api) API to avoid the type errors and use [this approach](https://storybook.js.org/docs/react/essentials/toolbars-and-globals#create-a-decorator) of creating decorators for this purpose.
