### ISSUE TITLE
License of examples?

### ISSUE THREAD

**Issue by fson** [facebook/relay#425]
The [README files of the examples](https://github.com/facebook/relay/tree/master/examples/todo#license) state that they are provided with a "Facebook reserves all rights" type of non-commercial evaluation license.

The file headers in examples say that they are BSD licensed, however: https://github.com/facebook/relay/blob/bd86c048cf0c8a4a5938a4a9c5913d7fc3985a7d/examples/todo/js/app.js#L1-L8

Which one is the license for examples at the moment?

**Comment by wincent** [comment]
I believe the `README` is correct. We should fix the headers in the other example files, although we might have to tweak our linter to recognize that the modified headers are legit.

**Comment by fson** [comment]
Thanks for answering @wincent. I'll keep this issue open as a reminder to update the headers.

**Comment by wincent** [comment]
I believe this is now taken care of (via 1e1131371f756f46bcbcf739f1b98af1002e6c8a).
