### ISSUE TITLE
Feature Request: using Relay on the backend

### ISSUE THREAD

**Issue by arantespp** [facebook/relay#4266]
# Using Relay on the backend

I want to generate the GraphQL schema types on my backend code, mainly because I want the inputs and enums. Today, it's possible to do so using `babel-plugin-relay` and following the [installation steps](https://relay.dev/docs/getting-started/installation-and-setup/). Finally, you create a file that exports nothing to make the queries and mutations you want to generate for the types. For example, the example below (named `relay/Types.ts`) generates `CreateBatchCampaignInput` for me when I run `relay-compile`.

```ts
/* eslint-disable relay/graphql-naming */
import graphql from 'babel-plugin-relay/macro';

graphql`
  mutation TypesMutation($createBatchCampaignInput: CreateBatchCampaignInput!) {
    batchCampaign {
      create(createBatchCampaignInput: $createBatchCampaignInput) {
        result
      }
    }
  }
`;
```

## Proposal

It'd be interesting if we didn't need to create the `relay/Types.ts` to generate the types but provide only the schema to get all types, inputs, and enums generated on the server.

**Comment by arantespp** [comment]
Thanks, @edvinerikson! It worked perfectly.

**Comment by sibelius** [comment]
Relay is great for this

https://dev.to/woovi/how-woovi-uses-relay-1iic

we are using Relay for type checking in our backend tests
