### ISSUE TITLE
Allow users to disable suspense when doing a refetch

### ISSUE THREAD

**Issue by cliedeman** [facebook/relay#4290]
When doing a refetch on a usePaginationFragment or useRefetchFragment refetch triggers a suspsense.
Essentiall I want my refetch to behave the same as the loadNext method

I could use this [method](https://relay.dev/docs/guided-tour/refetching/refetching-queries-with-different-data/#if-you-need-to-avoid-suspense-1) but I don't want to give up all the nice features of these higher level components, built in pagination for example.

For comparison react-query useQuery with suspense refetch only triggers a suspend on initial load and then works exactly as expected

Ciaran

**Comment by kejistan** [comment]
Wrapping the refetch call in [a transition](https://react.dev/reference/react/useTransition) is a general purpose approach to this. That'll let you keep showing the "previous" data while also keeping track of the loading state.

```ts
const [data, refetch] = useRefetchableFragment(/* */);
const [isLoading, startTransition] = useTransition();

return (
  <>
    {/* data */}
    <Button onPress={() => startTransition(() => refetch(/* */))}>Refetch</Button>
  </>
);

**Comment by cliedeman** [comment]
Thanks @kejistan That worked. 

It looks like there is a missing link from this [page](https://relay.dev/docs/guided-tour/refetching/refetching-fragments-with-different-data/#if-you-need-to-avoid-suspense) to this [page](https://relay.dev/docs/guided-tour/rendering/loading-states/)

The advice to use fetchQuery does not make sense with transtions being available now

**Comment by erikostling** [comment]
Using `useTransition` on a `refetch` from `usePaginationFragment ` doesn't seem to work (i e does not suspend). Is this expected behavior? See issue https://github.com/facebook/relay/issues/4526
