### ISSUE TITLE
Why the common pattern for mutations is removed?

### ISSUE THREAD

**Issue by chochihim** [facebook/relay#4305]
I have an old project that follows below naming convention:

> mutations are named as verbs, their inputs are the name with "Input" appended at the end, and they return an object that is the name with "Payload" appended.

Now I need to maintain the project and when I revisit the document I find that above convention is [removed](https://github.com/facebook/relay/pull/3381)

My question is why it is removed? Is it not good anymore? Should I keep using that naming convention?

**Comment by sibelius** [comment]
it is not required anymore, it is optional

but it is a good practice
