### ISSUE TITLE
Session cookie is not passed 

### ISSUE THREAD

**Issue by benoitguigal** [facebook/relay#437]
I am using Relay with express-graphql and express-session. I would like to use the session in my GraphQL schema but unfortunately the `connect.sid` cookie is not passed in graphql requests. 
Should I create my own network layer for that or is this supposed to be built-in ?

**Comment by fson** [comment]
The default network layer uses `fetch` which does not pass cookies by default, but can enable them by passing an init object for `fetch` when you're creating the network layer:
```js
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://example.com/graphql', {
    credentials: 'same-origin',
  })
);
```

**Comment by benoitguigal** [comment]
Great ! Reading the documentation for injecting a network layer, it is not clear to me where this should be done. Just before declaring the RootContainer ? I am using react-router-relay so I wonder if I have control over the network layer or if I should look inside react-router-relay.

**Comment by fson** [comment]
@benoitguigal It shouldn't matter as long as you do it before rendering your app with `ReactDOM.render()`. You probably have some sort of entry point for your app where you set up the router and call `ReactDOM.render()` – do it there.

**Comment by benoitguigal** [comment]
Works like a charm, thanks a lot !

**Comment by dasarma** [comment]
@benoitguigal Can you give me an example how you pass the connect.sid to the requests? I am at the same point and don't know how to set the cookie.

**Comment by benoitguigal** [comment]
@dasarma, just add:  
```
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://example.com/graphql', {
    credentials: 'same-origin',
  })
);
```
an then cookies will be passed. 
Then just follow documentation from `express-graphql`: 

```
var session = require('express-session');
var graphqlHTTP = require('express-graphql');

var app = express();

app.use(session({ secret: 'keyboard cat', cookie: { maxAge: 60000 }}));

app.use('/graphql', graphqlHTTP(request => ({
  schema: MySessionAwareGraphQLSchema,
  rootValue: { session: request.session },
  graphiql: true
})));
```
