### ISSUE TITLE
fetchQuery requires React Context

### ISSUE THREAD

**Issue by AmirL** [facebook/relay#4374]
I'm using Relay with NextJs 13 and the new app router.  It works well with Client components, but it has a problem with Server components. Even when I use fetchQuery, and pass a newly created relayEnviroment, it tries to create a React Context, which is completely unnecessary. And this throws a runtime error. 

```ts
  const environment = new Environment({
    network: Network.create(fetchFunction),
    store: new Store(new RecordSource()),
  });
  fetchQuery(environment, QUERY, {});
```

I believe in Relay should be a way, to fetch a query without any context. I use a workaround, a simple fetch function near my relayEnvironment function, which is not a good enough solution though.

```ts
// Use for server-side rendering, because Relay requires createContext for some reason
export async function fetchQueryServerSide<T>(query: string, variables: any) {
  const response = await fetch(graphqlEndpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query, variables }),
  }).then((res) => res.json());

  return response.data as T;
}
```

**Comment by puopg** [comment]
I think the thing is the `fetchQuery` is more than just "make a graphql request".  It also does all that jazz of normalizing data into the relay story and notifying components subscribed to parts of the store.

I feel like what you are asking for is exactly your workaround, make a POST request to some endpoint and fetch data.

**Comment by robrichard** [comment]
I was able to use `fetchQuery` in react server components by importing it from `relay-runtime`. Importing anything from `react-relay` will cause you to run into the createContext issue.

https://gist.github.com/robrichard/a402759733366ead3854a01aef8685b1

**Comment by AmirL** [comment]
I ended up with this version, it simple to use, and works well with graphql Relay macro, with types.
```ts
const EXAMPLE_QUERY = graphql`
...
`;

const response = await fetchQueryServerSide<pageQuery>(EXAMPLE_QUERY, { yourVariable: value})

...

export async function fetchQueryServerSide<T extends { response: object; variables: object }>(
  query: GraphQLTaggedNode,
  variables: T['variables'])
  const text = getRequest(query).params.text;
  const response = await fetch(graphqlEndpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
   body: JSON.stringify({ query: text, variables }),
  }).then((res) => res.json());

  return response.data as T['response'];
}
```
