### ISSUE TITLE
Which type in the MockPayloadGenerator's resolver the query that returns Boolean resolves to?

### ISSUE THREAD

**Issue by Mozuha** [facebook/relay#4377]
I am having an issue implementing a mock resolver with MockPayloadGenerator for a preloaded query that is expected to return a Boolean value. I would appreciate it if anyone could point me out if there is anything I am missing.

I have this GraphQL schema:
```graphql
type Query {
  emailExists(email: String!): Boolean
}
```

And I have components like these and already ran the relay compiler to generate the definition of the query:
```typescript
export const emailExistsQuery = graphql`
    query EmailFieldQuery($email: String!) {
      emailExists(email: $email)
    }

export default function EmailField() {
  const [queryRef, loadQuery] = useQueryLoader<EmailFieldQuery>(emailExistsQuery)

  const handleBlur = () => {
    loadQuery({ email: valueFromInput }, { fetchPolicy: 'network-only' })
  }

  return 
    <input onBlur={handleBlur} />
    { queryRef != null && <ShowResponse queryRef={queryRef} /> }
}

// In another file
export default function ShowResponse(props: { queryRef: PreloadedQuery<EmailFieldQuery> }) {
  const data = usePreloadedQuery(emailExistsQuery, props.queryRef)
  console.log(data)

  return <p>{data.emailExists}</p>
}
```

Then, in a test file with jest and testing-library:
```javascript
test("should show response data", async () => {
  const environment = createMockEnvironment()
  await waitFor(() => 
    environment.mock.queueOperationResolver((operation) => {
      return MockPayloadGenerator.generate(operation, {
        // Intuitive one to be called, but not
        Boolean(context) {
          console.log(context)
          return true
        },

        // Boolean maps to String in MockResolvers according to doc (https://relay.dev/docs/guides/testing-relay-components/#float-integer-boolean-etc),
        // so this is also the one possibly be called, but not
        String(context) {
          console.log(context)
          return true
        },

        // Tried several types to check which type actually matched, and this was the one
        Query(context) {
          console.log(context)
          return true
        }
      })
    })
  )
  await waitFor(() => environment.mock.queuePendingOperation(emailExistsQuery, { email: 'someEmail@email.com' }))
  render(
    <RelayEnvironmentProvider environment={environment}>
      <EmailField />
    </RelayEnvironmentProvider>
  )

  // act and assert follows...
  // After checking with console.logs and checking the instance of operation received by queueOperationResolver,
  // I am pretty sure that loadQuery was actually called with the specified query and variable { email: 'someEmail@email.com' }
})
```

As I wrote in the comment above, Boolean and String resolvers were not called and Query resolver was called, as that was the only one that printed out `context` value. However, the value of `context` was `{ parentType: null, name: null, alias: null, args: {}, path: [] }` and the value returned by usePreloadedQuery in the ShowResponse component was ` { emailExists: undefined }`

Environment:
- react: 18.2.0
- next: 13.4.6
- react-relay: 15.0.0
- relay-runtime: 15.0.0
- relay-compiler: 15.0.0
- relay-test-utils: 15.0.0
- jest: 29.6.1
- jest-environment-jsdom 29.6.1
- @testing-library/react: 14.0.0
- @testing-library/jest-dom: 5.16.5

**Comment by kejistan** [comment]
I'm not sure why `String` doesn't match, but you can make it work with `Query`. The `Query` resolver matches because you're issuing a query and that is the root type. You're getting `undefined` because you're returning the wrong type from that Query resolver: a scalar, rather than an object with the fields you queried.

```js
Query(context) {
  return { emailExists: true };
}
```

**Comment by Mozuha** [comment]
@kejistan Thanks for your advice. Yes, that works.
Actually, I was having another issue (#4362), and resolving it also resolved this issue. Now, `String` does match, and returning an object from `Query` match also works :)
