### ISSUE TITLE
Cannot resolve module 'qs' and 'deep-equal' in react-router

### ISSUE THREAD

**Issue by octref** [facebook/relay#439]
Fresh clone. For the todo example, run `npm i` and `npm start`. Here is the error message:

```
  [761] ./js/queries/ViewerQueries.js 995 bytes {0} [built]

ERROR in ./~/react-router/~/history/lib/useQueries.js
Module not found: Error: Cannot resolve module 'qs' in /Users/octref/Code/learn/relay/relay/examples/todo/node_modules/react-router/node_modules/history/lib
 @ ./~/react-router/~/history/lib/useQueries.js 11:10-23

ERROR in ./~/react-router/~/history/lib/createHistory.js
Module not found: Error: Cannot resolve module 'deep-equal' in /Users/octref/Code/learn/relay/relay/examples/todo/node_modules/react-router/node_modules/history/lib
 @ ./~/react-router/~/history/lib/createHistory.js 13:17-38
webpack: bundle is now VALID.
```

Manually installing `qs` and `deep-equal` solve the problem. But I guess that's not the way the problem should be resolved.

I'm using Node v4.1.2 and npm 2.14.4 if that matters.

**Comment by josephsavona** [comment]
@octref These are dependencies of `react-router`, not Relay. I'd recommend filing an issue with `react-router`. Feel free to comment again here though if that doesn't solve the problem!

**Comment by octref** [comment]
Yeah the problem is https://github.com/rackt/react-router/issues/2195. They are saying `rc3` will be released soon and it'll solve the problem. Should I keep an eye on it and submit a PR to update the dependencies for relay examples?

**Comment by josephsavona** [comment]
@octref that would be great, thanks!

**Comment by kassens** [comment]
@octref: rc3 is released now. Want to send the PR for the fix?

**Comment by octref** [comment]
@kassens 
Done and signed CLA.
