### ISSUE TITLE
Bug: requiring relay interrupts node process

### ISSUE THREAD

**Issue by droganov** [facebook/relay#440]
How to reproduce:
```
Relay = require "react-relay"
```
npm start:
```
dev server restarted
ReferenceError: self is not defined
    at .../relayapp/node_modules/react-relay/node_modules/fbjs/node_modules/whatwg-fetch/fetch.js:4:7
```

The problem is mentioned [here](https://github.com/facebook/relay/issues/136), but it's there is no `bug` label on it

**Comment by josephsavona** [comment]
This is on our radar and being tracked at facebook/fbjs#60.
