### ISSUE TITLE
Stale artifacts aren't cleaned up

### ISSUE THREAD

**Issue by tobias-tengler** [facebook/relay#4403]
Relay doesn't seem to cleanup old artifacts, when the compiler isn't continuously run in watch mode, but the relay command is invoked manually.

## How to reproduce

1. Create a query in some file

```js
const query = graphql`
  query TestQuery {
    someField
  }
`
```

2. Run the relay compiler
3. Observe `TestQuery.graphql.ts` being created
4. Change the query

```diff
const query = graphql`
- query TestQuery {
+ query Test2Query {
    someField
  }
`
```

5. Run the relay compiler
6. Observe `Test2Query.graphql.ts` being created
7. Notice how `TestQuery.graphql.ts` wasn't removed

**Comment by michaelmcneilnet** [comment]
Possibly covered by #3864

**Comment by tobias-tengler** [comment]
Yes, removing `__generated__` from the `exclude` config did work.
