### ISSUE TITLE
Is it possible to subscribe to node changes outside of a root query or fragment?

### ISSUE THREAD

**Issue by tinleym** [facebook/relay#4411]
I’m building something that requires indefinite recursion, and so needs to operate outside of Relay’s query -> fragment structure. I’m loading all the data I’ll need into a query, creating a tree with the node ids, and passing the ids into the consuming components. 

Calling a node(id) query with useLazyLoadQuery and a store-only fetchPolicy doesn’t return any results, even though the record associated with the id is in the store. Calling lookup() with the operation descriptor of the same node(id) query in an event also doesn’t return any results.

Calling relayEnvironment.getStore().getSource().get(id) in the same event does return the record, but I’d like to be able to subscribe to changes. Is there a way to do this?

**Comment by tinleym** [comment]
Still curious about node subscriptions by id, but in case anyone comes across this with a similar issue, the way I met my requirements was to use useFragment as normal, and to store a map of ids to fragmentReferences.

**Comment by edvinerikson** [comment]
Have you configured missingFieldHandlers to resolve node queries correctly? Otherwise the node query won't be able to get the data unless you actually fetch the data through that query.

**Comment by tinleym** [comment]
That's what I was missing! Thank you!
