### ISSUE TITLE
babel-relay-plugin dependencies out of date

### ISSUE THREAD

**Issue by Aweary** [facebook/relay#443]
`babel-relay-plugin` [still depends on `graphql` `0.2.4`](https://github.com/facebook/relay/blob/2a86be3e71cdc6511fa994e3de539f72070da1b4/scripts/babel-relay-plugin/package.json#L20)

I'm having some trouble using some recently introduced features like https://github.com/facebook/graphql/pull/100 and I'm thinking this might be the issue.

I'd be happy to PR with an updated dependency, unless there's some things that need to be updated in the plugin to work with `^0.4.7`

**Comment by josephsavona** [comment]
Thanks for the reminder! There are a few things we'd like to test and possibly add (such as the type of fragments you mentioned) during the upgrade, we got this one ;-)

**Comment by Aweary** [comment]
Cool, thank you! :smile: any estimate on when those changes might be made/published?
