### ISSUE TITLE
Option to specify custom mutation query name

### ISSUE THREAD

**Issue by chandu0101** [facebook/relay#445]
Hi,
      Scala.js-relay mutation queries not working because of this reason https://github.com/facebook/graphql/issues/102

i don't see any activity from graphql side may be it requires more work!, In my understanding graphql should allow javascript valid identifiers as its not the case now and scala.js can't do anything either so is it possible to allow option( static queryName) to define mutation query names ? or can we modify query name to match graphql ASCII set before sending  ? 

please let me know if either of cases can possible ?  , i am happy to send a PR!

**Comment by josephsavona** [comment]
Mutations can specify a custom name with ``Relay.QL`mutation YourNameHere { ... }` `` - does this help?

**Comment by xsistens** [comment]
@josephsavona is the code you referring to the one from the ```getMutation``` method like in this example? 
```
class LikeStoryMutation extends Relay.Mutation {
  getMutation() {
    return this.props.story.viewerDoesLike
      return Relay.QL`mutation MutationName {likeStory}`;
  }
}
```
if yes, then this does not solve the problem. 
@chandu0101 is talking about the mutation name that is actually used in the query that is send to the graphql server. 

As an example from scala.js relay version we developed, the query looks like this, even after applying the change you suggested:
```
mutation $c_Lcom_scalajs_relay_examples_treasure_mutations_CheckHidingSpotForTreasureMutation($input_0:CheckHidingSpotForTreasureInput!){
  checkHidingSpotForTreasure(input:$input_0){
    clientMutationId,
    ...
  }
}
```

as you can see in scala.js it still has a weird name, that indicates me that the name that is used in the query is generated of the name from the actual mutation instance in the global namespace (just a guess). In scala.js this must be unique over the whole javascript libraries that are used, thats why the package name is used. If your suggestion would affect the name used in the query i guess it should be reflected somewhere in this path even in scala.js. but i'm not 100% certain.

**Comment by josephsavona** [comment]
@xsistens Thanks for providing more detail, I see what's happening.

It seems reasonable to use the name of the mutation (from the ``Relay.QL`mutation YourName {...}` ``) as the name that is sent to the server. Note that `babel-relay-plugin` defaults to using the filename when no mutation name is provided in the query, so the default behavior shouldn't change (we should confirm). The change would be [in RelayMutationTransaction](https://github.com/facebook/relay/blob/c67358894c7c48588c48fdd56e726b053e6e5d64/src/mutation/RelayMutationTransaction.js#L197-L198) - we can replace `this._mutation.constructor.name` with `this._getMutationNode().name`. Want to submit a PR? ;-)

**Comment by chandu0101** [comment]
@josephsavona  thanks alot for pointer , i just opened a PR https://github.com/facebook/relay/pull/448 please review it , i can confirm that scalajs mutations working fine now :+1:
