### ISSUE TITLE
"GraphQL.QueryFragment is not a function" in todo example

### ISSUE THREAD

**Issue by imasl** [facebook/relay#446]
After clean todo example installation i got the following error in console log: "Uncaught TypeError: GraphQL.QueryFragment is not a function". The app is not showing.

**Comment by josephsavona** [comment]
Thanks for reporting, we're looking into it.

**Comment by steveluscher** [comment]
Fixed in 4e671a316bbb09dee0fcc14aa414f0d31076948f. Thank you!
