### ISSUE TITLE
Patterns for Transient UI notifications

### ISSUE THREAD

**Issue by AndrewIngram** [facebook/relay#447]
Following on from my StackOverflow question: http://stackoverflow.com/questions/33001632/patterns-for-transient-user-notifications-with-relay

I have a need to display success/error/warning/info messages in my UI, with text provided by the server. They don't get stored in a database, and don't get marked as read, they're simply shown once and then dismissed.

If there is an idiomatic way of handling this use case, it'd be useful to know what it is. It doesn't feel like this notification should live in the GraphQL schema, because it's never accessible afterwards. Conceptually it feels like metadata that's returned with a response, but I don't know how i'd achieve that. I'm also not sure if this is a GraphQL issue or a Relay issue.

**Comment by josephsavona** [comment]
Answered on SO

**Comment by AndrewIngram** [comment]
@josephsavona any chance on elaborating on SO? I've been working on this for a day now, and don't feel any closer to getting it working.
