### ISSUE TITLE
[TypeScript] useFragment can't handle undefined fragment references

### ISSUE THREAD

**Issue by tobias-tengler** [facebook/relay#4497]
The typings of the `useFragment` hook in TypeScript need to be aligned with the Flow typings to support `undefined` (`void`): https://github.com/facebook/relay/blob/a01756bc9c0718cc4575bf01210f3454ef18e874/packages/react-relay/relay-hooks/useFragment.js#L41-L44

Otherwise users can't upgrade to v16 without disabling the new generation of `undefined` for nullable types by the relay-compiler.

I'll send a PR to `@types/react-relay` once I get of work.

**Comment by tobias-tengler** [comment]
DefinitelyTyped PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67136

**Comment by tobias-tengler** [comment]
Released as v16.0.0 of `@types/react-relay`.

**Comment by VictorGlindasPaf** [comment]
There's a similar issue with `readInlineData`
