### ISSUE TITLE
Release notes for v16?

### ISSUE THREAD

**Issue by cheema-corellian** [facebook/relay#4503]
I noticed that v16 was released 3 days ago.  https://www.npmjs.com/package/react-relay/v/16.0.0

This is a major version upgrade.  Is there any documentation on what was changed?

**Comment by noghartt** [comment]
You can find the changelog [here](https://github.com/facebook/relay/releases/tag/v16.0.0)

**Comment by cheema-corellian** [comment]
Thanks.
