### ISSUE TITLE
Examples: Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by tothandras** [facebook/relay#455]
Running the examples I run into this problem.
![image](https://cloud.githubusercontent.com/assets/4157749/10447980/8b0ea570-7189-11e5-8876-994a32961342.png)

**Comment by wincent** [comment]
Thanks for the report!

Should be fixed by https://github.com/facebook/relay/pull/453

**Comment by tothandras** [comment]
@wincent Thank you!
