### ISSUE TITLE
Caching for things other than `node` ?

### ISSUE THREAD

**Issue by nickretallack** [facebook/relay#457]
I wrote a Relay app and I noticed that after loading a list of widgets, if I visited a page for just a single widget that queried for exactly the same fields that were already known from the list, Relay would still issue a new query.

Then I switched from `query { widget( id: $id ) }` to `query { node( id: $id ) }` in my route and it stopped doing the extra queries.  Is there something special about `node`?  `widgetType` implements the `nodeInterface` so shouldn't its id be treated the same?  Or is there some way I need to inform Relay that I'm querying for something by its id?  Or should I just not do that and always use `node` queries instead?

**Comment by wincent** [comment]
> Is there something special about `node`?

The Relay GraphQL spec does declare `node` to be special. As it is currently implemented, all object refetching [happens](http://facebook.github.io/relay/docs/graphql-object-identification.html) through the `node` field, so implementing the [Node Interface](http://facebook.github.io/relay/graphql/objectidentification.htm#sec-Node-Interface) is a necessary but not sufficient condition to avoid re-querying.

We have an internal data structure called the `rootCallMap` which enables us to associate fields like `widget(id: $id)` with an underlying, normalized record, but (disclaimer!) I am not super familiar with it. My understanding is that we update it when writing the results for a query like `widget(id: $id) { something}`, but the _first_ time we see such a query, no mapping has been set up yet and so we can't know that we already have the data, even though we may have fetched it via a different field like `widgets` previously. (If this is egregiously wrong, please correct me @yuzhi, @josephsavona...)

I'd recommend for now sticking with `query { node( id: $id ) }` in your route.

**Comment by josephsavona** [comment]
What @wincent said - for now, use `node` to get efficient refetches. 

@steveluscher is working on supporting a wider variety of root calls (fields) including connections and I believe non-`node` "identifying" fields such as fields of the pattern `foo(id: $id)`.

**Comment by wincent** [comment]
I'm going to close this out for now. If you want to follow along with @steveluscher's work you can subscribe to #112.
