### ISSUE TITLE
Non meaningful error and application break when declaring a `GraphQLTaggedNode` from `react-relay` 

### ISSUE THREAD

**Issue by scarletquasar** [facebook/relay#4570]
# Problem

A non meaningful error is happening everytime I try to declare a content inside the `graphql` function in my logic. I'm currently using vite with the plugin `vite-plugin-relay` and properly firing the command `pnpm relay` to generate the artifacts. The following code is causing the problem that won't happen when removed:

```ts
const ContactsProfileBodyQuery = graphql`
  query ContactsProfileBodyQuery($uuid: String, $token: String) {
    getProfileWithContacts(uuid: $uuid, token: $token) {
      username,
      bio
    }
  }
`;
```

That's the error that I'm getting in the browser (that explains nothing, or am I missing something?):

![image](https://github.com/facebook/relay/assets/70824102/1a6fb920-6e90-4736-ab9b-cd828ed3520e)

# Repro repo

If needed, [this is the link](https://github.com/scarletquasar/sonozap/blob/main/apps/frontend/src/features/contacts/ContactsProfileBody.tsx#L72) for the repository (public) where I am trying to execute the query. I already set the direct link to the code file that is the problem origin.

**Comment by tobias-tengler** [comment]
You're using Vite, which only supports ESM. You seem to have forgotten to enable `eagerEsModules` in the Relay config in your package.json file. Without this setting Relay artifacts will use the `module.exports` syntax for exporting the "request object" and the Babel plugin will try to import them with `require()`. With the setting you'll be using the ESM `export default` and `import` syntax, which should satisfy Vite :)
I've noted this in the usage section of the plugin: https://github.com/oscartbeaumont/vite-plugin-relay#usage

**Comment by scarletquasar** [comment]
> You're using Vite, which only supports ESM. You seem to have forgotten to enable `eagerEsModules` in the Relay config in your package.json file. Without this setting Relay artifacts will use the `module.exports` syntax for exporting the "request object" and the Babel plugin will try to import them with `require()`. With the setting you'll be using the ESM `export default` and `import` syntax, which should satisfy Vite :) I've noted this in the usage section of the plugin: https://github.com/oscartbeaumont/vite-plugin-relay#usage

You were right, this small change worked well. I was trying to find a solution in the Relay documentation but forgot to check the vite plugin proper documentation. Thank you for this insight, I'm closing the issue.
