### ISSUE TITLE
Publish Relay vscode extension v2.1.0

### ISSUE THREAD

**Issue by alex-statsig** [facebook/relay#4576]
Tried to look for some existing tracking of this, but it would be great to see v2.1.0 of the relay extension published. It seems like currently only v1.0.2 is published from 2 years ago, despite there being some really nice updates added such as https://github.com/facebook/relay/pull/4434. Apologies if this is already tracked elsewhere

**Comment by tobias-tengler** [comment]
This is indeed very overdue

@alunyov @captbaritone I see that the last runs of the extension publish workflow weren't successful: https://github.com/facebook/relay/actions/workflows/vscode.yml 
Is this the only blocker or are there other things?

**Comment by tobias-tengler** [comment]
Locally I'm able to at least package the extension via `yarn --ignore-engines vsce package`. Could one of you maybe run the Action again? In the best case we get a release for v2.1.0 in the worst we get some logs that help us fix the workflow 😄

**Comment by alex-statsig** [comment]
Seems like https://github.com/facebook/relay/pull/4275 has some context maybe fwiw

**Comment by captbaritone** [comment]
I reran the publish job. Looks like our token is expired. I'll work on that https://github.com/facebook/relay/actions/runs/7563585985/job/20596267485

**Comment by captbaritone** [comment]
Looks like that works. Can folks try out the new extension v2.1.0 once it becomes available and check for any issues?

**Comment by captbaritone** [comment]
Quick smoke test and it seems to be working on a small sample project:

https://github.com/facebook/relay/assets/162735/a69973d3-8411-4a0e-88b2-1abdd773d8fa

**Comment by alex-statsig** [comment]
Looks good to me, general functionality seems working and the new feature from https://github.com/facebook/relay/pull/4434 that I was looking forward to is looking good. Thanks so much!

**Comment by captbaritone** [comment]
Thanks for the prompt!

**Comment by dantrain** [comment]
Hey @captbaritone thanks for publishing this, the `relay.pathToLocateCommand` feature is working great!

I was also looking forward to the `relay.projects` feature (Multiple Relay Config Options) as they are both listed in the `README.md` in `main`: https://github.com/facebook/relay/tree/main/vscode-extension#multiple-relay-config-options

However it seems that feature isn't merged: https://github.com/facebook/relay/pull/4238. Might be worth removing from the `README.md` until ready as I found it confusing when it didn't work. Thanks!
