### ISSUE TITLE
Re-fetch issue/optimization of concrete type 

### ISSUE THREAD

**Issue by filod** [facebook/relay#458]
When i use union type along with  `Connection`  or  `GraphQLList`, i got wired behevior when **reload** component (like jump back use `react-router-relay`), relay will issue some queries like 
```
query Index{
  node(id:"QW5zd2VyVm9pY2VCbG9jazo5Mjox") {
    id,
    ...__RelayQueryFragment97h2zij,
    ...__RelayQueryFragmentayvfl5w
  }
} 
fragment __RelayQueryFragment97h2zij on AnswerTextBlock {text,id} 
fragment __RelayQueryFragmentayvfl5w on AnswerBlock {__typename}
```

`node QW5zd2VyVm9pY2VCbG9jazo5Mjox` is actually a `AnswerVoiceBlock`, seems relay are trying to find  which type of this node is (or diffing against cached data)? how would i prevent these queries?

Did i miss something ? or this is a bug of relay ?

**Comment by yungsters** [comment]
Hmm... these queries are not bugs, but they are indeed under-optimized for the case where we already know the concrete type of a node. I can think of two potential optimizations here:

1. We should never have to re-fetch the `__typename` of a record which a known concrete type.
2. We should omit fragments that are conditional on concrete types if that concrete type does not match the concrete type of the node we are fetching.

Regarding the issue title, this should not be specific to connections, right?

**Comment by josephsavona** [comment]
This is a great idea. Until recently Relay didn't record the concrete type of records but now that it does `diffRelayQuery` can remove fragments on types that don't match.

**Comment by josephsavona** [comment]
merging into #539
