### ISSUE TITLE
Relay compiler fails when using custom scalars [16.2]

### ISSUE THREAD

**Issue by amonger** [facebook/relay#4617]
# Relay compiler fails when using custom scalars

Using a config of:

```
module.exports = {
  src: '../../.',
  schema: '../../schema/schema.graphql',
  language: 'typescript',
  eagerEsModules: true,
  customScalars: {
    UUID: 'string',
    Date: 'string',
    DateTime: 'string',
    Decimal: 'number',
    Long: 'number'
  },
  excludes: ['**/node_modules/**', '**/__mocks__/**', '**/__generated__/**', 'apps/docs/**/*', '**/dist/**'],
};
```
Results in 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("The config file cannot be parsed as a single-project config file due to:\n- Error(\"unknown field `customScalars`\", line: 0, column: 0).\n\nIt also cannot be a multi-project config file due to:\n- Error(\"unknown field `customScalars`, expected one of `name`, `root`, `header`, `codegenCommand`, `sources`, `excludes`, `projects`, `featureFlags`, `savedStateConfig`, `isDevVariableName`\", line: 0, column: 0).", line: 0, column: 0)', /Users/runner/work/relay/relay/compiler/crates/js-config-loader/src/loader.rs:74:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Using without customScalars builds without issue, and is fine in older versions. Documentation still says that customScalars is supported, and expected names don't make sense for the config file.

**Comment by tobias-tengler** [comment]
See the release notes of 16.2: https://github.com/facebook/relay/releases/tag/v16.2.0 This specific change is called out at the top. You have to replace `customScalars` with `customScalarTypes`.

**Comment by amonger** [comment]
Thanks for your help. Out of interest, why was a breaking change made in a minor release?

**Comment by tobias-tengler** [comment]
Probably because the change is only affecting a configuration option that isn't being used by everyone, the remedy is a simple rename and because it doesn't break things at runtime.
