### ISSUE TITLE
MockPayloadGenerator.generateWithDefer returns incorrect `path` for deferred data for list items.

### ISSUE THREAD

**Issue by jakobkhansen** [facebook/relay#4676]
Hi,

I am seeing an issue when using `MockPayloadGenerator.generateWithDefer` to generate deferred data in list items. This happens because the `path` returned in the responses does not contain the index of the list-item.

Example:

A response returns 

`["x", "y", "z", "edges", "node"]` 

which should be 

`["x", "y", "z", "edges", 0, "node"]`

Without this, the deferred data is not correctly read into the relay store and list items don't get deferred data.

Tagging @gorodscy as it seems you implemented generating deferred data in Relay quite recently.

**Comment by gorodscy** [comment]
@jakobkhansen Thanks for flagging this bug! I fixed it in [this commit](https://github.com/facebook/relay/commit/f87e77daecc4939b381d66da9964b348a2f44608). Let me know if you still encounter issues.

**Comment by jakobkhansen** [comment]
Thanks! I will test this out when we can bump our project, closing for now 😄
