### ISSUE TITLE
Variable parameter not sending in Relay 0.4.0

### ISSUE THREAD

**Issue by saikat** [facebook/relay#470]
I have a version of the relay-starter-kit that I've been trying to upgrade to 0.4.0.  I have this route:

https://gist.github.com/saikat/37b4c0dc6fec363d0607

And this is how I'm rendering it:

https://gist.github.com/saikat/fba0d41a7dbd61c18e47

This worked fine in 0.3.2 but the id parameter is no longer sending in the request payload in 0.4.0.  Here are printouts of the respective payloads:

https://gist.github.com/saikat/97c56a4a2c49b033ca8b

Has the syntax for sending parameters changed in 0.4.0?  Or is this a bug?  Thanks!

**Comment by josephsavona** [comment]
@saikat Can you confirm the version of `babel-relay-plugin` that you're using? Relay 0.4.0 requires plugin version 0.3.0.

**Comment by saikat** [comment]
That was the problem, I was on 0.2.3.  Upgrading to 0.3.0 fixed it, thanks!
