### ISSUE TITLE
Generating client mock-data in `MockPayloadGenerator` does not work due to wrong partitioning when `generateDeferredPayload = true`.

### ISSUE THREAD

**Issue by jakobkhansen** [facebook/relay#4712]
Hi,

I am seeing an issue with using `mockClientData: true` with `MockPayloadGenerator.generateWithDefer`. When generating mock-data for client extensions, Relay generates an object with the following structure:

```typescript
{
    "path": [],
    "label": undefined,
    "data": {
       ...
    }
}
```

and it seems Relay misidentifies this as an incremental update in the [partitionGraphQLResponses](https://github.com/facebook/relay/blob/5d2fa70dc6114e1a96bd8caba742c31f7f32b50c/packages/relay-runtime/store/OperationExecutor.js#L1571) function. The invariant there fails and crashes since the `path` is not `null`, but the `label` is.

**Comment by jakobkhansen** [comment]
Tagging @gorodscy, it looks like this is hitting the [STREAM/DEFER case](https://github.com/facebook/relay/blob/5d2fa70dc6114e1a96bd8caba742c31f7f32b50c/packages/relay-test-utils/RelayMockPayloadGenerator.js#L319) when both `mockClientData` and `generateDeferredPayload` options are `true`. Maybe these should be separate cases?

**Comment by gorodscy** [comment]
@jakobkhansen Thanks for flagging this. This should be fixed in https://github.com/facebook/relay/commit/6d36d763f8778c9392ac3a3fd7a2839f681a4385. Let me know if you still encounter issues

**Comment by jakobkhansen** [comment]
Thanks @gorodscy! Closing this for now
