### ISSUE TITLE
Missing export graphql query definitions from typescript types 

### ISSUE THREAD

**Issue by matclayton** [facebook/relay#4727]
Sorry I'm not entirely sure how to describe this issue, however we routinely import graphql queries in tests, for example

```
import UploadCompleteQuery from '__generated__/UploadCompleteQuery.graphql';
```

This works as expected under flow, however when using the typescript generator it appears to be available. Ideally both the flow and the typescript versions would match the docs as per https://relay.dev/docs/guides/compiler/#importing-generated-definitions

I've tried 16.1.0 and 17.0.0 and validated both are the same

**Comment by captbaritone** [comment]
When you say "works as expected" it's very hard for me to know what that means, and therefore hard to know what might be the issue.

A helpful bug report format is "here's what I expected to happen" and "here's what actually happened" width screenshots or pastes of the error message, outcome, etc. Additionally including actual code (generated artifact?) or a minimal repro could help.

**Comment by matclayton** [comment]
Sorry for the awful bug report, I was trying to wrap up at the end of a long Friday. I'll close this for now and try and get some more details. Frustratingly I've found a single example which works, so my guess is this is more likely a config issue on our end. The issue was trying to import the query from the artefact files and getting an error saying that the import could not be found.
