### ISSUE TITLE
forceFetch and setVariables fails to get a response

### ISSUE THREAD

**Issue by khe123** [facebook/relay#473]
I am dealing with a strange issue. Whenever a make a forceFetch or setVariables call in my app, the response is empty.

I isolated this problem down to the simplest app possible and it is still occurring. 

Test it out here:
https://github.com/khe123/Relay-forceFetch-problem

It is a single component that makes a read and receives a user object from memory.  The initial response is correct:
```
{
  "data": {
    "viewer": {
      "id": "dXNlcjptZQ=="
    }
  }
}
```
The problem occurs when I make a forceFetch. I get back this reponse:
```
{
  "data": {
    "node": null
  }
}
```
The resolve method for user node is not even being hit.

This looks like a bug to me. But if I making an obvious mistake please let know.

Interestingly there are no errors if I add an extra type in the schema so that the component looks like this:
```
class ChatList extends React.Component {
  static propTypes = {
    viewer: React.PropTypes.object.isRequired,
  }

  fetch() {
    this.props.relay.forceFetch();
  }

  render() {
    return (
      <div>
        <button onClick={this.fetch.bind(this)}>Click</button>
      </div>
    );
  }
}

export default Relay.createContainer(ChatList, {
  fragments: {
    viewer: () => Relay.QL`
		fragment on User{
			 otherUser{
				  id,
			 }  
		}
    `,
  }
});
```
As opposed to:

```
class ChatList extends React.Component {
  static propTypes = {
    viewer: React.PropTypes.object.isRequired,
  }

  fetch() {
    this.props.relay.forceFetch();
  }

  render() {
    return (
      <div>
        <button onClick={this.fetch.bind(this)}>Click</button>
      </div>
    );
  }
}

export default Relay.createContainer(ChatList, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on User{
        id,
      }
    `,
  }
});
```

Thanks,
Kris

**Comment by josephsavona** [comment]
@khe123 Thanks for reporting this. Can you paste the query that is sent to the server initially, and the query after forceFetch/setVariables that returns the empty response?

**Comment by khe123** [comment]
Initial query:
```
"query RootQuery{viewer{id,...__RelayQueryFragment0ki8fwc}} fragment __RelayQueryFragment0ki8fwc on User{id}"
```

Query sent after forceFetch with empty response:
```
"query Container{node(id:"dXNlcjptZQ=="){...__RelayQueryFragment0ki8fwc}} fragment __RelayQueryFragment0ki8fwc on User{id}"
```

It seems like re-fetching using the node root field is broken. Now I understand why when I made a dummy node that didn't implement nodeInterface it worked. It avoids node re-fetching. My query looks like this with the dummy node (in both cases):

```
"query RootQuery{viewer{...__RelayQueryFragment0ki8fwc}} fragment __RelayQueryFragment0ki8fwc on Dummy{user{id}}"
```
Could it be a problem with how I set up nodeField and nodeInterface? I followed the samples:
```
var { nodeInterface, nodeField } = nodeDefinitions(
  (globalId) => {
    var {type, id} = fromGlobalId(globalId);
    if (type === 'User'){
      return getViewer();
    }
    return null;
  },
  (obj) => {
    if (obj instanceof User){
      return UserType;
    }
  }
);
```

Thanks,
Kris

**Comment by khe123** [comment]
Figured it out. My nodeDefinitions was incorrect. It should type === 'user' in accordance to using globalIdField('user'). I guess this can be closed now.
```
var { nodeInterface, nodeField } = nodeDefinitions(
  (globalId) => {
    var {type, id} = fromGlobalId(globalId);
    console.log(type);
    if (type === 'user'){
      return getViewer();
    }
    return null;
  },
  (obj) => {
    if (obj instanceof User){
      return UserType;
    }
  }
);
```

**Comment by josephsavona** [comment]
Yup, the queries all look correct, the `null` response definitely seems to from the `nodeDefinitions` name mismatch. Thanks for following up with how you resolved this!
