### ISSUE TITLE
`npm install -D relay-compiler@latest` installs v12

### ISSUE THREAD

**Issue by stomvi** [facebook/relay#4730]
# Creating issues for Relay

## Reporting issues with Relay

`npm install -D relay-compiler@latest` installs v12 while it should be v17. `npx relay-compiler --version` also shows `12.0.0`.
I am used to use `relay.config.js` so it's easy to figure out v12 is installed, v12 does not recognize the config file. This happened a few times while new versions came out.

MacOS 10.14
`node@20.10.0`
`npm@10.8.1`

**Comment by tobias-tengler** [comment]
This seems like an issue in your setup. I can install the latest version just fine. Are you perhaps using your companies mirrored npm feed or something similar?

**Comment by stomvi** [comment]
Nope.

I tried to remove `node_modules` and `package-lock.json` and run `npm cache clean --force` as well as `nx reset`. Installation from the start doesn't resolve this.

Step back to v16 for now.

**Comment by stomvi** [comment]
I found that the following minimum dependencies will cause this result.

```json
{
  "devDependencies": {
    "@eddeee888/gcg-typescript-resolver-files": "^0.10.2",
    "@graphql-codegen/cli": "^5.0.2",
    "@graphql-codegen/client-preset": "^4.3.2",
    "relay-compiler": "^17.0.0"
  },
  "dependencies": {}
}
```

How could this happen?

Close this issue.
