### ISSUE TITLE
When the server fails, the client fails at failing

### ISSUE THREAD

**Issue by nickretallack** [facebook/relay#475]
If you do a mutation in Relay and it causes your server to crash, Relay will not execute the onFailure callback.

**Comment by josephsavona** [comment]
> and it causes your server to crash

What is the HTTP response (status code, headers, content) when the server crashes?

**Comment by nickretallack** [comment]
No response.  I'm talking `net::ERR_CONNECTION_REFUSED`.

**Comment by edvinerikson** [comment]
A little late answer.. 
I don't think renderFailure should be executed when a mutation fails. There is apis like [getPendingTransactions](https://facebook.github.io/relay/docs/api-reference-relay-container.html#getpendingtransactions) to check whenever a mutation failed or not.

**Comment by josephsavona** [comment]
The mutation `onFailure` callback **should** be called if the mutation fails. I'm going to close this, feel free to comment with additional steps to repro.

**Comment by edvinerikson** [comment]
Aha, thought it was renderFailure.. my bad..
