### ISSUE TITLE
Relay extension not working in 2.4.0

### ISSUE THREAD

**Issue by MrJackWilson** [facebook/relay#4788]
I'm receiving the following error in the LSP logs when hovering over any GraphQL code in my project:
```
{"jsonrpc":"2.0","id":11,"error":{"code":-32001,"message":"Request Canceled"}}
[Error - 12:30:18 PM] Request textDocument/hover failed.
  Message: Request Canceled
  Code: -32001
```

I have relay-compiler 14.1.0 installed and the latest version (2.4.0) of the relay extension. I do not have any other GraphQL extensions installed. My LSP logs are in debug mode but the above information is all I get. I've tried restarting relay through the VSCode command and I've tried restarting VSCode.

**Comment by itamark** [comment]
Hey - just curious - is the relay extension server running? Can you try running `Relay: Restart VSCode Extension Server`

**Comment by MrJackWilson** [comment]
Hey, I don't have that command in the palette. Only:
```
> Relay: Restart
> Relay: Start compiler
> Relay: Stop compiler
```

**Comment by itamark** [comment]
Got it - thanks.

Do you have this in your VSCode Outputs? Or not that, either.

<img width="553" alt="Screenshot 2024-09-09 at 10 17 50" src="https://github.com/user-attachments/assets/6fed9b9a-8d55-467c-80df-25cfd74c6b9f">

**Comment by MrJackWilson** [comment]
Yes, that's where I got the error message above from. I had the logs set to Debug.

**Comment by itamark** [comment]
I've noticed you're using an old version of the compiler (14.1.0) with the latest version of the extension.
Would you mind trying to upgrade the compiler to v 18.0.0?

**Comment by tobias-tengler** [comment]
Are you using Windows? Your issue sounds a lot like this issue I filed when I was still using Windows: https://github.com/facebook/relay/issues/3918
I fixed it as part of v15, so @itamark's recommendation of upgrading should probably fix your issue (and is a good thing in general) :)

**Comment by MrJackWilson** [comment]
I've upgraded to the latest `relay-compiler` and `react-relay` etc and this has solved the issue with the extension. Thanks a lot for the help!
