### ISSUE TITLE
Allow error response customization in DefaultNetworkLayer

### ISSUE THREAD

**Issue by LegNeato** [facebook/relay#481]
Currently `DefaultNetworkLayer` is hardcoded to keep retrying if it doesn't get a hardcoded success status code.  This doesn't work in my auth/viewer setup as far as I can see. I could maybe write my own network layer, but this behavior seems pretty inflexible and maybe a knob should be added to `DefaultNetworkLayer`?

More details:

* I have a graphql server that requires a valid `Bearer` header to accept the request (via [passportjs](http://passportjs.org/)).
* I auth outside of Relay, write the auth token to localStorage, and pass it around via `injectNetworkLayer` as suggested in various places:

```js
const token = localStorage.getItem('accessToken');
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer(..., {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })
);
```
* I pass this to GraphQL via `rootValue` for resolution of those queries.

**This all works.** :tada: 

Now for the :beetle: . I create a component like this:

```js
class TestComponent extendsReact.Component {
  render(): any {
    const name = (this.props.viewer && this.props.viewer.firstName)
      ? this.props.viewer.firstName
      : 'Unknown';
    return (
        <h1> Your name is: {name}</h1>
    );
  }
}

export default Relay.createContainer(TestComponent, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        id,
        firstName,
        lastName,
      }
    `,
  },
});
```

I want the component to render "Unknown" if the GraphQL server returns a `401` (or maybe just checking if `this.props.viewer` is null...do components have access to the response code?) or the viewer's `firstName` if they are authed.

:beetle: Unfortunately, Relay's `DefaultNetworkLayer` sees the 401 status code as an error and just keeps retrying until failure.

:point_right: It would be great for `DefaultNetworkLayer` to get a list of HTTP status codes it ignores as failures. In my case, I could ignore `401` and then have the application logic assume that because Relay couldn't pull a viewer that no one is logged in.

I could also see this being useful for `500`s...with this change you could potentially show a UI message to the user that the server is having trouble rather than it throwing an error and failing.

:question: Is the idea that the GraphQL server is always supposed to be accessible and returns errors/information via a payload instead of status codes?

**Comment by LegNeato** [comment]
I know I can do something like https://facebook.github.io/relay/docs/api-reference-relay.html#injectnetworklayer-static-method to handle the errors but I don't see any way to override the default retry behavior without duplicating a lot of logic, hence this issue. Let me know if I am missing something!

**Comment by clentfort** [comment]
If I understood the idea behind the default network layer it is more an example/reference on how to implement your own network layer and to provide a sensible default people can work with.
IMHO adding more functionality to the network layer would cause more harm than do good. It makes the usage harder and discourages people to build their own. Instead people will stuff ever more functionality that is specific to their use case into the reference implementation, making the thing bloated and hard to maintain.

Maybe the `DefaultNetworkLayer` could be renamed to `ReferenceNetworkLayer` to make it clear that it is only a reference. I'd even advocate for moving it into its own NPM package and making it an optional dependency of relay. (And mention it in the documentation a gazillion times, that it is easy to build your own.)

**Comment by josephsavona** [comment]
@LegNeato The intention of the default network layer is exactly as @clentfort mentioned - it's a reference implementation that covers the basic cases to get people started. For custom functionality such as error handling, we'd recommend writing your own network layer: the API is designed to be constrained enough that it can be implemented relatively easily.

I'm going to close this issue, but feel free to comment if you have additional questions about implementing your own network layer.
