### ISSUE TITLE
Allow changing / setting headers in DefaultNetworkLayer from custom networking layers

### ISSUE THREAD

**Issue by LegNeato** [facebook/relay#482]
Note: not sure if my suggestion is the "right" way (I am a JS n00b).

To do auth I use a bearer token and this Relay code in my App.js:

```js
const token = localStorage.getItem('accessToken');
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer(..., {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  })
);

ReactDOM.render(...)
```

The problem is I *also* use [react-router](https://github.com/rackt/react-router) to have reload-free page transitions (using `this.context.history.pushState`). This means the code above reading from `localStorage` is only loaded / executed once unfortunately. If the token ever changes (like say in a login form) Relay is blissfully unaware and keeps sending the old value even after the new value is written. :cry:  While I currently do a `window.location` whole reload after login, that doesn't help the case where I need to transparently refresh an expiring token while the user is on a page.

Ideally I would just inject a slightly custom networking layer that reads from localStorage before every request like [this](https://facebook.github.io/relay/docs/api-reference-relay.html#injectnetworklayer-static-method-example) (with a memory cache to not kill perf), but because `DefaultNetworkLayer` only lets me set `headers` at init time I either need to reimplement most of its logic or do custom networking layer. Reimplementing `DefaultNetworkLayer` is a non-starter for me at this point because I can't track Relay changes too closely and `DefaultNetworkLayer` does almost what I need it to do.

 In a custom networking layer,`RelayQuery` doesn't expose anything related to networking of course...so I can't just intercept `sendQueries`, add some headers and go. I **can** directly modify [this._init.headers](https://github.com/facebook/relay/blob/a0ba844fbce1aca795570046d9a4fcf186c58cd7/src/network-layer/default/RelayDefaultNetworkLayer.js#L132) but I take it from the underscore that it is private API and could break at any time :person_frowning: :

```js
export default class MyNetworkLayer extends Relay.DefaultNetworkLayer {
  refreshAccessToken(): void {
    const token = localStorage.getItem('accessToken');
    this._init.headers.Authorization = `Bearer ${token}`;
  }
  sendQueries(queryRequests: Array<Object>): ?Promise {
    this.refreshAccessToken();
    return super.sendQueries(queryRequests);
  }
  sendMutation(mutationRequest: Object): ?Promise {
    this.refreshAccessToken();
    return super.sendMutation(mutationRequest);
  }
}
```

:point_right:  It would be super useful to have some supported way of editing the headers sent in `DefaultNetworkLayer` from custom networking layers, so I can do something like https://facebook.github.io/relay/docs/api-reference-relay.html#injectnetworklayer-static-method-example, leveraging most logic in `DefaultNetworkLayer` and just messing with the headers.

**Comment by clentfort** [comment]
A similar question was asked in #426.
For now the easiest way is to create a custom network layer that creates a new default network layer for each requests with the correct headers set and then delegates the request to it.
I wouldn't worry too much about changes to the DefaultNetworkLayer, I am confident the team would announce any breaking changes in a similar way the react team does.

**Comment by josephsavona** [comment]
As mentioned in #481, application-specific logic such as this belongs in a custom network layer. As I mentioned there:

> The API is designed to be constrained enough that it can be implemented relatively easily.

Feel free to comment with additional questions, and let us know how it goes when implementing this!

**Comment by rturk** [comment]
Hi All can someone share code or comment how you solved implemented this?

**Comment by nodkz** [comment]
@rturk try this open sourced implementation of relay network layer https://github.com/nodkz/react-relay-network-layer

**Comment by josephsavona** [comment]
@rturk take a look at [this comment](https://github.com/facebook/relay/issues/426#issuecomment-224032838) on the linked thread - does that help?

**Comment by rturk** [comment]
@josephsavona tks helps a lot! 
However after reading this post [graphql-and-authentication](https://medium.com/the-graphqlhub/graphql-and-authentication-b73aed34bbeb#.hsoqxwdhz) I'm considering passing the token in the Viewer and not in the Header.

**Comment by sibelius** [comment]
@LegNeato u can try use a custom RelayStore that accepts to reset a network layer

like this: https://github.com/sibelius/react-native-relay-example/blob/master/src/RelayStore.js#L18
