### ISSUE TITLE
Allow to specify multiple Relay configurations on the same VS Code project.

### ISSUE THREAD

**Issue by FezVrasta** [facebook/relay#4845]
It would be very helpful if the Relay VS Code extension allowed to specify multiple Relay configurations. I'm working on a monorepo and I would like to use the extension on two different workspaces.

I tried using a VS Code workspace configuration file, but the relay extension settings only apply to the workspace root and not to specific folders.

I think the best way to implement this would be to support VS Code workspaces so that VS Code can handle it as designed, but I would be okay even with a custom configuration specific for this extension.

**Comment by orta** [comment]
I think this is what I have working in the puzzmo.com monorepo, so I'll share our setup incase its useful:

`relay.config.json`
```
{
  "root": ".",
  "sources": {
    "apps/puzzmo.com": "app",
    "apps/studio": "studio"
  },
  "projects": {
    "app": {
      "language": "typescript",
      "schemaExtensions": ["apps/puzzmo.com"],
      "output": "apps/puzzmo.com/src/__generated__",
      "schema": "api-schema.graphql",
      "eagerEsModules": true
    },
    "studio": {
      "language": "typescript",
      "output": "apps/studio/src/__generated__",
      "schema": "api-schema.graphql",
      "eagerEsModules": true
    }
  }
}
```

These all rely on a root-of-repo `api-schema.graphql` - and the vscode tooling seems to generally work as I'd expect

**Comment by FezVrasta** [comment]
Thanks! I didn't know Relay config supported multiple projects out of the box, that solves my issue, thanks again!
