### ISSUE TITLE
Relay is inlining scalar fragment variables

### ISSUE THREAD

**Issue by vladar** [facebook/relay#486]
I had an impression that Relay should extract all query and fragment variables to separate object, that is sent to the server alongside with query.

But scalar fragment variables are inlined in query. This makes some server side optimizations impossible (like caching query validation step which may be expensive).

Is it intentional? Or am I missing something?

**Comment by josephsavona** [comment]
Relay inlines scalar values largely for historical reasons - it's simple and results in printed queries that are easy to debug (they can also be slightly smaller overall). This is certainly something we could reevaluate. 

How would you cache the results of query validation? By hashing the query text? Note that the printer avoids printing the same fragment twice: for example, if you use `<ProfilePicture>` container in multiple places all with the same photo `$size`, the corresponding fragment will be printed once. If the container is used with two different sizes, the fragment will be printed once for each value of `$size`. In other words, whether or not variables are inlined, different variable values can cause the query text to be different anyway. This may make query validation caching less effective.

**Comment by vladar** [comment]
I got such impression after this comment of Lee Byron: https://github.com/graphql/graphql-js/issues/158#issuecomment-136888434 where he mentions ability to store queries on the server, validate at build time and just use query id in clients.

Would be great if we could do something like that with Relay, but I guess it might be hard for dynamic queries built by Relay.

**Comment by josephsavona** [comment]
> Would be great if we could do something like that with Relay, but I guess it might be hard for dynamic queries

Yup! We're exploring ways to save Relay queries in a build step and then upload ID + variables. The main challenges are Relay's dynamic queries and the need to map Relay's local variables into a global namespace. This is definitely on our radar though! I'm going to close this issue and file another one for the ability to save queries at build time. Thanks for asking about this!
