### ISSUE TITLE
Resolve queries if all errors are on nullable fields

### ISSUE THREAD

**Issue by vladar** [facebook/relay#487]
Relay currents rejects requests whenever the `errors` response field is non-empty. However, these errors may all be for nullable fields. Relay should not reject requests in this case, and instead should resolve a `RelayQueryRequest` whenever the `data` field is non-null _or_ there are no `errors` (indicating that all required fields could be resolved).

-- original issue --

Currently when server returns errors for nullable fields Relay will execute fail callbacks and not render.

This is different from GraphQL behavior. GraphQL still returns all other data in response, so it should be possible to render anyway.

 Only errors in non-nullable fields should break the application.

**Comment by josephsavona** [comment]
@vladar Thanks for bringing this up. By errors you're referring to application errors while resolving the nullable fields, as opposed to GraphQL validation errors, correct?

**Comment by vladar** [comment]
Yes. When `resolve` method of some nullable field throws, GraphQL will just return `null` for this field, add entry to `errors`, but still evaluate all other fields and return usable result.

Relay doesn't seem to follow this model and breaks if there is any error in response - `renderFailure` is called on such responses.

**Comment by josephsavona** [comment]
@leebyron @dschafer Is there any way for a client (Relay) to detect whether an error occurred on a nullable field instead of a non-null field?

**Comment by dschafer** [comment]
> @leebyron @dschafer Is there any way for a client (Relay) to detect whether an error occurred on a nullable field instead of a non-null field?

Nothing built in; you could check to see if `data` is completely null before erroring; that feels like the right thing to do here. The server can also customize what it returns in the error, so we could add that data there if we wanted.

**Comment by josephsavona** [comment]
@dschafer Thanks for confirming. 

In this case, `RelayDefaultNetworkLayer` should be changed to resolve the request when `data` is non-null or there are no `errors` (if non-null but there errors just log them to console), and only `reject` the request when data is null and there are errors.

@vladar any interest in submitting a PR? ;-)

**Comment by vladar** [comment]
Yeah, will do in next couple days :)

**Comment by bsr203** [comment]
I have posted a related question at SO http://stackoverflow.com/questions/38284556/relay-graphql-nullable-response-or-a-way-to-catch-query-error

any response is appreciated. thanks.

**Comment by bsr203** [comment]
@josephsavona any hint on how would you model a request where error condition not block rendering the component? I hit a roadblock and just a one liner would help me to proceed. thanks in advance

**Comment by bsr203** [comment]
@josephsavona  Thanks a lot for the response. I already have a custom network layer to format the error and would be easy to adapt.

One thing to confirm. Does this ok to do in case of null response as well (if the response can be completely optional - and client can identify this from server error code). would it cause any issue with the internal cache.

**Comment by josephsavona** [comment]
> Does this ok to do in case of null response as well (if the response can be completely optional - and client can identify this from server error code). would it cause any issue with the internal cache.

Hmm. In general, when a response is `null` Relay records that as an indication that the field cannot be fetched. If the same query is executed again it will be diffed out (unless you use `forceFetch`). I would recommend trying this approach to confirm that the behavior is as you'd expect (possibly using an empty object instead of null if necessary).

**Comment by josephsavona** [comment]
In an upcoming release we will change from rejecting requests if `errors` is present to only rejecting if `data` is missing. Thanks for the feedback here!

**Comment by jwb** [comment]
Is there a way for a component to declare that it requires its fragment to be present in order to render? 

We'd like to suppress component rendering when required data is not present in the GraphQL response, but continue to render those components whose dependencies have been satisfied based on the `propTypes` entries that specify `isRequired`.

**Comment by wincent** [comment]
As Relay Modern is now out, I believe this issue can be closed. If there are any issues related to the way Relay Modern processes responses with errors, let's create a new issue (or issues) for those.
