### ISSUE TITLE
Tests fail on Node v4.2

### ISSUE THREAD

**Issue by enaqx** [facebook/relay#488]
I've tested on Node v4.1 and it complete without errors.
![relay enaqx macbook-pro -zsh 181x45 2015-10-18 22-08-03](https://github-cloud.s3.amazonaws.com/assets/182219/10566046/c16bbb94-75e4-11e5-9182-0df0495b984c.png)

But after removing `node_modules` and switching to Node v4.2 it fails.
![relay enaqx macbook-pro -zsh 181x45 2015-10-18 22-15-37](https://github-cloud.s3.amazonaws.com/assets/182219/10566086/c8f293c8-75e5-11e5-8a1d-7d23efd935ba.png)

**Comment by clentfort** [comment]
This seems to be the same problem reported in #396. Can you try again using `npm2`?

**Comment by wincent** [comment]
Thanks for the report @enaqx! I suspect @clentfort is right about this being a dupe, so I'm going to close this one.

Please feel free to comment again if this isn't the case and we can look into this further.
