### ISSUE TITLE
Ideas for improving the Relay mutation API

### ISSUE THREAD

**Issue by saikat** [facebook/relay#489]
Sorry in advance for the long post. This is also relates to #125 and #293 .  I'm a bit new to Relay, so apologies up front if I am missing the point somewhere here/my understanding is mistaken. 

I believe the issue raised in #293 touches on a slightly larger problem with writing mutation definitions in the client. With the current API, the relay mutation needs to have knowledge of the implementation of the GraphQL mutation to a) write a reasonable getOptimisticResponse method, b) write the correct getConfigs method by knowing all the side effects the server-side mutation had, c) write the correct getFatQuery  (though I'm not entirely clear on why you would not always just write the fat query to get every possible field since it gets intersected with the tracked query anyway/why relay wouldn't just use introspection on the GraphQL API here to figure out every possible field and auto-generate this fat query).  Furthermore, with getConfigs, it seems like the relay mutation needs to know what data the rest of the app cares about (and, if that's not the case, why is it necessary to, e.g., define fieldIDs for a FIELDS_CHANGE? Why not assume all the fields in the response changed and map those to the correct relay store fields via the ID and type in the response)?

Here are some possible directions to explore to help with this issue, ranging from smallest change to biggest change, but feel free to let me know if I'm way off base here:

1. Move getConfigs to the server. We already have a way for a GraphQL server to return outputFields - why not include data about how each outputField changed there?

2. Auto-generate getFatQuery based on the outputFields of the mutation's payload. This would involve being able to do introspection on a mutation in GraphQL - is that possible already?

3. This would be the largest departure from the current model, but also the one that feels cleanest to me (and I'm sure you guys have thought of this too so I'd be curious to hear where this idea fails). Based on the options for getConfigs in relay, it seems like we already agree that the way data changes is: a field on an object is modified, an object can be deleted, or an object can be created in a list of objects.  This is nothing new - it is CRUD, just operating on the leaves of a data tree. So why have a concept of mutation functions in GraphQL at all? Unless I am missing something, these mutation functions are, at the end of the day, just a grouping of various create/update/delete operations on different parts of the data?  The only time this seems not entirely true to me is when these mutation functions have side effects outside of your own application's data (e.g. a mutation function creates a new user in your database and also charges that user money via a third-party API).   So, why not model a mutation as a list of create/update/delete operations on the data tree and have side effects that live outside of your application data be modeled as something separate (I have not put a ton of thought into how this part would look - probably just within the implementation of a create/delete/update on a field in the GraphQL server)?  This has a number of advantages:

    * Optimistic updates will be automatic (the client-side relay store just applies the list of CRUD operations on the data tree on the client before sending the list of CRUD operations to the server)

    * The set of fields that get changed is defined by the mutation, so there is no need for getConfigs or getFatQuery

    * GraphQL permissions become cleaner/more unified.  Currently, I do access authorization for GraphQL objects in the resolve methods of fields. You can imagine a world where, if mutations are just sets of CRUD operations on the fields of GraphQL objects, I define field-level modification permissions in the same place instead of having to have a second set of authorization logic in my GraphQL server per-mutation.  This means less permission logic duplication.

    * Adding new mutations to an existing GraphQL API becomes much simpler. You just enable create-ability/delete-ability/update-ability to some field of your existing GraphQL schema.

    * The API for writing mutations on the client-side could be very similar to the existing (and simple) API for creating state changes on React components. A nice API here could be something where the relay store is the single store for all client-side state and modifying it re-renders the entire React-app (see something like https://github.com/arqex/freezer).   Now, when making state changes client-side, you no longer care if that state lives in memory, on local storage, or behind a GraphQL server. Obviously in practice it may not be so clean and we may still need to distinguish between optimistically updated changes that still hit the server vs. purely client-side state changes, but it could be a lot simpler I think.

    * I realize that one of the things that you lose in this approach is the ability to group together common operations on the server into single functions (e.g. liking a story on Facebook is something you may want to expose to all users of the Facebook GraphQL API without having every client re-implement all the steps to doing this).  But these common operations (which are what we call mutations in the current world) can just be described as a set of create/update/delete operations on the fields of the GraphQL schema objects. This also makes the actual logic of these "higher order mutations" introspect-able, so the relay client can still be smart about optimistically updating a client that calls something like likeStory on a GraphQL API.

**Comment by josephsavona** [comment]
@saikat Awesome writeup! We've discussed a lot of these ideas internally as well, and the mutations API is definitely something we want to improve. There are currently several issues related to this so I've consolidated them in one meta-task at #538. Let's continue the discussion there!
