### ISSUE TITLE
Modify query name programatically

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#491]
I'm using react-router-relay and currently every query is named `Router` e.g. `query Router{viewer{id}}` *unless* I manually set the query name.

This name I think comes from these lines https://github.com/facebook/relay/blob/a0ba844fbce1aca795570046d9a4fcf186c58cd7/src/traversal/printRelayOSSQuery.js#L108-L111

I'd rather not maintain query names for every component though. It'd be nice if react-router-relay could have some way of auto-setting the query name based on the component perhaps the query comes from or if there's a route name set.

Unique query names are important for tracking query execution per component.

**Comment by wincent** [comment]
Can you show a sample of how you're setting up the routes and the query configs?

For example, if I set up a module like `ArticleQueries`:

```
import Relay from 'react-relay';

const ArticleQueries  = {
  article: () => Relay.QL`query { node(id: $id) }`,
};

export default ArticleQueries;
```

And then set up routes like this:

```
<Router history={history} createElement={ReactRouterRelay.createElement}>
  <Route component={App} path="/">
    <Route
      component={Article}
      path="wiki/:id"
      prepareParams={prepareArticleParams}
      queries={ArticleQueries}
    />
  </Route>
</Router>
```

Then the query gets named `ArticlesQueries`:

```
query ArticleQueries{node(id:"..."){...}
```

All of this using:

- react-router-relay 0.7.0
- babel-relay-plugin 0.3.0
- react-relay 0.4.0
- react-router 1.0.0-rc3

**Comment by KyleAMathews** [comment]
I'm doing something very similar except my query configs are in `router.js` hence why they're named `Router` I suppose :)

I'd rather query names be pulled from their component rather than the query config as I have only two query configs basically `node: () => Relay.QL`query { node(id: $id) }` and `viewer: () => Relay.QL`query {viewer}`.

**Comment by josephsavona** [comment]
We have some internal clients that depend on the query name matching the route name for logging and tracking purposes. This is something that should be possible to do in `react-router-relay` when queries are generated from the route + component.
