### ISSUE TITLE
Dirtying unused connections

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#494]
This is Feature request, based on #464, to keep track of it.

@yuzhi said:
>We currently fetch based on the fragments that was cached, which means having a lot of ranges can be inefficient. In the future, we might look into dirtying cached data and only fetch data needed for the current view to make this step a but more efficient.

I think its important feature, especially for use cases when many different arguments for one connection are used to filter results. If I need to reload that connection, it currently reloads connections with all argument combinations used since application started, which can get crazy.

**Comment by josephsavona** [comment]
Work is ongoing in #485

**Comment by jardakotesovec** [comment]
@josephsavona Thanks, thats awesome!

**Comment by josephsavona** [comment]
merging into #537

**Comment by jardakotesovec** [comment]
@josephsavona Amazing, thanks!
