### ISSUE TITLE
Create Fragment string through Array.prototype.join

### ISSUE THREAD

**Issue by Globegitter** [facebook/relay#498]
Something like
```js
const testKeys = ['testId', 'testName', 'description', 'shareType', 'testPrice', 'balance', 'quantity',
  'cleitns'];

export default Relay.createContainer(FundsPage, {
  initialVariables: {
    testArg: 'hello'
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on FundViewer {
        funds(customArg: $testArg) {
          ${testKeys.join(', ')}
        }
      }
    `
  }
});
```

does not seem to work currently. Relay throws `Uncaught Error: Invariant Violation: RelayQL: Invalid fragment composition, use `${Child.getFragment('name')}`.`.  As soon as I replace that join and add the keys manually the request all works fine.

The reason I want to define the keys in an array is that I am using the exact same keys for table-headers and do keep the code dry and the update effort low.

**Comment by josephsavona** [comment]
Thanks for the question! Relay.QL queries are transformed at compile time via the `babel-relay-plugin`, which requires all the fields of a query to be known (declared) statically. This step annotates each field with metadata from the schema without which Relay can't process the query. 

So for this use-case we'd recommend adding the keys to the query manually.

**Comment by Globegitter** [comment]
@josephsavona Sorry to just get back so late, just taking relay-implementation up again. It would be nice if babel-relay-plugin could detect a 'statically' declared variable in the same file but I suppose that would be a lot of effort to gain just a little bit of DRYness.

Thanks for getting back so quickly though, loving relay and graphql so far!
