### ISSUE TITLE
Replace Relay.Route with RelayQueryConfig and Relay.RootContainer with RelayRenderer on homepage examples

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#503]

**Comment by michaelchum** [comment]
@steveluscher The [Relay public API](https://github.com/facebook/relay/blob/master/src/RelayPublic.js) currently does not expose `RelayQueryConfig`. Are you planning on exposing it to subclass `Relay.RelayQueryConfig` as a standard instead of `Relay.Route`?

**Comment by steveluscher** [comment]
Indeed. I just created this issue so that I wouldn't forget about the homepage when this happens!

**Comment by josephsavona** [comment]
Closing; we'll update the examples when we release the new APIs from #1369.
