### ISSUE TITLE
npm install fails in examples

### ISSUE THREAD

**Issue by michaelchum** [facebook/relay#505]
`npm install` fails in `examples/star-wars`, `examples/todo` and `examples/relay-treasurehunt` with missing module error.
<img width="1192" alt="screenshot 2015-10-23 00 40 39" src="https://cloud.githubusercontent.com/assets/3792228/10687045/e348686a-791e-11e5-9dc2-6f52b6edd15f.png"> I'm on the latest `master` branch with `node 4.2.1` and` npm 2.14.7` on OS X Yosemite. 

`npm install` in `relay/` works fine.

**Comment by michaelchum** [comment]
After some investigation, I believe this is caused by the addition of the `postinstall` script to Relay's `package.json` in [this recent commit](https://github.com/facebook/relay/commit/3035c12b5a46914e3fb847993effb3e31d0ca6fa#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R25). Removing the `postinstall` script makes it work properly.

I think when a project `npm install` its dependencies, all the corresponding `postinstall`'s of every dependency is also run. However, there must be a bug in `npm`. During the `postinstall` of the `react-relay` dependency, it thinks `react-relay` is located in `./node_modules/react-relay` while we specified it to be in `../..`

**Comment by zpao** [comment]
Ah yea. The bigger issue is that the `postinstall` hook will also be run when you ship a package to npm. The failure looks a lot like this. But we can't use `preinstall`. Perhaps we can use `prepublish` (and then we might need to fix some resolution pieces to make it work in examples).

**Comment by michaelchum** [comment]
Moving `postinstall` to `prepublish` actually makes `examples/` work. I think when we `npm install` a project the `prepublish`'s of it dependencies is not run, it is only run on a local `npm install`. Should I submit a PR for this?

**Comment by wincent** [comment]
I think that would be acceptable, @michaelchum.

The main intention of this check is to make sure that people developing in the Relay repo are using a known-to-be-supported tool-set, so that they can do things like run the tests without spurious failures. So in this case, `prepublish`, which will run when you do a top-level `npm install`, is probably good enough.

If you run `npm install` from the `examples/` directories, then this parent `prepublish` may not run, like you say (although it would be good to confirm that for sure), although that may be ok.

**Comment by michaelchum** [comment]
@wincent Thanks for the clarification! It says in the [npm docs](https://docs.npmjs.com/misc/scripts) that `prepublish` only runs before a package is published or in a "local" `npm install`. There's no mention of dependency install.

As you mentioned, since this script helps people developing Relay and not people using Relay as a dependency, I think it makes sense to move it to `prepublish`.
