### ISSUE TITLE
Websockets and Relay

### ISSUE THREAD

**Issue by mencken** [facebook/relay#51]
What are the current thoughts on using Websockets in the network layer?  

How would you keep all clients up-to-date when a mutation is sent from a single client?  In the other clients' environment, it would just receive a query response but, there wouldn't be a request object to go with it in the network layer.  Or is it as simple as Relay is not made with this kind of data flow in mind?

**Comment by steveluscher** [comment]
cc/ @laneyk

**Comment by devknoll** [comment]
There's also an ongoing discussion about subscriptions in GraphQL going on in #subscriptions channel on slack (www.github.com/facebook/graphql) which may(?) address this use case.

**Comment by wincent** [comment]
> Or is it as simple as Relay is not made with this kind of data flow in mind?

It's definitely within scope. As @devknoll mentioned, we are actively discussing what subscriptions should look like in open source GraphQL. Internally, we already have a prototypes that work with Relay, but they depend on bits of internal infra. We need to figure out how best to tackle this in open source, and websockets may be part of the solution.

**Comment by josephsavona** [comment]
Thanks for the great question! I've documented this in the wiki - please feel free to re-open if you have additional questions.

wiki: https://github.com/facebook/relay/wiki/Frequently-Asked-Questions#does-relay-support-real-time-updates

**Comment by toogy** [comment]
What is the current status of this? Any progress for real-time updates with Relay? Thanks!

**Comment by josephsavona** [comment]
@toogy We're tracking progress on this at #541. There are some open PRs from the community but we haven't had the bandwidth to support these well. Once #558 and #559 are complete we should be in a better place to focus on this.
