### ISSUE TITLE
Unable to use Relay with stateless components

### ISSUE THREAD

**Issue by vslinko** [facebook/relay#511]
I'm using Relay with [recompose](https://github.com/acdlite/recompose).
Recompose using stateless components inside.
When I wrap any Recompose decorator with Relay Container then I get this error:

```
Warning: Stateless function components cannot be given refs
(See ref "component" in doOnReceiveProps(mapProps(Theme(ProjectsList)))
created by Relay(doOnReceiveProps(mapProps(Theme(ProjectsList))))).
Attempts to access this ref will fail.
```

**Comment by tarun** [comment]
same warning with any simple stateless component/function
:+1:

**Comment by frodosamoa** [comment]
:+1:

**Comment by joshthecoder** [comment]
Seeing the same warnings as well. :cry:

**Comment by taion** [comment]
The upstream React issue is at https://github.com/facebook/react/issues/4936.

Would it be reasonable just to not add the `ref` when the component in question is stateless?

**Comment by taion** [comment]
Oh, I see this is already being handled in #525.
