### ISSUE TITLE
RANGE_DELETE `deletedIDFieldName`, could it be a path too?

### ISSUE THREAD

**Issue by luisobo** [facebook/relay#516]
Hi,

I'm implementing a RANGE_DELETE mutation, which all does is removing an entity from a collection but it does not delete the entity itself.

My `getFatQuery` looks like this:
```
  getFatQuery() {
    return Relay.QL`
      fragment on RemoveEntityFromCampaignPayload {
        campaign
        entity
        entityId
      }
    `;
  }
```

My `getConfigs` looks like this: 
```
  getConfigs() {
    
    return [{
      type: 'RANGE_DELETE',
      parentName: 'campaign',
      parentID: this.props.campaignId,
      connectionName: 'entities',
      deletedIDFieldName: 'entityId',
      pathToConnection: ['entities']
    }];
  }
```

It seems to make sense to include the entire entity object in the payload so it seems redundant to include its id in the top level of the payload. Ideally, I'd remove that `entityId` field from the payload and allow to pass an array to `deletedIDFieldName` like `['entity', 'id']`, just like `pathToConnection` . So it resolves the id from there, allowing the payload to be cleaner and more generic.

Thoughts?

Thank you!

**Comment by sampepose** [comment]
This was added in b43dc72683c285e21d9e0e52be87b7d66dab5029.

`deletedIDFieldName`: the field name in the response that contains the DataID of the removed node, or the path to the node removed from the connection.
