### ISSUE TITLE
Deprecate Relay.RootContainer in favor of <RelayRenderer>

### ISSUE THREAD

**Issue by yungsters** [facebook/relay#528]
- [ ] Replace `Relay.RootContainer` documentation with some for `<RelayRenderer>`
- [x] Make `context` a required prop of `<RelayRenderer>`
- [ ] Have `Relay.RootContainer` make the choice of a default context
- [ ] Deprecate `Relay.RootContainer`

**Comment by bigblind** [comment]
I'm starting to implement an app using Relay. How drastic is this change going to be? Should I look into RelayRenderer from the start, to minimize work in the (near) future, or will the upgrade process be smooth enough that I can just start out using RootContainer, and replace it once this is implemented and released?

**Comment by josephsavona** [comment]
If we're going to make `context` a required prop, this will depend on #558 which has a few outstanding tasks and pending diffs. The alternative is to go ahead with the deprecation now and introduce the context prop later - possibly gradually by first making it optional with a warning, then required in a subsequent release.

**Comment by wincent** [comment]
We're unlikely to take any more concrete steps on this, with [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable) just around the corner (which will have a new renderer), so I am going to close this out.

To belatedly answer, @bigblind's question:

> I'm starting to implement an app using Relay. How drastic is this change going to be?

The APIs for `Relay.RootContainer` and `RelayRenderer` are very similar, so the conversion path is pretty straightforward. And to answer the question you didn't ask, we're aiming to make the path to Relay 2 as smooth as possible too. We'll provide more details as we get closer to release.
