### ISSUE TITLE
Better workflow for examples & relay-starter-kit

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#53]
Might be worth coming up with a better workflow to manage these projects. It's great that they can all run out of the box with their own `npm install`, but so far any change to one of them means a change to all four.

We should see if we can come up with a script to generate the shared bits (similar to react/addons in 0.14.0). We could keep the output in git to keep it easy to use (if that's a goal) or just add a top level task to generate them.

:wink:

**Comment by wincent** [comment]
@steveluscher: thoughts?

**Comment by steveluscher** [comment]
Great idea! At the moment, I'm happy to make changes in four places until such time as building automation starts to pass the XKCD test, but if you have time or ideas I'm happy to have you run with it.

**Comment by yungsters** [comment]
Also curious to hear if @zpao has any feedback.

**Comment by zpao** [comment]
I tend to agree with about XCKD test with the added caveat that feeling like you're wasting time doing manual changes might be worse than actually wasting time.

FWIW, now is probably the *most* churny time for the examples as we work out of the technical preview. This might stop being an issue soon.

**Comment by devknoll** [comment]
> FWIW, now is probably the most churny time for the examples as we work out of the technical preview. This might stop being an issue soon.

Totally agree. Tell you what, I'll close this out for now and keep an idea on it. I'll reopen if after some time it still feels like a big deal.
