### ISSUE TITLE
babel-relay-plugin is not working with babel 6.x

### ISSUE THREAD

**Issue by mapduty** [facebook/relay#533]
```
Module build failed: TypeError: Plugin is not a function
    at getBabelRelayPlugin.js:44:12
```

**Comment by schweller** [comment]
That's most probably because babel 6.x changed smoothly the way that babel's plugin API works.
Changing this lines should get the job done: 
https://github.com/facebook/relay/blob/master/scripts/babel-relay-plugin/src/getBabelRelayPlugin.js#L47-L48

Docs: http://babeljs.io/blog/2015/10/29/6.0.0/

**Comment by teaegg** [comment]
I simply removed the `new Plugin()` and rebuild,  got error

```
Cannot read property 'opts' of undefined
    at PluginPass.Program (node_modules/babel-relay-plugin/lib/getBabelRelayPlugin.js:49:20)
``` 

after converted the router in relay-starter-kit
```javascript
export default class extends Relay.Route {
  static queries = {
    viewer: () => Relay.QL`
      query {
        viewer
      }
    `,
  };
  static routeName = 'AppHomeRoute';
}
```
to: 
```javascript
class AppHomeRouter extends Relay.Route {}
AppHomeRouter.queries = {
  viewer: () => Relay.QL`
    query {
       viewer
    }
  `,
};
AppHomeRouter.routeName = 'AppHomeRoute';
module.exports = AppHomeRouter;
```
error disappeared and transformed successfully. however, it's still not working.

**Comment by josephsavona** [comment]
Yup! The new version *just* came out, and we'll update as soon as feasible.

**Comment by alvinthen** [comment]
Any workaround for now besides reverting back to babel v5.x?

**Comment by philostler** [comment]
+1 just hit this and would love a workaround without have to downgrade

**Comment by indiejoseph** [comment]
+1

**Comment by mikestaub** [comment]
+1

**Comment by josephsavona** [comment]
@sebmck himself is helping out on this - hang in there!

**Comment by amenuor** [comment]
Hello, I hit this issue too but I couldn't wait :)
I have a working solution at this repo: https://github.com/YanchWare/relay 
Maybe it can help for the final solution.

It is not based on the latest version of your code, but on the release 0.3.0 (I think - version from facebook/relay-starter-kit)

**Comment by leebenson** [comment]
This looks pretty easy to fix... I got `scripts/build-lib` working with a combination of the following:

**Bump babel versions**

Something like this in `package.json`:

```
  "devDependencies": {
    "babel": "^6.1.5",
    "babel-jest": "^6.0.1",
    "babel-plugin-syntax-object-rest-spread": "^6.1.4",
    "babel-plugin-transform-flow-strip-types": "^6.1.4",
    "babel-preset-node5": "^6.1.4",
    "flow-bin": "0.18.1",
    "glob": "^6.0.1",
    "jest-cli": "^0.7.1",
    "minimist": "^1.2.0",
    "mkdirp": "^0.5.1",
    "rimraf": "^2.4"
  },
  "dependencies": {
    "babel-core": "^6.1.4",
    "graphql": "0.4.12"
  },
```

**Create a .babelrc with the right plug-ins to parse**

Running Node 5.x locally, the config looked something like:

```
{
  "presets": [
    "node5"
  ],
  "plugins": [
    "transform-flow-strip-types",
    "syntax-object-rest-spread"
  ]
}

```

**Change `babel` to `babel-core`**

Updating the reference in `scripts/build-lib`, and anywhere else it's used.

**Re-write a few lines in `getBabelRelayPlugin.js`**

This...

```
  return function (_ref) {
    var Plugin = _ref.Plugin;
    var t = _ref.types;

    return new Plugin('relay-query', {
      visitor: {
```

Should look more like...

```
  return function(_ref) {
    var t = _ref.types;

    return {
      visitor: {
```

There may be a bit more to it than that, but that got over the initial errors.

**Comment by shaimo** [comment]
+1. Got stuck...:-(

**Comment by gblache** [comment]
+1

**Comment by shuhaodo** [comment]
+1

**Comment by namtran3005** [comment]
+

**Comment by chrisgwgreen** [comment]
+

**Comment by josephsavona** [comment]
Per the above comment, we will upgrade the plugin for babel 6 as soon as feasible.

**Comment by shuhaodo** [comment]
guys, other alternatives? I'm pretty much stuck at this point. If someone can point me to Babel transpile doc I can try fixing it. I'm down to "Program(node, parent, scope, state)" and "TaggedTemplateExpression(node, parent, scope, state)" - the problem is that, "state" is always undefined but lots of references to it:  var documentName = state.opts.extra.documentName;

I guess the "state" parameter is changed in Babel 6. I see other plugins using "(node, parent, scope, file)" parameters. @sebmck, if you can point me to the doc would be great!

**Comment by gblache** [comment]
I downgraded to 5.  I spent some time trying to update the plugin yesterday but punted after a few hours because it sounded like the whole Relay app was being updated/ported internally (per this thread).

Happy to jump on a branch and take a stab this weekend if you have anything public/pushed.

**Comment by amenuor** [comment]
@shuhaodo @gblache I have spent some hours on this and I pushed all my changes to the branch here: https://github.com/YanchWare/relay
The plugin should be 100% working all tests passing, but I haven't had the time to test it in a real application.

The full relay package is also building fine now, but around 70% of the unit tests are failing. So... something is clearly wrong :) I do not think I will have more time this weekend for this, but if you feel like it that is quite a nice challenge :) You can continue where I left.

Btw I also suspect that someone else is "officially" porting this to babel6, but no idea if that is the case and when that is going to happen.

**Comment by shuhaodo** [comment]
@amenuor So cool! Should the whole relay package be replaced or just the babel-relay-plugin?

**Comment by amenuor** [comment]
@shuhaodo well depends what you want. If you want the latest version in the relay repository, then you will may try the full relay package as it is, but as I said unit tests are not passing so I do not think it will work.

If instead you need a quick and dirty solution (as I did too :) ) then you can use the latest official release of relay (the one for instance used in the starter kit at https://github.com/relayjs/relay-starter-kit ) with the plugin modified as in this change set https://github.com/YanchWare/relay/commit/c56891ac52c6c4aba41b4e5f7c5b41eba0818ac6 (modify directly the 2 js files under the plugin folder in node_modules/babel-relay-plugin/lib )

**Comment by shuhaodo** [comment]
I just took the plugin and it works like a charm, thank you!

**Comment by josephsavona** [comment]
If you're on master, `babel-relay-plugin` should work out of the box with babel 6 as of ba004a491f6a5ee278c01522d9f17a92a18b56bb. We'll upgrade the examples, tests, etc to use babel 6 at a later date.

**Comment by gblache** [comment]
:clap:

**Comment by voodooattack** [comment]
Please push this to npm. I can't wait to start working on my new project.

**Comment by steveluscher** [comment]
@voodooattack OK!
