### ISSUE TITLE
[meta] Implement field-level cache eviction and query tracking

### ISSUE THREAD

**Issue by josephsavona** [facebook/relay#537]
Relay currently retains two sets of information for the lifetime of a user session:
1. The cache of previously fetched server data.
2. The corresponding "tracked queries" that describe the queries used to fetch the cached data.

This has served us well, but causes a problem in larger apps that mutations must refetch *all* affected data, as opposed to only the affected data that is also being actively rendered.

Furthermore, some records in the cache can grow quite big - for example the 'viewer' node - and ideally unreferenced fields could be evicted from the cache.

This is a meta task to track the work on changes to query tracking and field-level cache eviction.

Work is ongoing in #485.

**Comment by grydstedt** [comment]
@josephsavona Is there any undocumented way to do this currently (before this is done)? Primarily to throw away the entire store and all cached data?

**Comment by kassens** [comment]
The `forceFetch` ([docs](https://facebook.github.io/relay/docs/guides-root-container.html#force-fetching)) property of RelayContainer can be used to load the full query of the component tree overwriting that's been fetched. This can often help work around this issue.

**Comment by josephsavona** [comment]
I experimented with this in #485 and spun off some ideas into separate commits, but this ultimately didn't pan out. We'll continue exploring ideas around cache eviction. As @kassens noted, `forceFetch` can be used to forcibly refetch information when necessary.

**Comment by grydstedt** [comment]
Unfortunately I can't use `forceFetch` in this case. I have to deal with a stale values in strange ways. I can create a separate ticket for it.
