### ISSUE TITLE
Simplify RANGE_ADD mutations

### ISSUE THREAD

**Issue by josephsavona** [facebook/relay#542]
RANGE_ADD mutations are common cause of confusion for users. In particular, if the application does not query for the connection, the field for the new edge is not included in the mutation fragment. This winds up issuing [this warning](https://github.com/facebook/relay/blob/411780d258fe3d4845ca9ab5d9f292100f2306c4/src/traversal/writeRelayUpdatePayload.js#L326-L333). Users expect the new edge to be fetched, but Relay doesn't have sufficient information to do so. This is because Relay doesn't know what fields should be fetched.

We should make it easier for users to get predictable behavior with range add mutations - either by strict `invariant`s to require the connection to be queried in advance or, possibly, with some other way to define the fields that should be queried on an edge in the case that the connection is not already queried.

**Comment by josephsavona** [comment]
per @steveluscher:

> The task. Given a RANGE_ADD mutation config:
> 1) If Relay never queries for the new edge because they were eliminated during the intersection of the tracked and fat queries, explain that there's a client-side problem and how to fix it (namely to make sure the parent/connection is used – ie. tracked – in your app)
> 2) If the server never responds with the newly created edge despite having been queried for it, explain that the problem is on the server side.

**Comment by Gregoor** [comment]
Shouldn't it be possible as well to have mutations that change connections which might or might not be tracked? Why even throw an error in the case where the connection is not tracked (and thereby no edge is returned)?

**Comment by dminkovsky** [comment]
Re:

> Users expect the new edge to be fetched, but Relay doesn't have sufficient information to do so. This is because Relay doesn't know what fields should be fetched. —@josephsavona 

In troubleshooting this issue, I considered this may be the case, but then thought: "but then why `RANGE_ADD` configuration have the `edgeName` field? Isn't that how Relay determines what to query for?" I guess just knowing the `edgeName` field isn't enough because it doesn't know the structure of the node? Might this structure come from the fat query?

**Comment by wincent** [comment]
I'm going to fold it into a checklist in #538, which is about overhauling the mutations API. (It will be easier to manage with the various interrelated mutations issues in a single place.)
