### ISSUE TITLE
`componentWillReceiveProps` will not be called when use `forceFetch`

### ISSUE THREAD

**Issue by filod** [facebook/relay#546]
bug or feature ?

**Comment by kassens** [comment]
`forceFetch` instructs Relay to fetch the full query from the server and not leave out fields it already has. If it fetched them and they're still identical, we don't force a React re-render.

Did you see that the props indeed changed but `componentWillReceiveProps` was not called?

**Comment by filod** [comment]
this could be my mistake, sorry about that
