### ISSUE TITLE
more readable query for debugging

### ISSUE THREAD

**Issue by gre** [facebook/relay#547]
Hi,

GraphQL queries generated by Relay are barely readable, and when debugging something (especially on a server side bug), it is important to have it readable.

**(1)** Wouldn't it be possible to have a **DEV mode**, where queries would be at least well formatted (indented and with new lines) ?

**(2)** At best, it would be neat to have better naming for the fragments and renamed properties (like A, B, C, D ...), i'm curious to know the reason why these are that long? (don't you want to minimize the bandwidth)

```
fragment __RelayQueryFragment4ugj39w on Foo{ id, ...__RelayQueryFragment547ytpa }
```

=>

```
fragment __A on Foo {
  id,
  ...__B
}
```

---

> The same way React is helping the developer in __DEV__, I think it's important that Relay help on this subject.

**Comment by josephsavona** [comment]
Making queries easier to debug is a great idea. Having different implementations between DEV and production can lead to subtle bugs, so we probably won't have a DEV printing mode. However, we should look at making the future Relay dev tools pretty-print queries.

cc @kassens

**Comment by yusefnapora** [comment]
In our relay server we've been using this in dev mode:

```javascript
import {print} from 'graphql/language/printer';
import {parse} from 'graphql/language/parser';

router.use((req, res, next) => {
  const prettyQuery = print(parse(req.body.query));
  // log query however you like.  we're using the 'winston' module:
  const query = colors.green(prettyQuery);
  winston.info(colors.cyan('Running GraphQL query\n'), query);
  next();
});
```

It doesn't help with the mangled names, but at least everything is formatted nicely & it's much easier to read.

**Comment by gre** [comment]
nice!

**Comment by josephsavona** [comment]
@yusefnapora awesome! @kassens let's keep this in mind for dev tools (if you didn't implement it already ;-)
