### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by knowbody** [facebook/relay#55]
I get an error while trying to run tests: `npm run tests`

this is what I get:
<img width="554" alt="screen shot 2015-08-13 at 11 48 54" src="https://cloud.githubusercontent.com/assets/3802023/9248157/5cdcc40a-41b1-11e5-8176-5bffe51b7fb8.png">

**Comment by fson** [comment]
@knowbody Jest not working on node 0.12.x is a known issue (see https://github.com/facebook/jest/issues/243). For me the tests started working after installing node 0.10 and running `npm rebuild`.

From #10 it seems that as soon as Jest 0.5.0 stable version gets released, this project can move to iojs and the old version of node is no longer needed.

**Comment by knowbody** [comment]
oh, make sense now, thanks @fson!

**Comment by knowbody** [comment]
we could mention that in the README I guess.

**Comment by fson** [comment]
@knowbody I think that's a good idea. There's a warning from `npm install` if you're running an unsupported version, but it's pretty easy to miss.

**Comment by knowbody** [comment]
so which version should I use? v0.10.0?
I'm using [n](https://github.com/tj/n) for managing node versions but with 0.10.0 I get errors when I try to do `npm install`

**Comment by fson** [comment]
@knowbody I installed v0.10.40, which is the latest 0.10.x release and it worked with that.

**Comment by knowbody** [comment]
with 0.10.40 fails. I get:
```
npm ERR! 404 Not Found
npm ERR! not ok code 0
```

**Comment by yungsters** [comment]
@knowbody Try double checking your `npm --version`. I know whenever I re-install 0.10.x, the `npm` I get is archaic (v1.x.x).

**Comment by knowbody** [comment]
@yungsters I don't know actually what happened but tried to `npm install` yesterday again and it worked with node 0.10.40 and npm 1.4.28.

I just think we should add clear instructions as it's important to run those tests locally and I'm guessing most of ppl use 0.12.7.

any ETA on when Jest 0.5.0 stable will be released?

**Comment by josephsavona** [comment]
Thanks for bringing up this issue - I've documented the configuration required to run tests at https://github.com/facebook/relay/wiki/Frequently-Asked-Questions#error-running-npm-test - please feel to reopen this if there are any additional questions.

**Comment by cpojer** [comment]
I published jest 0.5 today and sent a pull request to upgrade relay to iojs and jest, see #74
