### ISSUE TITLE
Option for skipping mutations in queue

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#550]
I have several use cases with optimistic updates  where user can make several changes on the same thing quickly which results in several mutations on the same thing. Lets say I have text input for user name.

If I handle that with optimistic updates - it works nicely, only issue is that it sends request for every letter (serially thanks to collision key), which can take a while. It would be handy for these situations be able to set some option on mutation which says that it can skip all queued mutations with that same collision key.

**Comment by josephsavona** [comment]
That's a good idea, it would be great to have support for this. Any interest in submitting a PR?

**Comment by jardakotesovec** [comment]
@josephsavona Yes.. that should not be that difficult as my first time Relay contribution.

But not sure if make more sense to just silently remove pending transactions from the queue or make them fail so the transaction callback gets always called. It would be necessary indicate that the failing reason (probably via status) is that it is skipped.

I am inclining to the first option - just remove pending transactions (and all relevant clean up) as its easier and I don't see much benefit of calling the failure callbacks. But would like your opinion.

Also we need good api name for it, here are some ideas: `shouldClearCollisionQueue`/`shouldSkipCollisionQueue` or shorter options: `shouldClearQueue`/`shouldSkipQueue`

**Comment by josephsavona** [comment]
Two mutations with the same collision key may be initiated from different parts of UI and be unaware of each other. There should be *some* callback that fires in the case of a mutation to allow for any cleanup, though I agree that `onFailure` isn't appropriate for this case. 

@yungsters @wincent Thoughts on switching to either an `onReadyStateChange`-style callback with props such as `{error, aborted, data}`? Calling `onSuccess` when a mutation isn't intuitive.

**Comment by devknoll** [comment]
What if throttling/debounce was made a user responsibility instead? I.e. Relay just provided control to add/remove mutations from the pending store, and a function to finally commit (and send) the mutation?

**Comment by devknoll** [comment]
Implementing throttle/debounce on top of that would be trivial: create a mutation and add it to the store, but don't commit it. If another mutation comes in, the app can remove the last mutation, and add a new one. After the debounce threshold, it can commit the change (with normal collision key behaviors).

**Comment by jardakotesovec** [comment]
I like @devknoll 's idea as it helps cover reasonable use case when user want to control (postpone) when update it sent to server. 

To keep discussion moving forward, here are some api ideas based on that idea:
Relay.Store.queue(mutation).commit(callbacks) could be equivalent to Relay.Store.Update(mutation, callbacks).

Both methods `queue` and `update` would return reference to transaction, which would have method `dequeue()`. This method would return `true` if dequeue was done (has not been sent to server yet).

So for use case when you just want to skip pending mutations, I would just keep reference to one transaction and call `dequeue()` before passing new mutation to `update`.

And for situation I want to postpone (wait for some saving event) updating server I would use `queue(mutation)` method and once I want to save it I would call `commit(callbacks)` on that transaction.

Also it can be easily combination of these two use cases. Thoughts?

**Comment by josephsavona** [comment]
Hmm. How about:

```javascript
type RelayStore = {
  update(mutation: RelayMutation): MutationTransaction;
};
type MutationTransaction = {
  preview(): void; // need a better name
  commit(): void;
  rollback(): void;
};
```

This covers all of the above use cases, and also allows Relay to track the sequence in which the updates were originally created and revert/apply them in the correct order in cases where the user did create two overlapping mutations and want to commit both. Of course, naming is hard: `(en)queue` doesn't really work, `preview` feels wrong. If anything explicit might be better with e.g. `applyOptimisticUpdate` and `applyServerUpdate`.

**Comment by devknoll** [comment]
Do we need a `preview()`? What if *previewed* was the default state after calling `RelayStore.update` and `MutationTransaction` just allowed for committing & rolling back?

**Comment by josephsavona** [comment]
That makes so much sense.

**Comment by kassens** [comment]
I like the way this is headed. I want to add is that we should make a basic API that auto-"commits". The manual control seems like it should be the advanced use case. We could rename the `update` method from @josephsavona's comment to `updateLocal` which makes it clear that it's uncommitted. This would free up `update` to be defined as `updateLocal().commit()`.

**Comment by devknoll** [comment]
:+1:

**Comment by josephsavona** [comment]
anyone want to write the PR? ;-)

**Comment by xuorig** [comment]
@josephsavona @devknoll I'd like to come up with a PR for this unless someone has started. From what I understand this is basically just coming up with a new function on the store, `updateLocal`, that will create a transaction without commiting it ? 

It seems like thats all we need to allow debounce since we have `commit` and `rollback` on the `Transaction` already. Let me know if I underestimate the issue :dancer:

**Comment by josephsavona** [comment]
No on is working on this, and it is now trivial to implement thanks to 6c41756 - the new method can be 

`Relay.Store.updateLocal(mutation, ?callbacks): RelayMutationTransaction` - basically return the object created by RelayMutationQueue.createTransaction w/o committing it.

**Comment by josephsavona** [comment]
@xuorig - all yours! :-)

**Comment by wincent** [comment]
Unless I'm mistaken, I believe all related work for this issue is now complete, so I'm going to close this. If that turns out to be wrong, please comment and I'll re-open.

**Comment by jardakotesovec** [comment]
@wincent Its possible to delay committing mutation to server, but its not possible to skip mutation that is already in queue yet.

This use case make sense for situations when there is no save button and user is changing input or some slider that could potentially generate many mutation requests and its necessary to skip queued mutations to do that efficiently - basically skip intermediate values.

Most convenient for developer would be to have api directly in mutation `shouldSkipQueue ` that I suggested at the beginning, that would just say if mutation should remove mutations in the queue.

Agreement here was to handle this out of relay, so I attempted to add possibility to rollback queued mutation in #646 .

But I am generally opened to any other solution for such use case that will play nicely with new mutation api. Using optimistic updates became very convenient..  as its not necessary to keep some additional state.

**Comment by proProbe** [comment]
hello everyone! just wanted to see the state of the `skipping queries` in the que. This would greatly improve my application (written in react-native) where there's always a problem with datafetching. Skipping queries in the que doesnt seem to be implemented yet? Are there other ways to do this?

**Comment by xuorig** [comment]
Hey @proProbe I wrote a small blog post on how you can use the `applyUpdate` API to do this. http://mgiroux.me/2016/relays-apply-update-function/

Let me know if it helps?

**Comment by proProbe** [comment]
thanks for the blogpost @xuorig! It looks really useful but Im not sure how it ties into my problems with `skipping queries` that is qued up. Lets say I make during 2 seconds about 10 queries via user interaction. Im currently seeing that only 6 of the queries are sent and the other 4 is qued up. What I actually want to do is to somehow have control on when to skip these 4 queries :)
