### ISSUE TITLE
[docs] Relay requires mutations to be top level

### ISSUE THREAD

**Issue by gre** [facebook/relay#551]
I'm trying to use a mutation that exists at a nested level in my schema:

```js
  getMutation() {
    return Relay.QL`mutation { me { setStatus } }`;
  }
```

However, Relay validation plugin throws: 

> Error: Your schema defines a mutation field `me` that takes 0 arguments, but mutation fields must have exactly one argument named `input`.

Does that mean Relay doesn't support nesting or is that just a bug in the validation plugin?

**Comment by josephsavona** [comment]
Mutations must be defined as top-level fields of the mutation type in your GraphQL schema. In the example above, `me` is the mutation, and `setStatus` is a field in the response payload.

**Comment by gre** [comment]
but GraphQL spec allows it right? (that you can group mutations into sub-objects)
so I guess Relay only support a subset of that spec where mutation are all in top level?

**Comment by gre** [comment]
(maybe this should be written somewhere in the documentation, I don't know where exactly)

**Comment by kassens** [comment]
I'm no expert on the GraphQL spec, but it seems pretty clear to me that mutations have to be top level fields under a `mutation`. See [Starting Types in the GraphQL spec](http://facebook.github.io/graphql/#sec-Starting-types).

What gave you the impression the mutations could be nested? There might be something to clarify in the spec!

**Comment by gre** [comment]
Just because you can do it.
The graphql reference implementation doesn't throw an error, you can define
a nested object with mutation.
I don't know on spec side but maybe graphQL spec missed to say this?

**Comment by gre** [comment]
Basically it is a spec ambiguity. No examples show nesting but also graphQL
don't disallow (AFAIK)
Le 6 nov. 2015 19:09, "Gaëtan Renaudeau" <renaudeau.gaetan@gmail.com> a
écrit :

> Just because you can do it.
> The graphql reference implementation doesn't throw an error, you can
> define a nested object with mutation.
> I don't know on spec side but maybe graphQL spec missed to say this?

**Comment by josephsavona** [comment]
@gre can you paste the part of your schema where you're defining this mutation? (or send a link to a Relay playground?)

**Comment by josephsavona** [comment]
I'm curious how you're defining it so that we can adjust `graphql-js` - but as stated previously, mutations are top-level fields and sub-items are fields in the response.

**Comment by gre** [comment]
I don't have a ready to use relay playground but basically:

```scala
type MutationUser {
  bar(input: BarInput!): BarPayload
}

type MutationsTopLevel {
  me: MutationUser
  foo(input: FooInput!): FooPayload
}
```

and a query:

```
mutation {
  me {
    bar(input: ...) { ... }
  }
}
```

We are using sangria scala implementation for the GraphQL server.

**Comment by josephsavona** [comment]
@gre Yup, in that case `me` is the mutation and `bar` is a field in the response payload. We'll update the documentation if this continues to be a source of confusion - thanks for opening this issue!

**Comment by BossGrand** [comment]
Why does it have to be? It seems to me this would be a good way to do authentication if you can say all these mutations can only be performed by X user

**Comment by gre** [comment]
actually I think it's better design to have auth outside of your GraphQL, changing the auth of a user is likely to completely change the graph and you likely will want a total cache refresh anyway, so there is no real benefit of staying in auth.
This is the biggest mistake we've taken at my company (to do it inside graphql) and we have lost so much time because of this. so if you have opportunity to, consider doing auth the more "classic way" (cookie, etc.).

**Comment by BossGrand** [comment]
Thank you, that makes a lot of sense!

On Mar 2, 2017 10:54 PM, "Gaëtan Renaudeau" <notifications@github.com>
wrote:

actually I think it's better design to have auth outside of your GraphQL,
changing the auth of a user is likely to completely change the graph and
you likely will want a total cache refresh anyway, so there is no real
benefit of staying in auth.
This is the biggest mistake we've taken at my company (to do it inside
graphql) and we have lost so much time because of this. so if you have
opportunity to, consider doing auth the more "classic way" (cookie, etc.).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/relay/issues/551#issuecomment-283880578>, or mute
the thread
