### ISSUE TITLE
Two fields with same Enum args fatals

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#553]
Not 100% sure, but seems like Relay bug.

Using such query:
```
fragment on Viewer {
    images (first:1) {
        edges{
            node {
                id
                relatedBySeries: relatedImages(relationType: SERIES) {
                    id
                },
                relatedBySeries2: relatedImages(relationType: SERIES) {
                    id
                }
            }
        }
    }
}
```

I end up with error from server:
```
{"errors":[{"message":"Fields \"_relatedImagescfvst1\" conflict because they have differing arguments."}]}
```

Request looks like
```
query: Admin($relationType_0:relationType,$relationType_1:relationType)
{viewer{id,...__RelayQueryFragment49zqipr}} fragment __RelayQueryFragment5qkxt80 on 
Viewer{_imagesxkcj5l:images(first:1){edges{node{id,
_relatedImagescfvst1:relatedImages(relationType:$relationType_0){id},
_relatedImagescfvst1:relatedImages(relationType:$relationType_1){id}
},cursor},pageInfo{hasNextPage,hasPreviousPage}},id} fragment __RelayQueryFragment49zqipr on Viewer{id,...__RelayQueryFragment5qkxt80}

variables:{"relationType_0":"SERIES","relationType_1":"SERIES"}}

```

And I know querying same thing from the one component does not make sense - but I got same error when I was using same field with same argument in child component, so it was included via fragment. 

Hope that description is clear. If not let me know.. I will spend more time to extract some basic example with request and response.

**Comment by jardakotesovec** [comment]
Did more testing. And noticed that relay use same generated names for fields that have same arguments, which is redundant but works ok as it gets merged on graphql server. 

Issue is if argument is ENUM, than I end up with this error, so it looks like `graphql-js` bug.

Closing for now. Sorry for noise.

**Comment by kassens** [comment]
I'll reopen this to find the cause of this error. Here's a somewhat simplified [test case](http://facebook.github.io/relay/prototyping/playground.html#source=class%20StoriesApp%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20%7BnameRed%2C%20nameBlue%7D%20%3D%20this.props.viewer%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3Cpre%3E%0A%20%20%20%20%20%20%20%20%20%20%7BJSON.stringify(%7BnameRed%2C%20nameBlue%7D%2C%20null%2C%20'%20%20')%7D%0A%20%20%20%20%20%20%20%20%3C%2Fpre%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A%0AStoriesApp%20%3D%20Relay.createContainer(StoriesApp%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20numStoriesToLoad%3A%203%2C%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20viewer%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Viewer%20%7B%0A%20%20%20%20%20%20%20%20nameRed%3A%20name(color%3A%20RED)%0A%20%20%20%20%20%20%20%20nameBlue%3A%20name(color%3A%20RED)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0Aclass%20StoriesRoute%20extends%20Relay.Route%20%7B%0A%20%20static%20params%20%3D%20%7B%7D%3B%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20viewer%3A%20(Component)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20ViewerQuery%20%7B%0A%20%20%20%20%20%20%20%20viewer%20%7B%0A%20%20%20%20%20%20%20%20%20%20%24%7BComponent.getFragment('viewer')%7D%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%20%20static%20routeName%20%3D%20'Stories'%3B%0A%7D%0A%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BStoriesApp%7D%0A%20%20%20%20route%3D%7Bnew%20StoriesRoute()%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B&schema=import%20%7B%0A%20%20GraphQLBoolean%2C%0A%20%20GraphQLEnumType%2C%0A%20%20GraphQLFloat%2C%0A%20%20GraphQLID%2C%0A%20%20GraphQLInputObjectType%2C%0A%20%20GraphQLInt%2C%0A%20%20GraphQLInterfaceType%2C%0A%20%20GraphQLList%2C%0A%20%20GraphQLNonNull%2C%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%20%20GraphQLUnionType%2C%0A%7D%20from%20'graphql'%3B%0Aimport%20%7B%0A%20%20connectionArgs%2C%0A%20%20connectionDefinitions%2C%0A%20%20connectionFromArray%2C%0A%20%20cursorForObjectInConnection%2C%0A%20%20fromGlobalId%2C%0A%20%20globalIdField%2C%0A%20%20mutationWithClientMutationId%2C%0A%20%20nodeDefinitions%2C%0A%20%20toGlobalId%2C%0A%7D%20from%20'graphql-relay'%3B%0A%0Aclass%20Viewer%20%7B%0A%20%20constructor(data)%20%7B%0A%20%20%20%20this.avatar%20%3D%20data.avatar%3B%0A%20%20%20%20this.id%20%3D%20data.id%3B%0A%20%20%20%20this.name%20%3D%20data.name%3B%0A%20%20%7D%0A%7D%0A%0Avar%20RGBType%20%3D%20new%20GraphQLEnumType(%7B%0A%20%20name%3A%20'RGB'%2C%0A%20%20values%3A%20%7B%0A%20%20%20%20RED%3A%20%7B%20value%3A%200%20%7D%2C%0A%20%20%20%20GREEN%3A%20%7B%20value%3A%201%20%7D%2C%0A%20%20%20%20BLUE%3A%20%7B%20value%3A%202%20%7D%0A%20%20%7D%0A%7D)%3B%0A%0Avar%20VIEWER%20%3D%20new%20Viewer(%7B%0A%20%20name%3A%20'Test'%0A%7D)%3B%0A%0A%2F**%0A%20*%20Let%20Relay%20map%20between%3A%0A%20*%20-%20global%20IDs%20and%20the%20object%20they%20represent%0A%20*%20-%20objects%20and%20the%20GraphQL%20type%20associated%20with%20them%0A%20*%2F%0Avar%20%7BnodeInterface%2C%20nodeField%7D%20%3D%20nodeDefinitions(%0A%20%20(globalId)%20%3D%3E%20%7B%0A%20%20%20%20var%20%7Btype%2C%20id%7D%20%3D%20fromGlobalId(globalId)%3B%0A%20%20%20%20if%20(type%20%3D%3D%3D%20'Comment')%20%7B%0A%20%20%20%20%20%20return%20COMMENTS.find(obj%20%3D%3E%20obj.id%20%3D%3D%3D%20id)%3B%0A%20%20%20%20%7D%20else%20if%20(type%20%3D%3D%3D%20'Person')%20%7B%0A%20%20%20%20%20%20return%20PEOPLE.find(obj%20%3D%3E%20obj.id%20%3D%3D%3D%20id)%3B%0A%20%20%20%20%7D%20else%20if%20(type%20%3D%3D%3D%20'Story')%20%7B%0A%20%20%20%20%20%20return%20STORIES.find(obj%20%3D%3E%20obj.id%20%3D%3D%3D%20id)%3B%0A%20%20%20%20%7D%20else%20if%20(type%20%3D%3D%3D%20'Viewer')%20%7B%0A%20%20%20%20%20%20return%20VIEWER%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20null%3B%0A%20%20%7D%2C%0A%20%20(obj)%20%3D%3E%20%7B%0A%20%20%20%20if%20(obj%20instanceof%20Comment)%20%7B%0A%20%20%20%20%20%20return%20CommentType%3B%0A%20%20%20%20%7D%20else%20if%20(obj%20instanceof%20Person)%20%7B%0A%20%20%20%20%20%20return%20PersonType%3B%0A%20%20%20%20%7D%20else%20if%20(obj%20instanceof%20Story)%20%7B%0A%20%20%20%20%20%20return%20StoryType%3B%0A%20%20%20%20%7D%20else%20if%20(obj%20instanceof%20Viewer)%20%7B%0A%20%20%20%20%20%20return%20ViewerType%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20null%3B%0A%20%20%7D%0A)%3B%0A%0Avar%20ViewerType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Viewer'%2C%0A%20%20description%3A%20'The%20acting%20person%20(eg.%20the%20logged%20in%20visitor)'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20globalIdField('Viewer')%2C%0A%20%20%20%20name%3A%20%7B%0A%20%20%20%20%20%20type%3A%20GraphQLString%2C%0A%20%20%20%20%20%20args%3A%20%7Bcolor%3A%20%7Btype%3A%20RGBType%7D%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%20%20interfaces%3A%20%5BnodeInterface%5D%2C%0A%7D)%3B%0A%0A%2F**%0A%20*%20Finally%2C%20configure%20the%20root%20Query%20and%20Mutation%20type%0A%20*%2F%0Avar%20QueryType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Query'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20node%3A%20nodeField%2C%0A%20%20%20%20viewer%3A%20%7B%0A%20%20%20%20%20%20type%3A%20ViewerType%2C%0A%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20VIEWER%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20QueryType%2C%0A%7D)%3B).

**Comment by josephsavona** [comment]
We should probably use the field alias as the basis for the serialization key, not the schema name.

**Comment by kassens** [comment]
fragment on Viewer {
      nameRed: name(color: RED)
      nameBlue: name(color: BLUE)
      nameRed2: name(color: RED)
    }

We print a fragment like:

    fragment __RelayQueryFragment63irdxi on Viewer{
      _namevidys9:name(color:$color_0),
      _namekv43m2:name(color:$color_1),
      _namevidys9:name(color:$color_2),
      id
    }

Causing a collision of the field names.

**Comment by jardakotesovec** [comment]
@kassens Thanks. I will just mention some observations. You said that fields with the same name should merge, which I agree with.   But thats not happening for any fields right now (including simple ones not having any argument) as far as I can see. 

So for something like this
```
        fragment on Viewer {
            someField
            someField
        }
```

Relay sends
```
fragment __RelayQueryFragment0kr90qm on Viewer{someField,someField,id}
```

If its fragment
```
        fragment on Viewer {
            someField
            ${SubComponent.getFragment('viewer')}
        }

SubComponent:
        fragment on Viewer {
            someField
        }
```

Relay sends
```
fragment __RelayQueryFragment1iwtsmn on Viewer{
  someField,
  id
} 

fragment __RelayQueryFragment0kr90qm on Viewer{
  someField,
  id,
  ...__RelayQueryFragment1iwtsmn}
```

I don't see any merging going on. My understanding is that it somehow got merged on the server...

And that merging goes wrong on server for fields with enum argument. Thats reason why I blamed graph-ql for it.

In your example it makes sense to me that nameRed and nameRed2 resulted in the same name fields (_namevidys9) - because they will get same value..  and should be merged, no need to hash them differently in my opinion.

**Comment by josephsavona** [comment]
Relay sends queries to the server as-is, without flattening or merging fields. This is primarily for efficiency - flattening a query requires in the worst case two full tree traversals (first to flatten, then to re-expand fragments by type) - but has the side benefit of making the printed output more debuggable. This is why you're seeing queries such as 

```
fragment A on Type {
  field
}
fragment B on Type {
  field
  ...A
}
```

The current "serialization key" - the dynamically generated field alias in the printed output - is based on the assumption that queries are flattened before being printed. Changing this to use the application defined alias instead of the schema name should fix this. Instead of `_relatedImagescfvst1`, we should send something like `relatedBySeries_cfvst1`

**Comment by jardakotesovec** [comment]
I suspect that If you use application alias for generated field alias it still would not solve situation, because you end up with collision when alias is not used:
```
fragment on Viewer {
   someField(something:ENUM1)
   ${SubComponent.getFragment('viewer')}
}

SubComponent:
fragment on Viewer {
    someField(something:ENUM1)
}
```

And still not sure if I understand why you want to avoid that name field conflict - since these fields are identical (has same arguments) it make sense to resolve them just once and consider them as same thing.  Which is what server currently does with all fields with exception of ones with ENUM arguments (and maybe input objects would go wrong, have not tried).

**Comment by luisobo** [comment]
I think I have the same problem. Here is my case:

I have an interface Customization and several object types implementing this interface, three of the subtypes have a field called `iconUrl` but they mean different things depending on the concrete type in which they are. They just happen to be called the same. These fields have no arguments, but we may add them in the future.

```
interface Customization {
  customizableId: String!
}

type ShowIconInTitle: Customization {
  iconUrl: Url
  ...
}

type ShowSomethingElseSomewhereElse: Customization {
  iconUrl: Url
  ...
}

type SomeOtherWithoutIcon: Customization {
  ...
  // no iconUrl here
}
```

when querying for all the Customizations of a given customizable, the query looks like this:

```
fragment on Customizable {
        id,
        ${AddShowIconInTitleCustomizationToNodeMutation.getFragment('customizable')},
        ${AddShowSomethingElseSomewhereElseCustomizationToNodeMutation.getFragment('customizable')},
        ${AddSomeOtherWithoutIconCustomizationToNodeMutation.getFragment('customizable')},
        ${RemoveCustomizationFromNodeMutation.getFragment('customizable')},
        customizations {
          customizableId,
          kind,
          ${ShowIconInTitleCell.getFragment('customization')},
          ${ShowSomethingElseSomewhereElseCell.getFragment('customization')},
          ${SomeOtherWithoutIconCell.getFragment('customization')},
        }
      }
```

What happens is that only the iconUrl of the first subtype listed in the query above gets requested to the server during the Add mutation. In this case, if I add  a ShowIconInTitle, the iconUrl gets requested fine as part of the mutation, because it is the first in the list, but if I do add a ShowSomethingElseSomewhereElse, the iconUrl of that subtype *does not* get requested to the server as part of the mutation.

Hope this helps.

**Comment by luisobo** [comment]
Just found my workaround, forceFetch the component after the mutation :confused:

**Comment by josephsavona** [comment]
@luisobo what version are you running?

**Comment by josephsavona** [comment]
@luisobo this looks like a different issue - the OP is posting about ENUM arguments, but you don't seem to be supplying arguments to the `iconUrl` field at issue. Can you file a new issue?

**Comment by luisobo** [comment]
@josephsavona someday I'll take the time to understand what is responsible of what in this list, in the meantime:
```
    "babel-core": "^5.8.25",
    "babel-loader": "^5.3.2",
    "babel-relay-plugin": "^0.4.1",
    "graphql": "^0.4.4",
    "history": "^1.12.6",
    "node-uuid": "^1.4.3",
    "react": "^0.14.0",
    "react-dom": "^0.14.0",
    "react-relay": "^0.5.0",
    "react-router": "^1.0.0-rc3",
    "react-router-relay": "^0.7.0",
    "sync-request": "^2.0.1",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.1"
```

**Comment by luisobo** [comment]
well, that didn't come out right

**Comment by vladar** [comment]
Have problem with conflicting fields too. Error occurs with following type hierarchy with `query` operation:

```
type User: Entity {
  affordances: UserAffordancesEnum
  ...
}

type Topic: Entity {
  affordances: TopicAffordancesEnum
  ...
}

interface Entity {
... no "affordances" field here ...
}
```

And following fragments:
```
entity: () => Relay.QL`
    fragment on Entity {
        ...
       ${User.getFragment('user').if(showingDetails)}
       ${Topic.getFragment('topic').if(showingDetails)}
    }
`
...
topic: () => Relay.QL`
    fragment on Topic {
      topicAffordances: affordances
    }
`
...
user: () => Relay.QL`
    fragment on User {
      userAffordances: affordances
    }
`
```

In my case Relay simply removes aliases, so that final query becomes:
```
query EntityLink {
  node(id: "VG9waWMvbaKbwj-EEeWYRgAMKeXbBA") {
    ...__RelayQueryFragmentbxdbgok
  }
}

fragment __RelayQueryFragmentw5fno5s on User {
  affordances,
  id
}

fragment __RelayQueryFragmentxeocf2w on Topic {
  affordances,
  id
}

fragment __RelayQueryFragmentbxdbgok on Entity {
  __typename,
  ...__RelayQueryFragmentw5fno5s,
  ...__RelayQueryFragmentxeocf2w
}
```

GraphQL server returns error: `Fields "affordances" conflict because they return differing types [UserAffordancesEnum] and [TopicAffordancesEnum]`. 

I manually tested with aliases in place and GraphQL correctly processed the query. 

My deps:
```
        "react": "^0.14.0",
        "react-dom": "^0.14.0",
        "react-relay": "^0.5.0",
        "babel": "5.8.23",
        "babel-runtime": "^5.8.25",
        "babel-loader": "5.3.2",
        "babel-relay-plugin": "^0.4.1",
        "graphql": "^0.4.7",
```

**Comment by josephsavona** [comment]
This is another case where the serialization key should perhaps be based off of the alias, not the canonical schema name.

**Comment by josephsavona** [comment]
@vladar do you still get this error on the latest graphql?

**Comment by vladar** [comment]
@josephsavona Nope, wokrs fine now (on graphql 4.13). Thanks!

**Comment by vladar** [comment]
Yet original issue doesn't seem to be fixed, as I just faced with it on GraphQL 0.4.14

**Comment by josephsavona** [comment]
Closing as a duplicate of #784, for which there is a pending fix #801.
