### ISSUE TITLE
Debouncing mutations

### ISSUE THREAD

**Issue by dminkovsky** [facebook/relay#564]
I've got a controlled React form backed by the Relay store. The UI for this form has no explicit "save" functionality. Changes should be persisted as the user updates the form. I was investigating how I might debounce this interaction because the user can trigger many mutations per second by interacting with this form. 

First I tried `_.debounce` on the the handler that triggers `Relay.Store.update(mutation)`. But that prevented optimistic updates from occurring which was a non-starter with the controlled from components. 

The optimistic update, however, happens very soon after the call to `Relay.Store.update()`, inside the `RelayMutationTransaction` constructor. Inside that constructor you also find the mutation transactions getting queued up. This seems like a pretty good place to do debouncing: if debouncing is enabled, the transaction is queued up but the subsequent call to `.commit()` is ignored and the transaction is eventually dequeued and the transaction is de-queued unless no new mutations of this same type come in after the debounce wait time.

Something similar could work for throttling.

I am guessing this will not be popular because debouncing and throttling, I've gathered, are not popular. But I don't want to change my form's UI to require the user to explicitly trigger the mutation. Also, I looked at solving this issue by implementing a custom network layer, but that seems to be at odds with the whole transaction mechanism. Wouldn't it be weird to have my custom network layer just ignore some transactions?

**Comment by josephsavona** [comment]
@dminkovsky This is a great idea. We'd like to support the option to skip pending mutations with the same collision key instead of enqueueing them. There's an open issue at #550 discussing this, let's continue discussion there.

**Comment by dminkovsky** [comment]
Thank you @josephsavona. Sorry I didn't find that issue.
