### ISSUE TITLE
props.relay.variables are the un-prepared variables

### ISSUE THREAD

**Issue by taion** [facebook/relay#578]
Currently, `prepareVariables` is only called when creating the fragments: https://github.com/facebook/relay/blob/v0.4.0/src/container/RelayContainer.js#L836-L838

Specifically, the variables injected into the component on `props.relay.variables` never include the effects of `prepareVariables`: https://github.com/facebook/relay/blob/v0.4.0/src/container/RelayContainer.js#L470-L471, https://github.com/facebook/relay/blob/v0.4.0/src/container/RelayContainer.js#L488-L492.

Is this intentional?

**Comment by yuzhi** [comment]
@yungsters  @josephsavona thoughts?

**Comment by shaimo** [comment]
Anything on this?

**Comment by mailaneel** [comment]
I have faced same issue on my side.I think we should have preparedVariables in ```this.props.relay.variables``` unless there is a good reason for not to do so.

**Comment by josephsavona** [comment]
Having `props.variables` be the prepared values seems reasonable. We'd be open to accepting pull-requests to change this.

**Comment by taion** [comment]
Yay
