### ISSUE TITLE
[docs] Relay{Query,Mutation}Request missing inherited methods

### ISSUE THREAD

**Issue by yungsters** [facebook/relay#581]
One of the most important aspects of `RelayQueryRequest` and `RelayMutationRequest` are that they extend `Deferred` which gives them the `resolve` and `reject` methods (among others). Documentation is missing this important detail.

Example: https://facebook.github.io/relay/docs/interfaces-relay-query-request.html

**Comment by wincent** [comment]
I'm going to fold this into a checklist in #538, which is about overhauling the mutations API. (It will be easier to manage with the various interrelated mutations issues in a single place.)
