### ISSUE TITLE
Uploading array of files

### ISSUE THREAD

**Issue by oguzbilgic** [facebook/relay#586]
Is there a way to upload array of files?

```js
getFiles(): ?FileMap

// Type of the FileMap object
type FileMap = {[key: string]: File};
```

Would it make sense to improve FileMap type to something like this: 

```js
type FileMap = {[key: string]: File | [File]};
```

**Comment by devknoll** [comment]
@oguzbilgic Neat idea. Would you mind opening a PR?

You could work around this today by passing in an array to your mutations constructor and mapping each file to a unique key in `getFiles`, but it seems useful to be able to take advantage of the built-in support for arrays in the browser and web servers.

**Comment by wincent** [comment]
Thanks for filing this issue @oguzbilgic!

This is important, so I'm going to fold it into #538, which is about overhauling the mutations API. (It will be easier to manage with the various interrelated mutations issues in a single place.)

**Comment by eugenehp** [comment]
@oguzbilgic were you able to find a solution for this?

**Comment by chrise86** [comment]
@oguzbilgic also interested to hear if you found a solution 👍

**Comment by sibelius** [comment]
I think a file map makes more sense, should use the filename in the key and disregard it on server
