### ISSUE TITLE
[Question/Example] How to search within connections

### ISSUE THREAD

**Issue by danielgriese** [facebook/relay#59]
First off, thank you for your wonderful work. Been looking forward to this day for months :)

I've been tangling around with the examples and starter-kit. Besides encountering issues upon paging (tickets already open), I stumbled upon a feature I wanted to test, but honestly have no idea how to approach best.

Let's take the starter-kit example. I want to introduce a search field to get widgets (of my user) by name. Let's say I want to get all widgets starting with "A", either paginated or not.

How would I need to extend the example to make this happen. I would assume that I need to pass some kind of additional "search" or "find" argument to the widgets sub-query, so I could pass it into the resolve function before returning the arrayed connections.
But currently I do not see how I could add an additional argument to the connection type, to let it go through.

Or would that even be the wrong way to do it and I should make a separate (root) query for this kind of behavior?

An extended example on how to solve this would be great.
Thanks in advance and kind regards,
Daniel

**Comment by fson** [comment]
The widget field definition in the schema looks like this:
```js
    widgets: {
      type: widgetConnection,
      description: 'A person\'s collection of widgets',
      args: connectionArgs,
      resolve: (_, args) => connectionFromArray(getWidgets(), args),
    },
```
The `args` definition uses the default connection args from `graphql-relay`, but it's just a plain object that you can extend to add more args. By default it looks like this:
```js
var connectionArgs = {
  before: {
    type: GraphQLString
  },
  after: {
    type: GraphQLString
  },
  first: {
    type: GraphQLInt
  },
  last: {
    type: GraphQLInt
  },
};
```
You can add your own arguments to the field. E.g.
```
  widgetName: {
    type: GraphQLString
  }
```

By extending the connectionArgs using the object spread operator we won't have to copy-paste those default args to our definition, so we can write:
```js
var userType = new GraphQLObjectType({
  name: 'User',
  description: 'A person who uses our app',
  fields: () => ({
    id: globalIdField('User'),
    widgets: {
      type: widgetConnection,
      description: 'A person\'s collection of widgets',
      args: {
        ...connectionArgs,
        widgetName: {
          type: GraphQLString,
        }
      },
      resolve: (_, args) =>
        connectionFromArray(getWidgets(args.widgetName), args),
    },
  }),
  interfaces: [nodeInterface],
});
```
Note that all the argument values are passed to the resolve function, so now you just need to modify your database function `getWidgets` to filter the widgets using the name passed to it and finally change the fragment in your React component to use the new argument.

Hope this helps!

**Comment by josephsavona** [comment]
good question, @danielgriese, and great answer @fson!

I'm closing this out because the answer is quite thorough, but I've added a link to it here: https://github.com/facebook/relay/wiki/Frequently-Asked-Questions

Feel free to reopen if you have follow-up questions.

**Comment by danielgriese** [comment]
Thanks for your reply @fson!
We should note that the babel-node call in the updateSchema script needs to be extended to allow for spread operators. Took me a while to get it to run, I'm just using "--stage 1" now.

The proposed solution works fine, if I set the widgetName with a value in the initialVariables of my Container. 
But when I hook it up to an input field, dynamically setting the variable value via this.props.relay.setVariables I get 400 - Bad Request errors from the server.

Query being sent by Relay:
```
"query App{node(id:"VXNlcjox"){_widgetsbe729b64:widgets(first:10,widgetName:"ail"){edges{node{id,name},cursor},pageInfo{hasNextPage,endCursor,hasPreviousPage}},id}}"
```

Return the following error:
"Cannot query field "widgets" on "Node"."

I guess the problem lies in the details of the starter-kit-example. Probably it is resolving the ID to a Node instead to a User. I'll try to investigate it a bit further.

Thanks and kind regards,
Daniel

**Comment by VictorienTardif** [comment]
Hello, Thanks @fson, 

I had the same problem as @danielgriese so I tried to extend connectionArgs exactly as you did, but I now encounter a new incomprehension:

Wether or not I use the argument to filter the list on the `getWidgets` function, the query will still contain the argument and, in any case, the data returned does not contain any widget, I just have an object like that: `Object {__dataID__: "VXNlcjo="}`

Here is what my container looks like:
```
export default Relay.createContainer(WidgetList, {

  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
         widgets(first: 10, name:"name") { 
          edges { 
            node { 
              id, 
              name
            } 
          } 
        } 
      }
    `,
  },
})
```
What could I be missing?
Thank you!

**Comment by icylabsDev** [comment]
Just a follow up on this question. Let's say we have different widgets belonging to different users. My immediate idea would be to do something like `{user(id:1){widgets(userId:1){widgetName}}}` But that seems bad to put the userId twice. Is there a better practice?
