### ISSUE TITLE
Mutation Error: Expected prop supplied to mutation to be fetched by Relay

### ISSUE THREAD

**Issue by chrissm79** [facebook/relay#592]
I'm am getting an error whenever I attempt to submit a mutation: ```Relay: Warning: RelayMutation: Expected prop `customer` supplied to `UpdateCustomerEmailMutation` to be data fetched by Relay. This is likely an error unless you are purposely passing in mock data that conforms to the shape of this mutation's fragment.warning```

Additionally, if I attempt to submit the mutation through GraphiQL it works as intended. However, the response I get back from the server when submitting the mutation through relay is different (it doesn't contain the email of the customer in this example). 

Is there something missing in my relay mutation?

```js
import Relay from 'react-relay';

export default class UpdateCustomerEmailMutation extends Relay.Mutation {
    static fragments = {
        customer: () => Relay.QL`
            fragment on Customer {
                entity_id,
            }
        `
    }

    getMutation() {
        return Relay.QL`mutation{updateCustomerEmail}`;
    }

    getFatQuery() {
        return Relay.QL`
            fragment on updateCustomerEmailPayload {
                customer {
                    email
                }
            }
        `;
    }

    getConfigs() {
        return [{
            type: 'FIELDS_CHANGE',
            fieldIDs: {
                customer: this.props.customer.entity_id,
            }
        }]
    }

    getVariables() {
        return {
            entity_id: this.props.customer.entity_id,
            email: this.props.email
        }
    }

    getOptimisticResponse() {
        return {
            customer: {
                entity_id: this.props.customer.entity_id,
                email: this.props.email
            }
        }
    }
}
```

Component:
```js
import React, {Component} from 'react';
import Relay from 'react-relay';
import UpdateCustomerEmailMutation from '../mutations/UpdateCustomerEmailMutation';

class Customer extends Component {
    render() {
        const customer = this.props.customer;
        return (
            <div>
                <h2>Customer: {customer.email}</h2>
                <hr />
                <button onClick={this._handleUpdateEmail}>Update Email</button>
                <ul>
                
                </ul>
            </div>
        )
    }

    _handleUpdateEmail = () => {
        console.log('Updating Customer', this.props.customer);
        Relay.Store.update(
            new UpdateCustomerEmailMutation({customer: this.props.customer, email: 'john.doe@example.com'})
        );
    }
}

export default Relay.createContainer(Customer, {
    fragments: {
        customer: () => Relay.QL`
            fragment on Customer {
                entity_id,
                email
            }
        `,
    }
});
```

My [schema.json] (https://gist.github.com/chrissm79/28b95536d26396252e63)

<img width="1512" alt="screen shot 2015-11-12 at 12 32 17 pm" src="https://cloud.githubusercontent.com/assets/1976169/11128951/21458d02-893a-11e5-97db-874d65603766.png">

<img width="1589" alt="screen shot 2015-11-12 at 12 33 20 pm" src="https://cloud.githubusercontent.com/assets/1976169/11128952/214836f6-893a-11e5-88c9-8f7d6be148f9.png">

**Comment by kassens** [comment]
As the error message says, you're currently not fetching the data for the mutation anywhere. This error should go away when you include the customer fragment of the mutation in your Relay container like this:

```javascript
export default Relay.createContainer(Customer, {
    fragments: {
        customer: () => Relay.QL`
            fragment on Customer {
                ${UpdateCustomerEmailMutation.getFragment('customer`)},
                entity_id,
                email
            }
        `,
    }
});
```

Please prefer other channels for questions or problems so we keep the github issues for likely bugs or enhancements (for options see http://facebook.github.io/relay/support.html )
