### ISSUE TITLE
Q: RelayQueryFragment instead of data

### ISSUE THREAD

**Issue by mikhail-riabokon** [facebook/relay#593]
I have a question about RelayContainer usage.
For example I have a Parent Relay Container, where I fetch data for Child elements.
```javascript
class Parent extends Component {
  render() {
    return (
      <div className="children">
        {this.props.viewer.children.map((child) => {
          return <Child {...child}/>
        })}
      </div>
    );
  }
}

export default Relay.createContainer(Parent, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        children {
          id, 
          name
        }
      }
    `
  }
});
```
And in this case each child will have name from received data.

If I changed Parent Relay Container to next variant
```javascript
 class Parent extends Component {
  render() {
    return (
      <div className="children">
        {this.props.viewer.children.map((child) => {
          return <Child {...child}/>
        })}
      </div>
    );
  }
}

export default Relay.createContainer(Parent, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        children {
          ${Child.getFragment('child')}
        }
      }
    `
  }
});
```
And my Child file looks like this

```javascript
class Child extends Component {
  render() {
    return (
      <div className="child">
        {this.props.name}
      </div>
    );
  }
}

export default Relay.createContainer(Child, {
  fragments: {
    child: () => Relay.QL`
      fragment on Child {
        id,
        name
      }
    `
  }
});
```

Instead of data, I will receive the array of next object 
```javascript
[
  {
    __dataID__: String,
    RelayQueryFragment: RelayFragment
  }
]
```

In first case data looks like
```javascript
[
  {
    id: '1',
    name: 'Some name'
  }
]
```

Why is it happened, and how to receive data in second variant of Parent. Thank you.

note: edited code formatting for readability

**Comment by josephsavona** [comment]
This is covered in the docs on [Data Masking](http://facebook.github.io/relay/docs/thinking-in-relay.html#data-masking).

In summary, components can only access fields they request. In the second example, the parent cannot access the `name` property because that field is only requested by the child. If the parent needs the name, just add it in the parent as follows:

```javascript
export default Relay.createContainer(Parent, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        children {
          name # not accessible unless requested
          ${Child.getFragment('child')}
        }
      }
    `
  }
});
```

**Comment by plievone** [comment]
@josephsavona Something else is amiss here, as the parent does not use the `name` property and should not need to know about it?

Does it need `@relay(plural:true)` on the parent? Or perhaps the `{...child}` spread  in `children.map( )` acts funnily? 

Also speaking about data masking, todo example manages to depend on [`viewer.todos`](https://github.com/facebook/relay/blob/7e96455/examples/todo/js/components/TodoApp.js#L47)  in quite an implicit way without declaring it?

**Comment by josephsavona** [comment]
@plievone Can you clarify what is different than you expected? It would be helpful to see:
- the component definition with fragments, for the component that is receiving unexpected data
- the actual data received by that component
- the expected data that you thought it would receive

Note that in the above example, the actual data received by the `Parent` component seems to be:

```javascript
[
  {
    __dataID__: String,
    RelayQueryFragment: RelayFragment
  }
]
```

Which is correct per `Parent`'s fragment definition and Relay's data-masking.

**Comment by mikhail-riabokon** [comment]
@josephsavona Can I declare in Parent component what should be fetched for Child via ```Child.getFragment('child')```?

I have a Parent, where I described what should to be fetched by ```viewer``` query. But in this case I would not receive data from ```Child.getFragment('child')```.
```javascript
class Parent extends Component {
  render() {
    return (
     // this.props.viewer.children = [{__dataID__: String, RelayQueryFragment: RelayQueryFragment}]

      <div className="children">
        {this.props.viewer.children.map((child) => {
          return <Child {...child}/>
        })}
      </div>
    );
  }
}

export default Relay.createContainer(Parent, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        children {
          ${Child.getFragment('child')}
        }
      }
    `
  }
});
```

But as you mentioned, I can receive exactly what I want if I would not use ```Child.getFragment('child')```. 
```javascript
class Parent extends Component {
  render() {
    return (
     // this.props.viewer.children = [{name: String, id: String}]

      <div className="children">
        {this.props.viewer.children.map((child) => {
          return <Child {...child}/>
        })}
      </div>
    );
  }
}

export default Relay.createContainer(Parent, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        children {
          name,
          id
        }
      }
    `
  }
});
```

So, when should I use it ```Child.getFragment('child')```? How to compose relay containers? Thank you.

**Comment by josephsavona** [comment]
Your code is correct - that is how to compose Relay containers. I'll repeat my question: **what component is receiving data that is different than you expected, and what is the actual/expected data?**

**Comment by mikhail-riabokon** [comment]
I expected receive data which declare in ```Child.getFragment('child')```.

Actual
```
[
  {
    __dataID: String,
    RelayQueryFragment: RelayQFragment
  }
]
```

Expected
```
[
  {
    id: String,
    name: String
  }
]
```

I thought that   ```Child.getFragment('child')```  equal 
``` 
fragment on Viewer {
 children {
   name,
   id
 }
}
```

**Comment by josephsavona** [comment]
**Please read the docs** - this is covered in [Data Masking](http://facebook.github.io/relay/docs/thinking-in-relay.html#data-masking). If you want to access `id` and `name` in the `Parent` component, *just request them*:

```javascript
export default Relay.createContainer(Parent, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        children {
          id         # <-- if you don't request a field, it's results won't be available
          name   # <-- if you don't request a field, it's results won't be available
          ${Child.getFragment('child')}
        }
      }
    `
  }
});
```

**Comment by plievone** [comment]
But `Child` component definition and its fragments are in issue description (search for "class Child extends Component") and it looks reasonable to me? Parent just gives the child its props, without knowing what they are, using getFragment. I am just an onlooker to this issue, but also curious to hear the solution for this kind of simple array fetching, haven't used relay yet.

**Comment by mikhail-riabokon** [comment]
@josephsavona Thank you for the article. I already read it. But I still have problems. If I changed ```Parent``` render method and will render  ```Child``` Relay Container instead of ```Child.jsx``` I got an warning
```
Warning: RelayContainer: Expected query `child` to be supplied to `Child` as a prop from the parent. Pass an explicit `null` if this is intentional.
```

So If I want to fetch data for children, and did not declare that children should have in ```Parent``` relay container, I should pass ```Child``` in ```RootContainer``` and render that in ```Parent```?

Could you share an example of Relay and GraphQL, without ``graphql-relay```  usage? Thank you in advanced.

**Comment by josephsavona** [comment]
Ohhhh, that error makes the problem clear. `Parent` is not passing data to `Child` with the correct prop.

Incorrect:
```javascript
<div className="children">
        {this.props.viewer.children.map((child) => {
          return <Child {...child}/>
        })}
      </div>
```

Correct:
```javascript
<div className="children">
        {this.props.viewer.children.map((child) => {
          return <Child child={child} />      // you have to pass a `child` prop to match the `child` fragment
        })}
      </div>
```

**Comment by plievone** [comment]
Thanks, now I see it! So the spread was the culprit, and in the `Child` one should use `this.props.child.name` instead of `this.props.name`, didn't see that. Hopefully this clears the issue. :)

**Comment by mikhail-riabokon** [comment]
@josephsavona Thank you a lot.
