### ISSUE TITLE
Documentation: usage of the term "call" in explanation of RANGE_ADD `rangeBehaviors` configuration

### ISSUE THREAD

**Issue by dminkovsky** [facebook/relay#601]
Hey, I was pretty confused about about the usage of the term "GraphQL call" on the documentation for RANGE_ADD. Fortunately @taion [clarified this for me on SO](http://stackoverflow.com/questions/33631322/what-are-the-graphql-calls-in-the-rangebehaviors-attribute-of-the-range-add). Is it worth updating the docs? Thanks.

**Comment by taion** [comment]
I think this just falls under https://github.com/facebook/relay/issues/538.

**Comment by josephsavona** [comment]
@dminkovsky We previously referred to field arguments as calls and it looks like we slipped up and used the old terminology in places. We'll fix it as time permits, but we're always happy to receive PRs to make the documentation more clear.

**Comment by dminkovsky** [comment]
Thanks I will submit a PR.
