### ISSUE TITLE
Variable of required type was not provided as argument of enum type

### ISSUE THREAD

**Issue by mikberg** [facebook/relay#605]
Hi!

I have a connection which has a required argument of an enum type:

```js
export const GraphQLPeriodInterval = new GraphQLEnumType({
  name: 'PeriodInterval',
  values: {
    DAY: { value: 0 },
    MONTH: { value: 1 },
    YEAR: { value: 2 }
  }
});
```

```js
orderStats: {
      type: OrderStatsConnection,
      args: {
        interval: {
          type: new GraphQLNonNull(GraphQLPeriodInterval),
          description: 'The interval of the periods',
        },
        ...connectionArgs,
      },
      async resolve(obj, { ...args }, { fieldASTs }) {
        ...
      }
    }
```

Everything works fine when I use Graphiql, but in Relay, I get an error:

```
Server request for query `Routes` failed for the following reasons:

1. Variable "$interval_0" of required type "PeriodInterval!" was not provided.
```

even though it's clearly specified:

```js
export default Relay.createContainer(Trend, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        orderStats(interval:MONTH) {
          edges {
            node {
              id,
              period
            }
          }
        }
      }
    `
  }
});
```

Is there something I don't get about using enums? `PeriodInterval` seems to be correctly defined in `schema.graphql` and its json counterpart. Do they have to be registered or initialized in Relay?

Is this a bug or is it my fault?

**Comment by xuorig** [comment]
Hey @mikberg, weird that it works in graphiql and not in relay, could you post what query relay is actually sending to your server ?

**Comment by mikberg** [comment]
Hi, @xuorig 

Thanks for a bump in the right direction! The error was on my part: The server was only passing on the `query` part of the JSON to `graphql()`, missing the `variables` part. The problem was completely resolved using `express-graphql` instead of "manually" parsing the body and passing it on.

Thank you!
