### ISSUE TITLE
cache problem when fetch same connection

### ISSUE THREAD

**Issue by filod** [facebook/relay#610]
say, i have 3 answers in a question.

step1, visit url `/a`, in this route i will issue a query like (nested in other queries)
```
fragment on Question {
  answers(first: 1) {
    edges {
      node {
        ...
      }
    }
  }
}
```
then jump to `/b`, will issue query like (same Question):
```
fragment on Question {
  answers(first: 100) {
    edges {
      node {
        ...
      }
    }
  }
}
```
actually server return 3 results as expected
![ecdaff65-24da-4ea0-8ef2-a69fa6edcfaa](https://cloud.githubusercontent.com/assets/679897/11232159/c60fbd26-8dea-11e5-9995-2b5ea7f18997.png)

but in container component, i cound get **only one answer**
![e3d125a8-650c-487f-9910-640403c70c2e](https://cloud.githubusercontent.com/assets/679897/11232149/ac5f3550-8dea-11e5-8ae6-302c11f0678d.png)

**Comment by yuzhi** [comment]
This could happen if Relay is having trouble resolving what has been cached with the additional data from the server (ie. if they mismatch). What does the query to the server look like? What are the IDs of the nodes each time you hit a route?

**Comment by filod** [comment]
yep, i am using `react-router-relay`

I am sure the ids were comply `relay graphql spec `,  in the case above, the query didn't issue any `node` query.

**Comment by yuzhi** [comment]
I meant the `node` field inside the connection. Can you include the query that was sent to the server? I am mainly interested to see if a diff query was generated properly after the first page you loaded.

**Comment by filod** [comment]
first query 
```
query Earning{
  viewer{
    id,...__RelayQueryFragment0myqtzl
  }
} 
fragment __RelayQueryFragment1wmpg2h on Question{
  ...
  _answersrbo29x:answers(first:1){
    edges{
      node{id},
      cursor
    },
    pageInfo{hasNextPage,hasPreviousPage}
  },
}
fragment __RelayQueryFragment0myqtzl on User{
  upcomings {
    stock {
      ...
      recentQuestion{id,...__RelayQueryFragment1wmpg2h},
    },
    ...
  },
}
```
second
```

query Question{
  question(id:"UXVlc3Rpb246MjM="){
    id,...__RelayQueryFragment2d1pr7f
  }
} 
fragment __RelayQueryFragment3kha3rh on Answer{
  ...
  question{id},
  content{
    ...__RelayQueryFragment4sk1iyd
  },
  ...
} 

fragment __RelayQueryFragment2d1pr7f on Question{
  ...
  _answers5dklw3:answers(first:100){
    edges{node{id,...__RelayQueryFragment3kha3rh},cursor},
    pageInfo{hasNextPage,hasPreviousPage}
  },
}
```

i ignore some unrelated fields & fragments, if you need the full queries, pls tell me

**Comment by yuzhi** [comment]
Did you see any warnings or errors in the console anywhere. Did the first edge of the first query match with the first edge of the second query? Relay might barf if they don't match because we are not sure if something got added or removed.

**Comment by filod** [comment]
ok, i got the problem, because i generate a wrong cursor of edge in my sever side.
thx your patient !

**Comment by filod** [comment]
@yuzhi  also i have a question is that how should i generate cursor of a connection which could present a dynamic list (like some answers of a question, the list will resort after user like one of them or as time pass by)

**Comment by yuzhi** [comment]
I'm not an expert on that. @dschafer might have suggestion for best practices for cursors.
