### ISSUE TITLE
Intersection between fat query and tracked query not working as expected

### ISSUE THREAD

**Issue by guigrpa** [facebook/relay#611]
In my application, a tabular Relay container uses the following fragment to show information on a number of items:

```
fragment on Viewer {
  pipes(first: 100000) {edges {node {
    id, idx, name ...
  }}}
}
```

When clicking on an item, the application unmounts that container and mounts another one that allows the user to edit and delete an item:

```
fragment on Pipe {
  id, idx, name ...
  ${mutations.DeletePipeMutation.getFragment('pipe')}
  ${mutations.UpdatePipeMutation.getFragment('pipe')}
}
```

When the user deletes the item, the `DeletePipeMutation` is run, which has the following fat query:

```
fragment on DeletePipePayload {
  deletedPipeId
  viewer {pipes}
}
```

However, Relay retrieves only very limited information about the *remaining* items, which may have changed (as is the case):

```
mutation Mutations($input_0: DeletePipeInput!) {
  deletePipe(input: $input_0) {
    clientMutationId, ...__RelayQueryFragment773nd7g, deletedPipeId
  }
}
fragment __RelayQueryFragment773nd7g on DeletePipePayload {
  viewer {
    id
  }
}
```

Note that no field from the items (pipes) is re-fetched. I would have expected the intersection of the fat query above and Relay's internal tracked query to include the cached item fields (`id`, `idx`, `name`...). I can work around this problem by writing a more complete fat query, but this seems not in line with the expected *intersection* behaviour:

```
fragment on DeletePipePayload {
  deletedPipeId
  viewer {pipes(first: 100000) {edges {node {idx}}}}
}
```

Might this be a bug?

**Comment by devknoll** [comment]
The issue is that Relay doesn't know that the `viewer { pipes }` in your fat query corresponds to the same one that your fragment is listening on. You can add a `FIELDS_CHANGE` config for the `viewer` field to get the behavior you're looking for.

**Comment by yuzhi** [comment]
Right. We'll need to know what node `viewer { pipes}` maps to since field in mutation doesn't always match up with root field names. What's in the `getConfig` of your mutation?

**Comment by guigrpa** [comment]
@devknoll With the additional `FIELDS_CHANGE` config, the unexpected behaviour indeed disappears (thanks!). @yuzhi Here is the complete `getConfigs()`:

```js
getConfigs() {
  return [{
    type: 'NODE_DELETE',
    parentName: 'viewer',
    parentID: this.props.viewer.id,
    connectionName: 'pipes',
    deletedIDFieldName: 'deletedPipeId',
  }, {
    type: 'FIELDS_CHANGE',
    fieldIDs: {
      viewer: this.props.viewer.id,
    },
  }];
}
```

However, two things remain unclear to me:

1. Relay *does* already have the information on the `viewer`'s ID (from the `NODE_DELETE` config). It could already use this information to perform a more complete intersection.

2. Why did the workaround work? I mean, this fat query without the additional `FIELDS_CHANGE` config:

```
fragment on DeletePipePayload {
  deletedPipeId
  viewer {
    pipes(first: 100000) {edges {node {
      rank
    }}}
  }
}
```

**Comment by guigrpa** [comment]
I'll try to answer myself: if I only specify a `NODE_DELETE` config and the fat query does not expand the `pipes` field, Relay understands that the possible result of this mutation is limited to the deletion and does not affect other connection edges. This is reasonable since that is the typical case in a deletion mutation and avoids costly refetches. If either the `FIELDS_CHANGE` is specified (related to my first question) *or* the fat query becomes more specific (second question), Relay performs the complete intersection.

Am I too far off?

**Comment by devknoll** [comment]
That sounds plausible, but I'll leave it to someone else to confirm.

Just wanted to add, if you're using `FIELDS_CHANGE` then you should be able to remove `NODE_DELETE`, as it _should_ cause the entire range (minus the deleted edge) to be fetched again.

**Comment by yuzhi** [comment]
You are totally correct! With a `NODE_DELETE` mutation, we simple remove the node from the store and remove it from all connections we know about. We do not refetch anything else. 
Adding a `FIELDS_CHANGE` well let us know other things could have changed and will cause us to do the intersection step and refetch data. 
You probably want to keep the `NODE_DELETE` mutation since that will actually delete the node from the store since we know it no longer exists. With only `FIELDS_CHANGE`, Relay can only figure out that node is no longer in this particular connection but doesn't know that it's actually gone from everywhere else as well.

**Comment by devknoll** [comment]
Awesome, thanks for the clarification @yuzhi :smile:

**Comment by guigrpa** [comment]
@yuzhi: just a final question: if the node is removed "from all known connections", why do you need to specify a particular one in the `NODE_DELETE` config?

**Comment by yuzhi** [comment]
It's mainly for refetching metadata in the connections like `count`. Since we assume only something is deleted, we don't try to refetch the individual items.
