### ISSUE TITLE
Support npm install from master

### ISSUE THREAD

**Issue by Globegitter** [facebook/relay#612]
I want to test some of the last features on the master-branch and be able to install relay e.g. via `npm install 'https://github.com/facebook/relay#090b2b1c1228fb3337d8af68648b34150da682e6'.

This currently leads to an almost empty react-relay folder, which just has as `node_modules` folder as well as `LICENSE`, `PATENTS`, etc.

**Comment by steveluscher** [comment]
In the meantime, can you achieve this if you:

1. `git clone git@github.com:facebook/relay.git`
2. `(cd relay && npm link)`
3. `(cd yourproject && npm install react-relay)`
