### ISSUE TITLE
Licensing for examples is inconsistent with the rest of the project.

### ISSUE THREAD

**Issue by sleepycat** [facebook/relay#613]
Relay is BSD licensed but for some reason all the example files are marked with following:

```
/**
 * This file provided by Facebook is for non-commercial testing and evaluation
 * purposes only.  Facebook reserves all rights not expressly granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * FACEBOOK BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
```

This more restrictive licence seems to clash with the more permissive terms of the BSD and makes it a little weird to use the examples as a base to build on.

Any thoughts on moving these examples to BSD?

**Comment by wincent** [comment]
This is the standard license that we apply to all such sample code across
our projects, as recommended by our legal peeps. I don't have enough legal
knowledge to explain exactly why.

**Comment by sleepycat** [comment]
Example code is obviously still code, and if someone (me for instance) is considering taking one of those examples, and cleaning it up to use as a starting point similar to the relay-starter-kit... well, those restrictions make it seem like people won't be able to use that starting point for commercial projects.

Obviously you all care about making this all accessible, and easy for anyone to work with and build on, hence the development here on Github and the BSD licence. Having the example code held up as somehow different is kinda weird.

If you are able to flag down one of the "legal peeps", I'd love to understand the thinking behind that.

**Comment by steveluscher** [comment]
Interesting discussion, but we're way out of our depth here as mere devs. Before someone says something they'll regret, I'm going to jump at the chance to close this issue!
