### ISSUE TITLE
Cannot read property 'unstable_batchedUpdates' of undefined

### ISSUE THREAD

**Issue by xuorig** [facebook/relay#616]
I get this error since I've updated to 0.5.0. Seems like ReactDOM is undefined but I do have react-dom 0.14.3 installed too... Anybody has had this problem before ?

**Comment by josephsavona** [comment]
@xuorig did you resolve this?

**Comment by xuorig** [comment]
@josephsavona yes I forgot to add a script tag for react-dom :facepalm:

**Comment by josephsavona** [comment]
:+1:
