### ISSUE TITLE
getOptimisticResponse does not seem to populate `__typename`

### ISSUE THREAD

**Issue by Globegitter** [facebook/relay#618]
I have a mutation which returns an optimistic response as follows:

```js
 getOptimisticResponse() {
    const {dateOfBirth, otherField, otherOtherField} = this.props;
    return {
      customer: {
        dateOfBirth,
        otherField,
        otherOtherField
      }
    };
  }
```

Which leads to: `'RelayQueryWriter: Could not find a type name for record `%s`.',` here: 'RelayQueryWriter: Could not find a type name for record `%s`.',

When debugging I can see that the passed-in payload does not have a `__typename`. If I set it manually to `Customer` in the `getOptimisticResponse` the warning disappears.

I am using a version from master with the commit id `090b2b1c1228fb3337d8af68648b34150da682e6`, so from about 2 days ago,

**Comment by josephsavona** [comment]
@Globegitter thanks for filing this, see #621 for a fix

**Comment by josephsavona** [comment]
@Globegitter thanks again for bringing this up!
