### ISSUE TITLE
Can't install any examples, Mac OS 10.11.1 (el capitan)

### ISSUE THREAD

**Issue by jaredonline** [facebook/relay#623]
Hey there!

Been playing around with GraphQL and wanted to try out relay, but can't get any of the examples to install.

Here's a gist containing the error and the output of the build log:

https://gist.github.com/jaredonline/df1f0c022aebe60764b0

**Comment by plievone** [comment]
Try running npm install separately on package root and scripts/babel-relay plugin, then on examples. There are order issues.

**Comment by josephsavona** [comment]
Closing as @pievone's suggestion should solve this.
