### ISSUE TITLE
Requesting ability to flush particular data from the Relay Store

### ISSUE THREAD

**Issue by OverclockedTim** [facebook/relay#629]
In my case, I am attempting to modify an object with a large number of connections. These connections primarily represent different methods for querying on descendant objects. When I move descendant objects around, all of the connections become invalid. These connections are pageable and can be very large if the user has been doing multiple searches and the request size has been continually upped on a number of connections. If I set this up as a FatQuery, Relay will end up requesting an update to every single node of every connection of the ancestor object even though most of the connections won't be needed again.  What I really need to do is to be able to simple reset the store state of those ancestors.  I could accomplish this with a page load of course, but that would be resetting the entire store which contains a lot of information which I would rather not fetch again as well as being ugly.

**Comment by johanobergman** [comment]
So you'd need something like `RANGE_DELETE`, but only for connections with certain arguments?

**Comment by OverclockedTim** [comment]
No, not really.  RANGE_DELETE indicates that the items have been deleted.  I need to specify that I don't really know what has happened on the server.  In some connections, it may be deleted, in some added, and in some the ordering may have changed.  And I may only be interested in say the first:20 for a particular connection (or a connection with certain arguments) because that is all that is currently displaying to the user. 

If that first:20 on ConnectionA lets call it had been the only thing ever requested, then I could do a FIELDS_CHANGE on the parent node and the mutation request would include ConnectionA::first:20.  However, if I'd been mucking around for a while, playing with the data grid sorts and filters and different views, then the Relay store would have a number of different connections (or connections with arguments) and as such would issue and absolutely msasive update request for ConnectionA:first:2000, ConnectionB: first:500, ConnectionC['byTitle']::first:50, etc etc.  even if those components are not currently displayed.  What I need is a way to tell it to just toss all that info.  Or, possibly toss all of the info except what is currently being displayed by a component.

**Comment by josephsavona** [comment]
@OverclockedTim This is definitely something we plan to address, and we're tracking progress at #537.
