### ISSUE TITLE
[babel-relay-plugin] please publish v0.5.0 to NPM

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#636]
Hello

As mentioned [here](https://github.com/facebook/relay/issues/635) by @josephsavona `It's important to upgrade react-relay and babel-relay-plugin together.`

To be able to do that and also to be able to update the [babel-relay-plugin-loader](https://github.com/BerndWessels/babel-relay-plugin-loader) we need the new `0.5.0` version of the `babel-relay-plugin` published to NPM.

Chan you please do that and let me know here? I will update the loader then right away.

Thank you
Bernd

**Comment by josephsavona** [comment]
Please see my comment on the original issue: you're using an out of date version of react-relay.

**Comment by plievone** [comment]
@josephsavona The issue is that `npm view babel-relay-plugin` shows that latest is still `0.4.1`, so the plugin releases haven't been published to npm for a while.

**Comment by josephsavona** [comment]
The OP was using react-relay 0.4.0 (out of date) with the current Babel-relay-plugin 0.4.x.

**Comment by BerndWessels** [comment]
@josephsavona Would be good if with the upcoming `react-relay` `0.6.0` release you could bump the `babel-relay-plugin` version to `0.6.0` too. Especially since they are tightly related anyway. That would stop all the confusion and lots of unnecessary git issues.

**Comment by josephsavona** [comment]
@BerndWessels yup, that's the plan.

**Comment by plievone** [comment]
Ah ok, I thought they were in sync and that plugin version pump to 0.4.2 a couple of weeks ago was not published to npm in error. It is the in progress version then, ok.
