### ISSUE TITLE
Can't add fragments to getFatQuery

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#643]
This caused me trouble just now as I needed to query for some changes to a field a type implementing an interface.

This was an unexpected limitation—any plan to remove it?

Invariant at https://github.com/facebook/relay/blob/4e671a316bbb09dee0fcc14aa414f0d31076948f/src/traversal/intersectRelayQuery.js#L86

`Nodes in `patternNode` must be fields.`

**Comment by josephsavona** [comment]
We enabled fragments in fat queries in ca0afe134d29fc8c2dc046be5f91253aebdf8565 - will go out in 0.6.0 :-)

**Comment by KyleAMathews** [comment]
Haha :-) guess I can wait then. Thanks!

**Comment by josephsavona** [comment]
sure thing!
