### ISSUE TITLE
Make dist/relay[.min].js CommonJS compatible

### ISSUE THREAD

**Issue by mhart** [facebook/relay#65]
Would be great if the Relay dist files could be CommonJS compatible (in the same way the `react[.min].js` files are with the whole `...typeof exports...` surrounding block)

Among other things, this would make it easier to use Relay with browserify.

With `dist/relay[.min].js` built on the latest master I get errors like `Uncaught TypeError: Cannot read property 'MutationObserver' of undefined`

**Comment by steveluscher** [comment]
Good idea. Thanks! If you're still having trouble with that `TypeError` open a separate issue and we'll help you out.
