### ISSUE TITLE
How to use FIELDS_CHANGE without dataID?

### ISSUE THREAD

**Issue by vslinko** [facebook/relay#651]
I want to create a server mutation that updates a currently authorized user without passing userId as an input argument: `mutation { updateUser(input: {name: "John"}) }`.
This approach should highly simplify permission checking.

But I have problem with this on the client side: `FIELDS_CHANGE` requires `dataID` to apply changes to the client store.
Is it possible to remove `id` from the mutations but still have store updates?

**Comment by devknoll** [comment]
@vslinko Do you mean that you don't want to pass the userId as an input argument (in the GraphQL sense) or as an argument to the mutation?

The only requirement is having the ID in the mutation. If you can pass it as a __mutation prop__, you can reference it with e.g. `this.props.user_id` __without__ including it in `getVariables()` and passing it as an input argument.

**Comment by vslinko** [comment]
Hmm. It makes sense. Thank you! :smile:
