### ISSUE TITLE
Relay and GraphQL QueryStreams

### ISSUE THREAD

**Issue by zuhair-naqvi** [facebook/relay#652]
Is there a Relay construct analogous to Mongoose QueryStreams (http://mongoosejs.com/docs/2.7.x/docs/querystream.html) with Relay? i.e. rather than polling the GraphQL endpoint, perhaps subscribe to a QueryStream over web-sockets into the GraphQL server?

1. I think this would fit nicely with GraphQL subscriptions
2. Being able to play / pause / close / open streams for queries would be very useful - i.e. you would get the benefits of observables (ability to cancel a promise / unsubscribe aka close a queryStream) without using RxJS

**Comment by josephsavona** [comment]
Subscriptions are designed as a sort of declarative analogue to imperative stream mechanisms (querying data inside a stream callback could cause the n+1 query problem because the streams aren't statically conposable).

What specific functionality about streams would you want separate from the subscriptions API? (see the issue for this).

**Comment by zuhair-naqvi** [comment]
The usecase is push messaging, if the app is primarily event driven, you don't want to be constantly polling the graphql server for updates. 

I see DiscordApp which apparently is built on Relay uses websockets 
<img width="1436" alt="screen shot 2015-12-06 at 9 37 00 pm" src="https://cloud.githubusercontent.com/assets/262722/11612917/a58caaca-9c61-11e5-8e16-149dcd466144.png">

Any ideas on a canonical way to achieve this?

**Comment by josephsavona** [comment]
Just checking. This is exactly the use-case that GraphQL Subscriptions are meant to address. This is still an active area of exploration, and we're tracking progress at #541.

**Comment by zuhair-naqvi** [comment]
Thanks I'll follow the issue.. PS did some digging found this https://gist.github.com/ngthorg/21a986962228f53a3ec5 .. your thoughts?

**Comment by josephsavona** [comment]
We've documented our thoughts on subscriptions pretty extensively in a [dedicated blog post](http://graphql.org/blog/subscriptions-in-graphql-and-relay/) :-)
