### ISSUE TITLE
Edge returns from mutation without typename

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#653]
Repro:

1. Load the TodoMVC example
2. Create a new todo

```
Warning: RelayQueryWriter: Could not find a type name for record `client:client:17244854812:VG9kbzoxMA==`.
```

Should we add `__typename` as a requisite field everywhere for mutation queries?

**Comment by josephsavona** [comment]
We should be already adding `__typename` wherever there is an abstract type. I can look into this.

**Comment by josephsavona** [comment]
closing as a duplicate of #474.
