### ISSUE TITLE
[react-relay] v4+ Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#656]
Hi
@josephsavona mentioned [here](https://github.com/facebook/relay/issues/635) that this should have been fixed with version 0.6.0 - but unfortunately is seem not to be fixed.

Can you please have a look again. It prevents us from upgrading beyond `0.3.0` at all.

Here are the details again with how to reproduce.

The problem comes when upgrading from `babel-relay-plugin(-loader)` `0.3.0` to `0.4.0`, `0.4.1` or `0.6.0`.

With `0.3.0` everything works just fine but with `0.6.0` I get this error in Chrome:

`Uncaught TypeError: Cannot read property 'length' of undefined`

relay.0.4.0.js in line 5394

`if (GraphQL.isQuery(node) && node.fragments.length === 0) {`

The problem is that the `node` object does not have a fragments property.

![relay040](https://cloud.githubusercontent.com/assets/1776695/11459451/aa8a02f0-973b-11e5-9a33-a269e50781bd.png)

You can easily reproduce it yourself with my [Git Repo](https://github.com/BerndWessels/react-webpack).

To reproduce just change the dependencies in `package.json` to

`"babel-relay-plugin": "^0.6.0"`
`"babel-relay-plugin-loader": "^0.6.0"`
`"react-relay": "^0.6.0"`

Setup and run:

`npm install`

Change `data/database/db.js` to point to your mysql/postgres database:

    /**
     * Create the database connection.
     */
    var sequelize = new Sequelize('testschema', 'root', 'password', {
      host: '192.168.101.27',
      dialect: 'mysql',
      pool: {
        max: 5,
        min: 0,
        idle: 10000
      }
    });

Create some sample data:

babel-node ./scripts/databaseCreate.js

Create the schema:
`npm run schema:update`

Then in one console run:
`npm run schema:serve`

and in another console run:
`npm start`

Now you will see the error in the Chrome DevTools.

Thank you
Bernd

**Comment by josephsavona** [comment]
The screenshot clearly indicates that you are running react-relay 0.4.0, which is two versions out of date. Please update to 0.6.0.

**Comment by BerndWessels** [comment]
@josephsavona was right - the problem was that I use webpack and have react and relay as external dependencies rather than compiling it into the application bundle - and the external dependency to react-relay was not updated.
Thanks again Joseph - sometimes it helps if somebody else just points out the obvious, especially when you work alone on a project.
Cheers
Bernd

**Comment by josephsavona** [comment]
happy to help! :-)
