### ISSUE TITLE
Dynamic query name

### ISSUE THREAD

**Issue by indiejoseph** [facebook/relay#659]
Is it possible to use ES6 template strings to generate dynamic fragment query as below?
babel will prompt a error `Error: Syntax Error`

```
Relay.QL`
  fragment on Viewer {
    ${ this.name } (after: $cursor, first: $limit) {
      edges {
        node { id }
      }
    }
  }
`
```

**Comment by josephsavona** [comment]
The exact field has to be known statically in order for Relay to verify the type of the fields, its arguments, and the possible field selections. Also answered in https://github.com/facebook/relay/issues/170#issuecomment-135175640.
