### ISSUE TITLE
Installing npm module using git notation fails with "No such file or directory"

### ISSUE THREAD

**Issue by mhart** [facebook/relay#66]
```console
npm install react-relay@facebook/relay

|
> react-relay@0.1.0 preinstall /my-react-example/node_modules/react-relay
> cd scripts/babel-relay-plugin/ && npm install

sh: line 0: cd: scripts/babel-relay-plugin/: No such file or directory
```

Should this be changed to just an `install` hook instead of a `preinstall` hook?

**Comment by mhart** [comment]
Actually, now that I look at this further, I think it's because you have a specific list of files in package.json for inclusion – and the scripts directory is not in there.

**Comment by zpao** [comment]
I think #64 is going to fix this, we're removing the preinstall hook entirely and just depending on the real package.

**Comment by mhart** [comment]
Hmmm, that indeed does get rid of the error – but now there's no `dist` or `lib` directories – I need to manually go in and `npm install && npm run build` to get them there.

**Comment by mhart** [comment]
Ugh, nope that doesn't even work, I get `No gulpfile found`

**Comment by mhart** [comment]
(presumably because `gulpfile.js` is not in the `files` list in `package.json`)

**Comment by zpao** [comment]
Ah yes. Well with the build step there isn't going to be a good way to make installing via git work. I don't really like the hacks (move devDeps like gulp to deps). We made that call in React (which with our build system there is even worse). I'll leave it up to the team here to decide what's best for them.

What's your reasoning for wanting to install direct from github? I know there are a couple fixes in master that the team will be shipping soon so if that's it, I'd say wait a little bit or just use `npm link`.

**Comment by mhart** [comment]
Yeah, quite a few fixes TBH – I couldn't even get what I wanted to do working with what's on npm at the moment.

Was actually hoping to push up an open source lib for relay, and was just going to point to the github URL until the next release, but I guess that's not an option.

I'll just wait :panda_face:

**Comment by zpao** [comment]
Ah gotcha. Sorry to delay anything open source! I bet you won't have to wait long, right @steveluscher nudgenudge ;)

**Comment by steveluscher** [comment]
@yungsters wanted to push v0.1.1 tonight, but I whined and said “tomorrow.”

So… tomorrow.

**Comment by mhart** [comment]
All good now, thanks y'all! :+1:
