### ISSUE TITLE
Your schema defines a mutation field `newItem` that takes 3 arguments, but mutation fields must have exactly one argument named `input`.

### ISSUE THREAD

**Issue by jaredonline** [facebook/relay#663]
I'm not sure what's goin' on here. I've seen a lot of examples in the wild that take multiple arguments for a mutation.

The introspection looks like:
Query:
```
query schema {
  __schema{
    mutationType{
      name,
      fields{
        name,
        args{
          name,
          type{
            kind,
            ofType{
               kind,
               name
}}}}}}}
```

Response
```
{
  "data": {
    "__schema": {
      "mutationType": {
        "fields": [
          {
            "args": [
              {
                "name": "name",
                "type": {
                  "kind": "NON_NULL",
                  "ofType": {
                    "kind": "SCALAR",
                    "name": "String"
                  }
                }
              },
              {
                "name": "purchase_price_cents",
                "type": {
                  "kind": "NON_NULL",
                  "ofType": {
                    "kind": "SCALAR",
                    "name": "Int"
                  }
                }
              },
              {
                "name": "sale_price_cents",
                "type": {
                  "kind": "NON_NULL",
                  "ofType": {
                    "kind": "SCALAR",
                    "name": "Int"
                  }
                }
              }
            ],
            "name": "newItem"
          }
        ],
        "name": "Mutation"
      }
    }
  }
}
```

Is this actually a problem with my schema or something else?

**Comment by josephsavona** [comment]
See the [Relay Mutation Spec](http://facebook.github.io/relay/docs/graphql-mutations.html#content).

**Comment by josephsavona** [comment]
Relay requires that GraphQL schema follow a few conventions - single arguments to mutations is one of them.

**Comment by jaredonline** [comment]
Aha, I see. Thanks for the super fast response! I was looking at [this mutations guide](http://facebook.github.io/relay/docs/guides-mutations.html#content) which seems to be a bit out of date? It doesn't mention the special "input" variable anywhere ]=

**Comment by josephsavona** [comment]
@jaredonline Yeah, that guide is meant to cover mutations on the Relay side, but we should probably link to the Mutations Spec from that guide. PRs welcome! ;-)

**Comment by Ansalibrahim** [comment]
@jaredonline 

> single arguments to mutations is one of them.

Is there any ways to pass multiple arguments to mutations? I have seen some code like this  somewhere
`getVariables() {
    return {
      text: this.props.text,
      id:this.props.id,
      time:this.props.time
    };
  }`

**Comment by Naoto-Ida** [comment]
The [document](https://facebook.github.io/relay/docs/api-reference-relay-mutation.html#getvariables-abstract-method) states that:

> Implement this required method to prepare *variables* to be used as input to the mutation.

I'm getting the same `mutation fields must have exactly one argument named 'input'` when I do the following:

````js
getVariables() {
  return {
    name: this.props.name,
    type: this.props.type,
  }
}
````

**Comment by josephsavona** [comment]
@Naoto-Ida Glad you got this solved. We've documented this requirement in the [Relay Mutation Spec](https://facebook.github.io/relay/docs/graphql-mutations.html#content), but if there are other places that you expected to see it and didn't, please submit a PR to update the docs!

**Comment by Naoto-Ida** [comment]
@josephsavona Ok, thank you for pointing that out. I'll see if I can submit a PR this week.
