### ISSUE TITLE
Error Running Relay in MS Edge

### ISSUE THREAD

**Issue by kumarharsh** [facebook/relay#665]
I'm getting an error while trying to run an app which has Relay in the Edge browser. The browser keeps throwing this error:

```
The use of a keyword for an identifier is invalid
```
I have tracked it down to the file: [RelayTaskScheduler.js](https://github.com/facebook/relay/blob/288d6a16b45ba098e742c664bfb2f9e225d0f39f/src/tools/RelayTaskScheduler.js#L94) in the **compiled** code (which is generated by Babel):

```
var RelayTaskScheduler {
  ...
  await: function await() {...}
}
```

I've verified that this is the problem by replacing the await function name with something non-reserved. `await` is a future reserved keyword: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FReserved_Words#Future_reserved_keywords

**Comment by plievone** [comment]
Interesting, `await` is missing from https://github.com/estools/esutils where it affects babel. 'enum' is there.

**Comment by hannesj** [comment]
The same issue is also making us unable to bundle relay using Webpack 2 beta (See webpack/webpack#1725)

**Comment by gschammah** [comment]
is this fix going to be published to npm soon? thanks!
