### ISSUE TITLE
Validation error of type FieldsConflict

### ISSUE THREAD

**Issue by stephanos** [facebook/relay#667]
We are currently stuck with this Relay error: `Validation error of type FieldsConflict: cycle: they return differing types TypeA and TypeB`.

Basically this is the query that we attempt:

```
Things {
  ... on TVShow {
     owner {
        name
     }
  },
  ... on Pet {
     owner {
        name
     }
  }
}
```

`owner` of a Pet is of type `Human`, `owner` of a `TVShow` is of type `Business`. Relay doesn't seem to like that.

On the GraphQL issue tracker there was a discussion about a very similar issue over a month ago. It was said that a workaround would be to use an alias. But this doesn't work for us in Relay (yet in Graphiql the error actually disappears!).

Eventually, the issue was closed and the behavior was changed to allow 'conflicts' like this: "[...] two fields which could not overlap are still treated as a potential conflict. This change loosens this rule, allowing fields which can never both apply in a frame of execution to diverge."

Am I missing something or is Relay being too strict here?

**Comment by josephsavona** [comment]
When does this error occur? In the babel plugin or when sending the query to the server?

**Comment by stephanos** [comment]
It's from the browser console, so when sending it to the server.

**Comment by josephsavona** [comment]
Relay logs babel transform errors in the browser console as well - is the request being sent to the server?

**Comment by stephanos** [comment]
We investigated this further. We didn't realize that the error was reported by our backend (Java implementation). Sorry for the false alarm :(

**Comment by josephsavona** [comment]
Glad you figured it out and thanks for following up!
