### ISSUE TITLE
connectionFromArraySlice bug

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#669]
Hi
I believe that there is something wrong with `connectionFromArraySlice`.

If I use the following values:

`args = { after: 'YXJyYXljb25uZWN0aW9uOjQ=', first: 3 }` // `cursorToOffset(args.after) = 4`
`meta = { sliceStart: 4, arrayLength: 10 }`
`arraySlice = ['a', 'b', 'c']`

I expect the following result edges:

`'a', 'b', 'c'`

But I only get:

`'a', 'b'`

I believe the bug is in `connectionFromArraySlice` in this line:

      var startOffset = Math.max(sliceStart - 1, afterOffset, -1) + 1;

To fix this case I can just replace that line with:

    var startOffset = Math.max(sliceStart, afterOffset, 0);

But I am not sure if that will screw up other query combinations.

Can you please have a look into that.

Thank you
Bernd

**Comment by BerndWessels** [comment]
Sorry, I think the problem was outside of `connectionFromArraySlice` in my database retrieval code.

All this `after` and `before` and `zero based indexes` mess with my brain ;)

Cheers
Bernd

**Comment by josephsavona** [comment]
thanks for following up!
