### ISSUE TITLE
Allow disabling Relay container shouldComponentUpdate?

### ISSUE THREAD

**Issue by taion** [facebook/relay#674]
I have a few use cases where I have components that receive data via React `context`. The current implementation of `shouldComponentUpdate` on Relay containers blocks updates to those components via `context`.

Would it make sense to allow disabling the optimized `shouldComponentUpdate` as a configuration option for `Relay.createContainer`? Right now I have to do something a bit ugly to get the behavior I want.

**Comment by devknoll** [comment]
This seems pretty reasonable. You should open a PR :smile:

**Comment by taion** [comment]
I wanted someone to tell me if it seemed reasonable :p

Given https://github.com/facebook/react/issues/2517#issuecomment-169838716, it looks like this will at most just be a temporary workaround – but it might be useful for some months.

**Comment by peterhorne** [comment]
I'd like to pick this up if no one else is currently working on it?

I've had a quick stab at it here: https://github.com/peterhorne/relay/commit/3e437dfb7e5ae2029686c56247c041b8ccfa0945. If that looks alright please let me know and I shall add tests/docs and submit a PR.

**Comment by taion** [comment]
I never started working on this.

Your code is roughly what I had in mind. For consistency with e.g. React-Redux containers, it might make sense to make the setting be something like `pure: false`, though.

**Comment by peterhorne** [comment]
I've changed the setting name to `pure` as suggested and have submitted a PR https://github.com/facebook/relay/pull/897

**Comment by taion** [comment]
This is inconvenient timing, but @gaearon has convinced me that `shouldComponentUpdate` blocking context updates is something that should be addressed by the library using context, not the library providing the container with `shouldComponentUpdate`: https://github.com/reactjs/react-router/issues/470.

Specifically in the context of React Router, we're working on making our context use bypass intervening SCU checks by default, and extracting the utilities into a separate library for use by other context-using libraries: https://github.com/reactjs/react-router/pull/3430/files#diff-933e86e8d3d465b7c3d503e664607d59.

It's possible, then, that this is a bit of an anti-feature now, since I'm not aware of any other good reason to disable the Relay container pure render optimizations other than to allow context updates to propagate.

**Comment by josephsavona** [comment]
@taion thanks for the follow-up. We'd be happy to remove the sCU option, we'll probably wait until `react-router` and other popular libraries using context have updated with the approach you described.

**Comment by taion** [comment]
@josephsavona Our current tentative plan is to cut a React Router v3.0.0-pre.0 (or some other prerelease tag) within the next day or two, with the live links.

**Comment by bochen2014** [comment]
@josephsavona   the current replay container allow user to specify its own implementation of scu. 
so if you pass a `()=>true`, you effectively disabled RelayContainer SCU

what I'm interested, is to integrate default SCU with customer provided SCU. something like this:
```
shouldComponentUpdate(
      nextProps: Object,
      nextState: any,
      nextContext: any
    ): boolean {
  const  scu_result =   call existing SCU logic to get default result
  if(!scu_result && specShouldComponentUpdate){
      scu_result = specShouldComponentUpdate(this, nextProps, nextState, nextContext)
  }
 return  scu_result
}
```
there are 2 main changes in above code
1. if relay think it should re-render the component, then the component will be re-rendered;
2. if relay think it doesn't need to re-render the component, then ask the user
3. when calling customer provided SCU, **please bind `this` and pass along props, state and context**
