### ISSUE TITLE
Missing property, relay fetches fragment from server but it's lost on the way.

### ISSUE THREAD

**Issue by quazzie** [facebook/relay#679]
~~https://tinyurl.com/zl6vgct~~ https://tinyurl.com/nfyfhff

I used Relay playground to sketch up an example, see above link.
link.commentCount is missing when rendering MyLink, should be 123.

Locally where i can check network  relay fetches:
```
data: {
  link: {
    ... /* my other properties */
    _commentCountbye41a: 4
  }
}
```

but the fragment for commentCount does not make it through to the prop on my component.
All other properties are ok.

**Comment by quazzie** [comment]
Noticed an error in my first playground, missing breaks on cases in schema.
Had nothing to do with the problem.

Here is new link : https://tinyurl.com/nfyfhff

Also noticed if i set the local variable on MyLink to the same as passed in from HelloApp it works.

**Comment by yuzhi** [comment]
cc. @steveluscher who know the most about the playground

**Comment by steveluscher** [comment]
This is a bug. When we write it into the store, we write using the storage key `commentCount{region:\"se\"}` but when we read it out, the storage key is `commentCount{region:\"\"}`.

**Comment by steveluscher** [comment]
Oh. Not a bug. You see, when querying, you passed the region down into the fragment:

```
${MyLink.getFragment('link', { region: vars.region })} 
```

…but when constructing the UI (the read pass) you didn't pass down the region:

```
<MyLink link={viewer.link} region={this.props.relay.variables.region} />
```

Here's the [fixed playground](http://localhost:8080/relay/prototyping/playground.html#source=class%20MyLink%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20%7Blink%7D%20%3D%20this.props%3B%0A%20%20%20%20console.log('mylink'%2C%20this.props)%3B%0A%20%20%20%20return%20%3Cdiv%3E%7Blink.id%7D%20-%20%7Blink.title%7D%20-%20%7Blink.commentCount%7D%3C%2Fdiv%3E%3B%0A%20%20%7D%0A%7D%0AMyLink%20%3D%20Relay.createContainer(MyLink%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20region%3A%20''%0A%20%20%7D%2C%20%20%0A%20%20fragments%3A%20%7B%0A%20%20%20%20link%3A%20()%20%3D%3E%20Relay.QL%60%20%0A%20%20%20%20%20%20fragment%20on%20MyLink%20%7B%0A%20%20%20%20%20%20%20%20id%2C%20title%2C%20commentCount(region%3A%20%24region)%0A%20%20%20%20%20%20%7D%20%0A%20%20%20%20%60%0A%20%20%7D%20%0A%7D)%3B%0A%0Aclass%20HelloApp%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20var%20%7B%20viewer%20%7D%20%3D%20this.props%3B%0A%20%20%20%20console.log('app'%2C%20this.props)%3B%0A%20%20%20%20return%20(%3Cdiv%3E%0A%20%20%20%20%20%20%3Ch1%3Ehello2%20%7Bviewer.id%7D%3C%2Fh1%3E%0A%20%20%20%20%20%20%3CMyLink%20link%3D%7Bviewer.link%7D%20region%3D%7Bthis.props.relay.variables.region%7D%20%2F%3E%0A%20%20%20%20%3C%2Fdiv%3E)%3B%0A%20%20%7D%0A%7D%0A%0AHelloApp%20%3D%20Relay.createContainer(HelloApp%2C%20%7B%0A%20%20initialVariables%3A%20%7B%0A%20%20%20%20region%3A%20'se'%0A%20%20%7D%2C%0A%20%20fragments%3A%20%7B%0A%20%20%20%20viewer%3A%20(vars)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Viewer%20%7B%0A%20%20%20%20%20%20%20%20id%2C%20test%2C%0A%20%20%20%20%20%20%20%20link%20%7B%20%20%0A%20%20%20%20%20%20%20%20%20%20%24%7BMyLink.getFragment('link'%2C%20%7B%20region%3A%20vars.region%20%7D)%7D%20%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%20%0A%7D)%3B%0A%0Aclass%20HelloRoute%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'Hello'%3B%20%20%2F%2F%20A%20unique%20name%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20viewer%3A%20(Component)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20%7B%20viewer%20%7B%20%24%7BComponent.getFragment('viewer')%7D%20%7D%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20Component%3D%7BHelloApp%7D%0A%20%20route%3D%7Bnew%20HelloRoute()%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B&schema=import%20%7B%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%20%20GraphQLInt%2C%20%0A%7D%20from%20'graphql'%3B%0A%0Avar%20LinkType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'MyLink'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7B%20type%3A%20GraphQLString%20%7D%2C%20%0A%20%20%20%20title%3A%20%7B%20type%3A%20GraphQLString%20%7D%2C%0A%20%20%20%20commentCount%3A%20%7B%0A%20%20%20%20%20%20type%3A%20GraphQLInt%2C%0A%20%20%20%20%20%20args%3A%20%7B%0A%20%20%20%20%20%20%20%20region%3A%20%7B%20type%3A%20GraphQLString%20%7D%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20resolve%3A%20(link%2C%20args)%20%3D%3E%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20var%20res%20%3D%200%3B%0A%20%20%20%20%20%20%20%20switch(args.region)%20%7B%20%0A%20%20%20%20%20%20%20%20%20%20case%20'se'%3A%20res%20%3D%20123%3B%20break%3B%0A%20%20%20%20%20%20%20%20%20%20case%20'fi'%3A%20res%20%3D%20321%3B%20break%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20console.log('get%20comment%20count'%2C%20args.region%2C%20res)%3B%0A%20%20%20%20%20%20%20%20resolve(res)%3B%0A%20%20%20%20%20%20%7D)%20%0A%20%20%20%20%7D%0A%20%20%7D)%0A%7D)%3B%0A%0Avar%20ViewerType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Viewer'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7B%20type%3A%20GraphQLString%20%7D%2C%0A%20%20%20%20test%3A%20%7B%20type%3A%20GraphQLString%2C%20resolve%3A%20()%20%3D%3E%20'hejsan'%20%7D%2C%0A%20%20%20%20link%3A%20%7B%20%0A%20%20%20%20%20%20type%3A%20LinkType%2C%0A%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20(%7B%20id%3A%20%22link12%22%2C%20title%3A%20%22my%20title%22%20%7D)%0A%20%20%20%20%7D%0A%20%20%7D)%0A%7D)%3B%0A%20%20%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20viewer%3A%20%7B%20%20%0A%20%20%20%20%20%20%20%20type%3A%20ViewerType%2C%20%0A%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20(%7B%20id%3A%20'viewer'%20%7D)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0A).

**Comment by quazzie** [comment]
Ah had no idea that you need to pass the variable as an prop also, haven't seen it in any documentation.

Btw your playground link points to localhost :)
Thanks.
