### ISSUE TITLE
Document says "renderLoading callback is always called with a data argument"

### ISSUE THREAD

**Issue by MrOrz** [facebook/relay#68]
In the section that introduces the `renderFetched` callback in [root container guide](https://facebook.github.io/relay/docs/guides-root-container.html#renderfetched), it reads,

    This snippet configures Relay.RootContainer to render ProfilePicture within a ScrollView
    component as soon as data is ready.

    The renderLoading callback is always called with a data argument, which is a an object
    mapping from propName to query data. It is expected that the renderLoading callback
    renders the supplied Component with them (e.g. using the JSX spread attributes feature).

    Note

    Even though we have access to the data object in renderLoading, the actual data is
    intentionally opaque. This prevents the renderLoading from creating an implicit dependency
    on the fragments declared by Component.

I suppose all `renderLoading` mentioned above should be `renderFetched` instead?

**Comment by yungsters** [comment]
Yup, sorry for the confusion!

This is fixed in a0bed17e8c0f222ad7c8b0994442452548246ee1. We'll push a new version of the documentation first thing in the morning.
