### ISSUE TITLE
Potential Race condition with forceFetch?

### ISSUE THREAD

**Issue by grydstedt** [facebook/relay#687]
(Apologies for length)
I'm not entirely sure if this is a bug, but I can't really work around it:

This is the schema:
```
 viewer {
   me {
     user_id
     payments {
       id
     }
   }
 }
```
When the user is logged out, `me` is false, when logged in it's a user object with said variables.

The page has two base components, both with separate RootContainers. One main "app" view and a Header view, both start of their route at `viewer`.

1 User comes onto site, landing page requires `viewer { me { user_id } `. Since user is not logged in `me` is returned as null. Header also requests `me` and gets null
2 User logs in gets redirected to a dashboard page. The dashboard view requires:
```
viewer {
   me {
     payments {
       id
     }
   }
}
```
3 The dashboard is rendered but has stale data. `me` is null but the view can deal with it.
4 At the same time the Header view listens in on a "logged in" event and does `forceFetch`, it requires data:
```
viewer {
 me {
    user_id
  }
}
```
5 The fetch from the Header (force fetched) returns from server before the request for the dashboard. The dashboard is observing `viewer` and is therefore re-rendered. The `me` is now not null, but it does not contain `payments`. The dashboard was not prepared for an `undefined` value for payments and therefore breaks.

**Comment by josephsavona** [comment]
@grydstedt were you able to resolve this?

**Comment by grydstedt** [comment]
I was not, but the example was contrived, I was going to come up with a reproducible test case. But I think the issue remains. It boils down being able to forceFetch while a another query is excuting. I think
