### ISSUE TITLE
Relay concerned with seemingly unrelated data.

### ISSUE THREAD

**Issue by ts-smith** [facebook/relay#692]
I have a query that is behaving very unexpectedly.

The query has a connection over a union, and a selection, both orthagonal.

```
fragment on Viewer {
    user: (id: userId) @include (if: $userSelected) {
       ...
    }
    ${SomeConnectionOverUnionsOfAandBNotUsers.getFragment('viewer')}
}
```

when I change the variables to include the user section, relay does a node query for every node in the connection, trying to determine the type apparently (it only wants {id, __typename}).

If I throw errors in the type resolver of the union nodes, the connection part still works. But when doing that, the user part fails.

**Comment by ts-smith** [comment]
After more research, if I create an unused variable and change it, the same behavior occurs.

**Comment by josephsavona** [comment]
Thanks for asking about this. Could you clarify if this is a bug (data is missing in your app or it otherwise breaks) or if the queries are simply different than you expected? In other case, we'd be happy to help debug - what is the full query in your component, and what is the full query that is sent to the network?

**Comment by ts-smith** [comment]
There is a lot of new concepts with Relay, so it is hard to know if that is a bug or not. But if it is a bug, it is simply an under optimization, because I believe the type information of the nodes should already be present. It is hard to show all of the potentially relevant information, but I found that the problem only exists when I have a certain fragment on one of the union types of the query. I will try to reproduce in in isolation so it is easier to see.

**Comment by ts-smith** [comment]
I wasn't able to reproduce the bug, but fortunately there was an easy work around by implementing the union in code for this specific case. Somehow, asking for fields other than {id, __typename} on the client for some types of the union would cause it to always refetch the type, regardless of whether or not it was actually fetched. Some of the types on the union did not have this problem, though.

**Comment by josephsavona** [comment]
Thanks for filing this. I'm going to close since we don't have a repro case - going forward we're moving toward APIs where queries are not modified at runtime, which may help to alleviate weird quirks such as this.
