### ISSUE TITLE
Using NODE_DELETE lists become [null] array with 1 item

### ISSUE THREAD

**Issue by oguzbilgic** [facebook/relay#693]
Using `NODE_DELETE`, related lists become `[null]` array with 1 item in them.

Given this mutation payload:

```js
fragment on DeleteCarPayload {
  id
  viewer { cars }
}
```

with this `getConfigs`:

```js
return [{
  type: 'NODE_DELETE',
  parentName: 'viewer',
  parentID: this.props.viewer.id,
  connectionName: 'cars',
  deletedIDFieldName: 'id'
}];
```

There is also another field that has cars in it: `shop.cars`. Car should also be removed from `shop.cars` list. However It's only converted to `null`, It's not removed, unlike `viewer.cars`

```js
// mutation applied
console.log(viewer.cars.length, viewer.cars)
// 0, []
console.log(shop.cars.length, shop.cars)
// 1, [null]
```

I believe this is a bug. I can't think of a reason why this should be the behavior.

**Comment by josephsavona** [comment]
Thanks for reporting this. Relay removes deleted nodes from connections, and we should probably remove them from lists for consistency. In this case that would mean returning an empty list instead of a list of `[null]`. 

@yuzhi can you think of any reason we shouldn't/can't do this?

**Comment by yuzhi** [comment]
@oguzbilgic Yeah `NODE_DELETE` mainly support nodes and nodes in connections since we do keep some extra metadata about each connection. If you want to update `viewer {cars}` and you know that can change as a part of this mutation, you can add another `FIELDS_CHANGE` config.
`
      {
        type: RelayMutationType.FIELDS_CHANGE,
        fieldIDs: { viewer: this.props.viewer.id},
      },
`
@josephsavona  We can probably do some filtering, although I don't know if there are legit cases for having nulls in plural fields.

**Comment by oguzbilgic** [comment]
@yuzhi Thank you. Thats exactly how I got around. However It's really pita at the moment. Basically `NODE_DELETE` doesn't do what its suppose to, and we need to find every list that may include this , get their ids in `getFragment`, and maybe add to `payload` ...

**Comment by josephsavona** [comment]
It definitely seems that filtering nulls would be the correct behavior here. @oguzbilgic any interest in submitting a PR to fix? 

For you or anyone else interested in a PR, the best place to start would be in RelayRecordStore where we return the list of IDs in the list in [`getLinkedRecordIDs`](https://github.com/facebook/relay/blob/master/src/store/RelayRecordStore.js#L509-L519). This could be changed to filter out IDs for known-deleted records, similarly to how we filter connection edges [here](https://github.com/facebook/relay/blob/master/src/store/RelayRecordStore.js#L681).

**Comment by oguzbilgic** [comment]
@josephsavona :+1: I have no experience, but It says 'good first bug', I can give it a try this weekend. :)

**Comment by andimarek** [comment]
I just submitted a PR, which should fix this Issue: #722

**Comment by wincent** [comment]
Closing this one because you have the PR in flight. Thanks for contributing!

**Comment by chirag04** [comment]
@wincent can we reopen this since the PR was not merged.

**Comment by RichardLindhout** [comment]
I still have a null in my array.

**Comment by devunt** [comment]
It's 2022 and I still have a null in my array.

**Comment by michaelmcneilnet** [comment]
This is still a problem, can it be reopened?

**Comment by JCMais** [comment]
how are folks solving this nowadays?
