### ISSUE TITLE
No way to get an underlying GraphQL error from RelayMutationTransaction's onFailure

### ISSUE THREAD

**Issue by LegNeato** [facebook/relay#696]
No way to get an underlying GraphQL error from RelayMutationTransaction's `onFailure`:

```js
  doIt: Function = () => {
    Relay.Store.update(
      new CreateMyRelayMutation(), {
        onSuccess: this.onMutationSuccess,
        onFailure: this.onMutationFailure,
      },
    );
  };
  onMutationSuccess: Function = (response: CreateMyMutationResponse) => {
    // Do stuff.
  };
  onMutationFailure: Function = (transaction: RelayMutationTransaction) => {
    console.log(transaction.getError().message);
  };
```

The problem is `transaction.getError()` in the `onFailure` callback only gives me access to a Relay `Error`, which means I can't get at the underlying GraphQL `Error`:

```
Server request for mutation `MyComponent` failed for the following reasons:

1. Cannot get name.
   createMyInput!){createMy(input:$input_0){clientMuta
                             ^^^
```

GraphQL errors are likely more user friendly than the Relay errors. I think `onFailure` should get passed the underlying GraphQL errors somehow to let tools choose which (Relay or GraphQL) is important for their use-case.

**Comment by josephsavona** [comment]
Thanks for asking about this. Errors have a `source` property that includes the original error information from the server, which can be accessed as `transaction.getError().source`. It's an object with all the error data returned from the server.

**Comment by LegNeato** [comment]
Ah sweet, that is exactly what I needed...guess I missed it. Thanks!

**Comment by rapilabs** [comment]
That's odd, I'm getting an object of type `Response` from my `transaction.getError()`.  Any ideas on what I'm doing wrong?  Running with the latest development snapshot.

**Comment by josephsavona** [comment]
@rapilabs are you using the default network layer? If yes, and the error property is not what's documented then it's a bug (and worth filing a new issue).

**Comment by mloncaric** [comment]
How would you show that message to the end user?
Components are updated only in case transaction was successful..

I was thinking about using redux for that, but.. that looks like an overkill.
(onFailure would dispatch an action, which would then in turn trigger the component update)

**Comment by wincent** [comment]
@mloncaric: You could use `setState` if you wanted to avoid involving any Redux/Flux actions.

**Comment by unirey** [comment]
For feature seekers, here's an example, it has both error and success callbacks:


```js

// Methods on ES6 React component

_handleClick(e) {
    e.preventDefault()

	const id = '123' // get id from somewhere (ref, state, props, e.target etc)

    Relay.Store.commitUpdate(
        new LikeMutation({
            post: {
				id
            }
        }), {
			onFailure: this._onFailure.bind(this),
			onSuccess: this._onSuccess
		}
    )
}

_onFailure(res) {
    // PS! "errors" is an array and you need to add iteration logic if you get > 1 error
	const err = res.getError().source.errors[0].message

    // For example, set a state for component in order to trigger update
    this.setState({error: err})
}

_onSuccess(res) {
    // "res" is same returned JSON data that you can see in dev tools
}



render() {
    return (

       <div>

           {/* other elements */}

           {this.state.error ?

               <span className="error-warning-alert-super-red">{this.state.error}</span>

           : ''}

      </div>
    )
}

```

**Comment by somit** [comment]
Using transaction.getError().source  ..but should be included in docs...

**Comment by matart15** [comment]
@somit you saved me from writing a whole custom error handler.
