### ISSUE TITLE
Multiple routes examples

### ISSUE THREAD

**Issue by genbit** [facebook/relay#7]
Not an issue, just some questions to understand how Routes in Relay work. Example which uses creates routes  would be nice to have.

Why do we need 'path' property?
For example, from documentation it looks like developer must handle location changes manually:

```js
window.addEventListener('popstate', () => {
  var userID = getQueryParamFromURI('userID', document.location.href);
  var profileRoute = new ProfileRoute(userID);
  React.render(
    <Relay.RootContainer
      Component={Profile}
      route={profileRoute}
    />
  );
});
```

not clear what kind of role 'path' property have or will have in future.

**Comment by yungsters** [comment]
We definitely need more examples of how routes can be used (and maybe how it integrates with other open source routing solutions).

When you refer to the `path` property, I assume you're referring to the `static path?: string` property or `RelayRoute`. This is kind of a remnant of the larger role that `RelayRoute` used to play in application routing. (This is also why we chose not to document the `uri` and `path` properties, heh.)

In the future, I think we will strip out any routing-specific properties (and maybe even rename `RelayRoute` to be something more like `RelayQueryRoots` or `RelayQueryConfig`).

**Comment by keithpitt** [comment]
> In the future, I think we will strip out any routing-specific properties (and maybe even rename RelayRoute to be something more like RelayQueryRoots or RelayQueryConfig).

:+1: I was confused by it's name when I started reading the documentation. "It's called a route, where do I set the path? How does this work with the history API" are things that I was thinking.

**Comment by genbit** [comment]
@yungsters thanks for explanation! Maybe note somewhere in docs will be useful, I believe many people will have similar confusion.

**Comment by sgwilym** [comment]
> In the future, I think we will strip out any routing-specific properties (and maybe even rename RelayRoute to be something more like RelayQueryRoots or RelayQueryConfig).

@yungsters This would be great, also for (spoken) conversation: I can imagine some confusion could pop up with the phonetically incestuous names of  `Relay.Route`, `Relay.Container`, and `Relay.RootContainer`.

**Comment by yungsters** [comment]
> This would be great, also for (spoken) conversation:

I don't know... all the confusion and laughs when confusing route and root were pretty fun. Haha, but yes... more reason to rename it.

**Comment by yungsters** [comment]
Now that we've got the helpful documentation, closing this out. I have an internal task to track the removal of `path` and `uri`.
