### ISSUE TITLE
Support node 5.x

### ISSUE THREAD

**Issue by kasselTrankos** [facebook/relay#706]
Hi,
Im trying to use relay with node 5.x, and give me allways 
Current node version is not supported for development, expected "5.3.0" to satisfy "4.x"

Could i use it?
tks

**Comment by josephsavona** [comment]
Thanks for filing this. I'm not aware of any reason that we *can't* support node 5.x, but others will know more.

cc @zpao

**Comment by kasselTrankos** [comment]
Ok, meanwhile i'll try to use in one isomorphic project

**Comment by kasselTrankos** [comment]
thanks

**Comment by zpao** [comment]
I don't recall if there was a reason not to support node 5 for development, but npm 2 was still a requirement due to Flow configs IIRC.

**Comment by kasselTrankos** [comment]
hi @zpao, i put the error code.
```javascript
AssertionError: Current node version is not supported for development, expected "5.3.0" to satisfy "4.x".
    at Object.<anonymous> (/home/vera/js/relay/base/node_modules/fbjs-scripts/node/check-dev-engines.js:38:3)
```
 :(, so if npm requirement Flow change will be usefull,

**Comment by edvinerikson** [comment]
This seems to have been resolved in https://github.com/facebook/relay/commit/60c8a76a47385d8f843e35de72d16f758689abc0

**Comment by josephsavona** [comment]
As @edvinerikson noted this should now be resolved.

**Comment by zpao** [comment]
Fwiw, bumping the npm version there is probably not right. Flow likely
won't work (because of nested node_modules in flowconfig)

**Comment by josephsavona** [comment]
Reopening per @zpao

**Comment by edvinerikson** [comment]
@zpao can you elaborate a little bit more? I ran `flow check src/` and got `Found 0 errors` back.
When I added a type error I got:
```
~/code/relay(master ✗) flow check src/
src/RelayPublic.js:39
 39:   return 1 * 1;
              ^^^^^ number. This type is incompatible with
 38: function bar(): React$Element {
                     ^^^^^^^^^^^^^ React$Element

src/RelayPublic.js:42
 42: foo('string');
     ^^^^^^^^^^^^^ function call
 42: foo('string');
         ^^^^^^^^ string. This type is incompatible with
 34: function foo(a: number): React$Element {
                     ^^^^^^ number

Found 2 errors
```
and the code:
```jsx
function foo(a: number): React$Element {
  return <span />;
}

function bar(): React$Element {
  return 1 * 1;
}

foo('string');
bar();

```

**Comment by zpao** [comment]
Hmm, I guess it's ok then. I was only looking at the previously linked
commit where there was still a nested node_modules reference, not master.
Looks like master is free :). Sorry for the poorly informed noise!

**Comment by josephsavona** [comment]
All good!

**Comment by edvinerikson** [comment]
No worries, maybe I should've linked to master instead. :)
