### ISSUE TITLE
"Unexpected invocation at runtime" error.

### ISSUE THREAD

**Issue by Nutelac** [facebook/relay#71]
I'm getting this error:
```
Error: Invariant Violation: RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `Relay.QL`.
```

Don't know where is the problem. Error is probably caused by `Relay.createContainer` function. I'm using Babel in my application, but I'm compiling it via Webpack before running.

**Comment by fson** [comment]
Hey, thanks for your question. Looks like you need to enable [Babel Relay Plugin](https://facebook.github.io/relay/docs/guides-babel-plugin.html). This plugin needs to be added to your Babel plugins and it converts the `Relay.QL` tagged template strings to code that describes the query.

See [relay-starter-kit](https://github.com/relayjs/relay-starter-kit) for an example of how to do this. Here are the relevant parts:
* [build/babelRelayPlugin.js](https://github.com/relayjs/relay-starter-kit/blob/83f3e3696c62c4bb975f2127d8c07b5730b4dcf4/build/babelRelayPlugin.js) – reads your schema from a `schema.json` file and creates an instance of `babel-relay-plugin` with the schema.
* [server.js](https://github.com/relayjs/relay-starter-kit/blob/83f3e3696c62c4bb975f2127d8c07b5730b4dcf4/server.js#L26) – the line in webpack configuration that tells Babel to use the plugin.
* [scripts/updateSchema.js](https://github.com/relayjs/relay-starter-kit/blob/83f3e3696c62c4bb975f2127d8c07b5730b4dcf4/scripts/updateSchema.js) – a script you can run to update the `schema.json` file.

**Comment by Nutelac** [comment]
Thank you, now it's everything works well.

**Comment by sibeliusseraphini** [comment]
is this the same for react-native?

**Comment by kassens** [comment]
@sibeliusseraphini: Yes, if you see this error you're probably also missing the transform.

**Comment by trentontri** [comment]
@fson what if we're trying to use Relay with an external source? For instance I want to work with the Github GraphQL API but `updateSchema.js` keeps overriding my attempts to fetch remote data.

**Comment by fson** [comment]
@trentontri To use an external API, the schema needs to be fetched using an introspection query from the server. You could use https://github.com/graphcool/babel-plugin-react-relay to set that up in an easy way (you'll only need to configure the URL of the GraphQL endpoint).

**Comment by Naoto-Ida** [comment]
I've run into this issue several times with my React Native apps, but I've managed to get through it with the method above.
I'm getting the same error now but its quite a different situation.

Say for instance you have a Relay Container called ArticleList which requests articles.
Inside it, it gets a Fragment defined in ArticleListItem.
I'm trying to package these components into a npm library, so that in my other apps I can do

```
import { ArticleList, ArticleListItem } from 'my-companies-common-components'
```

in all of our future apps and get a list of articles with the queries baked in.

I setup `babelRelayPlugin`, `.babelrc`, etc. in the `my-companies-common-components` directory, but this doesn't seem to do it.

**Comment by josephsavona** [comment]
My guess is that the way you have babel configured in the main plugin, it isn't transforming files from node_modules. It might be better to transform the my-company-components before "publishing"

**Comment by Naoto-Ida** [comment]
I have the same setup in the *my-company-components* project, then run a command called `build` which is `babel src -d lib --presets es2015,stage-0,react` in order to transpile, then set the package's main file to `lib/index.js`. Output in `lib` is looking ok from what I can gather.
