### ISSUE TITLE
flow types

### ISSUE THREAD

**Issue by bsr203** [facebook/relay#712]
Relay source is heavily annotated with flow types, and I too like to use these types in my project. Currently I am getting lot of errors on `Missing annotation`. I am not sure if there a way to `import` relay type definition in my code.

I think the compiled code strip off all type def, so probably below import doesn't make sense
`import type RelayQuery from 'react-relay/lib/RelayQuery';`. So what is the proper way to annotate relay code with flow type from `react-relay` ?

It would be great if one of the example in `/examples` is annotated with flow types.

```
 getMutation() {
                    ^ return. Missing annotation
 getOptimisticResponse() {
                              ^ return. Missing annotation
...

 7:   viewer: () => Relay.QL`query {viewer}`,
                     ^^^^^^^^^^^^^^^^^^^^^^^^ return. Missing annotation

src/routes/page.js:11
 11:   node: () => Relay.QL`query {node(id: $id)}`,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ return. Missing annotation
```

**Comment by josephsavona** [comment]
I apologize for our lack of an answer here. The public types are all exported in `RelayTypes` - does that help?

**Comment by bsr203** [comment]
:-)  that's alright, and thanks for all your hard work and support on it. I may try to make a standalone test case, but a detailed query on the same at SO here http://stackoverflow.com/questions/36023373/flowtype-annotate-relay-query
