### ISSUE TITLE
FIELDS_CHANGE according to payload

### ISSUE THREAD

**Issue by Gregoor** [facebook/relay#716]
It seems that only fields of a node can be changed that are known prior to commiting the mutation. In my payload there is a variable count of nodes that need to be updated, but the config examples I found rely on known IDs in the props.

Why do we even need `FIELDS_CHANGE`? Can't Relay just update every node that is in a payload?
And if it is needed, how about having a field in the config that returns the node to be changed, given the whole payload. e.g.:

```javascript
getConfigs() {
  return [{
    type: 'FIELDS_CHANGE',
    nodes: ({selectedShip, storedShips}) => [selectedShip, ...storedShips]
  }];
}
```

**Comment by NevilleS** [comment]
Remember, the mutation config is used to design the mutation query passed to the server. With the constraint of a single round trip, you can't have the mutation query depend on the mutation payload, that's impossible.

In cases where a large portion of the graph is affected, the only thing you can do today is to use REQUIRED_CHILDREN to pull out some data from the payload and use that data to kick off a second fetch. For example you could ask for the `affectedNodeIDs`, and then use those IDs as variables to another Relay fragment.

It'd be useful to have a nice, repeatable way to do this via mutations though. Fundamentally it'll require two round trips so it'd be a new type of mutation config... maybe something like `EXPIRE_NODES` that instructs the Relay store to purge it's local cache of a list of IDs, and then ask the containers subscribing to those nodes to refetch their data...

**Comment by Gregoor** [comment]
Maybe I'm missing something: In what way can a config change the query?

I would imagine that without FIELDS_CHANGE, Relay could just require IDs for all the nodes in the fat query, so that it knows which fields to update.

**Comment by Gregoor** [comment]
Since we can't know what is already loaded (and can't do the intersection with the fat-query) without knowing the ID, letting the server just return everything would be overfetching. So I guess my ideas from the original post are against the spirit of Relay.

**Comment by NevilleS** [comment]
Heh, I don't think it's necessarily "against the spirit". Mutations that affect arbitrary portions of the graph are a real-world problem so there should be a "Relay-ish" way to solve it. Right now you can do two round trips using `REQUIRED_CHILDREN` to get the affected IDs from the payload, but that's a lot of boilerplate, so it might be nice to support something a bit more declarative. Personally I like the idea of building in a way for the GraphQL server to instruct Relay which nodes have been changed, so Relay can go ahead and at least expire those nodes from it's local store, but I haven't thought it through a ton yet.
