### ISSUE TITLE
Mutation not fetching data specified by the fat query in conjunction with RANGE_ADD?

### ISSUE THREAD

**Issue by ryancole** [facebook/relay#719]
I'm trying to understand `RANGE_ADD`. I've provided the mutation config, for `RANGE_ADD`, with all the required information. I use the `viewer` naming convention, with my connections nested within `viewer`. Below is what my complete Relay Mutation looks like ...

```js
import Relay from "react-relay";

export default class CreateTeamMutation extends Relay.Mutation {
  static fragments = {
    viewer: () => Relay.QL`
      fragment on Viewer {
        id
      }
    `
  }

  getMutation() {
    return Relay.QL`
      mutation { createTeam }
    `;
  }

  getVariables() {
    return {
      name: this.props.name
    };
  }

  getFatQuery() {
    return Relay.QL`
      fragment on CreateTeamPayload {
        edge,
        viewer {
          teams
        }
      }
    `;
  }

  getConfigs() {
    console.log(this.props.viewer);
    return [{
      type: "RANGE_ADD",
      edgeName: "edge",
      parentID: this.props.viewer.id,
      parentName: "viewer",
      connectionName: "teams",
      rangeBehaviors: {
        "": "append"
      }
    }];
  }
};
```

I provide a fragment for the `viewer` id, which at run-time, within `getConfigs`, I can see is present.

In the GraphQL Mutation response payload, `CreateTeamPayload`, the `viewer` field is provided so that Relay can make use of the connection within the mutation config for `RANGE_ADD`. Also, within `CreateTeamPayload`, the new edge is provided as `edge`.

These three bits of info (viewer id for the parent, the connection information and the edge) seem to be all that `RANGE_ADD` demands. I also make sure to request this data from the server, via the fat query so that Relay has access to it for the mutation config.

Relay does not seem to be including what I've specified in the fat query, and what is required for the mutation config, in what it dispatches to the server, though. All that Relay is requesting is the `clientMutationId`. Here is the request made by Relay ...

```json
{
  "query": "mutation CreateTeamMutation($input_0:CreateTeamInput!){createTeam(input:$input_0){clientMutationId}}",
  "variables": {
    "input_0": {
      "name": "foo bar",
      "clientMutationId": "0"
    }
  }
}
```

And, in chain reaction fashion, this causes Relay, who is expecting the `viewer` and `edge` for the mutation config, to throw an error ...

```
Warning: writeRelayUpdatePayload(): Expected response payload to include the newly created edge `edge` and its `node` field. Did you forget to update the `RANGE_ADD` mutation config?
```

Those required fields could totally be there if Relay had included them. Does `RANGE_ADD` have to be accompanied by `REQUIRED_CHILDREN` for this to work? The mutation goes through to the server, and the record is created on the server, it's just the client-side mutation config fails to incorporate the changed data into the store.

**Comment by dphaener** [comment]
@ryancole There's a few other threads floating around in regards to this and I can't find them right now, but essentially, if that data has never been requested by Relay before, then it doesn't know about it and won't request it by itself. I.E. if your query doesn't request `teams` explicitly somewhere, then Relay is not tracking it. In this case, you have to explicitly accompany it with the `REQUIRED_CHILDREN` config type.

**Comment by ryancole** [comment]
@dphaener Ah, I see, OK. So if `teams` is requested, and therefore already being tracked, somewhere higher up in the container tree, or by a previous query, then all would work. So, in the event of creating a new node, which couldn't be in the store already somewhere, it might always be good to accompany this with `REQUIRED_CHILDREN`. Thanks for the info!
