### ISSUE TITLE
Relay not fetching new data

### ISSUE THREAD

**Issue by trbngr** [facebook/relay#725]
This works fine in 0.5.0.

I have a route that fetches data
```
class EventLayout extends Component {

    constructor(props) {
        super(props);
    }

    render() {

        const { children, eventId, event: {title, uuid} } = this.props;

        return (
            <div>
                <div className="ui">
                    <div>{title}</div>
                    <div className="menuContainer">
                        <Link to={{pathname: `/events/${eventId}/sessions`}}>Sessions</Link>
                    </div>
                    {React.cloneElement(children, {key: pathname})}
                </div>
            </div>
        );
    }
}
export default createContainer(EventLayout, {
    fragments: {
        event: ()=> Relay.QL`
            fragment on Event{
                uuid
                title
            }        `
    }
});
```

when I click the `sessions` link, we transition to `Sessions` where I need to grab more data from the query. 
```
class Sessions extends Component{
...
}
export default createContainer(Sessions, {
    initialVariables: {
        limit: 10000
    },
    fragments: {
        event: () => Relay.QL`
            fragment on Event{

                sessions(first: $limit){
                  count
                  edges{
                    uuid
                    node{
                      id
                      title
                      published
                      speakers{
                        count
                      }
                    }
                  }
                }
                ${RemoveSession.getFragment('event')}
            }`
    }
});
```

Relay 0.6 doesn't detect any changes in the query in `diffRelayQuery.js`

```
    // Diff the current dataID
    var scope = makeScope(dataID);
    var diffOutput = visitor.visit(nodeRoot, path, scope);
    var diffNode = diffOutput ? diffOutput.diffNode : null;
    if (diffNode) {
      !(diffNode instanceof RelayQuery.Root) ? process.env.NODE_ENV !== 'production' ? invariant(false, 'diffRelayQuery(): Expected result to be a root query.') : invariant(false) : undefined;
      queries.push(diffNode);
    }
  });
  return queries.concat(visitor.getSplitQueries());
```
and therefore, doesn't post the query to the server.

Relay 0.5 works correctly.

**Comment by steveluscher** [comment]
Quick question: I see that the `Event` type has a `uuid` field, but does it have an `id` field?

**Comment by trbngr** [comment]
It does, but perhaps I need to include it. 

BRB trying now.

**Comment by trbngr** [comment]
No luck.

**Comment by steveluscher** [comment]
Is this using relay-tools/react-router-relay? How is the transition from one route to the next implemented?

**Comment by trbngr** [comment]
I *am* using react-router-relay.

**Comment by devknoll** [comment]
Maybe @taion has some insight.

**Comment by taion** [comment]
Any chance this is related to https://github.com/relay-tools/react-router-relay/issues/76? I don't believe I've changed anything relating to that lately.

**Comment by trbngr** [comment]
I don't believe it is related, no. 

I will create a repro today.

**Comment by josephsavona** [comment]
@trbngr Can you provide a bit more information to help us debug this? In particular, what are the queries for the initial route and the sessions route that doesn't work?

**Comment by edvinerikson** [comment]
@trbngr Is this something that has been resolved, perhaps in a newer version of Relay or react-router-relay? I'm trying to find "stalled" issues and it would be great if could you give us an update.

**Comment by trbngr** [comment]
My appologies for not updating this issue. I got stuck on another project since this was opened and haven't had a chance to get back to it.

Feel free to close this. When I get back on this project, I will have an answer ;)

**Comment by edvinerikson** [comment]
No worries and thanks for the fast reply! Feel free to reopen whenever you get time. :)
