### ISSUE TITLE
alias validate bug when build concrete query

### ISSUE THREAD

**Issue by filod** [facebook/relay#731]
say i have this query in my code:
```
fragment on Content {
  blocks {
    __typename,
    ... on VoiceBlock {
      url
    }
    ... on ImageBlock {
      url (width: $width, larger: $larger),
    }
  }
}
```

i will get an error says: ` url is used as an alias more than once. Please use unique aliases.`

if i remove the first url field of VoiceBlock, everything works fine

**Comment by josephsavona** [comment]
Thanks for reporting this. This seems like a bug in the validation logic (which is only a DEV time warning); it doesn't take into account that the same alias can be safely used in fragments of different concrete types.

**Comment by filod** [comment]
yes, but `react-native` will take `console.error` as an error also brings up a redbox

**Comment by josephsavona** [comment]
Following up here, this is actually invalid GraphQL. The same alias, `url`, is being used to represent two different pieces of information that could appear at the same level of the output: `VoiceBlock.url` and `ImageBlock.url(width: ..., larger: ...)`. These can't be merged, so at least one of the fields must be given a different alias.
