### ISSUE TITLE
[Improvement] Optional parameters on Mutations

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#739]
Imagine you want to update a person.
Somewhere in your app you want to update only the email.
Somewhere else you want to update almost all properties.
And somewhere else you only want to update only the language.

At the moment it seems that you have to write a new mutation for each of these instead of having only one mutation like `updatePersonMutation` with optional parameters.

So what I suggest is basically allow optional parameters on mutations.

If that is already possible please let me know how.

**Comment by NevilleS** [comment]
You can totally do this. Just make the `UpdatePersonMutationInput` have optional fields like `email`, `language`, etc. The server will need to then react to which fields are provided. In fact, Relay mutations *require* there to just be a single parameter (`input`), but you define the shape of that param entirely.

**Comment by BerndWessels** [comment]
@NevilleS Thanks you are right.
