### ISSUE TITLE
Reference error while importing react-relay

### ISSUE THREAD

**Issue by mattiasewers** [facebook/relay#741]
I get this message when importing react-relay with webpack

ReferenceError: self is not defined: self is not definedget home

**Comment by dphaener** [comment]
I've seen this crop up when trying to include Relay on the server side. You can use this library to help get around that for now: https://github.com/denvned/isomorphic-relay

Another technique is to create your own custom network layer and inject that, which is what I've done.
You can see that implementation here: https://gist.github.com/dphaener/a5c0a6ab87cb2297483f

In essence what's happening is Relay is trying to use `fetch` on the server. In my network layer I'm using isomorphic-fetch.

**Comment by mattiasewers** [comment]
@dphaener Yes that was the problem and isomorphic-relay solved it for me. Thanks man! Might try your solution as well

**Comment by josephsavona** [comment]
@mattiasewers thanks for reporting this. We're aware of the compatibility issue with Relay in non-web environments - @skevy's pending #713 addresses the issue with `self`. For now, `isomorphic-relay` is a good workaround.

**Comment by guigrpa** [comment]
@dphaener If I'm not missing something, the problem with the second approach you mention is that you don't even get the chance to inject your custom network layer. Currently Relay loads its own fetch-dependent `RelayDefaultNetworkLayer` module at the very beginning.

**Comment by dphaener** [comment]
@guigrpa Relay will use the `RelayDefaultNetworkLayer` if you do not inject one:

`Relay.injectNetworkLayer(new MyCustomNetworkLayer())`

I think I may have left that part out of my gist. :)

Good docs on this here: https://facebook.github.io/relay/docs/guides-network-layer.html#content
