### ISSUE TITLE
GraphQL Server Cache invalidation

### ISSUE THREAD

**Issue by xuorig** [facebook/relay#744]
Let's say we have a posts connection, with `first: 10`. We update that to `20` to fetch 10 more posts.
Great, with relay's store, we'll only fetch 10 more posts without re-fetching the rest, this is awesome.

Now what if one of the 10 "old" posts had changed ? Will we ever see a possibility for a GraphQL server to invalidate Relay's client side cache ?

Just wondering if you guys thought of this along the way, and if it's in the plans to introduce something like that.

**Comment by josephsavona** [comment]
Great question! This is exactly the purpose that GraphQL subscriptions are meant to address. Determining when a previously cached datum should be invalidated is a non-trivial problem given that many inputs can affect any one output, so we've opted to pursue event-based subscriptions to balance practicality and liveness. The [blog post](http://graphql.org/blog/subscriptions-in-graphql-and-relay/) goes into much more detail about the rationale for this approach, and we're tracking work on implementing this in open source at #541. 

Does that address the question?

**Comment by xuorig** [comment]
Thanks @josephsavona, wasn't sure if subscription were the answer to that problem!
