### ISSUE TITLE
Mutation query missing fields that should have been tracked by previous queries

### ISSUE THREAD

**Issue by NevilleS** [facebook/relay#745]
This is a hard one to describe succinctly, so excuse the length. I think this is a bug, but can't rule out the possibility that we're just doing something wrong here...

We noticed some peculiar behaviour where our mutation queries get formed incorrectly in some circumstances. It seems that if multiple components register fragments for a linked field that is initially returned as `null`, the Relay store can get into a bad state wherein future mutation queries will only refetch the first fragment on that field, even though the fat query should include both. Basically, the store doesn't seem to be tracking fragments correctly in this case. Let me try to explain that in some more detail.

### Reproduction
I haven't built a repro for this in something like Relay Playground yet. I can probably figure out a way to do that, but I'm not particularly familiar with writing schemas with `graphql-js` yet, so instead I've just typed up the simplest example I could come up with... sorry.

(EDIT: I added a unit test that reproduces the issue here: https://github.com/NevilleS/relay/commit/a39ab59e62c0d466e7138cc90ea022e659f2408c)

### Example
Let's say we have this great app where we track `Users` and `Birthdays`.  A `User` type has a single `birthday` field, and a `Birthday` type has `year, `month`, and `day` fields, which are strings. Both `User` and `Birthday` are nodes, so they have ids. Our app has two components: `UserComponent` and `UserDetailsComponent`. We have a single `SetBirthdayMutation` that is used to create or update a `User`'s `birthday`.

Generally speaking, the user flow is something like this:
1) Navigate to some kind of user profile, where we use a `UserComponent` to render basic information about the user, including their birth year if the birthday is set.
2) Click on a "details" link which uses a `UserDetailsComponent` to render all the birthday information: year, month, and day - if it's set. There's also a form here that lets you edit the birthday data.
3) Complete a form that submits a `SetBirthdayMutation` that creates or updates the `birthday` field.

Step 1) `UserComponent` just shows the user's birthday year:
```
fragment on User {
  birthday  {
    year
  }
}
```

Step 2) `UserDetailsComponent` shows the month and day
```
fragment on User {
  birthday  {
    month
    day
  }
}
```

Step 3) `SetBirthdayMutation` takes a `user_id`, `year, `month`, and `day`, and creates/updates a `Birthday` for the given `User`. The fat query looks like this:
```
fragment on SetBirthdayMutationPayload {
  user {
    birthday
  }
}
```
Let's assume we use `FIELDS_CHANGE` and provide the `user_id` as the parentID, etc. etc.

### The Problem
Here's the thing - the `birthday` field for a user isn't defined until that mutation is run at least once, which creates the field. That means if we run those steps in order, the server returns `birthday: null` for the first step, and Relay doesn't even include the `birthday { day }` fragment in the second query, since it already knows that the `birthday` doesn't exist, I guess (that's a reasonable optimization). That looks something like this:
```
// Query 1)
query {
  node(id: "some-user") {
    id
    birthday {
      id
      year
    }
  }
}

// Response 1)
data = {
  node: {
    id: "some-user",
    birthday: null
  }
}

// Query 2)
query {
  node(id: "some-user") {
    id
    // other fields, but does not request birthday { year, month, day }
  }
}

// Response 2)
data = {
  node: {
    id: "some-user",
    // other fields, no birthday
  }
}
```

Alright, here's the curious part. When we run the mutation following steps 1 & 2, it looks something like this (omitting some obvious things like clientMutationId for brevity):
```
mutation set_birthday_mutation(input: { user_id: "some-user", month: "8", day: "13" }) {
  user {
    birthday {
      year    // ONLY THE YEAR IS REQUESTED, WHY?
    }
  }
}
```

For some reason, **the mutation doesn't try to fetch birthday { month, day }*** if you run that sequence. However, if you go straight to the `UserDetailsComponent` without doing the `UserComponent` first (e.g. only steps 2 and 3), the sequence looks more like this
```
// Query 1) is not sent

// Query 2) is the new first query
query {
  node(id: "some-user") {
    id
    birthday {
      year
      month
      day
    }
  }
}

// Response 2)
data = {
  node: {
    id: "some-user",
    birthday: null
  }
}

// Mutation
mutation set_birthday_mutation(input: { user_id: "some-user", month: "8", day: "13" }) {
  user {
    birthday {
      year
      month
      day    
    }
  }
}
```
In this sequence, Relay correctly tracks the second `Birthday` fragment, so we get back the new birthday data we were expecting.

### Theory
It seems that the problem is somehow related to there being two fragments defined on `Birthday`, and only the first one is being tracked. I'm guessing that the fact that `birthday: null` is returned is important, and probably ends up meaning that the fragment isn't added to the tracker. Since the record store isn't updated by either query (no data), and the tracker isn't updated, the intersection performed by `RelayMutationQuery` results in a query that only contains the fragment of the first query.

Thanks for your help!

**Comment by NevilleS** [comment]
Oops, almost forgot - this is on react-relay `0.6.0`

**Comment by NevilleS** [comment]
OK I did some more investigation this morning and I think I've tracked down what's causing this issue for me...

When the first query executes, a `trackedNode` is set up for the `User` that keeps track of the `Birthday` fragment (where we ask for the `year`).

When the second query executes, `diffRelayQuery` traverses the query constructed by the new container including our more extensive fragment on `Birthday`. However, when it visits the `birthday` field, it notices that the `dataID` is `null`, so it doesn't include the fragment in the new query. This is a reasonable optimization for the query, but it has the **side-effect** of not updating the parent `trackedNode` with the fact that there is a container that wants this new fragment!

I'm talking specifically about the code here: https://github.com/facebook/relay/blob/master/src/traversal/diffRelayQuery.js#L400

If I change the code to this instead, the final mutation query works well:
```
  diffLink(
    field: RelayQuery.Field,
    path: RelayQueryPath,
    dataID: DataID,
  ): ?DiffOutput {
    var nextDataID =
      this._store.getLinkedRecordID(dataID, field.getStorageKey());
    if (nextDataID === undefined || nextDataID === null) {
      return {
        diffNode: field,
        trackedNode: null,
      };
    }

    return this.traverse(
      field,
      path.getPath(field, nextDataID),
      makeScope(nextDataID)
    );
  }
```

This, of course, means we end up *not* pruning the fragment from the second query, so we end up requesting fields off a linked field we *know* is `null`. So it's not necessarily a fix, and it might even end up meaning we remove the tracking of the original fragment (not sure yet), but it definitely explains what I'm seeing.

**Comment by NevilleS** [comment]
I've written a unit test https://github.com/NevilleS/relay/commit/a39ab59e62c0d466e7138cc90ea022e659f2408c that reproduces what I'm seeing - subsequent queries that request additional data off of a `null` node are not tracked.

I'm happy to submit a PR, too, but I don't know exactly how I might break other things by messing with `diffRelayQuery`... something as trivial as this (https://github.com/NevilleS/relay/commit/c5abe4616fb509d57377e9c14636f0df6b93a9f8) fixes the issue I see with my mutation and constructs the second query optimally (not re-requesting `address`), but I'm not convinced it'd be that easy. Also, my unit test still fails because the tracked query doesn't include the `lastName` , so I'm pretty sure it's still wrong, although I could just be misunderstanding how `RelayQueryTracker` works.

I'm going to stop messing with this issue for now; let me know what you guys think should happen in cases like this :+1:

**Comment by NevilleS** [comment]
Any ideas? Like I said I'm happy to dig around a bit and submit a PR as needed, but I'd appreciate a bit of guidance since I'm poking around the codebase a bit blindly.

**Comment by larsonjj** [comment]
I am also having a having a similar fetching data with relay.
Here are the details:

1. Load initial page
 - queries a field `account` on `viewer` via Relay.Container
 - `account` field comes back `null` (correct behavior)
2. Redirect user to new page to fill out form (as they do not have an account)
 - User correctly fills out form and submits
 - account mutation is fired and completes successfully
3. User gets redirected back to initial page
 - `account` field is now no longer `null` when API is queried, but Relay does not re-fetch data or store user's form data locally
 - page is rendered incorrectly as Relay still thinks `account` is `null`

Problem is that Relay SHOULD refetch or store locally the `account` data since it will no longer be `null`, but it doesn't.

Ex: Mutation code:

```
export default class RegisterMutation extends Relay.Mutation {
  getMutation(): any {
    return Relay.QL`mutation { openAccount }`;
  }

  getVariables() {
    const { input } = this.props;
    return {
      account: {
        username: input.username,
        password: input.password
      },
    };
  }

  getFatQuery(): any {
    return Relay.QL`
      fragment on OpenAccountPayload {
        viewer {
          account {
            username
            password
          }
        }
      }
    `;
  }

  getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: {
        viewer: this.props.viewer.id
      }
    }];
  }
}

OnboardingMutation.fragments = {
  viewer: () => Relay.QL`
    fragment on Viewer {
      id
    }
  `
};
```

***NOTE***
@NevilleS's [PR](https://github.com/NevilleS/relay/commit/c5abe4616fb509d57377e9c14636f0df6b93a9f8) fixes this issue that I'm having.

**Comment by NevilleS** [comment]
Well, calling it a PR is a bit generous, but good to hear.

Like I said, I'm happy to clean up the code a bit and submit a real PR, I just want to make sure my change is doing the right thing.

**Comment by larsonjj** [comment]
@NevilleS, It definitely fixes the issue I've been having. It would be great if you submitted a PR to see if this gets more attention from the FB team.

**Comment by josephsavona** [comment]
@NevilleS can you submit a PR with your test and fix?

**Comment by NevilleS** [comment]
Yup, will do. Is that fix essentially correct though, or am I not considering some important side effect?

**Comment by NevilleS** [comment]
I'm not confident this is 100% correct, I updated my unit test to highlight this. I'll open a PR and we can discuss there, though.

**Comment by dminkovsky** [comment]
@josephsavona my use case is exactly the same as @larsonjj, except rename `account` to `user` :D
