### ISSUE TITLE
Support type-unique IDs

### ISSUE THREAD

**Issue by pushrax** [facebook/relay#75]
When implementing a Relay-compatible GraphQL API within an existing application, one point of friction is the requirement of globally-unique IDs as part of the `Node` interface. Combining the type name with the existing type-unique ID is often suggested, but this can make interop with legacy APIs more involved.

Fundamentally there isn't a reason why the client needs anything other than a type-unique ID, since it always knows the type of the `Node` it's requesting.

The most obvious implementation to me would be to add a `type` argument to the `node` root call. If enabled, Relay would then prepend the type name to any internal `DataID`s to keep the simplicity of a single store, but expose type-unique IDs externally to the application.

@leebyron thanks for suggesting I open this issue.

**Comment by yungsters** [comment]
> Fundamentally there isn't a reason why the client needs anything other than a type-unique ID, since it always knows the type of the `Node` it's requesting.

Currently, Relay does not always know the concrete type of the node that is being requested. We would have to augment every field with a dynamic `parentType` (e.g. interfaces) with a query for the type. Not impossible, but it does add more to the request, response, and processing.

**Comment by josephsavona** [comment]
Building on @yungsters's comment - supporting type-specific IDs is less trivial than it might seem at first glance and introduces complexity and maintenance cost to the framework. It's more than a matter of adding a `type` field to the `node` call. Relay would have to fetch and track the type of *every* record in the system and use this information everywhere it constructs queries (which is obviously often). 

Given that it is trivial for the server to encode/decode a global ID to/from type + ID, it is not clear that the cost of implementation and maintenance is justified. We'd be curious to hear feedback from you and the community about this.

**Comment by pushrax** [comment]
That makes sense. It's probably more work to actually implement that within a given GraphQL server.

**Comment by dthree** [comment]
This is quite rough for me where I am adding relay to a legacy database structure that has fixed IDs for common lookups across several systems, and which aren't going to change. These are used all over my application.
