### ISSUE TITLE
why base64 encode/decode with ascii instead of utf-8

### ISSUE THREAD

**Issue by quazzie** [facebook/relay#755]
Is there a reason why you user ascii as encoding and decoding base64 ids ?
I got bitten by this as i had a swedish character in an id and was incorrectly encoded.
Changed ascii to utf-8 in graphql-relay\lib\utils\base64.js and it worked.

**Comment by josephsavona** [comment]
Thanks for raising this. Any interest in submitting a PR to change this at [graphql/graphql-relay-js](https://github.com/graphql/graphql-relay-js)? Looks like the line you're referencing is https://github.com/graphql/graphql-relay-js/blob/master/src/utils/base64.js#L14

**Comment by josephsavona** [comment]
Let's move this to https://github.com/graphql/graphql-relay-js/issues/62
