### ISSUE TITLE
[meta] public API for evicting unreferenced data and tracked queries

### ISSUE THREAD

**Issue by josephsavona** [facebook/relay#756]
By default, Relay does not evict data from the cache. This can cause two main issues:
- Memory growth: As more data is loaded the amount of memory used by the cache can grow.
- Mutation performance: As more data is loaded, the number of fields that may need to updated by a mutation can also grow. 

Both cases can be addressed by evicting data (and tracked queries) that is not required for active views. We have an experimental implementation of garbage collection (aka cache eviction) at https://github.com/facebook/relay/blob/master/src/store/RelayGarbageCollector.js, but there are known edges cases that we're continuing to address before providing a public API for using it. This task is to track progress.

See also #537 and #479.

**Comment by NevilleS** [comment]
This makes a ton of sense. I worry a bit that if a user keeps a Relay application open long enough, they're local graph just gets bigger and bigger (and more and more stale), so being able to specify some basic garbage collection / expiration policies would be useful.

**Comment by NevilleS** [comment]
In parallel, an API to expire local data that you believe is out of date (but may still be needed for an active view) would be useful to handle mutations where the client cannot know ahead of time which nodes will be affected by the change.

For example, if we have a mutation that deletes a `Group` which has many `Users`, we might need to refetch the `groupsCount` for all the affected users. We can't necessarily guarantee that the client knows all the `Users` that will be affected by the deletion - a group might have 100,000+ `Users`, for example. However, the server could add a `affectedUserIDs` field to the mutation payload that the client could use to search for matching users in the local store and expire them manually (via something like `Relay.Store.expireNodes(affectedUserIDs)`). If any of those nodes are still subscribed to by active components, a refetch would be necessary.

**Comment by wincent** [comment]
Just adding a cross-reference to #538, which is about simplifying the mutations API. An unstated subgoal there is simplifying the underlying implementation too, which in turn means that things like tracked queries are up for discussion as well (the most extreme version of which is abolishing them; I'm not certain that's the right call yet, but I'm exploring it and alternatives to the current implementation).

**Comment by josephsavona** [comment]
We're planning to support garbage-collection in a future release (see also #1369).

**Comment by wincent** [comment]
Now that Relay Modern is out, I think we can close this. It includes basic methods for retaining data that is being actively rendered and disposing of it once it is no longer on screen. Note that we may wish to pursue more flexible or nuanced garbage collection strategies in the future, but we should file separate issues for those.
