### ISSUE TITLE
"Expected record data for prop" warning false positives

### ISSUE THREAD

**Issue by taion** [facebook/relay#759]
I'm getting false positives from the "Expected record data for prop" check on https://github.com/facebook/relay/blob/v0.6.1/src/container/RelayContainer.js#L577-L599, when I explicitly pass in a `null` for the prop in question.

This happens whenever any of the other props for the component is a sufficiently long string. This happens because `fragmentHash` is a stringified number, and can be used to index into a character in a string.

I think there are two ways to fix this; either don't check this when the matching prop is explicitly null on https://github.com/facebook/relay/blob/v0.6.1/src/container/RelayContainer.js#L580, or check that `props[propName]` is not a string on https://github.com/facebook/relay/blob/v0.6.1/src/container/RelayContainer.js#L588.

Does either approach seem reasonable?

**Comment by wincent** [comment]
Thanks for highlighting this, @taion. Of those, the string check sounds a bit more cumbersome, but it feels like it's technically the more correct fix. Want to submit a PR?

**Comment by taion** [comment]
Sure – I just needed confirmation that I wasn't missing something.

**Comment by taion** [comment]
Oops! Turns out this was fixed by https://github.com/facebook/relay/commit/839eeb36814d44b23aa4a57ea7625fcfa3d95835 on master before I even opened this issue.

I missed that somehow.

**Comment by wincent** [comment]
Well spotted. That's what I get for not looking at the code in master.
