### ISSUE TITLE
npm support out-of-date

### ISSUE THREAD

**Issue by dhenson02** [facebook/relay#762]
In relation to #706, trying to `npm install` from the root (or any of the examples of course) fails due to an expected version of `2.x` rather than the current (at this time) `3.5.3`.

While I understand certain things may or may not be set up to use something past the version it was developed under, it would be useful to place a **requirements** section at the top of the README files.

Anyways, going to go downgrade so I can enjoy some awesomeness and throw in some [GraphQL](https://facebook.github.io/relay/docs/getting-started.html) while I'm at it.

Thanks for all the hard work (and for open-sourcing this).

**Comment by developersencha** [comment]
In the package.json you may change the npm version to 3.x and you overcome this error.

**Comment by wincent** [comment]
Thanks for reporting this, @dhenson02. I think we can actually tackle this as part of #706, which you've already referenced, so I am going to close this one out.
