### ISSUE TITLE
Relay doesn't include viewer in query after setVariables/forceFetch

### ISSUE THREAD

**Issue by brad-decker** [facebook/relay#765]
### Problem Description
I have a Relay container defined below that fetches 15 items of a given category and is updated when a user switches categories on the frontend. The intent is to refetch the next set of films when a user switches categories. The initial query sent by the container is correct and returns the films attached to the viewer instance. However subsequent queries are not 'ViewerQueries' and are not attached to the viewer element. 

We are doing similiar refetches on other pages for slug based navigation to item pages and we don't suffer from this issue, however in each of those cases the setVariables call is made from componentWillMount whereas this particular case is being fired after the component is mounted and user input is changing the view.  Any help or tips are greatly appreciated! 

##### Relay Container Query definition:
```js
export default Relay.createContainer(FilmsContainer, {
  initialVariables: {
    category: 'Upcoming Auctions'
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        films(first: 15, category: $category){
          edges{
            node {
              createdAt,
              URL,
              filmID,
              title,
              description,
              property {
                lifestyles
                country {
                  name
                },
                state {
                  name
                }
              }
              category,
              featuredPhoto {
                sizes {
                  thumb2 {
                    src
                  }
                }
              }
            }
          }
        }
      }
    `
  }
});
```

##### Initial Full Query Logged on Server
```
query ViewerQueries{
  viewer{id,...F0}
} fragment F0 on User{
  _films1ednKd:films(first:15,category:"Upcoming Auctions"){
      edges{
        node{
          createdAt,
          URL,
          filmID,
          title,
          description,
          property{
            lifestyles,
            country{
              name,
              id
            },
            state{
              name,
              id
            },
            id
          },
          category,
          featuredPhoto{
            sizes{
              thumb2{
                src
              }
           },
           id
        },
        id
     },
     cursor
   },
   pageInfo{
    hasNextPage,
    hasPreviousPage
   }
  },
id
}
```

##### initial response blueprint
```{ data: { viewer: { id: 'VXNlcjo0MDA=', _films1ednKd: [Object] } } }```

##### reFetch/setVariables query logged on server
```
query Index{
  node(id:"VXNlcjo0MDA="){
    ...F0
  }
}
fragment F0 on User{_films1ednKd:films(first:15,category:"Upcoming Auctions"){
  edges{
    node{
      createdAt,
      URL,
      filmID,
      title,
      description,
      property{
        lifestyles,
       country{
          name,
          id
        },
       state{
          name,
          id
       },
       id
     },
     category,
     featuredPhoto{
        sizes{
          thumb2{
            src
          }
       },
       id
     },
     id
   },
   cursor
  },
  pageInfo{
    hasNextPage,
    hasPreviousPage
  }
},
id
}

##### Data signature of refetch
```{ data: { node: { _films1ednKd: [Object], id: 'VXNlcjo0MDA=' } } }```

**Comment by josephsavona** [comment]
Thanks for asking. This is expected behavior: for objects with an `id`, Relay will always fetch additional information via the `node` root field. In this case, the initial response indicates that the `id` of viewer is "VXNlcjo0MDA=", and Relay therefore fetches additional data for `setVariables` via `node(id: "VXNlcjo0MDA=")`.

Is there data missing after the `setVariables` call resolves, or was the query just different than you expected?

**Comment by brad-decker** [comment]
The viewer.films in this case never updates, the values don't change and the query takes twice to three times as long to complete according to react-dev-tools

**Comment by josephsavona** [comment]
What variables are you changing? (It might help to paste the code where you call `setVariables`, for example) In the examples you gave both the initial query and `setVariables` query have the same parameters - `films(first:15,category:"Upcoming Auctions")` - so the data would presumably be the same.

**Comment by brad-decker** [comment]
@josephsavona - I'm setting category, but I just discovered that the props are being set but some child component is not receiving the updated props. So all is operating well - i guess my only question then is why do these queries seem to take longer... is it because its using the node query to identify the source instead of the viewer query? 

Thanks!

**Comment by josephsavona** [comment]
> my only question then is why do these queries seem to take longer

There's nothing inherent in a `node` query that would be slower - generally, the `resolve` function simply maps the string type to a GraphQL schema type - see the [todo example](https://github.com/facebook/relay/blob/master/examples/todo/data/schema.js#L51-L69) - you might double check that you don't have complex logic inside that function that could cause the slowdown.

**Comment by brad-decker** [comment]
Thanks for the help on this, this is resolved (user error)

**Comment by josephsavona** [comment]
Thanks for the follow up!
