### ISSUE TITLE
NODE_DELETE getOptimisticResponse causes error

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#768]
Hi
I have a `NODE_DELETE` mutation that should remove a `post` from the `viewer.posts` connection.

It works fine without `getOptimisticResponse` !

BUT with `getOptimisticResponse` it kind of breaks with a short flashing red screen and the following error:

Warning: Failed propType: Required prop `post` was not specified in `Post`. Check the render method of `Relay(Post)`.

So it seems after the `optimistic response` and before the `server response` the `deleted edge` is still being rendered but the `deleted post` is already gone which causes the `post component` render to fail.

It looks like that the `optimistic response` is not handled in the same way as the `server response` even though they are identical.

Is this a bug in relay?

[Here is the complete project](https://github.com/BerndWessels/react-webpack) to reproduce the problem.

This is the mutation:

    class DeletePostMutation extends Relay.Mutation {
      getMutation() {
        return Relay.QL`mutation {deletePost}`;
      }
      getVariables() {
        return {
          id: this.props.post.id
        };
      }
      getFatQuery() {
        return Relay.QL`
          fragment on DeletePostPayload {
            viewer {
              id
              posts
            }
            deletedId
          }`;
      }
      getConfigs() {
        return [{
          type: 'NODE_DELETE',
          parentName: 'viewer',
          parentID: this.props.viewer.id,
          connectionName: 'posts',
          deletedIDFieldName: 'deletedId'
        }];
      }
      static fragments = {
        viewer: () => Relay.QL`
          fragment on Person {
            id
          }`,
        post: () => Relay.QL`
          fragment on Post {
            id
          }`
      };
      getOptimisticResponse() {
        const { viewer, post } = this.props;
        const viewerPayload = { id: viewer.id };
        return {
          viewer: viewerPayload,
          deletedId: post.id
        };
      }
    }

This is the post component:

    class Post extends React.Component {
      // Expected properties.
      static propTypes = {
        post: React.PropTypes.object.isRequired
      };
    
      // Initialize the component.
      constructor(props) {
        super(props);
      }
    
      _handleDeletePost = () => {
        const { viewer, post } = this.props;
        // We commit the update directly to the database.
        Relay.Store.commitUpdate(new DeletePostMutation({viewer, post}), {
          onFailure: (err) => {
            // TODO: Deal with it!
            console.log(err);
          },
          onSuccess: (result) => {
            // TODO: Maybe nothing todo here?
          }
        });
      };
      // Render the component.
      render() {
        return (
          <ListGroupItem>
            <div>{this.props.post.title} - {this.props.post.content}</div>
            <Button onClick={this._handleDeletePost}>
              <FormattedMessage
                id="post.button.delete"
                description="The delete post button's text."
                defaultMessage="Delete"/>
            </Button>
            <ul>
              {this.props.post.comments.edges.map(edge =>
                <Comment key={edge.cursor} comment={edge.node}/>
              )}
            </ul>
          </ListGroupItem>
        );
      }
    }
    
    /**
     * The data container.
     */
    export default Relay.createContainer(Post, {
      initialVariables: {
        first: 3
      },
      fragments: {
        viewer: () => Relay.QL`
          fragment on Person {
            ${DeletePostMutation.getFragment('viewer')}
          }`,
        post: () => Relay.QL`
          fragment on Post {
            id
            title
            content
            comments(first: $first) {
              edges {
                cursor
                node {
                  ${Comment.getFragment('comment')}
                }
              }
              totalCount
              pageInfo {
                hasNextPage
                hasPreviousPage
                startCursor
                endCursor
              }
            }
            ${DeletePostMutation.getFragment('post')}
          }`
      }
    });

And this is the home component with the list of posts:

    class Home extends React.Component {
      // Expected properties.
      static propTypes = {
        viewer: React.PropTypes.object.isRequired
      };
    
      // Expected context properties.
      static contextTypes = {
        storeSession: React.PropTypes.func,
        restoreSession: React.PropTypes.func
      };
    
      // Initialize the component.
      constructor(props) {
        super(props);
        // Default state.
        this.state = {
          postsPage: 1,
          postsPageSize: 2,
          postsTotalPages: 5
        };
      }
    
      // Invoked once, both on the client and server, immediately before the initial rendering occurs.
      // If you call setState within this method,
      // render() will see the updated state and will be executed only once despite the state change.
      componentWillMount() {
        // Restore the previous session if any.
        this.context.restoreSession(this.props.location.pathname, this);
      }
    
      // Invoked when a component is receiving new props. This method is not called for the initial render.
      // Use this as an opportunity to react to a prop transition before render() is called by updating the state using this.setState().
      // The old props can be accessed via this.props. Calling this.setState() within this function will not trigger an additional render.
      componentWillReceiveProps(nextProps, nextContext) {
        // Update the state.
        this.setState({
          postsPage: Math.floor(nextProps.relay.variables.offset / nextProps.relay.variables.limit) + 1,
          postsPageSize: nextProps.relay.variables.limit,
          postsTotalPages: Math.ceil(nextProps.viewer.posts.totalCount / nextProps.relay.variables.limit)
        });
        // Update the session store for this page.
        this.context.storeSession(this.props.location.pathname, {
          relay: {offset: nextProps.relay.variables.offset, limit: nextProps.relay.variables.limit}
        });
      }
    
      // The user changed the posts page size.
      _handlePostsPageSizeChange = (e, eventKey) => {
        // update relay query parameters
        this.props.relay.setVariables({
          limit: eventKey
        });
      };
      // The user changed the current posts page index.
      _handlePostsPageIndexChange = (e, pagingEvent) => {
        // update relay query parameters
        this.props.relay.setVariables({
          offset: (pagingEvent.eventKey - 1) * this.state.postsPageSize
        });
      };
      // Render the component.
      render() {
        // Calculate stuff.
        return (
          <form>
            <Grid>
              <Row>
                <Col xs={12}>
                  <PageHeader>
                    <FormattedMessage
                      id="home.greeting"
                      description="Welcome greeting to the user"
                      defaultMessage="Welcome {firstName} {lastName}!"
                      values={{firstName: this.props.viewer.firstName, lastName: this.props.viewer.lastName}}
                    />
                    <span>{this.props.viewer.posts.totalCount}</span>
                  </PageHeader>
                </Col>
              </Row>
              <Row style={{marginBottom: 10}}>
                <Col xs={12}>
                  <Pagination first last prev next ellipsis maxButtons={3}
                              items={this.state.postsTotalPages}
                              activePage={this.state.postsPage}
                              onSelect={this._handlePostsPageIndexChange}/>
                  <DropdownButton id="postsPageSizeDropdown" onSelect={this._handlePostsPageSizeChange}
                                  className="pagination-dropdown" bsStyle="default" title={this.state.postsPageSize}
                                  style={{marginLeft: 5}}>
                    <MenuItem eventKey={1} active={this.state.postsPageSize == 1}>1</MenuItem>
                    <MenuItem eventKey={2} active={this.state.postsPageSize == 2}>2</MenuItem>
                    <MenuItem eventKey={3} active={this.state.postsPageSize == 3}>3</MenuItem>
                  </DropdownButton>
                </Col>
              </Row>
              <Row>
                <Col xs={12}>
                  <ListGroup>
                    {this.props.viewer.posts.edges.map(edge =>
                      <Post key={edge.cursor} viewer={this.props.viewer} post={edge.node}/>
                    )}
                  </ListGroup>
                </Col>
              </Row>
            </Grid>
          </form>
        );
      }
    }
    
    /**
     * The data container.
     */
    export default Relay.createContainer(Home, {
      initialVariables: {
        limit: 2,
        offset: 0
      },
      fragments: {
        viewer: () => Relay.QL`
          fragment on Person {
            firstName
            lastName
            email
            posts(limit: $limit, offset: $offset) {
              ${postsFragment}
            }
             ${Post.getFragment('viewer')}
          }`
      }
    });
    
    var postsFragment = Relay.QL`
      fragment on postConnection {
        edges {
          cursor
          node {
            ${Post.getFragment('post')}
          }
        }
        totalCount
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
      }`;

**Comment by steveluscher** [comment]
Thanks for the detailed repro. I was able to run it and test a fix.

Fixing this, starting with #922. In the meantime, if you want to unbreak and future-proof your code, add `@relay(pattern: true)` to all of your fat queries:

```
fragment on DeletePostPayload @relay(pattern: false) {
  viewer {
    id
    posts
  }
  deletedId
}

fragment on UpdatePersonPayload @relay(pattern: true) {
  person {
    firstName
    lastName
    email
    language
  }
}
```

**Comment by steveluscher** [comment]
Oh sorry. This doesn't fix this; wrong issue.

**Comment by steveluscher** [comment]
So, here's what I think is going on here.

`NODE_DELETE`, `RANGE_DELETE`, and `RANGE_ADD` depend on the thing you're targeting being a connection (having `isConnection` metadata added to it by the Babel Relay plugin). I suspect that your `postsConnection` isn't acquiring this metadata because it's not a real connection (you've rolled your own offset/limit solution that deviates from the spec somewhat). Look at how your printed `comments` field has `isConnection: true` while your 'posts' field does not. This might be because your `pageInfo` type has the type “paginationInfo” rather than “PageInfo”, but I didn't dig much deeper after figuring out that your posts aren't being stored in the Relay store as a bonafide connection.

We should probably do something here to check that `connectionName` actually represents a bonafide connection. I'll talk to @wincent about this.

Because it's not a connection, `NODE_DELETE` kills the node but not the edge. What you end up with, until the server comes back with what appears to be an ‘overfetched’ response (see #769), is a deleted node and an intact edge. That's why your post re-renders, but has no data, causing the exception.

I think what you want in this case is either to:

1. Find a way to make `posts` register as a bonafide connection
2. Use `FIELDS_CHANGE` and actually return a new set of edges in your optimistic response with the deleted edge removed. This is probably unsuitable for other reasons – it might be hard to ‘pull up’ results from the next page before the server returns.

Side note: make sure that when you return `deletedId` you use the global ID:

```js
// Delete the post.
return dbPost.destroy().then(()=> {
  // Return the global ID, not the local ID
  return {id: inputFields.id, viewer: {id: dbPost.personId}};
});
```
