### ISSUE TITLE
connection mutation OVER-FETCHING problem

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#769]
Hi

When running a NODE_DELETE mutation on a connection, it seems that it causes the connection to request updates for all already cached nodes.

This feels like a bug because it causes massive over-fetching even if the user only deletes a single node.

Is this a bug, am I doing something wrong?

Surely deleting a node should not cause maybe thousands of already fetched notes to be re-fetched?

[Here is a Project](https://github.com/BerndWessels/react-webpack) you can use to reproduce and analyse if you want.

Cheers
Bernd

**Comment by tuananhtd** [comment]
I'm having the same issue on both NODE_DELETE and RANGE_ADD. It's strange to me that the todo example still works fine even when it looks no different from my code.

**Comment by wincent** [comment]
Is the issue because you have `viewer { posts }` in your fat query?

**Comment by BerndWessels** [comment]
@wincent Possibly. Here it is:

```
getFatQuery() {
    return Relay.QL`
      fragment on DeletePostPayload {
        viewer {
          id
          posts
        }
        deletedId
      }
    `;
  }
```

But how else would you do it? What is the right way to insert to and delete from a connection without mass updates of the relay cache?

**Comment by tuananhtd** [comment]
@BerndWessels I recently gives this on another attempt and it works. My query is just like your. Actually not putting the connection field in the fat query will cause the overfetching.

**Comment by steveluscher** [comment]
This is happening because `posts` is not a bonafide connection in your schema. See #768 for more discussion.
