### ISSUE TITLE
How can event subscriptions update connections?

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#770]
I am following [this issue here](https://github.com/facebook/relay/issues/541).

But I have a hard time to understand how connections can be updated based on event subscriptions.

Imagine I have a connection showing posts. Currently my connection shows posts between 8am and 10am. Now somebody deletes a post at 9am. I would expect that this post will disappear from my connection.
Obviously similar scenarios come up for `INSERT`/`UPDATE`/`DELETE`.

* Will this be possible to do with event subscriptions?
* Do cursors play a role in this?
* What about windowed connections with `offset` and `limit` rather than the infinite connections with `first` and `after`?

Can a connection like this below be updated efficiently via event subscriptions?

    fragment on User {
        posts(offset: 100, limit: 20, orderBy: ['author', 'createdAt']) {
            edges {
                node {
                    author
                    title
                    text
                }
            }
            totalCount
        }
    }

**Comment by josephsavona** [comment]
Under the proposed API a product would likely subscribe to an "event deletion" event, maybe something like:

```graphql
# pseudo-code
subscription EventDeleteSubscription {
  eventDelete {
    deletedEventID
  }
}
``` 

With a `NODE_DELETE` subscription configuration. Relay tracks the connections that contain any given node, so the subscription event firing would cause the node to be efficiently removed from the connection, as expected.

This isn't an issue or an enhancement, so I'm going to close it. Feel free to ask follow up questions and we'll try to address.

**Comment by BerndWessels** [comment]
Oh, I see @josephsavona.

So there will be a subscription for each connection, since the NODE_DELETE config will act on a node id specific for each connection I guess?

I am keen to see how that feels in reality, especially non-infinite (windowed) connection are still giving me a bit of a headache in relay since I am never sure what the right way is to implement it with all the internal relay mechanisms to consider and now subscriptions coming into play as well.
