### ISSUE TITLE
Support adding a list of edges via RANGE_ADD

### ISSUE THREAD

**Issue by jaredly** [facebook/relay#783]
or have a new RANGE_ADD_MUTLI or something.

**Comment by NevilleS** [comment]
How would you see this differing from providing multiple `RANGE_ADD` configs (which is supported)? For example:
```javascript
  getConfigs() {
    return [{
      type: "RANGE_ADD",
      parentName: "user",
      parentID: this.props.userID,
      connectionName: "pets",
      edgeName: "pet_edge",
      rangeBehaviors: {
        '': 'append'
      }
    }, {
      type: "RANGE_ADD",
      parentName: "pet",
      parentID: this.props.petID,
      connectionName: "owners",
      edgeName: "owner_edge",
      rangeBehaviors: {
        '': 'append'
      }
    }]
  }
```

**Comment by jaredly** [comment]
ah -- I mean "multiple edges" the number of which is not previously known. e.g. the server will return a list of edges that are to be added.

```js
getConfigs() {
  return [{
    type: "RANGE_ADD_MUTLI",
    parentName: "user",
    parentID: this.props.userID,
    connectionName: "pets",
    edgesName: "new_pets_edges",
    rangeBehaviors: {
      '': 'append',
    }
  }]
}
```

**Comment by NevilleS** [comment]
Ah, yes. In that case I agree - Relay mutations aren't particularly good at expressing "large" changes to the graph. Things like cascading deletes are [similarly problematic]...(http://stackoverflow.com/questions/34428093/handling-destruction-of-a-parent-node-via-a-graphql-mutation-in-relay)

**Comment by wincent** [comment]
Thanks for posting, @jaredly. Making common operations easy/simple, and harder operations possible/feasible is one of the goals of our current work on mutations (see #538); the surface area and scope of possible changes is huge however, so I am still gathering up all the issues and feedback trying to make a coherent plan. In the meantime please keep the feedback and ideas coming.

**Comment by wincent** [comment]
This is important, so I'm going to fold it into #538, which is about overhauling the mutations API. (It will be easier to manage with the various interrelated mutations issues in a single place.)
