### ISSUE TITLE
Update roadmap for H1 2016

### ISSUE THREAD

**Issue by wincent** [facebook/relay#788]
Update https://github.com/facebook/relay/wiki/Roadmap based on 2/2/2016 meeting.

**Comment by wincent** [comment]
Done.

**Comment by josephsavona** [comment]
@wincent there are ongoing community efforts to build subscriptions (#411), contextual state (#558), support server rendering, etc. What do you think about including these in the roadmap?

**Comment by wincent** [comment]
I think we can link to these but it will be most useful to draw a clean
line between what is prioritized internally and what's happening
externally. (Note the old roadmap is still at the bottom of the page and
does link to or mention these issues.)

[typed in my phone; apologies in advance for the errors.]

**Comment by josephsavona** [comment]
That makes sense. Perhaps we can link to a list of issues that have open PRs to provide a sense of what is being worked on by the community. 

Also, what about using gists for the weekly meetings so that people can ask questions in the comments?

**Comment by wincent** [comment]
I think the PR tab is the place to go for that; listing them in a wiki page
would be redundant and get out of date fast. If the PR tab isn't
sufficiently fine grained then we should use labels to make it so, but
there's a slippery slope there, making the judgment call about which PRs
should be highlighted.

re: gists, the commenting is nice but it's not a great interface for it (no
notifications). I think if we just post our meeting notes on Twitter we can
field questions there usefully. It's emphemeral, but so are plans, right?
