### ISSUE TITLE
`onProgress`-style callback for mutations with files

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#789]
This is feature I would like to see in Relay. 

It would require adding callback onProgress to `commitUpdate` and `applyUpdate` functions and pass this callback to `RelayMutationRequest` where it could be called from network layer.

Tricky is that `fetch` api does not support progress yet. So I suspect that it will be difficult to add this feature into standard relay network layer if there is no significant demand.

At the moment I can monitor with custom network layer (using xhr) that some files are being uploaded. It would be nice I could call individual callbacks that are passed on mutation creation, but currently I think there is no way to access mutation from network layer (to get callback from props or something).

Any ideas how to make this more feasible?

Thanks!

**Comment by GrzegorzKaczan** [comment]
+1 we need that feature native as well.
03.02.2016 10:21 AM "Jarda Kotěšovec" <notifications@github.com> napisał(a):

**Comment by wincent** [comment]
Thanks for filing this issue @jardakotesovec!

This is important, so I'm going to fold it into #538, which is about overhauling the mutations API. (It will be easier to manage with the various interrelated mutations issues in a single place.)

**Comment by jardakotesovec** [comment]
@wincent May I ask whats the status for this feature? I will need it sometime soon, so wondering what route should I take.  Default network layers is using *fetch*, which does not have progress callback, so it basically means using XHR in my custom network layer..  

I could spend some time on PRs if you give me clues what you envision in relay core for that matter.

**Comment by wincent** [comment]
@jardakotesovec I did some work a while back on introducing an [alternative low-level API for mutations](https://github.com/facebook/relay/blob/829450ab74aa5c6b0cdb453cb76b1fbc45f16687/src/mutation/RelayGraphQLMutation.js), but that decidedly doesn't involve any changes at the network layer. We're still working on improving mutations: if you check out [the meeting notes](https://github.com/facebook/relay/tree/master/meta/meeting-notes) you'll see that right now one of the things we're working on is prototyping some new ideas ([context](https://www.youtube.com/watch?v=7TA4T2TJQx0)), and we'll be doing more work on mutations as part of that.

I think it's going to be difficult to change this without going the custom network layer route, as we are not likely to swap out `fetch` in the default layer.

**Comment by jardakotesovec** [comment]
@wincent Thanks. Using xhr in custom network layer works just fine. Issue is that in `sendMutation` method I am getting `RelayMutationRequest` where I can't access mutation callbacks nor props, so basically I can pass just one onProgress function to the network layer on initialization. 

So even if I track all file upload progresses in network layer I don't see nice way to match these progresses with particular committed mutations.

Any suggestions?
