### ISSUE TITLE
_graphql.Source is not a function

### ISSUE THREAD

**Issue by raymondsze** [facebook/relay#805]
I follow the instruction and tried relay-treasurehunt.
The build is ok, but when I point my browser to localhost:3000
I got 3 network errors.
POST http://localhost:3000/graphql 500 (Internal Server Error)
The response is 
{
  "errors": [
    {
      "message": "_graphql.Source is not a function"
    }
  ]
}

**Comment by steveluscher** [comment]
Merging into #804.
