### ISSUE TITLE
hasOptimisticUpdate() Invariant Violation with graphql-js 0.4.17

### ISSUE THREAD

**Issue by enaqx** [facebook/relay#809]
I've same error described in #805. After manually update relay-treasurehunt package.json graphql to 0.4.17 it allows to query without error through GraphiQL. Despite that it still not working as app.

![Invaraiant Violation](https://monosnap.com/file/qJRaKP9YcYlnI2fw7lupGYGkOyff3E.png)

It produce invariant violation. getDataID requires object with `__dataID__` but receive id as you can see.

https://github.com/facebook/relay/blob/ecf643231ed550f6fff197396a1765f49079e3e5/src/store/RelayRecord.js#L91

**Comment by steveluscher** [comment]
Merging into #804.
