### ISSUE TITLE
Relay and websockets (real time web app)

### ISSUE THREAD

**Issue by hipertracker** [facebook/relay#81]
Can Relay somehow work with websockets instead of REST endpoints?

**Comment by fson** [comment]
Thanks for the question! See this answer in the wiki: https://github.com/facebook/relay/wiki/Frequently-Asked-Questions#can-i-use-websockets-instead-of-xhrfetch and the related discussion in https://github.com/facebook/relay/issues/51.

**Comment by josephsavona** [comment]
Please feel free to reopen if you have additional questions not covered in the wiki.
