### ISSUE TITLE
babel-relay-plugin broken in babel 6.5

### ISSUE THREAD

**Issue by billyjanitsch** [facebook/relay#812]
I'm not sure whether this is a bug on Babel or babel-relay-plugin's end, but the plugin fails to transpile `Relay.QL` occurrences in the latest Babel version.

You can reproduce this by cloning the relay-starter-kit and [bumping the Babel deps](https://github.com/relayjs/relay-starter-kit/blob/master/package.json#L12) to 6.5.

**Comment by steveluscher** [comment]
This should be fixed by virtue of this trickery: https://github.com/relayjs/relay-starter-kit/commit/f3025cee82eacc0fbfb66cec075b3691663d0b9f#diff-e56633f72ecc521128b3db6586074d2cR2

Give it a shot, and re-open this issue if you're still having trouble!

**Comment by billyjanitsch** [comment]
Unfortunately the `passPerPreset` option is still experimental -- it happens to work in this case because relay-starter-kit doesn't use the spread operator, but if you add a spread, there's currently no way to order the four presets to avoid getting `Unexpected token ...` :(

Btw, non-contributors can't re-open issues.
