### ISSUE TITLE
Empty connection when using an argument named status

### ISSUE THREAD

**Issue by ooflorent** [facebook/relay#814]
I am facing a really strange issue with connections. I have an object named `Blog` with a connection field named `posts` described as below:

```
type Blog : Node {
  id: ID!
  posts(kind: PostKind, status: PostStatus): BlogPostConnection
}

enum PostKind { PAGE, POST }
enum PostStatus { DRAFT, PUBLISHED }

type BlogPostConnection {
  edges: BlogPostEdge
}

type BlogPostEdge {
  cursor: ID!
  node: Post
}

type Post : Node {
  id: ID
  title: String
}
```

I've configured a container to fetch all posts from a specified blog:

```js
Relay.createContainer(Timeline, {
  initialVariables: {
    kind: "POST",
    status: "PUBLISHED",
  },
  fragments: {
    blog: () => Relay.QL`
      fragment on Blog {
        id
        posts(first: 10 kind: $kind status: $status) {
          edges {
            cursor
            node {
              title
            }
          }
        }
      }
    `
  }
})
```

Relay generates the following query:

```
query ActivityQuery($kind_0:PostKind,$status_1:PostStatus) {
  blog(id:"1") {
    ...F2,
    id
  }
}

fragment F0 on Post {
  id,
  title
}

fragment F1 on Blog {
  _posts1fGaxU:posts(first:10,kind:$kind_0,status:$status_1) {
    edges {
      cursor,
      node {
        ...F0,
        date,
        id
      }
    },
    pageInfo {
      hasNextPage,
      hasPreviousPage
    }
  },
  id
}

fragment F2 on Blog {
  ...F1,
  id
}
```

And variables:

```js
{
  "kind_0": "POST",
  "status_1": "PUBLISHED"
}
```

Playing the above query in GraphiQL returns the expected `Blog` and its posts. However when Relay runs it the fragment only contains the blog id.

```js
{"__dataID__":"QmxvZzox","id":"QmxvZzox"}"
```

What is really strange is that if I rename `$status` to `$statut` (_status_ in French) it works like a charm!

I suspect the variable to collide with some internal code. I added a break point in `getCallValue` before its final `return` and spot something weird. Here is what `variables` contains during the server fetch:

```js
// There is 2 calls to `getCallValue`.
// The first one before sending the query:
{kind: "POST", status: "PUBLISHED"}

// The second once the data is fetch:
{kind: "POST", status: 2}
```

Something internally has changed the value of `status`. I suspect this mutation to prevent Relay from hydrating the fragment with the connection result.

Other findings:

- Removing `status` from `initialVariables` solves the issue
- Setting `status` to `null` in `initialVariables` does not solve the issue

**Comment by josephsavona** [comment]
cc @wincent - who might have already changed internals to avoid this.

**Comment by ooflorent** [comment]
Here are the version of Relay tools I used:

- babel-relay-plugin@0.6.3
- react-relay@0.6.1
- react-router-relay@0.9.0

**Comment by josephsavona** [comment]
@ooflorent If possible, can you try your app on master? As I mentioned it should be fixed there.

**Comment by ooflorent** [comment]
@josephsavona I just did. The bug is still there.

**Comment by ooflorent** [comment]
@josephsavona I just did and the bug is no longer there. Thanks.

**Comment by josephsavona** [comment]
@ooflorent great, thanks for confirming :-)
