### ISSUE TITLE
Ideas: After migrating to Relay for the first time :)

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/relay#817]
Hey all, first off let me say thank you for working on this library with the awesome goal of making data on the frontend more declarative. After working with React, it's a breeze, and I was pretty excited to get Relay working for the app I'm working on.

I saw that people on the team mentioned welcoming ideas/feedback in new issues, so I wanted to write up a bunch of painpoints/issues that I ran into while getting started, hopefully some of the "new user mindset" can be useful. I'm going to split them up so it's easier to keep track of, but here's a list:

- [#818: Create a GraphQL schema introspector CLI?](https://github.com/facebook/relay/issues/818)
- [#819: Babel plugin should take a schema path from `.babelrc`?](https://github.com/facebook/relay/issues/819)
- [#820: Remove `viewer` confusion?](https://github.com/facebook/relay/issues/820)
- ~~[#821: Let loading state be handled by `render`?](https://github.com/facebook/relay/issues/821)~~
- [#822: Remove the `Route` concept?](https://github.com/facebook/relay/issues/822)
- ~~[#823: Allow static definitions on the actual components?](https://github.com/facebook/relay/issues/823)~~
- Remove the “Root Container” concept?
- ~~[#824: Simplify and encapsulate mutation calls?](https://github.com/facebook/relay/issues/824)~~
- [#825: Remove the mutation GraphQL specification requirements?](https://github.com/facebook/relay/issues/825)
- ~~[#826: Move “configs” to the GraphQL  #server?](https://github.com/facebook/relay/issues/826)~~
- Simplify fragments declaration?
- ~~Move away from the global singleton?~~
- Make the build-time logic opt-in?

Sorry if there's duplication, I looked through a lot of existing issues, but I probably missed some.

Some of these things might be no-brainers and already being worked on. Also, I'll admit, some of them might seem too drastic, or even not fully thought through (since I probably don't have full context on a lot of things yet), but figured I'd open them anyways for discussion.

Just for context: I was previously using Redux over REST, but I migrated to GraphQL and then Relay after running into lots of imperative data management issues with Redux weighing me down. The GraphQL piece is separate from (run alongside) the REST piece, instead of one consuming the other, and they both share the same DB calling modules.

Anyways, looking forward to discussing, and also seeing this library get more and more refined in the future. And thanks again!

**Comment by wincent** [comment]
Thanks, @ianstormtaylor. This is a very generous contribution of time and effort. Thanks for the feedback and analysis!

Some of these we've closed already to try and group together duplicated or overlapping concepts. I'll close this one too because we're trying to keep the open issues list down to a smaller number of aggregated, actionable issues. As we merge stuff together there will be backreferences to your original issues, but please feel welcome to add your commentary to the existing issues as you see fit.

Thanks once again for your (considerable) input! It's great.

**Comment by ianstormtaylor** [comment]
Sounds good, thanks!
