### ISSUE TITLE
Idea: Remove the `Route` concept?

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/relay#822]
One of the things I noticed while trying to understand “Routes” in the first place, was that they seemed very lightweight. So lightweight that I was wondering if they even needed to exist. We might instead be able to just combine their usage with Containers themselves.

For example, the first example in the docs uses a plain object as a Route, at which point it’s hardly anything special, it’s just a dictionary of options passed into a Root Container. The second example goes a step further, subclassing `Relay.Route`, but it seems like the only reason to do that is to get the error handling logic in `paramDefinitions`, which could be achieved in others ways.

The docs mention that `Routes must also define a string name.` but it’s unclear why this need exists, and I don’t think it’s ever mentioned again in the docs. I assume it’s for error handling too, but that too could be solved differently if it changing it allows for a simpler API?

Routes themselves seem like they'd rarely be re-used, and even if they were, why not just re-use the specific queries (via sharing them like regular functions) instead of needing an extra object to wrap them?

What if instead, containers could be declared with their own `queries` and `paramTypes` (renamed from `paramDefinitions` to match React’s naming scheme):

``` js
const Container = Relay.createContainer(Profile, {

  queries: {
    user: () => Relay.QL`
      query { user(id: $userId) }
    `,
  },

  paramTypes: {
    userId: Relay.ParamTypes.string.required // potentially unnecessary, but for consistency
  }

}
```

Instead of needing a `Route` object that throws without the proper parameters, that error handling logic can be taken on by the container itself, and the “Route” really is just a configuration dictionary at that point, hardly even needing a special name. Instead of passing in a `Route` to a `RootContainer`, the `RootContainer` could then just simply take `params={…}`:

``` jsx
<RootContainer Component={Thing} params={...} />
```

This is similar to the simplicity that libraries like [`react-router-relay`](https://github.com/relay-tools/react-router-relay) (which was very nice to get setup and remove the complexity of Relay) achieve for you by abstracting away the need to touch Routes or Root Containers.

**Comment by wincent** [comment]
This is great feedback, @ianstormtaylor. We've already taken some steps towards de-emphasizing routes, but there's still more that we can do. When we first designed them they were much closer to what developers typically thing of as "routes", and that's why we named them that way.

For an example of the direction we're headed, take a look at `RelayRenderer` ([here](https://github.com/facebook/relay/blob/master/src/container/RelayRenderer.js)), which dispenses with a route object much like you suggest, and instead takes a "query config". We haven't documented this yet, and it may continue to evolve, but our thinking is that this will replace `RelayRootContainer`.

**Comment by ianstormtaylor** [comment]
Totally get you on the initial naming since they were closer to routes back then. 

Side note: if moving to `QueryConfig` from `Route`, I think it would make sense to call them `variables` now instead of `params` to better match GraphQL's naming? (Looks like it's [sometimes referred to as `variables`](https://github.com/facebook/relay/blob/master/src/query-config/RelayQueryConfig.js#L49) and [sometimes as `params`](https://github.com/facebook/relay/blob/master/src/query-config/RelayQueryConfig.js#L47) on master.)

For the changes, it sounds like `RootContainer` is going to become `Renderer`, which makes total sense. And that `Route` is going to be `QueryConfig`. Curious to know what we gain from the `QueryConfig` being a separate object that you need to subclass, instead of just letting renderer take them directly:

```jsx
<Renderer 
  Component={View}
  queries={queriesObject}
  variables={paramsObject} />
```

(Tried to look through the source to answer that, but I don't think I understood it all.) It looks like it's basically just a really thin wrapper that lets you specify `prepareVariables`, and also a `params` dictionary that validates variables being required or not? I wonder if that's even worth keeping.

I was going to open a separate issue for this, but it seems like it's highly related, so I should just put it here...

I was wondering if there was a reason not to just let us put `queries` directly on containers like we already can with `fragments`. Following that logic, it could make sense to put the `params` validating there as well (as `variableTypes`), and even `prepareVariables` if it's needed:

```js
createContainer(View, {
  fragments: { ... },
  queries: { ... },
  variableTypes: {
    userId: Relay.Types.string.required // would allow for even better validation than just required, potentially
  },
  ...
})
```

Going even further, to arrive at something that's truly transparent to usage with React, if there was a way to invoke the renderer from inside the wrapped container, you could even just get components that fetch their own queries automatically so that you don't need any extra rendering logic:

```jsx
<View variables={...} />
```

But I don't know enough about rendering there (or server-side) to know if that's even possible. It would be really awesome if so though.

**Comment by wincent** [comment]
(Spring cleaning.) Closing due to staleness. In the new APIs and new core (parts of which are already landing on `master`, with more to come soon) the notion of "route" is much better separated from the Relay APIs, so I don't think there's anything further actionable here. Thanks for bring this up!
