### ISSUE TITLE
Idea: Allow static definitions on the actual components?

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/relay#823]
One of the most awesome parts of Relay is how it lets all of your components data requirements live right where the component itself is defined. I alluded to this a bit in the “removing routes” idea, but we could go even further along that line of thinking, and define the “relay bits” of logic as static properties on the `Component`s themselves, since they are already part of the component definition as far as the developer is concerned. 

It makes things feel even cleaner, and makes it feel more like just a thin layer on top of React that adds an additional layer of declarative-ness:

```js
class ProfilePicture extends React.Component {
    
  static fragments = {
    user: () => Relay.QL`
      fragment on User {
        profilePhoto(size: $size) {
          uri,
        },
      }
    `
  };
      
 render() {
    var user = this.props.user;
    var variables = this.props.relay.variables;
    return (
      <View>
        <Image 
          uri={user.profilePhoto.uri}
          width={variables.size} />
      </View>
    );
  }
      
}
    
const ProfilePictureContainer = Relay.createContainer(ProfilePicture)
```

This way `createContainer` doesn’t need to take an additional argument, and it just finds the relay-specific properties of the component itself, making everything defined in one place. If people used decorators, it becomes even terser and easier to read.

I wrote a small module that lets me do this in my own codebase, and it feels really nice to just think in terms of the components themselves defining their data.

**Comment by josephsavona** [comment]
We've debated this as well, but ultimately decided that these static annotations are properties of the container, not the component. We'd like to ensure that plain React components can continue to be used as-is without Relay, and to allow usage of basic Relay features without modification.

We appreciate the feedback, but ultimately this is enough of a stylistic choice that we're not likely to change without a strong reason. As you point out, it's easy to write this style and use an adapter function for `Relay.createContainer`.
