### ISSUE TITLE
Idea: Move the “configs” to the GraphQL server?

### ISSUE THREAD

**Issue by ianstormtaylor** [facebook/relay#826]
Another thing that was confusing was that the configuration for the effects of a mutation are all written and stored on the client, when they are tightly coupled to the what the mutation actually affects when run on the server. For something like:

```js
{
  type: 'NODE_DELETE',
  parentName: 'faction',
  parentID: this.props.ship.faction.id,
  connectionName: 'ships',
  deletedIDFieldName: 'destroyedShipID',
}
```

All of that seems like effect logic that the server is actual the root source of truth for. It seems like the only time that code would change would be when the mutation on the server changed. And with that in mind, it seems weird for every Relay client that is interacting with the server to have to rewrite that logic (or go to the trouble of sharing it in a separate library, in the case of a publicly consumed GraphQL/Relay API…)

Why not let the server opt-in to support Relay by passing back that information with the returned values of the mutation. Something like this inside the mutation resolver:

```js
return {
  faction: faction,
  relay: {
    type: 'NODE_DELETE',
    parentName: 'faction',
    parentID: faction.id,
    connectionName: 'ships',
    deleteIDFieldName: 'destroyedShipID'
  }
}
```

(Or even something more descriptive than `relay` since that logic seems pretty framework-agnostic, as long as it remains completely declarative.)

If we were able to move that logic to the server, the clients would become a lot simpler, and each new client wouldn’t have to reimplement the same “config” code that is inherent to the actions the server is performing itself, making it even easier to get started once you have a Relay-ready server implementation.

There’s a good chance I’m missing something here :)

I now see that other issues have been created with this thought: https://github.com/facebook/relay/issues/489 https://github.com/facebook/relay/issues/293 https://github.com/facebook/relay/issues/125. And that there's a meta issue summarizing them: https://github.com/facebook/relay/issues/538!

In https://github.com/facebook/relay/issues/125 @yuzhi alluded to `getConfigs` being needed for the optimistic responses to be implemented, and those are always going to be purely client-side I'd imagine, so that's a limitation. In that case, I think it would be great to get the server to contain the logic in the schema definition, and for the client to just use it (like it does with the Schema definition itself). 

If there was a way to augment GraphQL for this to all happen with introspection, that would seem to be the cleanest solution—as long as it doesn't muddy up GraphQL. Seems like a way of attaching metadata to a type or query or mutation isn't crazy. Otherwise, maybe there's a separate Relay schema that a server could implement to keep all of that logic in one place, and not require it to be reimplemented by each client.

**Comment by wincent** [comment]
Thanks for this, @ianstormtaylor. This is great feedback, and I see you've gone and found the related issues (like #538). I'll close this one out so that we don't have too much duplication, but I think your thoughts here are really valuable and I'll add a back-reference here so that we don't lose track of them.
