### ISSUE TITLE
Relay call renderFailure if network requests timeout

### ISSUE THREAD

**Issue by blatch** [facebook/relay#837]
No answer to this on SO (http://stackoverflow.com/questions/35312277/why-doesnt-relay-call-renderfailure-if-network-requests-timeout) so I guess it's a bug:

I've got a `renderLoading` function that shows a spinner. I've also got a `renderFailure` function that contains a button to let a user retry a failed request. Finally, my network layer is configured with timeouts and retry delays:
```
fetchTimeout: 10000,
retryDelays: [1000, 2000, 4000, 8000, 8000],
```
If I take my local graphql server offline and and load my app, the loading spinner spins. If I start my server, within a few seconds, data is loaded, so the retries are working.

However, if I only do 2 retries (`retryDelays: [1000, 2000]`), take my server offline, reload my app and wait, the loading spinner is never replaced by the retry button I've got in my `renderFailed` function. If I bring my server back online, no data is loaded, which shows that no retries are taking place, as expected.

Is this a bug or am I missing something? Why doesn't relay call `renderFailed` (which I've tested separately and it works) if all network requests timeout and there are no more retries to try?

**Comment by josephsavona** [comment]
Thanks for reporting this, it sounds like a bug possibly in the default network layer.

**Comment by edvinerikson** [comment]
You seem to have a typo `renderFailed` should be `renderFailure`. However I couldn't reproduce this.

**Comment by wincent** [comment]
Going to close this one due to inactivity. Please comment though if this is still an issue for you and we'll re-open it.
