### ISSUE TITLE
Connections Spec hasNextPage & hasPreviousPage inconsistent with implementation

### ISSUE THREAD

**Issue by fortruce** [facebook/relay#84]
The [Connections Specification](https://github.com/facebook/relay/blob/master/website/graphql/Connections.md#fields-2) states that `hasNextPage` of `PageInfo`:

> hasNextPage will be **true** if the client is paginating with first, and the server has determined that the client has reached the **end** of the set of edges defined by their cursors. More formally:

> HasNextPage(allEdges, before, after, first, last)
> 1. If first was not set, return false.
> 2. Let edges be the result of calling ApplyCursorsToEdges(allEdges, before, after).
> 3. **If edges contains more than first elements, return false.**
> 4. Return true.

(emphasis mine)

This description seems backwards, and does not reflect the [implementation](https://github.com/graphql/graphql-relay-js/blob/master/src/connection/arrayconnection.js#L46-L72):

```
  return {
    edges: edges,
    pageInfo: {
      startCursor: firstEdge.cursor,
      endCursor: lastEdge.cursor,
      hasPreviousPage: (firstEdge.cursor !== firstPresliceCursor),
      hasNextPage: (lastEdge.cursor !== lastPresliceCursor)
    }
  };
```

Instead, it should read:

> hasNextPage will be **true** if the client is paginating with first, and the server has determined that the client has **not** reached the end of the set of edges defined by their cursors. More formally:

> 1. ...
> 2. ...
> 3. If edges contains more than first elements, return **true**.
> 4. Return **false**

The same is true for `hasPreviousPage`.

**Comment by yuzhi** [comment]
cc @dschafer
