### ISSUE TITLE
babel-plugin-relay 0.7.0 ?

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#845]
Hi guys

I just noticed that you have released the `babel-relay-plugin` `0.7.0`.

But I thought the plan was to move on to the more common babel plugin naming `babel-plugin-relay`. I saw that you guys have already reserved the name but it is still an empty `1.0.0`.

When are you planning to move from `babel-relay-plugin` to `babel-plugin-relay`?

I think it is very confusing having both out there.

Cheers
Bernd

**Comment by josephsavona** [comment]
We reserved the name `babel-relay-plugin` because we will make the transition at some point, but for now `babel-relay-plugin` is the official plugin (as noted in the docs.) I'm going to close this for now since there's nothing actionable and we have separate PRs/issues tracking the rename.
