### ISSUE TITLE
Relay generating invalid query after using `setVariables`. Query lacks spread operator?

### ISSUE THREAD

**Issue by ryancole** [facebook/relay#861]
It's my first time using `setVariables`, so it's quite possible I'm doing something incorrectly and it's confusing Relay. With that said, I've got a React component, with a Relay container, that calls `setVariables` in response to a prop change. When I call `setVariables`, Relay dispatches a query that looks like the folliowing ...

```
query Routes($id_0: ID!) {
  node(id: $id_0) {
    session {
      ...F0
    }
  }
}

fragment F0 on Session {
  _myDiscussions3nz5K2: myDiscussions(ids: ["VGVhbTox"]) {
    id
  }
}
```

The GraphQL server responds with the following error ...

```
Cannot query field "session" on type "Node".
However, this field exists on "Viewer".
Perhaps you meant to use an inline fragment?
```

Now, in that query, the type of the node being queried is `Viewer`. It makes complete sense to me that the `Node` type does not have this field, so the error there is correct, but the type returned by that query is `Viewer` which does have the field. If this query had the spread operator on `Viewer` then perhaps it'd work. I'm not sure if this is an issue with Relay building an incorrect query, though, or if it's me doing something wrong.

Here is my component that calls `setVariables` ...

```js
import React from "react";
import Relay from "react-relay";
import {connect} from "react-redux";

function mapStateToProps(state) {
  return {
    discussionWindows: state.discussionWindows.toJS()
  };
};

@connect(mapStateToProps)
class FloatingDiscussionPane extends React.Component {
  componentWillReceiveProps(props) {
    const {discussionWindows} = this.props;
    if (props.discussionWindows != discussionWindows) {
      this.props.relay.setVariables({
        ids: props.discussionWindows
      });
    }
  }

  render() {
    return (
      <div>

      </div>
    );
  }
};

export default Relay.createContainer(FloatingDiscussionPane, {
  fragments: {
    session: () => Relay.QL`
      fragment on Session {
        myDiscussions(ids: $ids) {
          id
        }
      }
    `
  },
  initialVariables: {
    ids: []
  }
});
```

As mentioned earlier, it will call `setVariables` in response to a prop change. This component also uses Redux for some local state.

Some additional info is that when this component is first rendered it does not cause the invalid query. The invalid query open happens after the call to `setVariables`, in response to the prop change.

**Comment by josephsavona** [comment]
Thanks for the detailed bug report. To help us debug this, what is the original query that you used to fetch the data for this component?

**Comment by josephsavona** [comment]
Also, just to be sure: what version of relay are you using?

**Comment by ryancole** [comment]
Will respond with details in probably 30 minutes. I'm caught up in the middle of something. :(

**Comment by ryancole** [comment]
I'm using version `0.7.0`.

Hmm, well, I'm trying to see where it includes the fragment on `Session` that I am expecting, but I'm not seeing that fragment anywhere in the queries prior to that `setVariables`-forced query. I'm going to continue poking around. I just wanted to let you known that at the moment I'm not seeing the fragment included.

**Comment by ryancole** [comment]
Alright, so here's the query that runs when the component is first rendered. I'm not going to trim it down, just so that it's kept in original state. You can see the fragment on `Session` (F6) in there. This is the fragment from the Relay container above.

```
query Routes {
  viewer {
    id
    ...F7
  }
}

fragment F0 on Team {
  id
  name
}

fragment F1 on Team {
  id
  ...F0
}

fragment F2 on Team {
  id
  ...F1
}

fragment F3 on Team {
  id
  ...F2
}

fragment F4 on Account {
  username
  id
}

fragment F5 on Session {
  isAuthenticated
  myAccount {
    id
    ...F4
  }
}

fragment F6 on Session {
  _myDiscussions4jCocQ: myDiscussions(ids: []) {
    id
  }
}

fragment F7 on Viewer {
  teams {
    id
    ...F3
  }
  session {
    isAuthenticated
    ...F5
    ...F6
  }
  id
}
```

**Comment by josephsavona** [comment]
Great, thanks for confirming. I'm pretty sure I know what's causing this, will confirm tomorrow and hopefully send a PR to fix.

**Comment by ryancole** [comment]
Out of curiosity, what do you think causes it? I wouldn't mind getting more knowledge of the internals - I could take a look, too. If not too much trouble for you to explain, that is.

**Comment by josephsavona** [comment]
@ryancole Yeah, I'm also happy to explain more about how Relay works.

In this case, what's happening is that you're fetching some record:

```
query {
  viewer { # concrete type, id '123'
    # ... fields
    session { # concrete type, no id
      # ... fields
     }
  }
}
```

Because everything is a concrete type it's okay to query fields directly w/o conditioning on type (i.e. you don't need to do `viewer { ... on SomeType { session } }`). However when Relay tries to refetch `session`, it doesn't have an id, so it looks up the "path" to foo from the nearest node that does have an id, in this case the `viewer` record. It constructs a query:

```
node(id: "123") { ... }
```

And fills in everything that was on the path from node 123 down to session:

```
node(id: "123") {
  session {
    # ...
  }
}
```

Every part of this query is valid except the very first field: in the original query `session` was a direct field of a concrete type (so no need to condition), but now it's a direct field of an abstract type `Node` and isn't allowed. Relay should use its knowledge of the type of record 123 to construct the conditioning fragment and generate the correct:


```
node(id: "123") {
  ... on Viewer {
    session {
      # ...
    }
  }
}
```

The logic for handling this case is in [RelayQueryPath](https://github.com/facebook/relay/blob/master/src/query/RelayQueryPath.js#L125-L182) - the fix is to wrap the final [set of children](https://github.com/facebook/relay/blob/master/src/query/RelayQueryPath.js#L174-L178) in a fragment whose type is determined by looking it up in the store.

**Comment by ryancole** [comment]
Gotcha. Thanks for the explanation.

I think in my situation, it would make sense for me to just give `Session` an `id` field, which would allow Relay to query it directly, via `node`.

As far as the issue itself, I checked out the code and I think it may be above my head in terms of attempting a fix myself. I may give it a shot and then compare it to yours, because I'm sure I'll be a bit slow on mine. If this situation is indeed an issue, then at least my odd scenario pointed it out! :)

**Comment by josephsavona** [comment]
@ryancole yeah, an `id` on session is a good workaround.

**Comment by josephsavona** [comment]
@ryancole this is now fixed on master, i'm going to close out the issue. thanks again for reporting this :-)
