### ISSUE TITLE
Relay query readability

### ISSUE THREAD

**Issue by vladar** [facebook/relay#863]
This is a follow up for https://github.com/facebook/relay/issues/547 but my proposal is different. I am against dev mode as well, but what if Relay only renamed fragment if fragment doesn't have name in Container definition?

Say in following case Relay will generate name for fragment (as it does now):
```
fragment on MyType {
  a
  b
}
```

But in this case Relay will preserve original fragment name:
```
fragment MyFragment on MyType {
  a
  b
}
```

I realize that preserving original fragment name could produce conflicts when two components have same fragment names, but such errors would be obvious and very easy to fix for developers. 

I guess you could even raise an error (or warning) at static compile step if two components have fragment with same name.

This way every team could peek it's own style of dealing with fragment names. If you need short fragment aliases - don't set fragment names in your containers (they are useless right now anyway). But if you value readability of the query - just set fragment names. 

For us having readable queries is way more important than having shorter queries. Because debugging Relay-generated queries is very frustrating and time-consuming.

**Comment by josephsavona** [comment]
Thanks for filing this; this is really two issues in one. First is that it's hard to read the machine-generated queries, which we've optimized more for byte-size than we have for debugging. Second, there's the need to debug queries at all - please let us know when you encounter issues so we can also try to address these via documentation, fixes, etc.

As for printing readable queries, we'd like to keep the printed output as consistent and minimal as possible. However, a middle ground could be to offer a way to transform the current printer output into something more readable. If `printRelayOSSQuery` returned a nullable fragment map of printed fragment name -> original fragment name, then it would be possible to rewrite the printed query (swapping `...F0` for the corresponding name). You could use this in DEV, for example, to help debug. In production the map wouldn't be returned (hence making it nullable) to avoid the overhead of allocating this mapping.

@yungsters thoughts?

**Comment by vladar** [comment]
I had to debug Relay queries in following situations:

1. Some bugs in Relay. This doesn't happen often, but when it happens - you would want to isolate components that caused the bug, but mangled fragment names make it much harder than it could be.

2. Occasionally GraphQL server throws on some field and returns error. It may happen because of unexpected set of variables. Then you want to figure out which component produced these invalid variables, but mapping fragment name back to component is hard, so it requires more efforts to isolate the problem.

3. We use https://github.com/webonyx/graphql-php for GraphQL server and it is not always up-to-date with latest graphql-js features. So Relay may allow the query, but server fails and you need to debug it and sometimes adjust your component fragments.

In general, the experience is pretty much the same as not having source maps for javascript. 

> As for printing readable queries, we'd like to keep the printed output as consistent and minimal as possible.

Yeah, but with my proposal it would always be consistent. If you omit fragment name in container definition (and right now fragment names are useless anyway) - you always get the same behavior (same as now). 

But if you set fragment name you always get consistent queries with full fragment names - regardless of dev / production mode. And it is predictable - you get what you define.

I am pretty sure that some teams would strongly prefer non-optimized queries with original fragment names even on production - for debugging and analysis.

**Comment by josephsavona** [comment]
@yuzhi recently added an option where queries are printed with newlines/spacing in DEV mode. Might be worth also printing the fragment name in DEV too (plus the hashed prefix, which is necessary to distinguish multiple copies of the same fragment that may have different variables).

**Comment by wincent** [comment]
We're preparing [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable) for release soon, and with it we'll have statically generated, persistable queries. This will create new challenges and opportunities in terms of debuggability, logging, analysis, introspection etc. So I'm going to close this with the "relay 1" label and suggest that we open new issues for any specific ideas that we have for Relay 2.

Thanks for bringing this up @vladar!
