### ISSUE TITLE
Better support for consuming Relay components

### ISSUE THREAD

**Issue by clayallsopp** [facebook/relay#868]
We're running into problems sharing customizable Relay components between applications. Here's an example

```
// Profile and Headers are `RelayContainer`s
import { Profile, Header } from 'internal-ui-kit';

class CustomHeader extends Header {
  // ...
}

CustomHeader = Relay.createContainer(CustomHeader, {
  fragments: {
    user: () => Relay.QL`
      fragment on User {
        someCustomPropertyOnlyUsedByCustomHeader
      }
    `
  }
})

export class CustomProfile extends React.Component {
  render() {
    // Profile is implemented such that it either renders any subclass of Header or Header if none are provided
    return <Profile>
      <CustomHeader>
    </Profile>
  }
}
```

A problem arises because `Profile`'s query fragment has already been constructed statically:

```
Profile = Relay.createContainer(Profile, {
  fragments: {
    // Define a fragment with a name matching the `story` prop expected above
    user: () => Relay.QL`
      fragment on User {
        ${ Header.getFragment('user') }
      }
    `
  }
})
```

and has no knowledge of the query `CustomerHander` needs, so it can't be injected into the query (without jumping through some hoops). It would be ideal if Relay could handle this case better or construct the queries more automatically.

**Comment by clayallsopp** [comment]
cc @josephsavona what I mentioned IRL at react conf

**Comment by wincent** [comment]
Thanks for sharing this issue, @clayallsopp. We're working on getting [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable) ready for release, and that will have an entirely static query construction system, with all queries being built at compile time, and so the `Header.getFragment()` interpolation will go away, replaced with vanilla GraphQL fragment spreads (`...HeaderUserFragment` or some such). I'm going to close this and label it with the "relay 1" label. If there are still things that are painful to do under the new Relay 2 API then we should open a separate issue for that.
