### ISSUE TITLE
Relay starwars example got this error.

### ISSUE THREAD

**Issue by bfwg** [facebook/relay#870]
I tried to run starwars example and the graphql request timeout and giving me this error.
```
{
  "errors": [
    {
      "message": "Variable \"$names_0\" of type \"ID!\" used in position expecting type \"[String]\".",
      "locations": [
        {
          "line": 1,
          "column": 28
        },
        {
          "line": 1,
          "column": 57
        }
      ]
    }
  ]
}
```

**Comment by josephsavona** [comment]
Thanks for reporting this. Technically IDs/strings are equivalent, and a single string literal is valid at a location that accepts an array of strings. This suggests that a `ID!` should flow into `[String]` - 

@leebyron @dschafer can you confirm?

**Comment by steveluscher** [comment]
I cleaned up the examples for the release of [0.9.0](https://github.com/facebook/relay/releases/tag/v0.9.0). Give them a try!

**Comment by steveluscher** [comment]
We're in the middle of a little bit of a revert/unrevert situation, so if anyone wants to try the examples in the next 24 hours or so be sure to check out the v0.9.0 tag:

```
git clone git@github.com:facebook/relay.git
cd relay
git checkout tags/v0.9.0
```
