### ISSUE TITLE
404 in the todo example

### ISSUE THREAD

**Issue by aexmachina** [facebook/relay#88]
When I start the todo example (as per the README) is page is trying to communicate with the GraphQL server on port 3000, but I get a 404 because the GraphQL server is listening on port 8080.

**Comment by knowbody** [comment]
this should not happen. The application is running on [port 3000](https://github.com/facebook/relay/blob/master/examples/todo/server.js#L8) and the GraphQL server on 8080 which is fine.

Could you send the error you get in the terminal?

**Comment by yuzhi** [comment]
@aexmachina  Are you still having problems with the todo example?

**Comment by aexmachina** [comment]
`npm cache clean && rm -rf node_modules/ && npm install` fixed it. Thanks.
