### ISSUE TITLE
Babel Relay Plugin breaks with babel-core v6.6.0

### ISSUE THREAD

**Issue by Syynth** [facebook/relay#887]
Currently `babel-relay-plugin` checks for the existence of the `Plugin` field on the babel object passed to the plugin, and as of version 6.6.0, it is now a function which throws the error `Error: The (relay-query) Babel 5 plugin is being run with Babel 6.`. The Babel Relay plugin detects this function and runs in Babel 5 mode, which means this gets called and the whole thing bombs out. Or, at least that's my understanding after a quick glance at the code.

**Comment by josephsavona** [comment]
Thanks for reporting this. It sounds like the plugin needs to be updated - we'll get to this soon but contributions are also welcome :-)

**Comment by maggiben** [comment]
+1

**Comment by alexhawkins** [comment]
+1

**Comment by kassens** [comment]
Sorry about the delay here, I'm currently working on changing the internal flow to import the PRs. A quick fix is to change the babel version dependency to some 6.5 version.

**Comment by chirag04** [comment]
+1

**Comment by arvitaly** [comment]
+1

**Comment by chirag04** [comment]
@kassens `67b6957` fixes the problem for me in react-native.

**Comment by xsistens** [comment]
+1

**Comment by eugenehp** [comment]
@schickling what do you think of this https://github.com/relayjs/relay-starter-kit/pull/77 ?
