### ISSUE TITLE
Download link on website doesn't work

### ISSUE THREAD

**Issue by bikolya** [facebook/relay#907]
Download link on http://facebook.github.io/relay/ leads to 0.7.2 tag and get 404, but current version seems to be 0.7.1
https://github.com/facebook/relay/blob/master/website/src/relay/index.js#L63
https://github.com/facebook/relay/blob/c7df007066548f48dc1749119aefdb5d2cc176a7/website/core/SiteData.js

**Comment by NevilleS** [comment]
It looks like they pushed that tag about an hour ago: https://github.com/facebook/relay/releases/tag/v0.7.2

The download link works for me right now.

**Comment by kassens** [comment]
We were lagging with tagging the release. It should all work again now.
