### ISSUE TITLE
npm has 0.7.3 as the latest version

### ISSUE THREAD

**Issue by ryancole** [facebook/relay#912]
I just saw the 0.7.2 release come across. Checking npm shows 0.7.3, though. Is this a mistake?

**Comment by KyleAMathews** [comment]
Check github again, they made a new release :-)

**Comment by ryancole** [comment]
Still seeing 0.7.2 as the latest on Github. I don't see 0.7.3 anywhere. I'm just thinking it's an npm mistake?

**Comment by kassens** [comment]
Now it's also here, we we're getting a bit ahead of ourselves :)

See 45b1446097fce594d3a4f8bd0703364b58fef8fe
