### ISSUE TITLE
TodoMVC Example Bugs

### ISSUE THREAD

**Issue by seanabrahams** [facebook/relay#928]
There are 2 bugs in the TodoMVC example (that I've come across):

1) Completing/Uncompleting all todos does not generate the correct mutation query and thus the response does not include the correct data

![todomvcmarkall](https://cloud.githubusercontent.com/assets/44398/13618059/daf4756c-e536-11e5-8a5d-dc12810d5281.gif)

2) Completing a todo, then clicking on the filters in the footer does not properly show Active and Completed todos.

![todomvcmarkfilters](https://cloud.githubusercontent.com/assets/44398/13618062/de0806a6-e536-11e5-9313-6ee95b6c282a.gif)

Looking into both but still new to Relay. Thanks.

**Comment by josephsavona** [comment]
Thanks for reporting this. @steveluscher was looking into these just today.

**Comment by steveluscher** [comment]
You guys are quick! Fixed in #930.
