### ISSUE TITLE
"Relay only supports root fields with zero or one argument"

### ISSUE THREAD

**Issue by devknoll** [facebook/relay#94]
Totally understand this error for mutations (given the standard `INPUT_TYPE`), but I just got this on a root query in a route. Is this intended to apply to _all_ root queries, or just mutations?

In the mean time, I'll just refactor that query to take a single `input`, like mutations.

**Comment by josephsavona** [comment]
This is intended, as Relay needs to understand how the argument values of the root field correspond to the response values. We've solved this by limiting the flexibility of the root field, but it is possible that we could remove this limitation.

Can you describe an example use-case where multiple arguments would be valuable?

**Comment by devknoll** [comment]
In my situation, I have a route with two variables (`/:moduleSlug/:tutorialSlug`), both required to resolve the query. I was trying to pass them to a `tutorial(module: $module, tutorial: $tutorial)` root query.

The INPUT_TYPE seems like it will work for now, but not ideal. Let me know if you have another idea for how this could be solved.

**Comment by jardakotesovec** [comment]
How about lists and connections as root fields? That is also limited, right?

**Comment by devknoll** [comment]
Never mind, input objects don't work here either (`Unexpected arg kind: ObjectValue`)...

**Comment by yuzhi** [comment]
@devknoll this might be a bit hacky, but have you tried getting that root query to take in a string and JSON.stringify the two variables? 

@jardakotesovec  Correct, connections can not be root fields at the moment. As @josephsavona  mentioned, we might be able to remove these limitations

**Comment by devknoll** [comment]
@yuhzi So, I think in my own case, I might just change my urls to be less hierarchical (they are getting ridiculous as is...). 

But lots of folks do use hierarchical urls, so it seems like a restriction worth removing, if possible.

**Comment by yuzhi** [comment]
See #112 for more detailed explanation.

**Comment by devknoll** [comment]
Thanks yuzhi. I'll close this one so the discussion can move there!
