### ISSUE TITLE
Any way to detect `nodeHasChange` ?

### ISSUE THREAD

**Issue by filod** [facebook/relay#948]
https://github.com/facebook/relay/blob/712f4b683cfed3cae61a201b39936803bc6fbd41/examples/TodoMVC/components/TodoList.js#L34
```javascript
const _todosDataSource = new ListView.DataSource({
  rowHasChanged: (r1, r2) => r1.__dataID__ !== r2.__dataID__,
});
```
when perform a mutation, `__dataID__` wouldn't change, so we can not see the updates when using ListView

**Comment by josephsavona** [comment]
Relay returns the same objects if there are no changes, and a new object when there are changes. I.e. If `prevProps.foo === nextProps.foo` there are no changes, if `!==` then something ha changed. This is also true for nested items, so you can compare prev/next sun-objects or array items. 

In summary: just compare 

    RowHasChanged: (r1,r2) => r1 !== r2
