### ISSUE TITLE
Not updating cache for mutation that adds many edges to connection

### ISSUE THREAD

**Issue by sgwilym** [facebook/relay#949]
Let's say you have one component displaying a list based on a connection with arguments e.g: 

```
iceCreamFlavours(onlyWithChocolate: true, noAddedPreservatives: true)
```

You also have a mutation, `AddIceCreamFlavours`, that adds multiple edges to that connection in a single go, with a FIELDS_CHANGE mutation on `iceCreamParlour`, in which case our fat query looks like this:

```
fragment on AddFlavourPayload {
  viewer {
    iceCreamParlour {
      iceCreamFlavours
    }
  }
}
```

The problem is that the connection field returned by the server, e.g `_iceCreamFlavours238yz9` is not going to match the ID of the connection field with the `onlyWithChocolate` and `noAddedPreservatives` arguments present, and so now the new flavours added by our mutation aren't going to be present, and therefore not visible to our users.
 
Is there any way around this, or is this something that will be tackled by #538?

**Comment by wincent** [comment]
Thanks for this, @sgwilym!

Related: #783 (multi-insert support) and #766 (mutations limited by only returning a single edge and cursor).

I think #538 will be the imminent relief for you here. I am currently implementing a lower-level mutations API that can be used to manually force the desired updates to take place when the current vanilla/auto-magic approach falls down. The idea is that the current API can be placed as a layer on top of the low-level API, but that you will also have the option of accessing it to do any stuff that doesn't fall into the standard patterns that the high-level API supports.

Going to close this one for now as I think the need you've expressed here is already covered in those other issues.
