### ISSUE TITLE
Allow for async getSchema in babel plugin

### ISSUE THREAD

**Issue by grydstedt** [facebook/relay#95]
It would be very handy if getSchema (https://github.com/facebook/relay/blob/master/scripts/babel-relay-plugin/src/getBabelRelayPlugin.js#L198) could accept a promise/async function for schemaProvider. 
That way we wouldn't have to rebuild the schema into a file and read from it. Instead it could just be done on the fly.

Thanks!

**Comment by steveluscher** [comment]
I like where you're trying to take this! I plan on taking this on as part of relayjs/relay-starter-kit#13.

**Comment by grydstedt** [comment]
Awesome!

**Comment by josephsavona** [comment]
This is a great idea, but babel transforms files synchronously, so the schema must also be available synchronously when the plugin is used. The way around this is to load the schema (asynchronously) first, and *then* compile via babel.

**Comment by josephsavona** [comment]
I'm closing this due to the synchronous limitation and because @steveluscher is tracking `babel-relay-plugin` updates at relayjs/relay-starter-kit#13.
