### ISSUE TITLE
UMD build

### ISSUE THREAD

**Issue by DomKM** [facebook/relay#962]
Would you consider providing UMD builds of `babel-relay-plugin` and `graphql-js`? These UMD builds, along with [`babel-standalone`](https://github.com/Daniel15/babel-standalone), will make Relay a viable tool in non-Node environments. It will also partially address https://github.com/facebook/relay/issues/828 without the need for refactoring `babel-relay-plugin`.

**Comment by josephsavona** [comment]
We'll consider this going forward. For now we're iterating on the core quite a bit and it's probably best to revisit after things calm down.
