### ISSUE TITLE
Q: Defining data requirement in Relay.Route?

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#97]
My understanding is that data requirements on Relay Containers are defined statically and are fetched regardless if component is shown. 

Therefore logic what data will be actually necessary has to be deduced in Relay.Route from the parameters - that might be coming from url parameters or some other context.

So I guess creating several Relay.Route objects covering different scenarios is way to go currently. I know that its obvious to use multiple Relay.Route when different views are shown. But I mean for example scenario when user is on  page with list of albums and clicks on one of them to see pop-up menu with songs list (which is kind of sub-route scenario). That could affect url (using react-router) that could switch to different Relay.Route object that would additionally call `getFragment` on that pop-up menu.

I noticed in examples that Relay.Route always just call `getFragment` on `Component` which is argument. But I assume that calling `getFragment` directly in Relay.Route also from other components is also reasonable? 

Does this approach make sense? Wondering if there are some other tricks how to conditionally change data requirement - and I mean decide whether data be fetched or not (for example based on the fact if pop-up menu is opened or not). 

Thanks!

**Comment by devknoll** [comment]
> But I assume that calling getFragment directly in Relay.Route also from other components is also reasonable?

At the moment, you can only have a single fragment in a route. You should also check https://github.com/facebook/relay/issues/20#issuecomment-130770234, because the `Component` argument is going away too.

Digging through the source code, you might be able to achieve what you're looking for using variables, doing something like this:

```js
var MyComponentContainer = Relay.createContainer(MyComponent, {
  initialVariables: {
    showPopup: false,
  },
  fragments: {
    album: (variables) => Relay.QL`fragment on Album {
      name,
      ${variables.showPopup ? SongList.getFragment('songs') : null}
    }``
  }
});
```

(note: untested, and I have no idea if this will be a supported feature)

**Comment by devknoll** [comment]
Another possibility would be to just use connections, and do something like:
```js
var MyComponentContainer = Relay.createContainer(MyComponent, {
  initialVariables: {
    songsToShow: 0,
  },
  fragments: {
    album: (variables) => Relay.QL`fragment on Album {
      name,
      songs(first: $songsToShow) {
        edges {
          node {
            ${SongList.getFragment('songs')}
          }
        }
      }
    }``
  }
});
```
and use `setVariables` again to grab the list.

**Comment by jardakotesovec** [comment]
These conditional fragments would be great pattern for these use cases.

```
   ${SongList.getFragment('songs').if(variables.showPopup)}
```

Could someone from fb please comment if thats pattern we can use at the moment/future?

Thanks

**Comment by josephsavona** [comment]
@jardakotesovec Sorry for missing this: yes, that will work. Obviously you'll want to check the value of `variables.showPopup` in your render code and skip rendering `<SongList>` when it's false, otherwise you'll get errors about missing data.

**Comment by josephsavona** [comment]
@jardakotesovec did that solution work for you? I'm going to close this issue since the question is answered, but feel free to reopen if you have any additional questions!
