### ISSUE TITLE
[Suggestion] Add jest tests to examples

### ISSUE THREAD

**Issue by note89** [facebook/relay#970]
I would be great have some guidelines on how to make tests when using relay. 
I suggest adding tests to at least the todoMVC example so people like myself can get an idea on how to go about doing tests.

**Comment by josephsavona** [comment]
This is a good idea - though it isn't immediately clear exactly what the tests would demonstrate. The best way to proceed here is probably to submit a pull request that demonstrates the general shape of the tests you think would be useful, and we and the community can help fill in details about how to implement them.

**Comment by josephsavona** [comment]
We're open to this, but we aren't likely to get to ourselves. Feel free to submit a PR though!
