### ISSUE TITLE
Docs copyright still reads 2015,

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/relay#975]
e.g. https://facebook.github.io/relay/docs/getting-started.html  

https://github.com/facebook/relay/blob/master/website/core/Site.js#L54

**Comment by wincent** [comment]
Thanks for bringing this up, but i think it was dealt with in 1fddf1f.

The website will get rebuilt and published when we cut the next release, so I'm going to close this one for now.

**Comment by kevinSuttle** [comment]
:+1:
