### ISSUE TITLE
[meta] "Extended" mutations API

### ISSUE THREAD

**Issue by NevilleS** [facebook/relay#978]
One thing I keep bumping up against is this issue where mutations have a somewhat limited vocabulary for expressing changes to the graph. Basically, the client needs to be able to "simulate" the mutation locally in order to be able to use the mutation API (i.e. what fields will change, which nodes will be deleted, which range will we add/remove from, etc.)

There exists a certain "category" of mutations that the client can't reasonably simulate; for example, ones where the change might cascade to an undetermined number of nodes (say, a "delete" operation that would decrement the friend count of a large number of User nodes).

A simple example of this would be anything with "random" server behaviour. Consider a "lottery" app with the following schema (pseudo-code):
```
query {
  node(id)
}
mutation {
  randomlySelectWinnerMutation
}
```

On the client, you might have a way to fetch a handful of Users (you know their IDs somehow), so you might have N user nodes in the local store. When you execute the `randomlySelectWinnerMutation`, how can you ever specify the correct `node` in a `FIELDS_CHANGE` mutation so that you update the correct User?

Furthermore, if multiple winners are selected, how can you specify that one or more nodes might need to be changed, without resorting to simply refetching *all* of them?

**Comment by NevilleS** [comment]
(accidentally posted the issue early, but here's an actual proposal)

For scenarios where the client can't really know what nodes might be affected by an operation, it seems impossible to declaratively construct the mutation query ahead of time. Therefore, I'd like to see a way for a mutation payload to include which nodes have been *affected* by the mutation, so the client can then elect to remove cached data for those nodes (or refetch that data immediately).

A mutation config might look something like this:
```
class RandomlySelectWinnerMutation extends Relay.Mutation {
  getMutation() {
    return Relay.QL`mutation { randomlySelectWinner }`
  }

  getFatQuery() {
    return Relay.QL `
      fragment on RandomlySelectWinnerMutationPayload {
        affectedNodeIDs
      }
    `
  }

  getConfigs(): Relay.MutationConfig[] {
    return [{
      type: "NODES_CHANGE",
      affectedIDsFieldName: "affectedNodeIDs"
    }]
  }
}
```

This mutation basically says "I don't really know what's going to happen, but the server will tell me which nodes I need to refetch". After the mutation runs, the Store could read the `affectedNodeIDs` which would be an array of IDs corresponding to the nodes that were mutated by the operation. If the Store has records for any of those IDs, it could either:
1. Remove them (if no observers currently exist)
2. Refetch them (if observers exist)

This seems like a "reasonable" compromise between doing a very imperative API (like `Relay.Store.expireNode(id)`) but also allows Relay to cover a broader category of mutations that the current configs can't really handle today.

Am I way off?

**Comment by wincent** [comment]
Thanks for (another!) high-quality mutations suggestion, @NevilleS. I'm doing some spring cleaning seeing as [Relay 2](https://speakerdeck.com/wincent/relay-2-simpler-faster-more-predictable) is under preparation now, and it will have a much more expressive, powerful API for expressing mutations. As such, I think it's best to close this for now. Thanks once again though!
