### ISSUE TITLE
prev/next pagination support for starting in the middle of a dataset

### ISSUE THREAD

**Issue by ddispaltro** [facebook/relay#983]
So I finally hacked around the hasPreviousPage and hasNextPage issues (see only one can be true depending on your direction).  I should have read the docs better, but I brute forced it.

So the next thing on my list was resuming from where I started.  I keep track of the cursor in the URL and if you reload the page then you come back to the spot your paginating on.  Keep in mind this is only supporting backwards and forwards buttons, not limit/offset/count (windowed) style.  However, if I try to go back I get an exception. `GraphQLRange cannot find a segment that has the cursor:`.  Also I added another field to the call to denote where you're starting from.  My backend also knows if there is a previous page.  Basically it looks for something >= or <= (depending on direction) cursor and if that ID exists it prunes and sets hasPreviousPage.

So then I started looking around at issues and found this: #403.  Does that mean that basically anyone doing anything more complicated than an infinite scrolling list, should just end up using there own?  I feel like I am trying to do something fairly simple, and I am so close, so I was looking for guidance, or to see if this intending to be fixed.

**Comment by ddispaltro** [comment]
Okay, I realized the exception is from basically changing the start parameter after the first page.  So now I keep it constant and the backend does the right thing, but it's not even making the call to /graphql when I try to go back before the start parameter.  I noticed #540 which @talon suggests just ditching the Connection, is that still the best plan?

**Comment by josephsavona** [comment]
Thanks for posting and searching for relevant existing issues. As you noted, our existing connection handling is cursor-based; because this is our primary use case the core team is unlikely to work directly on alternate forms of pagination. 

The simplest approach here is to use a plain list field with page/limit arguments as @taion suggested. What do you think about closing this issue and continuing discussion at #540?

**Comment by ddispaltro** [comment]
Sure
