### ISSUE TITLE
Mutations with fat query against union type

### ISSUE THREAD

**Issue by theorygeek** [facebook/relay#984]
I have a mutation that can be used to delete more than one type of item on my GraphQL server. When the item is deleted, I need Relay to remove the item from the connections that might include it.

To do that, I have my GraphQL server return a union, representing the parent of the item that was deleted. And since each parent uses a different name for the connection, the `getConfigs` is smart enough to know what connection will actually be used.

Here's what the code looks like:

``` js
getFatQuery() {
  return Relay.QL`
    fragment on DeleteFeedbackRemarkPayload {
      deletedRemarkId
      parent {
        ... on Employee {
          feedbackItems
        }

        ... on OneOnOne {
          comments
        }

        ... on FeedbackNote {
          comments
        }
      }
    }
  `
}

getConfigs() {
  const configs = []

  if (this.props.parentId) {
    const { modelType } = decodeId(this.props.parentId)
    configs.push({
      type: 'NODE_DELETE',
      parentName: 'parent',
      parentID: this.props.parentId,
      connectionName: modelType === 'Employee' ? 'feedbackItems' : 'comments',
      deletedIDFieldName: 'deletedRemarkId'
    })
  }

  return configs
}
```

The problem is that Relay generates an invalid query when it runs this mutation, which results in this error:

```
Selections can't be made directly on unions (see selections on EmployeeOrFeedbackNoteOrOneOnOne)
```

Here's the query that Relay is generating: (transcribed by hand)

```
mutation Delete($input_0:DeleteFeedbackRemarkInput!) {
  deleteFeedbackRemark(input:$input_0) {
    ...F3,
    clientMutationId,
    deletedRemarkId
  }
}

fragment F0 on Employee {
  id
}

fragment F1 on Employee {
  ...F0,
  id
}

fragment F2 on Employee {
  ...F1,
  id
}

fragment F3 on DeleteFeedbackRemarkPayload {
  parent {
    ...F0,
    ...F2,
    id
  }  
}
```

Notice that in fragment F3, it's querying for the `id` field of `parent`. But `parent` is a union, so any selections against it should be wrapped inside fragments.

As a workaround, I'm planning to change the field from a union to an interface. I'm not sure if this is an unsupported case, or if I'm doing something wrong.

**Comment by wincent** [comment]
Wonder if this is related to #782.

**Comment by NevilleS** [comment]
Seems pretty much identical, except the error in this case is that the node in the payload isn't a more specific type (e.g. `Feedback` but we have tracked queries against `Employee`), but in this case the payload is actually a union type.

Note that the "solution" in #782 of escaping tracked queries with a generic wrapper like `...on Node { ...on Employee { <original frag> } }` would probably still work here, though is the `Node` interface guaranteed to be implemented by the union type...

**Comment by felguerez** [comment]
I had a similar issue but was able to get the mutation working by removing the `parentName` field from `getConfigs`. I think this might break optimistic updates.

Wanted to note that the errors/warnings outputted from Relay were a bit confusing:

```
fragment on CreateNoteMutationPayload {
        note
        notable {
          ... on Prequalification {
            notes(first: 5) {
              edges {
                node {
                  id
                  body
                }
              }
            }
          }
          ... on Document {
            notes(first: 5) {
              edges {
                node {
                  id
                  body
                }
              }
            }
          }
        }
      }
```
This inline fragment on a union type (Notable) in `getFatQuery`  generated this message:

```
Error: Server request for mutation `Create` failed for the following reasons:

1. Selections can't be made directly on unions (see selections on Notable)
     notable {
     ^^^
```

Thinking this meant my MutationPayload was somehow returning my union type (Notable) I moved the inline fragments to the root of the MutationPayload, and of course received this message:

```
Fragment cannot be spread here as objects of type "CreateNoteMutationPayload" can never be of type "CoolObjectType"
```

**Comment by josephsavona** [comment]
Thanks for filing this issue and your patience as we address it. The recommended workaround to this issue is to use [`Relay.GraphQLMutation`](https://facebook.github.io/relay/docs/api-reference-relay-graphql-mutation.html#content) for mutations, which gives you complete control over the mutation query sent to the server.

**Comment by dorthwein** [comment]
Sorry to resurrect this - has there been any progress on allowing this?

**Comment by wincent** [comment]
@dorthwein: There is unlikely to be any further work done related to the old, fat-query-powered mutations implementation (although we're open to PRs from external contributors); the team is focused on shipping the new core, which features a brand new mutations API (see recent work on the `experimental` branch in this repo). In the meantime, `Relay.GraphQLMutation` is an alternative that you can use today, and which bypasses the fat-query machine, allowing you to explicitly specify whatever mutation query you desire.
