### ISSUE TITLE
Production Minified 204 Kb seems very large

### ISSUE THREAD

**Issue by adieuadieu** [facebook/relay#996]
When minified, the production build of Relay is just over 200Kb. This makes it somewhat difficult to use in an SPA where load time is important. Is there a way to build a smaller production build? Why is it so large in the first place?

**Comment by josephsavona** [comment]
The production build is a standalone version that has all its dependencies bundled in addition to Relay core. It's meant as a convenient way to get started with Relay, not as the most optimal distribution. We'd recommend creating a bundle containing React *and* Relay, which should be able to take advantage of shared utility libraries and be smaller than the total of the standalone production builds. 

We're also open to pull-requests that optimize the production build configuration.

**Comment by laszbalo** [comment]
If you send the minified file gzipped then effectively only about ~30K will be sent over the wire. You can also cache the file on the client. The 30K is an estimate, but generally speaking enabling compression is much more efficient in terms of file size/load time, than minification.

**Comment by kassens** [comment]
Since I don't see any real action items here, I'm going to close the issue. Making sure to compile as a production build and enable dead code elimination/minification in combination with compression should help reduce the size.
