### ISSUE TITLE
ToDo example installation fails: stream.js, ModuleNotFoundError: Cannot resolve 'file' or 'directory' ./RelayVariable

### ISSUE THREAD

**Issue by Lux44** [facebook/relay#998]
[npm-debug.zip](https://github.com/facebook/relay/files/192407/npm-debug.zip)

[23:02:39] Starting 'dist:min'...
\
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
 Error: ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./RelayVariable in C:\Users\andre\Desktop\relay01\relay\lib
 |
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! react-relay@0.7.3 build: `gulp`
npm ERR! Exit status 1
npm ERR! Failed at the react-relay@0.7.3 build script 'gulp'.
npm ERR! This is most likely a problem with the react-relay package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-relay
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-relay
npm ERR! There is likely additional logging output above.
-
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\andre\Desktop\relay01\relay\npm-debug.log
npm ERR! addLocalDirectory Could not pack C:\Users\andre\Desktop\relay01\relay to C:\Users\andre\AppData\Roaming\npm-cache\react-relay\0.7.3\package.tgz
npm ERR! addLocal Could not install C:\Users\andre\Desktop\relay01\relay
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! react-relay@0.7.3 prepublish: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-relay@0.7.3 prepublish script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && npm run build'.
npm ERR! This is most likely a problem with the react-relay package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-relay
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-relay
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by kassens** [comment]
This blames to a1a4d99cb698e1eed63d28f8291ef114115d515d which adds a reference to the internal only `RelayVariable`. @steveluscher would you mind taking a look? Maybe we need a fork or we can move `RelayVariable` to OSS?

**Comment by steveluscher** [comment]
A fix is coming! Thanks for reporting.
